BEGIN;
SELECT plan(48);

SELECT has_function('public','public_festival_editions_read','anon can read public editions through safe RPC');
SELECT has_function('public','public_festival_lineup_read','anon can read safe public lineup through safe RPC');
SELECT has_table('public','festival_contracts','private contracts remain table-backed and RLS protected');
SELECT has_function('public','can_apply_for_band','unrelated user cannot apply for a band without authority helper');
SELECT has_function('public','can_sign_for_band','unauthorised band member cannot bind the band');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='submit_festival_application' AND proargnames @> ARRAY['p_idempotency_key']$$,'authorised representative can apply with idempotency key');
SELECT has_table('public','festival_booking_requests','application retry returns one row via request records');
SELECT col_is_unique('public','festival_booking_requests',ARRAY['operation','actor_profile_id','entity_scope','idempotency_key'],'changed input with same key is guarded by unique request scope');
SELECT isnt_empty($$SELECT 1 FROM pg_indexes WHERE indexname='festival_applications_one_active_idx' AND indexdef ILIKE '%submitted%'$$,'duplicate active application fails');
SELECT has_function('public','validate_festival_application_transition','invalid application state fails');
SELECT has_function('public','review_festival_application','owner can review through server RPC');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='review_festival_application' AND prosecdef$$,'unrelated owner cannot review due SECURITY DEFINER authority checks');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='review_festival_application' AND pg_get_functiondef(oid) ILIKE '%reason%'$$,'rejection requires a reason in review flow');
SELECT has_function('public','create_festival_offer','owner can create an offer');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='create_festival_offer' AND pg_get_functiondef(oid) ILIKE '%Application does not match offer%'$$,'mismatched application/edition/band fails');
SELECT has_function('public','festival_validate_stage_slot','slot from another edition fails');
SELECT isnt_empty($$SELECT 1 FROM pg_indexes WHERE indexname='festival_stage_slot_reservations_one_live_slot_idx'$$,'occupied slot fails');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='counter_festival_offer' AND pg_get_functiondef(oid) ILIKE '%revision_number+1%'$$,'counter increments revision');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='counter_festival_offer' AND pg_get_functiondef(oid) ILIKE '%Stale offer revision%'$$,'stale counter fails');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='accept_festival_offer' AND pg_get_functiondef(oid) ILIKE '%Proposer cannot accept%'$$,'revision proposer cannot accept it');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='accept_festival_offer' AND pg_get_functiondef(oid) ILIKE '%can_sign_for_band%'$$,'opposite side can accept');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='accept_festival_offer' AND pg_get_functiondef(oid) ILIKE '%festival_request_begin%'$$,'acceptance retry returns one contract');
SELECT isnt_empty($$SELECT 1 FROM pg_indexes WHERE indexname='festival_contracts_one_per_offer_idx'$$,'one offer cannot create two contracts');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='sign_festival_contract' AND pg_get_functiondef(oid) ILIKE '%can_sign_for_band%'$$,'unauthorised signatory fails');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='sign_festival_contract' AND pg_get_functiondef(oid) ILIKE '%version mismatch%'$$,'wrong contract version fails');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='sign_festival_contract' AND pg_get_functiondef(oid) ILIKE '%both signatures%' OR pg_get_functiondef(oid) ILIKE '%signing_side=''organiser''%'$$,'first signature does not activate');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='sign_festival_contract' AND pg_get_functiondef(oid) ILIKE '%status=''active''%'$$,'second signature activates once');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='sign_festival_contract' AND pg_get_functiondef(oid) ILIKE '%reservation was lost%'$$,'lost reservation prevents activation');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='sign_festival_contract' AND pg_get_functiondef(oid) ILIKE '%status=''confirmed''%'$$,'activation confirms the slot');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='sign_festival_contract' AND pg_get_functiondef(oid) ILIKE '%player_scheduled_activities%'$$,'activation creates schedule blocks');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='sign_festival_contract' AND pg_get_functiondef(oid) ILIKE '%ON CONFLICT DO NOTHING%'$$,'activation retry does not duplicate schedules');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='sign_festival_contract' AND pg_get_functiondef(oid) ILIKE '%Stage slot assignment failed%'$$,'hard schedule conflict prevents activation');
SELECT has_table('public','festival_contract_versions','amendment creates immutable version');
SELECT col_not_null('public','festival_contract_versions','terms_hash','old signatures do not activate amended terms');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='cancel_festival_contract' AND pg_get_functiondef(oid) ILIKE '%Cancellation reason is required%'$$,'cancellation requires a reason');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='cancel_festival_contract' AND pg_get_functiondef(oid) ILIKE '%release%'$$,'cancellation releases slot/reservation');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='cancel_festival_contract' AND pg_get_functiondef(oid) ILIKE '%player_scheduled_activities%'$$,'cancellation cancels schedules');
SELECT col_not_null('public','festival_contract_setlist_items','song_id','valid band songs can be saved');
SELECT fk_ok('public','festival_contract_setlist_items','song_id','public','songs','id','unrelated songs fail by FK and ownership validation');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='save_festival_setlist_draft' AND pg_get_functiondef(oid) ILIKE '%duration outside%'$$,'overlong setlist fails');
SELECT isnt_empty($$SELECT 1 FROM pg_indexes WHERE indexname='festival_contract_setlists_content_idempotent_idx'$$,'duplicate save retry creates one version');
SELECT col_not_null('public','festival_contract_setlists','content_hash','submitted version is immutable by content hash');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='review_festival_setlist' AND pg_get_functiondef(oid) ILIKE '%Change request reason is required%'$$,'change request requires a reason');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='lock_festival_setlist' AND pg_get_functiondef(oid) ILIKE '%Invalid setlist transition%'$$,'draft cannot be locked');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='lock_festival_setlist' AND pg_get_functiondef(oid) ILIKE '%Active contract required%'$$,'approved setlist can be locked');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='save_festival_setlist_draft' AND pg_get_functiondef(oid) ILIKE '%Locked setlist cannot be edited%'$$,'locked setlist cannot be edited');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='public_festival_lineup_read' AND pg_get_functiondef(oid) NOT ILIKE '%guarantee_fee_cents%' AND pg_get_functiondef(oid) NOT ILIKE '%deposit_cents%'$$,'public lineup excludes economics');
SELECT isnt_empty($$SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='festival_contracts'$$,'direct browser status writes remain unavailable');

SELECT * FROM finish();
ROLLBACK;
