BEGIN;
SELECT plan(28);
SELECT has_function('public','public_festival_editions_read','public read function exists');
SELECT has_table('public','festival_applications','applications table exists');
SELECT has_table('public','festival_contract_offers','offers table exists');
SELECT has_table('public','festival_offer_revisions','offer revisions table exists');
SELECT has_table('public','festival_contracts','contracts table exists');
SELECT has_table('public','festival_contract_signatures','signatures table exists');
SELECT has_table('public','festival_contract_setlists','setlists table exists');
SELECT has_table('public','festival_contract_setlist_items','setlist items table exists');
SELECT has_table('public','festival_application_events','application events table exists');
SELECT has_table('public','festival_contract_events','contract events table exists');
SELECT has_view('public','public_festival_lineup','public lineup view exists');
SELECT col_not_null('public','festival_applications','edition_id','applications are edition scoped');
SELECT col_not_null('public','festival_contract_offers','offer_revision','offers track current revision');
SELECT col_not_null('public','festival_offer_revisions','terms_snapshot','revisions keep immutable terms');
SELECT col_not_null('public','festival_contracts','contract_version','contracts are versioned');
SELECT col_not_null('public','festival_contract_signatures','terms_hash','signatures hash terms');
SELECT col_not_null('public','festival_contract_setlists','total_duration_seconds','setlist totals persist');
SELECT isnt_empty($$SELECT 1 FROM pg_indexes WHERE indexname='festival_applications_one_active_idx' AND indexdef ILIKE '%WHERE%'$$,'duplicate active applications are constrained');
SELECT isnt_empty($$SELECT 1 FROM pg_indexes WHERE indexname='festival_contracts_stage_active_idx' AND indexdef ILIKE '%stage_slot_id%'$$,'slot reservation is exclusive');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='submit_festival_application'$$,'submit application RPC exists');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='counter_festival_offer'$$,'counter offer RPC exists');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='accept_festival_offer'$$,'accept offer RPC exists');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='sign_festival_contract'$$,'sign contract RPC exists');
SELECT isnt_empty($$SELECT 1 FROM pg_proc WHERE proname='save_festival_setlist_draft'$$,'setlist draft RPC exists');
SELECT throws_ok($$INSERT INTO public.festival_contract_offers(edition_id,band_id,guarantee_fee_cents) VALUES (gen_random_uuid(),gen_random_uuid(),-1)$$, NULL, NULL, 'negative offer economics rejected');
SELECT isnt_empty($$SELECT 1 FROM information_schema.routine_table_usage WHERE routine_name='public_festival_editions_read' AND table_name='festival_editions'$$,'public read is backed by editions');
SELECT isnt_empty($$SELECT 1 FROM information_schema.views WHERE table_schema='public' AND table_name='public_festival_lineup' AND view_definition NOT ILIKE '%guarantee_fee_cents%'$$,'public lineup excludes economics');
SELECT isnt_empty($$SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='festival_contract_signatures'$$,'signature data is protected by RLS');
SELECT * FROM finish();
ROLLBACK;
