-- Finance Phase 7.4 behavioural banking integration harness.
BEGIN;
SELECT plan(26);
SELECT has_function('public','post_financial_journal',ARRAY['public.financial_transaction_category','uuid','character','text','jsonb','text','uuid','jsonb'],'internal atomic journal primitive exists');
SELECT ok(EXISTS(SELECT 1 FROM information_schema.routine_privileges WHERE routine_schema='public' AND routine_name='post_financial_journal' AND grantee='service_role' AND privilege_type='EXECUTE'),'service role can execute journal primitive');
SELECT ok(NOT EXISTS(SELECT 1 FROM information_schema.routine_privileges WHERE routine_schema='public' AND routine_name='post_financial_journal' AND grantee IN ('authenticated','anon') AND privilege_type='EXECUTE'),'borrowers cannot call journal primitive directly');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='accept_loan_offer' ORDER BY oid DESC LIMIT 1) LIKE '%post_provider_loan_origination%','offer acceptance calls origination journal');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='accept_loan_offer' ORDER BY oid DESC LIMIT 1) NOT LIKE '%finance_transfer_accounts(provider_funding%','old direct principal transfer path removed');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='process_due_loan_repayments' ORDER BY oid DESC LIMIT 1) LIKE '%post_provider_loan_repayment%','scheduled processor calls repayment journal');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='process_due_loan_repayments' ORDER BY oid DESC LIMIT 1) NOT LIKE '%provider_receivable, total_due%','scheduled processor no longer sends whole payment to receivable');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='post_provider_loan_origination' ORDER BY oid DESC LIMIT 1) LIKE '%provider_equity%','origination uses provider equity offset');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='post_provider_loan_origination' ORDER BY oid DESC LIMIT 1) LIKE '%origination_fee%','origination fee is posted by journal');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='post_provider_loan_repayment' ORDER BY oid DESC LIMIT 1) LIKE '%interest_income%','interest reaches provider interest income');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='post_provider_loan_repayment' ORDER BY oid DESC LIMIT 1) LIKE '%fee_income%','fees reach provider fee income');
SELECT has_function('public','reconcile_loan_contract',ARRAY['uuid'],'loan-level reconciliation RPC exists');
SELECT ok(EXISTS(SELECT 1 FROM information_schema.views WHERE table_schema='public' AND table_name='banking_provider_reconciliation'),'provider reconciliation view exists');
SELECT ok(EXISTS(SELECT 1 FROM information_schema.views WHERE table_schema='public' AND table_name='loan_integrity_issues'),'integrity view exists');
SELECT ok(pg_get_viewdef('public.loan_integrity_issues'::regclass) LIKE '%loan_without_repayment_schedule%','restored missing schedule integrity check');
SELECT ok(pg_get_viewdef('public.loan_integrity_issues'::regclass) LIKE '%settlement_clearing_imbalance%','added settlement clearing integrity check');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='create_loan_application' ORDER BY oid DESC LIMIT 1) NOT LIKE '%GREATEST(avg_income%','income is not fabricated from product requirement');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='create_loan_application' ORDER BY oid DESC LIMIT 1) LIKE '%interval ''12 weeks''%','application income uses recent period');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='create_loan_application' ORDER BY oid DESC LIMIT 1) LIKE '%allowed_purposes%','invalid purpose is rejected');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='create_loan_application' ORDER BY oid DESC LIMIT 1) LIKE '%minimum_amount_minor%','invalid amount is rejected');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='create_loan_application' ORDER BY oid DESC LIMIT 1) LIKE '%minimum_term_months%','invalid term is rejected');
SELECT has_function('public','list_banking_providers',ARRAY[]::text[],'provider listing RPC exists');
SELECT has_function('public','get_loan_details',ARRAY['uuid'],'loan detail RPC exists');
SELECT has_function('public','get_loan_schedule',ARRAY['uuid'],'loan schedule RPC exists');
SELECT has_function('public','retry_loan_payment',ARRAY['uuid','uuid','text'],'manual repayment retry RPC exists');
SELECT ok((SELECT prosrc FROM pg_proc WHERE proname='get_banking_dashboard' ORDER BY oid DESC LIMIT 1) LIKE '%loan_schedule_lines%','dashboard reads exact next unpaid schedule line');
SELECT * FROM finish();
ROLLBACK;
