BEGIN;
SELECT plan(33);
SELECT has_table('public','festival_runtime_sessions','runtime sessions exist');
SELECT has_table('public','festival_runtime_days','runtime days exist');
SELECT has_table('public','festival_runtime_stages','runtime stages exist');
SELECT has_table('public','festival_runtime_performances','runtime performances exist');
SELECT has_table('public','festival_runtime_artist_checkins','artist check-ins exist');
SELECT has_table('public','festival_runtime_band_member_attendance','band attendance exists');
SELECT has_table('public','festival_runtime_staff_checkins','staff check-ins exist');
SELECT has_table('public','festival_runtime_supplier_checkins','supplier check-ins exist');
SELECT has_table('public','festival_runtime_ticket_admissions','admissions exist');
SELECT has_table('public','festival_runtime_attendance','capacity ledger exists');
SELECT has_table('public','festival_runtime_jobs','retry jobs exist');
SELECT has_table('public','festival_runtime_events','events exist');
SELECT has_table('public','festival_runtime_snapshots','recovery snapshots exist');
SELECT has_table('public','festival_runtime_requests','idempotency receipts exist');
SELECT has_table('public','festival_runtime_audit','audit exists');
SELECT has_function('public','prepare_festival_runtime',ARRAY['uuid','integer','uuid'],'atomic preparation RPC');
SELECT has_function('public','check_in_festival_artist',ARRAY['uuid','integer','uuid'],'artist check-in RPC');
SELECT has_function('public','check_in_festival_band_member',ARRAY['uuid','uuid','integer','uuid'],'band attendance RPC');
SELECT has_function('public','check_in_festival_staff',ARRAY['uuid','uuid','integer','uuid'],'staff check-in RPC');
SELECT has_function('public','check_in_festival_supplier',ARRAY['uuid','uuid','integer','uuid'],'supplier check-in RPC');
SELECT has_function('public','mark_festival_ready_to_open',ARRAY['uuid','integer','uuid'],'gate blocker RPC');
SELECT has_function('public','admit_festival_ticket',ARRAY['uuid','uuid','text','uuid'],'ticket admission RPC');
SELECT has_function('public','start_festival_performance',ARRAY['uuid','integer','uuid'],'performance start RPC');
SELECT has_function('public','resolve_festival_performance',ARRAY['uuid','integer','uuid'],'exactly-once resolution RPC');
SELECT has_function('public','record_festival_performance_delay',ARRAY['uuid','integer','integer','text','uuid'],'delay RPC');
SELECT has_function('public','pause_festival_runtime',ARRAY['uuid','integer','uuid'],'pause RPC');
SELECT has_function('public','place_festival_emergency_hold',ARRAY['uuid','integer','boolean','text','uuid'],'emergency RPC');
SELECT has_function('public','recover_festival_runtime',ARRAY['uuid','integer','uuid'],'recovery RPC');
SELECT has_function('public','process_due_festival_runtime_jobs',ARRAY['uuid','integer'],'concurrency-safe worker RPC');
SELECT lives_ok($$SELECT public.get_public_festival_live_status('does-not-exist')$$,'public live status is total');
SELECT is((SELECT count(*) FROM public.festival_runtime_sessions),0::bigint,'migration never silently creates runtimes');
SELECT is((SELECT count(*) FROM information_schema.role_table_grants WHERE table_schema='public' AND table_name LIKE 'festival_runtime_%' AND grantee IN('anon','authenticated') AND privilege_type IN('INSERT','UPDATE','DELETE')),0::bigint,'browser direct writes revoked');
SELECT throws_ok($$SELECT public.process_due_festival_runtime_jobs(NULL,50)$$,'P0001','festival_runtime_worker_forbidden','normal clients cannot process jobs');
SELECT * FROM finish();
ROLLBACK;
