import { useEffect } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { FESTIVAL_OUTCOME_QUERY_KEYS } from "./model";
import { calculateFestivalPerformanceOutcome, generateFestivalEditionAudience, getFestivalPerformanceNarrative, listFestivalHighlights, listFestivalSongOutcomes, listPublicFestivalPerformanceOutcomes, simulateFestivalCrowdMovement } from "./service";

export const usePublicFestivalOutcomes = (editionId?: string) => useQuery({ queryKey: FESTIVAL_OUTCOME_QUERY_KEYS.publicOutcomes(editionId ?? "all"), queryFn: () => listPublicFestivalPerformanceOutcomes(editionId) });
export const useFestivalSongOutcomes = (sessionId?: string) => useQuery({ queryKey: FESTIVAL_OUTCOME_QUERY_KEYS.songOutcomes(sessionId ?? ""), queryFn: () => listFestivalSongOutcomes(sessionId!), enabled: Boolean(sessionId) });
export const useFestivalHighlights = (sessionId?: string) => useQuery({ queryKey: FESTIVAL_OUTCOME_QUERY_KEYS.highlights(sessionId ?? ""), queryFn: () => listFestivalHighlights(sessionId!), enabled: Boolean(sessionId) });
export const useFestivalNarrative = (sessionId?: string) => useQuery({ queryKey: FESTIVAL_OUTCOME_QUERY_KEYS.narrative(sessionId ?? ""), queryFn: () => getFestivalPerformanceNarrative(sessionId!), enabled: Boolean(sessionId) });
export function useGenerateFestivalAudience(editionId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: () => generateFestivalEditionAudience(editionId, crypto.randomUUID()), onSuccess: () => qc.invalidateQueries({ queryKey: FESTIVAL_OUTCOME_QUERY_KEYS.editionAudience(editionId) }) }); }
export function useSimulateFestivalCrowd(editionId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (at: string) => simulateFestivalCrowdMovement(editionId, at, crypto.randomUUID()), onSuccess: () => qc.invalidateQueries({ queryKey: FESTIVAL_OUTCOME_QUERY_KEYS.stageCrowd(editionId) }) }); }
export function useCalculateFestivalOutcome(sessionId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: () => calculateFestivalPerformanceOutcome(sessionId, crypto.randomUUID()), onSuccess: (outcome) => { qc.invalidateQueries({ queryKey: FESTIVAL_OUTCOME_QUERY_KEYS.performanceOutcome(sessionId) }); qc.invalidateQueries({ queryKey: FESTIVAL_OUTCOME_QUERY_KEYS.songOutcomes(sessionId) }); qc.invalidateQueries({ queryKey: FESTIVAL_OUTCOME_QUERY_KEYS.effects(outcome.id) }); } }); }
export function useFestivalOutcomeRealtime(ids: { editionId?: string; sessionId?: string }) { const qc = useQueryClient(); useEffect(() => { if (!ids.editionId && !ids.sessionId) return; const channel = supabase.channel(`festival-outcomes:${ids.editionId ?? ids.sessionId}`).on("postgres_changes", { event: "*", schema: "public", table: "festival_stage_crowd_snapshots", filter: ids.editionId ? `edition_id=eq.${ids.editionId}` : undefined }, () => ids.editionId && qc.invalidateQueries({ queryKey: FESTIVAL_OUTCOME_QUERY_KEYS.stageCrowd(ids.editionId) })).on("postgres_changes", { event: "*", schema: "public", table: "festival_performance_highlights", filter: ids.sessionId ? `session_id=eq.${ids.sessionId}` : undefined }, () => ids.sessionId && qc.invalidateQueries({ queryKey: FESTIVAL_OUTCOME_QUERY_KEYS.highlights(ids.sessionId) })).on("postgres_changes", { event: "*", schema: "public", table: "festival_performance_outcomes", filter: ids.sessionId ? `session_id=eq.${ids.sessionId}` : undefined }, () => ids.sessionId && qc.invalidateQueries({ queryKey: FESTIVAL_OUTCOME_QUERY_KEYS.performanceOutcome(ids.sessionId) })).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [ids.editionId, ids.sessionId, qc]); }
