import {useEffect,useMemo,useRef,useState} from "react";
import {Alert,AlertDescription} from "@/components/ui/alert";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {useFestivalSitePlan} from "../application/useFestivalSitePlan";
import {useFestivalConfiguration} from "../application/useFestivalConfiguration";
import {useFestivalTicketPlan,useSaveFestivalTicketPlan} from "../application/useFestivalTicketPlan";
import {formatMinorMoney,parseMoneyToMinor,ticketPlanToDraft,type FestivalTicketPlanDraft,type FestivalTicketProduct} from "../domain/festivalTicketPlan";
import {previewTicketForecast} from "../domain/festivalTicketForecast";
import {validateFestivalTicketDraft} from "../domain/festivalTicketValidation";
const slug=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export function FestivalTicketPlanner({festivalCompanyId}:{festivalCompanyId:string}){const config=useFestivalConfiguration(festivalCompanyId),site=useFestivalSitePlan(festivalCompanyId),query=useFestivalTicketPlan(festivalCompanyId,site.data?.ready===true),save=useSaveFestivalTicketPlan();const [draft,setDraft]=useState<FestivalTicketPlanDraft|null>(null),[tab,setTab]=useState<"tickets"|"capacity"|"releases"|"forecast"|"review">("tickets"),[conflict,setConflict]=useState(false);const retry=useRef<{hash:string;key:string}|null>(null);useEffect(()=>{if(query.data)setDraft(ticketPlanToDraft(query.data))},[query.data]);const dates=query.data?.festivalDates??[];const initial=():FestivalTicketPlanDraft=>({ticketPlan:{id:null,currencyCode:"GBP",salesTaxRateBasisPoints:2000,bookingFeeMode:"none",bookingFeeMinor:0,bookingFeeBasisPoints:0,bookingFeePayer:"customer",refundPolicy:"",transferPolicy:"",minimumPurchaseQuantity:1,maximumPurchaseQuantity:8,expectedSellThroughBasisPoints:8000,expectedRefundBasisPoints:300,expectedComplimentaryUseBasisPoints:8000,expectedNoShowBasisPoints:500,status:"in_progress"},products:[],releasePhases:[],capacityAllocations:[]});const d=draft??initial();const issues=useMemo(()=>validateFestivalTicketDraft(d,dates,query.data?.usableSiteCapacity??1),[d,dates,query.data?.usableSiteCapacity]);const forecast=useMemo(()=>previewTicketForecast(d,dates,query.data?.usableSiteCapacity??1),[d,dates,query.data?.usableSiteCapacity]);const dirty=Boolean(draft&&query.data&&JSON.stringify(draft)!==JSON.stringify(ticketPlanToDraft(query.data)));useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};addEventListener("beforeunload",guard);return()=>removeEventListener("beforeunload",guard)},[dirty]);
 if(config.isLoading||site.isLoading)return <p role="status">Checking ticket-planning readiness…</p>;if(!site.data?.ready)return <Alert><AlertDescription>Complete Site and Stages before Tickets, Capacity and Forecast unlock.</AlertDescription></Alert>;if(query.isLoading)return <p role="status">Loading ticket plan…</p>;if(query.isError||!query.data)return <Alert variant="destructive"><AlertDescription>Ticket planning could not be loaded. Check your access and try again.</AlertDescription></Alert>;
 const patchProduct=(i:number,x:Partial<FestivalTicketProduct>)=>{const products=d.products.map((p,n)=>n===i?{...p,...x}:p);const changed=products[i];let capacityAllocations=d.capacityAllocations;if(x.capacityLimit!==undefined&&changed.productClass==="admission")capacityAllocations=dates.map(date=>({id:null,productId:changed.id,productSlug:changed.slug,festivalDate:date,capacityAllocated:x.capacityLimit!,capacityReserved:0,capacityComplimentary:0})).concat(d.capacityAllocations.filter(a=>a.productSlug!==d.products[i].slug));setDraft({...d,products,capacityAllocations})};const addProduct=(kind:"admission"|"add_on"="admission")=>{const name=kind==="admission"?"Full Festival":"Camping Add-on";setDraft({...d,products:[...d.products,{id:null,name,slug:slug(name+" "+(d.products.length+1)),ticketType:kind==="admission"?"full_festival":"camping",productClass:kind,accessScope:kind==="admission"?"full_festival":"non_admission",validFromDate:dates[0],validToDate:dates.at(-1)!,priceMinor:0,faceValueMinor:0,capacityLimit:0,minimumAge:null,includesCamping:kind==="add_on",includesParking:false,includesVipArea:false,includesBackstage:false,transferable:true,refundable:false,salePriority:d.products.length,active:true}]})};const persist=(complete=false)=>{if(save.isPending)return;const hash=JSON.stringify({d,complete});if(retry.current?.hash!==hash)retry.current={hash,key:crypto.randomUUID()};save.mutate({festivalCompanyId,expectedVersion:query.data.planningVersion,draft:d,idempotencyKey:retry.current.key,complete},{onSuccess:r=>{setDraft(ticketPlanToDraft(r));retry.current=null;setConflict(false)},onError:e=>setConflict(e.message==="festival_ticket_plan_stale")})};
 return <section className="mt-8 space-y-5" aria-labelledby="ticket-planning-title"><header><h2 id="ticket-planning-title" className="text-2xl font-bold">Ticketing and capacity planning</h2><p className="text-muted-foreground">Planning only — no tickets have been sold and no revenue has been earned.</p></header><nav aria-label="Festival setup phases" className="flex flex-wrap gap-2">{(["tickets","capacity","releases","forecast","review"] as const).map(x=><Button key={x} type="button" variant={tab===x?"default":"outline"} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</Button>)}<Button disabled title="Complete ticket planning first" variant="outline">Artists — locked</Button></nav>{conflict&&<Alert variant="destructive" role="alert"><AlertDescription>A newer ticket plan exists. Your local edits are preserved. Reload latest before saving.</AlertDescription></Alert>}
 {tab==="tickets"&&<div className="space-y-4"><div className="flex gap-2"><Button onClick={()=>addProduct()}>Add ticket product</Button><Button variant="outline" onClick={()=>addProduct("add_on")}>Add add-on</Button></div><ul className="space-y-4">{d.products.map((p,i)=><li key={p.slug} className="rounded border p-4 grid gap-3 sm:grid-cols-2"><div><Label htmlFor={`name-${i}`}>Product name</Label><Input id={`name-${i}`} value={p.name} onChange={e=>patchProduct(i,{name:e.target.value,slug:slug(e.target.value)})}/></div><div><Label htmlFor={`price-${i}`}>Price ({d.ticketPlan.currencyCode})</Label><Input id={`price-${i}`} inputMode="decimal" value={(p.priceMinor/100).toFixed(2)} onChange={e=>{const value=parseMoneyToMinor(e.target.value);if(value!==null)patchProduct(i,{priceMinor:value,faceValueMinor:value})}}/></div><div><Label htmlFor={`cap-${i}`}>Product allocation</Label><Input id={`cap-${i}`} type="number" min={0} value={p.capacityLimit} onChange={e=>patchProduct(i,{capacityLimit:Number(e.target.value)})}/></div><p>{p.productClass==="admission"?`Admission: consumes capacity on ${p.accessScope==="full_festival"?"every Festival day":"selected dates"}.`:"Add-on: does not consume admission capacity."}</p><Button variant="destructive" onClick={()=>confirm(`Remove ${p.name}?`)&&setDraft({...d,products:d.products.filter((_,n)=>n!==i)})}>Remove</Button></li>)}</ul></div>}
 {tab==="capacity"&&<div><h3 className="font-semibold">Daily capacity allocation</h3><p>Usable site capacity: {query.data.usableSiteCapacity.toLocaleString("en-GB")}. Multi-day admission allocations consume the same capacity on every covered date.</p><div className="grid gap-3">{dates.map(date=>{const rows=d.capacityAllocations.filter(a=>a.festivalDate===date),used=rows.reduce((s,a)=>s+a.capacityAllocated+a.capacityReserved+a.capacityComplimentary,0);return <article key={date} className="rounded border p-4"><h4>{date}</h4><p>{used} allocated · {query.data.usableSiteCapacity-used} remaining · {Math.round(used*100/query.data.usableSiteCapacity)}% utilised</p><progress value={Math.min(used,query.data.usableSiteCapacity)} max={query.data.usableSiteCapacity} aria-label={`${date} capacity utilisation`}/></article>})}</div></div>}
 {tab==="releases"&&<div><h3 className="font-semibold">Planned sales phases</h3><p>Release allocations are plans only and cannot place tickets on sale. The server rejects totals above their product allocation.</p>{d.releasePhases.length===0&&<p>No early release configured.</p>}</div>}
 {tab==="forecast"&&<div><h3 className="font-semibold">Planning forecast</h3><p>No tickets have been sold. Forecast values are not yet earned and are not accounting or legal advice.</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["Maximum ticket revenue",forecast.maximumAdmissionRevenueMinor],["Expected gross receipts",forecast.expectedGrossTicketReceiptsMinor],["Estimated tax",forecast.estimatedTaxMinor],["Expected booking fees",forecast.expectedBookingFeesMinor],["Expected refunds",forecast.expectedRefundsMinor],["Expected net receipts",forecast.expectedNetTicketReceiptsMinor]].map(([label,value])=><article className="rounded border p-4" key={label as string}><h4>{label}</h4><strong>{formatMinorMoney(value as number,d.ticketPlan.currencyCode)}</strong></article>)}</div></div>}
 {tab==="review"&&<div tabIndex={-1}><h3 className="font-semibold">Ticket-plan review</h3><p>{d.products.length} products · {d.releasePhases.length} planned phases · currency {d.ticketPlan.currencyCode}</p>{issues.length>0&&<Alert variant="destructive"><AlertDescription>{issues.length} blocking issue(s) must be resolved before completion.</AlertDescription></Alert>}<Button disabled={issues.length>0||save.isPending} onClick={()=>persist(true)}>Complete ticket planning</Button>{query.data.ready&&<p role="status">Ticket planning complete. Artist applications and booking can now be configured.</p>}</div>}
 <footer className="sticky bottom-2 flex items-center justify-between rounded border bg-background p-3"><span role="status">{save.isPending?"Saving…":dirty?"Unsaved changes":"Saved"}</span><Button disabled={save.isPending||!query.data.canWrite} onClick={()=>persist(false)}>Save ticket plan</Button></footer></section>}
