import {useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {useFestivalArtistAction,useFestivalArtistOpportunities} from "../application/useFestivalArtistWorkflows";
import type {FestivalArtistOpportunity} from "../domain/festivalArtistWorkflows";

const id=()=>crypto.randomUUID();
const value=(row:Record<string,unknown>,camel:string,snake:string)=>row[camel]??row[snake];
const message:Record<string,string>={FESTIVAL_APPLICATION_ALREADY_EXISTS:"This act already has an active application or invitation.",FESTIVAL_APPLICATION_WINDOW_CLOSED:"Applications are closed.",FESTIVAL_APPLICATION_DEADLINE_PASSED:"The application deadline has passed.",FESTIVAL_APPLICATION_ARTIST_INELIGIBLE:"This act does not currently meet the Festival requirements.",FESTIVAL_APPLICATION_INSUFFICIENT_SONGS:"This act needs more performance-ready songs.",FESTIVAL_APPLICATION_GENRE_MISMATCH:"This act's genre does not match this edition.",FESTIVAL_APPLICATION_SCHEDULE_CONFLICT:"This act has a scheduling conflict.",FESTIVAL_APPLICATION_VERSION_CONFLICT:"This application changed. Refresh and try again.",FESTIVAL_APPLICATION_ACCESS_DENIED:"You are not authorised to represent this act."};
const friendly=(error:unknown)=>message[error instanceof Error?error.message:""]??"The Festival could not complete that action. Please refresh and try again.";

export default function FestivalArtistOpportunitiesPage(){
 const q=useFestivalArtistOpportunities();const submit=useFestivalArtistAction("submitApplication");const withdraw=useFestivalArtistAction("withdrawApplication");const respond=useFestivalArtistAction("respondInvitation");
 const [search,setSearch]=useState("");const [band,setBand]=useState("");const [error,setError]=useState("");
 const run=async(action:()=>Promise<unknown>)=>{setError("");try{await action()}catch(e){setError(friendly(e))}};
 const opportunities=useMemo(()=>q.data?.openApplications.filter(x=>x.name.toLowerCase().includes(search.toLowerCase()))??[],[q.data,search]);
 if(q.isLoading)return <main className="mx-auto max-w-5xl p-4"><p>Loading Festival opportunities…</p></main>;
 if(q.isError||!q.data)return <main className="mx-auto max-w-5xl p-4"><h1 className="text-2xl font-bold">Festival opportunities</h1><p role="alert">Your Festival opportunity inbox is unavailable.</p></main>;
 const d=q.data;const identities=[...(d.permissions.canApplySolo?[{label:"Solo performer",type:"solo",profile:d.permissions.profileId,band:null}]:[]),...d.permissions.managedBandIds.map((bandId,index)=>({label:`Band ${index+1}`,type:"band",profile:null,band:bandId}))];const selected=identities.find(x=>(x.band??x.profile)===band)||identities[0];
 const apply=(o:FestivalArtistOpportunity)=>selected&&run(()=>submit.mutateAsync({p_festival_company_id:o.festivalCompanyId,p_application_window_id:o.windowId,p_artist_type:selected.type,p_artist_profile_id:selected.profile,p_band_id:selected.band,p_preferred_dates:[],p_preferred_stage_types:[],p_minimum_fee_minor:0,p_requested_fee_minor:0,p_minimum_set_minutes:30,p_maximum_set_minutes:60,p_message:null,p_idempotency_key:id()}));
 return <main className="mx-auto max-w-5xl space-y-5 p-4"><header><h1 className="text-3xl font-bold">Festival opportunities</h1><p className="text-muted-foreground">Discover editions, apply as an authorised act, and respond to invitations.</p></header>
  <div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1 text-sm">Search<Input aria-label="Search Festival opportunities" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Festival name"/></label><label className="space-y-1 text-sm">Apply as<select aria-label="Apply as" className="flex h-10 w-full rounded-md border bg-background px-3" value={selected?.band??selected?.profile??""} onChange={e=>setBand(e.target.value)}>{identities.map(x=><option key={x.band??x.profile??x.label} value={x.band??x.profile??""}>{x.label}</option>)}</select></label></div>
  {error?<p role="alert" className="text-sm text-destructive">{error}</p>:null}
  <Card><CardHeader><CardTitle>Open applications</CardTitle><CardDescription>{opportunities.length} opportunity(s)</CardDescription></CardHeader><CardContent className="grid gap-3">{opportunities.length===0?<p className="text-sm text-muted-foreground">Nothing here right now.</p>:opportunities.map(o=><article className="rounded-lg border p-3" key={o.windowId}><div className="flex flex-wrap items-center justify-between gap-2"><strong>{o.name}</strong><Badge variant={o.canApply&&o.eligibility?.eligible!==false?"secondary":"outline"}>{o.eligibility?.eligible===false?"Not eligible":"Open"}</Badge></div><p className="text-sm">Deadline: {new Date(o.closesAt).toLocaleString("en-GB")}</p>{o.preferredGenres.length?<p className="text-sm">Genres: {o.preferredGenres.join(", ")}</p>:null}{o.minimumFame!==null?<p className="text-sm">Minimum fame: {o.minimumFame}</p>:null}{o.eligibility?.reasons.map(r=><p className="text-sm text-destructive" key={r.code}>{message[r.code]??r.code.replaceAll("_"," ").toLowerCase()}</p>)}<Button className="mt-3" disabled={!selected||!o.canApply||o.eligibility?.eligible===false||submit.isPending} onClick={()=>apply(o)}>Apply</Button></article>)}</CardContent></Card>
  <Card><CardHeader><CardTitle>My applications</CardTitle><CardDescription>{d.applications.length} application(s)</CardDescription></CardHeader><CardContent className="grid gap-3">{d.applications.length===0?<p className="text-sm text-muted-foreground">No applications yet.</p>:d.applications.map(row=><article className="rounded-lg border p-3" key={String(row.id)}><div className="flex justify-between"><strong>Festival application</strong><Badge variant="secondary">{String(row.status)}</Badge></div>{["submitted","under_review"].includes(String(row.status))?<Button className="mt-3" variant="outline" disabled={withdraw.isPending} onClick={()=>run(()=>withdraw.mutateAsync({p_application_id:row.id,p_expected_version:value(row,"version","version"),p_idempotency_key:id()}))}>Withdraw</Button>:null}{value(row,"createdContractId","created_contract_id")?<Button asChild className="mt-3"><Link to={`/festival-contracts/${String(value(row,"createdContractId","created_contract_id"))}`}>Open contract</Link></Button>:null}</article>)}</CardContent></Card>
  <Card><CardHeader><CardTitle>Invitations</CardTitle><CardDescription>{d.invitations.length} invitation(s)</CardDescription></CardHeader><CardContent className="grid gap-3">{d.invitations.length===0?<p className="text-sm text-muted-foreground">No invitations right now.</p>:d.invitations.map(row=><article className="rounded-lg border p-3" key={String(row.id)}><div className="flex justify-between"><strong>Festival invitation</strong><Badge>{String(row.status)}</Badge></div>{["sent","viewed","invited"].includes(String(row.status))?<div className="mt-3 flex gap-2"><Button disabled={respond.isPending} onClick={()=>run(()=>respond.mutateAsync({p_invitation_id:row.id,p_expected_version:row.version,p_response:"accept",p_idempotency_key:id()}))}>Accept</Button><Button variant="outline" disabled={respond.isPending} onClick={()=>run(()=>respond.mutateAsync({p_invitation_id:row.id,p_expected_version:row.version,p_response:"decline",p_idempotency_key:id()}))}>Decline</Button></div>:null}</article>)}</CardContent></Card>
  {!identities.length?<p role="note">A leader, founder, co-leader or manager must take contractual actions for a band.</p>:null}<Button asChild variant="outline"><Link to="/gigs">Back to gigs</Link></Button>
 </main>;
}
