import {AlertTriangle,BriefcaseBusiness,ShieldCheck,Truck} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {useFestivalOperationsPlan,useSaveFestivalOperationsPlan} from "../application/useFestivalOperations";
import {formatFestivalMoney} from "../domain/festivalOperationsPlan";
export function FestivalOperationsPlanner({festivalCompanyId}:{festivalCompanyId:string}){
 const query=useFestivalOperationsPlan(festivalCompanyId);const save=useSaveFestivalOperationsPlan();
 if(query.isLoading)return <Card><CardContent className="p-6">Loading operational planning…</CardContent></Card>;
 if(query.isError)return <Card><CardHeader><CardTitle>Staffing and suppliers</CardTitle></CardHeader><CardContent>Complete artist planning to unlock Phase 5.</CardContent></Card>;
 const data=query.data!;const plan=data.operationsPlan;const currency=plan?.currencyCode??"GBP";
 const complete=()=>save.mutate({festivalCompanyId,expectedVersion:data.planningVersion,plan:plan?{staffBudgetMinor:plan.staffBudgetMinor,supplierBudgetMinor:plan.supplierBudgetMinor,contingencyBudgetMinor:plan.contingencyBudgetMinor,staffingMode:plan.staffingMode,procurementMode:plan.procurementMode}:{staffBudgetMinor:2_500_000,supplierBudgetMinor:5_000_000,contingencyBudgetMinor:750_000,staffingMode:"mixed",procurementMode:"mixed"},idempotencyKey:crypto.randomUUID(),complete:Boolean(plan)});
 return <section aria-labelledby="festival-operations-title" className="space-y-4"><div><h2 id="festival-operations-title" className="text-2xl font-semibold">Staffing, suppliers and operations</h2><p className="text-muted-foreground">Plan commitments and safety coverage. No wages or suppliers are paid in this phase.</p></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" aria-label="Operational readiness summary"><Metric icon={BriefcaseBusiness} label="Staffing coverage" value={`${data.qualityScores.staffingCoverageBasisPoints/100}%`}/><Metric icon={Truck} label="Supplier coverage" value={`${data.qualityScores.supplierCoverageBasisPoints/100}%`}/><Metric icon={ShieldCheck} label="Safety readiness" value={`${data.qualityScores.safetyReadinessScore}/100`}/><Metric icon={AlertTriangle} label="Operations score" value={`${data.qualityScores.overallOperationsScore}/100`}/></div>
 <Card><CardHeader><CardTitle>Operational budget</CardTitle></CardHeader><CardContent><dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Money label="Staff budget" value={data.budgetSummary.staffBudgetMinor}/><Money label="Supplier budget" value={data.budgetSummary.supplierBudgetMinor}/><Money label="Contingency" value={data.budgetSummary.contingencyMinor}/><Money label="Staff commitments" value={data.budgetSummary.staffCommitmentsMinor}/><Money label="Supplier commitments" value={data.budgetSummary.supplierCommitmentsMinor}/><Money label="Artist commitments (separate)" value={data.budgetSummary.artistCommitmentsMinor}/></dl></CardContent></Card>
 {data.issues.length>0&&<div role="alert" tabIndex={-1} className="rounded-md border border-destructive p-4"><h3 className="font-semibold">Readiness issues</h3><ul className="list-disc pl-5">{data.issues.map(issue=><li key={`${issue.code}-${issue.entityId}`}>{issue.code.replaceAll("_"," ")}{issue.blocking?" (blocking)":""}</li>)}</ul></div>}
 <div className="grid gap-3 md:grid-cols-2"><List title="Departments" items={data.departments}/><List title="Staffing requirements and vacancies" items={data.staffingRequirements}/><List title="Assignments and shifts" items={[...data.assignments,...data.shifts]}/><List title="Supplier requirements, quotes and contracts" items={[...data.supplierRequirements,...data.quotes,...data.contracts]}/></div>
 <Button className="min-h-11" disabled={save.isPending||!data.canWrite||data.readiness} onClick={complete}>{plan?"Complete staffing and supplier planning":"Generate operational requirements"}</Button>{data.readiness&&<p role="status" className="font-medium">Staffing and supplier planning complete. Sponsorship and final readiness preparation can now begin.</p>}
 </section>;
 function Money({label,value}:{label:string;value:number}){return <div><dt className="text-sm text-muted-foreground">{label}</dt><dd className="break-words font-semibold">{formatFestivalMoney(value,currency)}</dd></div>}
}
function Metric({icon:Icon,label,value}:{icon:typeof ShieldCheck;label:string;value:string}){return <Card><CardContent className="flex items-center gap-3 p-4"><Icon aria-hidden="true"/><div><p className="text-sm text-muted-foreground">{label}</p><p className="font-semibold">{value}</p></div></CardContent></Card>}
function List({title,items}:{title:string;items:Record<string,unknown>[]}){return <Card><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent><ul className="space-y-2">{items.length?items.slice(0,6).map((item,index)=><li className="rounded border p-3" key={String(item.id??index)}>{String(item.name??item.role_type??item.requirement_type??item.status??"Planned item")}</li>):<li className="text-muted-foreground">No items yet.</li>}</ul></CardContent></Card>}
