import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { festivalBookingKeys } from './bookingTypes';
import { getBandApplications, listOrganiserApplications, submitFestivalApplication, withdrawFestivalApplication, reviewFestivalApplication } from './applications';
import { acceptFestivalOffer, counterFestivalOffer, createFestivalOffer, declineFestivalOffer, listFestivalOffers } from './offers';
import { getFestivalContract, listBandContracts, signFestivalContract } from './contracts';
import { lockFestivalSetlist, reviewFestivalSetlist, saveFestivalSetlistDraft, submitFestivalSetlist } from './setlists';
export function useFestivalApplications(bandId?: string, editionId?: string, profileId?: string) { return useQuery({ queryKey: festivalBookingKeys.bandApplications(bandId, editionId, profileId), queryFn: () => getBandApplications(bandId!, editionId), enabled: Boolean(bandId) }); }
export function useFestivalApplicationActions(bandId?: string, editionId?: string) { const qc = useQueryClient(); const invalidate = () => qc.invalidateQueries({ queryKey: festivalBookingKeys.bandApplications(bandId, editionId) }); return { submitApplication: useMutation({ mutationFn: submitFestivalApplication, onSuccess: invalidate }), withdrawApplication: useMutation({ mutationFn: ({ applicationId, reason, idempotencyKey }: { applicationId: string; reason: string; idempotencyKey: string }) => withdrawFestivalApplication(applicationId, reason, idempotencyKey), onSuccess: invalidate }), reviewApplication: useMutation({ mutationFn: reviewFestivalApplication, onSuccess: () => qc.invalidateQueries({ queryKey: ['festivals','booking'] }) }) }; }
export function useOrganiserFestivalApplications(editionId?: string) { return useQuery({ queryKey: festivalBookingKeys.organiserApplications(editionId), queryFn: () => listOrganiserApplications(editionId!), enabled: Boolean(editionId) }); }
export function useFestivalOffers(bandId?: string, editionId?: string) { return useQuery({ queryKey: festivalBookingKeys.offers(bandId, editionId), queryFn: () => listFestivalOffers(bandId, editionId), enabled: Boolean(bandId || editionId) }); }
export function useFestivalOfferActions(bandId?: string, editionId?: string) { const qc = useQueryClient(); const invalidate = () => qc.invalidateQueries({ queryKey: festivalBookingKeys.offers(bandId, editionId) }); return { createOffer: useMutation({ mutationFn: createFestivalOffer, onSuccess: invalidate }), counterOffer: useMutation({ mutationFn: counterFestivalOffer, onSuccess: invalidate }), acceptOffer: useMutation({ mutationFn: ({ offerId, revision, idempotencyKey }: { offerId: string; revision: number; idempotencyKey: string }) => acceptFestivalOffer(offerId, revision, idempotencyKey), onSuccess: () => qc.invalidateQueries({ queryKey: ['festivals','booking'] }) }), declineOffer: useMutation({ mutationFn: ({ offerId, reason, idempotencyKey }: { offerId: string; reason: string; idempotencyKey: string }) => declineFestivalOffer(offerId, reason, idempotencyKey), onSuccess: invalidate }) }; }
export function useFestivalContracts(bandId?: string) { return useQuery({ queryKey: festivalBookingKeys.contracts(bandId), queryFn: () => listBandContracts(bandId!), enabled: Boolean(bandId) }); }
export function useFestivalContract(contractId?: string) { return useQuery({ queryKey: festivalBookingKeys.contracts(undefined, contractId), queryFn: () => getFestivalContract(contractId!), enabled: Boolean(contractId) }); }
export function useFestivalContractActions(contractId?: string) { const qc = useQueryClient(); return { signContract: useMutation({ mutationFn: signFestivalContract, onSuccess: () => qc.invalidateQueries({ queryKey: festivalBookingKeys.contracts(undefined, contractId) }) }) }; }
export function useFestivalSetlist(contractId?: string) { const qc = useQueryClient(); return { saveDraft: useMutation({ mutationFn: saveFestivalSetlistDraft, onSuccess: () => qc.invalidateQueries({ queryKey: festivalBookingKeys.setlist(contractId) }) }), submitSetlist: useMutation({ mutationFn: submitFestivalSetlist, onSuccess: () => qc.invalidateQueries({ queryKey: festivalBookingKeys.setlist(contractId) }) }), reviewSetlist: useMutation({ mutationFn: ({ setlistId, action, reason }: { setlistId: string; action: 'approve' | 'request_changes'; reason?: string }) => reviewFestivalSetlist(setlistId, action, reason), onSuccess: () => qc.invalidateQueries({ queryKey: festivalBookingKeys.setlist(contractId) }) }), lockSetlist: useMutation({ mutationFn: lockFestivalSetlist, onSuccess: () => qc.invalidateQueries({ queryKey: festivalBookingKeys.setlist(contractId) }) }) }; }
