import { Link } from "react-router-dom";
import { AlertTriangle, CheckCircle2, CircleDashed } from "lucide-react";
import { Badge } from "@/components/ui/badge";import { Button } from "@/components/ui/button";import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";import { Progress } from "@/components/ui/progress";
import { asArray, asObject, pct, statusTone } from "./managementUtils";
export function buildReadiness(ops: unknown){const r=asObject(ops);const stages=asArray(r.stages),slots=asArray(r.slots),staff=asArray(r.staff),permits=asArray(r.permit_requirements),quotes=asArray(r.insurance_quotes),policies=asArray(r.insurance_policies),ledger=asArray(r.ledger),sessions=asArray(r.performance_sessions);const filled=slots.filter(s=>s.reservation_id||s.band_id||s.system_act_id).length;const approvedPermits=permits.filter(p=>/approved|not_required/i.test(String(p.status))).length;return [
{key:"stages",label:"Stages",status:stages.length?"complete":"blocked",blocker:stages.length?null:"No stages created",warning:null,nextAction:stages.length?"Review stage capacities":"Create first stage",href:"#stages"},
{key:"slots",label:"Slots",status:slots.length? filled===slots.length?"complete":"warning":"blocked",blocker:slots.length?null:"No slots generated",warning:slots.length&&filled<slots.length?`${slots.length-filled} open slots`:null,nextAction:slots.length?"Fill open slots":"Generate schedule",href:"#stages"},
{key:"lineup",label:"Lineup",status:filled?"warning":"not_started",blocker:null,warning:filled?`${filled} assigned acts`:"No contracted acts",nextAction:"Review applications",href:"#lineup"},
{key:"staff",label:"Staff",status:staff.length?"warning":"blocked",blocker:staff.length?null:"No staff hired",warning:r.staffing_readiness?.missing_roles?.length?"Missing roles remain":null,nextAction:"Hire missing staff",href:"#staff"},
{key:"permits",label:"Permits",status:permits.length? approvedPermits===permits.length?"complete":"warning":"complete",blocker:null,warning:permits.length?`${approvedPermits}/${permits.length} approved`:"No permits required",nextAction:"Apply for permit",href:"#permits"},
{key:"insurance",label:"Insurance",status:policies.length?"complete":quotes.length?"warning":"blocked",blocker:policies.length?null:"No active policy",warning:quotes.length&&!policies.length?"Quotes awaiting purchase":null,nextAction:quotes.length?"Purchase insurance":"Request quotes",href:"#insurance"},
{key:"finance",label:"Finance",status:r.finance?.overdue_cents>0?"blocked":"warning",blocker:r.finance?.overdue_cents>0?"Overdue costs":null,warning:"Review budget",nextAction:"Resolve finance warning",href:"#finance"},
{key:"sessions",label:"Performance sessions",status:sessions.length?"complete":"not_started",blocker:null,warning:sessions.length?null:"No sessions projected",nextAction:"Open live operations",href:"#live"}];}
export function FestivalOperationalReadiness({operations, basePath=""}:{operations:unknown;basePath?:string}){const items=buildReadiness(operations);const ready=items.filter(i=>i.status==="complete").length;return <Card><CardHeader><CardTitle className="flex items-center justify-between">Operational readiness <Badge>{ready}/{items.length} ready</Badge></CardTitle></CardHeader><CardContent className="space-y-4"><Progress value={pct(ready,items.length)}/><div className="grid gap-3 md:grid-cols-2">{items.map(i=><div key={i.key} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2">{i.status==="complete"?<CheckCircle2 className="h-4 w-4 text-emerald-500"/>:i.status==="blocked"?<AlertTriangle className="h-4 w-4 text-destructive"/>:<CircleDashed className="h-4 w-4 text-amber-500"/>}<b>{i.label}</b></div><Badge variant={statusTone(i.status) as any}>{i.status.replace("_"," ")}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{i.blocker||i.warning||"No blockers reported."}</p><Button asChild size="sm" variant="outline" className="mt-3"><Link to={`${basePath}${i.href}`}>{i.nextAction}</Link></Button></div>)}</div></CardContent></Card>}
