import {describe,expect,it} from "vitest";
import {FESTIVAL_SPONSORSHIP_ERROR,formatSponsorshipMoney,parseFestivalSponsorContract,parseFestivalSponsorProposal,parseFestivalSponsorshipOpportunities,parseFestivalSponsorshipResult} from "../domain/festivalSponsorship";
const id="123e4567-e89b-42d3-a456-426614174000";
const summary=Object.fromEntries(["sponsorshipTargetMinor","minimumCashTargetMinor","contractedCashMinor","contractedInKindMinor","totalContractedValueMinor","pendingProposalCashMinor","pendingProposalInKindMinor","remainingTargetMinor","inventoryUtilisationBasisPoints","cashTargetProgressBasisPoints","playerSponsorShareBasisPoints","npcSponsorShareBasisPoints","adminSponsorShareBasisPoints","commercialReadinessScore"].map(k=>[k,0]));
const result={festivalCompanyId:id,operationsReadiness:true,sponsorshipPlan:{id,currencyCode:"GBP",sponsorshipTargetMinor:2500000,minimumCashTargetMinor:1000000,maximumInKindShareBasisPoints:4000,minimumPlayerCompanyShareBasisPoints:1000,applicationMode:"hybrid",publicApplicationsOpenAt:null,publicApplicationsCloseAt:null,status:"inventory_configured",planningVersion:1},categories:[],inventory:[],packages:[],prospects:[],applications:[],invitations:[],proposals:[],revisions:[],contracts:[],contributions:[],deliverables:[],brandingPlacements:[],commercialSummary:summary,issues:[],readiness:false,canWrite:true,planningVersion:1,updatedAt:null};
const opportunity={festivalCompanyId:id,festivalName:"Rock South",city:null,country:null,startDate:"2030-06-01",endDate:"2030-06-02",scale:"small",applicationDeadline:"2030-05-01T00:00:00Z",packages:[{id,name:"Gold",tier:"gold",minimumCashMinor:10000,permittedInKindShareBasisPoints:2500,targetIndustries:[],excludedIndustries:[]}],inventorySummary:[],eligibility:{canApply:true,reasonCodes:[]},companyAuthority:true,affordabilityCategory:"adequate_capacity",existingApplicationState:null,existingInvitationState:null,existingProposalState:null};
describe("Festival sponsorship contracts",()=>{
 it("strictly parses the canonical plan and commercial summary",()=>expect(parseFestivalSponsorshipResult(result).sponsorshipPlan?.currencyCode).toBe("GBP"));
 it("rejects malformed money, scores, versions, identities and statuses",()=>expect(()=>parseFestivalSponsorshipResult({...result,commercialSummary:{...summary,contractedCashMinor:-1}})).toThrow(FESTIVAL_SPONSORSHIP_ERROR));
 it("strictly parses safe opportunities and rejects private/malformed shapes",()=>{expect(parseFestivalSponsorshipOpportunities({items:[opportunity]})).toHaveLength(1);expect(()=>parseFestivalSponsorshipOpportunities({items:[{...opportunity,affordabilityCategory:"£1,000,000"}]})).toThrow("malformed_festival_sponsorship_opportunity_result")});
 it("parses proposals without whole-payload trust",()=>expect(parseFestivalSponsorProposal({id,sponsorSource:"player_company",status:"sent",currencyCode:"GBP",cashContributionMinor:10,inKindContributionMinor:0,proposalVersion:2,currentRevisionId:id,responseDeadline:"2030-01-01T00:00:00Z"}).status).toBe("sent"));
 it("rejects inconsistent contract totals",()=>expect(()=>parseFestivalSponsorContract({id,sponsorSource:"player_company",status:"committed",currencyCode:"GBP",cashContributionMinor:10,inKindContributionMinor:5,totalContributionMinor:99,contractVersion:1})).toThrow("malformed_festival_sponsor_contract_result"));
 it("uses en-GB currency formatting without truncation",()=>expect(formatSponsorshipMoney(2500000,"GBP")).toBe("£25,000.00"));
 it("keeps readiness locked until the server says complete",()=>expect(parseFestivalSponsorshipResult(result).readiness).toBe(false));
});
