import {describe,expect,it} from "vitest";
import {parseFestivalRuntimeCrowd,parseFestivalRuntimeIncident,parseFestivalStageCrowd,parseFestivalVendorSales} from "../domain/festivalRuntime";
const id="123e4567-e89b-42d3-a456-426614174000";
describe("Festival live operational contracts",()=>{
 it("parses server-owned stage crowds and enforces mood vocabulary",()=>{const crowd=parseFestivalStageCrowd({id,runtime_session_id:id,runtime_day_id:id,runtime_stage_id:id,current_crowd:900,stage_capacity:1000,crowd_share:.6,arrivals:40,departures:5,queue_size:0,mood:"excited",energy:80,satisfaction:75,safety_pressure:90,peak_audience:900,formula_version:"festival-crowd-v1",last_calculated_at:"2029-12-17T20:00:00Z",version:2});expect(crowd.currentCrowd).toBeLessThanOrEqual(crowd.stageCapacity);expect(()=>parseFestivalStageCrowd({...crowd,mood:"client_result"})).toThrow("malformed_festival_runtime")});
 it("keeps aggregate allocation explicit",()=>expect(parseFestivalRuntimeCrowd({id,runtime_session_id:id,runtime_day_id:id,admitted_count:1200,allocated_count:1000,unallocated_count:200,overall_mood:"engaged",energy:70,satisfaction:65,formula_version:"festival-crowd-v1",last_calculated_at:"2029-12-17T20:00:00Z",version:1}).unallocatedCount).toBe(200));
 it("separates public summaries from private operational detail",()=>{const incident=parseFestivalRuntimeIncident({id,runtime_session_id:id,runtime_day_id:id,runtime_stage_id:null,category:"medical",incident_type:"fan_illness",severity:"minor",trigger:"heat_pressure",status:"detected",required_response:"medical_team",public_safe_summary:"A guest is receiving assistance.",private_operational_details:"Zone reference for responders",formula_version:"festival-incident-v1",resolution_outcome:null,detected_at:"2029-12-17T20:00:00Z",resolved_at:null,version:1});expect(incident.publicSafeSummary).not.toContain("Zone")});
 it("preserves integer-minor sales and deferred liabilities",()=>{const sale=parseFestivalVendorSales({id,runtime_session_id:id,runtime_day_id:id,category:"artist_merch",product_name:"Tour shirt",currency_code:"GBP",opening_stock:10,remaining_stock:4,unit_price_minor:2500,units_sold:6,gross_revenue_minor:15000,tax_liability_minor:3000,cost_basis_minor:5000,waste_units:0,sold_out:false,status:"open",formula_version:"festival-vendor-v1",version:1});expect(sale.grossRevenueMinor).toBe(sale.unitPriceMinor*sale.unitsSold)});
});
