import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const app=fs.readFileSync("src/App.tsx","utf8");
const registry=fs.readFileSync("src/features/festivals/routes.ts","utf8");
const patterns=[...registry.matchAll(/^\s{2}(\w+): "([^"]+)",$/gm)].map(m=>({key:m[1],path:m[2]}));
const normalise=p=>p.replace(/:[^/]+/g,":parameter").replace(/\/$/,"");
test("canonical Festival registry has no semantic duplicates",()=>assert.equal(new Set(patterns.map(x=>normalise(x.path))).size,patterns.length));
test("every canonical Festival route is registered exactly once",()=>{for(const {key} of patterns){assert.equal([...app.matchAll(new RegExp(`path=\\{festivalRoutePatterns\\.${key}(?:\\.split\\("/"\\)\\.at\\(-1\\))?\\}`,"g"))].length,1,key)}});
test("legacy discovery redirects and owner routes resolve",()=>{assert.match(app,/path="festivals" element=\{<PreserveQueryRedirect/);assert.match(app,/path="festivals\/simulation" element=\{<PreserveQueryRedirect to=\{festivalRoutes\.publicDirectory\(\)\}/);for(const route of ["manage","calendar","run"])assert.match(app,new RegExp(`festivals/:festivalId/${route}`));assert.doesNotMatch(app,/festivals\/simulation[^\n]+LegacyFestivalGate/i)});
test("registry declares identifier semantics and typed builders",()=>{assert.match(registry,/festival_company_slug_or_uuid/);assert.match(registry,/normaliseRoutePattern/);assert.match(registry,/assertUniqueFestivalRoutePatterns/)});
