import {
  OutreachStage,
  OutreachTask,
  OutreachTaskStatus,
  PressRelease,
  PressReleaseStatus,
  MediaContact,
} from "@/types/publicRelations";

export const mockPressReleases: PressRelease[] = [
  {
    id: "pr-001",
    title: "Debut Album 'Neon Horizons' Announced",
    slug: "debut-album-neon-horizons-announced",
    summary: "Artist unveils debut album with a cross-country listening tour and exclusive vinyl release.",
    body: "The breakout artist is set to launch 'Neon Horizons' this fall, blending synth-pop with R&B influences.",
    releaseDate: "2024-08-15",
    status: PressReleaseStatus.Scheduled,
    heroImageUrl: "https://images.example.com/pr/neon-horizons.jpg",
    relatedAssets: ["press-kit", "album-cover", "tour-dates"],
    contactIds: ["contact-001", "contact-002"],
    createdAt: "2024-07-01T10:00:00Z",
    updatedAt: "2024-07-02T15:30:00Z",
  },
  {
    id: "pr-002",
    title: "Summer Festival Headline Slot Secured",
    slug: "summer-festival-headline-slot",
    summary: "Artist to headline the Sunset Fields Festival with immersive stage production and fan meetups.",
    body: "Headlining announcement includes interactive fan experiences and new stage visuals debuting this season.",
    releaseDate: "2024-07-28",
    status: PressReleaseStatus.Published,
    relatedAssets: ["festival-lineup", "press-photos"],
    contactIds: ["contact-003"],
    createdAt: "2024-06-12T09:00:00Z",
    updatedAt: "2024-06-20T11:45:00Z",
  },
];

export const mockMediaContacts: MediaContact[] = [
  {
    id: "contact-001",
    name: "Alex Ramirez",
    outlet: "Indie Sound Weekly",
    role: "Senior Editor",
    email: "alex.ramirez@indiesoundweekly.com",
    region: "North America",
    topics: ["album releases", "tours"],
    lastContactedAt: "2024-06-30T16:00:00Z",
  },
  {
    id: "contact-002",
    name: "Priya Das",
    outlet: "Global Beats Radio",
    role: "Host",
    email: "priya.das@globalbeats.fm",
    phone: "+1-555-123-4567",
    region: "Global",
    topics: ["interviews", "live sessions"],
    notes: "Interested in exclusive acoustic performances.",
  },
  {
    id: "contact-003",
    name: "Morgan Lee",
    outlet: "Festival Insider",
    role: "Staff Writer",
    email: "morgan.lee@festivalinsider.com",
    region: "North America",
    topics: ["festivals", "production"],
    lastContactedAt: "2024-06-10T13:30:00Z",
  },
];

export const mockOutreachTasks: OutreachTask[] = [
  {
    id: "task-001",
    title: "Send advance streaming link to Indie Sound Weekly",
    description: "Include private SoundCloud link and album liner notes.",
    pressReleaseId: "pr-001",
    contactId: "contact-001",
    stage: OutreachStage.Contacted,
    status: OutreachTaskStatus.InProgress,
    dueDate: "2024-07-05",
    priority: "high",
    createdAt: "2024-07-01T10:00:00Z",
    updatedAt: "2024-07-03T08:15:00Z",
  },
  {
    id: "task-002",
    title: "Schedule festival interview with Global Beats Radio",
    pressReleaseId: "pr-002",
    contactId: "contact-002",
    stage: OutreachStage.Negotiating,
    status: OutreachTaskStatus.Open,
    dueDate: "2024-07-10",
    priority: "medium",
    createdAt: "2024-06-22T12:00:00Z",
    updatedAt: "2024-06-22T12:00:00Z",
  },
  {
    id: "task-003",
    title: "Confirm headline coverage with Festival Insider",
    pressReleaseId: "pr-002",
    contactId: "contact-003",
    stage: OutreachStage.CoverageSecured,
    status: OutreachTaskStatus.Completed,
    dueDate: "2024-06-25",
    priority: "high",
    createdAt: "2024-06-15T09:00:00Z",
    updatedAt: "2024-06-26T09:30:00Z",
  },
];
