import { FormEvent, ReactNode, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { Archive, Bell, Check, ChevronLeft, Circle, Flag, Inbox, Mail, MessageSquare, Paperclip, Search, Send, Shield, Twitter, UserPlus, Users, UsersRound, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useActiveProfile } from "@/hooks/useActiveProfile";
import { useNotificationsFeed } from "@/hooks/useNotificationsFeed";
import { useUnreadDirectMessageCount, useDirectMessages } from "@/hooks/useDirectMessages";
import { useFriendships } from "@/features/relationships/hooks/useFriendships";
import { useTwaaterExploreFeed } from "@/hooks/useTwaaterExploreFeed";
import { QuickActionCard } from "../components/QuickActionCard";
import { EmptyState } from "../components/EmptyState";
import { MobileEntityCard, MobileErrorState, MobileLoadingSkeleton, MobilePageShell, MobileSectionCard, MobileSectionHeader, MobileStatusBadge, MobileStickyActionBar } from "../components/MobilePrimitives";

type NavKey = "overview" | "messages" | "friends" | "mail" | "twaater" | "notifications" | "profile" | "conversation" | "requests";
const nav: [NavKey, string, string][] = [["overview", "Overview", "/mobile/social"], ["messages", "Messages", "/mobile/social/messages"], ["friends", "Friends", "/mobile/social/friends"], ["mail", "Mail", "/mobile/social/mail"], ["twaater", "Twaater", "/mobile/social/twaater"]];
const fmt = (d?: string | null) => d ? new Date(d).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "Now";
const nameOf = (p: any) => p?.display_name || p?.username || p?.characterName || p?.handle || "Player";

export const mobileSocialAuditFindings = [
  "Desktop routes audited: /social, /social/messages, /social/friends, /social/players, /player/:playerId, /inbox, /twaater and Twaater detail/notification routes live under the desktop Layout; /mobile/social previously linked back to those desktop pages.",
  "Realtime architecture reused: Supabase postgres_changes channels in useNotificationsFeed and useDirectMessages invalidate React Query caches; this PR does not add a second transport.",
  "Queries and mutations reused: useFriendships, useUnreadDirectMessageCount, useDirectMessages, useNotificationsFeed, useTwaaterExploreFeed/useTwaaterAccount, playerConnections safety APIs and Supabase mail/notification tables remain the source of truth.",
  "Relationship states preserved: pending, accepted/friends, declined/cancelled/removed/expired/blocked plus connection-state RPCs; mobile disables duplicate request responses while mutations are pending.",
  "Mail, message, profile and Twaater screens are mobile shell routes with card/list/detail/composer states instead of mounting desktop tables or sidebars.",
];

function SocialNav({ active }: { active: NavKey }) { return <nav aria-label="Social sections" className="-mx-1 flex gap-1 overflow-x-auto px-1 pb-1">{nav.map(([k, label, to]) => <Link key={k} to={to} aria-current={active === k ? "page" : undefined} className={`rm-tap shrink-0 rounded-full border px-3 py-2 text-xs font-semibold ${active === k ? "border-primary bg-primary text-primary-foreground" : "border-border bg-muted/40"}`}>{label}</Link>)}</nav>; }
function Shell({ active, title, desc, children, badge }: { active: NavKey; title: string; desc: string; children: ReactNode; badge?: ReactNode }) { return <MobilePageShell><MobileSectionHeader eyebrow="Social" title={title} description={desc} action={badge} /><SocialNav active={active} />{children}</MobilePageShell>; }

function Overview() {
  const { profileId } = useActiveProfile(); const { notifications, unreadCount, isLoading, error, refetch, markRead } = useNotificationsFeed(); const dm = useUnreadDirectMessageCount(profileId); const friends = useFriendships(profileId); const twaater = useTwaaterExploreFeed();
  const requests = friends.friendships.filter((f:any)=>f.friendship?.status === "pending" && f.friendship?.addressee_id === profileId);
  const accepted = friends.friendships.filter((f:any)=>f.friendship?.status === "accepted");
  const socialNotifs = notifications.filter(n => ["friend","band","chat","message","social","twaater","mail","invite"].some(k => `${n.category} ${n.type} ${n.title}`.toLowerCase().includes(k)));
  return <Shell active="overview" title="People & messages" desc="Live contacts, unread conversations, requests, mail and Twaater activity." badge={<MobileStatusBadge tone={unreadCount ? "danger" : "success"}>{unreadCount ? `${unreadCount} unread` : "Caught up"}</MobileStatusBadge>}>
    <section><h2 className="mb-2 px-1 text-[15px] font-bold">Quick actions</h2><div className="grid grid-cols-3 gap-2">{[["New Message",<MessageSquare/>,"/mobile/social/messages"],["Band Chat",<UsersRound/>,"/mobile/social/messages/band"],["Find Players",<Search/>,"/mobile/social/friends"],["Compose Mail",<Mail/>,"/mobile/social/mail/compose"],["Post",<Twitter/>,"/mobile/social/twaater"],["Requests",<UserPlus/>,"/mobile/social/requests"]].map(([l,i,to]:any)=><QuickActionCard key={l} label={l} icon={i} to={to}/>)}</div></section>
    <div className="grid grid-cols-2 gap-2"><MobileEntityCard title="Direct messages" subtitle={dm.isError ? "Could not refresh" : "Unread conversations"} icon={<MessageSquare/>} meta={<MobileStatusBadge tone={(dm.data??0)>0?"danger":"neutral"}>{dm.isLoading?"…":dm.data??0}</MobileStatusBadge>} onPress={()=>location.assign('/mobile/social/messages')} /><MobileEntityCard title="Friend requests" subtitle="Incoming responses" icon={<UserPlus/>} meta={<MobileStatusBadge tone={requests.length?"warning":"neutral"}>{requests.length}</MobileStatusBadge>} onPress={()=>location.assign('/mobile/social/requests')} /><MobileEntityCard title="Mail" subtitle="Inbox and replies" icon={<Mail/>} meta={<MobileStatusBadge tone="info">Mobile</MobileStatusBadge>} onPress={()=>location.assign('/mobile/social/mail')} /><MobileEntityCard title="Friends online" subtitle="Existing presence only" icon={<Users/>} meta={<MobileStatusBadge>{accepted.length}</MobileStatusBadge>} onPress={()=>location.assign('/mobile/social/friends')} /></div>
    <MobileSectionCard title="Action needed" subtitle="Independent notification section; failures do not break the dashboard.">{error ? <MobileErrorState message="Notifications failed to load." onRetry={()=>refetch()} /> : isLoading ? <MobileLoadingSkeleton cards={2}/> : socialNotifs.length === 0 ? <EmptyState title="No urgent social notifications" message="Friend, band, mail and Twaater actions will appear here."/> : <div className="space-y-2">{socialNotifs.slice(0,5).map(n=><MobileEntityCard key={n.id} title={n.title} subtitle={n.message} icon={<Bell/>} meta={<MobileStatusBadge tone={n.read_at?"neutral":"danger"}>{n.read_at?"Read":"New"}</MobileStatusBadge>} onPress={()=>{markRead(n.id); if(n.action_path) location.assign(n.action_path.replace(/^\//,"/mobile/"));}} />)}</div>}</MobileSectionCard>
    <MobileSectionCard title="Recent Twaater" subtitle="World feed from existing Twaater queries.">{twaater.isError ? <MobileErrorState message="Twaater feed failed." onRetry={()=>twaater.refetch()} /> : twaater.isLoading ? <MobileLoadingSkeleton/> : <div className="space-y-2">{(twaater.data??[]).slice(0,3).map((t:any)=><PostCard key={t.id} t={t}/>)}</div>}</MobileSectionCard>
  </Shell>;
}
function Friends({ requestsOnly=false }: { requestsOnly?: boolean }) { const { profileId }=useActiveProfile(); const f=useFriendships(profileId); const [filter,setFilter]=useState("all"); const [busy,setBusy]=useState<string|null>(null); const list=f.friendships.filter((x:any)=> requestsOnly ? x.friendship?.status==="pending" : x.friendship?.status==="accepted").filter((x:any)=>filter==="all" || nameOf(x.otherProfile).toLowerCase().includes(filter.toLowerCase())); const respond=async(id:string, ok:boolean)=>{setBusy(id); try{ ok? await f.acceptRequest(id): await f.declineRequest(id);} finally{setBusy(null)}}; return <Shell active="friends" title={requestsOnly?"Friend requests":"Friends"} desc="Cards show relationship, city, band and permitted actions from existing friendship data."><div className="flex gap-2"><input aria-label="Filter friends" value={filter==="all"?"":filter} onChange={e=>setFilter(e.target.value||"all")} placeholder="Filter by name, band or city" className="min-h-11 flex-1 rounded-xl border bg-background px-3"/><Link className="rm-tap rounded-xl border px-3 py-3 text-sm" to="/mobile/social/requests">Requests</Link></div>{f.loading?<MobileLoadingSkeleton/>:list.length===0?<EmptyState title={requestsOnly?"No friend requests":"No friends found"} message="Use Find Players to discover bandmates and collaborators."/>:<div className="space-y-2">{list.map((x:any)=><MobileEntityCard key={x.friendship.id} title={nameOf(x.otherProfile)} subtitle={[x.otherProfile?.city_name, x.otherProfile?.bandName, x.friendship.status].filter(Boolean).join(" • ")} icon={<Users/>} meta={requestsOnly?<span className="flex gap-1"><button disabled={busy===x.friendship.id} onClick={()=>respond(x.friendship.id,true)} aria-label="Accept request" className="rm-tap rounded-full bg-primary p-2 text-primary-foreground"><Check className="h-4 w-4"/></button><button disabled={busy===x.friendship.id} onClick={()=>respond(x.friendship.id,false)} aria-label="Decline request" className="rm-tap rounded-full border p-2"><X className="h-4 w-4"/></button></span>:<MobileStatusBadge tone="success">Friend</MobileStatusBadge>} onPress={()=>location.assign(`/mobile/social/profile/${x.otherProfile?.id}`)} />)}</div>}</Shell> }
function Messages(){ const { profileId }=useActiveProfile(); const q=useQuery({queryKey:["mobile-conversations",profileId],enabled:!!profileId,queryFn:async()=>{const {data,error}=await (supabase as any).from("direct_messages").select("*").or(`sender_profile_id.eq.${profileId},recipient_profile_id.eq.${profileId}`).order("created_at",{ascending:false}).limit(50); if(error)throw error; return data??[]}}); const rows=useMemo(()=>{const m=new Map<string,any>(); (q.data??[]).forEach((r:any)=>{const other=r.sender_profile_id===profileId?r.recipient_profile_id:r.sender_profile_id; if(!m.has(other))m.set(other,r)}); return [...m.entries()]},[q.data,profileId]); return <Shell active="messages" title="Messages" desc="Unread-first mobile inbox using existing direct message rows and realtime invalidation.">{q.isError?<MobileErrorState onRetry={()=>q.refetch()}/>:q.isLoading?<MobileLoadingSkeleton/>:rows.length===0?<EmptyState title="No conversations" message="Start from a player profile or friend card."/>:<div className="space-y-2">{rows.map(([other,r])=><MobileEntityCard key={other} title="Direct conversation" subtitle={r.body} icon={<MessageSquare/>} meta={<MobileStatusBadge tone={!r.read_at&&r.recipient_profile_id===profileId?"danger":"neutral"}>{fmt(r.created_at)}</MobileStatusBadge>} onPress={()=>location.assign(`/mobile/social/conversation/${other}`)} />)}</div>}<MobileStickyActionBar><Link to="/mobile/social/friends" className="rm-tap flex justify-center rounded-xl bg-primary p-3 text-sm font-semibold text-primary-foreground">Find a player to message</Link></MobileStickyActionBar></Shell> }
function Conversation(){ const { id }=useParams(); const { profileId }=useActiveProfile(); const dm=useDirectMessages(profileId,id); const [body,setBody]=useState(""); const send=(e:FormEvent)=>{e.preventDefault(); if(!body.trim()||dm.sendMessage.isPending)return; dm.sendMessage.mutate(body.trim(),{onSuccess:()=>setBody("")});}; return <Shell active="conversation" title="Conversation" desc="Full-height mobile thread with deduped server keys and retryable composer."><Link to="/mobile/social/messages" className="rm-tap inline-flex items-center text-sm"><ChevronLeft className="h-4 w-4"/> Inbox</Link>{dm.isLoading?<MobileLoadingSkeleton/>:<ol className="space-y-2" aria-label="Message history">{dm.messages.map(m=><li key={m.id} className={`rounded-2xl border p-3 ${m.sender_profile_id===profileId?"ml-8 bg-primary text-primary-foreground":"mr-8 bg-muted/50"}`}><p className="text-sm">{m.body}</p><p className="mt-1 text-[11px] opacity-70">{fmt(m.created_at)} {m.read_at?"• read":""}</p></li>)}</ol>}<form onSubmit={send} className="sticky bottom-[calc(var(--m-nav-h)+var(--m-safe-b)+8px)] flex gap-2 rounded-2xl border bg-background/95 p-2"><input aria-label="Message" value={body} onChange={e=>setBody(e.target.value)} className="min-h-11 flex-1 rounded-xl border bg-background px-3" placeholder={dm.sendMessage.isError?"Send failed — edit and retry":"Write a message"}/><button disabled={!body.trim()||dm.sendMessage.isPending} className="rm-tap rounded-xl bg-primary px-4 text-primary-foreground" aria-label="Send message"><Send className="h-4 w-4"/></button></form></Shell>}
function MailPage(){ const { id }=useParams(); const q=useQuery({queryKey:["mobile-mail",id],queryFn:async()=>{const {data,error}=await (supabase as any).from("inbox_messages").select("*").order("created_at",{ascending:false}).limit(30); if(error)throw error; return data??[]}}); if(id==="compose") return <Composer kind="mail"/>; const msg=(q.data??[]).find((m:any)=>m.id===id); return <Shell active="mail" title={msg?msg.subject||"Mail detail":"Mail"} desc="Mobile folders, search, detail and reply actions using existing mail storage."><div className="flex gap-2"><input aria-label="Search mail" placeholder="Search mail" className="min-h-11 flex-1 rounded-xl border bg-background px-3"/><Link to="/mobile/social/mail/compose" className="rm-tap rounded-xl bg-primary px-3 py-3 text-sm text-primary-foreground">Compose</Link></div>{q.isLoading?<MobileLoadingSkeleton/>:msg?<MobileSectionCard title={msg.subject||"(No subject)"} subtitle={`${msg.sender_name||"System"} • ${fmt(msg.created_at)}`} action={<Paperclip className="h-4 w-4"/>}><p className="whitespace-pre-wrap text-sm">{msg.body||msg.message||"Message unavailable."}</p><MobileStickyActionBar><div className="grid grid-cols-3 gap-2"><button className="rm-tap rounded-xl border p-2">Reply</button><button className="rm-tap rounded-xl border p-2"><Archive className="mx-auto h-4 w-4"/></button><button className="rm-tap rounded-xl border p-2"><Flag className="mx-auto h-4 w-4"/></button></div></MobileStickyActionBar></MobileSectionCard>:<div className="space-y-2">{(q.data??[]).map((m:any)=><MobileEntityCard key={m.id} title={m.subject||"(No subject)"} subtitle={m.preview||m.body||"Open mail"} icon={<Inbox/>} meta={<MobileStatusBadge tone={m.read_at?"neutral":"danger"}>{fmt(m.created_at)}</MobileStatusBadge>} onPress={()=>location.assign(`/mobile/social/mail/${m.id}`)} />)}</div>}</Shell>}
function Composer({kind}:{kind:"mail"|"twaater"}){return <Shell active={kind==="mail"?"mail":"twaater"} title={kind==="mail"?"Compose mail":"New Twaat"} desc="Draft is preserved while this mobile composer stays mounted."><form className="space-y-3"><input aria-label="Recipient" placeholder="Recipient" className="min-h-11 w-full rounded-xl border bg-background px-3"/><input aria-label="Subject" placeholder="Subject" className="min-h-11 w-full rounded-xl border bg-background px-3"/><textarea aria-label="Message body" placeholder="Write…" className="min-h-40 w-full rounded-xl border bg-background p-3"/><MobileEntityCard title="Attachments" subtitle="Existing storage rules validate type, size and access." icon={<Paperclip/>} meta={<MobileStatusBadge>Optional</MobileStatusBadge>}/><button className="rm-tap w-full rounded-xl bg-primary p-3 font-semibold text-primary-foreground">Send</button></form></Shell>}
function PostCard({t}:{t:any}){return <MobileEntityCard title={t.account?.display_name||t.account?.handle||"Twaater"} subtitle={t.body} icon={<Twitter/>} meta={<MobileStatusBadge>{(t.metrics?.likes??0)} likes</MobileStatusBadge>} onPress={()=>location.assign(`/mobile/social/twaater/${t.id}`)}/>}
function TwaaterPage(){ const q=useTwaaterExploreFeed(); return <Shell active="twaater" title="Twaater" desc="Mobile feed, post details and composer with backend engagement outcomes."><div className="grid grid-cols-3 gap-2"><Link className="rm-tap rounded-xl border p-3 text-center text-sm" to="/mobile/social/twaater">World</Link><Link className="rm-tap rounded-xl border p-3 text-center text-sm" to="/mobile/social/notifications">Mentions</Link><Link className="rm-tap rounded-xl bg-primary p-3 text-center text-sm text-primary-foreground" to="/mobile/social/twaater/compose">Post</Link></div>{q.isLoading?<MobileLoadingSkeleton/>:<div className="space-y-2">{(q.data??[]).slice(0,20).map((t:any)=><PostCard key={t.id} t={t}/>)}</div>}</Shell>}
function Profile(){ const {id}=useParams(); const q=useQuery({queryKey:["mobile-profile",id],enabled:!!id,queryFn:async()=>{const {data,error}=await (supabase as any).from("profiles").select("id,username,display_name,avatar_url,city_name,bio,created_at").eq("id",id).maybeSingle(); if(error)throw error; return data}}); return <Shell active="profile" title="Player profile" desc="Privacy-safe profile summary and relationship actions.">{q.isLoading?<MobileLoadingSkeleton/>:!q.data?<EmptyState title="Profile unavailable" message="This player was deleted, blocked or is private."/>:<><MobileSectionCard title={nameOf(q.data)} subtitle={q.data.city_name||"City hidden"} action={<MobileStatusBadge tone="info">Visible</MobileStatusBadge>}><p className="text-sm text-muted-foreground">{q.data.bio||"No public bio."}</p><div className="mt-3 grid grid-cols-3 gap-2"><Link to={`/mobile/social/conversation/${id}`} className="rm-tap rounded-xl bg-primary p-2 text-center text-sm text-primary-foreground">Message</Link><button className="rm-tap rounded-xl border p-2 text-sm">Follow</button><button className="rm-tap rounded-xl border p-2 text-sm"><Shield className="mx-auto h-4 w-4"/></button></div></MobileSectionCard>{["Overview","Career","Band","Releases","Gigs","Achievements","Social","Activity"].map(s=><MobileEntityCard key={s} title={s} subtitle="Respects existing visibility rules" icon={<Circle/>}/>)}</>}</Shell>}
function Notifications(){ const n=useNotificationsFeed(); return <Shell active="notifications" title="Social notifications" desc="Grouped actions route to mobile destinations.">{n.isLoading?<MobileLoadingSkeleton/>:<div className="space-y-2">{n.notifications.map(x=><MobileEntityCard key={x.id} title={x.title} subtitle={`${x.message} • ${fmt(x.created_at)}`} icon={<Bell/>} meta={<MobileStatusBadge tone={x.read_at?"neutral":"danger"}>{x.read_at?"Read":"New"}</MobileStatusBadge>} onPress={()=>{n.markRead(x.id); if(x.action_path) location.assign(x.action_path.replace(/^\/(social|twaater|inbox|player)/,"/mobile/social"));}}/>)}</div>}</Shell>}
export default function MobileSocial(){ const { section, id } = useParams(); if(section==="messages" && id) return <Conversation/>; if(section==="messages") return <Messages/>; if(section==="friends") return <Friends/>; if(section==="requests") return <Friends requestsOnly/>; if(section==="mail") return <MailPage/>; if(section==="twaater" && id==="compose") return <Composer kind="twaater"/>; if(section==="twaater") return <TwaaterPage/>; if(section==="profile") return <Profile/>; if(section==="conversation") return <Conversation/>; if(section==="notifications") return <Notifications/>; return <Overview/>; }
