import { useState } from "react";
import { Link, useLocation, useParams } from "react-router-dom";
import { LineChart, MapPin, Plane, Ticket, Trophy } from "lucide-react";
import { useGameData } from "@/hooks/useGameData";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useCountryCharts } from "@/hooks/useCountryCharts";
import { EmptyState } from "../components/EmptyState";
import { MobileEntityCard, MobileLoadingSkeleton, MobilePageShell, MobileProgressCard, MobileSectionCard, MobileSectionHeader, MobileStatusBadge, MobileStickyActionBar, MobileTimeline, MobileTimelineItem } from "../components/MobilePrimitives";

const worldTabs = [["Overview","/mobile/world"],["City","/world/current-city"],["Travel","/mobile/world/travel"],["Festivals","/mobile/world/festivals"],["Charts","/mobile/world/charts"],["Companies","/world-companies"],["Marketplace","/gear-shop"]] as const;
function WorldNav(){ const {pathname}=useLocation(); return <nav aria-label="World sections" className="-mx-1 flex gap-1 overflow-x-auto px-1 pb-1">{worldTabs.map(([l,to])=>{const active=pathname===to||(to.startsWith('/mobile')&&pathname.startsWith(to)); return <Link key={to} to={to} aria-current={active?"page":undefined} className={`rm-tap shrink-0 rounded-full border px-3 py-2 text-xs font-semibold ${active?"border-primary bg-primary text-primary-foreground":"border-border bg-muted/40"}`}>{l}</Link>})}</nav> }
function Shell({title,description,children}:{title:string;description?:string;children:any}){return <MobilePageShell><MobileSectionHeader eyebrow="World" title={title} description={description}/><WorldNav/>{children}</MobilePageShell>}
const fmt=(d?:string)=>d?new Date(d).toLocaleString():"TBC";
export default function MobileWorldPhase5(){ const {section,id}=useParams(); if(section==="travel") return id?<JourneyDetail id={id}/>:<TravelMobile/>; if(section==="festivals") return id==="apply"?<FestivalApply/>:id?<FestivalDetailMobile id={id}/>:<FestivalsMobile/>; if(section==="charts") return id?<ChartDetail id={id}/>:<ChartsMobile/>; return <WorldOverviewMobile/> }
function WorldOverviewMobile(){ const {currentCity,activityStatus}=useGameData(); const travelling=String((activityStatus as any)?.activity_type??"").includes("travel"); return <Shell title={currentCity?.name??"Explore"} description="City, travel, festivals, charts and marketplace stay inside the mobile shell."><div className="grid grid-cols-4 gap-2">{worldTabs.slice(1).map(([l,to])=><Link key={l} to={to} className="rm-tap rounded-xl border p-2 text-center text-xs font-semibold">{l}</Link>)}</div><MobileSectionCard title="Where you are"><MobileEntityCard title={currentCity?.name??"No city loaded"} subtitle={currentCity?[currentCity.country,currentCity.region].filter(Boolean).join(" • "):"Travel data unavailable"} icon={<MapPin/>} meta={<MobileStatusBadge tone={travelling?"info":"neutral"}>{travelling?"Travelling":"Local"}</MobileStatusBadge>}/></MobileSectionCard></Shell> }
function TravelMobile(){ const {currentCity,activityStatus}=useGameData(); const q=useQuery({queryKey:["mobile-cities"],queryFn:async()=>{const {data,error}=await supabase.from("cities").select("id,name,country,region,population").limit(30); if(error) throw error; return data??[]}}); const active=String((activityStatus as any)?.activity_type??"").includes("travel"); return <Shell title="Travel" description="Destination browser, booking preview and active journeys without the desktop city table."><div className="grid grid-cols-2 gap-2"><MobileProgressCard label="Current city" value={currentCity?100:0} detail={currentCity?.name??"Unknown"}/><MobileProgressCard label="Active journey" value={active?65:0} detail={active?"In progress":"No active travel"}/></div><MobileSectionCard title="Quick actions"><div className="grid grid-cols-2 gap-2">{["Travel Now","Travel to Next Gig","View Route","Join Band Travel","View Tour","View Current Journey"].map(x=><button className="rm-tap rounded-xl border p-3 text-sm font-semibold" key={x}>{x}</button>)}</div></MobileSectionCard>{active&&<MobileSectionCard title="Active journey"><MobileEntityCard title="Current journey" subtitle="Departure, arrival, band members, equipment and linked tour are read from activity status." icon={<Plane/>} meta={<MobileStatusBadge tone="info">Travelling</MobileStatusBadge>} /></MobileSectionCard>}<MobileSectionCard title="Destination picker" subtitle="Search, filters and sorting should page server-side city results.">{q.isLoading?<MobileLoadingSkeleton cards={2}/>:q.data?.map((c:any)=><MobileEntityCard key={c.id} title={`${c.name}, ${c.country}`} subtitle={`Travel time and cost calculated by existing route rules · venues and events nearby`} icon={<MapPin/>} meta={<MobileStatusBadge>Preview</MobileStatusBadge>}/>)}</MobileSectionCard><MobileSectionCard title="Booking validation"><MobileTimeline>{["Past departures blocked","Unavailable transport blocked","Funds and schedule conflicts reviewed","Band or tour impact shown before confirmation"].map(x=><MobileTimelineItem key={x} title={x} detail="Existing travel booking and activity blockers remain authoritative."/>)}</MobileTimeline></MobileSectionCard></Shell> }
function JourneyDetail({id}:{id:string}){return <Shell title="Active journey"><MobileSectionCard title="Journey detail"><MobileTimeline>{["Origin","Destination","Transport","Departure time","Arrival time","Remaining duration","Route progress","Band members travelling","Equipment and crew","Linked gig or tour"].map(x=><MobileTimelineItem key={x} title={x} detail={`Existing journey field for ${id}`}/>)}</MobileTimeline></MobileSectionCard><MobileStickyActionBar><div className="grid grid-cols-3 gap-2"><button className="rounded-xl border p-2 text-xs font-semibold">Destination</button><button className="rounded-xl border p-2 text-xs font-semibold">Linked gig</button><button className="rounded-xl bg-primary p-2 text-xs font-semibold text-primary-foreground">Tour</button></div></MobileStickyActionBar></Shell>}
function FestivalsMobile(){ const q=useQuery({queryKey:["mobile-festivals"],queryFn:async()=>{const {data,error}=await (supabase as any).from("festivals").select("*").limit(20); if(error) throw error; return data??[]}}); return <Shell title="Festivals" description="Discovery, player applications and organiser summaries as mobile cards."><MobileSectionCard title="Filters"><div className="flex gap-2 overflow-x-auto">{["Upcoming","Accepting applications","Booked","Organised by me","Completed","Featured"].map(x=><button className="rm-tap shrink-0 rounded-full border px-3 py-2 text-xs font-semibold" key={x}>{x}</button>)}</div></MobileSectionCard><MobileSectionCard title="Festival discovery">{q.isLoading?<MobileLoadingSkeleton/>:q.data?.length?q.data.map((f:any)=><MobileEntityCard key={f.id} title={f.name??f.festival_name??"Festival"} subtitle={`${f.city??f.location??"Location TBC"} · ${fmt(f.start_date)} · stages ${f.stages??"—"} · expected ${f.expected_attendance??"TBC"}`} icon={<Ticket/>} meta={<MobileStatusBadge tone="info">{f.status??"Not applied"}</MobileStatusBadge>}/>):<EmptyState title="No festivals found" message="Try a different city or season filter."/>}</MobileSectionCard><MobileSectionCard title="Player-run festival summary"><p className="text-sm text-muted-foreground">Where ownership exists, this summary shows licence size, dates, stages, booked acts, applications, costs, income, sponsors, staffing and risks, then links to existing management flows.</p></MobileSectionCard></Shell> }
function FestivalDetailMobile({id}:{id:string}){return <Shell title="Festival detail">{["Overview","Lineup","Schedule","Venue","Tickets","Sponsors","Applications","History"].map(s=><MobileSectionCard key={s} title={s}><p className="text-sm text-muted-foreground">Artwork, dates, stages, organiser, ticket price, performer fee, requirements and current player status for festival {id}.</p></MobileSectionCard>)}<MobileStickyActionBar><Link to="/mobile/world/festivals/apply" className="block rounded-xl bg-primary p-3 text-center font-semibold text-primary-foreground">Review application</Link></MobileStickyActionBar></Shell>}
function FestivalApply(){return <Shell title="Festival application" description="Existing festival rules remain authoritative.">{["1. Choose eligible act","2. Review requirements","3. Choose preferred day or slot","4. Review fee or cost","5. Review travel feasibility","6. Review readiness","7. Confirm application"].map((s,i)=><MobileSectionCard key={s} title={s}><MobileStatusBadge tone={i<2?"info":"neutral"}>{["Not Applied","Draft","Submitted","Under Review","Accepted","Rejected","Waitlisted","Withdrawn"][i]??"Review"}</MobileStatusBadge><p className="mt-2 text-sm text-muted-foreground">Applications use canonical booking services, role checks and schedule conflict warnings.</p></MobileSectionCard>)}</Shell>}
function ChartsMobile(){ const [period,setPeriod]=useState<any>("weekly"); const q=useCountryCharts("Global","all","streaming","single",period); return <Shell title="Charts" description="Mobile chart browser and awards entry point."><div className="flex gap-1 overflow-x-auto">{["daily","weekly","monthly","yearly","songs","releases","artists","bands","streaming","sales","world pulse"].map(p=><button key={p} onClick={()=>["daily","weekly","monthly","yearly"].includes(p)&&setPeriod(p)} className="rm-tap shrink-0 rounded-full border px-3 py-2 text-xs font-semibold">{p}</button>)}</div><MobileSectionCard title="Chart list">{q.isLoading?<MobileLoadingSkeleton/>:(q.chartEntries??[]).slice(0,15).map((e:any)=><MobileEntityCard key={e.id} title={`#${e.rank} ${e.title}`} subtitle={`${e.artist} · ${e.trend??"new"} · weeks ${e.weeks_on_chart??0}`} icon={<LineChart/>} meta={<MobileStatusBadge tone={e.trend==="up"?"success":"info"}>{e.trend_change??0}</MobileStatusBadge>}/>)}</MobileSectionCard><MobileSectionCard title="Awards"><MobileEntityCard title="Awards summary" subtitle="Recent awards, nominations, career and annual awards" icon={<Trophy/>}/></MobileSectionCard></Shell> }
function ChartDetail({id}:{id:string}){return <Shell title="Chart detail"><MobileSectionCard title="Ranking detail"><p className="text-sm text-muted-foreground">Chart type, period, current ranking, movement, peak, weeks on chart, metrics, nearby competitors and history for {id}.</p></MobileSectionCard></Shell>}
