import type { OwnerEditionOption } from "../types";
import { asArray, asObject } from "../components/managementUtils";

export type FestivalDashboardStatus = "draft" | "planning" | "booking" | "on_sale" | "ready" | "live" | "completed" | "cancelled" | "unknown";
export type DashboardCheckStatus = "complete" | "warning" | "blocked" | "not_started" | "unavailable";
export type DashboardSeverity = "positive" | "warning" | "blocked" | "info";

export interface FestivalDashboardCheck { key: string; label: string; status: DashboardCheckStatus; explanation: string; destination: string; nextActionLabel: string; source: string; }
export interface FestivalDashboardAction { key: string; title: string; description: string; actionLabel: string; destination: string; severity: DashboardSeverity; }
export interface FestivalDashboardWarning { key: string; message: string; severity: Exclude<DashboardSeverity, "positive">; }
export interface FestivalDashboardUnavailableSection { key: string; label: string; reason: string; retryable?: boolean; }
export interface FestivalDashboardModel { festivalName: string; editionTitle: string; editionStatus: FestivalDashboardStatus; statusLabel: string; statusDescription: string; startsAt: string | null; endsAt: string | null; daysUntilStart: number | null; capacity: number | null; ticketsSold: number | null; ticketSalesPercent: number | null; bookedActs: number; acceptedApplications: number; contractedActs: number; publishedActs: number; availableSlots: number; lineupPercent: number | null; stageCount: number; approvedBudgetMinor: number | null; committedCostMinor: number | null; remainingBudgetMinor: number | null; budgetUsedPercent: number | null; currencyCode: string; sponsorCount: number | null; reputation: number | null; readinessPercent: number; completedChecks: number; totalChecks: number; checks: FestivalDashboardCheck[]; nextAction: FestivalDashboardAction | null; warnings: FestivalDashboardWarning[]; unavailableSections: FestivalDashboardUnavailableSection[]; }

const validDestinations = new Set(["#lineup", "#schedule", "#stages", "#staff", "#permits", "#insurance", "#finance", "#operations", "#settings"]);
const statusCopy: Record<FestivalDashboardStatus, { label: string; description: string }> = { draft: { label: "Draft", description: "Set the dates, location and basic festival structure." }, planning: { label: "Planning", description: "Configure stages, staff, permits, insurance and budget." }, booking: { label: "Booking", description: "Build and confirm the lineup." }, on_sale: { label: "On sale", description: "Ticket sales are open and demand is being tracked." }, ready: { label: "Ready", description: "All essential checks are complete." }, live: { label: "Live", description: "Festival operations are in progress." }, completed: { label: "Completed", description: "The edition has finished and results can be reviewed." }, cancelled: { label: "Cancelled", description: "This edition is no longer proceeding." }, unknown: { label: "Unknown status", description: "The server returned a lifecycle state this client does not recognise." } };

function num(v: unknown): number | null { if (v === null || v === undefined || v === "") return null; const n = Number(v); return Number.isFinite(n) ? n : null; }
function pct(part: number | null, total: number | null): number | null { if (part === null || total === null || total <= 0) return null; return Math.max(0, Math.min(100, Math.round((part / total) * 100))); }
function daysUntilDate(value: string | null, now: Date): number | null { if (!value) return null; const time = new Date(value).getTime(); if (!Number.isFinite(time)) return null; return Math.ceil((time - now.getTime()) / 86400000); }
function mapStatus(raw: unknown): FestivalDashboardStatus { switch (String(raw ?? "").toLowerCase()) { case "concept": case "draft": return "draft"; case "planning": case "setup": case "postponed": return "planning"; case "applications_open": case "booking": case "announced": return "booking"; case "on_sale": return "on_sale"; case "ready": return "ready"; case "live": return "live"; case "settling": case "completed": return "completed"; case "cancelled": case "abandoned": return "cancelled"; default: return "unknown"; } }
function check(key: string, label: string, status: DashboardCheckStatus, explanation: string, destination: string, nextActionLabel: string, source: string): FestivalDashboardCheck { if (!validDestinations.has(destination)) throw new Error(`Invalid festival dashboard destination ${destination}`); return { key, label, status, explanation, destination, nextActionLabel, source }; }
function isOccupied(s: Record<string, unknown>) { return Boolean(s.reservation_id || s.band_id || s.system_act_id || s.booking_id || s.act_id); }
function isContracted(s: Record<string, unknown>) { return Boolean(s.canonical_contract_id || /signed|executed|confirmed/i.test(String(s.contract_status ?? ""))); }

export function buildFestivalDashboardModel(input: { festivalName?: string | null; edition: Pick<OwnerEditionOption, "title" | "status" | "startAt" | "endAt" | "cityName" | "currencyCode"> & Partial<OwnerEditionOption>; operations?: unknown; finance?: unknown; operationsUnavailable?: boolean; financeUnavailable?: boolean; now?: Date; }): FestivalDashboardModel {
  const ops = asObject(input.operations), fin = input.financeUnavailable ? {} : asObject(input.finance ?? ops.finance);
  const stages = asArray(ops.stages), slots = asArray(ops.slots), staff = asArray(ops.staff), permits = asArray(ops.permit_requirements), policies = asArray(ops.insurance_policies);
  const capacity = num(ops.capacity ?? ops.ticketing?.capacity ?? ops.ticket_summary?.capacity ?? input.edition?.["capacity" as keyof typeof input.edition]);
  const ticketsSold = num(ops.tickets_sold ?? ops.ticketing?.tickets_sold ?? ops.ticket_summary?.tickets_sold ?? ops.ticket_summary?.sold);
  const approvedBudgetMinor = num(fin.budget_cents ?? fin.approved_budget_cents ?? ops.budget_cents ?? ops.approved_budget_cents);
  const committedCostMinor = num(fin.committed_cost_cents ?? fin.committed_costs_cents ?? ops.committed_cost_cents ?? ops.committed_costs_cents);
  const stageCount = stages.length;
  const availableSlots = slots.length;
  const bookedActs = slots.filter(isOccupied).length;
  const contractedActs = slots.filter(isContracted).length;
  const acceptedApplications = num(ops.accepted_application_count) ?? slots.filter((s) => /accepted/i.test(String(s.application_status ?? ""))).length;
  const publishedActs = num(ops.published_lineup_count) ?? slots.filter((s) => s.published_at || s.is_published === true).length;
  const requiredStaff = Math.max(1, asArray(ops.staffing_readiness?.required_roles).length || stageCount || 1);
  const approvedPermits = permits.filter((p) => /approved|not_required/i.test(String(p.status ?? p.requirement_status ?? p.decision))).length;
  const permitsNotRequired = permits.length === 0 && Boolean(ops.permits_not_required ?? ops.permit_requirements_not_required);
  const permitsReady = permits.length > 0 ? approvedPermits === permits.length : permitsNotRequired;
  const eventStart = input.edition.startAt ? new Date(input.edition.startAt).getTime() : null;
  const eventEnd = input.edition.endAt ? new Date(input.edition.endAt).getTime() : eventStart;
  const activePolicies = policies.filter((p) => { const status = String(p.policy_status ?? p.status ?? p.coverage_status ?? "").toLowerCase(); const active = /active|bound|issued|covered|in_force/.test(status) && !/cancel|expired|reject|draft|void/.test(status); const from = p.coverage_start_at ?? p.starts_at ?? p.start_at ?? p.effective_at; const to = p.coverage_end_at ?? p.ends_at ?? p.end_at ?? p.expires_at; const fromTime = from ? new Date(String(from)).getTime() : null; const toTime = to ? new Date(String(to)).getTime() : null; return active && (eventStart === null || fromTime === null || fromTime <= eventStart) && (eventEnd === null || toTime === null || toTime >= eventEnd); });
  const operationsAvailable = !input.operationsUnavailable;
  const op = (ready: boolean) => operationsAvailable ? ready : null;
  const readinessChecks = [Boolean(input.edition.startAt && input.edition.endAt), Boolean(input.edition.cityName || ops.venue_name || ops.location_name), op(stageCount > 0), op(availableSlots > 0), op(availableSlots > 0 && bookedActs >= availableSlots), op(bookedActs === 0 ? false : contractedActs >= bookedActs), op(capacity !== null && ticketsSold !== null), op(staff.length >= requiredStaff), op(permitsReady), op(activePolicies.length > 0), approvedBudgetMinor !== null && approvedBudgetMinor > 0];
  const totalChecks = readinessChecks.filter((value) => value !== null).length; const completedChecks = readinessChecks.filter(Boolean).length;
  const checks = [
    check("festival_details", "Festival details", input.edition.title ? "complete" : "blocked", input.edition.title ? "Edition name is present." : "Add the edition name.", "#settings", "Review settings", "owner bootstrap edition option"),
    check("dates_location", "Dates and location", input.edition.startAt && input.edition.endAt && (input.edition.cityName || ops.venue_name) ? "complete" : "blocked", input.edition.startAt && input.edition.endAt ? (input.edition.cityName || ops.venue_name ? "Dates and location are confirmed." : "Choose a location or venue.") : "Set valid start and end dates.", "#settings", "Set dates and location", "edition start/end/city plus operations venue"),
    check("stages", "Stages configured", !operationsAvailable ? "unavailable" : stageCount ? "complete" : "blocked", !operationsAvailable ? "Operations summary is unavailable." : stageCount ? `${stageCount} stages configured.` : "A festival needs at least one stage.", "#stages", "Manage stages", "operations.stages"),
    check("slots", "Performance slots created", !operationsAvailable ? "unavailable" : availableSlots ? "complete" : stageCount ? "blocked" : "not_started", !operationsAvailable ? "Operations summary is unavailable." : availableSlots ? `${availableSlots} performance slots created.` : "Create slots after stages are configured.", "#stages", "Create slots", "operations.slots"),
    check("lineup", "Lineup sufficiently filled", !operationsAvailable ? "unavailable" : availableSlots ? (bookedActs >= availableSlots ? "complete" : "warning") : "not_started", !operationsAvailable ? "Operations summary is unavailable." : availableSlots ? `${bookedActs} of ${availableSlots} performance slots are filled.` : "No slots are available for lineup booking yet.", "#lineup", "Review lineup", "slot occupancy only"),
    check("contracts", "Contracts confirmed", !operationsAvailable ? "unavailable" : bookedActs ? (contractedActs >= bookedActs ? "complete" : "warning") : "not_started", !operationsAvailable ? "Operations summary is unavailable." : bookedActs ? `${contractedActs} of ${bookedActs} occupied slots have signed contracts.` : "Book acts before contracts can be confirmed.", "#lineup", "Confirm contracts", "canonical contract id / signed status"),
    check("tickets", "Tickets configured", !operationsAvailable || capacity === null || ticketsSold === null ? "unavailable" : "complete", !operationsAvailable ? "Operations summary is unavailable." : capacity !== null && ticketsSold !== null ? `${ticketsSold} of ${capacity} tickets sold.` : "Ticket configuration is not present in the operations summary.", "#finance", "Review ticket finances", "ticket summary fields"),
    check("staff", "Staffing arranged", !operationsAvailable ? "unavailable" : staff.length >= requiredStaff ? "complete" : staff.length ? "warning" : "blocked", !operationsAvailable ? "Operations summary is unavailable." : staff.length ? `${staff.length} staff assigned.` : "No staff have been hired.", "#staff", "Arrange staffing", "operations.staff"),
    check("permits", "Permits approved", !operationsAvailable ? "unavailable" : permitsReady ? "complete" : permits.length ? "blocked" : "not_started", !operationsAvailable ? "Operations summary is unavailable." : permits.length ? `${approvedPermits} of ${permits.length} permit requirements approved.` : permitsNotRequired ? "No permits are currently required." : "Permit requirements have not been configured.", "#permits", "Review permits", "operations.permit_requirements"),
    check("insurance", "Insurance active", !operationsAvailable ? "unavailable" : activePolicies.length ? "complete" : "blocked", !operationsAvailable ? "Operations summary is unavailable." : activePolicies.length ? "Active insurance covers the edition dates." : "No active insurance policy is present for the edition dates.", "#insurance", "Manage insurance", "operations.insurance_policies"),
    check("budget", "Budget approved", approvedBudgetMinor === null ? "unavailable" : approvedBudgetMinor > 0 ? "complete" : "blocked", approvedBudgetMinor === null ? "Finance summary is unavailable." : approvedBudgetMinor > 0 ? "Approved budget is present." : "Approved budget is zero.", "#finance", "Review budget", "finance.budget_cents"),
    check("readiness", "Operational readiness", completedChecks === totalChecks ? "complete" : "warning", `${completedChecks} of ${totalChecks} checks complete.`, "#operations", "Review readiness", "dashboard checks"),
  ];
  const actionable = checks.find((c) => c.status === "blocked") ?? checks.find((c) => c.status === "warning") ?? checks.find((c) => c.status === "unavailable");
  const nextAction = actionable ? { key: actionable.key, title: actionable.label, description: actionable.explanation, actionLabel: actionable.nextActionLabel, destination: actionable.destination, severity: actionable.status === "blocked" ? "blocked" as const : actionable.status === "warning" ? "warning" as const : "info" as const } : { key: "on_track", title: "Festival planning is on track", description: "Review the final readiness checks before the event begins.", actionLabel: "Review readiness", destination: "#operations", severity: "positive" as const };
  const status = mapStatus(input.edition.status);
  return { festivalName: input.festivalName ?? String(ops.festival_name ?? ops.brand_name ?? "Festival"), editionTitle: input.edition.title ?? "Untitled edition", editionStatus: status, statusLabel: statusCopy[status].label, statusDescription: statusCopy[status].description, startsAt: input.edition.startAt ?? null, endsAt: input.edition.endAt ?? null, daysUntilStart: daysUntilDate(input.edition.startAt ?? null, input.now ?? new Date()), capacity, ticketsSold, ticketSalesPercent: pct(ticketsSold, capacity), bookedActs, acceptedApplications, contractedActs, publishedActs, availableSlots, lineupPercent: pct(bookedActs, availableSlots), stageCount, approvedBudgetMinor, committedCostMinor, remainingBudgetMinor: approvedBudgetMinor === null || committedCostMinor === null ? null : approvedBudgetMinor - committedCostMinor, budgetUsedPercent: pct(committedCostMinor, approvedBudgetMinor), currencyCode: String(fin.currency ?? fin.currency_code ?? ops.currency ?? ops.currency_code ?? input.edition.currencyCode ?? "USD"), sponsorCount: num(ops.sponsor_count ?? ops.sponsors?.length), reputation: num(ops.reputation ?? ops.festival_reputation), readinessPercent: pct(completedChecks, totalChecks) ?? 0, completedChecks, totalChecks, checks, nextAction, warnings: [...(status === "unknown" ? [{ key: "unknown_status", message: `Unknown lifecycle status: ${String(input.edition.status)}`, severity: "warning" as const }] : []), ...(input.operationsUnavailable ? [{ key: "operations_unavailable", message: "Festival operations could not be loaded.", severity: "blocked" as const }] : []), ...(input.financeUnavailable ? [{ key: "finance_unavailable", message: "Budget currently unavailable.", severity: "warning" as const }] : [])], unavailableSections: [...(input.operationsUnavailable ? [{ key: "operations", label: "Operations", reason: "FESTIVAL_EDITION_OPERATIONS", retryable: true }] : []), ...(input.financeUnavailable ? [{ key: "finance", label: "Finance", reason: "FESTIVAL_EDITION_FINANCE", retryable: true }] : [])] };
}
