import { useEffect, useRef, useState } from "react";
import { Check, Copy, Download, Image as ImageIcon, Share2 } from "lucide-react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";
import { canvasBlob, renderShareMoment, shareFilename } from "./canvas";
import { copyPng, copyText, downloadBlob, nativeShare, withReferral } from "./share";
import type { ShareFormat, ShareMoment, ShareVisualTheme } from "./types";
import { loadCaptureImage } from "./avatarCapture";
import type { CharacterProfileShareMoment } from "./characterProfile";
import rockmundoLogo from "@/assets/rockmundo-new-logo.png";
import { saveShareMomentSnapshot } from "./gallery";

export function ShareMomentSheet({moment,open,onOpenChange}:{moment:ShareMoment|null;open:boolean;onOpenChange:(open:boolean)=>void}){
 const {toast}=useToast();
 const canvasRef=useRef<HTMLCanvasElement|null>(null); const avatarRef=useRef<CanvasImageSource|null>(null); const artworkRef=useRef<CanvasImageSource|null>(null); const logoRef=useRef<CanvasImageSource|null>(null); const [format,setFormat]=useState<ShareFormat>("square"); const [done,setDone]=useState<string|null>(null); const [avatarVersion,setAvatarVersion]=useState(0); const [draft,setDraft]=useState<ShareMoment|null>(moment);
 useEffect(()=>{if(open&&moment)setDraft({...moment});},[open,moment]);
 useEffect(()=>{let cancelled=false;avatarRef.current=null;if(!open||!moment)return;const embedded=(moment as CharacterProfileShareMoment).avatar;
  if(!embedded){setAvatarVersion(v=>v+1);return;}
  void loadCaptureImage(embedded).then(avatar=>{if(!cancelled){avatarRef.current=avatar;setAvatarVersion(v=>v+1)}}).catch(()=>{if(!cancelled)setAvatarVersion(v=>v+1)});
  return()=>{cancelled=true};
 },[open,moment]);
 useEffect(()=>{let cancelled=false;artworkRef.current=null;if(!open||!moment?.artworkUrl){setAvatarVersion(v=>v+1);return;}const image=new Image();image.crossOrigin="anonymous";image.onload=()=>{if(!cancelled){artworkRef.current=image;setAvatarVersion(v=>v+1)}};image.onerror=()=>{if(!cancelled)setAvatarVersion(v=>v+1)};image.src=moment.artworkUrl;return()=>{cancelled=true};},[open,moment?.artworkUrl]);
 useEffect(()=>{let cancelled=false;const image=new Image();image.onload=()=>{if(!cancelled){logoRef.current=image;setAvatarVersion(v=>v+1)}};image.onerror=()=>{if(!cancelled)setAvatarVersion(v=>v+1)};image.src=rockmundoLogo;return()=>{cancelled=true};},[]);
 useEffect(()=>{if(open&&draft&&canvasRef.current)renderShareMoment(canvasRef.current,draft,format,avatarRef.current,artworkRef.current,logoRef.current)},[open,draft,format,avatarVersion]);
 if(!moment||!draft)return null;
 const url=draft.destinationUrl?withReferral(draft.destinationUrl,draft.referralCode):undefined; const text=[draft.headline,draft.subheadline].filter(Boolean).join(" — ");
 const blob=()=>canvasRef.current?canvasBlob(canvasRef.current):Promise.reject(new Error("Preview unavailable")); const recordShare=()=>{if(draft.shareCooldownKey&&typeof localStorage!=="undefined")localStorage.setItem(draft.shareCooldownKey,String(Date.now()));void saveShareMomentSnapshot(draft).catch(()=>undefined)}; const flash=(k:string)=>{setDone(k);setTimeout(()=>setDone(v=>v===k?null:v),1400)};
 const share=async()=>{try{const b=await blob();const file=new File([b],shareFilename(draft,format),{type:"image/png"});const result=await nativeShare({title:draft.headline,text,url,file});if(result==="unsupported"){(await copyText([text,url].filter(Boolean).join("\n")))?(recordShare(),toast({title:"Share link copied"})):toast({title:"Sharing unsupported",description:"Download the PNG to share it manually.",variant:"destructive"});}else if(result==="shared"){recordShare();flash("share")}}catch(e){toast({title:"Unable to share",description:(e as Error).message,variant:"destructive"})}};
 return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="w-full overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle className="flex items-center gap-2"><Share2 className="h-4 w-4"/>Share your RockMundo moment</SheetTitle><SheetDescription>Choose a format, preview the branded card, then share the image or link.</SheetDescription></SheetHeader><div className="mt-4 space-y-4"><div className="flex gap-2">{(["square","story","landscape"] as ShareFormat[]).map(f=><Button key={f} size="sm" variant={format===f?"default":"outline"} onClick={()=>setFormat(f)} className="capitalize">{f}</Button>)}</div><div className="space-y-3 rounded-lg border p-3"><div><p className="mb-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">Style</p><div className="flex flex-wrap gap-2">{(["moment","spotlight","neon","mono"] as ShareVisualTheme[]).map(theme=><Button key={theme} type="button" size="sm" variant={(draft.visualTheme||"moment")===theme?"default":"outline"} className="capitalize" onClick={()=>setDraft({...draft,visualTheme:theme})}>{theme==="moment"?"Original":theme}</Button>)}</div></div><div className="grid gap-2"><Input value={draft.headline} maxLength={80} aria-label="Share headline" onChange={e=>setDraft({...draft,headline:e.target.value})}/><Input value={draft.subheadline||""} maxLength={120} placeholder="Optional subheadline" aria-label="Share subheadline" onChange={e=>setDraft({...draft,subheadline:e.target.value})}/></div></div><div className="rounded-lg border bg-muted/30 p-2"><canvas ref={canvasRef} className="h-auto w-full rounded-md" aria-label="RockMundo share card preview"/></div><div className="grid grid-cols-2 gap-2"><Button onClick={share}>{done==="share"?<Check/>:<Share2/>}Share…</Button><Button variant="secondary" onClick={async()=>{const b=await blob();downloadBlob(b,shareFilename(draft,format));flash("download")}}>{done==="download"?<Check/>:<Download/>}Download PNG</Button><Button variant="outline" onClick={async()=>{const b=await blob();if(await copyPng(b))flash("image");else toast({title:"Copy image unsupported",description:"Download the PNG instead.",variant:"destructive"})}}>{done==="image"?<Check/>:<ImageIcon/>}Copy image</Button><Button variant="outline" onClick={async()=>{if(await copyText([text,url].filter(Boolean).join("\n"))){recordShare();flash("link")}else toast({title:"Copy link unavailable",description:"Your browser blocked clipboard access.",variant:"destructive"})}}>{done==="link"?<Check/>:<Copy/>}Copy link</Button></div></div></SheetContent></Sheet>;
}
