import { describe, expect, it } from "vitest";
import type { GigViewerReplay } from "../../events/types";
import { buildStoryModel, clampEnergy, crowdMoodForEnergy, deriveStorySnapshot, interpolateEnergy, phaseForSong } from "../engine/StoryEngine";
const e = (sequence: number, offset: number, duration: number, payload: any, extra: any = {}) => ({ id: `e${sequence}`, gigId: "g1", sequence, scheduledOffsetMs: offset, durationMs: duration, phase: extra.phase ?? "song_performance", eventType: extra.eventType ?? "song_crowd_reaction", importance: extra.importance ?? "normal", messageKey: extra.messageKey ?? "gig.viewer.song_reaction", messageParams: extra.messageParams ?? {}, songId: extra.songId, performerProfileId: extra.performerProfileId, crowdEnergyBefore: extra.before, crowdEnergyAfter: extra.after, visualPayload: payload }) as any;
const replay: GigViewerReplay = { id: "r", gigId: "g1", gigOutcomeId: "o", viewerVersion: 1, eventSchemaVersion: 1, simulationSeed: "seed", durationMs: 70000, generatedAt: "now", checksum: null, status: "ready", events: [
  e(0,0,1000,{type:"venue_open", entranceIds:["main"], lightLevel:.3},{phase:"venue_opening",eventType:"venue_opened",messageKey:"gig.viewer.venue_opened"}),
  e(1,1000,9000,{type:"song_start", songId:"s1", title:"Open", position:0, montage:false},{phase:"song_intro",eventType:"song_started",messageKey:"gig.viewer.song_started",songId:"s1",messageParams:{title:"Open"}}),
  e(2,5000,10000,{type:"crowd_reaction", reaction:"wave", intensity:.5},{songId:"s1",before:40,after:50}),
  e(3,20000,9000,{type:"song_start", songId:"s2", title:"Lift", position:1, montage:false},{phase:"song_intro",eventType:"song_started",messageKey:"gig.viewer.song_started",songId:"s2",messageParams:{title:"Lift"}}),
  e(4,25000,10000,{type:"crowd_reaction", reaction:"jump", intensity:.8},{songId:"s2",before:50,after:72}),
  e(5,36000,3000,{type:"moment_effect", effect:"pulse", intensity:.8},{eventType:"song_highlight",importance:"important",songId:"s2",before:50,after:72,messageKey:"gig.viewer.song_highlight",messageParams:{title:"Lift"}}),
  e(6,45000,9000,{type:"song_start", songId:"s3", title:"Close", position:2, montage:false},{phase:"song_intro",eventType:"song_started",messageKey:"gig.viewer.song_started",songId:"s3",messageParams:{title:"Close"}}),
  e(7,50000,10000,{type:"crowd_reaction", reaction:"still", intensity:.2},{songId:"s3",before:72,after:35}),
  e(8,61000,3000,{type:"crowd_reaction", reaction:"wave", intensity:.5},{phase:"encore_decision",eventType:"encore_decided",importance:"important",before:35,after:35,messageKey:"gig.viewer.encore_declined"}),
  e(9,65000,3000,{type:"result_reveal", overallRating: 12, attendance: 100, netProfit: 5, verdictKey:"mixed"},{phase:"result_reveal",eventType:"result_revealed",importance:"critical",messageKey:"gig.viewer.result_reveal"})] };
const experience: any = { songs: [{ id:"p1", songId:"s1", performanceScore:{status:"available", value:10}}, { id:"p2", songId:"s2", performanceScore:{status:"available", value:22}}, { id:"p3", songId:"s3", performanceScore:{status:"available", value:8}}] };
describe("story engine", () => {
  it("maps energy thresholds and clamps interpolation", () => { expect(crowdMoodForEnergy(0).mood).toBe("disappointed"); expect(crowdMoodForEnergy(85).mood).toBe("ecstatic"); expect(clampEnergy(150)).toBe(100); expect(interpolateEnergy(10, 90, .5)).toBe(50); expect(interpolateEnergy(10, 90, .5, true)).toBe(10); });
  it("builds song lifecycle, best/weakest, highlight, finale and result points", () => { const story = buildStoryModel(replay, experience); expect(story.songs).toHaveLength(3); expect(story.bestSong?.title).toBe("Lift"); expect(story.weakestSong?.title).toBe("Close"); expect(story.turningPoint?.title).toBe("Lift"); expect(story.highlights.some((h) => h.title === "Strongest song")).toBe(true); expect(story.resultOffsetMs).toBe(65000); expect(phaseForSong(story.songs[0], 2000)).toBe("intro"); expect(phaseForSong(story.songs[0], 12000)).toBe("peak"); });
  it("reconstructs deterministic snapshot and poor moments reduce activity", () => { const story = buildStoryModel(replay, experience); expect(deriveStorySnapshot(story, 30000).reaction).toMatch(/jump|bounce|cheer_pulse/); const falling = deriveStorySnapshot(story, 54000); expect(falling.reaction).toBe("disappointed_settling"); expect(deriveStorySnapshot(story, 66000).resultVisible).toBe(true); expect(deriveStorySnapshot(story, 36000).activeHighlight?.songId).toBe("s2"); });
  it("does not force turning point for flat energy", () => { const flat = { ...replay, events: replay.events.map((ev: any) => ({ ...ev, crowdEnergyBefore: ev.crowdEnergyBefore == null ? ev.crowdEnergyBefore : 50, crowdEnergyAfter: ev.crowdEnergyAfter == null ? ev.crowdEnergyAfter : 52 })) }; expect(buildStoryModel(flat, experience).turningPoint).toBeNull(); });
});
