import { describe, expect, it } from 'vitest';
import { amendAgreement, calculateBandRevenueShares, diffAgreementTerms, signAgreement, validateAgreement } from '../services';
import { createEqualShareTemplate } from '../templates';
import type { BandAgreement } from '../types';

function agreement(): BandAgreement { const terms = createEqualShareTemplate('2026-07-13T00:00:00.000Z', ['a','b'], 20).terms; return { id:'ag1', bandId:'band1', agreementType:'standard_membership', title:'Membership', version:1, status:'awaiting_signatures', effectiveFrom:'2026-07-13T00:00:00.000Z', createdBy:'owner', termsSnapshot:terms, parties:[{playerId:'a', partyRole:'member', mandatory:true, signatureStatus:'pending'}, {playerId:'owner', partyRole:'band_signatory', mandatory:true, signatureStatus:'pending'}], createdAt:'2026-07-13T00:00:00.000Z', updatedAt:'2026-07-13T00:00:00.000Z' }; }

describe('band agreement services', () => {
  it('validates required parties, notice limits, and revenue totals', () => { expect(validateAgreement(agreement())).toEqual([]); const bad = agreement(); bad.termsSnapshot.noticePeriodDays = 99; bad.termsSnapshot.revenueShares[0].recipients[0].percentage = 90; expect(validateAgreement(bad)).toContain('notice period must be between 0 and 28 gameplay days'); expect(validateAgreement(bad).some(e => e.includes('exceed 100%'))).toBe(true); });
  it('requires all mandatory authenticated parties before activation', () => { const one = signAgreement(agreement(), 'a', '2026-07-13T01:00:00.000Z'); expect(one.status).toBe('partially_signed'); const two = signAgreement(one, 'owner', '2026-07-13T02:00:00.000Z'); expect(two.status).toBe('active'); expect(two.activatedAt).toBe('2026-07-13T02:00:00.000Z'); });
  it('invalidates signatures after amendment and produces player-readable diffs', () => { const active = signAgreement(signAgreement(agreement(), 'a'), 'owner'); const nextTerms = { ...active.termsSnapshot, noticePeriodDays: 14 }; const amended = amendAgreement(active, nextTerms, 'owner', 'longer handover'); expect(amended.version).toBe(2); expect(amended.parties.every(p => p.signatureStatus === 'invalidated')).toBe(true); expect(diffAgreementTerms(active.termsSnapshot, amended.termsSnapshot)).toContain('Notice period changed from 7 to 14 days'); });
  it('allocates category-specific revenue with an immutable snapshot and band reserve', () => { const snapshot = calculateBandRevenueShares(agreement(), { bandId:'band1', category:'gig_income', grossAmount:10000, costs:1000, occurredAt:'2026-07-14T00:00:00.000Z', source:{type:'gig', id:'gig1'} }); expect(snapshot.netDistributable).toBe(9000); expect(snapshot.allocations).toEqual(expect.arrayContaining([{ recipientId:'band-reserve', recipientType:'band_reserve', percentage:20, amount:1800 }])); expect(snapshot.agreementVersion).toBe(1); });
});
