import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { AlertTriangle, Banknote, Building2, CalendarDays, CheckCircle2, Home, KeyRound } from "lucide-react";
import { FMPageScaffold } from "@/components/fm/FMPageScaffold";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { formatCurrencyMinor } from "@/services/banking/currency";
import { loadApplication, loadDashboard, loadOffer, loadPropertyDetail, loadSchedule, loadUnderwritingResult, listMortgages, reserveOffer, submitMortgageApplication, type MortgageDashboard, type MortgageProduct, type MortgageScheduleLine, type MortgageSummary, type PropertyDetail, type RpcState } from "@/services/banking/mortgageVerticalSlice";

function money(amountMinor?: number, currencyCode = "GBP") { return formatCurrencyMinor({ amountMinor: amountMinor ?? 0, currencyCode }); }
function Status<T>({ state }: { state: RpcState<T> }) { if (state.status === "loading") return <p className="text-sm text-muted-foreground">Loading…</p>; if (state.status === "error") return <div className="rounded border border-destructive/40 p-3 text-sm text-destructive"><AlertTriangle className="mr-2 inline h-4 w-4" />{state.message}</div>; if (state.status === "empty") return <p className="text-sm text-muted-foreground">No records found.</p>; return null; }

export function PropertyDetailPage() {
  const { propertyId = "" } = useParams();
  const [detail, setDetail] = useState<RpcState<PropertyDetail>>({ status: "loading" });
  useEffect(() => { setDetail({ status: "loading" }); void loadPropertyDetail(propertyId).then(setDetail); }, [propertyId]);
  const property = detail.data?.property;
  const products = detail.data?.products ?? [];
  return <FMPageScaffold title="Property detail" subtitle="Persistent property data and eligible fixed-rate products." icon={Home} backTo="/finance/properties"><Status state={detail} />{property && <Card><CardHeader><CardTitle>{property.district_name ?? "Property"} {property.property_type}</CardTitle><CardDescription>{property.city_name} · {property.size_sqm} sqm · condition {property.condition}% · prestige {property.prestige}</CardDescription></CardHeader><CardContent className="space-y-3"><p className="text-2xl font-bold">{money(property.current_valuation_minor, property.currency_code)}</p><Badge>{property.listing_status ?? "loading"}</Badge><div className="grid gap-2 md:grid-cols-2">{products.map((p) => <div key={p.id} className="rounded-lg border p-3"><p className="font-semibold">{p.product_name}</p><p className="text-sm text-muted-foreground">{p.providerName ?? "Provider"} · {(p.annual_rate_bps / 100).toFixed(2)}% fixed · {(p.min_deposit_bps / 100).toFixed(1)}% minimum deposit</p></div>)}</div><Button asChild disabled={products.length === 0}><Link to={`/finance/properties/${propertyId}/mortgage`}><KeyRound className="mr-2 h-4 w-4" />Start mortgage</Link></Button></CardContent></Card>}</FMPageScaffold>;
}

export function MortgageApplicationPage() {
  const { propertyId = "" } = useParams(); const navigate = useNavigate();
  const [detail, setDetail] = useState<RpcState<PropertyDetail>>({ status: "loading" }); const [term, setTerm] = useState(300); const [deposit, setDeposit] = useState(2400000); const [submitState, setSubmitState] = useState<RpcState<string>>({ status: "idle" }); const keyRef = useRef<string>("");
  useEffect(() => { setDetail({ status: "loading" }); void loadPropertyDetail(propertyId).then(setDetail); }, [propertyId]);
  const product: MortgageProduct | undefined = useMemo(() => detail.data?.products[0], [detail]); const property = detail.data?.property;
  const monthly = product && property ? Math.ceil((Number(property.current_valuation_minor ?? 0) - deposit) * ((Number(product.annual_rate_bps) / 10000) / 12) / (1 - Math.pow(1 + ((Number(product.annual_rate_bps) / 10000) / 12), -term))) : 0;
  async function submit() { if (!product || !property) return; if (!keyRef.current) keyRef.current = `ui-mortgage-${crypto.randomUUID()}`; setSubmitState({ status: "loading" }); const result = await submitMortgageApplication({ propertyId, productId: product.id, termMonths: term, depositMinor: deposit, currencyCode: property.currency_code ?? "GBP", idempotencyKey: keyRef.current }); setSubmitState(result); if (result.status === "success" && result.data) navigate(`/finance/mortgage-applications/${result.data}`); }
  return <FMPageScaffold title="Mortgage application" subtitle="A unique submission key is generated per intentional application attempt." icon={Banknote} backTo={`/finance/properties/${propertyId}`}><Status state={detail} /><Card><CardHeader><CardTitle>{product?.product_name ?? "No eligible product"}</CardTitle><CardDescription>Underwriting remains server-side; the browser only submits product, deposit and term.</CardDescription></CardHeader><CardContent className="space-y-4"><Input aria-label="Deposit amount" type="number" value={deposit} onChange={(event) => { keyRef.current = ""; setDeposit(Number(event.target.value)); }} /><Input aria-label="Term months" type="number" value={term} onChange={(event) => { keyRef.current = ""; setTerm(Number(event.target.value)); }} /><p>Indicative monthly payment: <strong>{money(monthly, property?.currency_code)}</strong></p><Button onClick={submit} disabled={!product || submitState.status === "loading"}>Submit authoritative application</Button><Status state={submitState} /></CardContent></Card></FMPageScaffold>;
}

export function MortgageApplicationResultPage() {
  const { applicationId = "" } = useParams(); const [app, setApp] = useState<RpcState<unknown>>({ status: "loading" }); const [result, setResult] = useState<RpcState<{ status: string; rejection_reasons?: string[]; verified_deposit_minor: number; required_deposit_minor: number; principal_minor: number; ltv_bps: number; stressed_payment_minor: number; disposable_income_minor: number }>>({ status: "loading" }); const [offer, setOffer] = useState<RpcState<{ id: string; currency_code: string; deposit_minor: number; principal_minor: number; monthly_payment_minor: number; expires_at: string }>>({ status: "loading" });
  useEffect(() => { void loadApplication(applicationId).then(setApp); void loadUnderwritingResult(applicationId).then(setResult); void loadOffer(applicationId).then(setOffer); }, [applicationId]);
  return <FMPageScaffold title="Mortgage application result" subtitle="Review the authoritative underwriting result before reserving the property." icon={CheckCircle2} backTo="/finance/properties"><Status state={app} /><Status state={result} />{result.data && <Card><CardHeader><CardTitle>{result.data.status === "approved" ? "Approved" : "Not approved"}</CardTitle><CardDescription>{(result.data.rejection_reasons ?? []).join(", ") || "No rejection reasons."}</CardDescription></CardHeader><CardContent className="grid gap-2 md:grid-cols-2"><span>Verified deposit {money(result.data.verified_deposit_minor)}</span><span>Required deposit {money(result.data.required_deposit_minor)}</span><span>Offered principal {money(result.data.principal_minor)}</span><span>LTV {(result.data.ltv_bps / 100).toFixed(1)}%</span><span>Stressed payment {money(result.data.stressed_payment_minor)}</span><span>Disposable income {money(result.data.disposable_income_minor)}</span></CardContent></Card>}<Status state={offer} />{offer.data && <Card className="mt-4"><CardHeader><CardTitle>Offer review</CardTitle><CardDescription>Expires {new Date(offer.data.expires_at).toLocaleString()}</CardDescription></CardHeader><CardContent className="space-y-3"><p>Deposit {money(offer.data.deposit_minor, offer.data.currency_code)} · Principal {money(offer.data.principal_minor, offer.data.currency_code)} · Payment {money(offer.data.monthly_payment_minor, offer.data.currency_code)}</p><Button asChild><Link to={`/finance/mortgage-offers/${offer.data.id}`}>Accept and reserve</Link></Button></CardContent></Card>}</FMPageScaffold>;
}

export function MortgageOfferPage() { const { offerId = "" } = useParams(); const [state, setState] = useState<RpcState<Record<string, unknown>>>({ status: "idle" }); async function reserve() { setState({ status: "loading" }); setState(await reserveOffer(offerId, `ui-reservation-${crypto.randomUUID()}`)); } return <FMPageScaffold title="Mortgage offer" subtitle="Reservation and completion are intentionally separated from the contract dashboard." icon={KeyRound} backTo="/finance/mortgages"><Card><CardHeader><CardTitle>Reserve property</CardTitle><CardDescription>Completion account selection remains server-validated and will not navigate to a contract until completion returns a contract ID.</CardDescription></CardHeader><CardContent className="space-y-3"><Button onClick={reserve} disabled={state.status === "loading"}>Accept offer and reserve</Button><Status state={state} />{state.status === "success" && <p className="text-sm text-muted-foreground">Reservation recorded. Completion remains blocked if accounting prerequisites fail.</p>}</CardContent></Card></FMPageScaffold>; }

export function MortgagesPage() { const [mortgages, setMortgages] = useState<RpcState<MortgageSummary[]>>({ status: "loading" }); useEffect(() => { void listMortgages().then(setMortgages); }, []); return <FMPageScaffold title="Mortgage dashboard" subtitle="Persistent contracts from completed property purchases." icon={Building2} backTo="/finances"><Status state={mortgages} /><div className="grid gap-3">{(mortgages.data ?? []).map((m) => <Card key={m.id}><CardHeader><CardTitle>{money(m.outstandingPrincipalMinor, m.currencyCode)} outstanding</CardTitle><CardDescription>Next payment {m.nextPaymentDueDate ?? "—"}</CardDescription></CardHeader><CardContent><Button asChild><Link to={`/finance/mortgages/${m.id}`}>Open mortgage</Link></Button></CardContent></Card>)}</div></FMPageScaffold>; }

export function MortgageDashboardPage() { const { mortgageId = "" } = useParams(); const [dashboard, setDashboard] = useState<RpcState<MortgageDashboard>>({ status: "loading" }); const [schedule, setSchedule] = useState<RpcState<MortgageScheduleLine[]>>({ status: "loading" }); useEffect(() => { void loadDashboard(mortgageId).then(setDashboard); void loadSchedule(mortgageId).then(setSchedule); }, [mortgageId]); const contract = dashboard.data?.contract; const property = dashboard.data?.property; const next = dashboard.data?.nextScheduleLine; return <FMPageScaffold title="Mortgage account" subtitle="Authoritative balance, security, arrears and repayment schedule." icon={CheckCircle2} backTo="/finance/mortgages"><Status state={dashboard} />{contract && <div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle>Balance</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold">{money(contract.outstanding_principal_minor, contract.currency_code)}</p></CardContent></Card><Card><CardHeader><CardTitle>LTV and equity</CardTitle></CardHeader><CardContent><p>{dashboard.data?.equity?.ltv_bps ? `${(dashboard.data.equity.ltv_bps / 100).toFixed(1)}% LTV` : "—"}</p><p>{money(dashboard.data?.equity?.equity_minor, contract.currency_code)} equity</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarDays className="h-5 w-5" />Next payment</CardTitle></CardHeader><CardContent><p>{next?.due_date ?? "—"}</p><p>{money(next?.total_due_minor, contract.currency_code)}</p></CardContent></Card></div>}<Card className="mt-4"><CardHeader><CardTitle>{property?.district_name ?? "Property"} repayment schedule</CardTitle><CardDescription>Shows the active schedule with principal, interest, fees, paid amounts and status.</CardDescription></CardHeader><CardContent className="space-y-2"><Status state={schedule} />{(schedule.data ?? []).map((line) => <div key={line.id} className="grid grid-cols-6 rounded border p-2 text-sm"><span>{line.instalment_number}</span><span>{line.due_date}</span><span>P {money(line.principal_due_minor, line.currency_code)}</span><span>I {money(line.interest_due_minor, line.currency_code)}</span><span>F {money(line.fees_due_minor, line.currency_code)}</span><Badge>{line.status}</Badge></div>)}</CardContent></Card></FMPageScaffold>; }
