import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type Row = { id:string; line_kind:"revenue"|"cost"; category:string; net_amount_minor:number; currency_code:string; cash_state:string; source_type:string };
type Aggregate = { id:string; state:string; settlement_version:number; currency_code:string; gross_revenue_minor:number; total_costs_minor:number; tax_minor:number; refunds_minor:number; net_profit_loss_minor:number; reconciliation_status:string; runtime_completion_digest_id:string; reconciliation:Record<string,unknown> };
type Report = { settlement:Aggregate; lines:Row[]; outcomes:Array<{outcome_type:string;final_score:number|null}>; batch:null|{state:string;completed_items:number;expected_items:number}; audit:Array<{id:string;action:string;status:string;created_at:string}> };
const client=supabase as unknown as {rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:{message:string}|null}>};
const call=async(name:string,args:Record<string,unknown>)=>{const {data,error}=await client.rpc(name,args);if(error)throw new Error(error.message);return data};
const key=()=>crypto.randomUUID();
const money=(minor:number,currency:string)=>new Intl.NumberFormat("en-GB",{style:"currency",currency}).format(minor/100);
const message=(error:unknown)=>{const raw=error instanceof Error?error.message:"FESTIVAL_SETTLEMENT_POSTING_FAILED";const code=["FESTIVAL_SETTLEMENT_RUNTIME_INCOMPLETE","FESTIVAL_SETTLEMENT_EVIDENCE_MISSING","FESTIVAL_SETTLEMENT_RECONCILIATION_FAILED","FESTIVAL_SETTLEMENT_VERSION_CONFLICT","FESTIVAL_SETTLEMENT_IDEMPOTENCY_CONFLICT","FESTIVAL_SETTLEMENT_RECOVERY_REQUIRED","FESTIVAL_SETTLEMENT_TAX_CONFIGURATION_MISSING"].find(x=>raw.includes(x));return ({FESTIVAL_SETTLEMENT_RUNTIME_INCOMPLETE:"Complete the Festival runtime before preparing settlement.",FESTIVAL_SETTLEMENT_EVIDENCE_MISSING:"Frozen settlement evidence is missing or inconsistent.",FESTIVAL_SETTLEMENT_RECONCILIATION_FAILED:"Reconciliation is blocked and cannot be approved.",FESTIVAL_SETTLEMENT_VERSION_CONFLICT:"Settlement changed. Refresh before trying again.",FESTIVAL_SETTLEMENT_IDEMPOTENCY_CONFLICT:"That request key was already used for a different command.",FESTIVAL_SETTLEMENT_RECOVERY_REQUIRED:"Posting stopped safely. Retry to continue the existing batch.",FESTIVAL_SETTLEMENT_TAX_CONFIGURATION_MISSING:"The frozen jurisdiction tax configuration is missing."} as Record<string,string>)[code??""]??"The authoritative settlement operation failed."};

export function EditionSettlementWorkspace({companyId,editionId}:{companyId:string;editionId:string}){
 const qc=useQueryClient();const q=useQuery({queryKey:["festival-edition-settlement",companyId,editionId],queryFn:()=>call("get_festival_edition_settlement",{p_festival_company_id:companyId,p_edition_id:editionId}) as Promise<Report|null>});
 const refresh=()=>qc.invalidateQueries({queryKey:["festival-edition-settlement",companyId,editionId]});
 const prepare=useMutation({mutationFn:(digest:string)=>call("prepare_festival_edition_settlement",{p_edition_id:editionId,p_expected_runtime_digest:digest,p_idempotency_key:key()}),onSuccess:refresh});
 const approve=useMutation({mutationFn:(s:Aggregate)=>call("approve_festival_edition_settlement",{p_settlement_id:s.id,p_expected_version:s.settlement_version,p_idempotency_key:key()}),onSuccess:refresh});
 const post=useMutation({mutationFn:(s:Aggregate)=>call("post_festival_edition_settlement",{p_settlement_id:s.id,p_expected_version:s.settlement_version,p_idempotency_key:key()}),onSuccess:refresh});
 if(q.isLoading)return <p role="status"><Loader2 className="inline animate-spin"/> Loading authoritative settlement…</p>;
 if(q.error)return <Notice error={q.error}/>;
 const report=q.data; if(!report)return <Card><CardHeader><CardTitle>Settlement pending</CardTitle></CardHeader><CardContent className="space-y-3"><p>A completed runtime digest and frozen financial evidence are required. Preparation never reads mutable company settings.</p><label className="block text-sm" htmlFor="runtime-digest">Runtime completion digest</label><input id="runtime-digest" className="w-full rounded border bg-background p-2" placeholder="Paste the completion digest"/><Button disabled={prepare.isPending} onClick={()=>prepare.mutate((document.getElementById("runtime-digest") as HTMLInputElement).value)}>Prepare settlement</Button>{prepare.error&&<Notice error={prepare.error}/>}</CardContent></Card>;
 const s=report.settlement;const revenues=report.lines.filter(x=>x.line_kind==="revenue"),costs=report.lines.filter(x=>x.line_kind==="cost");const mutationError=approve.error??post.error;
 return <section className="space-y-5" aria-label="Festival edition settlement"><header><h2 className="text-2xl font-bold">Authoritative settlement</h2><p className="capitalize">{s.state.replaceAll("_"," ")} · version {s.settlement_version}</p></header><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Revenue" value={money(s.gross_revenue_minor,s.currency_code)}/><Metric label="Costs" value={money(s.total_costs_minor,s.currency_code)}/><Metric label="Tax and refunds" value={`${money(s.tax_minor,s.currency_code)} · ${money(s.refunds_minor,s.currency_code)}`}/><Metric label="Profit or loss" value={money(s.net_profit_loss_minor,s.currency_code)}/></div><Card><CardHeader><CardTitle>Reconciliation</CardTitle></CardHeader><CardContent><p className="flex items-center gap-2">{s.reconciliation_status==="blocked"?<AlertTriangle className="text-destructive"/>:<CheckCircle2 className="text-emerald-600"/>}<span className="capitalize">{s.reconciliation_status.replaceAll("_"," ")}</span></p>{s.reconciliation_status==="blocked"&&<p>Approval and posting are disabled until every material discrepancy is resolved.</p>}</CardContent></Card><div className="grid gap-4 lg:grid-cols-2"><Breakdown title="Revenue breakdown" rows={revenues} currency={s.currency_code}/><Breakdown title="Cost breakdown" rows={costs} currency={s.currency_code}/></div>{report.batch&&<Card><CardHeader><CardTitle>Posting recovery</CardTitle></CardHeader><CardContent>{report.batch.state}: {report.batch.completed_items} of {report.batch.expected_items} canonical ledger movements posted.</CardContent></Card>}<div className="flex gap-3">{s.state==="review"&&<Button disabled={s.reconciliation_status==="blocked"||approve.isPending} onClick={()=>approve.mutate(s)}>Approve</Button>}{["approved","recovery_required"].includes(s.state)&&<Button disabled={post.isPending} onClick={()=>post.mutate(s)}>{s.state==="recovery_required"?"Recover posting":"Post settlement"}</Button>}</div>{mutationError&&<Notice error={mutationError}/>}<Card><CardHeader><CardTitle>Audit timeline</CardTitle></CardHeader><CardContent><ol>{report.audit.map(x=><li key={x.id}>{new Date(x.created_at).toLocaleString("en-GB")} · {x.action} · {x.status}</li>)}</ol></CardContent></Card></section>;
}
const Metric=({label,value}:{label:string;value:string})=><Card><CardHeader><CardTitle className="text-sm">{label}</CardTitle></CardHeader><CardContent className="font-semibold">{value}</CardContent></Card>;
const Breakdown=({title,rows,currency}:{title:string;rows:Row[];currency:string})=><Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{rows.length?<ul className="divide-y">{rows.map(x=><li className="flex justify-between gap-3 py-2" key={x.id}><span className="capitalize">{x.category.replaceAll("_"," ")}<small className="block text-muted-foreground">{x.source_type} · {x.cash_state}</small></span><strong>{money(x.net_amount_minor,currency)}</strong></li>)}</ul>:<p>No lines recorded.</p>}</CardContent></Card>;
const Notice=({error}:{error:unknown})=><p className="rounded border border-destructive p-3 text-destructive" role="alert">{message(error)}</p>;
