import { useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { settlementRepository as repository } from "./repository";
import { publicError, type SettlementAggregate, type SettlementLine } from "./model";

const money=(minor:number,currency:string)=>new Intl.NumberFormat("en-GB",{style:"currency",currency}).format(minor/100);
const commandKey=()=>crypto.randomUUID();
export function EditionSettlementWorkspace({companyId,editionId}:{companyId:string;editionId:string}){
 const qc=useQueryClient(), [confirm,setConfirm]=useState<"approve"|"post"|"finalise"|null>(null); const postingKey=useRef<string>();
 const queryKey=["festival-edition-settlement",companyId,editionId];
 const readiness=useQuery({queryKey:[...queryKey,"readiness"],queryFn:()=>repository.readiness(companyId,editionId)});
 const report=useQuery({queryKey,queryFn:()=>repository.read(companyId,editionId)});
 const progress=useQuery({queryKey:[...queryKey,"effects"],queryFn:()=>report.data?.settlement.id?repository.effectProgress(report.data.settlement.id):null,enabled:Boolean(report.data?.settlement.id),refetchInterval:5000});
 const refresh=()=>qc.invalidateQueries({queryKey:["festival-edition-settlement",companyId,editionId]});
 const prepare=useMutation({mutationFn:()=>{if(!readiness.data?.runtimeDigest)throw new Error("FESTIVAL_SETTLEMENT_RUNTIME_INCOMPLETE");return repository.prepare(editionId,readiness.data.runtimeDigest,commandKey())},onSuccess:refresh});
 const approve=useMutation({mutationFn:(s:SettlementAggregate)=>repository.approve(s.id,s.settlement_version,commandKey()),onSuccess:()=>{setConfirm(null);refresh()}});
 const post=useMutation({mutationFn:async(s:SettlementAggregate)=>{postingKey.current??=commandKey();let result=await repository.startPosting(s.id,s.settlement_version,postingKey.current); while(result.pendingItems>0&&result.failedItems===0)result=await repository.postNext(s.id,commandKey()); if(result.pendingItems===0&&result.failedItems===0)result=await repository.finalisePosting(s.id,commandKey()); return result;},onSuccess:(x)=>{if(x.state==="completed")postingKey.current=undefined;setConfirm(null);refresh()}});
 const finalise=useMutation({mutationFn:(s:SettlementAggregate)=>repository.finalise(s.id,s.settlement_version,commandKey()),onSuccess:()=>{postingKey.current=undefined;setConfirm(null);refresh()}});
 const calculate=useMutation({mutationFn:(s:SettlementAggregate)=>repository.applyOutcomes(s.id,s.settlement_version,commandKey()),onSuccess:refresh});
 const retry=useMutation({mutationFn:(s:SettlementAggregate)=>repository.resumeEffects(s.id,"Owner requested retry from settlement workspace"),onSuccess:refresh});
 if(readiness.isLoading||report.isLoading)return <p role="status"><Loader2 className="inline animate-spin"/> Loading authoritative settlement…</p>;
 if(readiness.error||report.error)return <Notice error={readiness.error??report.error}/>;
 if(!report.data){const ready=readiness.data!;return <Card><CardHeader><CardTitle>Settlement readiness</CardTitle></CardHeader><CardContent className="space-y-3"><p>{ready.eligible?"The completed runtime is ready to settle.":"Settlement is not ready."}</p>{ready.blockers.length>0&&<ul>{ready.blockers.map(x=><li key={x}>{x}</li>)}</ul>}<Button disabled={!ready.eligible||prepare.isPending} onClick={()=>prepare.mutate()}>Prepare settlement</Button><details><summary>Technical audit details</summary><code className="break-all">{ready.runtimeDigest??"No completion digest"}</code></details>{prepare.error&&<Notice error={prepare.error}/>}</CardContent></Card>}
 const r=report.data,s=r.settlement,revenues=r.lines.filter(x=>x.line_kind==="revenue"),costs=r.lines.filter(x=>x.line_kind==="cost"),busy=approve.isPending||post.isPending||finalise.isPending;
 return <section className="space-y-5" aria-label="Festival edition settlement"><header><h2 className="text-2xl font-bold">Authoritative settlement</h2><p className="capitalize">{s.state.replaceAll("_"," ")} · version {s.settlement_version}</p></header>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Revenue" value={money(s.gross_revenue_minor,s.currency_code)}/><Metric label="Costs" value={money(s.total_costs_minor,s.currency_code)}/><Metric label="Tax and refunds" value={`${money(s.tax_minor,s.currency_code)} · ${money(s.refunds_minor,s.currency_code)}`}/><Metric label="Accounting profit or loss" value={money(s.net_profit_loss_minor,s.currency_code)}/><Metric label="Actual cash posted" value={money(s.cash_posted_minor,s.currency_code)}/><Metric label="Outstanding receivables" value={money(s.unpaid_receivables_minor,s.currency_code)}/><Metric label="Outstanding payables" value={money(s.unpaid_payables_minor,s.currency_code)}/></div>
 <Card><CardHeader><CardTitle>Reconciliation</CardTitle></CardHeader><CardContent><p className="flex items-center gap-2">{s.reconciliation_status==="blocked"?<AlertTriangle className="text-destructive"/>:<CheckCircle2 className="text-emerald-600"/>}{s.reconciliation_status.replaceAll("_"," ")}</p></CardContent></Card>
 <div className="grid gap-4 lg:grid-cols-2"><Breakdown title="Revenue breakdown" rows={revenues} currency={s.currency_code}/><Breakdown title="Cost breakdown" rows={costs} currency={s.currency_code}/></div>
 {r.batch&&<Card><CardHeader><CardTitle>Posting recovery</CardTitle></CardHeader><CardContent><p>{r.batch.completed_items} of {r.batch.expected_items} ledger movements completed; {r.batch.failed_items} failed and {r.batch.pending_items} remain.</p>{r.batch.failure?.code&&<p>Retry is safe: stable references prevent duplicate transactions. Error category: {r.batch.failure.code}.</p>}</CardContent></Card>}
 {progress.data&&<Card><CardHeader><CardTitle>Outcome effects</CardTitle></CardHeader><CardContent className="space-y-2"><p>{progress.data.outcomeCount>0?"Outcomes calculated":"Awaiting outcome calculation"} · {progress.data.requiredEffectsRemaining>0?"Worker processing":"Effects applied"}</p><div className="flex flex-wrap gap-2 text-sm"><span>Applied {progress.data.countsByStatus.applied??0}</span><span>Not applicable {progress.data.countsByStatus.not_applicable??0}</span><span>Failed {progress.data.countsByStatus.failed??0}</span><span>Recovery required {progress.data.countsByStatus.recovery_required??0}</span><span>Dead letter {progress.data.deadLetterCount}</span><span>{progress.data.taxReconciled?"Tax ready":"Tax pending"}</span><span>{progress.data.finalisationEligible?"Ready to finalise":s.state==="completed"?"Completed":"Not ready to finalise"}</span></div>{progress.data.finalisationBlockers.length>0&&<p className="text-muted-foreground">Blocked by: {progress.data.finalisationBlockers.join(", ")}</p>}{(progress.data.countsByStatus.recovery_required??0)>0&&<Button variant="outline" disabled={retry.isPending} onClick={()=>retry.mutate(s)}>Retry recoverable effects</Button>}</CardContent></Card>}
 {confirm&&<Card><CardHeader><CardTitle>Confirm {confirm}</CardTitle></CardHeader><CardContent className="space-y-2"><p>Revenue {money(s.gross_revenue_minor,s.currency_code)}; costs {money(s.total_costs_minor,s.currency_code)}; tax {money(s.tax_minor,s.currency_code)}; result {money(s.net_profit_loss_minor,s.currency_code)}.</p>{confirm==="post"&&<p>Expected cash in {money(revenues.filter(x=>x.cash_state==="due").reduce((n,x)=>n+x.net_amount_minor,0),s.currency_code)}; expected cash out {money(costs.filter(x=>x.cash_state==="due").reduce((n,x)=>n+x.net_amount_minor,0),s.currency_code)}. Receivables and payables remain outstanding.</p>}<Button disabled={busy} onClick={()=>confirm==="approve"?approve.mutate(s):confirm==="finalise"?finalise.mutate(s):post.mutate(s)}>Confirm</Button><Button variant="outline" disabled={busy} onClick={()=>setConfirm(null)}>Cancel</Button></CardContent></Card>}
 {s.state==="completed"&&<Card><CardHeader><CardTitle>Edition outcomes</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-3"><Metric label="Audience satisfaction" value={`${r.outcomes.find(x=>x.outcome_type==="audience")?.final_score??"—"}/100`}/><Metric label="Average artist satisfaction" value={average(r.outcomes.filter(x=>x.outcome_type==="artist").map(x=>x.final_score))}/><Metric label="Average sponsor satisfaction" value={average(r.outcomes.filter(x=>x.outcome_type==="sponsor").map(x=>x.final_score))}/></CardContent></Card>}
 <div className="flex gap-3">{s.state==="review"&&<Button disabled={busy||s.reconciliation_status==="blocked"} onClick={()=>setConfirm("approve")}>Review approval</Button>}{["approved","posting","recovery_required"].includes(s.state)&&<Button disabled={busy} onClick={()=>setConfirm("post")}>{s.state==="recovery_required"?"Safely retry posting":"Review posting"}</Button>}{["financial_posting_complete","calculating_outcomes"].includes(s.state)&&<Button disabled={busy||calculate.isPending} onClick={()=>calculate.mutate(s)}>Calculate outcomes</Button>}{s.state==="effects_complete"&&<Button disabled={busy||!progress.data?.finalisationEligible} onClick={()=>setConfirm("finalise")}>Finalise settlement</Button>}</div>{(approve.error||post.error||calculate.error||retry.error||finalise.error)&&<Notice error={approve.error??post.error??calculate.error??retry.error??finalise.error}/>} </section>;
}
const average=(values:Array<number|null>)=>{const valid=values.filter((x):x is number=>typeof x==="number");return valid.length?`${(valid.reduce((a,b)=>a+b,0)/valid.length).toLocaleString("en-GB",{maximumFractionDigits:1})}/100`:"—";};
const Metric=({label,value}:{label:string;value:string})=><Card><CardHeader><CardTitle className="text-sm">{label}</CardTitle></CardHeader><CardContent className="font-semibold">{value}</CardContent></Card>;
const Breakdown=({title,rows,currency}:{title:string;rows:SettlementLine[];currency:string})=><Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{rows.length?<ul className="divide-y">{rows.map(x=><li className="flex justify-between gap-3 py-2" key={x.id}><span className="capitalize">{x.category.replaceAll("_"," ")}<small className="block text-muted-foreground">{x.source_type} · {x.cash_state}</small></span><strong>{money(x.net_amount_minor,currency)}</strong></li>)}</ul>:<p>No lines recorded.</p>}</CardContent></Card>;
const Notice=({error}:{error:unknown})=><p className="rounded border border-destructive p-3 text-destructive" role="alert">{publicError(error)}</p>;
