import { calculateCrewEffectiveness, calculateEquipmentReliability, GIG_CREW_ROLES, type CrewAssignmentInput, type EquipmentLoadoutInput } from './gigCrewEquipment';
import { calculateReadinessPerformanceModifier, type ReadinessResult } from './gigReadiness';
import { SOUNDCHECK_TYPES, type ProductionQualityResult, type SoundcheckType } from './gigStageProduction';
import { applyPreshowConsequencesToReadiness, summarizePreshowPerformanceModifiers, type PreshowConsequence } from './gigPreshow';

export type ForecastConfidence = 'low' | 'medium' | 'high';
export type ForecastSeverity = 'low' | 'medium' | 'high' | 'critical';
export type ChecklistStatus = 'complete' | 'warning' | 'missing' | 'blocked' | 'not_applicable';
export type PreparationStatus = 'not_ready' | 'ready_with_risks' | 'ready' | 'fully_prepared';
export interface ForecastRange { low: number; likely: number; high: number }
export interface ForecastRisk { key: string; severity: ForecastSeverity; category: string; title: string; explanation: string; suggestedAction?: string; linkedPreparationSection?: string; impact?: number }
export interface ForecastStrength { key: string; category: string; title: string; explanation: string; linkedPreparationSection?: string; impact?: number }
export interface ChecklistItem { key: string; category: string; status: ChecklistStatus; label: string; explanation: string; blocking: boolean; linkedPreparationSection?: string }

export interface GigForecastInput {
  gigId: string; generatedAt?: string; status?: string | null; capacity: number; ticketPrice: number; ticketsSold?: number | null; fixedFee?: number | null; venueHireCost?: number | null; venueQuality?: number | null; venuePrestige?: number | null; venueAcoustics?: number | null; localPopularity?: number | null; globalFame?: number | null; genreAffinity?: number | null; promotionScore?: number | null; repeatedLocalGigs?: number | null; daysUntilGig?: number | null; readiness: ReadinessResult; crew?: CrewAssignmentInput[]; equipment?: EquipmentLoadoutInput[]; productionQuality?: ProductionQualityResult | null; productionValid?: boolean; soundcheckType?: SoundcheckType; soundcheckValid?: boolean; setlistSongCount?: number; setlistDurationSeconds?: number; slotDurationSeconds?: number; hasEncore?: boolean; songPopularity?: number | null; songQuality?: number | null; performerSkill?: number | null; bandChemistry?: number | null; fatigueScore?: number | null; healthScore?: number | null; recentComparableGigs?: number | null; productionCost?: number | null; soundcheckCost?: number | null; otherCosts?: number | null; otherRevenue?: number | null; merchandiseSpendPerAttendee?: number | null; merchandiseMargin?: number | null; bandFunds?: number | null; preShowConsequences?: PreshowConsequence[]; }

export interface GigForecastSnapshot { gigId: string; generatedAt: string; calculationVersion: number; confidence: ForecastConfidence; confidenceScore: number; expectedAttendance: ForecastRange & { capacity: number; sellThroughPercent: number }; expectedRevenue: { tickets: ForecastRange; merchandise: ForecastRange; other: ForecastRange; total: ForecastRange; guaranteedIncome: number; variableIncomeRange: ForecastRange }; expectedCosts: { venue: number; crew: number; equipment: number; production: number; soundcheck: number; other: number; total: number; committedCosts: number; variableCostRange: ForecastRange }; expectedProfit: ForecastRange; breakEvenAttendance: number | null; expectedPerformanceQuality: ForecastRange & { expectedRating: string }; expectedFanSatisfaction: ForecastRange; expectedCrowdEnergy: ForecastRange & { opening: ForecastRange; midSet: ForecastRange; closing: ForecastRange; encorePotential: ForecastRange }; readinessScore: number; preparationStatus: PreparationStatus; risks: ForecastRisk[]; strengths: ForecastStrength[]; blockingIssues: string[]; warnings: string[]; assumptions: string[]; checklist: ChecklistItem[] }

export const GIG_FORECAST_VERSION = 1;
const clamp = (n: number, min = 0, max = 100) => Math.max(min, Math.min(max, n));
const money = (n: number) => Math.round(n);
const range = (likely: number, width: number, min = 0, max = Number.POSITIVE_INFINITY): ForecastRange => ({ low: Math.round(Math.max(min, likely - width)), likely: Math.round(Math.max(min, Math.min(max, likely))), high: Math.round(Math.min(max, likely + width)) });
const rangeFromValues = (low: number, likely: number, high: number): ForecastRange => ({ low: money(low), likely: money(likely), high: money(high) });
const addRanges = (...rs: ForecastRange[]) => rangeFromValues(rs.reduce((s,r)=>s+r.low,0), rs.reduce((s,r)=>s+r.likely,0), rs.reduce((s,r)=>s+r.high,0));
const mulRange = (r: ForecastRange, m: number) => rangeFromValues(r.low*m, r.likely*m, r.high*m);

function confidence(input: GigForecastInput, risks: ForecastRisk[]) { let score = 72; if (input.readiness.score >= 80) score += 8; if ((input.ticketsSold ?? 0) / Math.max(1, input.capacity) > 0.55) score += 8; if ((input.crew ?? []).some(c => c.attendance === 'pending' || c.attendance === 'conflict')) score -= 12; if ((input.equipment ?? []).length === 0) score -= 10; if ((input.soundcheckType ?? 'none') === 'none') score -= 8; if ((input.productionQuality?.setupRisk ?? 0) > 60) score -= 8; if ((input.daysUntilGig ?? 0) > 30) score -= 8; if ((input.recentComparableGigs ?? 0) > 1) score += 5; score -= risks.filter(r => r.severity === 'critical').length * 14 + risks.filter(r => r.severity === 'high').length * 7; score = clamp(score); return { score: Math.round(score), label: score >= 76 ? 'high' as const : score >= 51 ? 'medium' as const : 'low' as const, width: score >= 76 ? 0.11 : score >= 51 ? 0.18 : 0.28 }; }

export function calculateAttendanceForecast(input: GigForecastInput, widthMultiplier = 0.18) {
  const cap = Math.max(0, Math.round(input.capacity || 0));
  const sold = Math.max(0, Math.min(cap, Math.round(input.ticketsSold ?? 0)));
  const local = input.localPopularity ?? 45, fame = input.globalFame ?? 35, genre = input.genreAffinity ?? 55;
  const venue = ((input.venueQuality ?? 55) + (input.venuePrestige ?? 50)) / 2;
  const promo = input.promotionScore ?? 0;
  const largeVenuePenalty = Math.max(0.55, 1 - Math.log10(Math.max(100, cap) / 1000) * 0.16);
  const pricePressure = Math.max(0.35, Math.min(1.25, 1 - ((input.ticketPrice || 0) - 20) / 90));
  const repeatPenalty = Math.max(0.65, 1 - (input.repeatedLocalGigs ?? 0) * 0.09);
  const readinessLift = 1 + calculateReadinessPerformanceModifier(input.readiness.score) * 0.35;
  const demandScore = clamp(local * 0.36 + fame * 0.2 + genre * 0.14 + venue * 0.11 + promo * 0.12 + input.readiness.score * 0.07);
  const likely = Math.max(sold, Math.min(cap, cap * (0.18 + demandScore / 118) * largeVenuePenalty * pricePressure * repeatPenalty * readinessLift));
  const unsold = cap - sold;
  const low = Math.max(sold, likely - unsold * widthMultiplier);
  const high = Math.min(cap, likely + unsold * widthMultiplier);
  return { low: Math.round(low), likely: Math.round(likely), high: Math.round(high), capacity: cap, sellThroughPercent: cap ? Math.round((likely / cap) * 100) : 0 };
}

export function buildFinalPreparationChecklist(input: GigForecastInput): ChecklistItem[] {
  const crew = input.crew ?? [], equip = input.equipment ?? [];
  const missingCriticalCrew = (['sound_engineer','stage_manager'] as const).filter(r => !crew.some(c => c.role === r && (c.status ?? 'accepted') === 'accepted'));
  const reliability = calculateEquipmentReliability(equip, crew);
  const durationRatio = (input.setlistDurationSeconds ?? 0) / Math.max(1, input.slotDurationSeconds ?? 7200);
  return [
    { key:'setlist_exists', category:'setlist', status:(input.setlistSongCount??0)>0?'complete':'blocked', label:'Setlist exists', explanation:(input.setlistSongCount??0)>0?`${input.setlistSongCount} songs configured.`:'No valid gig setlist has been saved.', blocking:(input.setlistSongCount??0)===0, linkedPreparationSection:'setlist' },
    { key:'duration_fit', category:'setlist', status:durationRatio>1.08?'warning':durationRatio<0.5?'warning':'complete', label:'Duration fits slot', explanation:`Planned duration is ${Math.round((input.setlistDurationSeconds??0)/60)} minutes.`, blocking:false, linkedPreparationSection:'setlist' },
    { key:'encore', category:'setlist', status:input.hasEncore?'complete':'warning', label:'Encore configured where appropriate', explanation:input.hasEncore?'Encore is planned.':'No encore is configured.', blocking:false, linkedPreparationSection:'setlist' },
    { key:'performers', category:'performers', status:input.readiness.blockingIssues.some(i=>i.toLowerCase().includes('performer'))?'blocked':'complete', label:'Required performers assigned', explanation:'Uses gig readiness performer validation.', blocking:input.readiness.blockingIssues.some(i=>i.toLowerCase().includes('performer')), linkedPreparationSection:'performers' },
    { key:'member_condition', category:'performers', status:(input.fatigueScore??75)<35 || (input.healthScore??75)<40?'warning':'complete', label:'Health and fatigue acceptable', explanation:'Member condition is included when available.', blocking:false, linkedPreparationSection:'rehearsal' },
    { key:'critical_crew', category:'crew', status:missingCriticalCrew.length?'warning':'complete', label:'Critical crew roles covered', explanation:missingCriticalCrew.length?`Missing ${missingCriticalCrew.map(r=>GIG_CREW_ROLES[r].label).join(', ')}.`:'Sound engineer and stage manager are covered.', blocking:false, linkedPreparationSection:'crew' },
    { key:'crew_confirmed', category:'crew', status:crew.some(c=>c.attendance==='conflict' || c.attendance==='absent')?'blocked':crew.some(c=>c.attendance==='pending')?'warning':'complete', label:'Crew availability confirmed', explanation:'Accepted crew attendance is checked for conflicts.', blocking:crew.some(c=>c.attendance==='conflict' || c.attendance==='absent'), linkedPreparationSection:'crew' },
    { key:'equipment_present', category:'equipment', status:equip.length?'complete':'blocked', label:'Required equipment present', explanation:equip.length?`${equip.length} loadout items configured.`:'No gig equipment loadout has been configured.', blocking:equip.length===0, linkedPreparationSection:'equipment' },
    { key:'equipment_condition', category:'equipment', status:reliability.score<45?'warning':'complete', label:'Condition acceptable', explanation:`Equipment reliability is ${reliability.score}%.`, blocking:false, linkedPreparationSection:'equipment' },
    { key:'spares', category:'equipment', status:equip.some(e=>e.isSpare)?'complete':'warning', label:'Critical spares available', explanation:equip.some(e=>e.isSpare)?'At least one spare is in the loadout.':'No spare equipment is configured.', blocking:false, linkedPreparationSection:'equipment' },
    { key:'production_valid', category:'production', status:input.productionValid===false?'blocked':'complete', label:'Production plan valid', explanation:input.productionValid===false?'Production is not compatible with the venue.':'Production plan is compatible or not configured.', blocking:input.productionValid===false, linkedPreparationSection:'production' },
    { key:'soundcheck_valid', category:'soundcheck', status:input.soundcheckValid===false?'blocked':(input.soundcheckType??'none')==='none'?'warning':'complete', label:'Soundcheck schedule valid', explanation:(input.soundcheckType??'none')==='none'?'No soundcheck selected.':'Soundcheck fits the preparation timeline.', blocking:input.soundcheckValid===false, linkedPreparationSection:'soundcheck' },
    { key:'finance', category:'finance', status:input.bandFunds != null && input.bandFunds < ((input.venueHireCost??0)+(input.productionCost??0)+(input.soundcheckCost??0))?'warning':'complete', label:'Expected costs understood', explanation:'Committed costs are server-calculated and shown below.', blocking:false, linkedPreparationSection:'finance' },
    { key:'gig_status', category:'schedule', status:['completed','cancelled'].includes(input.status??'')?'blocked':'complete', label:'Gig is performable', explanation:`Gig status is ${input.status ?? 'scheduled'}.`, blocking:['completed','cancelled'].includes(input.status??''), linkedPreparationSection:'schedule' },
  ];
}

export function generateGigForecast(input: GigForecastInput): GigForecastSnapshot {
  const preshowModifiers = summarizePreshowPerformanceModifiers(input.preShowConsequences ?? []);
  const readinessForForecast = input.preShowConsequences?.length ? applyPreshowConsequencesToReadiness(input.readiness, input.preShowConsequences) : input.readiness;
  input = { ...input, readiness: readinessForForecast, otherCosts: Number(input.otherCosts ?? 0) + (input.preShowConsequences ?? []).flatMap(c => c.financialTransactions ?? []).reduce((sum, tx) => sum + Math.max(0, -tx.amount), 0) };
  const assumptions: string[] = []; if (input.localPopularity == null) assumptions.push('Local popularity data was unavailable, so a neutral local-demand estimate was used.'); if (input.promotionScore == null) assumptions.push('No active promotion data was found; the forecast assumes organic demand only.');
  const risks: ForecastRisk[] = [];
  if ((input.ticketPrice || 0) > 45) risks.push({ key:'ticket_price', severity:'medium', category:'attendance', title:'Ticket price may suppress demand', explanation:'The configured ticket price is above the baseline used by attendance demand.', suggestedAction:'Review ticket price', linkedPreparationSection:'finance', impact:12 });
  if (input.readiness.blockingIssues.length) risks.push(...input.readiness.blockingIssues.map((i,idx)=>({ key:`blocking_${idx}`, severity:'critical' as const, category:'readiness', title:'Blocking preparation issue', explanation:i, suggestedAction:'Resolve blocking preparation issue', linkedPreparationSection:'setlist', impact:50 })));
  if ((input.equipment ?? []).length === 0) risks.push({ key:'missing_equipment', severity:'critical', category:'equipment', title:'Missing essential equipment', explanation:'No equipment loadout is configured for the gig.', suggestedAction:'Add required equipment', linkedPreparationSection:'equipment', impact:40 });
  const equipRel = calculateEquipmentReliability(input.equipment ?? [], input.crew ?? []); if (equipRel.score < 45) risks.push({ key:'poor_equipment', severity:'high', category:'equipment', title:'Poor equipment condition', explanation:`Equipment reliability is only ${equipRel.score}%.`, suggestedAction:'Replace or add spare equipment', linkedPreparationSection:'equipment', impact:25 });
  if (input.productionValid === false) risks.push({ key:'production_incompatible', severity:'critical', category:'production', title:'Production exceeds venue capability', explanation:'The selected production plan is not compatible with venue limits.', suggestedAction:'Reduce production package', linkedPreparationSection:'production', impact:35 });
  if (input.soundcheckValid === false) risks.push({ key:'soundcheck_invalid', severity:'critical', category:'soundcheck', title:'Soundcheck cannot fit', explanation:'The soundcheck schedule fails timeline validation.', suggestedAction:'Change soundcheck', linkedPreparationSection:'soundcheck', impact:30 });
  if ((input.fatigueScore ?? 75) < 35) risks.push({ key:'fatigue', severity:'high', category:'performers', title:'Band fatigue is high', explanation:'Low condition reduces likely performance quality.', suggestedAction:'Add rest before the gig', linkedPreparationSection:'schedule', impact:20 });
  const conf = confidence(input, risks); const baseAtt = calculateAttendanceForecast(input, conf.width); const att = { ...baseAtt, low: Math.round(baseAtt.low * (1 + preshowModifiers.attendanceModifier)), likely: Math.round(baseAtt.likely * (1 + preshowModifiers.attendanceModifier)), high: Math.round(Math.min(baseAtt.capacity, baseAtt.high * (1 + preshowModifiers.attendanceModifier))), sellThroughPercent: baseAtt.capacity ? Math.round((baseAtt.likely * (1 + preshowModifiers.attendanceModifier)) / baseAtt.capacity * 100) : 0 };
  if (att.sellThroughPercent < 35 && input.capacity > 500) risks.push({ key:'venue_too_large', severity:'medium', category:'attendance', title:'Venue may be too large', explanation:'Expected sell-through is low for the venue size.', suggestedAction:'Review venue choice or promotion', linkedPreparationSection:'finance', impact:15 });
  const strengths: ForecastStrength[] = [];
  if ((input.localPopularity ?? 45) >= 75) strengths.push({ key:'local_popularity', category:'attendance', title:'Strong local popularity', explanation:'Local popularity is a positive attendance driver.', impact:20 });
  if ((input.preShowConsequences?.length ?? 0) > 0) risks.push({ key:'preshow_incidents', severity:preshowModifiers.performanceModifier < -0.04 ? 'high' : 'medium', category:'preshow', title:'Pre-show incidents affected the plan', explanation:`${input.preShowConsequences?.length ?? 0} pre-show consequence(s) are included in this forecast.`, linkedPreparationSection:'preshow', impact:Math.round(Math.abs(preshowModifiers.performanceModifier)*100) });
  if (input.readiness.score >= 85) strengths.push({ key:'readiness', category:'readiness', title:'Excellent rehearsal readiness', explanation:`Readiness is ${input.readiness.score}.`, impact:22 });
  if (equipRel.score >= 80) strengths.push({ key:'equipment', category:'equipment', title:'High-quality equipment loadout', explanation:`Equipment reliability is ${equipRel.score}%.`, impact:16 });
  if ((input.productionQuality?.score ?? 0) >= 78) strengths.push({ key:'production', category:'production', title:'Strong venue production fit', explanation:'Production quality should support the show.', impact:14 });
  if (att.sellThroughPercent >= 85) strengths.push({ key:'sellout', category:'attendance', title:'Near sell-out attendance', explanation:'Likely attendance is close to venue capacity.', impact:18 });
  const ticketRevenue = mulRange(att, input.ticketPrice || 0); const merchPer = input.merchandiseSpendPerAttendee ?? 4; const merchMargin = input.merchandiseMargin ?? 0.6; const merchandise = mulRange(att, merchPer * merchMargin); const other = rangeFromValues(input.fixedFee ?? input.otherRevenue ?? 0, input.fixedFee ?? input.otherRevenue ?? 0, input.fixedFee ?? input.otherRevenue ?? 0); const totalRevenue = addRanges(ticketRevenue, merchandise, other);
  const crewCost = (input.crew ?? []).reduce((s,c)=>s+(c.coveredByEmployment?0:Number(c.fee??0)),0); const equipCost = (input.equipment ?? []).reduce((s,e)=>s+Number(e.rentalCost??0),0); const venue = Number(input.venueHireCost??0), production = Number(input.productionCost??0), sound = Number(input.soundcheckCost ?? SOUNDCHECK_TYPES[input.soundcheckType ?? 'none'].cost), otherCost = Number(input.otherCosts??0); const totalCost = money(crewCost+equipCost+venue+production+sound+otherCost); const profit = rangeFromValues(totalRevenue.low-totalCost,totalRevenue.likely-totalCost,totalRevenue.high-totalCost);
  if (profit.likely < 0) risks.push({ key:'loss_risk', severity:profit.high < 0?'high':'medium', category:'finance', title:'High committed costs create loss risk', explanation:'Likely revenue does not cover committed costs.', suggestedAction:'Review costs, promotion, or ticket price', linkedPreparationSection:'finance', impact:25 }); else strengths.push({ key:'profit_margin', category:'finance', title:'Strong expected profit margin', explanation:'Likely revenue covers committed costs.', impact:15 });
  const variablePerAttendee = (input.ticketPrice || 0) + merchPer * merchMargin; const breakEvenAttendance = variablePerAttendee > 0 ? Math.ceil(Math.max(0,totalCost - (input.fixedFee ?? input.otherRevenue ?? 0))/variablePerAttendee) : null;
  const crewAvg = (input.crew ?? []).length ? (input.crew ?? []).reduce((s,c)=>s+calculateCrewEffectiveness(c),0)/(input.crew ?? []).length : 45; const density = att.capacity ? att.likely/att.capacity*100 : 0; const soundBenefit = SOUNDCHECK_TYPES[input.soundcheckType ?? 'none'].soundBenefit; const qualityLikely = clamp(preshowModifiers.performanceModifier * 100 + preshowModifiers.soundQualityModifier * 45 + preshowModifiers.productionModifier * 35 + input.readiness.score*0.28 + (input.performerSkill??55)*0.18 + (input.songQuality??55)*0.12 + (input.bandChemistry??55)*0.1 + crewAvg*0.09 + equipRel.quality*0.08 + (input.productionQuality?.score??55)*0.08 + (input.venueAcoustics??55)*0.05 + soundBenefit*0.09 - Math.max(0,50-(input.fatigueScore??75))*0.25 - equipRel.failureRisk*0.04);
  const width = conf.label==='high'?7:conf.label==='medium'?11:16; const performance = { ...range(qualityLikely,width,0,100), expectedRating: qualityLikely>=85?'excellent':qualityLikely>=70?'strong':qualityLikely>=55?'solid':qualityLikely>=40?'uneven':'poor' };
  const satisfactionLikely = clamp(preshowModifiers.fanSatisfactionModifier * 100 + qualityLikely*0.46 + density*0.15 + (input.songPopularity??55)*0.12 + (input.venueQuality??55)*0.1 + (input.genreAffinity??55)*0.07 + (100 - Math.max(0,(input.ticketPrice||0)-20))*0.06 + input.readiness.score*0.04);
  const energyLikely = clamp(preshowModifiers.crowdEnergyModifier * 100 + satisfactionLikely*0.34 + density*0.21 + (input.songPopularity??55)*0.18 + (input.productionQuality?.audienceImpact??0)*0.25 + (input.performerSkill??55)*0.1 + (input.hasEncore?5:-3));
  const checklist = buildFinalPreparationChecklist(input); const blocking = checklist.filter(i=>i.blocking).map(i=>i.explanation); const warningCount = checklist.filter(i=>i.status==='warning').length + risks.filter(r=>['high','critical'].includes(r.severity)).length; const preparationStatus: PreparationStatus = blocking.length?'not_ready': warningCount>=2?'ready_with_risks': input.readiness.score>=88 && warningCount===0?'fully_prepared':'ready';
  return { gigId: input.gigId, generatedAt: input.generatedAt ?? new Date().toISOString(), calculationVersion: GIG_FORECAST_VERSION, confidence: conf.label, confidenceScore: conf.score, expectedAttendance: att, expectedRevenue: { tickets: ticketRevenue, merchandise, other, total: totalRevenue, guaranteedIncome: input.fixedFee ?? input.otherRevenue ?? 0, variableIncomeRange: addRanges(ticketRevenue, merchandise) }, expectedCosts: { venue, crew: money(crewCost), equipment: money(equipCost), production, soundcheck: sound, other: otherCost, total: totalCost, committedCosts: totalCost, variableCostRange: rangeFromValues(0,0,0) }, expectedProfit: profit, breakEvenAttendance, expectedPerformanceQuality: performance, expectedFanSatisfaction: range(satisfactionLikely,width,0,100), expectedCrowdEnergy: { ...range(energyLikely,width,0,100), opening: range(energyLikely-4,width,0,100), midSet: range(energyLikely,width,0,100), closing: range(energyLikely+(input.hasEncore?4:0),width,0,100), encorePotential: range(input.hasEncore?energyLikely+6:energyLikely-8,width,0,100) }, readinessScore: input.readiness.score, preparationStatus, risks: risks.sort((a,b)=>(b.impact??0)-(a.impact??0)).slice(0,8), strengths: strengths.sort((a,b)=>(b.impact??0)-(a.impact??0)).slice(0,8), blockingIssues: [...input.readiness.blockingIssues, ...blocking], warnings: [...input.readiness.warnings, ...risks.filter(r=>r.severity!=='critical').map(r=>r.title)], assumptions, checklist };
}
