import { calculateCrewEffectiveness, calculateEquipmentReliability, type CrewAssignmentInput, type EquipmentLoadoutInput, type GigCrewRole, type EquipmentRole } from './gigCrewEquipment';
import type { GigForecastSnapshot } from './gigForecast';
import type { ReadinessResult } from './gigReadiness';
import type { ProductionQualityResult, ProductionPlanInput, VenueProductionCapabilities, SoundcheckType } from './gigStageProduction';

export type PreshowSessionStatus = 'not_started' | 'open' | 'awaiting_decision' | 'resolved' | 'expired' | 'skipped' | 'locked';
export type PreshowIncidentStatus = 'open' | 'awaiting_decision' | 'resolved' | 'expired' | 'carried_to_performance';
export type PreshowIncidentCategory = 'equipment' | 'crew' | 'performer' | 'production' | 'venue' | 'commercial' | 'media_social' | 'crowd_safety';
export type PreshowIncidentSeverity = 'minor' | 'moderate' | 'major' | 'critical';
export type PreshowDecisionSource = 'player' | 'delegated_staff' | 'automatic_fallback' | 'system';
export type PreshowGigSize = 'small' | 'medium' | 'large' | 'headline' | 'festival';

export interface PreshowTimingConfig { defaultOpenHours: number; smallOpenHours: number; majorOpenHours: number; lockMinutesBeforeStart: number; defaultDecisionMinutes: number; reminderMinutesBeforeDeadline: number }
export interface PreshowGenerationConfig { baseIncidentProbability: number; positiveOpportunityFrequency: number; maxIncidentsByGigSize: Record<PreshowGigSize, number>; categoryWeights: Record<PreshowIncidentCategory, number>; preparationMitigationFactor: number; criticalSeverityCap: number }
export interface PreshowSkillCheckConfig { minChance: number; maxChance: number }
export interface PreshowEffectCaps { readiness: number; performance: number; soundQuality: number; production: number; crowdEnergy: number; fanSatisfaction: number; attendance: number; fatigue: number; health: number }
export interface PreshowConfig { timing: PreshowTimingConfig; generation: PreshowGenerationConfig; skillChecks: PreshowSkillCheckConfig; effectCaps: PreshowEffectCaps; optionCosts: { emergencyRental: number; repairConsumables: number; extraSecurity: number; mediaHandler: number; medicalSupport: number; advertisingPackage: number } }

export const DEFAULT_PRESHOW_CONFIG: PreshowConfig = {
  timing: { defaultOpenHours: 24, smallOpenHours: 24, majorOpenHours: 48, lockMinutesBeforeStart: 30, defaultDecisionMinutes: 90, reminderMinutesBeforeDeadline: 30 },
  generation: { baseIncidentProbability: 0.42, positiveOpportunityFrequency: 0.18, maxIncidentsByGigSize: { small: 1, medium: 2, large: 3, headline: 3, festival: 3 }, categoryWeights: { equipment: 1, crew: 0.9, performer: 0.85, production: 0.85, venue: 0.7, commercial: 0.55, media_social: 0.45, crowd_safety: 0.65 }, preparationMitigationFactor: 0.38, criticalSeverityCap: 0.06 },
  skillChecks: { minChance: 15, maxChance: 92 },
  effectCaps: { readiness: 18, performance: 0.12, soundQuality: 0.1, production: 0.1, crowdEnergy: 0.12, fanSatisfaction: 0.12, attendance: 0.1, fatigue: 18, health: 14 },
  optionCosts: { emergencyRental: 350, repairConsumables: 60, extraSecurity: 220, mediaHandler: 120, medicalSupport: 180, advertisingPackage: 300 },
};

export interface PreshowContext { gigId: string; bandId: string; scheduledAt: string | Date; gigSize?: PreshowGigSize; status?: string | null; capacity?: number | null; ticketsSold?: number | null; readiness: ReadinessResult; forecast?: GigForecastSnapshot | null; crew?: CrewAssignmentInput[]; equipment?: EquipmentLoadoutInput[]; productionQuality?: ProductionQualityResult | null; productionPlan?: ProductionPlanInput | null; venue?: VenueProductionCapabilities | null; soundcheckType?: SoundcheckType; soundcheckValid?: boolean; performerHealth?: number | null; performerFatigue?: number | null; bandFunds?: number | null; unresolvedWarnings?: string[] }
export interface PreshowSkillCheck { baseChance: number; skillContribution: number; equipmentContribution: number; preparationContribution: number; timeContribution: number; difficultyPenalty: number; finalChance: number }
export interface PreshowConsequence { readinessModifier?: number; performanceModifier?: number; soundQualityModifier?: number; productionModifier?: number; crowdEnergyModifier?: number; fanSatisfactionModifier?: number; attendanceModifier?: number; fatigueChanges?: Array<{ targetId?: string; amount: number; reason: string }>; healthChanges?: Array<{ targetId?: string; amount: number; reason: string }>; financialTransactions?: Array<{ amount: number; category: string; description: string; idempotencyKey: string }>; equipmentChanges?: Array<{ role: EquipmentRole; conditionDelta?: number; reliabilityDelta?: number; reason: string }>; setlistChanges?: Array<{ action: 'remove_song' | 'shorten_set' | 'move_song' | 'replace_song'; reason: string }>; flags?: string[] }
export interface PreshowDecisionOption { key: string; label: string; description: string; requiredPermissions: Array<'band_manager' | 'band_leader' | 'tour_manager' | 'crew_lead' | 'admin'>; requirements: string[]; unavailableReason?: string; costPreview?: number; timeRequiredMinutes: number; skillCheck?: PreshowSkillCheck; guaranteedEffects: PreshowConsequence; riskEffects?: PreshowConsequence; resolvesIncident: boolean; createsFollowUp: boolean; requiresConfirmation: boolean; defaultFallback?: boolean }
export interface PreshowIncident { id: string; incidentType: string; category: PreshowIncidentCategory; severity: PreshowIncidentSeverity; title: string; description: string; status: PreshowIncidentStatus; decisionDeadline: string; affectedSystems: string[]; eligibilitySnapshot: { eligible: boolean; explanation: string; inputs: Record<string, unknown> }; generationData: { seed: number; riskScore: number; severityScore: number; preparationScore: number }; options: PreshowDecisionOption[] }

const clamp = (n: number, min = 0, max = 100) => Math.max(min, Math.min(max, n));
const hashSeed = (s: string) => Array.from(s).reduce((h, ch) => (h * 31 + ch.charCodeAt(0)) >>> 0, 2166136261);
const rand = (seed: number, i = 0) => ((seed + i * 1013904223) * 1664525 + 1013904223 >>> 0) / 4294967296;
const iso = (d: Date) => d.toISOString();

export function getPreshowWindow(ctx: Pick<PreshowContext, 'scheduledAt' | 'gigSize'>, config = DEFAULT_PRESHOW_CONFIG) { const start = new Date(ctx.scheduledAt); const openHours = ctx.gigSize === 'small' ? config.timing.smallOpenHours : ['large','headline','festival'].includes(ctx.gigSize ?? '') ? config.timing.majorOpenHours : config.timing.defaultOpenHours; return { opensAt: iso(new Date(start.getTime() - openHours * 3600000)), locksAt: iso(new Date(start.getTime() - config.timing.lockMinutesBeforeStart * 60000)) }; }
export function getPreshowSessionStatus(ctx: PreshowContext, now = new Date(), config = DEFAULT_PRESHOW_CONFIG): PreshowSessionStatus { if (['completed','cancelled','resolved'].includes(ctx.status ?? '')) return 'skipped'; const { opensAt, locksAt } = getPreshowWindow(ctx, config); if (now < new Date(opensAt)) return 'not_started'; if (now >= new Date(ctx.scheduledAt)) return 'locked'; if (now >= new Date(locksAt)) return 'locked'; return 'open'; }

export function calculatePreshowRisk(ctx: PreshowContext) { const crew = ctx.crew ?? []; const equipment = ctx.equipment ?? []; const reliability = calculateEquipmentReliability(equipment, crew); const crewAvg = crew.length ? crew.reduce((s,c)=>s+calculateCrewEffectiveness(c),0)/crew.length : 45; const productionRisk = ctx.productionQuality?.setupRisk ?? 20; const readinessWeakness = 100 - ctx.readiness.score; const healthRisk = Math.max(0, 55 - (ctx.performerHealth ?? 75)) + Math.max(0, 55 - (ctx.performerFatigue ?? 75)) * 0.7; const warningRisk = (ctx.unresolvedWarnings?.length ?? ctx.forecast?.warnings.length ?? 0) * 3; const complexity = (ctx.productionQuality?.score ?? 35) > 75 ? 12 : 0; const raw = readinessWeakness * 0.32 + reliability.failureRisk * 0.18 + Math.max(0, 60 - crewAvg) * 0.18 + productionRisk * 0.14 + healthRisk * 0.1 + warningRisk + complexity; return Math.round(clamp(raw)); }
export function calculatePreparationScore(ctx: PreshowContext) { const crew = ctx.crew ?? []; const equipment = ctx.equipment ?? []; const rel = calculateEquipmentReliability(equipment, crew); const spares = equipment.some(e=>e.isSpare) ? 8 : 0; const soundcheck = ctx.soundcheckType && ctx.soundcheckType !== 'none' && ctx.soundcheckValid !== false ? 7 : 0; const managers = crew.some(c=>c.role === 'tour_manager' && (c.status ?? 'accepted') === 'accepted') ? 6 : 0; return Math.round(clamp(ctx.readiness.score * 0.46 + rel.score * 0.22 + spares + soundcheck + managers + (ctx.productionQuality?.reliability ?? 50) * 0.12)); }
export function calculatePreshowSkillCheck(input: { baseChance: number; relevantSkill?: number; equipmentQuality?: number; preparationScore?: number; minutesUntilDeadline?: number; difficulty?: number }, config = DEFAULT_PRESHOW_CONFIG): PreshowSkillCheck { const skillContribution = ((input.relevantSkill ?? 50) - 50) * 0.32; const equipmentContribution = ((input.equipmentQuality ?? 50) - 50) * 0.18; const preparationContribution = ((input.preparationScore ?? 50) - 50) * 0.22; const timeContribution = Math.max(-12, Math.min(8, ((input.minutesUntilDeadline ?? 60) - 60) / 10)); const difficultyPenalty = input.difficulty ?? 0; const finalChance = Math.round(clamp(input.baseChance + skillContribution + equipmentContribution + preparationContribution + timeContribution - difficultyPenalty, config.skillChecks.minChance, config.skillChecks.maxChance)); return { baseChance: input.baseChance, skillContribution: Math.round(skillContribution), equipmentContribution: Math.round(equipmentContribution), preparationContribution: Math.round(preparationContribution), timeContribution: Math.round(timeContribution), difficultyPenalty, finalChance }; }

function severityFrom(score: number, r: number, config = DEFAULT_PRESHOW_CONFIG): PreshowIncidentSeverity { if (score > 82 && r < config.generation.criticalSeverityCap) return 'critical'; if (score > 66) return 'major'; if (score > 40) return 'moderate'; return 'minor'; }
function deadline(ctx: PreshowContext, minutes: number, config = DEFAULT_PRESHOW_CONFIG) { const lock = new Date(getPreshowWindow(ctx, config).locksAt).getTime(); return iso(new Date(Math.min(new Date(ctx.scheduledAt).getTime() - 35*60000, lock, Date.now() + minutes*60000))); }
function option(key: string, label: string, description: string, partial: Partial<PreshowDecisionOption>): PreshowDecisionOption { return { key, label, description, requiredPermissions: ['band_manager','band_leader','admin'], requirements: [], timeRequiredMinutes: 20, guaranteedEffects: {}, resolvesIncident: true, createsFollowUp: false, requiresConfirmation: false, ...partial }; }

export function generatePreshowIncidents(ctx: PreshowContext, now = new Date(), config = DEFAULT_PRESHOW_CONFIG): PreshowIncident[] { if (getPreshowSessionStatus(ctx, now, config) === 'skipped') return []; const seed = hashSeed(`${ctx.gigId}:${ctx.bandId}:preshow:v1`); const risk = calculatePreshowRisk(ctx); const prep = calculatePreparationScore(ctx); const mitigated = clamp(risk - (prep - 50) * config.generation.preparationMitigationFactor); const max = config.generation.maxIncidentsByGigSize[ctx.gigSize ?? 'medium']; const probability = clamp(config.generation.baseIncidentProbability * 100 + mitigated * 0.45, 0, 92) / 100; const desired = Array.from({length:max}).filter((_,i)=>rand(seed,i) < probability * (1 - i*0.22)).length; const incidents: PreshowIncident[] = []; const add = (incident: Omit<PreshowIncident,'id'|'status'|'decisionDeadline'|'generationData'>, i: number, severityScore = mitigated) => incidents.push({ ...incident, id: `${ctx.gigId}-${incident.incidentType}`, status: 'awaiting_decision', decisionDeadline: deadline(ctx, config.timing.defaultDecisionMinutes - i*15, config), generationData: { seed, riskScore: risk, severityScore: Math.round(severityScore), preparationScore: prep } });
  const rel = calculateEquipmentReliability(ctx.equipment ?? [], ctx.crew ?? []); const crewAvg = (ctx.crew?.length ? ctx.crew.reduce((s,c)=>s+calculateCrewEffectiveness(c),0)/ctx.crew.length : 45); const hasSpare = (role?: EquipmentRole) => (ctx.equipment ?? []).some(e=>e.isSpare && (!role || e.equipmentRole === role)); const hasCrew = (role: GigCrewRole) => (ctx.crew ?? []).some(c=>c.role===role && (c.status ?? 'accepted')==='accepted'); const minutes = Math.max(0, Math.round((new Date(ctx.scheduledAt).getTime() - now.getTime())/60000));
  const candidates = [
    () => (ctx.equipment ?? []).some(e=>e.equipmentRole==='amplifier' && !e.isSpare) ? add({ incidentType:'amplifier_fault', category:'equipment', severity: severityFrom(mitigated + rel.failureRisk*.2, rand(seed,9), config), title:'Amplifier noise during line check', description:'The primary amplifier is producing intermittent noise shortly before setup finishes.', affectedSystems:['equipment','sound_quality','readiness'], eligibilitySnapshot:{eligible:true, explanation:'Generated because an amplifier is assigned in the gig loadout.', inputs:{equipmentRoles:(ctx.equipment??[]).map(e=>e.equipmentRole), reliability:rel.score}}, options:[ option('use_spare','Use the spare amplifier','Swap to the spare already in the loadout.',{requirements:['Spare amplifier in loadout'], unavailableReason:hasSpare('amplifier')?undefined:'No spare amplifier is assigned.', timeRequiredMinutes:10, guaranteedEffects:{soundQualityModifier:-0.01, readinessModifier:1, flags:['amplifier_spare_used']}}), option('technician_repair','Ask technician to repair it','Use the guitar or sound technician for a fast repair.',{requirements:['Guitar technician or sound engineer'], unavailableReason:hasCrew('guitar_technician')||hasCrew('sound_engineer')?undefined:'No relevant technician is assigned.', costPreview:config.optionCosts.repairConsumables, timeRequiredMinutes:35, skillCheck:calculatePreshowSkillCheck({baseChance:58,relevantSkill:crewAvg,equipmentQuality:rel.quality,preparationScore:prep,minutesUntilDeadline:minutes,difficulty:8},config), guaranteedEffects:{financialTransactions:[{amount:-config.optionCosts.repairConsumables,category:'preshow_repair',description:'Amplifier repair consumables',idempotencyKey:`${ctx.gigId}:amplifier_fault:technician_repair`}], soundQualityModifier:0.015}, riskEffects:{performanceModifier:-0.025,soundQualityModifier:-0.025,flags:['amplifier_repair_failed']}, requiresConfirmation:true}), option('rent_venue_amp','Rent venue amplifier','Pay for a guaranteed replacement from the venue.',{requirements:['Band funds for emergency rental'], unavailableReason:(ctx.bandFunds ?? Infinity) >= config.optionCosts.emergencyRental ? undefined:'Insufficient band funds.', costPreview:config.optionCosts.emergencyRental, timeRequiredMinutes:20, guaranteedEffects:{financialTransactions:[{amount:-config.optionCosts.emergencyRental,category:'emergency_rental',description:'Emergency amplifier rental',idempotencyKey:`${ctx.gigId}:amplifier_fault:rent_venue_amp`}], soundQualityModifier:0.005}, requiresConfirmation:true}), option('continue_no_fix','Continue without replacement','Accept degraded sound and carry the risk into the performance.',{timeRequiredMinutes:0, guaranteedEffects:{readinessModifier:-7,performanceModifier:-0.045,soundQualityModifier:-0.06,flags:['unresolved_amplifier_fault']}, resolvesIncident:false, defaultFallback:true})] }, 0) : null,
    () => (ctx.crew ?? []).some(c=>c.workerType==='player' && c.attendance !== 'confirmed') ? add({ incidentType:'player_crew_late', category:'crew', severity: severityFrom(mitigated + 10, rand(seed,10), config), title:'Player crew member has not arrived', description:'A real-player crew assignment is still unconfirmed as the backstage clock runs down.', affectedSystems:['crew','setup_timeline'], eligibilitySnapshot:{eligible:true, explanation:'Generated because at least one assigned player crew member is pending, absent or conflicted.', inputs:{playerCrew:(ctx.crew??[]).filter(c=>c.workerType==='player').length}}, options:[ option('tour_manager_covers','Let tour manager reassign coverage','The tour manager covers the gap with a practical workaround.',{requirements:['Assigned tour manager'], unavailableReason:hasCrew('tour_manager')?undefined:'No tour manager is assigned.', requiredPermissions:['band_manager','band_leader','tour_manager','admin'], timeRequiredMinutes:20, guaranteedEffects:{readinessModifier:1, performanceModifier:-0.005, flags:['crew_gap_reassigned']}}), option('hire_local_hand','Hire local standby crew','Bring in paid venue help for the missing role.',{costPreview:config.optionCosts.extraSecurity, timeRequiredMinutes:25, guaranteedEffects:{financialTransactions:[{amount:-config.optionCosts.extraSecurity,category:'crew_overtime',description:'Local standby crew',idempotencyKey:`${ctx.gigId}:player_crew_late:hire_local_hand`}], readinessModifier:2}, requiresConfirmation:true}), option('work_short','Work short-handed','Proceed with a leaner backstage crew.',{timeRequiredMinutes:0, guaranteedEffects:{readinessModifier:-5,productionModifier:-0.025,performanceModifier:-0.015,flags:['short_handed_crew']}, resolvesIncident:false, defaultFallback:true})] }, 1) : null,
    () => (ctx.performerFatigue ?? 75) < 55 ? add({ incidentType:'performer_fatigue', category:'performer', severity: severityFrom(mitigated + 8, rand(seed,11), config), title:'Performer reports heavy fatigue', description:'A performer needs a lower-stress plan before doors open.', affectedSystems:['health','fatigue','performance'], eligibilitySnapshot:{eligible:true, explanation:'Generated because performer fatigue/condition data is below the safe preparation threshold.', inputs:{performerFatigue:ctx.performerFatigue}}, options:[ option('rest_backstage','Rest backstage','Cut distractions and preserve energy before the show.',{timeRequiredMinutes:45, guaranteedEffects:{fatigueChanges:[{amount:5,reason:'Backstage rest'}], crowdEnergyModifier:-0.005, flags:['rested_backstage']}}), option('shorten_set','Shorten the set','Use the existing setlist flow to remove the most demanding segment.',{requirements:['Valid gig setlist'], timeRequiredMinutes:20, guaranteedEffects:{setlistChanges:[{action:'shorten_set',reason:'Fatigue mitigation'}], fatigueChanges:[{amount:8,reason:'Reduced stage load'}], fanSatisfactionModifier:-0.025}, requiresConfirmation:true}), option('push_through','Push through unchanged','Avoid disruption but carry fatigue risk into the performance.',{timeRequiredMinutes:0, guaranteedEffects:{healthChanges:[{amount:-4,reason:'Performed while fatigued'}], performanceModifier:-0.035, flags:['fatigue_unmitigated']}, resolvesIncident:false, defaultFallback:true})] }, 2) : null,
    () => ctx.productionPlan && ctx.productionPlan.effectsPackage && ctx.productionPlan.effectsPackage !== 'none' ? add({ incidentType:'effects_restriction', category:'production', severity: severityFrom(mitigated + (ctx.productionQuality?.setupRisk ?? 0)*.2, rand(seed,12), config), title:'Venue restricts a production effect', description:'Venue staff request a safer version of the planned effects package.', affectedSystems:['production','venue','crowd_energy'], eligibilitySnapshot:{eligible:true, explanation:'Generated because the production plan includes smoke, haze or pyrotechnic effects.', inputs:{effectsPackage:ctx.productionPlan.effectsPackage, allowsPyro:ctx.venue?.allowsPyro}}, options:[ option('downsize_effects','Downsize the effect safely','Remove the restricted cue and preserve the rest of the plan.',{timeRequiredMinutes:15, guaranteedEffects:{productionModifier:-0.02,crowdEnergyModifier:-0.015,flags:['effects_downsized']}}), option('negotiate_venue','Have crew negotiate with venue','Use production staff to preserve part of the effect.',{requirements:['Stage manager or lighting engineer'], unavailableReason:hasCrew('stage_manager')||hasCrew('lighting_engineer')?undefined:'No relevant production lead is assigned.', timeRequiredMinutes:25, skillCheck:calculatePreshowSkillCheck({baseChance:55,relevantSkill:crewAvg,preparationScore:prep,minutesUntilDeadline:minutes,difficulty:12},config), guaranteedEffects:{productionModifier:-0.005}, riskEffects:{productionModifier:-0.035,flags:['venue_negotiation_failed']}}), option('drop_effects','Drop the effect package','Comply immediately and avoid delay.',{timeRequiredMinutes:5, guaranteedEffects:{productionModifier:-0.04,crowdEnergyModifier:-0.025,flags:['effects_removed']}, defaultFallback:true})] }, 3) : null,
    () => (ctx.forecast?.expectedAttendance.sellThroughPercent ?? ((ctx.ticketsSold??0)/Math.max(1,ctx.capacity??1)*100)) < 45 ? add({ incidentType:'last_minute_advertising', category:'commercial', severity:'minor', title:'Promoter offers last-minute advertising', description:'A local promoter can push the gig today, but it will cost money and backstage attention.', affectedSystems:['attendance','finance','fatigue'], eligibilitySnapshot:{eligible:true, explanation:'Generated because expected sell-through is weak and tickets are still relevant.', inputs:{sellThrough:ctx.forecast?.expectedAttendance.sellThroughPercent, ticketsSold:ctx.ticketsSold, capacity:ctx.capacity}}, options:[ option('buy_ads','Buy the advertising package','Spend on a final promotional push.',{costPreview:config.optionCosts.advertisingPackage, timeRequiredMinutes:30, guaranteedEffects:{attendanceModifier:0.045,fanSatisfactionModifier:0.005,financialTransactions:[{amount:-config.optionCosts.advertisingPackage,category:'promotion',description:'Last-minute advertising package',idempotencyKey:`${ctx.gigId}:last_minute_advertising:buy_ads`}]}, requiresConfirmation:true}), option('quick_social_push','Do a free social push','Use band channels without spending cash.',{timeRequiredMinutes:20, guaranteedEffects:{attendanceModifier:0.015,fatigueChanges:[{amount:-2,reason:'Promo distraction'}]}}), option('decline_ads','Decline and focus on show','Protect preparation time.',{timeRequiredMinutes:0, guaranteedEffects:{flags:['declined_last_minute_ads']}, defaultFallback:true})] }, 4, mitigated*.5) : null,
  ];
  for (let i=0; i<candidates.length && incidents.length<desired; i++) candidates[(Math.floor(rand(seed,i+20)*candidates.length)+i)%candidates.length]();
  return incidents.slice(0, desired);
}

export function applyPreshowConsequencesToReadiness(readiness: ReadinessResult, consequences: PreshowConsequence[], config = DEFAULT_PRESHOW_CONFIG): ReadinessResult { const modifier = Math.round(clamp(consequences.reduce((s,c)=>s+(c.readinessModifier??0),0), -config.effectCaps.readiness, config.effectCaps.readiness)); const score = Math.round(clamp(readiness.score + modifier)); const factor = { key:'preshowIncidents', label:'Pre-show incidents', score: clamp(70 + modifier * 2), weight:0.08, status: modifier < -4 ? 'warning' as const : modifier > 2 ? 'positive' as const : 'neutral' as const, explanation:`Resolved and unresolved pre-show decisions adjusted readiness by ${modifier} point(s).` }; return { ...readiness, score, rating: score >= 90 ? 'legendary' : score >= 70 ? 'excellent' : score >= 50 ? 'good' : score >= 30 ? 'average' : 'poor', factors:[...readiness.factors, factor], warnings:[...readiness.warnings, ...(modifier<0?[`Pre-show incident consequences reduced readiness by ${Math.abs(modifier)}.`]:[])] }; }
export function summarizePreshowPerformanceModifiers(consequences: PreshowConsequence[], config = DEFAULT_PRESHOW_CONFIG) { const sum = (key: keyof PreshowConsequence, cap: number) => Math.max(-cap, Math.min(cap, consequences.reduce((s,c)=>s+Number(c[key] ?? 0),0))); return { performanceModifier: sum('performanceModifier', config.effectCaps.performance), soundQualityModifier: sum('soundQualityModifier', config.effectCaps.soundQuality), productionModifier: sum('productionModifier', config.effectCaps.production), crowdEnergyModifier: sum('crowdEnergyModifier', config.effectCaps.crowdEnergy), fanSatisfactionModifier: sum('fanSatisfactionModifier', config.effectCaps.fanSatisfaction), attendanceModifier: sum('attendanceModifier', config.effectCaps.attendance), flags: consequences.flatMap(c=>c.flags ?? []) }; }
