export type MasteryCurveKey = "mastery_standard" | "mastery_professional" | "mastery_elite";
export type MasterySystemKey = "songwriting" | "recording" | "live_gig" | "rehearsal" | "teaching" | "production" | "business" | "wellness";
export type MasteryRankName = "Eligible" | "Specialist" | "Expert" | "Master" | "Virtuoso";

export interface MasteryUnlockRequirement { type: "primary_skill_level" | "lifetime_skill_xp" | "supporting_skill_level" | "activity_count" | "achievement" | "attribute_threshold" | "role_experience"; sourceKey: string; requiredValue: number | string; hidden?: boolean; }
export interface SkillSpecialisation { id: string; skillId: string; slug: string; name: string; description: string; isActive: boolean; isHidden: boolean; masteryRankCap: number; displayOrder: number; iconKey: string; balanceVersion: string; recommendedSystems: MasterySystemKey[]; }
export interface SpecialisationPrerequisite { specialisationId: string; prerequisiteType: MasteryUnlockRequirement["type"] | "prior_specialisation"; sourceKey: string; requiredValue: number | string; isHidden?: boolean; }
export interface SpecialisationEffect { specialisationId: string; rankRequired: number; systemKey: MasterySystemKey; effectKey: string; effectValue: number; effectCap: number; description: string; }
export interface MasteryChallenge { id: string; specialisationId: string; rankRequired: number; challengeType: "successful_gigs" | "high_quality_recordings" | "difficult_songwriting_projects" | "teaching_sessions" | "venue_tier" | "consistency_streak" | "genre_diverse_work"; targetValue: number; metadata: Record<string, unknown>; isActive: boolean; }
export interface PlayerMasteryProgress { profileId: string; skillId: string; specialisationId: string; masteryXp: number; masteryRank: number; selectedAt?: string; lastProgressAt?: string; challengeProgress?: Record<string, number>; }
export interface MasteryRewardEvent { profileId: string; skillId: string; specialisationId: string; source: "gig" | "recording" | "songwriting" | "teaching" | "challenge" | "migration"; sourceRecordId: string; baseXp: number; difficulty: number; quality: number; durationMinutes?: number; repetitionCount?: number; idempotencyKey: string; }

export const MASTERY_BALANCE_VERSION = "mastery_v1.0.0";
export const MASTERY_RANK_NAMES: MasteryRankName[] = ["Eligible", "Specialist", "Expert", "Master", "Virtuoso"];
export const MASTERY_CURVES: Record<MasteryCurveKey, number[]> = {
  mastery_standard: [0, 1500, 6000, 18000, 48000],
  mastery_professional: [0, 2200, 8500, 26000, 70000],
  mastery_elite: [0, 3200, 12500, 40000, 110000],
};

export const SKILL_MASTERY_CONFIG = {
  guitar: { supportsMastery: true, masteryCategory: "instrument", masteryRankCap: 4, masteryCurveKey: "mastery_professional" as MasteryCurveKey, masteryDisplayOrder: 10, masteryUnlockRequirements: [{ type: "primary_skill_level", sourceKey: "guitar", requiredValue: 100 }, { type: "lifetime_skill_xp", sourceKey: "guitar", requiredValue: 210000 }, { type: "supporting_skill_level", sourceKey: "performance", requiredValue: 60 }] },
  vocals: { supportsMastery: true, masteryCategory: "vocal", masteryRankCap: 4, masteryCurveKey: "mastery_professional" as MasteryCurveKey, masteryDisplayOrder: 20, masteryUnlockRequirements: [{ type: "primary_skill_level", sourceKey: "vocals", requiredValue: 100 }, { type: "lifetime_skill_xp", sourceKey: "vocals", requiredValue: 210000 }, { type: "supporting_skill_level", sourceKey: "performance", requiredValue: 60 }] },
  songwriting: { supportsMastery: true, masteryCategory: "creative", masteryRankCap: 4, masteryCurveKey: "mastery_elite" as MasteryCurveKey, masteryDisplayOrder: 30, masteryUnlockRequirements: [{ type: "primary_skill_level", sourceKey: "songwriting", requiredValue: 100 }, { type: "lifetime_skill_xp", sourceKey: "songwriting", requiredValue: 240000 }, { type: "supporting_skill_level", sourceKey: "creativity", requiredValue: 55 }] },
  production: { supportsMastery: true, masteryCategory: "studio", masteryRankCap: 4, masteryCurveKey: "mastery_elite" as MasteryCurveKey, masteryDisplayOrder: 40, masteryUnlockRequirements: [{ type: "primary_skill_level", sourceKey: "production", requiredValue: 100 }, { type: "lifetime_skill_xp", sourceKey: "production", requiredValue: 240000 }, { type: "supporting_skill_level", sourceKey: "technical", requiredValue: 60 }] },
} as const;

export const SKILL_SPECIALISATIONS: SkillSpecialisation[] = [
  { id: "guitar_live", skillId: "guitar", slug: "live-guitar", name: "Live Guitar", description: "Recovery, endurance and stage reliability for guitar-led gigs.", isActive: true, isHidden: false, masteryRankCap: 4, displayOrder: 10, iconKey: "guitar", balanceVersion: MASTERY_BALANCE_VERSION, recommendedSystems: ["live_gig", "rehearsal"] },
  { id: "guitar_studio", skillId: "guitar", slug: "studio-guitar", name: "Studio Guitar", description: "Consistent takes, tone choices and reduced retake waste in recording sessions.", isActive: true, isHidden: false, masteryRankCap: 4, displayOrder: 20, iconKey: "sliders", balanceVersion: MASTERY_BALANCE_VERSION, recommendedSystems: ["recording", "production"] },
  { id: "vocals_frontperson", skillId: "vocals", slug: "frontperson", name: "Frontperson", description: "Crowd recovery, stage command and momentum management without improving instrumental accuracy.", isActive: true, isHidden: false, masteryRankCap: 4, displayOrder: 30, iconKey: "mic", balanceVersion: MASTERY_BALANCE_VERSION, recommendedSystems: ["live_gig", "teaching"] },
  { id: "vocals_studio", skillId: "vocals", slug: "studio-vocals", name: "Studio Vocals", description: "Vocal consistency, harmony blend and retake efficiency for studio work.", isActive: true, isHidden: false, masteryRankCap: 4, displayOrder: 40, iconKey: "waveform", balanceVersion: MASTERY_BALANCE_VERSION, recommendedSystems: ["recording"] },
  { id: "songwriting_composition", skillId: "songwriting", slug: "composition", name: "Composition", description: "Structural consistency and realised potential for complex songs.", isActive: true, isHidden: false, masteryRankCap: 4, displayOrder: 50, iconKey: "music", balanceVersion: MASTERY_BALANCE_VERSION, recommendedSystems: ["songwriting", "teaching"] },
  { id: "songwriting_hooks", skillId: "songwriting", slug: "commercial-hooks", name: "Commercial Hooks", description: "Accessibility and memorable hook craft without boosting technical completion directly.", isActive: true, isHidden: false, masteryRankCap: 4, displayOrder: 60, iconKey: "sparkles", balanceVersion: MASTERY_BALANCE_VERSION, recommendedSystems: ["songwriting", "business"] },
  { id: "production_mixing", skillId: "production", slug: "mixing", name: "Mixing", description: "Engineering judgement, session consistency and professional studio reputation.", isActive: true, isHidden: false, masteryRankCap: 4, displayOrder: 70, iconKey: "audio-lines", balanceVersion: MASTERY_BALANCE_VERSION, recommendedSystems: ["recording", "production"] },
  { id: "production_hidden_experimental", skillId: "production", slug: "experimental-production", name: "Experimental Production", description: "Hidden path for unusual high-quality cross-genre studio work.", isActive: true, isHidden: true, masteryRankCap: 4, displayOrder: 80, iconKey: "flask", balanceVersion: MASTERY_BALANCE_VERSION, recommendedSystems: ["recording", "songwriting"] },
];

export const SPECIALISATION_PREREQUISITES: SpecialisationPrerequisite[] = SKILL_SPECIALISATIONS.flatMap((s) => [
  { specialisationId: s.id, prerequisiteType: "primary_skill_level", sourceKey: s.skillId, requiredValue: 100 },
  { specialisationId: s.id, prerequisiteType: "activity_count", sourceKey: s.recommendedSystems[0], requiredValue: s.isHidden ? 75 : 25, isHidden: s.isHidden },
]);

export const SPECIALISATION_EFFECTS: SpecialisationEffect[] = [
  { specialisationId: "guitar_live", rankRequired: 1, systemKey: "live_gig", effectKey: "minor_error_recovery", effectValue: 0.015, effectCap: 0.08, description: "Improves recovery from small live guitar mistakes." },
  { specialisationId: "guitar_live", rankRequired: 2, systemKey: "live_gig", effectKey: "timing_variance_reduction", effectValue: 0.02, effectCap: 0.08, description: "Reduces guitar timing variance during difficult sets." },
  { specialisationId: "guitar_studio", rankRequired: 1, systemKey: "recording", effectKey: "retake_waste_reduction", effectValue: 0.015, effectCap: 0.08, description: "Reduces guitar retake waste in valid studio sessions." },
  { specialisationId: "vocals_frontperson", rankRequired: 1, systemKey: "live_gig", effectKey: "crowd_recovery", effectValue: 0.015, effectCap: 0.08, description: "Improves crowd retention after a weak song." },
  { specialisationId: "vocals_studio", rankRequired: 1, systemKey: "recording", effectKey: "vocal_consistency", effectValue: 0.015, effectCap: 0.08, description: "Improves vocal take consistency; does not replace required vocal roles." },
  { specialisationId: "songwriting_composition", rankRequired: 1, systemKey: "songwriting", effectKey: "structure_consistency", effectValue: 0.015, effectCap: 0.08, description: "Improves structural consistency for songwriting projects." },
  { specialisationId: "songwriting_hooks", rankRequired: 1, systemKey: "songwriting", effectKey: "accessibility_contribution", effectValue: 0.015, effectCap: 0.08, description: "Improves hook accessibility contribution only." },
  { specialisationId: "production_mixing", rankRequired: 1, systemKey: "recording", effectKey: "engineering_consistency", effectValue: 0.015, effectCap: 0.08, description: "Improves engineering consistency in configured recording systems." },
];

export const MASTERY_CHALLENGES: MasteryChallenge[] = SKILL_SPECIALISATIONS.filter((s) => !s.isHidden).flatMap((s) => [
  { id: `${s.id}_rank1`, specialisationId: s.id, rankRequired: 1, challengeType: s.recommendedSystems.includes("live_gig") ? "successful_gigs" : s.recommendedSystems.includes("recording") ? "high_quality_recordings" : "difficult_songwriting_projects", targetValue: 5, metadata: { minimumQuality: 70 }, isActive: true },
  { id: `${s.id}_rank2`, specialisationId: s.id, rankRequired: 2, challengeType: "consistency_streak", targetValue: 3, metadata: { minimumQuality: 75 }, isActive: true },
  { id: `${s.id}_rank3`, specialisationId: s.id, rankRequired: 3, challengeType: "teaching_sessions", targetValue: 8, metadata: { uniqueStudents: 4, diminishingReturns: true }, isActive: true },
  { id: `${s.id}_rank4`, specialisationId: s.id, rankRequired: 4, challengeType: "genre_diverse_work", targetValue: 6, metadata: { minimumQuality: 80 }, isActive: true },
]);

export function getSpecialisationsForSkill(skillId: string, includeHidden = false) { return SKILL_SPECIALISATIONS.filter((s) => s.skillId === skillId && s.isActive && (includeHidden || !s.isHidden)).sort((a, b) => a.displayOrder - b.displayOrder); }
export function getMasteryXpForRank(specialisation: SkillSpecialisation | string, rank: number): number { const spec = typeof specialisation === "string" ? SKILL_SPECIALISATIONS.find((s) => s.id === specialisation) : specialisation; const curveKey = spec ? SKILL_MASTERY_CONFIG[spec.skillId as keyof typeof SKILL_MASTERY_CONFIG]?.masteryCurveKey ?? "mastery_standard" : "mastery_standard"; return MASTERY_CURVES[curveKey][Math.max(0, Math.min(4, Math.floor(rank)))] ?? Infinity; }
export function getCumulativeMasteryXp(specialisation: SkillSpecialisation | string, rank: number): number { return getMasteryXpForRank(specialisation, rank); }
export function getMasteryRankFromXp(specialisation: SkillSpecialisation | string, xp: number): number { const spec = typeof specialisation === "string" ? SKILL_SPECIALISATIONS.find((s) => s.id === specialisation) : specialisation; const cap = spec?.masteryRankCap ?? 4; const safeXp = Math.max(0, Math.floor(Number.isFinite(xp) ? xp : 0)); let rank = 0; for (let next = 1; next <= cap; next += 1) if (safeXp >= getCumulativeMasteryXp(spec ?? "", next)) rank = next; return rank; }
export function getMasteryProgress(specialisation: SkillSpecialisation | string, xp: number) { const rank = getMasteryRankFromXp(specialisation, xp); const cap = (typeof specialisation === "string" ? SKILL_SPECIALISATIONS.find((s) => s.id === specialisation) : specialisation)?.masteryRankCap ?? 4; const current = getCumulativeMasteryXp(specialisation, rank); const next = rank >= cap ? current : getCumulativeMasteryXp(specialisation, rank + 1); const intoRank = Math.max(0, xp - current); const needed = Math.max(0, next - current); return { rank, rankName: MASTERY_RANK_NAMES[rank], currentRankXp: current, nextRankXp: next, xpIntoRank: intoRank, xpForNextRank: needed, progressPercent: needed > 0 ? Math.min(100, (intoRank / needed) * 100) : 100, isMaxRank: rank >= cap }; }
export function calculateMasteryRewardXp(event: MasteryRewardEvent): number { const relevance = event.difficulty < 0.35 || event.quality < 0.55 ? 0 : 1; const qualityScalar = Math.min(1.4, Math.max(0, event.quality)); const difficultyScalar = Math.min(1.5, Math.max(0, event.difficulty)); const durationScalar = Math.min(1.25, Math.max(0.5, (event.durationMinutes ?? 60) / 60)); const repetitionPenalty = [1, 0.7, 0.45, 0.25, 0.1][Math.min(4, Math.max(0, event.repetitionCount ?? 0))]; return Math.floor(Math.max(0, event.baseXp * relevance * qualityScalar * difficultyScalar * durationScalar * repetitionPenalty)); }
export function getApplicableMasteryEffects(progress: PlayerMasteryProgress[], systemKey: MasterySystemKey): SpecialisationEffect[] { return progress.flatMap((p) => SPECIALISATION_EFFECTS.filter((e) => e.specialisationId === p.specialisationId && e.systemKey === systemKey && e.rankRequired <= p.masteryRank)).map((e) => ({ ...e, effectValue: Math.min(e.effectValue, e.effectCap) })); }
export function getTotalDirectMasteryAdvantage(effects: SpecialisationEffect[]): number { return Math.min(0.1, effects.reduce((sum, effect) => sum + Math.min(effect.effectValue, effect.effectCap), 0)); }
export function canSelectSpecialisation(existingForSkill: PlayerMasteryProgress[], specialisation: SkillSpecialisation): boolean { if (!specialisation.isActive) return false; return existingForSkill.length === 0 || existingForSkill.some((p) => p.specialisationId === specialisation.id); }
export function respecialiseMasteryXp(xp: number, retention = 0.75): number { return Math.floor(Math.max(0, xp) * Math.min(0.8, Math.max(0.7, retention))); }
