import type { GigViewerReplay } from "../../events/types";
import type { GigExperienceDTO } from "../../types";
import type { DerivedPlaybackState } from "./PlaybackController";
import { buildEntityLayout, type EntityLayout } from "./EntityLayout";
import type { Size } from "./Viewport";
import { selectVenuePreset, scaleVenuePreset } from "./VenueLayout";

export class CanvasRenderer {
  private ctx: CanvasRenderingContext2D; private size: Size = { width: 1, height: 1 }; private dpr = 1; private layout: EntityLayout | null = null;
  constructor(private canvas: HTMLCanvasElement, private replay: GigViewerReplay, private experience: GigExperienceDTO | null, private reducedMotion: boolean) { const ctx = canvas.getContext("2d"); if (!ctx) throw new Error("Canvas is unavailable"); this.ctx = ctx; }
  resize(size: Size) { this.size = { width: Math.max(280, size.width), height: Math.max(220, size.height) }; this.dpr = Math.max(1, Math.min(2, window.devicePixelRatio || 1)); this.canvas.width = Math.floor(this.size.width * this.dpr); this.canvas.height = Math.floor(this.size.height * this.dpr); this.canvas.style.width = `${this.size.width}px`; this.canvas.style.height = `${this.size.height}px`; this.ctx.setTransform(this.dpr, 0, 0, this.dpr, 0, 0); this.layout = buildEntityLayout({ replay: this.replay, experience: this.experience, size: this.size, reducedMotion: this.reducedMotion }); }
  render(state: DerivedPlaybackState) { const ctx = this.ctx; const size = this.size; if (!this.layout) this.resize(size); const preset = scaleVenuePreset(selectVenuePreset({ capacity: this.experience?.gig.venue.capacity }), size); ctx.clearRect(0, 0, size.width, size.height); ctx.fillStyle = "#111827"; ctx.fillRect(0, 0, size.width, size.height); ctx.fillStyle = "#1f2937"; ctx.fillRect(preset.audience.x, preset.audience.y, preset.audience.width, preset.audience.height); ctx.fillStyle = "#374151"; preset.entrances.forEach((p) => { ctx.beginPath(); ctx.arc(p.x, p.y, 14, 0, Math.PI * 2); ctx.fill(); }); ctx.fillStyle = "#3f2f20"; ctx.fillRect(preset.stage.x, preset.stage.y, preset.stage.width, preset.stage.height); ctx.fillStyle = "#6b7280"; preset.barriers.forEach((r) => ctx.fillRect(r.x, r.y, r.width, r.height)); ctx.fillStyle = "#9ca3af"; ctx.beginPath(); ctx.arc(preset.backstage.x, preset.backstage.y, 10, 0, Math.PI * 2); ctx.fill(); const intensity = this.reducedMotion ? 0 : Math.min(1, (state.crowdEnergy ?? 25) / 100); const pulse = this.reducedMotion ? 0 : Math.sin(state.positionMs / 300) * 1.2 * intensity; (this.layout?.crowd ?? []).forEach((c, i) => { ctx.fillStyle = i % 3 === 0 ? "#60a5fa" : i % 3 === 1 ? "#a78bfa" : "#f472b6"; ctx.globalAlpha = .55 + intensity * .35; ctx.beginPath(); ctx.arc(c.x, c.y, Math.max(2, Math.min(5, c.weight / 80)) + pulse, 0, Math.PI * 2); ctx.fill(); }); ctx.globalAlpha = 1; (this.layout?.performers ?? []).forEach((p) => { ctx.fillStyle = state.performerFocusId === p.id ? "#fde047" : "#f8fafc"; ctx.strokeStyle = "#111827"; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(p.x, p.y, 16, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.fillStyle = "#111827"; ctx.font = "bold 10px sans-serif"; ctx.textAlign = "center"; ctx.textBaseline = "middle"; ctx.fillText(p.initials, p.x, p.y); }); if (state.activeEvent?.visualPayload.type === "spotlight" || state.activeEvent?.visualPayload.type === "moment_effect") { ctx.strokeStyle = "rgba(250, 204, 21, .75)"; ctx.lineWidth = 4; ctx.beginPath(); ctx.arc(size.width / 2, preset.stage.y + preset.stage.height / 2, 48 + (this.reducedMotion ? 0 : Math.sin(state.positionMs / 180) * 8), 0, Math.PI * 2); ctx.stroke(); } ctx.fillStyle = "rgba(15,23,42,.78)"; ctx.fillRect(preset.labelSafe.x, preset.labelSafe.y, preset.labelSafe.width, preset.labelSafe.height); ctx.fillStyle = "#f8fafc"; ctx.font = "bold 14px sans-serif"; ctx.textAlign = "left"; ctx.fillText(`${label(state.activePhase)}${state.currentSongTitle ? ` · ${state.currentSongTitle}` : ""}`, preset.labelSafe.x + 10, preset.labelSafe.y + 24); if (state.activeEvent?.visualPayload.type === "result_reveal") { ctx.fillStyle = "rgba(22, 163, 74, .86)"; ctx.fillRect(size.width * .25, size.height * .42, size.width * .5, 52); ctx.fillStyle = "white"; ctx.textAlign = "center"; ctx.font = "bold 18px sans-serif"; ctx.fillText("Result ready", size.width / 2, size.height * .42 + 31); } }
  destroy() { this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height); }
}
function label(phase: string) { return phase.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()); }
