import type { GigViewerEvent, GigViewerReplay } from "../../events/types";
import type { GigExperienceDTO, ReportMetric } from "../../types";
import { sanitizedEvents } from "./PlaybackController";

export type SongPhase = "waiting" | "intro" | "performing" | "peak" | "ending" | "between_songs" | "completed";
export type CrowdMood = "disappointed" | "quiet" | "attentive" | "engaged" | "energetic" | "ecstatic";
export type CrowdReaction = "still" | "sway" | "bounce" | "jump" | "wave" | "cheer_pulse" | "disappointed_settling" | "disperse";
export const CROWD_ENERGY_THRESHOLDS = [
  { max: 19, mood: "disappointed", label: "Disappointed" },
  { max: 39, mood: "quiet", label: "Quiet" },
  { max: 54, mood: "attentive", label: "Attentive" },
  { max: 69, mood: "engaged", label: "Engaged" },
  { max: 84, mood: "energetic", label: "Energetic" },
  { max: 100, mood: "ecstatic", label: "Ecstatic" },
] as const;
export interface SongSegment { id: string | null; title: string; position: number; score: number | null; energyBefore: number | null; energyAfter: number | null; startMs: number; endMs: number; introEndMs: number; peakStartMs: number; endingStartMs: number; nextTitle: string | null; isOpener: boolean; isFinale: boolean; isBest: boolean; isWeakest: boolean; isEncore: boolean; isTurningPoint: boolean; introEventIndex: number; highlightBadges: string[] }
export interface Highlight { id: string; title: string; description: string; importance: GigViewerEvent["importance"]; songId: string | null; performerId: string | null; energyDelta: number | null; offsetMs: number; visualEffect: string | null }
export interface StoryModel { events: GigViewerEvent[]; songs: SongSegment[]; highlights: Highlight[]; turningPoint: SongSegment | null; resultOffsetMs: number | null; encoreEvent: GigViewerEvent | null; finaleEvent: GigViewerEvent | null; bestSong: SongSegment | null; weakestSong: SongSegment | null }
export interface StorySnapshot { song: (SongSegment & { phase: SongPhase; elapsedMs: number; remainingMs: number }) | null; crowdEnergy: number; crowdMood: CrowdMood; crowdMoodLabel: string; reaction: CrowdReaction; activeHighlight: Highlight | null; activeCommentary: Array<{ id: string; text: string; importance: GigViewerEvent["importance"]; announce: boolean }>; performerFocusId: string | null; resultVisible: boolean; finaleActive: boolean; encoreActive: boolean }

export function clampEnergy(value: unknown, fallback = 50) { return Math.max(0, Math.min(100, Math.round(typeof value === "number" && Number.isFinite(value) ? value : fallback))); }
export function crowdMoodForEnergy(value: unknown) { const energy = clampEnergy(value); const row = CROWD_ENERGY_THRESHOLDS.find((t) => energy <= t.max) ?? CROWD_ENERGY_THRESHOLDS[2]; return { energy, mood: row.mood as CrowdMood, label: row.label }; }
export function interpolateEnergy(before: number | null | undefined, after: number | null | undefined, progress: number, reducedMotion = false) { const b = clampEnergy(before); const a = clampEnergy(after, b); const p = reducedMotion ? (progress >= 1 ? 1 : 0) : Math.max(0, Math.min(1, progress)); return clampEnergy(b + (a - b) * p); }
export function buildStoryModel(replay: GigViewerReplay, experience: GigExperienceDTO | null): StoryModel {
  const events = sanitizedEvents(replay.events);
  const songEvents = events.map((event, index) => ({ event, index })).filter(({ event }) => event.visualPayload.type === "song_start");
  const scores = new Map((experience?.songs ?? []).map((s) => [s.songId ?? s.id, metricNumber(s.performanceScore)]));
  const bestScore = maxMetric(experience?.songs.map((s) => metricNumber(s.performanceScore)) ?? []);
  const weakestScore = minMetric(experience?.songs.map((s) => metricNumber(s.performanceScore)) ?? []);
  const songs: SongSegment[] = songEvents.map(({ event, index }, i) => {
    const nextSong = songEvents[i + 1]?.event;
    const reaction = events.find((e) => e.songId === event.songId && e.scheduledOffsetMs > event.scheduledOffsetMs && e.visualPayload.type === "crowd_reaction");
    const endMs = nextSong?.scheduledOffsetMs ?? events.find((e) => ["encore_decided", "finale_started", "result_revealed"].includes(e.eventType) && e.scheduledOffsetMs > event.scheduledOffsetMs)?.scheduledOffsetMs ?? event.scheduledOffsetMs + event.durationMs;
    const length = Math.max(1, endMs - event.scheduledOffsetMs); const id = event.visualPayload.type === "song_start" ? event.visualPayload.songId : event.songId ?? null; const score = scores.get(id ?? "") ?? null;
    return { id, title: event.visualPayload.type === "song_start" ? event.visualPayload.title || "Untitled song" : "Untitled song", position: event.visualPayload.type === "song_start" ? event.visualPayload.position + 1 : i + 1, score, energyBefore: reaction?.crowdEnergyBefore ?? event.crowdEnergyBefore ?? null, energyAfter: reaction?.crowdEnergyAfter ?? event.crowdEnergyAfter ?? null, startMs: event.scheduledOffsetMs, endMs, introEndMs: event.scheduledOffsetMs + length * .2, peakStartMs: event.scheduledOffsetMs + length * .65, endingStartMs: event.scheduledOffsetMs + length * .85, nextTitle: nextSong?.visualPayload.type === "song_start" ? nextSong.visualPayload.title : null, isOpener: i === 0, isFinale: i === songEvents.length - 1, isBest: score !== null && bestScore !== null && score === bestScore, isWeakest: score !== null && weakestScore !== null && score === weakestScore && bestScore !== weakestScore, isEncore: false, isTurningPoint: false, introEventIndex: index, highlightBadges: [] };
  });
  const turningPoint = detectTurningPoint(songs); if (turningPoint) { const s = songs.find((x) => x.startMs === turningPoint.startMs); if (s) s.isTurningPoint = true; }
  const highlights = buildHighlights(events, songs);
  songs.forEach((song) => { if (song.isOpener) song.highlightBadges.push("Opener"); if (song.isFinale) song.highlightBadges.push("Finale"); if (song.isBest) song.highlightBadges.push("Strongest song"); if (song.isWeakest) song.highlightBadges.push("Most difficult moment"); if (song.isTurningPoint) song.highlightBadges.push("Turning point"); });
  return { events, songs, highlights, turningPoint: songs.find((s) => s.isTurningPoint) ?? null, resultOffsetMs: events.find((e) => e.visualPayload.type === "result_reveal")?.scheduledOffsetMs ?? null, encoreEvent: events.find((e) => e.eventType === "encore_decided") ?? null, finaleEvent: events.find((e) => e.eventType === "finale_started") ?? null, bestSong: songs.find((s) => s.isBest) ?? null, weakestSong: songs.find((s) => s.isWeakest) ?? null };
}
export function deriveStorySnapshot(model: StoryModel, positionMs: number, reducedMotion = false): StorySnapshot {
  const song = currentSong(model.songs, positionMs); const lastEnergyEvent = [...model.events].reverse().find((e) => e.scheduledOffsetMs <= positionMs && (typeof e.crowdEnergyAfter === "number" || typeof e.crowdEnergyBefore === "number"));
  const progress = song ? (positionMs - song.startMs) / Math.max(1, song.endMs - song.startMs) : 1; const energy = song ? interpolateEnergy(song.energyBefore, song.energyAfter, progress, reducedMotion) : clampEnergy(lastEnergyEvent?.crowdEnergyAfter ?? lastEnergyEvent?.crowdEnergyBefore);
  const mood = crowdMoodForEnergy(energy); const activeEvent = [...model.events].reverse().find((e) => e.scheduledOffsetMs <= positionMs); const activeHighlight = model.highlights.find((h) => Math.abs(positionMs - h.offsetMs) <= 4500) ?? null;
  return { song: song ? { ...song, phase: phaseForSong(song, positionMs), elapsedMs: Math.max(0, positionMs - song.startMs), remainingMs: Math.max(0, song.endMs - positionMs) } : null, crowdEnergy: energy, crowdMood: mood.mood, crowdMoodLabel: mood.label, reaction: reactionFor(activeEvent, energy, song), activeHighlight, activeCommentary: commentaryFeed(model, positionMs), performerFocusId: activeEvent?.performerProfileId ?? activeHighlight?.performerId ?? null, resultVisible: model.resultOffsetMs !== null && positionMs >= model.resultOffsetMs, finaleActive: !!model.finaleEvent && positionMs >= model.finaleEvent.scheduledOffsetMs && positionMs < (model.resultOffsetMs ?? Infinity), encoreActive: !!model.encoreEvent && Math.abs(positionMs - model.encoreEvent.scheduledOffsetMs) < 8000 };
}
export function formatCommentary(event: GigViewerEvent): string { const p = event.messageParams ?? {}; const title = String(p.title ?? "the song"); switch (event.messageKey) { case "gig.viewer.venue_opened": return "Venue doors open."; case "gig.viewer.crowd_arrived": return `${p.attendance ?? "The"} fans enter the room.`; case "gig.viewer.performer_entered": return `${p.performer ?? "A performer"} takes the stage${p.role ? ` (${p.role})` : ""}.`; case "gig.viewer.song_started": return `${title} begins.`; case "gig.viewer.song_reaction": return `The crowd responds to ${title}.`; case "gig.viewer.song_highlight": return `${title} becomes a key moment.`; case "gig.viewer.encore_requested": return "The crowd asks for more."; case "gig.viewer.encore_declined": return "The set moves calmly toward the finish."; case "gig.viewer.finale": return "The finale lands."; case "gig.viewer.band_exit": return "The band leaves the stage."; case "gig.viewer.result_reveal": return "The authoritative result is ready."; case "gig.viewer.completed": return "Replay complete."; default: return event.messageKey.startsWith("gig.viewer.") ? event.messageKey.slice(11).replace(/_/g, " ") : "Replay event."; } }
function commentaryFeed(model: StoryModel, pos: number) { const recent = model.events.filter((e) => e.scheduledOffsetMs <= pos && e.scheduledOffsetMs >= pos - 30000 && e.importance !== "ambient"); const out: any[] = []; const seen = new Set<string>(); for (const e of recent) { const text = formatCommentary(e); const key = `${e.messageKey}:${e.songId ?? ""}`; if (seen.has(key) || out.at(-1)?.text === text) continue; seen.add(key); out.push({ id: e.id, text, importance: e.importance, announce: e.importance === "important" || e.importance === "critical" }); } return out.slice(-4); }
function currentSong(songs: SongSegment[], pos: number) { return songs.find((s) => pos >= s.startMs && pos < s.endMs) ?? (pos < (songs[0]?.startMs ?? 0) ? null : songs.at(-1) ?? null); }
export function phaseForSong(song: SongSegment, pos: number): SongPhase { if (pos < song.startMs) return "waiting"; if (pos >= song.endMs) return "completed"; if (pos < song.introEndMs) return "intro"; if (pos >= song.endingStartMs) return "ending"; if (pos >= song.peakStartMs) return "peak"; return "performing"; }
function reactionFor(event: GigViewerEvent | undefined, energy: number, song: SongSegment | null): CrowdReaction { if (event?.visualPayload.type === "crowd_reaction" && event.visualPayload.reaction === "disperse") return "disperse"; const delta = song?.energyAfter != null && song?.energyBefore != null ? song.energyAfter - song.energyBefore : 0; if (delta < -6 || energy < 20) return "disappointed_settling"; if (energy >= 85) return event?.visualPayload.type === "crowd_reaction" && event.visualPayload.reaction === "wave" ? "wave" : "cheer_pulse"; if (energy >= 70) return "jump"; if (energy >= 55) return "bounce"; if (energy >= 35) return "sway"; return "still"; }
function detectTurningPoint(songs: SongSegment[]) { let best: SongSegment | null = null; let bestDelta = 0; for (const s of songs) { if (s.energyBefore == null || s.energyAfter == null) continue; const delta = s.energyAfter - s.energyBefore; if (delta >= 8 && delta > bestDelta) { best = s; bestDelta = delta; } } return best; }
function buildHighlights(events: GigViewerEvent[], songs: SongSegment[]): Highlight[] { return events.filter((e) => e.importance !== "ambient" && ["song_highlight", "encore_decided", "finale_started"].includes(e.eventType)).map((e) => { const song = songs.find((s) => s.id === e.songId) ?? null; const delta = e.crowdEnergyAfter != null && e.crowdEnergyBefore != null ? e.crowdEnergyAfter - e.crowdEnergyBefore : null; return { id: e.id, title: e.eventType === "encore_decided" ? (e.messageKey.includes("requested") ? "Encore requested" : "No encore") : e.eventType === "finale_started" ? "Finale" : song?.isBest ? "Strongest song" : song?.isWeakest ? "Most difficult moment" : "Highlight", description: formatCommentary(e), importance: e.importance, songId: e.songId ?? null, performerId: e.performerProfileId ?? null, energyDelta: delta, offsetMs: e.scheduledOffsetMs, visualEffect: e.visualPayload.type === "moment_effect" ? e.visualPayload.effect : null }; }); }
function metricNumber(metric: ReportMetric<number> | undefined): number | null { return metric?.status === "available" && typeof metric.value === "number" ? metric.value : null; }
function maxMetric(values: Array<number | null>) { const v = values.filter((x): x is number => x !== null); return v.length ? Math.max(...v) : null; }
function minMetric(values: Array<number | null>) { const v = values.filter((x): x is number => x !== null); return v.length ? Math.min(...v) : null; }
