export type FestivalAudience = "player" | "owner" | "admin" | "public";
export type FestivalImplementationStatus =
  | "visible"
  | "read_only"
  | "backend_only"
  | "placeholder"
  | "broken"
  | "legacy";

export interface FestivalFeatureRegistryEntry {
  id: string;
  label: string;
  description: string;
  audience: FestivalAudience[];
  route: string;
  navigationParent: string;
  requiredPermission: string;
  requiredLifecycleStates: string[];
  implementationStatus: FestivalImplementationStatus;
  visibilityCondition: string;
  component: string;
  emptyState: string;
  errorState: string;
}

const ownerStates = [
  "planning",
  "applications_open",
  "booking",
  "setup",
  "live",
  "settling",
  "completed",
];

const entry = (
  id: string,
  label: string,
  description: string,
  audience: FestivalAudience[],
  route: string,
  navigationParent: string,
  requiredPermission: string,
  requiredLifecycleStates: string[],
  implementationStatus: FestivalImplementationStatus,
  visibilityCondition: string,
  component: string,
  emptyState: string,
  errorState: string,
): FestivalFeatureRegistryEntry => ({
  id,
  label,
  description,
  audience,
  route,
  navigationParent,
  requiredPermission,
  requiredLifecycleStates,
  implementationStatus,
  visibilityCondition,
  component,
  emptyState,
  errorState,
});

export const festivalFeatureRegistry: FestivalFeatureRegistryEntry[] = [
  entry(
    "public-discovery",
    "Public discovery",
    "Players browse public canonical Festival companies and annual editions.",
    ["player", "public"],
    "/world/festivals",
    "World > Festivals",
    "none",
    [],
    "visible",
    "public directory route is mounted",
    "PublicFestivalDirectory",
    "No public Festivals yet.",
    "Festival directory failed to load.",
  ),
  entry(
    "public-detail",
    "Public detail",
    "Players inspect a public Festival company or annual edition.",
    ["player", "public"],
    "/world/festivals/:festivalCompanyIdentifier/editions/:editionIdentifier",
    "World > Festivals",
    "none",
    [],
    "visible",
    "public edition route is mounted",
    "PublicFestivalEditionPage",
    "Festival details are not published yet.",
    "Festival detail failed to load.",
  ),
  entry(
    "company-home",
    "Festival company",
    "Permanent Festival company dashboard with balance, reputation, licence and current annual Festival.",
    ["owner"],
    "/festival-company/:festivalCompanyId",
    "Business > My Festivals",
    "company_manager",
    ownerStates,
    "visible",
    "authorised Festival company is returned",
    "FestivalCompanyHome",
    "No current annual Festival is being planned.",
    "Festival company could not be loaded.",
  ),
  entry(
    "upgrades",
    "Upgrades and licence",
    "Eleven permanent Festival upgrade categories and the simplified company licence action.",
    ["owner"],
    "/festival-company/:festivalCompanyId/upgrades",
    "Business > My Festivals",
    "company_manager",
    ownerStates,
    "visible",
    "Festival company management is enabled",
    "FestivalUpgradeWorkspace",
    "No upgrade catalogue is available.",
    "Festival upgrades could not be loaded.",
  ),
  entry(
    "owner-editions",
    "Annual Festivals",
    "Owner annual-edition selector, current event and immutable history.",
    ["owner"],
    "/festival-company/:festivalCompanyId/editions",
    "Business > My Festivals",
    "company_manager",
    ownerStates,
    "visible",
    "authorised Festival company is returned",
    "FestivalCompanyEditionsPage",
    "No annual Festival is currently planned.",
    "Annual Festivals failed to load.",
  ),
  entry(
    "annual-plan",
    "Plan",
    "High-impact annual choices: date, place, vibe, size, duration and marketing.",
    ["owner"],
    "/festival-company/:festivalCompanyId/editions/:editionId",
    "Festival owner > Plan",
    "company_manager",
    ["planning", "applications_open", "booking", "setup"],
    "visible",
    "annual edition is editable",
    "FestivalAnnualPlan",
    "Complete the annual Festival choices.",
    "Annual Festival plan failed to load.",
  ),
  entry(
    "applications",
    "Applications",
    "Player and band applications are reviewed inside the simplified Line-up screen.",
    ["player", "owner"],
    "/festival-company/:festivalCompanyId/editions/:editionId/applications",
    "Festival owner > Line-up",
    "company_manager",
    ["applications_open", "booking", "setup"],
    "visible",
    "exact-edition Line-up workflow is available",
    "SimplifiedFestivalLineupManager",
    "No applications yet.",
    "Applications failed to load.",
  ),
  entry(
    "offers",
    "Offers",
    "Simple artist invitations and offers are managed inside Line-up.",
    ["owner"],
    "/festival-company/:festivalCompanyId/editions/:editionId/applications",
    "Festival owner > Line-up",
    "company_manager",
    ["applications_open", "booking", "setup"],
    "visible",
    "exact-edition Line-up workflow is available",
    "SimplifiedFestivalLineupManager",
    "No offers yet.",
    "Offers failed to load.",
  ),
  entry(
    "contracts",
    "Detailed contracts",
    "Legacy contract detail remains implementation machinery; owners use simple confirmed bookings in Line-up.",
    ["owner", "player"],
    "/festival-company/:festivalCompanyId/editions/:editionId/applications",
    "Automatic Festival simulation",
    "company_manager",
    ["booking", "setup", "live", "settling", "completed"],
    "backend_only",
    "not shown in normal owner navigation",
    "festival artist offer/booking services",
    "No confirmed bookings yet.",
    "Artist booking state failed to load.",
  ),
  entry(
    "setlists",
    "Setlists",
    "Band setlist readiness for confirmed Festival performances.",
    ["player", "owner"],
    "/music/setlists",
    "Band > Repertoire",
    "band_member",
    ["booking", "setup", "live"],
    "read_only",
    "linked from confirmed Festival bookings",
    "SetlistManager",
    "No setlist submitted.",
    "Setlist readiness unavailable.",
  ),
  entry(
    "finance",
    "Tickets & budget",
    "Owner chooses standard ticket price and availability and sees the simplified forecast.",
    ["owner"],
    "/festival-company/:festivalCompanyId/editions/:editionId/finance",
    "Festival owner > Tickets & budget",
    "company_manager",
    ["planning", "applications_open", "booking", "setup"],
    "visible",
    "annual plan foundations are ready",
    "FestivalTicketPlanner",
    "Configure tickets and budget.",
    "Ticket and budget planning failed to load.",
  ),
  entry(
    "live-sessions",
    "Run Festival",
    "One-action readiness and automatic annual Festival simulation.",
    ["owner", "player", "admin"],
    "/festival-company/:festivalCompanyId/editions/:editionId/live",
    "Festival owner > Run Festival",
    "company_manager",
    ["setup", "live", "completed"],
    "visible",
    "exact-edition run readiness is available",
    "FestivalLiveControlRoom",
    "Festival is not ready to run yet.",
    "Festival runtime failed to load.",
  ),
  entry(
    "outcomes",
    "Results",
    "Immutable annual Festival results and company impact.",
    ["owner", "player", "public", "admin"],
    "/festival-company/:festivalCompanyId/editions/:editionId/history",
    "Festival owner > Results",
    "festival_view",
    ["settling", "completed"],
    "read_only",
    "annual Festival has completed or has a result",
    "FestivalEditionHistory",
    "Results are pending.",
    "Festival results failed to load.",
  ),
  entry(
    "stages",
    "Generated stages",
    "Stage requirements are generated automatically from annual choices, licence and upgrades.",
    ["owner", "admin"],
    "/festival-company/:festivalCompanyId/editions/:editionId",
    "Automatic Festival simulation",
    "operations_manager",
    ["planning", "applications_open", "booking", "setup", "live"],
    "backend_only",
    "not shown in normal owner navigation",
    "festival stage projection services",
    "No generated stages yet.",
    "Generated stage data failed.",
  ),
  entry(
    "slots",
    "Generated running order",
    "Stage slots and running order are generated automatically.",
    ["owner", "admin"],
    "/festival-company/:festivalCompanyId/editions/:editionId/live",
    "Automatic Festival simulation",
    "operations_manager",
    ["planning", "booking", "setup", "live"],
    "backend_only",
    "not shown in normal owner navigation",
    "festival schedule projection services",
    "No generated running order yet.",
    "Generated running order failed.",
  ),
  entry(
    "staff",
    "Generated staffing",
    "Staff requirements, suppliers and wages are calculated automatically.",
    ["owner", "admin"],
    "/festival-company/:festivalCompanyId/editions/:editionId/live",
    "Automatic Festival simulation",
    "operations_manager",
    ["planning", "setup", "live"],
    "backend_only",
    "not shown in normal owner navigation",
    "festival operations services",
    "No staffing projection yet.",
    "Staffing projection failed.",
  ),
  entry(
    "permits",
    "Automatic permits",
    "Permit requirements remain automatic simulation detail represented by concise blockers.",
    ["owner", "admin"],
    "/festival-company/:festivalCompanyId/editions/:editionId/live",
    "Automatic Festival simulation",
    "operations_manager",
    ["planning", "setup", "live"],
    "backend_only",
    "not shown in normal owner navigation",
    "festival permit services",
    "No permit blockers.",
    "Permit state failed.",
  ),
  entry(
    "insurance",
    "Automatic insurance",
    "Insurance is automatic simulation detail represented through cost and readiness.",
    ["owner", "admin"],
    "/festival-company/:festivalCompanyId/editions/:editionId/live",
    "Automatic Festival simulation",
    "finance_manager",
    ["planning", "setup", "live"],
    "backend_only",
    "not shown in normal owner navigation",
    "festival insurance services",
    "No insurance blockers.",
    "Insurance state failed.",
  ),
  entry(
    "settlement",
    "Automatic settlement",
    "Detailed settlement batches remain server-side; owners receive the final Results and company impact.",
    ["owner", "player", "admin"],
    "/festival-company/:festivalCompanyId/editions/:editionId/history",
    "Automatic Festival simulation",
    "finance_manager",
    ["settling", "completed"],
    "backend_only",
    "not shown in normal owner navigation",
    "festival settlement services",
    "Settlement has not run yet.",
    "Settlement failed.",
  ),
  entry(
    "legacy-records",
    "Legacy records",
    "Mapped compatibility records and repair evidence.",
    ["admin"],
    "/admin/festivals",
    "Admin > Festivals",
    "admin",
    [],
    "read_only",
    "admin legacy screen is mounted",
    "FestivalLegacyRecordsManagement",
    "No legacy issues.",
    "Legacy issues failed to load.",
  ),
  entry(
    "data-health",
    "Data health",
    "Migration blockers, mapping problems and repair actions.",
    ["admin"],
    "/admin/festivals",
    "Admin > Festivals",
    "admin",
    [],
    "visible",
    "admin data-health screen is mounted",
    "FestivalDataHealthManagement",
    "No open blockers.",
    "Data health failed to load.",
  ),
  entry(
    "admin-catalogue",
    "Admin catalogue",
    "Canonical Festival companies, editions and lifecycle workspace.",
    ["admin"],
    "/admin/festivals",
    "Admin > Festivals",
    "admin",
    [],
    "visible",
    "admin route is mounted",
    "AdminFestivalCatalogue",
    "No Festival companies yet.",
    "Festival catalogue failed to load.",
  ),
  entry(
    "audit-log",
    "Audit log",
    "Audited Festival changes and repair actions.",
    ["admin"],
    "/admin/festivals",
    "Admin > Festivals",
    "admin",
    [],
    "read_only",
    "audit screen is mounted",
    "FestivalAuditLog",
    "No audit events yet.",
    "Audit failed to load.",
  ),
];

export const visibleFestivalFeatures = festivalFeatureRegistry.filter(
  (feature) =>
    feature.implementationStatus === "visible" ||
    feature.implementationStatus === "read_only",
);
