export const FESTIVAL_LAUNCH_STATUSES = ["not_ready","ready_for_launch_preparation","launch_review","launched","tickets_on_sale","sales_paused","sales_closed","cancelled_before_event"] as const;
export type FestivalLaunchStatus=(typeof FESTIVAL_LAUNCH_STATUSES)[number];
export interface FestivalLaunch {id:string;festivalCompanyId:string;launchStatus:FestivalLaunchStatus;publicSlug:string|null;publicVisibility:"private"|"unlisted"|"public";launchVersion:number;launchedAt:string|null;ticketSalesOpenedAt:string|null}
export interface FestivalPublicProfile {festivalCompanyId:string;publicName:string;tagline:string|null;description:string;publicSlug:string;heroImageReference:string|null;logoReference:string|null;ageGuidance:string|null;accessibilitySummary:string|null;transportSummary:string|null;campingSummary:string|null;foodAndDrinkSummary:string|null;termsSummary:string|null;refundPolicySummary:string|null;contactSummary:string|null;publicVersion:number}
export interface FestivalPublicStage{id:string;name:string;capacity:number}
export interface FestivalPublicTimetableEntry{id:string;artistName:string;artistType:"player"|"band"|"npc";artistId:string|null;genre:string|null;fame:number;stageId:string;stageName:string;festivalDate:string;startsAt:string;endsAt:string;headline:boolean}
export interface FestivalPublicSponsor{id:string;name:string;logoReference:string|null;category:string;relationshipLabel:string;sponsoredArea:string|null}
export interface FestivalPublicTicketProduct{id:string;name:string;ticketType:string;productClass:"admission"|"upgrade"|"add_on";accessScope:"single_day"|"date_range"|"full_festival"|"non_admission";accessStartDate:string;accessEndDate:string;priceMinor:number;feeMinor:number;taxMinor:number;totalMinor:number;currency:string;availableQuantity:number;purchaseLimit:number;saleStatus:string}
export interface FestivalPublicEdition{id:string;slug:string;name:string;tagline:string|null;description:string;city:string;country:string;timezone:string;startsAt:string;endsAt:string;festivalType:string|null;vibe:string|null;scale:string|null;heroImageReference:string|null;launchStatus:FestivalLaunchStatus;soldOut:boolean;countdownTarget:string;stages:FestivalPublicStage[];timetable:FestivalPublicTimetableEntry[];sponsors:FestivalPublicSponsor[];ticketProducts:FestivalPublicTicketProduct[];information:{travel:string|null;camping:string|null;accessibility:string|null;foodAndDrink:string|null;ageGuidance:string|null;terms:string|null;refundPolicy:string|null;contact:string|null}}
export interface FestivalIssuedTicket{id:string;saleId:string|null;productId:string;festivalName:string;festivalSlug:string;ticketReference:string;ticketType:string;productClass:string;accessStartDate:string;accessEndDate:string;ownerProfileId:string;holderProfileId:string;status:"valid"|"transferred"|"cancelled"|"refunded"|"used";issuedAt:string}
export interface FestivalTicketPurchaseResult{saleId:string;purchaseRequestId:string;status:"completed";quantity:number;subtotalMinor:number;feeMinor:number;taxMinor:number;totalMinor:number;currency:string;inventoryVersion:number;availableQuantity:number;tickets:FestivalIssuedTicket[]}
export interface FestivalSalesSummary{festivalLaunchId:string;currency:string;ticketsSold:number;ticketsAvailable:number;grossSalesMinor:number;feesMinor:number;taxLiabilityMinor:number;netFestivalReceiptsMinor:number;sellThroughBasisPoints:number;products:unknown[]}
export interface FestivalLaunchActionResult{launch:FestivalLaunch;message:string;idempotent:boolean}

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const object=(v:unknown,code:string):Record<string,unknown>=>{if(!v||typeof v!=="object"||Array.isArray(v))throw new Error(code);return v as Record<string,unknown>};
const value=(o:Record<string,unknown>,k:string)=>o[k]??o[k.replace(/[A-Z]/g,m=>`_${m.toLowerCase()}`)];
const string=(o:Record<string,unknown>,k:string,code:string,nullable=false)=>{const v=value(o,k);if(nullable&&v==null)return null;if(typeof v!=="string"||!v)throw new Error(code);return v};
const uuid=(o:Record<string,unknown>,k:string,c:string,nullable=false)=>{const v=string(o,k,c,nullable);if(v===null)return null;if(!UUID.test(v))throw new Error(c);return v};
const integer=(o:Record<string,unknown>,k:string,c:string)=>{const v=value(o,k);if(!Number.isSafeInteger(v)||Number(v)<0)throw new Error(c);return Number(v)};
const timestamp=(o:Record<string,unknown>,k:string,c:string,nullable=false)=>{const v=string(o,k,c,nullable);if(v!==null&&!Number.isFinite(Date.parse(v)))throw new Error(c);return v};
const date=(o:Record<string,unknown>,k:string,c:string)=>{const v=string(o,k,c);if(!/^\d{4}-\d{2}-\d{2}$/.test(v!))throw new Error(c);return v!};
const array=<T>(o:Record<string,unknown>,k:string,c:string,p:(x:unknown)=>T)=>{const v=value(o,k);if(!Array.isArray(v))throw new Error(c);return v.map(p)};
export const isFestivalUuid=(v:string)=>UUID.test(v);
export function parseFestivalLaunch(v:unknown):FestivalLaunch{const c="malformed_festival_launch_result",o=object(v,c),status=string(o,"launchStatus",c) as FestivalLaunchStatus,visibility=string(o,"publicVisibility",c) as FestivalLaunch["publicVisibility"];if(!FESTIVAL_LAUNCH_STATUSES.includes(status)||!["private","unlisted","public"].includes(visibility))throw new Error(c);return{id:uuid(o,"id",c)!,festivalCompanyId:uuid(o,"festivalCompanyId",c)!,launchStatus:status,publicSlug:string(o,"publicSlug",c,true),publicVisibility:visibility,launchVersion:integer(o,"launchVersion",c),launchedAt:timestamp(o,"launchedAt",c,true),ticketSalesOpenedAt:timestamp(o,"ticketSalesOpenedAt",c,true)}}
export function parseFestivalTicketProduct(v:unknown):FestivalPublicTicketProduct{const c="malformed_festival_ticket_product_result",o=object(v,c),pc=string(o,"productClass",c) as FestivalPublicTicketProduct["productClass"],scope=string(o,"accessScope",c) as FestivalPublicTicketProduct["accessScope"];if(!["admission","upgrade","add_on"].includes(pc)||!["single_day","date_range","full_festival","non_admission"].includes(scope))throw new Error(c);return{id:uuid(o,"id",c)!,name:string(o,"name",c)!,ticketType:string(o,"ticketType",c)!,productClass:pc,accessScope:scope,accessStartDate:date(o,"accessStartDate",c),accessEndDate:date(o,"accessEndDate",c),priceMinor:integer(o,"priceMinor",c),feeMinor:integer(o,"feeMinor",c),taxMinor:integer(o,"taxMinor",c),totalMinor:integer(o,"totalMinor",c),currency:string(o,"currency",c)!,availableQuantity:integer(o,"availableQuantity",c),purchaseLimit:integer(o,"purchaseLimit",c),saleStatus:string(o,"saleStatus",c)!}}
const parseTicket=(v:unknown):FestivalIssuedTicket=>{const c="malformed_festival_ticket_wallet_result",o=object(v,c),status=string(o,"status",c) as FestivalIssuedTicket["status"];if(!["valid","transferred","cancelled","refunded","used"].includes(status))throw new Error(c);return{id:uuid(o,"id",c)!,saleId:uuid(o,"saleId",c,true),productId:uuid(o,"productId",c)!,festivalName:string(o,"festivalName",c)!,festivalSlug:string(o,"festivalSlug",c)!,ticketReference:string(o,"ticketReference",c)!,ticketType:string(o,"ticketType",c)!,productClass:string(o,"productClass",c)!,accessStartDate:date(o,"accessStartDate",c),accessEndDate:date(o,"accessEndDate",c),ownerProfileId:uuid(o,"ownerProfileId",c)!,holderProfileId:uuid(o,"holderProfileId",c)!,status,issuedAt:timestamp(o,"issuedAt",c)!}};
export function parseFestivalTicketPurchase(v:unknown):FestivalTicketPurchaseResult{const c="malformed_festival_ticket_purchase_result",o=object(v,c);if(string(o,"status",c)!=="completed")throw new Error(c);return{saleId:uuid(o,"saleId",c)!,purchaseRequestId:uuid(o,"purchaseRequestId",c)!,status:"completed",quantity:integer(o,"quantity",c),subtotalMinor:integer(o,"subtotalMinor",c),feeMinor:integer(o,"feeMinor",c),taxMinor:integer(o,"taxMinor",c),totalMinor:integer(o,"totalMinor",c),currency:string(o,"currency",c)!,inventoryVersion:integer(o,"inventoryVersion",c),availableQuantity:integer(o,"availableQuantity",c),tickets:array(o,"tickets",c,parseTicket)}}
export const parseFestivalTicketWallet=(v:unknown)=>{const c="malformed_festival_ticket_wallet_result";if(!Array.isArray(v))throw new Error(c);return v.map(parseTicket)};
export function parsePublicFestival(v:unknown):FestivalPublicEdition{const c="malformed_public_festival_result",o=object(v,c),info=object(value(o,"information"),c),status=string(o,"launchStatus",c) as FestivalLaunchStatus;if(!FESTIVAL_LAUNCH_STATUSES.includes(status))throw new Error(c);return{id:uuid(o,"id",c)!,slug:string(o,"slug",c)!,name:string(o,"name",c)!,tagline:string(o,"tagline",c,true),description:string(o,"description",c)!,city:string(o,"city",c)!,country:string(o,"country",c)!,timezone:string(o,"timezone",c)!,startsAt:timestamp(o,"startsAt",c)!,endsAt:timestamp(o,"endsAt",c)!,festivalType:string(o,"festivalType",c,true),vibe:string(o,"vibe",c,true),scale:string(o,"scale",c,true),heroImageReference:string(o,"heroImageReference",c,true),launchStatus:status,soldOut:value(o,"soldOut")===true,countdownTarget:timestamp(o,"countdownTarget",c)!,stages:array(o,"stages",c,x=>{const z=object(x,c);return{id:uuid(z,"id",c)!,name:string(z,"name",c)!,capacity:integer(z,"capacity",c)}}),timetable:array(o,"timetable",c,x=>{const z=object(x,c);return{id:uuid(z,"id",c)!,artistName:string(z,"artistName",c)!,artistType:string(z,"artistType",c) as FestivalPublicTimetableEntry["artistType"],artistId:uuid(z,"artistId",c,true),genre:string(z,"genre",c,true),fame:integer(z,"fame",c),stageId:uuid(z,"stageId",c)!,stageName:string(z,"stageName",c)!,festivalDate:date(z,"festivalDate",c),startsAt:timestamp(z,"startsAt",c)!,endsAt:timestamp(z,"endsAt",c)!,headline:value(z,"headline")===true}}),sponsors:array(o,"sponsors",c,x=>{const z=object(x,c);return{id:uuid(z,"id",c)!,name:string(z,"name",c)!,logoReference:string(z,"logoReference",c,true),category:string(z,"category",c)!,relationshipLabel:string(z,"relationshipLabel",c)!,sponsoredArea:string(z,"sponsoredArea",c,true)}}),ticketProducts:array(o,"ticketProducts",c,parseFestivalTicketProduct),information:{travel:string(info,"travel",c,true),camping:string(info,"camping",c,true),accessibility:string(info,"accessibility",c,true),foodAndDrink:string(info,"foodAndDrink",c,true),ageGuidance:string(info,"ageGuidance",c,true),terms:string(info,"terms",c,true),refundPolicy:string(info,"refundPolicy",c,true),contact:string(info,"contact",c,true)}}}
export const formatFestivalLaunchMoney=(minor:number,currency:string)=>new Intl.NumberFormat("en-GB",{style:"currency",currency}).format(minor/100);
