export const FESTIVAL_RUNTIME_STATUSES = ["created","pre_event","site_setup","ready_to_open","gates_open","live","final_performance_complete","public_closed","site_clearance","runtime_complete","paused","emergency_hold","cancelled","failed"] as const;
export const FESTIVAL_PERFORMANCE_STATUSES = ["scheduled","awaiting_artist","artist_ready","stage_ready","ready","starting","live","completed","delayed","cancelled","abandoned","failed"] as const;
export type FestivalRuntimeStatus = typeof FESTIVAL_RUNTIME_STATUSES[number];
export type FestivalPerformanceStatus = typeof FESTIVAL_PERFORMANCE_STATUSES[number];
export type AttendanceBand = "quiet"|"building"|"busy"|"very_busy"|"near_capacity"|"full";
export interface FestivalRuntimeSession { id:string; festivalLaunchId:string; status:FestivalRuntimeStatus; version:number; gatesOpen:boolean; siteCapacity:number; engineVersion:string; formulaVersion:string }
export interface FestivalRuntimeDay { id:string; runtimeSessionId:string; festivalDate:string; dayNumber:number; startsAt:string; endsAt:string; status:string }
export interface FestivalRuntimeStage { id:string; runtimeSessionId:string; sourceStageId:string; stageName:string; capacity:number; status:string; safetyReady:boolean; crewReady:boolean; version:number }
export interface FestivalRuntimePerformance { id:string; runtimeSessionId:string; runtimeDayId:string; runtimeStageId:string; artistName:string; scheduledStart:string; scheduledEnd:string; actualStart:string|null; actualEnd:string|null; status:FestivalPerformanceStatus; delayMinutes:number; version:number; engineInputSnapshot:unknown; engineResultSnapshot:unknown }
export interface FestivalRuntimeArtistCheckin { id:string; runtimePerformanceId:string; status:"expected"|"checked_in"|"late"|"missing"|"cancelled"|"waived"; checkedInAt:string|null; version:number }
export interface FestivalRuntimeBandMemberAttendance { id:string; runtimePerformanceId:string; profileId:string; status:"expected"|"present"|"late"|"missing"|"substituted"|"excused"; required:boolean; version:number }
export interface FestivalRuntimeStaffCheckin { id:string; runtimeSessionId:string; staffShiftId:string; status:string; safetyCritical:boolean; expectedStart:string; expectedEnd:string; checkedInAt:string|null; checkedOutAt:string|null; version:number }
export interface FestivalRuntimeSupplierCheckin { id:string; runtimeSessionId:string; supplierContractId:string; status:string; essential:boolean; deliveryStart:string|null; deliveryEnd:string|null; arrivedAt:string|null; departedAt:string|null; version:number }
export interface FestivalRuntimeGateSession { id:string; runtimeSessionId:string; runtimeDayId:string; status:string; blockingFailures:string[]; warnings:string[]; version:number }
export interface FestivalRuntimeAttendance { runtimeSessionId:string; runtimeDayId:string; admittedCount:number; exitedCount:number; onsiteCount:number; capacity:number; version:number }
export interface FestivalRuntimeEvent { id:string; eventType:string; entityType:string|null; entityId:string|null; publicPayload:Record<string,unknown>; privatePayload:Record<string,unknown>; createdAt:string }
export interface FestivalRuntimeSnapshot { id:string; runtimeSessionId:string; snapshotType:string; snapshot:Record<string,unknown>; engineVersion:string; formulaVersion:string; createdAt:string }
export interface FestivalRuntimePermissions { canManageFestival:boolean; canManageEmergency:boolean; assignedStageIds:string[]; canCheckInArtist:boolean; canCheckInStaff:boolean; canCheckInSupplier:boolean }
export interface FestivalPublicLiveStatus { festivalLaunchId:string; runtimeStatus:FestivalRuntimeStatus; gatesStatus:"open"|"closed"; currentDay:string|null; attendanceBand:AttendanceBand|null; performances:Array<Pick<FestivalRuntimePerformance,"id"|"artistName"|"scheduledStart"|"scheduledEnd"|"status"|"delayMinutes"> & {stageName:string}>; messages:Record<string,unknown>[] }

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const record=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=="object"||Array.isArray(v))throw new Error("malformed_festival_runtime");return v as Record<string,unknown>};
const str=(v:unknown)=>{if(typeof v!=="string"||!v)throw new Error("malformed_festival_runtime");return v};
const uuid=(v:unknown)=>{const x=str(v);if(!UUID.test(x))throw new Error("malformed_festival_runtime");return x};
const num=(v:unknown)=>{if(typeof v!=="number"||!Number.isFinite(v))throw new Error("malformed_festival_runtime");return v};
const bool=(v:unknown)=>{if(typeof v!=="boolean")throw new Error("malformed_festival_runtime");return v};
const nullableString=(v:unknown)=>v==null?null:str(v);
const array=(v:unknown)=>{if(!Array.isArray(v))throw new Error("malformed_festival_runtime");return v};
const oneOf=<T extends readonly string[]>(v:unknown,values:T):T[number]=>{const x=str(v);if(!values.includes(x))throw new Error("malformed_festival_runtime");return x as T[number]};
export const parseFestivalRuntimeSession=(v:unknown):FestivalRuntimeSession=>{const x=record(v);return{id:uuid(x.id),festivalLaunchId:uuid(x.festivalLaunchId),status:oneOf(x.status,FESTIVAL_RUNTIME_STATUSES),version:num(x.version),gatesOpen:bool(x.gatesOpen),siteCapacity:num(x.siteCapacity),engineVersion:str(x.engineVersion),formulaVersion:str(x.formulaVersion)}};
export const parseFestivalRuntimeDay=(v:unknown):FestivalRuntimeDay=>{const x=record(v);return{id:uuid(x.id),runtimeSessionId:uuid(x.runtime_session_id??x.runtimeSessionId),festivalDate:str(x.festival_date??x.festivalDate),dayNumber:num(x.day_number??x.dayNumber),startsAt:str(x.starts_at??x.startsAt),endsAt:str(x.ends_at??x.endsAt),status:str(x.status)}};
export const parseFestivalRuntimeStage=(v:unknown):FestivalRuntimeStage=>{const x=record(v);return{id:uuid(x.id),runtimeSessionId:uuid(x.runtime_session_id??x.runtimeSessionId),sourceStageId:uuid(x.source_stage_id??x.sourceStageId),stageName:str(x.stage_name??x.stageName),capacity:num(x.capacity),status:str(x.status),safetyReady:bool(x.safety_ready??x.safetyReady),crewReady:bool(x.crew_ready??x.crewReady),version:num(x.version)}};
export const parseFestivalRuntimePerformance=(v:unknown):FestivalRuntimePerformance=>{const x=record(v);return{id:uuid(x.id),runtimeSessionId:uuid(x.runtime_session_id??x.runtimeSessionId),runtimeDayId:uuid(x.runtime_day_id??x.runtimeDayId),runtimeStageId:uuid(x.runtime_stage_id??x.runtimeStageId),artistName:str(x.artist_name??x.artistName),scheduledStart:str(x.scheduled_start??x.scheduledStart),scheduledEnd:str(x.scheduled_end??x.scheduledEnd),actualStart:nullableString(x.actual_start??x.actualStart),actualEnd:nullableString(x.actual_end??x.actualEnd),status:oneOf(x.status,FESTIVAL_PERFORMANCE_STATUSES),delayMinutes:num(x.delay_minutes??x.delayMinutes),version:num(x.version),engineInputSnapshot:x.engine_input_snapshot??x.engineInputSnapshot??null,engineResultSnapshot:x.engine_result_snapshot??x.engineResultSnapshot??null}};
export const parseFestivalPublicLiveStatus=(v:unknown):FestivalPublicLiveStatus=>{const x=record(v);const bands=["quiet","building","busy","very_busy","near_capacity","full"] as const;return{festivalLaunchId:uuid(x.festivalLaunchId),runtimeStatus:oneOf(x.runtimeStatus,FESTIVAL_RUNTIME_STATUSES),gatesStatus:oneOf(x.gatesStatus,["open","closed"] as const),currentDay:nullableString(x.currentDay),attendanceBand:x.attendanceBand==null?null:oneOf(x.attendanceBand,bands),performances:array(x.performances).map(item=>{const p=record(item);return{id:uuid(p.id),artistName:str(p.artistName),stageName:str(p.stageName),scheduledStart:str(p.scheduledStart),scheduledEnd:str(p.scheduledEnd),status:oneOf(p.status,FESTIVAL_PERFORMANCE_STATUSES),delayMinutes:num(p.delayMinutes)}}),messages:array(x.messages).map(record)}};
export const parseFestivalRuntimeList=<T>(value:unknown,parser:(v:unknown)=>T):T[]=>array(value).map(parser);

export const FESTIVAL_CROWD_STATES=["bored","calm","interested","engaged","excited","jumping","ecstatic","tired","frustrated","leaving"] as const;
export const FESTIVAL_WEATHER_STATES=["clear","cloudy","light_rain","heavy_rain","hot","cold","high_wind","storm"] as const;
export const FESTIVAL_INCIDENT_CATEGORIES=["medical","security","crowd","weather","technical","power","stage","artist","staffing","supplier","transport","food_safety","fire_safety"] as const;
export const FESTIVAL_INCIDENT_SEVERITIES=["minor","moderate","major","critical"] as const;
export type FestivalCrowdState=typeof FESTIVAL_CROWD_STATES[number];
export type FestivalRuntimeWeatherState=typeof FESTIVAL_WEATHER_STATES[number];
export type FestivalIncidentCategory=typeof FESTIVAL_INCIDENT_CATEGORIES[number];
export type FestivalIncidentSeverity=typeof FESTIVAL_INCIDENT_SEVERITIES[number];
export interface FestivalRuntimeCrowd {id:string;runtimeSessionId:string;runtimeDayId:string;admittedCount:number;allocatedCount:number;unallocatedCount:number;overallMood:FestivalCrowdState;energy:number;satisfaction:number;formulaVersion:string;lastCalculatedAt:string;version:number}
export interface FestivalStageCrowd {id:string;runtimeSessionId:string;runtimeDayId:string;runtimeStageId:string;currentCrowd:number;stageCapacity:number;crowdShare:number;arrivals:number;departures:number;queueSize:number;mood:FestivalCrowdState;energy:number;satisfaction:number;safetyPressure:number;peakAudience:number;formulaVersion:string;lastCalculatedAt:string;version:number}
export interface FestivalRuntimeWeather {id:string;runtimeSessionId:string;runtimeDayId:string;weatherState:FestivalRuntimeWeatherState;temperatureBand:string;groundCondition:string;operationalImpact:number;formulaVersion:string;calculatedAt:string}
export interface FestivalRuntimeIncident {id:string;runtimeSessionId:string;runtimeDayId:string|null;runtimeStageId:string|null;category:FestivalIncidentCategory;incidentType:string;severity:FestivalIncidentSeverity;trigger:string;status:string;requiredResponse:string;publicSafeSummary:string;privateOperationalDetails:string;formulaVersion:string;resolutionOutcome:string|null;detectedAt:string;resolvedAt:string|null;version:number}
export interface FestivalIncidentOutcome {id:string;incidentId:string;outcome:string;responseQuality:number;responseSeconds:number;staffCoverage:number;equipmentScore:number;operationalEffects:Record<string,unknown>;createdAt:string}
export interface FestivalStaffOutcome {id:string;runtimeSessionId:string;staffCheckinId:string;sourceType:"player"|"npc";attendanceScore:number;latenessMinutes:number;shiftCompletion:number;workload:number;qualificationMatch:number;departmentCoverage:number;incidentResponse:number;roleEffectiveness:number;preliminaryScore:number;formulaVersion:string;capturedAt:string}
export interface FestivalSupplierOutcome {id:string;runtimeSessionId:string;supplierCheckinId:string;arrivalStatus:string;latenessMinutes:number;deliveryCompleteness:number;productQuality:number;serviceQuality:number;reliability:number;contractCompliance:number;operationalImpact:Record<string,unknown>;formulaVersion:string;capturedAt:string}
export interface FestivalSponsorActivation {id:string;runtimeSessionId:string;activationType:string;placement:string;status:"planned"|"ready"|"active"|"completed"|"partially_completed"|"failed"|"cancelled";actualStart:string|null;actualEnd:string|null;audienceExposure:number;deliveryQuality:number|null;staffSupport:number|null;operationalIssues:unknown[];publicVisibility:boolean;version:number}
export interface FestivalVendorSales {id:string;runtimeSessionId:string;runtimeDayId:string;category:"food"|"soft_drinks"|"alcohol_where_game_rules_allow"|"festival_merch"|"artist_merch";productName:string;currencyCode:string;openingStock:number;remainingStock:number;unitPriceMinor:number;unitsSold:number;grossRevenueMinor:number;taxLiabilityMinor:number;costBasisMinor:number;wasteUnits:number;soldOut:boolean;status:"open"|"closed";formulaVersion:string;version:number}
export interface FestivalRuntimeOutcomeSnapshot {id:string;runtimeSessionId:string;snapshot:Record<string,unknown>;engineVersion:string;formulaVersions:Record<string,unknown>;contentDigest:string;createdAt:string}
const field=(x:Record<string,unknown>,snake:string,camel:string)=>x[snake]??x[camel];
export const parseFestivalRuntimeCrowd=(v:unknown):FestivalRuntimeCrowd=>{const x=record(v);return{id:uuid(x.id),runtimeSessionId:uuid(field(x,"runtime_session_id","runtimeSessionId")),runtimeDayId:uuid(field(x,"runtime_day_id","runtimeDayId")),admittedCount:num(field(x,"admitted_count","admittedCount")),allocatedCount:num(field(x,"allocated_count","allocatedCount")),unallocatedCount:num(field(x,"unallocated_count","unallocatedCount")),overallMood:oneOf(field(x,"overall_mood","overallMood"),FESTIVAL_CROWD_STATES),energy:num(x.energy),satisfaction:num(x.satisfaction),formulaVersion:str(field(x,"formula_version","formulaVersion")),lastCalculatedAt:str(field(x,"last_calculated_at","lastCalculatedAt")),version:num(x.version)}};
export const parseFestivalStageCrowd=(v:unknown):FestivalStageCrowd=>{const x=record(v);return{id:uuid(x.id),runtimeSessionId:uuid(field(x,"runtime_session_id","runtimeSessionId")),runtimeDayId:uuid(field(x,"runtime_day_id","runtimeDayId")),runtimeStageId:uuid(field(x,"runtime_stage_id","runtimeStageId")),currentCrowd:num(field(x,"current_crowd","currentCrowd")),stageCapacity:num(field(x,"stage_capacity","stageCapacity")),crowdShare:num(field(x,"crowd_share","crowdShare")),arrivals:num(x.arrivals),departures:num(x.departures),queueSize:num(field(x,"queue_size","queueSize")),mood:oneOf(x.mood,FESTIVAL_CROWD_STATES),energy:num(x.energy),satisfaction:num(x.satisfaction),safetyPressure:num(field(x,"safety_pressure","safetyPressure")),peakAudience:num(field(x,"peak_audience","peakAudience")),formulaVersion:str(field(x,"formula_version","formulaVersion")),lastCalculatedAt:str(field(x,"last_calculated_at","lastCalculatedAt")),version:num(x.version)}};
export const parseFestivalRuntimeWeather=(v:unknown):FestivalRuntimeWeather=>{const x=record(v);return{id:uuid(x.id),runtimeSessionId:uuid(field(x,"runtime_session_id","runtimeSessionId")),runtimeDayId:uuid(field(x,"runtime_day_id","runtimeDayId")),weatherState:oneOf(field(x,"weather_state","weatherState"),FESTIVAL_WEATHER_STATES),temperatureBand:str(field(x,"temperature_band","temperatureBand")),groundCondition:str(field(x,"ground_condition","groundCondition")),operationalImpact:num(field(x,"operational_impact","operationalImpact")),formulaVersion:str(field(x,"formula_version","formulaVersion")),calculatedAt:str(field(x,"calculated_at","calculatedAt"))}};
export const parseFestivalRuntimeIncident=(v:unknown):FestivalRuntimeIncident=>{const x=record(v);return{id:uuid(x.id),runtimeSessionId:uuid(field(x,"runtime_session_id","runtimeSessionId")),runtimeDayId:field(x,"runtime_day_id","runtimeDayId")==null?null:uuid(field(x,"runtime_day_id","runtimeDayId")),runtimeStageId:field(x,"runtime_stage_id","runtimeStageId")==null?null:uuid(field(x,"runtime_stage_id","runtimeStageId")),category:oneOf(x.category,FESTIVAL_INCIDENT_CATEGORIES),incidentType:str(field(x,"incident_type","incidentType")),severity:oneOf(x.severity,FESTIVAL_INCIDENT_SEVERITIES),trigger:str(x.trigger),status:str(x.status),requiredResponse:str(field(x,"required_response","requiredResponse")),publicSafeSummary:str(field(x,"public_safe_summary","publicSafeSummary")),privateOperationalDetails:str(field(x,"private_operational_details","privateOperationalDetails")),formulaVersion:str(field(x,"formula_version","formulaVersion")),resolutionOutcome:nullableString(field(x,"resolution_outcome","resolutionOutcome")),detectedAt:str(field(x,"detected_at","detectedAt")),resolvedAt:nullableString(field(x,"resolved_at","resolvedAt")),version:num(x.version)}};
export const parseFestivalVendorSales=(v:unknown):FestivalVendorSales=>{const x=record(v);return{id:uuid(x.id),runtimeSessionId:uuid(field(x,"runtime_session_id","runtimeSessionId")),runtimeDayId:uuid(field(x,"runtime_day_id","runtimeDayId")),category:oneOf(x.category,["food","soft_drinks","alcohol_where_game_rules_allow","festival_merch","artist_merch"] as const),productName:str(field(x,"product_name","productName")),currencyCode:str(field(x,"currency_code","currencyCode")),openingStock:num(field(x,"opening_stock","openingStock")),remainingStock:num(field(x,"remaining_stock","remainingStock")),unitPriceMinor:num(field(x,"unit_price_minor","unitPriceMinor")),unitsSold:num(field(x,"units_sold","unitsSold")),grossRevenueMinor:num(field(x,"gross_revenue_minor","grossRevenueMinor")),taxLiabilityMinor:num(field(x,"tax_liability_minor","taxLiabilityMinor")),costBasisMinor:num(field(x,"cost_basis_minor","costBasisMinor")),wasteUnits:num(field(x,"waste_units","wasteUnits")),soldOut:bool(field(x,"sold_out","soldOut")),status:oneOf(x.status,["open","closed"] as const),formulaVersion:str(field(x,"formula_version","formulaVersion")),version:num(x.version)}};
export const parseFestivalRuntimeArtistCheckin=(v:unknown):FestivalRuntimeArtistCheckin=>{const x=record(v);return{id:uuid(x.id),runtimePerformanceId:uuid(x.runtime_performance_id??x.runtimePerformanceId),status:oneOf(x.status,["expected","checked_in","late","missing","cancelled","waived"] as const),checkedInAt:nullableString(x.checked_in_at??x.checkedInAt),version:num(x.version)}};
export const parseFestivalRuntimeBandMemberAttendance=(v:unknown):FestivalRuntimeBandMemberAttendance=>{const x=record(v);return{id:uuid(x.id),runtimePerformanceId:uuid(x.runtime_performance_id??x.runtimePerformanceId),profileId:uuid(x.profile_id??x.profileId),status:oneOf(x.status,["expected","present","late","missing","substituted","excused"] as const),required:bool(x.required),version:num(x.version)}};
export const parseFestivalRuntimeStaffCheckin=(v:unknown):FestivalRuntimeStaffCheckin=>{const x=record(v);return{id:uuid(x.id),runtimeSessionId:uuid(x.runtime_session_id??x.runtimeSessionId),staffShiftId:uuid(x.staff_shift_id??x.staffShiftId),status:str(x.status),safetyCritical:bool(x.safety_critical??x.safetyCritical),expectedStart:str(x.expected_start??x.expectedStart),expectedEnd:str(x.expected_end??x.expectedEnd),checkedInAt:nullableString(x.checked_in_at??x.checkedInAt),checkedOutAt:nullableString(x.checked_out_at??x.checkedOutAt),version:num(x.version)}};
export const parseFestivalRuntimeSupplierCheckin=(v:unknown):FestivalRuntimeSupplierCheckin=>{const x=record(v);return{id:uuid(x.id),runtimeSessionId:uuid(x.runtime_session_id??x.runtimeSessionId),supplierContractId:uuid(x.supplier_contract_id??x.supplierContractId),status:str(x.status),essential:bool(x.essential),deliveryStart:nullableString(x.delivery_start??x.deliveryStart),deliveryEnd:nullableString(x.delivery_end??x.deliveryEnd),arrivedAt:nullableString(x.arrived_at??x.arrivedAt),departedAt:nullableString(x.departed_at??x.departedAt),version:num(x.version)}};
export const parseFestivalRuntimeGateSession=(v:unknown):FestivalRuntimeGateSession=>{const x=record(v);return{id:uuid(x.id),runtimeSessionId:uuid(x.runtime_session_id??x.runtimeSessionId),runtimeDayId:uuid(x.runtime_day_id??x.runtimeDayId),status:str(x.status),blockingFailures:array(x.blocking_failures??x.blockingFailures).map(str),warnings:array(x.warnings).map(str),version:num(x.version)}};
export const parseFestivalRuntimeAttendance=(v:unknown):FestivalRuntimeAttendance=>{const x=record(v);return{runtimeSessionId:uuid(x.runtime_session_id??x.runtimeSessionId),runtimeDayId:uuid(x.runtime_day_id??x.runtimeDayId),admittedCount:num(x.admitted_count??x.admittedCount),exitedCount:num(x.exited_count??x.exitedCount),onsiteCount:num(x.onsite_count??x.onsiteCount),capacity:num(x.capacity),version:num(x.version)}};
export const parseFestivalRuntimeEvent=(v:unknown):FestivalRuntimeEvent=>{const x=record(v);return{id:uuid(x.id),eventType:str(x.eventType),entityType:nullableString(x.entityType),entityId:x.entityId==null?null:uuid(x.entityId),publicPayload:record(x.publicPayload),privatePayload:record(x.privatePayload),createdAt:str(x.createdAt)}};
export const parseFestivalRuntimeSnapshot=(v:unknown):FestivalRuntimeSnapshot=>{const x=record(v);return{id:uuid(x.id),runtimeSessionId:uuid(x.runtimeSessionId),snapshotType:str(x.snapshotType),snapshot:record(x.snapshot),engineVersion:str(x.engineVersion),formulaVersion:str(x.formulaVersion),createdAt:str(x.createdAt)}};
export const parseFestivalRuntimePermissions=(v:unknown):FestivalRuntimePermissions=>{const x=record(v);return{canManageFestival:bool(x.canManageFestival),canManageEmergency:bool(x.canManageEmergency),assignedStageIds:array(x.assignedStageIds).map(uuid),canCheckInArtist:bool(x.canCheckInArtist),canCheckInStaff:bool(x.canCheckInStaff),canCheckInSupplier:bool(x.canCheckInSupplier)}};
