import { parseArtistIdentity, type ArtistIdentity } from "./festivalArtistProgramme";

export interface FestivalArtistPermissions { profileId:string; canApplySolo:boolean; managedBandIds:string[] }
export interface FestivalArtistOpportunity { windowId:string; festivalCompanyId:string; name:string; opensAt:string; closesAt:string; eligibleArtistType:string; minimumFame:number|null; maximumFame:number|null; preferredGenres:string[]; stageTypes:string[]; canApply:boolean }
export interface FestivalArtistCandidate { identity:ArtistIdentity; displayName:string; playerNpc:"player"|"npc"; genres:string[]; fame:number; popularity:number; homeCity:string|null; estimatedFeeMinimumMinor:number; estimatedFeeMaximumMinor:number; availabilityState:"available"|"potential_conflict"|"unavailable"|"unknown"; stageSuitability:number; genreFit:number; audienceFit:number; relationshipState:string }
export interface FestivalArtistRevision { id:string; offer_version:number; proposed_by_party:"festival"|"artist"|"system"|"admin"; terms_snapshot:Record<string,unknown> }
export interface FestivalFinancialCommitment { id:string; amount_minor:number; currency_code:string; status:"committed"|"released"|"settled" }
export interface FestivalArtistOpportunitiesResult { openApplications:FestivalArtistOpportunity[]; applications:Record<string,unknown>[]; invitations:Record<string,unknown>[]; offers:Record<string,unknown>[]; bookings:Record<string,unknown>[]; permissions:FestivalArtistPermissions }
export type FestivalArtistActionResult={kind:"application"|"invitation"|"offer"|"booking";application?:Record<string,unknown>;invitation?:Record<string,unknown>;offer?:Record<string,unknown>;booking?:Record<string,unknown>;commitment?:FestivalFinancialCommitment;programme?:unknown};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
const strings=(v:unknown):v is string[]=>Array.isArray(v)&&v.every(x=>typeof x==="string");
const integer=(v:unknown)=>Number.isSafeInteger(v)&&(v as number)>=0;
export function parseFestivalArtistOpportunities(v:unknown):FestivalArtistOpportunitiesResult {if(!object(v)||!Array.isArray(v.openApplications)||!Array.isArray(v.applications)||!Array.isArray(v.invitations)||!Array.isArray(v.offers)||!Array.isArray(v.bookings)||!object(v.permissions)||typeof v.permissions.profileId!=="string"||!UUID.test(v.permissions.profileId)||typeof v.permissions.canApplySolo!=="boolean"||!strings(v.permissions.managedBandIds))throw new Error("malformed_festival_artist_opportunities_result");for(const x of v.openApplications){if(!object(x)||typeof x.windowId!=="string"||!UUID.test(x.windowId)||typeof x.festivalCompanyId!=="string"||!UUID.test(x.festivalCompanyId)||typeof x.name!=="string"||!strings(x.preferredGenres)||!strings(x.stageTypes)||typeof x.canApply!=="boolean")throw new Error("malformed_festival_artist_opportunities_result");}return v as unknown as FestivalArtistOpportunitiesResult}
export function parseFestivalArtistCandidates(v:unknown):{items:FestivalArtistCandidate[];limit:number;offset:number}{if(!object(v)||!Array.isArray(v.items)||!integer(v.limit)||!integer(v.offset))throw new Error("malformed_festival_artist_candidates_result");for(const x of v.items){if(!object(x)||typeof x.displayName!=="string"||!strings(x.genres)||!integer(x.fame)||!integer(x.popularity))throw new Error("malformed_festival_artist_candidates_result");parseArtistIdentity(x.identity)}return v as unknown as {items:FestivalArtistCandidate[];limit:number;offset:number}}
export function parseFestivalArtistActionResult(v:unknown):FestivalArtistActionResult {if(!object(v)||!["application","invitation","offer","booking"].includes(String(v.kind)))throw new Error("malformed_festival_artist_action_result");const entity=v[v.kind as keyof typeof v];if(!object(entity))throw new Error("malformed_festival_artist_action_result");return v as FestivalArtistActionResult}
