export const TIMETABLE_STATUSES = ["not_started","structure_generated","artist_scheduling","operations_scheduling","conflict_review","readiness_review","ready_for_launch_preparation"] as const;
export const SLOT_TYPES = ["performance","changeover","soundcheck","opening_ceremony","closing_ceremony","sponsor_activation","media","maintenance","reserved"] as const;
export type FestivalTimetableStatus=(typeof TIMETABLE_STATUSES)[number];
export type FestivalStageSlotType=(typeof SLOT_TYPES)[number];
export interface FestivalTimetableDay {id:string;festivalDate:string;dayNumber:number;publicOpenAt:string|null;publicCloseAt:string|null;artistAccessAt:string|null;staffAccessAt:string|null;supplierAccessAt:string|null;siteClearAt:string|null;status:"planned"|"locked"}
export interface FestivalStageOperatingWindow{id:string;festivalTimetableDayId:string;stageId:string;opensAt:string;performancesStartAt:string;performancesEndAt:string;curfewAt:string;soundcheckStartAt:string|null;soundcheckEndAt:string|null;status:string}
export interface FestivalStageSlot{id:string;festivalTimetableDayId:string;stageId:string;slotType:FestivalStageSlotType;startsAt:string;endsAt:string;status:"planned"|"locked"|"cancelled";sequenceNumber:number;headlineSlot:boolean;slotVersion:number}
export interface FestivalArtistPerformanceSlot{id:string;stageSlotId:string;artistBookingId:string;artistSource:"profile"|"band"|"npc";profileId:string|null;bandId:string|null;npcArtistId:string|null;performanceDurationMinutes:number;arrivalRequiredAt:string;backstageCallAt:string;stageCallAt:string;performanceStatus:"scheduled"|"removed";suitabilitySnapshot:Record<string,unknown>;availabilitySnapshot:Record<string,unknown>;allocationVersion:number}
export interface FestivalArtistSoundcheck{id:string;artistPerformanceSlotId:string;stageId:string;startsAt:string;endsAt:string;soundcheckType:"full"|"line_check"|"shared_backline"|"headliner_extended"|"none";status:string}
export interface FestivalStageChangeover{id:string;stageId:string;startsAt:string;endsAt:string;requiredMinutes:number;plannedMinutes:number;complexityScore:number;status:string;issues:unknown[]}
export interface FestivalStageManagerAssignment{id:string;stageId:string;festivalDate:string;managerSource:"player"|"npc";profileId:string|null;npcStaffAssignmentId:string|null;startsAt:string;endsAt:string;authorityScope:string[];status:string;assignmentVersion:number}
export interface FestivalOperationalScheduleItem{id:string;itemType:string;startsAt:string;endsAt:string;status:string;stageId:string|null;departmentId:string|null;requiredCoverage:number|null}
export interface FestivalSupplierDeliveryWindow{id:string;supplierContractId:string;deliveryType:string;startsAt:string;endsAt:string;status:string;stageId:string|null}
export interface FestivalSponsorActivationWindow{id:string;sponsorContractId:string;activationType:string;startsAt:string;endsAt:string;status:string;locationReference:string|null}
export interface FestivalScheduleConflict{id:string;code:string;category:string;severity:"info"|"warning"|"blocking";blocking:boolean;entityType:string|null;entityId:string|null;startsAt:string|null;endsAt:string|null;section:string;messageKey:string;safeMetadata:Record<string,unknown>}
export interface FestivalReadinessAssessment{overallScore:number;identityScore:number;siteScore:number;ticketScore:number;artistScore:number;operationsScore:number;sponsorshipScore:number;timetableScore:number;safetyScore:number;financeScore:number;riskScore:number;blockingCount:number;warningCount:number;formulaVersion:number;financialSnapshot:Record<string,unknown>;riskAssessment:unknown[];calculatedAt:string}
export interface FestivalReadinessCheck{id:string;checkCode:string;groupCode:string;status:"passed"|"warning"|"failed"|"not_applicable";blocking:boolean;messageKey:string;entityType:string|null;entityId:string|null;safeMetadata:Record<string,unknown>}
export interface FestivalTimetablePermissions{canManageFestival:boolean;canComplete:boolean;stageManagerStageIds:string[]}
export interface FestivalTimetablePlan{festivalCompanyId:string;festivalSummary:{name:string;startDate:string;endDate:string};timezone:string;status:FestivalTimetableStatus;planningVersion:number;updatedAt:string;days:FestivalTimetableDay[];stageWindows:FestivalStageOperatingWindow[];stageSlots:FestivalStageSlot[];artistAllocations:FestivalArtistPerformanceSlot[];soundchecks:FestivalArtistSoundcheck[];changeovers:FestivalStageChangeover[];stageManagers:FestivalStageManagerAssignment[];operationalItems:FestivalOperationalScheduleItem[];supplierWindows:FestivalSupplierDeliveryWindow[];sponsorActivationWindows:FestivalSponsorActivationWindow[];conflicts:FestivalScheduleConflict[];readinessAssessment:FestivalReadinessAssessment|null;readinessChecks:FestivalReadinessCheck[];permissions:FestivalTimetablePermissions}
export interface FestivalReadinessSnapshot{id:string;snapshotVersion:number;createdAt:string;formulaVersions:Record<string,number>}
export interface FestivalTimetableActionResult extends FestivalTimetablePlan {}

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const obj=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=="object"||Array.isArray(v))throw new Error("malformed_festival_timetable_result");return v as Record<string,unknown>};
const val=(o:Record<string,unknown>,camel:string)=>o[camel]??o[camel.replace(/[A-Z]/g,m=>`_${m.toLowerCase()}`)];
const str=(o:Record<string,unknown>,k:string)=>{const v=val(o,k);if(typeof v!=="string"||!v)return "";return v};
const uuid=(o:Record<string,unknown>,k:string)=>{const v=str(o,k);if(!UUID.test(v))throw new Error("malformed_festival_timetable_result");return v};
const iso=(o:Record<string,unknown>,k:string,nullable=false)=>{const v=val(o,k);if(nullable&&v==null)return null;if(typeof v!=="string"||!Number.isFinite(Date.parse(v)))throw new Error("malformed_festival_timetable_result");return v};
const integer=(o:Record<string,unknown>,k:string)=>{const v=Number(val(o,k));if(!Number.isSafeInteger(v)||v<0)throw new Error("malformed_festival_timetable_result");return v};
const record=(v:unknown)=>obj(v);
const list=<T>(o:Record<string,unknown>,k:string,p:(v:unknown)=>T):T[]=>{const v=val(o,k);if(!Array.isArray(v))throw new Error("malformed_festival_timetable_result");return v.map(p)};
export function isIanaTimezone(value:string){try{return Intl.DateTimeFormat("en-GB",{timeZone:value}).resolvedOptions().timeZone.length>0}catch{return false}}
export function parseFestivalStageSlot(v:unknown):FestivalStageSlot{const o=obj(v),slotType=str(o,"slotType") as FestivalStageSlotType,status=str(o,"status") as FestivalStageSlot["status"];if(!SLOT_TYPES.includes(slotType)||!["planned","locked","cancelled"].includes(status))throw new Error("malformed_festival_timetable_result");return{id:uuid(o,"id"),festivalTimetableDayId:uuid(o,"festivalTimetableDayId"),stageId:uuid(o,"stageId"),slotType,startsAt:iso(o,"startsAt"),endsAt:iso(o,"endsAt"),status,sequenceNumber:integer(o,"sequenceNumber"),headlineSlot:val(o,"headlineSlot")===true,slotVersion:integer(o,"slotVersion")}}
const parseConflict=(v:unknown):FestivalScheduleConflict=>{const o=obj(v),severity=str(o,"severity") as FestivalScheduleConflict["severity"];if(!["info","warning","blocking"].includes(severity)||typeof val(o,"blocking")!=="boolean")throw new Error("malformed_festival_schedule_conflict_result");return{id:uuid(o,"id"),code:str(o,"code"),category:str(o,"category"),severity,blocking:val(o,"blocking") as boolean,entityType:(val(o,"entityType") as string|null)??null,entityId:(val(o,"entityId") as string|null)??null,startsAt:iso(o,"startsAt",true),endsAt:iso(o,"endsAt",true),section:str(o,"section"),messageKey:str(o,"messageKey"),safeMetadata:record(val(o,"safeMetadata")??{})}}
export function parseFestivalTimetablePlan(v:unknown):FestivalTimetablePlan{const o=obj(v),timezone=str(o,"timezone"),status=str(o,"status") as FestivalTimetableStatus,summary=obj(val(o,"festivalSummary")),permissions=obj(val(o,"permissions"));if(!isIanaTimezone(timezone)||!TIMETABLE_STATUSES.includes(status))throw new Error("malformed_festival_timetable_result");const simple=(x:unknown)=>{const z=obj(x);return Object.fromEntries(Object.keys(z).map(k=>[k.replace(/_([a-z])/g,(_,c:string)=>c.toUpperCase()),z[k]])) as Record<string,unknown>};return{festivalCompanyId:uuid(o,"festivalCompanyId"),festivalSummary:{name:str(summary,"name"),startDate:str(summary,"startDate"),endDate:str(summary,"endDate")},timezone,status,planningVersion:integer(o,"planningVersion"),updatedAt:iso(o,"updatedAt"),days:list(o,"days",x=>simple(x) as unknown as FestivalTimetableDay),stageWindows:list(o,"stageWindows",x=>simple(x) as unknown as FestivalStageOperatingWindow),stageSlots:list(o,"stageSlots",parseFestivalStageSlot),artistAllocations:list(o,"artistAllocations",x=>simple(x) as unknown as FestivalArtistPerformanceSlot),soundchecks:list(o,"soundchecks",x=>simple(x) as unknown as FestivalArtistSoundcheck),changeovers:list(o,"changeovers",x=>simple(x) as unknown as FestivalStageChangeover),stageManagers:list(o,"stageManagers",x=>simple(x) as unknown as FestivalStageManagerAssignment),operationalItems:list(o,"operationalItems",x=>simple(x) as unknown as FestivalOperationalScheduleItem),supplierWindows:list(o,"supplierWindows",x=>simple(x) as unknown as FestivalSupplierDeliveryWindow),sponsorActivationWindows:list(o,"sponsorActivationWindows",x=>simple(x) as unknown as FestivalSponsorActivationWindow),conflicts:list(o,"conflicts",parseConflict),readinessAssessment:val(o,"readinessAssessment")?simple(val(o,"readinessAssessment")) as unknown as FestivalReadinessAssessment:null,readinessChecks:list(o,"readinessChecks",x=>simple(x) as unknown as FestivalReadinessCheck),permissions:{canManageFestival:val(permissions,"canManageFestival")===true,canComplete:val(permissions,"canComplete")===true,stageManagerStageIds:Array.isArray(val(permissions,"stageManagerStageIds"))?val(permissions,"stageManagerStageIds") as string[]:[]}}}
export const parseFestivalTimetableActionResult=(v:unknown):FestivalTimetableActionResult=>{try{return parseFestivalTimetablePlan(v)}catch{throw new Error("malformed_festival_timetable_action_result")}};
export const formatFestivalMoney=(minor:number,currency:string)=>new Intl.NumberFormat("en-GB",{style:"currency",currency}).format(minor/100);
