export const festivalTicketPlanStatuses = ["not_started", "in_progress", "products_configured", "capacity_allocated", "forecast_reviewed", "ready_for_artist_planning"] as const;
export const festivalTicketTypes = ["general_admission", "day_ticket", "weekend", "full_festival", "vip", "accessible", "child", "resident", "early_entry", "camping", "parking"] as const;
export const festivalTicketAccessScopes = ["single_day", "date_range", "full_festival", "non_admission"] as const;
export const festivalTicketProductClasses = ["admission", "upgrade", "add_on"] as const;
export const festivalTicketReleaseTypes = ["presale", "early_bird", "general_sale", "final_release", "door", "invitation", "sponsor", "community"] as const;
export type FestivalTicketPlanStatus = typeof festivalTicketPlanStatuses[number];
export type FestivalTicketType = typeof festivalTicketTypes[number];
export type FestivalTicketAccessScope = typeof festivalTicketAccessScopes[number];
export type FestivalTicketProductClass = typeof festivalTicketProductClasses[number];

export interface FestivalTicketPlan { id: string | null; currencyCode: string; salesTaxRateBasisPoints: number; bookingFeeMode: "fixed" | "percentage" | "combined" | "none"; bookingFeeMinor: number; bookingFeeBasisPoints: number; bookingFeePayer: "customer" | "festival_company" | "split"; refundPolicy: string; transferPolicy: string; minimumPurchaseQuantity: number; maximumPurchaseQuantity: number; expectedSellThroughBasisPoints: number; expectedRefundBasisPoints: number; expectedComplimentaryUseBasisPoints: number; expectedNoShowBasisPoints: number; status: FestivalTicketPlanStatus; }
export interface FestivalTicketProduct { id: string | null; name: string; slug: string; ticketType: FestivalTicketType; productClass: FestivalTicketProductClass; accessScope: FestivalTicketAccessScope; validFromDate: string; validToDate: string; priceMinor: number; faceValueMinor: number; capacityLimit: number; minimumAge: number | null; includesCamping: boolean; includesParking: boolean; includesVipArea: boolean; includesBackstage: boolean; transferable: boolean; refundable: boolean; salePriority: number; active: boolean; }
export interface FestivalTicketReleasePhase { id: string | null; productId: string | null; name: string; releaseType: typeof festivalTicketReleaseTypes[number]; sortOrder: number; startsAt: string | null; endsAt: string | null; allocationLimit: number; priceOverrideMinor: number | null; discountBasisPoints: number; eligibilityRule: string; status: "planned" | "disabled"; }
export interface FestivalTicketCapacityAllocation { id: string | null; productId: string | null; productSlug: string; festivalDate: string; capacityAllocated: number; capacityReserved: number; capacityComplimentary: number; }
export interface FestivalTicketPlanningIssue { code: string; severity: "error" | "warning"; section: "products" | "capacity" | "releases" | "forecast" | "plan"; field: string | null; entityId: string | null; blocking: boolean; messageKey: string; metadata: Record<string, unknown>; }
export interface FestivalTicketDailyForecast { festivalDate: string; attendance: number; capacity: number; utilisationBasisPoints: number; remainingCapacity: number; }
export interface FestivalTicketForecast { maximumAdmissionRevenueMinor: number; expectedTicketsSold: number; expectedGrossTicketReceiptsMinor: number; expectedBookingFeesMinor: number; estimatedFestivalPaidFeesMinor: number; estimatedTaxMinor: number; expectedRefundsMinor: number; expectedNetTicketReceiptsMinor: number; averageRevenuePerAttendeeMinor: number; daily: FestivalTicketDailyForecast[]; }
export interface FestivalTicketPlanResult { festivalCompanyId: string; festivalName: string; festivalDates: string[]; usableSiteCapacity: number; sitePlanStatus: string; ticketPlan: FestivalTicketPlan | null; products: FestivalTicketProduct[]; releasePhases: FestivalTicketReleasePhase[]; capacityAllocations: FestivalTicketCapacityAllocation[]; forecast: FestivalTicketForecast; issues: FestivalTicketPlanningIssue[]; warnings: FestivalTicketPlanningIssue[]; ready: boolean; canWrite: boolean; planningVersion: number; updatedAt: string | null; }
export interface FestivalTicketPlanDraft { ticketPlan: FestivalTicketPlan; products: FestivalTicketProduct[]; releasePhases: FestivalTicketReleasePhase[]; capacityAllocations: FestivalTicketCapacityAllocation[]; }

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i, DATE=/^\d{4}-\d{2}-\d{2}$/, CURRENCY=/^[A-Z]{3}$/;
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
const integer=(v:unknown,min=0,max=Number.MAX_SAFE_INTEGER)=>Number.isSafeInteger(v)&&(v as number)>=min&&(v as number)<=max;
const string=(v:unknown)=>typeof v==="string";
const uuidOrNull=(v:unknown)=>v===null||(string(v)&&UUID.test(v as string));
const timestampOrNull=(v:unknown)=>v===null||(string(v)&&!Number.isNaN(Date.parse(v as string)));
const malformed=():never=>{throw new Error("malformed_festival_ticket_plan_result")};
const parseProduct=(v:unknown):FestivalTicketProduct=>{if(!object(v)||!uuidOrNull(v.id)||!string(v.name)||!(v.name as string).trim()||!string(v.slug)||!festivalTicketTypes.includes(v.ticketType as FestivalTicketType)||!festivalTicketProductClasses.includes(v.productClass as FestivalTicketProductClass)||!festivalTicketAccessScopes.includes(v.accessScope as FestivalTicketAccessScope)||!string(v.validFromDate)||!DATE.test(v.validFromDate as string)||!string(v.validToDate)||!DATE.test(v.validToDate as string)||!integer(v.priceMinor)||!integer(v.faceValueMinor)||!integer(v.capacityLimit)||!(v.minimumAge===null||integer(v.minimumAge,0,99))||![v.includesCamping,v.includesParking,v.includesVipArea,v.includesBackstage,v.transferable,v.refundable,v.active].every(x=>typeof x==="boolean")||!integer(v.salePriority))malformed();return v as unknown as FestivalTicketProduct};
const parseIssue=(v:unknown):FestivalTicketPlanningIssue=>{if(!object(v)||!string(v.code)||!string(v.severity)||!string(v.section)||!(v.field===null||string(v.field))||!uuidOrNull(v.entityId)||typeof v.blocking!=="boolean"||!string(v.messageKey)||!object(v.metadata))malformed();return v as unknown as FestivalTicketPlanningIssue};
export function parseFestivalTicketPlanResult(v:unknown):FestivalTicketPlanResult { if(!object(v)||!string(v.festivalCompanyId)||!UUID.test(v.festivalCompanyId as string)||!string(v.festivalName)||!Array.isArray(v.festivalDates)||!(v.festivalDates as unknown[]).every(x=>string(x)&&DATE.test(x as string))||!integer(v.usableSiteCapacity,1)||!string(v.sitePlanStatus)||!Array.isArray(v.products)||!Array.isArray(v.releasePhases)||!Array.isArray(v.capacityAllocations)||!Array.isArray(v.issues)||!Array.isArray(v.warnings)||typeof v.ready!=="boolean"||typeof v.canWrite!=="boolean"||!integer(v.planningVersion)||!timestampOrNull(v.updatedAt)||!object(v.forecast))malformed();
 const plan=v.ticketPlan;if(plan!==null&&(!object(plan)||!uuidOrNull(plan.id)||!string(plan.currencyCode)||!CURRENCY.test(plan.currencyCode as string)||!integer(plan.salesTaxRateBasisPoints,0,10000)||!integer(plan.bookingFeeMinor)||!integer(plan.bookingFeeBasisPoints,0,10000)||!integer(plan.minimumPurchaseQuantity,1)||!integer(plan.maximumPurchaseQuantity,1)||!festivalTicketPlanStatuses.includes(plan.status as FestivalTicketPlanStatus)))malformed();
 const products=v.products.map(parseProduct); if(new Set(products.map(p=>p.slug)).size!==products.length)malformed();
 const forecast=v.forecast as Record<string,unknown>; const money=["maximumAdmissionRevenueMinor","expectedTicketsSold","expectedGrossTicketReceiptsMinor","expectedBookingFeesMinor","estimatedFestivalPaidFeesMinor","estimatedTaxMinor","expectedRefundsMinor","expectedNetTicketReceiptsMinor","averageRevenuePerAttendeeMinor"];if(!money.every(k=>integer(forecast[k]))||!Array.isArray(forecast.daily))malformed();
 return {...v,ticketPlan:plan,products,issues:v.issues.map(parseIssue),warnings:v.warnings.map(parseIssue)} as unknown as FestivalTicketPlanResult;
}
export const ticketPlanToDraft=(r:FestivalTicketPlanResult):FestivalTicketPlanDraft|null=>r.ticketPlan?{ticketPlan:{...r.ticketPlan},products:r.products.map(x=>({...x})),releasePhases:r.releasePhases.map(x=>({...x})),capacityAllocations:r.capacityAllocations.map(x=>({...x}))}:null;
export function festivalDates(start:string,end:string){const dates:string[]=[];for(let t=Date.parse(start+"T00:00:00Z"),stop=Date.parse(end+"T00:00:00Z");t<=stop;t+=86400000)dates.push(new Date(t).toISOString().slice(0,10));return dates;}
export function affectedFestivalDates(product:FestivalTicketProduct, dates:string[]):string[]{if(product.productClass!=="admission"||product.accessScope==="non_admission")return [];if(product.accessScope==="full_festival")return [...dates];return dates.filter(d=>d>=product.validFromDate&&d<=product.validToDate);}
export function parseMoneyToMinor(value:string):number|null {const normalized=value.trim().replace(/,/g,"");if(!/^\d+(?:\.\d{1,2})?$/.test(normalized))return null;const [whole,fraction=""]=normalized.split(".");const amount=Number(whole)*100+Number(fraction.padEnd(2,"0"));return Number.isSafeInteger(amount)?amount:null;}
export const formatMinorMoney=(minor:number,currency:string)=>new Intl.NumberFormat("en-GB",{style:"currency",currency}).format(minor/100);
