export const FESTIVAL_SPONSORSHIP_ERROR="malformed_festival_sponsorship_result";
export const FESTIVAL_SPONSOR_ACTION_ERROR="malformed_festival_sponsor_action_result";
export const FESTIVAL_SPONSOR_OPPORTUNITIES_ERROR="malformed_festival_sponsorship_opportunity_result";
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
const uint=(v:unknown,max=Number.MAX_SAFE_INTEGER)=>Number.isSafeInteger(v)&&Number(v)>=0&&Number(v)<=max;
const currency=(v:unknown)=>typeof v==="string"&&/^[A-Z]{3}$/.test(v);
const timestamp=(v:unknown)=>v===null||(typeof v==="string"&&!Number.isNaN(Date.parse(v)));
const array=(v:unknown)=>Array.isArray(v);
const planStatuses=["not_started","inventory_configured","applications_open","proposals_in_progress","contracts_in_progress","commercial_plan_complete","ready_for_final_readiness"] as const;
export type FestivalSponsorshipStatus=typeof planStatuses[number];
export type SponsorSource="player_company"|"npc_company"|"admin_sponsor";
export interface FestivalSponsorshipPlan{id:string;currencyCode:string;sponsorshipTargetMinor:number;minimumCashTargetMinor:number;maximumInKindShareBasisPoints:number;minimumPlayerCompanyShareBasisPoints:number;applicationMode:"closed"|"invite_only"|"applications_only"|"hybrid";publicApplicationsOpenAt:string|null;publicApplicationsCloseAt:string|null;status:FestivalSponsorshipStatus;planningVersion:number}
export interface CommercialSummary{sponsorshipTargetMinor:number;minimumCashTargetMinor:number;contractedCashMinor:number;contractedInKindMinor:number;totalContractedValueMinor:number;pendingProposalCashMinor:number;pendingProposalInKindMinor:number;remainingTargetMinor:number;inventoryUtilisationBasisPoints:number;cashTargetProgressBasisPoints:number;playerSponsorShareBasisPoints:number;npcSponsorShareBasisPoints:number;adminSponsorShareBasisPoints:number;commercialReadinessScore:number}
export interface SponsorshipIssue{code:string;severity:"warning"|"error";section:string;entityId:string|null;blocking:boolean;messageKey:string;metadata:Record<string,unknown>}
export interface FestivalSponsorshipResult{festivalCompanyId:string;operationsReadiness:boolean;sponsorshipPlan:FestivalSponsorshipPlan|null;categories:Record<string,unknown>[];inventory:Record<string,unknown>[];packages:Record<string,unknown>[];prospects:Record<string,unknown>[];applications:Record<string,unknown>[];invitations:Record<string,unknown>[];proposals:Record<string,unknown>[];revisions:Record<string,unknown>[];contracts:Record<string,unknown>[];contributions:Record<string,unknown>[];deliverables:Record<string,unknown>[];brandingPlacements:Record<string,unknown>[];commercialSummary:CommercialSummary;issues:SponsorshipIssue[];readiness:boolean;canWrite:boolean;planningVersion:number;updatedAt:string|null}
export interface FestivalSponsorshipDraft{sponsorshipTargetMinor:number;minimumCashTargetMinor:number;maximumInKindShareBasisPoints:number;minimumPlayerCompanyShareBasisPoints:number;applicationMode:FestivalSponsorshipPlan["applicationMode"];publicApplicationsOpenAt:string|null;publicApplicationsCloseAt:string|null}
const summaryKeys=["sponsorshipTargetMinor","minimumCashTargetMinor","contractedCashMinor","contractedInKindMinor","totalContractedValueMinor","pendingProposalCashMinor","pendingProposalInKindMinor","remainingTargetMinor","inventoryUtilisationBasisPoints","cashTargetProgressBasisPoints","playerSponsorShareBasisPoints","npcSponsorShareBasisPoints","adminSponsorShareBasisPoints","commercialReadinessScore"];
function fail(code=FESTIVAL_SPONSORSHIP_ERROR):never{throw new Error(code)}
export function parseFestivalSponsorshipResult(v:unknown):FestivalSponsorshipResult{if(!object(v)||typeof v.festivalCompanyId!=="string"||!UUID.test(v.festivalCompanyId)||typeof v.operationsReadiness!=="boolean"||!["categories","inventory","packages","prospects","applications","invitations","proposals","revisions","contracts","contributions","deliverables","brandingPlacements","issues"].every(k=>array(v[k]))||!object(v.commercialSummary)||!summaryKeys.every(k=>uint(v.commercialSummary[k],k.endsWith("BasisPoints")?10000:undefined))||typeof v.readiness!=="boolean"||typeof v.canWrite!=="boolean"||!uint(v.planningVersion)||!timestamp(v.updatedAt))fail();if(v.sponsorshipPlan!==null){const p=v.sponsorshipPlan;if(!object(p)||typeof p.id!=="string"||!UUID.test(p.id)||!currency(p.currencyCode)||!["sponsorshipTargetMinor","minimumCashTargetMinor"].every(k=>uint(p[k]))||!["maximumInKindShareBasisPoints","minimumPlayerCompanyShareBasisPoints"].every(k=>uint(p[k],10000))||!["closed","invite_only","applications_only","hybrid"].includes(String(p.applicationMode))||!planStatuses.includes(String(p.status) as FestivalSponsorshipStatus)||!uint(p.planningVersion)||!timestamp(p.publicApplicationsOpenAt)||!timestamp(p.publicApplicationsCloseAt))fail()}return v as unknown as FestivalSponsorshipResult}
export function parseFestivalSponsorActionResult(v:unknown){if(!object(v)||!object(v.entity)||!object(v.sponsorship)||!array(v.communications))fail(FESTIVAL_SPONSOR_ACTION_ERROR);return v as {entity:Record<string,unknown>;sponsorship:FestivalSponsorshipResult;communications:Record<string,unknown>[]}}
export function parseFestivalSponsorshipOpportunities(v:unknown):FestivalSponsorshipOpportunity[]{if(!object(v)||!array(v.items))fail(FESTIVAL_SPONSOR_OPPORTUNITIES_ERROR);return v.items.map(x=>{if(!object(x)||typeof x.festivalCompanyId!=="string"||!UUID.test(x.festivalCompanyId)||typeof x.festivalName!=="string"||!(x.city===null||typeof x.city==="string")||!(x.country===null||typeof x.country==="string")||!timestamp(x.startDate)||!timestamp(x.endDate)||typeof x.applicationDeadline!=="string"||!timestamp(x.applicationDeadline)||!array(x.packages)||!x.packages.every(p=>object(p)&&typeof p.id==="string"&&UUID.test(p.id)&&typeof p.name==="string"&&typeof p.tier==="string"&&uint(p.minimumCashMinor)&&uint(p.permittedInKindShareBasisPoints,10000)&&array(p.targetIndustries)&&array(p.excludedIndustries))||!array(x.inventorySummary)||!object(x.eligibility)||typeof x.eligibility.canApply!=="boolean"||!array(x.eligibility.reasonCodes)||!["strong_capacity","adequate_capacity","limited_capacity","insufficient_capacity","unknown"].includes(String(x.affordabilityCategory)))fail(FESTIVAL_SPONSOR_OPPORTUNITIES_ERROR);return x as unknown as FestivalSponsorshipOpportunity})}
export const formatSponsorshipMoney=(minor:number,code:string)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:code}).format(minor/100);

export type SponsorshipAffordability="strong_capacity"|"adequate_capacity"|"limited_capacity"|"insufficient_capacity"|"unknown";
export interface FestivalSponsorshipPermissions{canManageFestival:boolean;canRepresentCompany:boolean;canApply:boolean;canNegotiate:boolean;canAccept:boolean;reasonCodes:string[]}
export interface FestivalSponsorshipOpportunity{festivalCompanyId:string;festivalName:string;city:string|null;country:string|null;startDate:string|null;endDate:string|null;scale:string|null;applicationDeadline:string;packages:FestivalSponsorshipPackageSummary[];inventorySummary:{type:string;availableQuantity:number;exclusive:boolean}[];eligibility:{canApply:boolean;reasonCodes:string[]};companyAuthority:boolean|"unknown";affordabilityCategory:SponsorshipAffordability;existingApplicationState:string|null;existingInvitationState:string|null;existingProposalState:string|null}
export interface FestivalSponsorshipPackageSummary{id:string;name:string;tier:string;minimumCashMinor:number;permittedInKindShareBasisPoints:number;targetIndustries:string[];excludedIndustries:string[]}
export interface FestivalSponsorApplication{id:string;status:"submitted"|"under_review"|"shortlisted"|"proposal_pending"|"rejected"|"withdrawn"|"expired";companyId:string;packageId:string|null;proposedCashMinor:number;proposedInKindMinor:number;applicationVersion:number;submittedAt:string}
export interface FestivalSponsorInvitation{id:string;sponsorSource:SponsorSource;status:"draft"|"sent"|"viewed"|"interested"|"declined"|"expired"|"converted_to_proposal"|"withdrawn";invitationVersion:number;expiresAt:string|null}
export interface FestivalSponsorProposalRevision{id:string;proposalId:string;proposalVersion:number;proposedByParty:"festival"|"sponsor"|"system"|"admin";cashContributionMinor:number;inKindContributionMinor:number;inventorySnapshot:unknown[];deliverablesSnapshot:unknown[];createdAt:string}
export interface FestivalSponsorProposal{id:string;sponsorSource:SponsorSource;status:"draft"|"sent"|"countered"|"accepted"|"declined"|"expired"|"withdrawn"|"superseded";currencyCode:string;cashContributionMinor:number;inKindContributionMinor:number;proposalVersion:number;currentRevisionId:string|null;responseDeadline:string|null}
export interface FestivalSponsorContract{id:string;sponsorSource:SponsorSource;status:"committed"|"awaiting_activation"|"active"|"fulfilled"|"cancelled"|"sponsor_defaulted"|"festival_cancelled";cashContributionMinor:number;inKindContributionMinor:number;totalContributionMinor:number;currencyCode:string;contractVersion:number}
export interface FestivalSponsorContribution{id:string;contractId:string;type:string;approvedValueMinor:number;currencyCode:string;status:"planned"|"committed"|"cancelled"}
export interface FestivalBrandingPlacement{id:string;contractId:string;inventoryId:string;quantity:number;status:"planned"|"contracted"|"cancelled"}
export interface FestivalSponsorDeliverable{id:string;contractId:string;type:string;quantity:number;dueAt:string|null;status:"planned"|"contracted"|"cancelled"}
export interface FestivalFinancialReceivable{id:string;contractId:string;sourceType:"sponsor_contract_cash"|"sponsor_contract_in_kind";amountMinor:number;currencyCode:string;status:"planned"|"cancelled"|"settled"}
export interface FestivalSponsorCompanyCommitment{id:string;companyId:string;contractId:string;amountMinor:number;currencyCode:string;status:"reserved"|"released"|"settled"}
export interface FestivalSponsorFeedback{id:string;stage:string;reasonCodes:string[];messageKey:string;safeMetadata:Record<string,unknown>}
export interface FestivalSponsorshipActionResult{entity:Record<string,unknown>;sponsorship:FestivalSponsorshipResult;communications:Record<string,unknown>[]}

export function parseFestivalSponsorProposal(v:unknown):FestivalSponsorProposal{if(!object(v)||typeof v.id!=="string"||!UUID.test(v.id)||!["player_company","npc_company","admin_sponsor"].includes(String(v.sponsorSource))||!["draft","sent","countered","accepted","declined","expired","withdrawn","superseded"].includes(String(v.status))||!currency(v.currencyCode)||!uint(v.cashContributionMinor)||!uint(v.inKindContributionMinor)||!uint(v.proposalVersion)||!(v.currentRevisionId===null||(typeof v.currentRevisionId==="string"&&UUID.test(v.currentRevisionId)))||!timestamp(v.responseDeadline))fail("malformed_festival_sponsor_proposal_result");return v as unknown as FestivalSponsorProposal}
export function parseFestivalSponsorContract(v:unknown):FestivalSponsorContract{if(!object(v)||typeof v.id!=="string"||!UUID.test(v.id)||!["player_company","npc_company","admin_sponsor"].includes(String(v.sponsorSource))||!["committed","awaiting_activation","active","fulfilled","cancelled","sponsor_defaulted","festival_cancelled"].includes(String(v.status))||!currency(v.currencyCode)||!uint(v.cashContributionMinor)||!uint(v.inKindContributionMinor)||!uint(v.totalContributionMinor)||v.totalContributionMinor!==Number(v.cashContributionMinor)+Number(v.inKindContributionMinor)||!uint(v.contractVersion))fail("malformed_festival_sponsor_contract_result");return v as unknown as FestivalSponsorContract}
