-- Historical migration ordering repair.
--
-- This migration originally altered public.music_video_configs and
-- public.music_video_metrics before their dependency-safe creation point on a clean
-- database. Its enum and workflow fields are now created together with the complete
-- music video schema in:
--   20251116081455_b656d8bc-8184-4de7-b40d-71793921f362.sql
--
-- Keep the historical version as an intentional no-op so deployed migration history
-- is not renumbered while `supabase db reset` remains reproducible.
SELECT 1;
