-- Create performance items catalog
CREATE TABLE IF NOT EXISTS performance_items_catalog (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  item_category TEXT NOT NULL CHECK (item_category IN ('stage_action', 'crowd_interaction', 'special_effect', 'improvisation', 'storytelling')),
  required_skill TEXT, -- skill slug like 'stage_presence', 'showmanship', etc
  required_genre TEXT, -- genre like 'Rock', 'Jazz', etc
  min_skill_level INTEGER DEFAULT 1 CHECK (min_skill_level >= 0 AND min_skill_level <= 20),
  base_impact_min NUMERIC DEFAULT 0.5 CHECK (base_impact_min >= 0 AND base_impact_min <= 2.0),
  base_impact_max NUMERIC DEFAULT 1.5 CHECK (base_impact_max >= 0 AND base_impact_max <= 2.0),
  duration_seconds INTEGER DEFAULT 180,
  energy_cost INTEGER DEFAULT 5 CHECK (energy_cost >= 1 AND energy_cost <= 10),
  crowd_appeal INTEGER DEFAULT 5 CHECK (crowd_appeal >= 1 AND crowd_appeal <= 10),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE performance_items_catalog ENABLE ROW LEVEL SECURITY;

-- Allow everyone to read the catalog
CREATE POLICY "Everyone can view performance items catalog"
ON performance_items_catalog FOR SELECT
USING (true);

-- Only admins can modify
CREATE POLICY "Admins can manage performance items catalog"
ON performance_items_catalog FOR ALL
USING (has_role(auth.uid(), 'admin'::app_role));

-- Update setlist_songs constraints to allow NULL song_id when it's a performance item
ALTER TABLE setlist_songs 
DROP CONSTRAINT IF EXISTS setlist_songs_setlist_id_song_id_key;

-- Add new constraint that allows NULL song_id for performance items
ALTER TABLE setlist_songs
ADD CONSTRAINT setlist_songs_unique_song CHECK (
  (item_type = 'song' AND song_id IS NOT NULL) OR
  (item_type = 'performance_item' AND performance_item_id IS NOT NULL)
);

-- Create index for performance lookups
CREATE INDEX IF NOT EXISTS idx_setlist_songs_performance_item 
ON setlist_songs(performance_item_id) 
WHERE item_type = 'performance_item';

-- Seed 200 performance items
INSERT INTO performance_items_catalog (name, description, item_category, required_skill, required_genre, min_skill_level, base_impact_min, base_impact_max, duration_seconds, energy_cost, crowd_appeal) VALUES
-- Stage Actions (40 items)
('Guitar Solo Showcase', 'Extended improvised guitar solo that showcases technical mastery', 'stage_action', 'guitar_advanced', NULL, 5, 0.8, 1.8, 240, 8, 9),
('Drum Fill Extravaganza', 'High-energy drum solo with complex rhythms', 'stage_action', 'drums_advanced', NULL, 5, 0.7, 1.6, 180, 7, 8),
('Bass Groove Spotlight', 'Funky bass solo with slap technique', 'stage_action', 'bass_advanced', NULL, 4, 0.6, 1.4, 150, 6, 7),
('Piano Interlude', 'Melodic piano solo with classical influences', 'stage_action', 'piano_intermediate', NULL, 3, 0.5, 1.3, 200, 5, 7),
('Acoustic Breakdown', 'Unplugged acoustic moment for intimate connection', 'stage_action', 'guitar_basic', NULL, 2, 0.6, 1.2, 180, 4, 8),
('Vocal Acrobatics', 'Impressive vocal runs and high notes', 'stage_action', 'vocals_advanced', NULL, 6, 0.9, 1.9, 120, 9, 10),
('Harmonica Blues Break', 'Soulful harmonica solo', 'stage_action', 'harmonica', NULL, 3, 0.5, 1.2, 150, 5, 6),
('Saxophone Solo', 'Smooth or energetic sax performance', 'stage_action', 'saxophone', NULL, 4, 0.7, 1.5, 180, 6, 8),
('Synth Odyssey', 'Electronic keyboard exploration', 'stage_action', 'synthesizer', NULL, 3, 0.6, 1.4, 200, 6, 7),
('Percussion Jam', 'Auxiliary percussion showcase', 'stage_action', 'percussion', NULL, 2, 0.4, 1.1, 150, 5, 6),
('Stage Dive', 'Jump into the crowd for physical connection', 'stage_action', 'stage_presence', NULL, 4, 0.8, 1.7, 30, 9, 10),
('Crowd Surfing', 'Surf across the audience', 'stage_action', 'stage_presence', NULL, 5, 0.9, 1.8, 45, 10, 10),
('Mic Stand Spin', 'Flashy microphone stand tricks', 'stage_action', 'showmanship', NULL, 2, 0.4, 1.0, 20, 3, 5),
('Power Stance', 'Strike a commanding pose during instrumental break', 'stage_action', 'stage_presence', NULL, 1, 0.3, 0.9, 30, 2, 4),
('Instrument Toss', 'Toss instrument to another band member', 'stage_action', 'showmanship', NULL, 3, 0.5, 1.2, 15, 5, 7),
('Windmill Strum', 'Aggressive windmill guitar strumming', 'stage_action', 'showmanship', 'Rock', 2, 0.5, 1.3, 30, 6, 8),
('Jazz Scat Singing', 'Improvised vocal jazz scatting', 'stage_action', 'vocals_advanced', 'Jazz', 5, 0.7, 1.5, 120, 7, 8),
('Rap Freestyle', 'Improvised rap verses', 'stage_action', 'rap_skills', 'Hip Hop', 4, 0.8, 1.7, 180, 8, 9),
('Beatbox Break', 'Vocal percussion performance', 'stage_action', 'beatboxing', 'Hip Hop', 3, 0.6, 1.4, 120, 6, 8),
('Dance Routine', 'Choreographed dance moves', 'stage_action', 'dancing', NULL, 3, 0.6, 1.3, 90, 7, 8),
('Guitar Spin', 'Spin guitar around body', 'stage_action', 'showmanship', NULL, 2, 0.4, 1.0, 10, 4, 6),
('Knee Slide', 'Slide across stage on knees', 'stage_action', 'stage_presence', NULL, 2, 0.5, 1.1, 15, 5, 7),
('Headbanging Section', 'Intense headbanging during heavy part', 'stage_action', 'stage_presence', 'Heavy Metal', 1, 0.4, 1.0, 45, 6, 8),
('Flamenco Footwork', 'Traditional flamenco dancing', 'stage_action', 'dancing', 'Flamenco', 4, 0.7, 1.5, 120, 7, 9),
('Reggae Skank', 'Signature reggae dance moves', 'stage_action', 'dancing', 'Reggae', 2, 0.5, 1.1, 60, 4, 6),
('Country Two-Step', 'Line dancing or two-step', 'stage_action', 'dancing', 'Country', 2, 0.4, 1.0, 90, 5, 6),
('Electronic Drop', 'Big bass drop with crowd buildup', 'stage_action', 'production', 'EDM', 4, 0.9, 1.9, 60, 8, 10),
('Acoustic Loop Building', 'Build layered loops live', 'stage_action', 'looping', NULL, 5, 0.7, 1.6, 240, 7, 8),
('Falsetto Showcase', 'Extended high vocal range display', 'stage_action', 'vocals_advanced', NULL, 5, 0.7, 1.5, 90, 7, 8),
('Growl Vocals', 'Metal/rock growling technique', 'stage_action', 'vocals_advanced', 'Heavy Metal', 4, 0.6, 1.4, 60, 8, 9),
('Operatic Vocals', 'Classical opera-style singing', 'stage_action', 'vocals_advanced', 'Classical', 6, 0.8, 1.7, 120, 8, 9),
('Violin Solo', 'Classical or rock violin performance', 'stage_action', 'violin', NULL, 4, 0.7, 1.5, 180, 6, 8),
('Cello Feature', 'Deep melodic cello showcase', 'stage_action', 'cello', 'Classical', 4, 0.6, 1.4, 200, 5, 7),
('Trumpet Solo', 'Bold brass solo', 'stage_action', 'trumpet', 'Jazz', 4, 0.7, 1.5, 150, 6, 8),
('Trombone Slide', 'Smooth trombone performance', 'stage_action', 'trombone', NULL, 3, 0.5, 1.2, 150, 5, 6),
('DJ Scratching', 'Turntable scratching display', 'stage_action', 'djing', 'Hip Hop', 4, 0.8, 1.6, 120, 7, 9),
('Live Sampling', 'Create beats from live sounds', 'stage_action', 'production', NULL, 5, 0.8, 1.7, 180, 8, 8),
('Theremin Performance', 'Spooky electronic instrument', 'stage_action', 'theremin', NULL, 6, 0.7, 1.5, 150, 6, 7),
('Banjo Picking', 'Fast bluegrass banjo playing', 'stage_action', 'banjo', 'Country', 4, 0.6, 1.4, 120, 6, 7),
('Accordion Feature', 'Traditional accordion showcase', 'stage_action', 'accordion', NULL, 3, 0.5, 1.2, 150, 5, 6),

-- Crowd Interaction (40 items)
('Sing-Along Chorus', 'Get crowd to sing the chorus', 'crowd_interaction', 'crowd_control', NULL, 1, 0.7, 1.5, 120, 5, 9),
('Call and Response', 'Musical call and response with audience', 'crowd_interaction', 'crowd_control', NULL, 2, 0.6, 1.4, 90, 4, 8),
('Hands Up Moment', 'Get everyone''s hands in the air', 'crowd_interaction', 'crowd_control', NULL, 1, 0.5, 1.2, 60, 3, 7),
('Wave Creation', 'Start a crowd wave', 'crowd_interaction', 'crowd_control', NULL, 2, 0.6, 1.3, 45, 4, 8),
('Clap Along', 'Get crowd clapping in rhythm', 'crowd_interaction', 'crowd_control', NULL, 1, 0.5, 1.1, 60, 3, 7),
('Mosh Pit Incitement', 'Encourage mosh pit formation', 'crowd_interaction', 'crowd_control', 'Heavy Metal', 3, 0.8, 1.7, 90, 7, 9),
('Circle Pit', 'Start a circle pit', 'crowd_interaction', 'crowd_control', 'Punk Rock', 3, 0.7, 1.6, 120, 7, 9),
('Wall of Death', 'Split crowd for wall of death', 'crowd_interaction', 'crowd_control', 'Heavy Metal', 4, 0.9, 1.8, 60, 8, 10),
('Jump Together', 'Get entire crowd jumping', 'crowd_interaction', 'crowd_control', NULL, 2, 0.6, 1.3, 45, 5, 8),
('Shout Your City', 'Get crowd to shout city name', 'crowd_interaction', 'crowd_control', NULL, 1, 0.5, 1.1, 30, 3, 7),
('Birthday Shoutout', 'Acknowledge someone''s birthday', 'crowd_interaction', 'crowd_control', NULL, 1, 0.3, 0.9, 60, 2, 6),
('Dedication Message', 'Dedicate song to someone/something', 'crowd_interaction', 'storytelling', NULL, 1, 0.4, 1.0, 90, 3, 6),
('Audience Member on Stage', 'Bring fan on stage to participate', 'crowd_interaction', 'crowd_control', NULL, 3, 0.7, 1.6, 180, 6, 9),
('Crowd Selfie', 'Take photo with audience', 'crowd_interaction', 'crowd_control', NULL, 1, 0.4, 0.9, 30, 2, 7),
('Lyric Teaching', 'Teach crowd new song lyrics', 'crowd_interaction', 'crowd_control', NULL, 2, 0.5, 1.2, 120, 4, 7),
('Quiet Moment Request', 'Ask for complete silence', 'crowd_interaction', 'crowd_control', NULL, 2, 0.6, 1.3, 60, 4, 8),
('Phone Lights Up', 'Request phone flashlights', 'crowd_interaction', 'crowd_control', NULL, 1, 0.5, 1.2, 90, 3, 8),
('Split Crowd Singing', 'Different sides sing different parts', 'crowd_interaction', 'crowd_control', NULL, 3, 0.7, 1.5, 120, 5, 9),
('Front Row Interaction', 'Personal interaction with front row', 'crowd_interaction', 'crowd_control', NULL, 2, 0.5, 1.1, 90, 4, 7),
('Crowd Compliment', 'Praise the audience energy', 'crowd_interaction', 'crowd_control', NULL, 1, 0.4, 1.0, 30, 2, 6),
('Ask How They''re Doing', 'Check in with the crowd', 'crowd_interaction', 'crowd_control', NULL, 1, 0.4, 0.9, 45, 2, 6),
('Genre History Lesson', 'Brief musical history talk', 'crowd_interaction', 'storytelling', NULL, 3, 0.5, 1.1, 120, 3, 6),
('Local Venue Appreciation', 'Thank the venue and local scene', 'crowd_interaction', 'crowd_control', NULL, 1, 0.4, 0.9, 60, 2, 6),
('Crowd Petition', 'Ask what song they want next', 'crowd_interaction', 'crowd_control', NULL, 2, 0.5, 1.2, 60, 3, 7),
('High Five Run', 'Run and high-five audience members', 'crowd_interaction', 'stage_presence', NULL, 2, 0.6, 1.3, 45, 6, 8),
('Throw Guitar Picks', 'Toss picks into crowd', 'crowd_interaction', 'crowd_control', NULL, 1, 0.3, 0.8, 30, 2, 6),
('Throw Drumsticks', 'Toss sticks to audience', 'crowd_interaction', 'crowd_control', NULL, 1, 0.3, 0.8, 20, 2, 6),
('Sign a Setlist', 'Sign and throw setlist to crowd', 'crowd_interaction', 'crowd_control', NULL, 1, 0.3, 0.7, 45, 2, 5),
('Meet and Greet Announcement', 'Announce post-show meetup', 'crowd_interaction', 'crowd_control', NULL, 1, 0.3, 0.8, 60, 2, 6),
('Social Media Shoutout', 'Encourage social media posts', 'crowd_interaction', 'crowd_control', NULL, 1, 0.3, 0.7, 45, 2, 5),
('Thank Opening Bands', 'Shout out to support acts', 'crowd_interaction', 'crowd_control', NULL, 1, 0.3, 0.8, 60, 2, 6),
('Encourage Crowd Surfing', 'Safely encourage surfing', 'crowd_interaction', 'crowd_control', 'Punk Rock', 2, 0.6, 1.4, 60, 5, 8),
('Fist Pumps Together', 'Synchronized fist pumping', 'crowd_interaction', 'crowd_control', 'Heavy Metal', 1, 0.5, 1.1, 45, 4, 7),
('Dance Challenge', 'Challenge crowd to dance battle', 'crowd_interaction', 'crowd_control', 'Hip Hop', 2, 0.6, 1.3, 90, 5, 8),
('Freestyle Request', 'Ask crowd for freestyle topic', 'crowd_interaction', 'rap_skills', 'Hip Hop', 4, 0.7, 1.6, 120, 7, 9),
('Blues Call Back', 'Traditional blues audience callbacks', 'crowd_interaction', 'crowd_control', 'Blues', 2, 0.6, 1.3, 90, 4, 7),
('Gospel Testimony', 'Share personal story/testimony', 'crowd_interaction', 'storytelling', NULL, 3, 0.6, 1.3, 150, 4, 7),
('Reggae Positive Message', 'Share uplifting message', 'crowd_interaction', 'storytelling', 'Reggae', 2, 0.5, 1.1, 90, 3, 7),
('Punk Rock Rant', 'Political or social commentary', 'crowd_interaction', 'storytelling', 'Punk Rock', 3, 0.7, 1.5, 120, 5, 8),
('Jazz Club Banter', 'Sophisticated audience chat', 'crowd_interaction', 'crowd_control', 'Jazz', 3, 0.5, 1.2, 90, 3, 6),

-- Special Effects (40 items)
('Pyrotechnic Display', 'Coordinated fire effects', 'special_effect', 'stage_production', NULL, 5, 1.0, 2.0, 45, 9, 10),
('Confetti Cannon', 'Burst of confetti over crowd', 'special_effect', 'stage_production', NULL, 2, 0.7, 1.4, 15, 5, 9),
('Smoke Machine', 'Create atmospheric smoke', 'special_effect', 'stage_production', NULL, 1, 0.5, 1.1, 60, 3, 7),
('Strobe Lighting', 'Intense strobe light sequence', 'special_effect', 'stage_production', NULL, 2, 0.6, 1.3, 30, 4, 8),
('Laser Show', 'Synchronized laser display', 'special_effect', 'stage_production', NULL, 4, 0.9, 1.7, 90, 7, 9),
('LED Screen Visuals', 'Custom video content on screens', 'special_effect', 'stage_production', NULL, 3, 0.7, 1.5, 120, 6, 8),
('Mirror Ball Moment', 'Classic disco ball effect', 'special_effect', 'stage_production', NULL, 1, 0.4, 0.9, 45, 2, 6),
('Fog Machine', 'Low-lying fog effect', 'special_effect', 'stage_production', NULL, 1, 0.5, 1.0, 90, 3, 6),
('Bubble Machine', 'Fun bubble effects', 'special_effect', 'stage_production', NULL, 1, 0.4, 0.9, 60, 3, 6),
('Rain Effect', 'Simulated rain on stage', 'special_effect', 'stage_production', NULL, 3, 0.7, 1.4, 90, 6, 8),
('Snow Effect', 'Fake snow falling', 'special_effect', 'stage_production', NULL, 2, 0.6, 1.2, 60, 4, 7),
('Blacklight UV Effect', 'Ultraviolet lighting', 'special_effect', 'stage_production', NULL, 2, 0.5, 1.1, 90, 4, 7),
('Moving Stage Platforms', 'Hydraulic stage movement', 'special_effect', 'stage_production', NULL, 4, 0.8, 1.6, 60, 7, 9),
('Spotlight Solo', 'Single spotlight on performer', 'special_effect', 'stage_production', NULL, 1, 0.4, 0.9, 120, 2, 6),
('Crowd Lighting', 'Lights pointed at audience', 'special_effect', 'stage_production', NULL, 2, 0.5, 1.1, 45, 3, 7),
('Color Wash Change', 'Dramatic color shift', 'special_effect', 'stage_production', NULL, 1, 0.4, 0.8, 20, 2, 6),
('Video Projection Mapping', 'Project visuals on stage/venue', 'special_effect', 'stage_production', NULL, 5, 0.9, 1.8, 120, 8, 9),
('Hologram Effect', 'Create holographic display', 'special_effect', 'stage_production', NULL, 6, 1.1, 2.0, 90, 9, 10),
('Fireworks Finale', 'Indoor firework-style effects', 'special_effect', 'stage_production', NULL, 5, 1.0, 1.9, 30, 9, 10),
('Streamer Cannons', 'Shoot paper streamers', 'special_effect', 'stage_production', NULL, 2, 0.5, 1.0, 20, 4, 7),
('Giant Inflatable Props', 'Deploy large inflatable objects', 'special_effect', 'stage_production', NULL, 3, 0.7, 1.3, 60, 5, 8),
('Stage Flames', 'Controlled fire columns', 'special_effect', 'stage_production', 'Heavy Metal', 5, 1.0, 1.9, 30, 9, 10),
('CO2 Jets', 'Cold CO2 fog blast', 'special_effect', 'stage_production', 'EDM', 3, 0.7, 1.4, 15, 6, 8),
('Water Fountain Effects', 'Synchronized water displays', 'special_effect', 'stage_production', NULL, 4, 0.8, 1.5, 90, 7, 8),
('Glitter Bomb', 'Explode glitter over crowd', 'special_effect', 'stage_production', NULL, 2, 0.6, 1.2, 10, 4, 8),
('Glow Stick Distribution', 'Hand out glow sticks to crowd', 'special_effect', 'stage_production', 'EDM', 1, 0.5, 1.0, 60, 3, 7),
('Neon Light Sculpture', 'Deploy neon art installation', 'special_effect', 'stage_production', NULL, 3, 0.6, 1.2, 120, 5, 7),
('Chaser Light Sequence', 'Running light patterns', 'special_effect', 'stage_production', NULL, 2, 0.5, 1.0, 45, 3, 6),
('Gobo Pattern Projection', 'Project patterns with lights', 'special_effect', 'stage_production', NULL, 2, 0.5, 1.0, 60, 3, 6),
('Haze for Light Beams', 'Atmospheric haze for beam visibility', 'special_effect', 'stage_production', NULL, 1, 0.4, 0.9, 90, 2, 6),
('Floor LED Panels', 'Illuminated floor display', 'special_effect', 'stage_production', 'K-Pop/J-Pop', 4, 0.8, 1.5, 120, 6, 8),
('Rising Platform', 'Elevate performer on platform', 'special_effect', 'stage_production', NULL, 4, 0.8, 1.6, 90, 7, 9),
('Descending From Ceiling', 'Lower performer from above', 'special_effect', 'stage_production', NULL, 5, 0.9, 1.8, 60, 8, 10),
('Revolving Stage', 'Spin stage during performance', 'special_effect', 'stage_production', NULL, 3, 0.6, 1.3, 90, 5, 7),
('Trap Door Entrance', 'Appear through stage floor', 'special_effect', 'stage_production', NULL, 4, 0.8, 1.6, 30, 7, 9),
('Flying Rig', 'Performer suspended on wires', 'special_effect', 'stage_production', NULL, 6, 1.0, 1.9, 120, 9, 10),
('Costume Quick Change', 'On-stage outfit transformation', 'special_effect', 'showmanship', 'K-Pop/J-Pop', 4, 0.7, 1.4, 45, 7, 8),
('Wind Machine', 'Dramatic wind effect', 'special_effect', 'stage_production', NULL, 2, 0.5, 1.1, 60, 4, 6),
('Dry Ice Cascade', 'Flowing dry ice effect', 'special_effect', 'stage_production', NULL, 2, 0.6, 1.2, 45, 4, 7),
('Spark Fountain', 'Cold spark pyrotechnics', 'special_effect', 'stage_production', NULL, 3, 0.7, 1.4, 30, 6, 8),

-- Improvisation (40 items)
('Instrumental Jam Session', 'Open jam with band', 'improvisation', 'improvisation', NULL, 4, 0.7, 1.6, 300, 7, 8),
('Jazz Improvisation', 'Free-form jazz solo', 'improvisation', 'improvisation', 'Jazz', 5, 0.8, 1.7, 240, 8, 9),
('Blues Improv', 'Blues-based improvised solo', 'improvisation', 'improvisation', 'Blues', 4, 0.7, 1.5, 180, 7, 8),
('Rock Guitar Jam', 'Extended rock guitar improvisation', 'improvisation', 'guitar_advanced', 'Rock', 5, 0.8, 1.6, 240, 8, 9),
('Funk Breakdown', 'Improvised funk groove', 'improvisation', 'improvisation', 'R&B', 4, 0.7, 1.5, 200, 7, 8),
('Electronic Live Remix', 'Real-time song remix', 'improvisation', 'production', 'EDM', 6, 0.9, 1.8, 180, 9, 9),
('Drum Circle', 'Collaborative percussion improv', 'improvisation', 'drums_advanced', NULL, 3, 0.6, 1.4, 200, 6, 7),
('Bass Walking Improv', 'Jazz walking bass improvisation', 'improvisation', 'bass_advanced', 'Jazz', 5, 0.7, 1.5, 180, 7, 8),
('Keyboard Soundscape', 'Ambient keyboard exploration', 'improvisation', 'piano_advanced', NULL, 4, 0.6, 1.4, 240, 6, 7),
('Vocal Freestyle Rap', 'Improvised rap about audience', 'improvisation', 'rap_skills', 'Hip Hop', 5, 0.9, 1.8, 180, 9, 10),
('Scat Jazz Improv', 'Impromptu scat singing', 'improvisation', 'vocals_advanced', 'Jazz', 5, 0.7, 1.5, 150, 7, 8),
('Country Fiddle Breakdown', 'Improvised country violin', 'improvisation', 'violin', 'Country', 4, 0.6, 1.4, 180, 6, 7),
('Flamenco Guitar Improv', 'Spontaneous flamenco playing', 'improvisation', 'guitar_advanced', 'Flamenco', 6, 0.8, 1.7, 200, 8, 9),
('Reggae Dub Mix', 'Live dub mixing and effects', 'improvisation', 'production', 'Reggae', 5, 0.7, 1.6, 240, 7, 8),
('Classical Cadenza', 'Improvised classical passage', 'improvisation', 'improvisation', 'Classical', 7, 0.9, 1.8, 150, 8, 9),
('Metal Shred Session', 'Intense guitar shredding', 'improvisation', 'guitar_advanced', 'Heavy Metal', 6, 0.9, 1.8, 200, 9, 9),
('Trap Beat Creation', 'Build trap beat live', 'improvisation', 'production', 'Trap', 5, 0.8, 1.7, 180, 8, 9),
('Lo-Fi Loop Building', 'Create lo-fi beat on stage', 'improvisation', 'production', 'Lo-Fi Hip Hop', 4, 0.7, 1.5, 240, 7, 7),
('Afrobeats Percussion', 'Improvised African rhythms', 'improvisation', 'percussion', 'Afrobeats/Amapiano', 4, 0.7, 1.5, 200, 7, 8),
('Synthwave Soundscape', 'Retro synth improvisation', 'improvisation', 'synthesizer', 'Synthwave', 4, 0.7, 1.4, 200, 6, 7),
('Djent Breakdown', 'Heavy progressive improv', 'improvisation', 'guitar_advanced', 'Metalcore/Djent', 6, 0.8, 1.7, 180, 9, 9),
('R&B Vocal Runs', 'Improvised melismatic vocals', 'improvisation', 'vocals_advanced', 'Alt R&B/Neo-Soul', 5, 0.8, 1.6, 120, 7, 9),
('World Music Fusion', 'Blend different cultural styles', 'improvisation', 'improvisation', 'World Music', 6, 0.8, 1.7, 240, 8, 8),
('Experimental Noise', 'Avant-garde sound exploration', 'improvisation', 'improvisation', NULL, 5, 0.6, 1.5, 180, 7, 6),
('Mashup Creation', 'Combine multiple song elements', 'improvisation', 'improvisation', NULL, 5, 0.8, 1.7, 200, 8, 9),
('Beatbox Battle', 'Showcase beatbox skills', 'improvisation', 'beatboxing', 'Hip Hop', 4, 0.7, 1.6, 150, 7, 9),
('Theremin Improv', 'Otherworldly theremin sounds', 'improvisation', 'theremin', NULL, 6, 0.7, 1.5, 180, 7, 7),
('Harmonica Blues Walk', 'Walking blues harmonica', 'improvisation', 'harmonica', 'Blues', 4, 0.6, 1.4, 120, 6, 7),
('Banjo Breakdown', 'Fast bluegrass improvisation', 'improvisation', 'banjo', 'Country', 5, 0.7, 1.5, 150, 7, 8),
('Accordion Improvisation', 'Spontaneous accordion playing', 'improvisation', 'accordion', NULL, 4, 0.6, 1.3, 180, 6, 6),
('Tabla Solo', 'Indian percussion showcase', 'improvisation', 'percussion', 'World Music', 5, 0.7, 1.5, 200, 7, 7),
('Didgeridoo Drone', 'Australian wind instrument', 'improvisation', 'wind_instruments', 'World Music', 4, 0.6, 1.3, 180, 6, 6),
('Sitar Raga', 'Classical Indian improvisation', 'improvisation', 'sitar', 'World Music', 6, 0.8, 1.6, 300, 8, 8),
('Kora Playing', 'West African harp improvisation', 'improvisation', 'string_instruments', 'African Music', 5, 0.7, 1.4, 200, 7, 7),
('Steel Drum Calypso', 'Caribbean steel drum improv', 'improvisation', 'steel_drum', 'Reggae', 4, 0.6, 1.3, 150, 6, 7),
('Bagpipe Interlude', 'Scottish bagpipe performance', 'improvisation', 'bagpipes', NULL, 5, 0.7, 1.4, 120, 7, 7),
('Hurdy-Gurdy Feature', 'Medieval instrument showcase', 'improvisation', 'hurdy_gurdy', NULL, 5, 0.6, 1.3, 150, 6, 6),
('Ukulele Improv', 'Spontaneous ukulele playing', 'improvisation', 'ukulele', NULL, 3, 0.5, 1.2, 120, 5, 6),
('Mandolin Breakdown', 'Fast mandolin improvisation', 'improvisation', 'mandolin', 'Country', 4, 0.6, 1.4, 150, 6, 7),
('Oud Middle Eastern', 'Arabic oud improvisation', 'improvisation', 'oud', 'World Music', 5, 0.7, 1.5, 180, 7, 7),

-- Storytelling (40 items)
('Song Origin Story', 'Tell story behind the song', 'storytelling', 'storytelling', NULL, 1, 0.5, 1.2, 120, 3, 7),
('Personal Journey', 'Share band''s humble beginnings', 'storytelling', 'storytelling', NULL, 2, 0.6, 1.3, 180, 4, 8),
('Fan Encounter Story', 'Heartwarming fan interaction tale', 'storytelling', 'storytelling', NULL, 1, 0.5, 1.1, 90, 3, 7),
('Tour Mishap Tale', 'Funny story from the road', 'storytelling', 'storytelling', NULL, 2, 0.6, 1.3, 150, 4, 8),
('Studio Recording Story', 'Behind the scenes of making album', 'storytelling', 'storytelling', NULL, 2, 0.5, 1.2, 120, 3, 7),
('First Gig Memory', 'Nostalgic first performance story', 'storytelling', 'storytelling', NULL, 1, 0.5, 1.1, 120, 3, 7),
('Inspiration Explanation', 'What inspired this song', 'storytelling', 'storytelling', NULL, 1, 0.5, 1.2, 90, 3, 7),
('Musical Influence Talk', 'Discuss artists who inspired you', 'storytelling', 'storytelling', NULL, 2, 0.5, 1.1, 150, 3, 7),
('City Love Letter', 'Express love for this city', 'storytelling', 'storytelling', NULL, 1, 0.6, 1.3, 90, 3, 8),
('Venue History', 'Share venue''s musical heritage', 'storytelling', 'storytelling', NULL, 2, 0.5, 1.1, 120, 3, 7),
('Bandmate Introduction', 'Introduce each band member with stories', 'storytelling', 'storytelling', NULL, 2, 0.6, 1.2, 180, 4, 7),
('Overcoming Adversity', 'Share struggle and triumph story', 'storytelling', 'storytelling', NULL, 3, 0.7, 1.5, 200, 5, 9),
('Songwriting Process', 'Explain how song was written', 'storytelling', 'storytelling', NULL, 2, 0.5, 1.1, 120, 3, 6),
('Collaboration Story', 'Tell about working with other artists', 'storytelling', 'storytelling', NULL, 2, 0.5, 1.2, 120, 3, 7),
('Equipment Story', 'Story about beloved instrument', 'storytelling', 'storytelling', NULL, 1, 0.4, 1.0, 90, 2, 6),
('Childhood Music Memory', 'Share early musical experience', 'storytelling', 'storytelling', NULL, 1, 0.5, 1.1, 120, 3, 7),
('Teacher/Mentor Tribute', 'Honor someone who taught you', 'storytelling', 'storytelling', NULL, 2, 0.6, 1.3, 150, 4, 8),
('Cultural Heritage', 'Share cultural musical roots', 'storytelling', 'storytelling', NULL, 2, 0.6, 1.3, 150, 4, 8),
('Genre History Lesson', 'Educate about musical genre', 'storytelling', 'storytelling', NULL, 3, 0.5, 1.2, 180, 4, 7),
('Political Statement', 'Share important social message', 'storytelling', 'storytelling', NULL, 3, 0.7, 1.5, 150, 5, 8),
('Love Story', 'Romantic tale behind love song', 'storytelling', 'storytelling', NULL, 1, 0.5, 1.2, 120, 3, 8),
('Loss and Healing', 'Emotional story about grief', 'storytelling', 'storytelling', NULL, 2, 0.7, 1.4, 150, 5, 9),
('Funny Lyric Mishap', 'Share embarrassing lyric mistake', 'storytelling', 'storytelling', NULL, 1, 0.5, 1.1, 60, 2, 7),
('Fan Request Story', 'How a fan influenced this song', 'storytelling', 'storytelling', NULL, 1, 0.5, 1.1, 90, 3, 7),
('Dream Achievement', 'Celebrate milestone reached', 'storytelling', 'storytelling', NULL, 2, 0.6, 1.3, 120, 4, 8),
('Musical Evolution', 'How your sound has changed', 'storytelling', 'storytelling', NULL, 2, 0.5, 1.1, 150, 3, 6),
('Producer Anecdote', 'Story about working in studio', 'storytelling', 'storytelling', NULL, 2, 0.5, 1.1, 120, 3, 6),
('Festival Experience', 'Share festival performance memory', 'storytelling', 'storytelling', NULL, 2, 0.5, 1.2, 120, 3, 7),
('Support Act Thank You', 'Praise and story about opener', 'storytelling', 'storytelling', NULL, 1, 0.4, 0.9, 90, 2, 6),
('Competition Win Story', 'Share breakthrough competition', 'storytelling', 'storytelling', NULL, 2, 0.5, 1.2, 120, 3, 7),
('Near Miss Story', 'Almost gave up but persevered', 'storytelling', 'storytelling', NULL, 3, 0.7, 1.4, 150, 5, 9),
('Serendipity Tale', 'Lucky break or coincidence', 'storytelling', 'storytelling', NULL, 2, 0.5, 1.1, 120, 3, 7),
('Haters to Fans', 'Won over skeptics story', 'storytelling', 'storytelling', NULL, 2, 0.6, 1.3, 120, 4, 8),
('DIY Ethos', 'Share independent music journey', 'storytelling', 'storytelling', 'Punk Rock', 2, 0.6, 1.3, 150, 4, 8),
('Hometown Pride', 'Talk about where you''re from', 'storytelling', 'storytelling', NULL, 1, 0.5, 1.1, 90, 3, 7),
('Last Show Story', 'Reflect on previous performance', 'storytelling', 'storytelling', NULL, 1, 0.4, 1.0, 90, 2, 6),
('Next Album Tease', 'Hint at upcoming music', 'storytelling', 'storytelling', NULL, 1, 0.5, 1.1, 90, 3, 7),
('Musical Discovery', 'How you found your sound', 'storytelling', 'storytelling', NULL, 2, 0.5, 1.2, 150, 3, 7),
('Charity Cause', 'Share important cause you support', 'storytelling', 'storytelling', NULL, 2, 0.6, 1.3, 120, 4, 8),
('Thank You Speech', 'Express gratitude to fans and team', 'storytelling', 'storytelling', NULL, 1, 0.6, 1.3, 120, 3, 8);