
-- Add new columns to crew_catalog for star rating, fame-based unlocking, and exclusivity
ALTER TABLE crew_catalog ADD COLUMN IF NOT EXISTS star_rating INTEGER NOT NULL DEFAULT 5 CHECK (star_rating >= 1 AND star_rating <= 10);
ALTER TABLE crew_catalog ADD COLUMN IF NOT EXISTS min_fame_required INTEGER NOT NULL DEFAULT 0;
ALTER TABLE crew_catalog ADD COLUMN IF NOT EXISTS hired_by_band_id UUID REFERENCES public.bands(id) ON DELETE SET NULL;
ALTER TABLE crew_catalog ADD COLUMN IF NOT EXISTS city TEXT;

-- Add new columns to band_crew_members for cohesion mechanics
ALTER TABLE band_crew_members ADD COLUMN IF NOT EXISTS star_rating INTEGER DEFAULT 5 CHECK (star_rating >= 1 AND star_rating <= 10);
ALTER TABLE band_crew_members ADD COLUMN IF NOT EXISTS cohesion_rating NUMERIC NOT NULL DEFAULT 0 CHECK (cohesion_rating >= 0 AND cohesion_rating <= 100);
ALTER TABLE band_crew_members ADD COLUMN IF NOT EXISTS gigs_together INTEGER NOT NULL DEFAULT 0;
ALTER TABLE band_crew_members ADD COLUMN IF NOT EXISTS catalog_crew_id TEXT;

-- Create unique constraint so one crew member can only be hired by one band
CREATE UNIQUE INDEX IF NOT EXISTS idx_crew_catalog_hired_by_band ON crew_catalog(id) WHERE hired_by_band_id IS NOT NULL;

-- Clear existing crew_catalog to seed fresh data
DELETE FROM crew_catalog;

-- Seed 54 crew members across 5 tiers
-- TIER 1 (1-2 stars): Entry-level, requires 0 fame - $200-500/gig
INSERT INTO crew_catalog (id, name, role, headline, background, skill, salary, experience, morale, loyalty, assignment, focus, specialties, traits, openings, star_rating, min_fame_required) VALUES
('t1-tm-rookie', 'Dave Murphy', 'Tour Manager', 'Fresh out of college but eager to learn the ropes.', 'Recently graduated from music business school. Organized campus concerts.', 25, 200, 1, 'steady', 50, 'Touring', 'Basic logistics', ARRAY['Schedule management', 'Basic routing'], ARRAY['Eager', 'Learning'], 1, 2, 0),
('t1-foh-beginner', 'Sarah Chen', 'Front of House Engineer', 'Local venue mixer taking first tour gig.', 'Spent two years mixing at a local club. Knows the basics well.', 30, 250, 2, 'steady', 55, 'Touring', 'Basic mixing', ARRAY['PA setup', 'Basic EQ'], ARRAY['Patient', 'Detail-oriented'], 1, 2, 0),
('t1-ld-starter', 'Mike Torres', 'Lighting Director', 'DIY venue tech branching into touring.', 'Self-taught lighting designer from the punk scene.', 28, 220, 1, 'steady', 52, 'Production', 'Basic lighting', ARRAY['Par cans', 'Basic cues'], ARRAY['Resourceful', 'Budget-conscious'], 1, 2, 0),
('t1-road-helper', 'Jim Wilson', 'Road Crew Chief', 'Former warehouse worker with strong back.', 'No touring experience but reliable and hardworking.', 22, 180, 0, 'steady', 48, 'Production', 'Load assistance', ARRAY['Heavy lifting', 'Truck loading'], ARRAY['Strong', 'Punctual'], 1, 1, 0),
('t1-backline-newbie', 'Amy Lee', 'Backline Technician', 'Guitar shop employee wanting tour experience.', 'Spent 3 years repairing guitars at a local shop.', 32, 280, 1, 'steady', 58, 'Touring', 'Basic guitar tech', ARRAY['String changes', 'Basic setup'], ARRAY['Careful', 'Eager'], 1, 2, 0),
('t1-merch-first', 'Tyler Brown', 'Merch Director', 'College student selling band merch part-time.', 'Sold merch at festivals during summers.', 20, 150, 0, 'steady', 45, 'Standby', 'Basic sales', ARRAY['Cash handling', 'Inventory count'], ARRAY['Friendly', 'Quick learner'], 1, 1, 0),
('t1-security-bouncer', 'Marcus Gray', 'Security Lead', 'Former bar bouncer transitioning to touring.', 'Five years of nightclub security experience.', 35, 300, 2, 'steady', 60, 'Touring', 'Basic security', ARRAY['Crowd control', 'ID checking'], ARRAY['Imposing', 'Calm'], 1, 2, 0),
('t1-wardrobe-helper', 'Jessie Quinn', 'Wardrobe Stylist', 'Fashion student interning on tour.', 'Studies fashion design, loves band aesthetics.', 25, 200, 0, 'steady', 50, 'Standby', 'Basic styling', ARRAY['Outfit organization', 'Quick changes'], ARRAY['Creative', 'Enthusiastic'], 1, 2, 0),
('t1-tm-budget', 'Pete Santos', 'Tour Manager', 'Former van driver promoted to management.', 'Drove bands for 3 years, learned the business from inside.', 28, 230, 2, 'steady', 55, 'Touring', 'Budget tours', ARRAY['Van routing', 'Cheap motels'], ARRAY['Frugal', 'Resourceful'], 1, 2, 0),
('t1-foh-local', 'Kim Park', 'Front of House Engineer', 'Church sound tech looking for road work.', 'Mixed worship services for 4 years, solid fundamentals.', 33, 270, 3, 'steady', 58, 'Touring', 'Clean mixes', ARRAY['Vocal clarity', 'Feedback control'], ARRAY['Patient', 'Reliable'], 1, 2, 0),

-- TIER 2 (3-4 stars): Mid-level, requires 500 fame - $500-1000/gig
('t2-tm-seasoned', 'Maria Gonzalez', 'Tour Manager', 'Club circuit veteran with solid contacts.', 'Managed 15+ club tours, knows every booker on the circuit.', 55, 600, 5, 'steady', 68, 'Touring', 'Club touring', ARRAY['Venue relationships', 'Settlement negotiation', 'Routing'], ARRAY['Well-connected', 'Organized'], 1, 4, 500),
('t2-foh-club', 'James Cooper', 'Front of House Engineer', 'Respected club engineer with loyal following.', 'Known for getting great sound in terrible rooms.', 58, 650, 6, 'steady', 70, 'Touring', 'Room correction', ARRAY['System tuning', 'Monitor mixing', 'Problem solving'], ARRAY['Adaptive', 'Ears of gold'], 1, 4, 500),
('t2-ld-creative', 'Nina Volkov', 'Lighting Director', 'Theater-trained LD bringing drama to rock shows.', 'Worked in theater before transitioning to live music.', 52, 580, 4, 'steady', 65, 'Production', 'Theatrical lighting', ARRAY['Moving heads', 'Color theory', 'Timecode sync'], ARRAY['Artistic', 'Dramatic'], 1, 4, 500),
('t2-road-experienced', 'Carlos Reyes', 'Road Crew Chief', 'Festival veteran who runs tight crews.', 'Worked 50+ festivals, knows every stage configuration.', 55, 550, 6, 'steady', 68, 'Production', 'Festival setups', ARRAY['Stage plots', 'Crew coordination', 'Time management'], ARRAY['Efficient', 'No-nonsense'], 1, 4, 500),
('t2-backline-solid', 'Rachel Kim', 'Backline Technician', 'Multi-instrument tech with quick hands.', 'Can handle guitar, bass, and keys with equal skill.', 60, 700, 5, 'steady', 72, 'Touring', 'Multi-instrument', ARRAY['Quick changes', 'Troubleshooting', 'Intonation'], ARRAY['Versatile', 'Quick thinker'], 1, 4, 500),
('t2-merch-savvy', 'Alex Morgan', 'Merch Director', 'Retail background with online integration skills.', 'Built merch programs for several mid-tier bands.', 48, 520, 4, 'steady', 62, 'Standby', 'Omnichannel', ARRAY['POS systems', 'Inventory management', 'Display design'], ARRAY['Business-minded', 'Tech-savvy'], 1, 3, 500),
('t2-security-pro', 'Derek Stone', 'Security Lead', 'Certified crowd management specialist.', 'OSHA certified, trained in emergency response.', 58, 680, 7, 'steady', 70, 'Touring', 'Crowd safety', ARRAY['Emergency protocols', 'Artist protection', 'Pit management'], ARRAY['Professional', 'Alert'], 1, 4, 500),
('t2-wardrobe-exp', 'Sophie Laurent', 'Wardrobe Stylist', 'Fashion industry veteran with tour experience.', 'Styled music videos before moving to live shows.', 50, 600, 4, 'steady', 65, 'Standby', 'Stage fashion', ARRAY['Quick changes', 'Wardrobe management', 'Brand consistency'], ARRAY['Stylish', 'Efficient'], 1, 3, 500),
('t2-tm-regional', 'Brandon Hayes', 'Tour Manager', 'Regional expert who knows every market.', 'Deep knowledge of specific touring regions.', 52, 580, 5, 'steady', 66, 'Touring', 'Regional expertise', ARRAY['Local knowledge', 'Radio contacts', 'Press relations'], ARRAY['Well-traveled', 'Networked'], 1, 4, 500),
('t2-foh-broadcast', 'Yuki Tanaka', 'Front of House Engineer', 'Broadcast experience brings polish to live shows.', 'Worked in radio before transitioning to live sound.', 55, 620, 5, 'steady', 68, 'Touring', 'Broadcast quality', ARRAY['Recording mixes', 'Multitrack', 'Streaming'], ARRAY['Technical', 'Precise'], 1, 4, 500),
('t2-ld-programmer', 'Chris Williams', 'Lighting Director', 'Skilled programmer with efficient pre-production.', 'Creates stunning shows with minimal gear.', 54, 600, 5, 'steady', 67, 'Production', 'Programming', ARRAY['MA2/3', 'Visualization', 'Budget rigs'], ARRAY['Technical', 'Efficient'], 1, 4, 500),

-- TIER 3 (5-6 stars): Professional, requires 2000 fame - $1500-2500/gig
('t3-tm-arena', 'Mara Liang', 'Tour Manager', 'Arena routing ace who never misses curfew.', 'Guided platinum acts through world tours without a canceled date.', 75, 1800, 8, 'electric', 78, 'Touring', 'Arena logistics', ARRAY['Visa wrangling', 'Promoter negotiations', 'Crisis messaging'], ARRAY['Budget hawk', 'Sleeps on the bus'], 1, 6, 2000),
('t3-foh-clarity', 'Riley Cortez', 'Front of House Engineer', 'Makes stadium crowds feel like club mixes.', 'Fans routinely share board mixes because the clarity is unreal.', 78, 2000, 10, 'electric', 84, 'Touring', 'Stadium sound', ARRAY['Timecode automation', 'Broadcast-ready', 'Arena EQ'], ARRAY['Meticulous', 'Calm under pressure'], 1, 6, 2000),
('t3-ld-cinematic', 'Sera Nyx', 'Lighting Director', 'Turns stages into cinematic worlds with synced cues.', 'Was the secret weapon behind a breakout bands residency visuals.', 72, 1700, 7, 'steady', 72, 'Production', 'Cinematic design', ARRAY['Timecode programming', 'Hybrid rigs', 'Laser choreography'], ARRAY['Precision', 'Story-driven'], 1, 6, 2000),
('t3-road-chief', 'Donovan Wells', 'Road Crew Chief', 'Leads 30-person crews with zen calm.', 'Former construction superintendent who reinvented load-ins.', 70, 1600, 12, 'steady', 80, 'Production', 'Large crews', ARRAY['Stage builds', 'Crew routing', 'Risk assessment'], ARRAY['Hands-on', 'Crew dad'], 1, 5, 2000),
('t3-backline-ace', 'Jules Armitage', 'Backline Technician', 'Can rebuild a pedalboard blindfolded between songs.', 'Supported festival headliners with last-second gear swaps.', 68, 1500, 6, 'steady', 70, 'Touring', 'Quick changes', ARRAY['Guitar setups', 'Synth calibration', 'Emergency repairs'], ARRAY['Unflappable', 'Gear whisperer'], 1, 5, 2000),
('t3-merch-director', 'Lex Avery', 'Merch Director', 'Turns merch lines into retail experiences that trend.', 'Built programs that doubled per-head spend for indie darlings.', 65, 1400, 5, 'steady', 68, 'Standby', 'Brand experience', ARRAY['Pop-up shops', 'Inventory optimization', 'Design drops'], ARRAY['Storyteller', 'Data fluent'], 1, 5, 2000),
('t3-security-chief', 'Ibrahim Cole', 'Security Lead', 'Festival-level crowd management expert.', 'Led security for major festival main stages.', 72, 1700, 8, 'steady', 75, 'Touring', 'Festival security', ARRAY['VIP protection', 'Barrier management', 'Medical coordination'], ARRAY['Commanding', 'Level-headed'], 1, 6, 2000),
('t3-wardrobe-pro', 'Elena Vasquez', 'Wardrobe Stylist', 'Celebrity stylist with touring expertise.', 'Styled magazine covers before taking shows on the road.', 68, 1600, 6, 'steady', 70, 'Standby', 'Celebrity styling', ARRAY['Custom design', 'Quick changes', 'Brand development'], ARRAY['Fashion-forward', 'Detail obsessed'], 1, 5, 2000),
('t3-tm-international', 'Henrik Berg', 'Tour Manager', 'International touring specialist with global contacts.', 'Managed tours across 40+ countries seamlessly.', 73, 1900, 9, 'electric', 76, 'Touring', 'International', ARRAY['Work permits', 'Currency management', 'Cultural navigation'], ARRAY['Multilingual', 'Diplomatic'], 1, 6, 2000),
('t3-foh-veteran', 'Diana Ross Jr', 'Front of House Engineer', 'Three decades of live sound excellence.', 'Mixed legends and newcomers with equal dedication.', 76, 1850, 15, 'steady', 82, 'Touring', 'Classic sound', ARRAY['Analog warmth', 'Digital precision', 'Mix philosophy'], ARRAY['Experienced', 'Mentor'], 1, 6, 2000),
('t3-ld-festival', 'Marco DiStefano', 'Lighting Director', 'Festival main stage regular with huge rig experience.', 'Designed shows for headliners at major festivals.', 74, 1750, 8, 'steady', 74, 'Production', 'Festival scale', ARRAY['Large rigs', 'Outdoor challenges', 'Weather adaptation'], ARRAY['Ambitious', 'Big picture'], 1, 6, 2000),

-- TIER 4 (7-8 stars): Elite, requires 10000 fame - $3000-4500/gig
('t4-tm-platinum', 'Victoria Sterling', 'Tour Manager', 'Platinum-selling tour architect.', 'Every tour she manages goes platinum. Industry legend.', 88, 3500, 15, 'electric', 88, 'Touring', 'Platinum campaigns', ARRAY['Record label liaison', 'Media coordination', 'Revenue optimization'], ARRAY['Perfectionist', 'Industry connected'], 1, 8, 10000),
('t4-foh-grammy', 'Marcus Webb', 'Front of House Engineer', 'Grammy-winning mixer adapting studio magic live.', 'His live mixes have won industry awards.', 90, 3800, 18, 'electric', 90, 'Touring', 'Award-winning sound', ARRAY['Signature sound', 'Immersive mixing', 'Artist collaboration'], ARRAY['Visionary', 'Perfectionist'], 1, 8, 10000),
('t4-ld-visionary', 'Astrid Moon', 'Lighting Director', 'Visual artist redefining live show aesthetics.', 'Her shows are featured in design magazines.', 85, 3300, 12, 'electric', 85, 'Production', 'Visual art', ARRAY['Custom installations', 'Video integration', 'Architectural mapping'], ARRAY['Artistic', 'Innovative'], 1, 8, 10000),
('t4-road-legend', 'Big Mike Johnson', 'Road Crew Chief', 'Stadium production coordinator extraordinaire.', 'Built stages for Super Bowl halftime shows.', 86, 3200, 20, 'electric', 88, 'Production', 'Stadium production', ARRAY['Massive rigs', 'Union coordination', 'Safety systems'], ARRAY['Legendary', 'Respected'], 1, 7, 10000),
('t4-backline-master', 'Kenji Yamamoto', 'Backline Technician', 'The tech that rockstars request by name.', 'Personal tech for multiple guitar heroes.', 84, 3100, 14, 'electric', 86, 'Touring', 'A-list service', ARRAY['Custom modifications', 'Vintage maintenance', 'Collection curation'], ARRAY['Trusted', 'Elite'], 1, 7, 10000),
('t4-merch-empire', 'Jordan Blake', 'Merch Director', 'Built merch empires for stadium acts.', 'Turned band merch into fashion brands.', 82, 3000, 10, 'electric', 82, 'Standby', 'Brand building', ARRAY['Fashion collaborations', 'Limited editions', 'Global distribution'], ARRAY['Visionary', 'Entrepreneur'], 1, 7, 10000),
('t4-security-exec', 'Colonel Ray Martinez', 'Security Lead', 'Former Secret Service with celebrity protection experience.', 'Protected heads of state before moving to entertainment.', 88, 3600, 16, 'electric', 90, 'Touring', 'Executive protection', ARRAY['Threat assessment', 'Secure transport', 'Counter-surveillance'], ARRAY['Elite', 'Discrete'], 1, 8, 10000),
('t4-wardrobe-celeb', 'Valentina Rossi', 'Wardrobe Stylist', 'A-list celebrity stylist with Grammy red carpet experience.', 'Styled multiple Grammy and VMA red carpet moments.', 85, 3400, 12, 'electric', 84, 'Standby', 'Red carpet ready', ARRAY['Custom couture', 'Award show prep', 'Image consulting'], ARRAY['A-list connections', 'Trendsetter'], 1, 8, 10000),
('t4-tm-global', 'Dmitri Volkov', 'Tour Manager', 'Global tour strategist for arena-level acts.', 'Optimizes routing across continents for maximum profit.', 86, 3600, 14, 'electric', 86, 'Touring', 'Global optimization', ARRAY['Multi-continent routing', 'Tax optimization', 'Sponsorship integration'], ARRAY['Strategic', 'Numbers-driven'], 1, 8, 10000),
('t4-foh-immersive', 'Samantha Rivers', 'Front of House Engineer', 'Immersive audio pioneer pushing live sound boundaries.', 'Designed spatial audio systems for arena tours.', 88, 3700, 12, 'electric', 88, 'Touring', 'Spatial audio', ARRAY['Dolby Atmos live', '360 sound', 'Subwoofer arrays'], ARRAY['Innovator', 'Tech pioneer'], 1, 8, 10000),

-- TIER 5 (9-10 stars): Legendary, requires 50000 fame - $5000-8000/gig
('t5-tm-legendary', 'Michael "The Fixer" Chen', 'Tour Manager', 'Industry legend who has managed the biggest tours in history.', 'Has managed tours grossing over $1 billion combined. The ultimate fixer.', 98, 6500, 25, 'electric', 95, 'Touring', 'Legendary campaigns', ARRAY['Crisis management', 'Industry relationships', 'Tour architecture'], ARRAY['Legendary', 'Untouchable'], 1, 10, 50000),
('t5-foh-icon', 'Robert "The Ears" Thompson', 'Front of House Engineer', 'The most sought-after live mixer on the planet.', 'Artists fight over his availability. His mixes define eras.', 99, 7000, 30, 'electric', 98, 'Touring', 'Iconic sound', ARRAY['Signature systems', 'Artist partnerships', 'Sound innovation'], ARRAY['Iconic', 'Irreplaceable'], 1, 10, 50000),
('t5-ld-icon', 'Yuki "Lumina" Sato', 'Lighting Director', 'The lighting designer behind the most memorable shows ever.', 'Her work is studied in design schools worldwide.', 97, 6200, 22, 'electric', 96, 'Production', 'Legendary design', ARRAY['Groundbreaking installations', 'Technology innovation', 'Cultural moments'], ARRAY['Visionary', 'Legendary'], 1, 10, 50000),
('t5-road-titan', 'Frank "The Mountain" OBrien', 'Road Crew Chief', 'The production manager every stadium tour wants.', 'Built the infrastructure for historys biggest tours.', 96, 5800, 28, 'electric', 95, 'Production', 'Mega production', ARRAY['360 stages', 'Moving platforms', 'Pyrotechnics'], ARRAY['Titan', 'Institution'], 1, 9, 50000),
('t5-backline-legend', 'Eddie "Golden Hands" Sanchez', 'Backline Technician', 'The tech who maintains historys most valuable instruments.', 'Trusted with guitars worth millions. Priceless expertise.', 95, 5500, 25, 'electric', 94, 'Touring', 'Priceless care', ARRAY['Museum pieces', 'Custom builds', 'Restoration'], ARRAY['Trusted', 'Irreplaceable'], 1, 9, 50000),
('t5-merch-mogul', 'Zara Diamond', 'Merch Director', 'Built merchandise into a billion-dollar business.', 'Transformed artist merchandise into lifestyle brands.', 94, 5200, 18, 'electric', 92, 'Standby', 'Empire building', ARRAY['Brand licensing', 'Fashion lines', 'Global retail'], ARRAY['Mogul', 'Visionary'], 1, 9, 50000),
('t5-security-legend', 'John "Ghost" Mitchell', 'Security Lead', 'The security chief every superstar wants.', 'Protected the biggest names for decades. Invisible and invincible.', 98, 7500, 30, 'electric', 97, 'Touring', 'Superstar protection', ARRAY['Intelligence networks', 'Global coordination', 'Zero incidents'], ARRAY['Ghost', 'Legend'], 1, 10, 50000),
('t5-wardrobe-icon', 'Isabella DeLuca', 'Wardrobe Stylist', 'The stylist whose looks become iconic moments.', 'Created outfits that defined generations of artists.', 96, 6000, 20, 'electric', 94, 'Standby', 'Iconic fashion', ARRAY['Costume design', 'Brand creation', 'Cultural impact'], ARRAY['Icon maker', 'Legendary'], 1, 10, 50000);
