-- Historical ordering compatibility note:
-- this migration sorts before the base schema migration that creates public.profiles.
-- The side-hustle progression tables depend on public.profiles, so their
-- materialisation is intentionally deferred to
-- 20260901225500_finalize_preprofile_player_tables.sql.
--
-- Existing environments that already applied the original migration are unaffected;
-- the finaliser is idempotent.
