-- Historical migration ordering repair.
--
-- This migration originally created the music video tables before core dependencies
-- such as public.releases, public.bands, public.band_members and the shared
-- update_updated_at_column() trigger function existed on a clean database.
-- That made `supabase db reset` fail even though deployed environments already had
-- the required objects from their historical evolution.
--
-- The complete music video schema (including the fields introduced by the companion
-- 20250620120000 migration) is now created at the dependency-safe Phase 4 migration:
--   20251116081455_b656d8bc-8184-4de7-b40d-71793921f362.sql
--
-- Keep this migration as an intentional no-op so existing migration history remains
-- stable while fresh databases can replay the repository deterministically.
SELECT 1;
