-- Production-forward history marker for the 2026-09-01 Festival directory repair.
--
-- The canonical Festival tables used by this projection are created by the repository's
-- frozen inherited 2029 migration chain. Production already has those tables and this
-- function was applied directly there on 2026-09-01.
--
-- Do not create the function here: on a clean database this current-dated migration is
-- intentionally encountered before the inherited Festival bootstrap. The matching
-- clean-build parity SQL lives in:
-- supabase/reconciliation/festival/20260901_festival_directory_cards.sql
