WITH famous(name, city_name, capacity, venue_type, prestige_level, description) AS (
  VALUES
  ('Royal Albert Hall','London',5272,'concert_hall',96,'Victorian rotunda in Kensington; the most storied concert hall in Britain.'),
  ('O2 Academy Brixton','London',4921,'large_venue',88,'Sloped-floor art deco hall, legendary for its atmosphere.'),
  ('The 100 Club','London',350,'rock_club',82,'Basement club on Oxford Street where punk was born.'),
  ('Ronnie Scott''s','London',250,'jazz_lounge',85,'Soho''s hallowed jazz basement since 1959.'),
  ('The Cavern Club','Liverpool',400,'rock_club',90,'The sweaty cellar that launched Merseybeat.'),
  ('Manchester Apollo','Manchester',3500,'theatre',82,'Art deco theatre and northern rock institution.'),
  ('Barrowland Ballroom','Glasgow',1900,'large_venue',86,'Sprung dancefloor and starry ceiling; Glasgow''s loudest crowd.'),
  ('Vicar Street','Dublin',1500,'large_venue',78,'Intimate Dublin room beloved by songwriters.'),
  ('Madison Square Garden','New York',20789,'indoor_arena',98,'The World''s Most Famous Arena.'),
  ('Apollo Theater','New York',1506,'theatre',93,'Harlem''s cathedral of soul and amateur night legend.'),
  ('Bowery Ballroom','New York',575,'rock_club',80,'Downtown tastemaker room for breaking bands.'),
  ('Village Vanguard','New York',132,'jazz_lounge',88,'Basement wedge of a room; the holy site of live jazz.'),
  ('Whisky a Go Go','Los Angeles',500,'rock_club',87,'Sunset Strip club that made west coast rock.'),
  ('Hollywood Bowl','Los Angeles',17500,'amphitheatre',94,'Band-shell amphitheatre under the Hollywood hills.'),
  ('The Troubadour','Los Angeles',500,'rock_club',85,'West Hollywood room where singer-songwriters were made.'),
  ('The Fillmore','San Francisco',1315,'large_venue',89,'Psychedelic ballroom with chandeliers and free apples.'),
  ('Ryman Auditorium','Nashville',2362,'theatre',92,'The Mother Church of Country Music.'),
  ('Bluebird Cafe','Nashville',90,'cafe_stage',80,'Tiny writers-in-the-round listening room.'),
  ('Red Rocks Amphitheatre','Denver',9525,'amphitheatre',96,'Natural sandstone amphitheatre; the ultimate bucket-list gig.'),
  ('Preservation Hall','New Orleans',100,'jazz_lounge',84,'French Quarter shrine to traditional New Orleans jazz.'),
  ('Tipitina''s','New Orleans',1000,'rock_club',78,'Uptown dancehall and funk institution.'),
  ('Sun Studio','Memphis',120,'live_house',86,'The birthplace of rock and roll, still hosting live sets.'),
  ('Continental Club','Austin',300,'rock_club',79,'South Congress roots-rock mainstay.'),
  ('Metro','Chicago',1150,'rock_club',80,'Wrigleyville club that broke countless alternative acts.'),
  ('Buddy Guy''s Legends','Chicago',500,'jazz_lounge',82,'South Loop home of Chicago blues.'),
  ('Paradise Rock Club','Boston',933,'rock_club',77,'Boston''s scrappy college-town rock room.'),
  ('The Fillmore Philadelphia','Philadelphia',2500,'large_venue',76,'Fishtown warehouse hall with a classic Fillmore feel.'),
  ('Saint Andrew''s Hall','Detroit',1000,'rock_club',78,'Detroit rock and hip-hop crucible.'),
  ('The Crocodile','Seattle',560,'rock_club',80,'Belltown club at the heart of the grunge explosion.'),
  ('Massey Hall','Toronto',2765,'concert_hall',85,'Toronto''s beloved acoustic jewel.'),
  ('Olympia','Montreal',2000,'theatre',74,'Historic Montreal theatre with a devoted crowd.'),
  ('L''Olympia','Paris',1996,'theatre',90,'The red-velvet Paris hall of chanson and rock alike.'),
  ('Le Bataclan','Paris',1500,'large_venue',84,'Pagoda-fronted Paris venue with fierce loyalty.'),
  ('Paradiso','Amsterdam',1500,'large_venue',88,'Converted church; Europe''s definitive rock temple.'),
  ('Melkweg','Amsterdam',1500,'large_venue',82,'Old dairy turned multi-room music hub.'),
  ('SO36','Berlin',800,'rock_club',82,'Kreuzberg punk stronghold.'),
  ('Berghain Kantine','Berlin',300,'warehouse',80,'Concrete side-room of Berlin''s techno cathedral.'),
  ('Grosser Freiheit 36','Hamburg',1400,'rock_club',80,'Reeperbahn club on the street the Beatles cut their teeth.'),
  ('Wiener Konzerthaus','Vienna',1840,'concert_hall',86,'Gilded Viennese hall with peerless acoustics.'),
  ('Debaser Strand','Stockholm',1000,'rock_club',74,'Sodermalm indie hub.'),
  ('Rockefeller','Oslo',1350,'large_venue',74,'Old bathhouse turned Oslo rock staple.'),
  ('VEGA','Copenhagen',1550,'large_venue',80,'Danish modernist union hall, now a music landmark.'),
  ('Alcatraz','Milan',3000,'warehouse',76,'Industrial Milanese hall for heavy nights.'),
  ('Razzmatazz','Barcelona',2500,'warehouse',78,'Five-room Poblenou complex that never sleeps.'),
  ('Sala Apolo','Madrid',1600,'large_venue',76,'Madrid ballroom with a late-night pulse.'),
  ('Nippon Budokan','Tokyo',14471,'indoor_arena',93,'Martial arts hall immortalised by live albums.'),
  ('Shibuya O-East','Tokyo',1300,'live_house',78,'Shibuya live house at the centre of Japan''s scene.'),
  ('Olympic Hall','Seoul',15000,'indoor_arena',82,'Seoul''s go-to arena for homecoming shows.'),
  ('Sydney Opera House Concert Hall','Sydney',2679,'concert_hall',95,'Sails over the harbour; the most photographed stage on earth.'),
  ('Enmore Theatre','Sydney',2500,'theatre',80,'Newtown''s much-loved sloped-floor theatre.'),
  ('The Corner Hotel','Melbourne',800,'rock_club',78,'Richmond pub venue with a famous rooftop.'),
  ('Forum Melbourne','Melbourne',2100,'theatre',82,'Moorish fantasy interior and starlit ceiling.'),
  ('Teatro Gran Rex','Buenos Aires',3262,'theatre',82,'Corrientes avenue rationalist theatre.'),
  ('Circo Voador','Rio de Janeiro',2300,'festival_tent',80,'Lapa''s open-sided big top under the arches.'),
  ('Foro Sol','Mexico City',65000,'stadium',88,'Vast Mexico City bowl for stadium-scale nights.'),
  ('El Plaza Condesa','Mexico City',1800,'theatre',76,'Art deco Condesa hall.'),
  ('Kingston Dub Club','Kingston',600,'rooftop_terrace',80,'Hillside sound-system session above the city lights.'),
  ('Royal Opera House Mumbai','Mumbai',1000,'theatre',78,'Restored Baroque opera house.'),
  ('Kirstenbosch Summer Stage','Cape Town',3000,'park_bandstand',78,'Botanical garden lawn beneath Table Mountain.'),
  ('Green Theatre Gorky Park','Moscow',5000,'amphitheatre',74,'Open-air Gorky Park stage.'),
  ('The Chelsea at Cosmopolitan','Las Vegas',3200,'theatre',78,'Two-tier Strip theatre for residencies.'),
  ('Tabernacle','Atlanta',2600,'theatre',78,'Former church with three balconies of noise.'),
  ('Ohio Theatre Hall','Philadelphia',1200,'theatre',70,'Ornate east coast road-house stage.')
)
INSERT INTO public.venues (
  name, location, city_id, capacity, venue_type, base_payment, prestige_level,
  reputation, reputation_score, is_legendary, description,
  sound_system_rating, lighting_rating, backstage_quality, equipment_quality,
  has_green_room, has_recording_capability, minimum_guarantee, slots_per_day
)
SELECT
  f.name,
  c.name || ', ' || c.country,
  c.id,
  f.capacity,
  f.venue_type,
  GREATEST(500, LEAST(250000, ROUND(f.capacity * 1.6 * (1 + f.prestige_level / 120.0))::int)),
  f.prestige_level,
  LEAST(100, f.prestige_level),
  LEAST(100, f.prestige_level),
  true,
  f.description,
  LEAST(5, GREATEST(3, (f.prestige_level / 20)::int)),
  LEAST(5, GREATEST(3, (f.prestige_level / 20)::int)),
  LEAST(5, GREATEST(3, (f.prestige_level / 22)::int)),
  LEAST(5, GREATEST(3, (f.prestige_level / 22)::int)),
  true,
  f.prestige_level >= 85,
  GREATEST(500, ROUND(f.capacity * 0.9)::int),
  CASE WHEN f.capacity > 10000 THEN 1 WHEN f.capacity > 2000 THEN 2 ELSE 3 END
FROM famous f
JOIN public.cities c ON c.name = f.city_name
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE lower(v.name) = lower(f.name) AND v.city_id = c.id
);