-- Backfill image references for existing crew
UPDATE public.crew_catalog SET image_url = 'tour-manager' WHERE role = 'Tour Manager';
UPDATE public.crew_catalog SET image_url = 'foh-engineer' WHERE role = 'Front of House Engineer';
UPDATE public.crew_catalog SET image_url = 'lighting-director' WHERE role = 'Lighting Director';
UPDATE public.crew_catalog SET image_url = 'road-chief' WHERE role = 'Road Crew Chief';
UPDATE public.crew_catalog SET image_url = 'backline-tech' WHERE role = 'Backline Technician';
UPDATE public.crew_catalog SET image_url = 'merch-director' WHERE role = 'Merch Director';
UPDATE public.crew_catalog SET image_url = 'security-lead' WHERE role = 'Security Lead';
UPDATE public.crew_catalog SET image_url = 'wardrobe-stylist' WHERE role = 'Wardrobe Stylist';

-- Seed 40 new crew (5 per role, mixed tiers)
INSERT INTO public.crew_catalog (id, name, role, headline, background, skill, salary, experience, morale, loyalty, assignment, focus, specialties, traits, openings, star_rating, min_fame_required, image_url) VALUES
-- Tour Manager (5)
('seed-tm-01','Lena Akinwale','Tour Manager','Routes club tours through three time zones without breaking a sweat.','Came up running indie van tours in West Africa before scaling to European club circuits.',55,1400,3,'steady',60,'Touring','Routing & settlements',ARRAY['Van tours','Visa packets','Per-diems'],ARRAY['Patient','Spreadsheet ninja'],1,3,200,'tour-manager'),
('seed-tm-02','Hugo Bartlett','Tour Manager','Day-of-show problem solver loved by every promoter on the circuit.','Cut his teeth backstage at theater runs in the UK midlands.',62,1900,5,'steady',65,'Touring','Day-of-show ops',ARRAY['Promoter relations','Settlement math','Crew morale'],ARRAY['Calm','Direct'],1,5,1200,'tour-manager'),
('seed-tm-03','Priya Raman','Tour Manager','Bus-tour vet who never lets the wheels stop turning.','Built logistics for sleeper-bus tours across North America and India.',71,2600,7,'steady',72,'Touring','Bus & sleeper logistics',ARRAY['Sleeper schedules','Border crossings','Driver relief'],ARRAY['Methodical','Bus-life'],1,6,3500,'tour-manager'),
('seed-tm-04','Stefan Holm','Tour Manager','Festival-circuit specialist with relationships at every European stage.','Ran festival routing for a Scandinavian booking agency before going freelance.',80,3200,9,'electric',78,'Touring','Festival routing',ARRAY['Festival packets','Day-off logic','Hospitality riders'],ARRAY['Network-rich','Diplomatic'],1,7,12000,'tour-manager'),
('seed-tm-05','Aaliyah Brooks','Tour Manager','Stadium-grade tour manager trusted with platinum acts.','Built and led tour ops for two arena-headlining acts back-to-back years.',92,4500,12,'electric',86,'Touring','Stadium operations',ARRAY['Stadium routing','Crisis comms','Crew of 60+'],ARRAY['Unflappable','Visionary'],1,9,55000,'tour-manager'),

-- FOH Engineer (5)
('seed-foh-01','Owen Park','Front of House Engineer','Mixes punchy club shows on a shoestring rider.','Self-taught, learned by mixing at every dive bar in his hometown.',50,1300,2,'steady',55,'Touring','Front of house mix',ARRAY['Vocal clarity','EQ on the fly','Tube monitors'],ARRAY['Ear-driven','Scrappy'],1,2,150,'foh-engineer'),
('seed-foh-02','Camille Soto','Front of House Engineer','Theater-circuit pro with a love for deep low end.','Toured theaters with two indie acts before going freelance.',64,2000,5,'steady',62,'Touring','Front of house mix',ARRAY['Theater acoustics','Subwoofer tuning','In-ear coordination'],ARRAY['Detailed','Steady hand'],1,4,1500,'foh-engineer'),
('seed-foh-03','Devon Mackay','Front of House Engineer','Festival mixer with stadium broadcast credits.','Spent years mixing festival side stages and slid into broadcast mixes.',74,2900,7,'electric',70,'Touring','Festival & broadcast mix',ARRAY['Stem mixes','Festival changeovers','Broadcast splits'],ARRAY['Fast-changeover','Composed'],1,6,4000,'foh-engineer'),
('seed-foh-04','Hana Beck','Front of House Engineer','Arena tour mixer with multiple gold-cert tour credits.','Came up programming digital consoles, now headlines arena rigs worldwide.',85,3700,10,'electric',80,'Touring','Arena mix',ARRAY['Digital console programming','Tour file management','Arena tuning'],ARRAY['Precise','Cool under pressure'],1,8,18000,'foh-engineer'),
('seed-foh-05','Kwame Asante','Front of House Engineer','Legendary mixer whose front-of-house mixes get bootlegged for being too good.','Three decades of touring; mentored a generation of mixers.',95,5000,15,'electric',90,'Touring','Stadium FOH mix',ARRAY['Stadium PA tuning','Immersive mix','Live streaming'],ARRAY['Iconic','Mentor'],1,10,80000,'foh-engineer'),

-- Lighting Director (5)
('seed-ld-01','Jamie Stoll','Lighting Director','Programs club rigs that punch above their weight.','Started as a lampie at college venues, now a freelance club LD.',52,1350,2,'steady',58,'Production','Lighting design',ARRAY['Conventional rigs','Color theory','Fast cueing'],ARRAY['Creative','Resourceful'],1,2,200,'lighting-director'),
('seed-ld-02','Mira Patel','Lighting Director','Designs theater shows with painterly, story-driven cueing.','Trained in theatrical lighting before crossing into rock tours.',66,2100,5,'steady',64,'Production','Theatrical lighting',ARRAY['Story arcs','Atmospherics','Scenic integration'],ARRAY['Story-driven','Patient'],1,4,1600,'lighting-director'),
('seed-ld-03','Felix Bauer','Lighting Director','Programs timecoded festival sets with surgical precision.','German festival circuit veteran with deep timecode chops.',76,2900,8,'electric',72,'Production','Timecoded design',ARRAY['Timecode','MA programming','Pixel mapping'],ARRAY['Precision','Workaholic'],1,6,4500,'lighting-director'),
('seed-ld-04','Inara Cole','Lighting Director','Arena LD with multiple touring rig design credits.','Designed touring rigs for two platinum tours before going freelance.',86,3700,10,'electric',80,'Production','Arena lighting design',ARRAY['Touring rig design','Arena programming','Pyro coordination'],ARRAY['Visionary','Collaborative'],1,8,20000,'lighting-director'),
('seed-ld-05','Takeshi Mori','Lighting Director','Cinematic stadium designer credited on award-show productions.','Built award-show lighting packages and toured with global pop icons.',96,5200,16,'electric',88,'Production','Stadium & broadcast design',ARRAY['Broadcast lighting','Stadium kabuki','Award-show design'],ARRAY['Iconic','Unrelenting'],1,10,90000,'lighting-director'),

-- Road Crew Chief (5)
('seed-road-01','Bex Ortiz','Road Crew Chief','Runs tight 4-person load-ins for club runs.','Started as backline tech, now runs small-club crews.',54,1300,3,'steady',60,'Production','Club load-ins',ARRAY['Stage stack','Cable management','Quick strike'],ARRAY['Hustle','Crew-first'],1,2,200,'road-chief'),
('seed-road-02','Trent Nakamura','Road Crew Chief','Theater-tour chief with strong vendor relationships.','Six theater tours under his belt with no missed load-ins.',66,2000,6,'steady',66,'Production','Theater load-ins',ARRAY['Vendor coordination','Truck packing','Crew routing'],ARRAY['Organized','Calm'],1,4,1800,'road-chief'),
('seed-road-03','Gabriela Souza','Road Crew Chief','Festival production chief who keeps changeovers under 12 minutes.','Brazilian festival circuit veteran who scaled up to international fests.',77,2900,8,'electric',72,'Production','Festival changeovers',ARRAY['Changeover drills','Local crew leadership','Multi-stage ops'],ARRAY['Decisive','Energetic'],1,6,4500,'road-chief'),
('seed-road-04','Magnus Larsson','Road Crew Chief','Arena chief who has loaded in over 600 shows.','Veteran of nine world tours with stadium and arena production.',87,3800,11,'electric',82,'Production','Arena production',ARRAY['Steel & motors','Stage builds','Risk assessment'],ARRAY['Commanding','Hands-on'],1,8,22000,'road-chief'),
('seed-road-05','Ada Whitfield','Road Crew Chief','Stadium tour chief whose load-ins are studied by industry mags.','Designed load-in workflows now used by major touring outfits.',96,5300,17,'electric',90,'Production','Stadium production',ARRAY['Stadium builds','Multi-truck logistics','Crew of 80+'],ARRAY['Iconic','Mentor'],1,10,95000,'road-chief'),

-- Backline Technician (5)
('seed-bl-01','Mateo Gallego','Backline Technician','Reliable guitar tech for club tours.','Started as a roadie, learned setups on the road.',52,1250,2,'steady',58,'Touring','Guitar tech',ARRAY['Guitar setups','String changes','Pedal repair'],ARRAY['Steady','Patient'],1,2,150,'backline-tech'),
('seed-bl-02','Suki Tanaka','Backline Technician','Drum tech with a feel for tuning under hot lights.','Tours with three indie bands as a freelance drum tech.',65,2000,5,'steady',64,'Touring','Drum tech',ARRAY['Drum tuning','Hardware repair','Trigger setups'],ARRAY['Detail-driven','Calm'],1,4,1500,'backline-tech'),
('seed-bl-03','Connor Whelan','Backline Technician','Guitar & bass tech with a workshop on wheels.','Built a mobile workshop into his crew kit and never misses a set.',75,2700,7,'electric',70,'Touring','Multi-instrument tech',ARRAY['Guitar setups','Bass setups','Electronics repair'],ARRAY['Inventive','Quick hands'],1,6,4000,'backline-tech'),
('seed-bl-04','Olu Adesina','Backline Technician','Synth tech for arena shows with tour-pack programming chops.','Toured with electronic acts as a dedicated synth & MIDI tech.',85,3500,10,'electric',78,'Touring','Synth & MIDI tech',ARRAY['Synth programming','MIDI rigs','Track playback'],ARRAY['Tech-savvy','Reliable'],1,8,16000,'backline-tech'),
('seed-bl-05','Roxy Vance','Backline Technician','Stadium-level tech who can rewire a rig mid-set.','Three world tours, zero failed setups.',95,4900,15,'electric',88,'Touring','Stadium backline',ARRAY['Live rewiring','Multi-rig coordination','Tour-pack design'],ARRAY['Iconic','Unflappable'],1,10,80000,'backline-tech'),

-- Merch Director (5)
('seed-mrc-01','Hollis Day','Merch Director','Runs tidy club merch tables that move limited drops.','Started designing band tees, now manages full merch ops.',50,1200,2,'steady',56,'Standby','Club merch ops',ARRAY['Pop-up merch','Inventory','Cash handling'],ARRAY['Friendly','Detail-driven'],1,2,150,'merch-director'),
('seed-mrc-02','Naomi Ezra','Merch Director','Theater-tour merch director with strong drop strategy.','Grew per-head spend for two indie acts during recent tours.',62,1800,5,'steady',62,'Standby','Theater merch ops',ARRAY['Drop planning','Inventory','Vendor sourcing'],ARRAY['Strategic','Creative'],1,4,1400,'merch-director'),
('seed-mrc-03','Kade Lutz','Merch Director','Festival merch lead who runs pop-ups that go viral.','Pop-up shop operator who scaled to festival circuits.',73,2600,7,'electric',68,'Standby','Pop-up ops',ARRAY['Viral drops','Pop-up design','Limited runs'],ARRAY['Trend-spotter','Storyteller'],1,6,4500,'merch-director'),
('seed-mrc-04','Sienna Holt','Merch Director','Arena merch director with deep ecom integration.','Built ecom + tour merch programs for a major indie label.',83,3400,9,'electric',76,'Standby','Tour & ecom ops',ARRAY['Ecom integration','Tour drops','Capsule design'],ARRAY['Data-fluent','Visionary'],1,8,18000,'merch-director'),
('seed-mrc-05','Marquise Adler','Merch Director','Stadium-level merch mogul known for narrative drops.','Ran merch for two record-setting stadium tours.',94,4800,14,'electric',86,'Standby','Stadium merch ops',ARRAY['Narrative drops','Tour capsule','Brand collabs'],ARRAY['Iconic','Brand-builder'],1,10,75000,'merch-director'),

-- Security Lead (5)
('seed-sec-01','Bruno Vega','Security Lead','Bouncer-turned-tour security with cool-headed presence.','Worked nightclub security for a decade before joining tours.',54,1300,3,'steady',62,'Production','Door & artist security',ARRAY['Crowd response','Artist screening','Backstage perimeter'],ARRAY['Steady','Friendly-but-firm'],1,2,200,'security-lead'),
('seed-sec-02','Talia Roth','Security Lead','Theater-circuit security lead with calm de-escalation skills.','Trained in conflict de-escalation, runs theater-tour security.',64,1900,5,'steady',66,'Production','Theater security',ARRAY['De-escalation','Backstage screening','Advance sweeps'],ARRAY['Calm','Observant'],1,4,1500,'security-lead'),
('seed-sec-03','Hank Volkov','Security Lead','Festival security lead trusted by promoters worldwide.','Spent years on festival security teams, now leads artist details.',75,2700,8,'electric',72,'Production','Festival security',ARRAY['Festival logistics','Artist details','Riot response'],ARRAY['Decisive','Crew-friendly'],1,6,4200,'security-lead'),
('seed-sec-04','Imani Pryce','Security Lead','Arena security exec with celebrity advance experience.','Ran advance teams for celebrity-heavy productions.',86,3600,11,'electric',82,'Production','Arena security',ARRAY['Advance ops','VIP escorts','Venue partnerships'],ARRAY['Protective','Strategic'],1,8,22000,'security-lead'),
('seed-sec-05','Riggs Donovan','Security Lead','Stadium security legend with an immaculate tour record.','Three world tours, zero incidents on his watch.',95,5000,16,'electric',90,'Production','Stadium security',ARRAY['Stadium perimeters','Crisis response','Executive protection'],ARRAY['Iconic','Unflappable'],1,10,90000,'security-lead'),

-- Wardrobe Stylist (5)
('seed-ward-01','Pippa Inoue','Wardrobe Stylist','Quick-change wizard for club tours.','Self-taught stylist, started altering tour outfits in her bedroom.',50,1200,2,'steady',56,'Studio','Club wardrobe',ARRAY['Quick repairs','Outfit pulls','Steaming'],ARRAY['Friendly','Fast hands'],1,2,150,'wardrobe-stylist'),
('seed-ward-02','Andre Lefevre','Wardrobe Stylist','Theater-tour stylist with capsule-collection chops.','French stylist known for dramatic theater capsules.',62,1800,5,'steady',62,'Studio','Theater wardrobe',ARRAY['Capsule collections','Quick changes','Wardrobe budgets'],ARRAY['Visionary','Detail-driven'],1,4,1400,'wardrobe-stylist'),
('seed-ward-03','Mei Tanaka','Wardrobe Stylist','Festival stylist who builds tour looks that photograph beautifully.','Tokyo stylist with editorial credits, now styling festival runs.',72,2500,7,'electric',68,'Studio','Festival wardrobe',ARRAY['Editorial styling','On-stage durability','Photo-ready looks'],ARRAY['Trend-spotter','Composed'],1,6,4000,'wardrobe-stylist'),
('seed-ward-04','Lior Ben-Ami','Wardrobe Stylist','Arena tour stylist with award-show credits.','Worked award-show red-carpet styling, now leads arena wardrobe.',83,3300,9,'electric',76,'Studio','Arena wardrobe',ARRAY['Award-show looks','Tour capsule','Atelier collabs'],ARRAY['Visionary','Network-rich'],1,8,18000,'wardrobe-stylist'),
('seed-ward-05','Cyra Devereux','Wardrobe Stylist','Stadium-level stylist with iconic tour-defining looks.','Defined the visual identity of two record-setting tours.',94,4700,14,'electric',86,'Studio','Stadium & broadcast wardrobe',ARRAY['Tour identity','Couture collabs','Broadcast wardrobe'],ARRAY['Iconic','Visionary'],1,10,80000,'wardrobe-stylist');