ALTER TABLE public.festival_scale_catalogue
 ADD COLUMN minimum_site_capacity integer,
 ADD COLUMN maximum_site_capacity integer,
 ADD COLUMN minimum_stages smallint,
 ADD COLUMN maximum_stages smallint,
 ADD COLUMN maximum_main_stage_capacity integer,
 ADD COLUMN maximum_total_stage_capacity integer,
 ADD COLUMN requires_secondary_stage boolean NOT NULL DEFAULT false,
 ADD COLUMN requires_accessibility_plan boolean NOT NULL DEFAULT false;
UPDATE public.festival_scale_catalogue SET
 minimum_site_capacity=CASE key WHEN 'local' THEN 500 WHEN 'small' THEN 1000 WHEN 'medium' THEN 5000 WHEN 'large' THEN 15000 ELSE 40000 END,
 maximum_site_capacity=CASE key WHEN 'local' THEN 1000 WHEN 'small' THEN 5000 WHEN 'medium' THEN 20000 WHEN 'large' THEN 50000 ELSE 120000 END,
 minimum_stages=CASE key WHEN 'local' THEN 1 WHEN 'small' THEN 1 WHEN 'medium' THEN 2 WHEN 'large' THEN 3 ELSE 4 END,
 maximum_stages=CASE key WHEN 'local' THEN 1 WHEN 'small' THEN 2 WHEN 'medium' THEN 4 WHEN 'large' THEN 6 ELSE 10 END,
 maximum_main_stage_capacity=CASE key WHEN 'local' THEN 1000 WHEN 'small' THEN 5000 WHEN 'medium' THEN 18000 WHEN 'large' THEN 45000 ELSE 100000 END,
 maximum_total_stage_capacity=CASE key WHEN 'local' THEN 1000 WHEN 'small' THEN 7500 WHEN 'medium' THEN 35000 WHEN 'large' THEN 100000 ELSE 300000 END,
 requires_secondary_stage=key IN ('medium','large','major'), requires_accessibility_plan=key IN ('medium','large','major');
ALTER TABLE public.festival_scale_catalogue ALTER COLUMN minimum_site_capacity SET NOT NULL, ALTER COLUMN maximum_site_capacity SET NOT NULL, ALTER COLUMN minimum_stages SET NOT NULL, ALTER COLUMN maximum_stages SET NOT NULL, ALTER COLUMN maximum_main_stage_capacity SET NOT NULL, ALTER COLUMN maximum_total_stage_capacity SET NOT NULL;

CREATE TABLE public.festival_site_plans (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_company_id uuid UNIQUE NOT NULL REFERENCES public.festival_companies(id) ON DELETE CASCADE, configuration_id uuid NOT NULL REFERENCES public.festival_configurations(id) ON DELETE CASCADE,
 site_source text NOT NULL CHECK(site_source IN ('existing_venue','temporary_site','open_land','mixed_site')), existing_venue_id uuid REFERENCES public.venues(id), site_name text NOT NULL CHECK(char_length(btrim(site_name)) BETWEEN 1 AND 120), site_type text NOT NULL CHECK(site_type IN ('indoor','outdoor','mixed')), site_description text,
 city_id uuid NOT NULL REFERENCES public.cities(id), timezone text, total_capacity integer NOT NULL CHECK(total_capacity>0), usable_capacity integer NOT NULL CHECK(usable_capacity>0 AND usable_capacity<=total_capacity), reserved_capacity integer NOT NULL DEFAULT 0 CHECK(reserved_capacity>=0 AND reserved_capacity<total_capacity), minimum_age smallint CHECK(minimum_age BETWEEN 0 AND 99), curfew_time time, gates_open_time time, daily_open_time time NOT NULL, daily_close_time time NOT NULL,
 accessibility_notes text, transport_notes text, weather_exposure text, ground_condition text, facility_recommendations jsonb NOT NULL DEFAULT '{}', validation_issues jsonb NOT NULL DEFAULT '[]', status text NOT NULL DEFAULT 'in_progress' CHECK(status IN ('not_started','in_progress','site_selected','stages_configured','ready_for_ticketing')), planning_version integer NOT NULL DEFAULT 1 CHECK(planning_version>0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz,
 CHECK((site_source='existing_venue')=(existing_venue_id IS NOT NULL)), CHECK(daily_open_time<daily_close_time)
);
CREATE TABLE public.festival_site_plan_stages (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_site_plan_id uuid NOT NULL REFERENCES public.festival_site_plans(id) ON DELETE CASCADE, festival_company_id uuid NOT NULL REFERENCES public.festival_companies(id) ON DELETE CASCADE,
 name text NOT NULL, slug text NOT NULL, stage_type text NOT NULL CHECK(stage_type IN ('main','secondary','emerging','acoustic','dance','specialist','community')), sort_order smallint NOT NULL CHECK(sort_order>=0), capacity integer NOT NULL CHECK(capacity>0), minimum_artist_fame integer, performance_area_quality smallint, sound_quality smallint, lighting_quality smallint, production_complexity text NOT NULL DEFAULT 'standard', indoor boolean NOT NULL, covered boolean NOT NULL, accessible_viewing_capacity integer NOT NULL DEFAULT 0 CHECK(accessible_viewing_capacity>=0 AND accessible_viewing_capacity<=capacity), opens_at time NOT NULL, closes_at time NOT NULL, changeover_minutes smallint NOT NULL CHECK(changeover_minutes BETWEEN 5 AND 180), headline_slot_minutes smallint NOT NULL CHECK(headline_slot_minutes BETWEEN 15 AND 240), standard_slot_minutes smallint NOT NULL CHECK(standard_slot_minutes BETWEEN 10 AND 180), status text NOT NULL DEFAULT 'planned' CHECK(status IN ('planned','ready')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(festival_site_plan_id,name), UNIQUE(festival_site_plan_id,slug), UNIQUE(festival_site_plan_id,sort_order), CHECK(opens_at<closes_at)
);
CREATE UNIQUE INDEX festival_site_plan_stages_one_main ON public.festival_site_plan_stages(festival_site_plan_id) WHERE stage_type='main';
CREATE TABLE public.festival_site_plan_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_company_id uuid NOT NULL REFERENCES public.festival_companies(id) ON DELETE CASCADE, caller_profile_id uuid NOT NULL REFERENCES public.profiles(id), idempotency_key uuid NOT NULL, payload_hash text NOT NULL, result jsonb, status text NOT NULL DEFAULT 'processing' CHECK(status IN ('processing','succeeded')), created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, UNIQUE(festival_company_id,caller_profile_id,idempotency_key));
CREATE TABLE public.festival_site_plan_audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_company_id uuid NOT NULL REFERENCES public.festival_companies(id) ON DELETE CASCADE, site_plan_id uuid NOT NULL REFERENCES public.festival_site_plans(id) ON DELETE CASCADE, actor_profile_id uuid REFERENCES public.profiles(id), event_type text NOT NULL, previous_version integer NOT NULL, new_version integer NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());

GRANT ALL ON public.festival_site_plans TO service_role;
GRANT ALL ON public.festival_site_plan_stages TO service_role;
GRANT ALL ON public.festival_site_plan_requests TO service_role;
GRANT ALL ON public.festival_site_plan_audit TO service_role;

ALTER TABLE public.festival_site_plans ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_site_plan_stages ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_site_plan_requests ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_site_plan_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.festival_site_plans,public.festival_site_plan_stages,public.festival_site_plan_requests,public.festival_site_plan_audit FROM PUBLIC,anon,authenticated;

CREATE FUNCTION public._festival_site_plan_result(p_company uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT jsonb_build_object('festivalCompanyId',fc.id,'festivalName',cfg.public_name,'configurationStatus',cfg.setup_status,'sitePlan',CASE WHEN sp.id IS NULL THEN NULL ELSE jsonb_build_object('id',sp.id,'siteSource',sp.site_source,'existingVenueId',sp.existing_venue_id,'siteName',sp.site_name,'siteType',sp.site_type,'siteDescription',coalesce(sp.site_description,''),'cityId',sp.city_id,'timezone',sp.timezone,'totalCapacity',sp.total_capacity,'usableCapacity',sp.usable_capacity,'reservedCapacity',sp.reserved_capacity,'minimumAge',sp.minimum_age,'curfewTime',sp.curfew_time,'gatesOpenTime',sp.gates_open_time,'dailyOpenTime',sp.daily_open_time,'dailyCloseTime',sp.daily_close_time,'accessibilityNotes',coalesce(sp.accessibility_notes,''),'transportNotes',coalesce(sp.transport_notes,''),'weatherExposure',coalesce(sp.weather_exposure,''),'groundCondition',coalesce(sp.ground_condition,''),'status',sp.status) END,
 'venueOptions',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',v.id,'name',v.name,'cityId',v.city_id,'cityName',c.name,'venueType',coalesce(v.venue_type,'venue'),'siteType',CASE WHEN coalesce(v.venue_type,'') IN ('festival','stadium','park') THEN 'outdoor' ELSE 'indoor' END,'capacity',v.capacity,'quality',coalesce(v.prestige_level,0),'active',true,'festivalCompatible',coalesce((v.requirements->>'festival_compatible')::boolean,v.venue_type IN ('festival','stadium','arena')),'availability','unknown') ORDER BY v.name),'[]') FROM public.venues v JOIN public.cities c ON c.id=v.city_id WHERE v.city_id=cfg.home_city_id AND v.capacity>0),
 'scaleLimits',jsonb_build_object('minimumSiteCapacity',sc.minimum_site_capacity,'maximumSiteCapacity',sc.maximum_site_capacity,'minimumStages',sc.minimum_stages,'maximumStages',sc.maximum_stages,'maximumMainStageCapacity',sc.maximum_main_stage_capacity,'maximumTotalStageCapacity',sc.maximum_total_stage_capacity,'requiresSecondaryStage',sc.requires_secondary_stage,'requiresAccessibilityPlan',sc.requires_accessibility_plan),
 'stages',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',s.id,'name',s.name,'slug',s.slug,'stageType',s.stage_type,'sortOrder',s.sort_order,'capacity',s.capacity,'minimumArtistFame',s.minimum_artist_fame,'performanceAreaQuality',s.performance_area_quality,'soundQuality',s.sound_quality,'lightingQuality',s.lighting_quality,'productionComplexity',s.production_complexity,'indoor',s.indoor,'covered',s.covered,'accessibleViewingCapacity',s.accessible_viewing_capacity,'opensAt',s.opens_at,'closesAt',s.closes_at,'changeoverMinutes',s.changeover_minutes,'headlineSlotMinutes',s.headline_slot_minutes,'standardSlotMinutes',s.standard_slot_minutes,'status',s.status) ORDER BY s.sort_order),'[]') FROM public.festival_site_plan_stages s WHERE s.festival_site_plan_id=sp.id),
 'facilities',coalesce(sp.facility_recommendations,'{"toiletsRequired":0,"medicalPointsRequired":0,"securityPositionsRequired":0,"barsRecommended":0,"foodVendorSpacesRecommended":0,"waterPointsRequired":0,"accessibleViewingRequired":0,"backstageZonesRequired":0,"parkingRequirement":0,"transportRequirement":0}'),'issues',coalesce(sp.validation_issues,'[]'),'ready',coalesce(sp.status='ready_for_ticketing',false),'canWrite',true,'planningVersion',coalesce(sp.planning_version,0),'updatedAt',sp.updated_at,
 'capacityMetrics',jsonb_build_object('largestStageCapacity',coalesce((SELECT max(capacity) FROM public.festival_site_plan_stages WHERE festival_site_plan_id=sp.id),0),'totalStageCapacity',coalesce((SELECT sum(capacity) FROM public.festival_site_plan_stages WHERE festival_site_plan_id=sp.id),0),'mainStageShare',coalesce((SELECT round(100.0*capacity/nullif(sp.usable_capacity,0)) FROM public.festival_site_plan_stages WHERE festival_site_plan_id=sp.id AND stage_type='main'),0),'accessibleViewingTotal',coalesce((SELECT sum(accessible_viewing_capacity) FROM public.festival_site_plan_stages WHERE festival_site_plan_id=sp.id),0),'peakCrowdConcentration',coalesce((SELECT round(100.0*max(capacity)/nullif(sp.usable_capacity,0)) FROM public.festival_site_plan_stages WHERE festival_site_plan_id=sp.id),0)))
 FROM public.festival_companies fc JOIN public.festival_configurations cfg ON cfg.festival_company_id=fc.id JOIN public.festival_scale_catalogue sc ON sc.key=cfg.festival_scale LEFT JOIN public.festival_site_plans sp ON sp.festival_company_id=fc.id WHERE fc.id=p_company $$;

CREATE FUNCTION public.get_festival_site_plan(p_festival_company_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE p uuid:=public._caller_profile_id(); fc public.festival_companies%ROWTYPE; BEGIN IF auth.uid() IS NULL THEN RAISE EXCEPTION 'festival_site_plan_forbidden' USING ERRCODE='P0001'; END IF; SELECT * INTO fc FROM public.festival_companies WHERE id=p_festival_company_id; IF NOT FOUND OR (fc.owner_profile_id IS DISTINCT FROM p AND NOT coalesce(public.has_role(auth.uid(),'admin'::public.app_role),false)) THEN RAISE EXCEPTION 'festival_site_plan_forbidden' USING ERRCODE='P0001'; END IF; RETURN public._festival_site_plan_result(p_festival_company_id); END $$;

CREATE FUNCTION public.save_festival_site_plan(p_festival_company_id uuid,p_expected_version integer,p_site_plan jsonb,p_stages jsonb,p_idempotency_key uuid,p_complete boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE profile uuid:=public._caller_profile_id(); cfg public.festival_configurations%ROWTYPE; plan public.festival_site_plans%ROWTYPE; lim public.festival_scale_catalogue%ROWTYPE; req public.festival_site_plan_requests%ROWTYPE; h text; result jsonb; issues jsonb:='[]'; facilities jsonb; source text:=p_site_plan->>'siteSource'; venue uuid; city uuid; cap int; stage_count int; main_count int;
BEGIN
 IF auth.uid() IS NULL OR NOT EXISTS(SELECT 1 FROM public.festival_companies f WHERE f.id=p_festival_company_id AND (f.owner_profile_id=profile OR coalesce(public.has_role(auth.uid(),'admin'::public.app_role),false))) THEN RAISE EXCEPTION 'festival_site_plan_forbidden' USING ERRCODE='P0001'; END IF;
 SELECT * INTO cfg FROM public.festival_configurations WHERE festival_company_id=p_festival_company_id; IF cfg.setup_status<>'ready_for_planning' THEN RAISE EXCEPTION 'festival_configuration_incomplete' USING ERRCODE='P0001'; END IF; SELECT * INTO lim FROM public.festival_scale_catalogue WHERE key=cfg.festival_scale;
 PERFORM pg_advisory_xact_lock(hashtextextended(p_festival_company_id::text||p_idempotency_key::text,0)); h:=encode(digest(jsonb_build_object('version',p_expected_version,'site',p_site_plan,'stages',(SELECT coalesce(jsonb_agg(x ORDER BY (x->>'sortOrder')::int),'[]') FROM jsonb_array_elements(p_stages) x),'complete',p_complete)::text,'sha256'),'hex');
 SELECT * INTO req FROM public.festival_site_plan_requests WHERE festival_company_id=p_festival_company_id AND caller_profile_id=profile AND idempotency_key=p_idempotency_key FOR UPDATE; IF FOUND THEN IF req.payload_hash<>h THEN RAISE EXCEPTION 'festival_site_plan_idempotency_conflict' USING ERRCODE='P0001'; END IF; IF req.status='succeeded' THEN RETURN req.result; END IF; END IF;
 IF source NOT IN ('existing_venue','temporary_site','open_land','mixed_site') THEN RAISE EXCEPTION 'festival_site_invalid' USING ERRCODE='P0001'; END IF; city:=(p_site_plan->>'cityId')::uuid; cap:=(p_site_plan->>'usableCapacity')::int; IF city<>cfg.home_city_id THEN RAISE EXCEPTION 'festival_city_mismatch' USING ERRCODE='P0001'; END IF; IF cap NOT BETWEEN lim.minimum_site_capacity AND lim.maximum_site_capacity THEN RAISE EXCEPTION 'festival_capacity_invalid' USING ERRCODE='P0001'; END IF;
 IF source='existing_venue' THEN venue:=(p_site_plan->>'existingVenueId')::uuid; IF NOT EXISTS(SELECT 1 FROM public.venues v WHERE v.id=venue AND v.city_id=city AND v.capacity>=cap AND coalesce((v.requirements->>'festival_compatible')::boolean,v.venue_type IN ('festival','stadium','arena'))) THEN RAISE EXCEPTION 'festival_venue_invalid' USING ERRCODE='P0001'; END IF; ELSE IF char_length(btrim(coalesce(p_site_plan->>'siteName','')))=0 THEN RAISE EXCEPTION 'festival_site_invalid' USING ERRCODE='P0001'; END IF; END IF;
 stage_count:=jsonb_array_length(p_stages); SELECT count(*) INTO main_count FROM jsonb_array_elements(p_stages) s WHERE s->>'stageType'='main'; IF stage_count NOT BETWEEN lim.minimum_stages AND lim.maximum_stages OR main_count<>1 THEN issues:=issues||jsonb_build_array(jsonb_build_object('code',CASE WHEN main_count=0 THEN 'main_stage_required' ELSE 'multiple_main_stages' END,'severity','error','section','stages','field',null,'message','Exactly one Main Stage is required.','blocking',true)); END IF;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_stages) s WHERE (s->>'capacity')::int<=0 OR (s->>'capacity')::int>cap OR (s->>'accessibleViewingCapacity')::int>(s->>'capacity')::int OR (s->>'opensAt')::time >= (s->>'closesAt')::time OR (s->>'opensAt')::time < (p_site_plan->>'dailyOpenTime')::time OR (s->>'closesAt')::time > (p_site_plan->>'dailyCloseTime')::time) OR EXISTS(SELECT 1 FROM jsonb_array_elements(p_stages) s GROUP BY lower(btrim(s->>'name')) HAVING count(*)>1) THEN RAISE EXCEPTION 'festival_stage_invalid' USING ERRCODE='P0001'; END IF;
 IF p_complete AND issues<>'[]' THEN RAISE EXCEPTION 'festival_site_invalid' USING ERRCODE='P0001'; END IF;
 facilities:=jsonb_build_object('toiletsRequired',ceil(cap/75.0),'medicalPointsRequired',greatest(1,ceil(cap/5000.0)),'securityPositionsRequired',ceil(cap/250.0),'barsRecommended',ceil(cap/500.0),'foodVendorSpacesRecommended',ceil(cap/400.0),'waterPointsRequired',ceil(cap/500.0),'accessibleViewingRequired',ceil(cap/100.0),'backstageZonesRequired',greatest(1,stage_count),'parkingRequirement',ceil(cap/4.0),'transportRequirement',ceil(cap*0.7));
 SELECT * INTO plan FROM public.festival_site_plans WHERE festival_company_id=p_festival_company_id FOR UPDATE; IF FOUND AND plan.planning_version<>p_expected_version THEN RAISE EXCEPTION 'festival_site_plan_stale' USING ERRCODE='P0001'; ELSIF NOT FOUND AND p_expected_version<>0 THEN RAISE EXCEPTION 'festival_site_plan_stale' USING ERRCODE='P0001'; END IF;
 INSERT INTO public.festival_site_plan_requests(festival_company_id,caller_profile_id,idempotency_key,payload_hash) VALUES(p_festival_company_id,profile,p_idempotency_key,h);
 INSERT INTO public.festival_site_plans(festival_company_id,configuration_id,site_source,existing_venue_id,site_name,site_type,site_description,city_id,timezone,total_capacity,usable_capacity,reserved_capacity,minimum_age,curfew_time,gates_open_time,daily_open_time,daily_close_time,accessibility_notes,transport_notes,weather_exposure,ground_condition,facility_recommendations,validation_issues,status,planning_version,completed_at) VALUES(p_festival_company_id,cfg.id,source,venue,CASE WHEN venue IS NULL THEN btrim(p_site_plan->>'siteName') ELSE (SELECT name FROM public.venues WHERE id=venue) END,p_site_plan->>'siteType',p_site_plan->>'siteDescription',city,p_site_plan->>'timezone',(p_site_plan->>'totalCapacity')::int,cap,coalesce((p_site_plan->>'reservedCapacity')::int,0),(p_site_plan->>'minimumAge')::int,(p_site_plan->>'curfewTime')::time,(p_site_plan->>'gatesOpenTime')::time,(p_site_plan->>'dailyOpenTime')::time,(p_site_plan->>'dailyCloseTime')::time,p_site_plan->>'accessibilityNotes',p_site_plan->>'transportNotes',p_site_plan->>'weatherExposure',p_site_plan->>'groundCondition',facilities,issues,CASE WHEN p_complete THEN 'ready_for_ticketing' WHEN stage_count>0 THEN 'stages_configured' ELSE 'site_selected' END,1,CASE WHEN p_complete THEN now() END) ON CONFLICT(festival_company_id) DO UPDATE SET site_source=excluded.site_source,existing_venue_id=excluded.existing_venue_id,site_name=excluded.site_name,site_type=excluded.site_type,site_description=excluded.site_description,city_id=excluded.city_id,timezone=excluded.timezone,total_capacity=excluded.total_capacity,usable_capacity=excluded.usable_capacity,reserved_capacity=excluded.reserved_capacity,minimum_age=excluded.minimum_age,curfew_time=excluded.curfew_time,gates_open_time=excluded.gates_open_time,daily_open_time=excluded.daily_open_time,daily_close_time=excluded.daily_close_time,accessibility_notes=excluded.accessibility_notes,transport_notes=excluded.transport_notes,weather_exposure=excluded.weather_exposure,ground_condition=excluded.ground_condition,facility_recommendations=excluded.facility_recommendations,validation_issues=excluded.validation_issues,status=excluded.status,planning_version=public.festival_site_plans.planning_version+1,updated_at=now(),completed_at=excluded.completed_at RETURNING * INTO plan;
 DELETE FROM public.festival_site_plan_stages WHERE festival_site_plan_id=plan.id; INSERT INTO public.festival_site_plan_stages(festival_site_plan_id,festival_company_id,name,slug,stage_type,sort_order,capacity,minimum_artist_fame,performance_area_quality,sound_quality,lighting_quality,production_complexity,indoor,covered,accessible_viewing_capacity,opens_at,closes_at,changeover_minutes,headline_slot_minutes,standard_slot_minutes,status) SELECT plan.id,p_festival_company_id,btrim(s->>'name'),s->>'slug',s->>'stageType',(s->>'sortOrder')::int,(s->>'capacity')::int,(s->>'minimumArtistFame')::int,(s->>'performanceAreaQuality')::int,(s->>'soundQuality')::int,(s->>'lightingQuality')::int,coalesce(s->>'productionComplexity','standard'),(s->>'indoor')::boolean,(s->>'covered')::boolean,(s->>'accessibleViewingCapacity')::int,(s->>'opensAt')::time,(s->>'closesAt')::time,(s->>'changeoverMinutes')::int,(s->>'headlineSlotMinutes')::int,(s->>'standardSlotMinutes')::int,coalesce(s->>'status','planned') FROM jsonb_array_elements(p_stages) s;
 INSERT INTO public.festival_site_plan_audit(festival_company_id,site_plan_id,actor_profile_id,event_type,previous_version,new_version,metadata) VALUES(p_festival_company_id,plan.id,profile,CASE WHEN p_complete THEN 'planning_completed' ELSE 'planning_saved' END,p_expected_version,plan.planning_version,jsonb_build_object('stageCount',stage_count)); result:=public._festival_site_plan_result(p_festival_company_id); UPDATE public.festival_site_plan_requests SET status='succeeded',result=result,completed_at=now() WHERE festival_company_id=p_festival_company_id AND caller_profile_id=profile AND idempotency_key=p_idempotency_key; RETURN result;
EXCEPTION WHEN invalid_text_representation OR check_violation OR not_null_violation OR unique_violation THEN RAISE EXCEPTION 'festival_site_invalid' USING ERRCODE='P0001'; END $$;
REVOKE ALL ON FUNCTION public._festival_site_plan_result(uuid) FROM PUBLIC,anon,authenticated; REVOKE ALL ON FUNCTION public.get_festival_site_plan(uuid),public.save_festival_site_plan(uuid,integer,jsonb,jsonb,uuid,boolean) FROM PUBLIC,anon; GRANT EXECUTE ON FUNCTION public.get_festival_site_plan(uuid),public.save_festival_site_plan(uuid,integer,jsonb,jsonb,uuid,boolean) TO authenticated;
COMMENT ON TABLE public.festival_site_plan_requests IS 'Company/caller-scoped idempotency receipts; retain through the supported retry window and purge operationally after 90 days.';
NOTIFY pgrst,'reload schema';