-- Finance Phase 8B: persistent property foundation and secured residential mortgages.

DO $$ BEGIN CREATE TYPE public.property_owner_type AS ENUM ('player','band','company','world','provider'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.property_category AS ENUM ('residential','commercial'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.property_listing_status AS ENUM ('for_sale','for_rent','reserved','sold','off_market'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.property_status AS ENUM ('available','occupied','reserved','under_maintenance','sold'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.mortgage_status AS ENUM ('application','offered','pending_completion','active','arrears','redeemed','refinanced','cancelled','declined'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.mortgage_schedule_status AS ENUM ('scheduled','due','paid','part_paid','missed','cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.security_interest_status AS ENUM ('registered','pending_release','released','replaced'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.mortgage_rate_model AS ENUM ('fixed','variable'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.mortgage_repayment_strategy AS ENUM ('repayment','interest_only'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.property_districts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), city_id uuid REFERENCES public.cities(id), city_name text NOT NULL, name text NOT NULL,
  country_code text, default_currency_code char(3) NOT NULL DEFAULT 'GBP', prestige_index integer NOT NULL DEFAULT 50,
  created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now()), UNIQUE(city_name,name)
);
CREATE TABLE IF NOT EXISTS public.property_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE, district_id uuid REFERENCES public.property_districts(id),
  category public.property_category NOT NULL, property_type text NOT NULL, quality integer NOT NULL, size_sqm integer NOT NULL,
  rooms integer NOT NULL, bedrooms integer NOT NULL DEFAULT 0, capacity integer NOT NULL, base_condition integer NOT NULL DEFAULT 100,
  prestige integer NOT NULL DEFAULT 0, base_value_minor bigint NOT NULL CHECK(base_value_minor>0), currency_code char(3) NOT NULL,
  default_running_costs jsonb NOT NULL DEFAULT '{}', status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now())
);
CREATE TABLE IF NOT EXISTS public.properties (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), template_id uuid REFERENCES public.property_templates(id), city_id uuid REFERENCES public.cities(id), district_id uuid REFERENCES public.property_districts(id),
  city_name text NOT NULL, district_name text NOT NULL, category public.property_category NOT NULL, property_type text NOT NULL, quality integer NOT NULL,
  size_sqm integer NOT NULL, rooms integer NOT NULL, bedrooms integer NOT NULL DEFAULT 0, capacity integer NOT NULL, condition integer NOT NULL DEFAULT 100,
  prestige integer NOT NULL DEFAULT 0, current_valuation_minor bigint NOT NULL CHECK(current_valuation_minor>=0), currency_code char(3) NOT NULL,
  listing_status public.property_listing_status NOT NULL DEFAULT 'off_market', owner_type public.property_owner_type NOT NULL DEFAULT 'world', owner_id uuid,
  occupant_type public.property_owner_type, occupant_id uuid, persistent_status public.property_status NOT NULL DEFAULT 'available', metadata jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now())
);
CREATE TABLE IF NOT EXISTS public.property_listings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), property_id uuid NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE, listing_type text NOT NULL CHECK(listing_type IN('sale','rent')), price_minor bigint NOT NULL, currency_code char(3) NOT NULL, status public.property_listing_status NOT NULL DEFAULT 'for_sale', listed_at timestamptz NOT NULL DEFAULT timezone('utc',now()), closed_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS public.property_ownership_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), property_id uuid NOT NULL REFERENCES public.properties(id), owner_type public.property_owner_type NOT NULL, owner_id uuid, purchase_transaction_id uuid, purchase_price_minor bigint, currency_code char(3), started_at timestamptz NOT NULL DEFAULT timezone('utc',now()), ended_at timestamptz);
CREATE TABLE IF NOT EXISTS public.property_occupancies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), property_id uuid NOT NULL REFERENCES public.properties(id), occupant_type public.property_owner_type NOT NULL, occupant_id uuid NOT NULL, use_type text NOT NULL, started_at timestamptz NOT NULL DEFAULT timezone('utc',now()), ended_at timestamptz, status text NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS public.property_valuations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), property_id uuid NOT NULL REFERENCES public.properties(id), valuation_minor bigint NOT NULL, currency_code char(3) NOT NULL, valuation_date date NOT NULL DEFAULT CURRENT_DATE, source text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS public.property_permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), property_id uuid NOT NULL REFERENCES public.properties(id), grantee_type public.property_owner_type NOT NULL, grantee_id uuid NOT NULL, permission text NOT NULL, granted_by uuid, created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), revoked_at timestamptz);
CREATE TABLE IF NOT EXISTS public.property_running_costs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), property_id uuid NOT NULL REFERENCES public.properties(id), cost_type text NOT NULL, amount_minor bigint NOT NULL, currency_code char(3) NOT NULL, frequency text NOT NULL DEFAULT 'monthly', status text NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS public.property_reservations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), property_id uuid NOT NULL REFERENCES public.properties(id), applicant_type public.property_owner_type NOT NULL, applicant_id uuid NOT NULL, expires_at timestamptz NOT NULL, status text NOT NULL DEFAULT 'active', idempotency_key text, created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), completed_at timestamptz, cancelled_at timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS property_reservations_one_active ON public.property_reservations(property_id) WHERE status='active';
CREATE TABLE IF NOT EXISTS public.property_purchase_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), property_id uuid NOT NULL REFERENCES public.properties(id), buyer_type public.property_owner_type NOT NULL, buyer_id uuid NOT NULL, seller_type public.property_owner_type NOT NULL, seller_id uuid, purchase_price_minor bigint NOT NULL, deposit_minor bigint NOT NULL DEFAULT 0, mortgage_principal_minor bigint NOT NULL DEFAULT 0, currency_code char(3) NOT NULL, financial_transaction_id uuid REFERENCES public.financial_transactions(id), status text NOT NULL DEFAULT 'pending', idempotency_key text UNIQUE, created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), completed_at timestamptz);
CREATE TABLE IF NOT EXISTS public.property_leases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), property_id uuid NOT NULL REFERENCES public.properties(id), tenant_type public.property_owner_type NOT NULL, tenant_id uuid NOT NULL, monthly_rent_minor bigint NOT NULL, deposit_minor bigint NOT NULL DEFAULT 0, currency_code char(3) NOT NULL, status text NOT NULL DEFAULT 'active', lease_start date NOT NULL, lease_end date);
CREATE TABLE IF NOT EXISTS public.property_deposits (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), property_id uuid NOT NULL REFERENCES public.properties(id), owner_type public.property_owner_type NOT NULL, owner_id uuid NOT NULL, amount_minor bigint NOT NULL, currency_code char(3) NOT NULL, status text NOT NULL DEFAULT 'reserved', source_account_id uuid REFERENCES public.financial_accounts(id), created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), released_at timestamptz);

CREATE TABLE IF NOT EXISTS public.mortgage_products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), provider_id uuid REFERENCES public.banking_providers(id), product_code text NOT NULL UNIQUE, product_name text NOT NULL, status text NOT NULL DEFAULT 'active', eligible_owner_types public.financial_owner_type[] NOT NULL DEFAULT ARRAY['player']::public.financial_owner_type[], eligible_property_categories public.property_category[] NOT NULL DEFAULT ARRAY['residential']::public.property_category[], currency_code char(3) NOT NULL, rate_model public.mortgage_rate_model NOT NULL DEFAULT 'fixed', repayment_strategy public.mortgage_repayment_strategy NOT NULL DEFAULT 'repayment', annual_rate_bps integer NOT NULL, stress_rate_bps integer NOT NULL DEFAULT 700, min_deposit_bps integer NOT NULL, max_ltv_bps integer NOT NULL, min_term_months integer NOT NULL, max_term_months integer NOT NULL, early_repayment_charge_bps integer NOT NULL DEFAULT 0, fees jsonb NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS public.mortgage_applications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), applicant_type public.financial_owner_type NOT NULL DEFAULT 'player', applicant_id uuid NOT NULL, property_id uuid NOT NULL REFERENCES public.properties(id), product_id uuid NOT NULL REFERENCES public.mortgage_products(id), requested_term_months integer NOT NULL, requested_deposit_minor bigint NOT NULL, currency_code char(3) NOT NULL, status public.mortgage_status NOT NULL DEFAULT 'application', idempotency_key text UNIQUE, created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now()));
CREATE TABLE IF NOT EXISTS public.mortgage_affordability_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), application_id uuid NOT NULL REFERENCES public.mortgage_applications(id), source_period_start date NOT NULL, source_period_end date NOT NULL, game_time_period text NOT NULL DEFAULT 'monthly', calculation_version text NOT NULL, verified_income_minor bigint NOT NULL, essential_expenditure_minor bigint NOT NULL, existing_debt_service_minor bigint NOT NULL, unrestricted_cash_minor bigint NOT NULL, credit_score integer NOT NULL, currency_code char(3) NOT NULL, source_references jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT timezone('utc',now()));
CREATE TABLE IF NOT EXISTS public.mortgage_underwriting_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), application_id uuid NOT NULL REFERENCES public.mortgage_applications(id), snapshot_id uuid REFERENCES public.mortgage_affordability_snapshots(id), status text NOT NULL, verified_deposit_minor bigint NOT NULL, required_deposit_minor bigint NOT NULL, principal_minor bigint NOT NULL, ltv_bps integer NOT NULL, stressed_payment_minor bigint NOT NULL, debt_service_ratio_bps integer NOT NULL, disposable_income_minor bigint NOT NULL, maximum_affordable_principal_minor bigint NOT NULL, approval_reasons jsonb NOT NULL DEFAULT '[]', rejection_reasons jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT timezone('utc',now()));
CREATE TABLE IF NOT EXISTS public.mortgage_offers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), application_id uuid NOT NULL REFERENCES public.mortgage_applications(id), product_id uuid NOT NULL REFERENCES public.mortgage_products(id), property_id uuid NOT NULL REFERENCES public.properties(id), provider_id uuid REFERENCES public.banking_providers(id), purchase_price_minor bigint NOT NULL, deposit_minor bigint NOT NULL, principal_minor bigint NOT NULL, currency_code char(3) NOT NULL, annual_rate_bps integer NOT NULL, term_months integer NOT NULL, first_payment_date date NOT NULL, monthly_payment_minor bigint NOT NULL, total_repayment_estimate_minor bigint NOT NULL, fees jsonb NOT NULL DEFAULT '[]', expires_at timestamptz NOT NULL, status text NOT NULL DEFAULT 'issued', created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), accepted_at timestamptz, declined_at timestamptz);
CREATE TABLE IF NOT EXISTS public.mortgage_contracts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), offer_id uuid NOT NULL REFERENCES public.mortgage_offers(id), property_id uuid NOT NULL REFERENCES public.properties(id), provider_id uuid REFERENCES public.banking_providers(id), borrower_type public.financial_owner_type NOT NULL, borrower_id uuid NOT NULL, deposit_bank_account_id uuid REFERENCES public.bank_accounts(id), repayment_bank_account_id uuid REFERENCES public.bank_accounts(id), original_principal_minor bigint NOT NULL, outstanding_principal_minor bigint NOT NULL, currency_code char(3) NOT NULL, annual_rate_bps integer NOT NULL, term_months integer NOT NULL, remaining_term_months integer NOT NULL, next_payment_due_date date, status public.mortgage_status NOT NULL DEFAULT 'pending_completion', created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), activated_at timestamptz, redeemed_at timestamptz, idempotency_key text UNIQUE);
CREATE TABLE IF NOT EXISTS public.mortgage_schedule_lines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), mortgage_contract_id uuid NOT NULL REFERENCES public.mortgage_contracts(id) ON DELETE CASCADE, schedule_version integer NOT NULL DEFAULT 1, instalment_number integer NOT NULL, due_date date NOT NULL, opening_principal_minor bigint NOT NULL, principal_due_minor bigint NOT NULL, interest_due_minor bigint NOT NULL, fees_due_minor bigint NOT NULL DEFAULT 0, total_due_minor bigint NOT NULL, paid_principal_minor bigint NOT NULL DEFAULT 0, paid_interest_minor bigint NOT NULL DEFAULT 0, paid_fees_minor bigint NOT NULL DEFAULT 0, currency_code char(3) NOT NULL, status public.mortgage_schedule_status NOT NULL DEFAULT 'scheduled', payment_transaction_id uuid REFERENCES public.financial_transactions(id), UNIQUE(mortgage_contract_id,schedule_version,instalment_number));
CREATE TABLE IF NOT EXISTS public.mortgage_payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), mortgage_contract_id uuid NOT NULL REFERENCES public.mortgage_contracts(id), schedule_line_id uuid REFERENCES public.mortgage_schedule_lines(id), financial_transaction_id uuid REFERENCES public.financial_transactions(id), amount_minor bigint NOT NULL, principal_minor bigint NOT NULL DEFAULT 0, interest_minor bigint NOT NULL DEFAULT 0, fees_minor bigint NOT NULL DEFAULT 0, currency_code char(3) NOT NULL, status text NOT NULL DEFAULT 'posted', idempotency_key text UNIQUE, created_at timestamptz NOT NULL DEFAULT timezone('utc',now()));
CREATE TABLE IF NOT EXISTS public.mortgage_payment_attempts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), mortgage_contract_id uuid NOT NULL REFERENCES public.mortgage_contracts(id), schedule_line_id uuid REFERENCES public.mortgage_schedule_lines(id), amount_minor bigint NOT NULL, currency_code char(3) NOT NULL, status text NOT NULL, failure_reason text, idempotency_key text UNIQUE, attempted_at timestamptz NOT NULL DEFAULT timezone('utc',now()));
CREATE TABLE IF NOT EXISTS public.property_security_interests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), property_id uuid NOT NULL REFERENCES public.properties(id), mortgage_contract_id uuid NOT NULL REFERENCES public.mortgage_contracts(id), provider_id uuid REFERENCES public.banking_providers(id), original_secured_amount_minor bigint NOT NULL, outstanding_secured_amount_minor bigint NOT NULL, currency_code char(3) NOT NULL, registration_date date NOT NULL DEFAULT CURRENT_DATE, priority integer NOT NULL DEFAULT 1, status public.security_interest_status NOT NULL DEFAULT 'registered', release_date date, release_transaction_id uuid REFERENCES public.financial_transactions(id));
CREATE UNIQUE INDEX IF NOT EXISTS property_security_one_registered ON public.property_security_interests(property_id,priority) WHERE status='registered';
CREATE TABLE IF NOT EXISTS public.mortgage_rate_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), mortgage_contract_id uuid REFERENCES public.mortgage_contracts(id), product_id uuid REFERENCES public.mortgage_products(id), effective_date date NOT NULL, annual_rate_bps integer NOT NULL, reason text NOT NULL, created_at timestamptz NOT NULL DEFAULT timezone('utc',now()));
CREATE TABLE IF NOT EXISTS public.mortgage_overpayments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), mortgage_contract_id uuid NOT NULL REFERENCES public.mortgage_contracts(id), payment_id uuid REFERENCES public.mortgage_payments(id), amount_minor bigint NOT NULL, currency_code char(3) NOT NULL, reduction_preference text NOT NULL CHECK(reduction_preference IN('reduce_term','reduce_payment')), schedule_version_created integer, created_at timestamptz NOT NULL DEFAULT timezone('utc',now())) ;
CREATE TABLE IF NOT EXISTS public.mortgage_settlement_quotes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), mortgage_contract_id uuid NOT NULL REFERENCES public.mortgage_contracts(id), outstanding_principal_minor bigint NOT NULL, accrued_interest_minor bigint NOT NULL, unpaid_fees_minor bigint NOT NULL DEFAULT 0, early_repayment_charge_minor bigint NOT NULL DEFAULT 0, release_fees_minor bigint NOT NULL DEFAULT 0, total_payable_minor bigint NOT NULL, currency_code char(3) NOT NULL, expires_at timestamptz NOT NULL, status text NOT NULL DEFAULT 'issued', created_at timestamptz NOT NULL DEFAULT timezone('utc',now())) ;
CREATE TABLE IF NOT EXISTS public.mortgage_settlements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), mortgage_contract_id uuid NOT NULL REFERENCES public.mortgage_contracts(id), settlement_quote_id uuid NOT NULL REFERENCES public.mortgage_settlement_quotes(id), financial_transaction_id uuid REFERENCES public.financial_transactions(id), total_paid_minor bigint NOT NULL, currency_code char(3) NOT NULL, status text NOT NULL DEFAULT 'completed', created_at timestamptz NOT NULL DEFAULT timezone('utc',now())) ;
CREATE TABLE IF NOT EXISTS public.mortgage_arrears_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), mortgage_contract_id uuid NOT NULL REFERENCES public.mortgage_contracts(id), schedule_line_id uuid REFERENCES public.mortgage_schedule_lines(id), days_overdue integer NOT NULL, unpaid_principal_minor bigint NOT NULL, unpaid_interest_minor bigint NOT NULL, fees_minor bigint NOT NULL DEFAULT 0, missed_payment_count integer NOT NULL, stage text NOT NULL, created_at timestamptz NOT NULL DEFAULT timezone('utc',now())) ;
CREATE TABLE IF NOT EXISTS public.mortgage_refinance_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), old_mortgage_contract_id uuid NOT NULL REFERENCES public.mortgage_contracts(id), new_mortgage_contract_id uuid REFERENCES public.mortgage_contracts(id), settlement_quote_id uuid REFERENCES public.mortgage_settlement_quotes(id), status text NOT NULL DEFAULT 'deferred', created_at timestamptz NOT NULL DEFAULT timezone('utc',now())) ;
CREATE TABLE IF NOT EXISTS public.mortgage_equity_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), mortgage_contract_id uuid NOT NULL REFERENCES public.mortgage_contracts(id), property_id uuid NOT NULL REFERENCES public.properties(id), property_value_minor bigint NOT NULL, outstanding_principal_minor bigint NOT NULL, equity_minor bigint NOT NULL, ltv_bps integer NOT NULL, currency_code char(3) NOT NULL, snapshot_date date NOT NULL DEFAULT CURRENT_DATE);
CREATE TABLE IF NOT EXISTS public.mortgage_audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), mortgage_contract_id uuid REFERENCES public.mortgage_contracts(id), application_id uuid REFERENCES public.mortgage_applications(id), action text NOT NULL, actor_type text NOT NULL DEFAULT 'system', actor_id uuid, idempotency_key text, details jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT timezone('utc',now())) ;

-- Extend provider account roles used by Phase 7 banking to include mortgage-specific roles.
ALTER TABLE public.banking_provider_financial_accounts DROP CONSTRAINT IF EXISTS banking_provider_financial_accounts_account_role_check;
ALTER TABLE public.banking_provider_financial_accounts ADD CONSTRAINT banking_provider_financial_accounts_account_role_check CHECK (account_role IN ('lending_funding','loan_receivable','interest_income','fee_income','loss_write_off','interest_expense','settlement_clearing','provider_equity','mortgage_funding_cash','mortgage_receivable','mortgage_interest_income','mortgage_fee_income','mortgage_settlement_clearing','mortgage_credit_loss_expense'));

CREATE OR REPLACE FUNCTION public.current_player_profile_id() RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT id FROM public.profiles WHERE user_id=auth.uid() LIMIT 1 $$;
CREATE OR REPLACE FUNCTION public.mortgage_monthly_payment(p_principal bigint,p_rate_bps int,p_months int) RETURNS bigint LANGUAGE sql IMMUTABLE AS $$ SELECT CASE WHEN p_months<=0 THEN 0 WHEN p_rate_bps=0 THEN CEIL(p_principal::numeric/p_months)::bigint ELSE CEIL((p_principal::numeric*(p_rate_bps::numeric/10000/12))/(1-POWER(1+(p_rate_bps::numeric/10000/12),-p_months)))::bigint END $$;

CREATE OR REPLACE FUNCTION public.prevent_direct_secured_property_transfer() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP='UPDATE' AND (OLD.owner_type IS DISTINCT FROM NEW.owner_type OR OLD.owner_id IS DISTINCT FROM NEW.owner_id) AND EXISTS (SELECT 1 FROM public.property_security_interests si WHERE si.property_id=OLD.id AND si.status='registered') THEN
    RAISE EXCEPTION 'active_security_interest_blocks_transfer';
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS properties_prevent_direct_secured_transfer ON public.properties;
CREATE TRIGGER properties_prevent_direct_secured_transfer BEFORE UPDATE OF owner_type,owner_id ON public.properties FOR EACH ROW EXECUTE FUNCTION public.prevent_direct_secured_property_transfer();

CREATE OR REPLACE FUNCTION public.list_persistent_properties() RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
  SELECT COALESCE(jsonb_agg(jsonb_build_object('id',p.id,'city',p.city_name,'district',p.district_name,'category',p.category,'type',p.property_type,'priceMinor',p.current_valuation_minor,'currencyCode',p.currency_code,'condition',p.condition,'prestige',p.prestige,'sizeSqm',p.size_sqm,'rooms',p.rooms,'capacity',p.capacity,'listingStatus',p.listing_status,'mortgageEligible',p.category='residential' AND p.listing_status='for_sale') ORDER BY p.city_name,p.district_name,p.current_valuation_minor),'[]'::jsonb) FROM public.properties p WHERE p.listing_status IN ('for_sale','for_rent')
$$;
CREATE OR REPLACE FUNCTION public.list_eligible_mortgage_products(p_property_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
  SELECT COALESCE(jsonb_agg(jsonb_build_object('id',mp.id,'providerId',mp.provider_id,'productName',mp.product_name,'rateModel',mp.rate_model,'repaymentStrategy',mp.repayment_strategy,'annualRateBps',mp.annual_rate_bps,'minDepositBps',mp.min_deposit_bps,'maxLtvBps',mp.max_ltv_bps,'minTermMonths',mp.min_term_months,'maxTermMonths',mp.max_term_months,'currencyCode',mp.currency_code) ORDER BY mp.product_name),'[]'::jsonb)
  FROM public.mortgage_products mp JOIN public.properties p ON p.id=p_property_id WHERE mp.status='active' AND mp.rate_model='fixed' AND mp.repayment_strategy='repayment' AND mp.currency_code=p.currency_code AND p.category=ANY(mp.eligible_property_categories) AND 'player'=ANY(mp.eligible_owner_types)
$$;

CREATE OR REPLACE FUNCTION public.create_mortgage_application(p_property_id uuid,p_product_id uuid,p_term_months int,p_requested_deposit_minor bigint,p_currency_code char(3),p_idempotency_key text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE pid uuid:=public.current_player_profile_id(); prop public.properties; prod public.mortgage_products; app_id uuid; required_deposit bigint; principal bigint; pay bigint; income bigint; cash bigint; debt bigint; score int; snap uuid; result_status text; reasons jsonb:='[]';
BEGIN
  IF pid IS NULL THEN RAISE EXCEPTION 'profile_required'; END IF;
  SELECT * INTO prop FROM public.properties WHERE id=p_property_id FOR UPDATE; SELECT * INTO prod FROM public.mortgage_products WHERE id=p_product_id;
  IF prop.id IS NULL OR prod.id IS NULL THEN RAISE EXCEPTION 'not_found'; END IF;
  IF p_currency_code<>prop.currency_code OR prod.currency_code<>prop.currency_code THEN RAISE EXCEPTION 'currency_mismatch'; END IF;
  IF prop.listing_status<>'for_sale' OR prop.persistent_status<>'available' THEN reasons := reasons || '"property_not_available"'::jsonb; END IF;
  IF p_term_months<prod.min_term_months OR p_term_months>prod.max_term_months THEN reasons := reasons || '"term_out_of_range"'::jsonb; END IF;
  required_deposit:=CEIL(prop.current_valuation_minor::numeric*prod.min_deposit_bps/10000)::bigint; principal:=prop.current_valuation_minor-p_requested_deposit_minor;
  IF p_requested_deposit_minor<required_deposit THEN reasons := reasons || '"insufficient_deposit"'::jsonb; END IF;
  IF principal>FLOOR(prop.current_valuation_minor::numeric*prod.max_ltv_bps/10000)::bigint THEN reasons := reasons || '"ltv_exceeded"'::jsonb; END IF;
  SELECT COALESCE(sum(t.net_amount_minor),0) INTO income FROM public.financial_transactions t JOIN public.financial_accounts fa ON fa.id=t.destination_account_id WHERE fa.owner_type='player' AND fa.owner_id=pid AND t.created_at>=timezone('utc',now())-interval '90 days' AND t.transaction_category IN ('wage_payment','gig_payment','festival_payment','merchandise_revenue','streaming_royalty','song_release_royalty','session_income');
  SELECT COALESCE(sum(available_balance_minor),0) INTO cash FROM public.financial_accounts WHERE owner_type='player' AND owner_id=pid AND account_status='active' AND default_currency_code=p_currency_code;
  SELECT COALESCE(sum(scheduled_payment_minor),0) INTO debt FROM public.loan_contracts WHERE borrower_type='player' AND borrower_id=pid AND status IN ('active','grace_period','delinquent');
  SELECT COALESCE(credit_score,600) INTO score FROM public.banking_customer_profiles WHERE owner_type='player' AND owner_id=pid;
  IF cash<p_requested_deposit_minor THEN reasons := reasons || '"deposit_funds_unverified"'::jsonb; END IF;
  pay:=public.mortgage_monthly_payment(principal,GREATEST(prod.annual_rate_bps,prod.stress_rate_bps),p_term_months);
  IF income>0 AND ((debt+pay)*10000/income)>4500 THEN reasons := reasons || '"affordability_stress_failed"'::jsonb; END IF;
  IF score<500 THEN reasons := reasons || '"credit_history_failed"'::jsonb; END IF;
  result_status:=CASE WHEN jsonb_array_length(reasons)=0 THEN 'approved' ELSE 'declined' END;
  INSERT INTO public.mortgage_applications(applicant_type,applicant_id,property_id,product_id,requested_term_months,requested_deposit_minor,currency_code,status,idempotency_key) VALUES('player',pid,p_property_id,p_product_id,p_term_months,p_requested_deposit_minor,p_currency_code,CASE WHEN result_status='approved' THEN 'offered'::public.mortgage_status ELSE 'declined'::public.mortgage_status END,p_idempotency_key) ON CONFLICT(idempotency_key) DO UPDATE SET updated_at=EXCLUDED.updated_at RETURNING id INTO app_id;
  INSERT INTO public.mortgage_affordability_snapshots(application_id,source_period_start,source_period_end,calculation_version,verified_income_minor,essential_expenditure_minor,existing_debt_service_minor,unrestricted_cash_minor,credit_score,currency_code,source_references) VALUES(app_id,(CURRENT_DATE-90),CURRENT_DATE,'phase8b-player-v1',income,0,debt,cash,score,p_currency_code,jsonb_build_object('income_window_days',90,'excluded_categories',jsonb_build_array('loan','transfer','refund','admin_adjustment'))) RETURNING id INTO snap;
  INSERT INTO public.mortgage_underwriting_results(application_id,snapshot_id,status,verified_deposit_minor,required_deposit_minor,principal_minor,ltv_bps,stressed_payment_minor,debt_service_ratio_bps,disposable_income_minor,maximum_affordable_principal_minor,rejection_reasons) VALUES(app_id,snap,result_status,LEAST(cash,p_requested_deposit_minor),required_deposit,principal,FLOOR(principal::numeric*10000/NULLIF(prop.current_valuation_minor,0))::int,pay,CASE WHEN income>0 THEN FLOOR((debt+pay)::numeric*10000/income)::int ELSE 10000 END,income-debt-pay,FLOOR(prop.current_valuation_minor::numeric*prod.max_ltv_bps/10000)::bigint,reasons);
  IF result_status='approved' THEN INSERT INTO public.mortgage_offers(application_id,product_id,property_id,provider_id,purchase_price_minor,deposit_minor,principal_minor,currency_code,annual_rate_bps,term_months,first_payment_date,monthly_payment_minor,total_repayment_estimate_minor,fees,expires_at) VALUES(app_id,p_product_id,p_property_id,prod.provider_id,prop.current_valuation_minor,p_requested_deposit_minor,principal,p_currency_code,prod.annual_rate_bps,p_term_months,CURRENT_DATE+interval '1 month',public.mortgage_monthly_payment(principal,prod.annual_rate_bps,p_term_months),public.mortgage_monthly_payment(principal,prod.annual_rate_bps,p_term_months)*p_term_months,prod.fees,timezone('utc',now())+interval '14 days'); END IF;
  RETURN app_id;
END $$;
CREATE OR REPLACE FUNCTION public.get_mortgage_application(p_application_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT to_jsonb(a) FROM public.mortgage_applications a WHERE a.id=p_application_id AND a.applicant_type='player' AND a.applicant_id=public.current_player_profile_id() $$;
CREATE OR REPLACE FUNCTION public.evaluate_mortgage_application(p_application_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT to_jsonb(r) FROM public.mortgage_underwriting_results r JOIN public.mortgage_applications a ON a.id=r.application_id WHERE r.application_id=p_application_id AND a.applicant_type='player' AND a.applicant_id=public.current_player_profile_id() ORDER BY r.created_at DESC LIMIT 1 $$;
CREATE OR REPLACE FUNCTION public.get_mortgage_offer(p_application_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT to_jsonb(o) FROM public.mortgage_offers o JOIN public.mortgage_applications a ON a.id=o.application_id WHERE o.application_id=p_application_id AND a.applicant_type='player' AND a.applicant_id=public.current_player_profile_id() AND o.status='issued' $$;
CREATE OR REPLACE FUNCTION public.decline_mortgage_offer(p_offer_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN UPDATE public.mortgage_offers o SET status='declined',declined_at=timezone('utc',now()) FROM public.mortgage_applications a WHERE a.id=o.application_id AND o.id=p_offer_id AND a.applicant_type='player' AND a.applicant_id=public.current_player_profile_id(); END $$;

-- Completion and servicing entry points are intentionally fail-closed until the ledger-posting procedure is wired end-to-end.
CREATE OR REPLACE FUNCTION public.complete_mortgaged_property_purchase(p_offer_id uuid,p_deposit_bank_account_id uuid,p_repayment_bank_account_id uuid,p_idempotency_key text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN RAISE EXCEPTION 'mortgage_completion_not_enabled_until_ledger_vertical_slice_is_configured'; END $$;
CREATE OR REPLACE FUNCTION public.retry_mortgage_payment(p_schedule_line_id uuid,p_idempotency_key text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN RAISE EXCEPTION 'mortgage_payment_processing_not_enabled_until_ledger_vertical_slice_is_configured'; END $$;
CREATE OR REPLACE FUNCTION public.make_mortgage_overpayment(p_mortgage_contract_id uuid,p_amount_minor bigint,p_reduction_preference text,p_idempotency_key text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN RAISE EXCEPTION 'mortgage_overpayments_not_enabled_until_ledger_vertical_slice_is_configured'; END $$;
CREATE OR REPLACE FUNCTION public.settle_mortgage(p_settlement_quote_id uuid,p_idempotency_key text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN RAISE EXCEPTION 'mortgage_settlement_not_enabled_until_ledger_vertical_slice_is_configured'; END $$;

CREATE OR REPLACE VIEW public.mortgage_reconciliation_exceptions AS
SELECT 'contract_without_security' issue, c.id::text entity_id FROM public.mortgage_contracts c WHERE c.status='active' AND NOT EXISTS(SELECT 1 FROM public.property_security_interests s WHERE s.mortgage_contract_id=c.id AND s.status='registered')
UNION ALL SELECT 'security_balance_mismatch', s.id::text FROM public.property_security_interests s JOIN public.mortgage_contracts c ON c.id=s.mortgage_contract_id WHERE s.status='registered' AND s.outstanding_secured_amount_minor<>c.outstanding_principal_minor;
CREATE OR REPLACE VIEW public.property_purchase_reconciliation_exceptions AS
SELECT 'sold_listing_not_closed' issue, p.id::text entity_id FROM public.properties p WHERE p.owner_type<>'world' AND p.listing_status IN ('for_sale','reserved')
UNION ALL SELECT 'active_reservation_on_sold_property', r.id::text FROM public.property_reservations r JOIN public.properties p ON p.id=r.property_id WHERE r.status='active' AND p.owner_type<>'world';

ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY; ALTER TABLE public.property_listings ENABLE ROW LEVEL SECURITY; ALTER TABLE public.property_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mortgage_products ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_applications ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_affordability_snapshots ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_underwriting_results ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_offers ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_contracts ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_schedule_lines ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_payments ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_payment_attempts ENABLE ROW LEVEL SECURITY; ALTER TABLE public.property_security_interests ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_rate_history ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_overpayments ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_settlement_quotes ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_settlements ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_arrears_records ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_refinance_records ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_equity_snapshots ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mortgage_audit_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY properties_marketplace_select ON public.properties FOR SELECT USING (listing_status IN ('for_sale','for_rent') OR (owner_type='player' AND owner_id=public.current_player_profile_id()));
CREATE POLICY mortgage_products_select_active ON public.mortgage_products FOR SELECT USING (status='active');
CREATE POLICY mortgage_applications_own_select ON public.mortgage_applications FOR SELECT USING (applicant_type='player' AND applicant_id=public.current_player_profile_id());
CREATE POLICY mortgage_offers_own_select ON public.mortgage_offers FOR SELECT USING (EXISTS(SELECT 1 FROM public.mortgage_applications a WHERE a.id=application_id AND a.applicant_type='player' AND a.applicant_id=public.current_player_profile_id()));
CREATE POLICY mortgage_contracts_own_select ON public.mortgage_contracts FOR SELECT USING (borrower_type='player' AND borrower_id=public.current_player_profile_id());
CREATE POLICY mortgage_schedule_own_select ON public.mortgage_schedule_lines FOR SELECT USING (EXISTS(SELECT 1 FROM public.mortgage_contracts c WHERE c.id=mortgage_contract_id AND c.borrower_type='player' AND c.borrower_id=public.current_player_profile_id()));
CREATE POLICY mortgage_payments_own_select ON public.mortgage_payments FOR SELECT USING (EXISTS(SELECT 1 FROM public.mortgage_contracts c WHERE c.id=mortgage_contract_id AND c.borrower_type='player' AND c.borrower_id=public.current_player_profile_id()));
CREATE POLICY mortgage_attempts_own_select ON public.mortgage_payment_attempts FOR SELECT USING (EXISTS(SELECT 1 FROM public.mortgage_contracts c WHERE c.id=mortgage_contract_id AND c.borrower_type='player' AND c.borrower_id=public.current_player_profile_id()));
CREATE POLICY security_own_select ON public.property_security_interests FOR SELECT USING (EXISTS(SELECT 1 FROM public.mortgage_contracts c WHERE c.id=mortgage_contract_id AND c.borrower_type='player' AND c.borrower_id=public.current_player_profile_id()));

GRANT SELECT ON public.property_districts,public.property_templates,public.properties,public.property_listings,public.mortgage_products TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_persistent_properties(), public.list_eligible_mortgage_products(uuid), public.create_mortgage_application(uuid,uuid,int,bigint,char,text), public.get_mortgage_application(uuid), public.evaluate_mortgage_application(uuid), public.get_mortgage_offer(uuid), public.decline_mortgage_offer(uuid), public.complete_mortgaged_property_purchase(uuid,uuid,uuid,text), public.retry_mortgage_payment(uuid,text), public.make_mortgage_overpayment(uuid,bigint,text,text), public.settle_mortgage(uuid,text) TO authenticated;

INSERT INTO public.property_districts(city_name,name,country_code,default_currency_code,prestige_index) VALUES ('London','Camden','GB','GBP',70) ON CONFLICT(city_name,name) DO NOTHING;
INSERT INTO public.property_templates(code,district_id,category,property_type,quality,size_sqm,rooms,bedrooms,capacity,prestige,base_value_minor,currency_code,default_running_costs)
SELECT 'phase8b-camden-studio',d.id,'residential','Studio',3,38,2,1,2,4,24000000,'GBP','{"maintenance":12000,"utilities":9000,"localTaxes":7000,"cleaning":4000}'::jsonb FROM public.property_districts d WHERE d.city_name='London' AND d.name='Camden' ON CONFLICT(code) DO NOTHING;
INSERT INTO public.properties(template_id,city_name,district_name,category,property_type,quality,size_sqm,rooms,bedrooms,capacity,condition,prestige,current_valuation_minor,currency_code,listing_status,owner_type,persistent_status,metadata)
SELECT t.id,'London','Camden',t.category,t.property_type,t.quality,t.size_sqm,t.rooms,t.bedrooms,t.capacity,100,t.prestige,t.base_value_minor,t.currency_code,'for_sale','world','available',jsonb_build_object('seed','finance_phase8b') FROM public.property_templates t WHERE t.code='phase8b-camden-studio' AND NOT EXISTS(SELECT 1 FROM public.properties p WHERE p.template_id=t.id);
INSERT INTO public.property_listings(property_id,listing_type,price_minor,currency_code,status)
SELECT p.id,'sale',p.current_valuation_minor,p.currency_code,'for_sale' FROM public.properties p WHERE p.metadata->>'seed'='finance_phase8b' AND NOT EXISTS(SELECT 1 FROM public.property_listings l WHERE l.property_id=p.id AND l.status='for_sale');
INSERT INTO public.mortgage_products(product_code,product_name,currency_code,rate_model,repayment_strategy,annual_rate_bps,stress_rate_bps,min_deposit_bps,max_ltv_bps,min_term_months,max_term_months,early_repayment_charge_bps,fees)
VALUES('phase8b-player-fixed-gbp','Player residential fixed repayment','GBP','fixed','repayment',475,700,1500,8500,120,360,100,'[{"name":"Arrangement","amountMinor":49900}]'::jsonb) ON CONFLICT(product_code) DO NOTHING;
