-- Finance Phase 7.4: corrected provider journals and working player loan lifecycle.

ALTER TABLE public.loan_payments ADD COLUMN IF NOT EXISTS journal_event_id uuid REFERENCES public.financial_transactions(id);
ALTER TABLE public.loan_schedule_lines ADD COLUMN IF NOT EXISTS repayment_event_id uuid REFERENCES public.financial_transactions(id);

ALTER TABLE public.banking_provider_financial_accounts DROP CONSTRAINT IF EXISTS banking_provider_financial_accounts_account_role_check;
ALTER TABLE public.banking_provider_financial_accounts ADD CONSTRAINT banking_provider_financial_accounts_account_role_check CHECK (account_role IN ('lending_funding','loan_receivable','interest_income','fee_income','loss_write_off','interest_expense','settlement_clearing','provider_equity'));

CREATE OR REPLACE FUNCTION public.post_financial_journal(
  p_event_type public.financial_transaction_category,
  p_event_id uuid,
  p_currency_code char(3),
  p_idempotency_key text,
  p_entries jsonb,
  p_related_entity_type text DEFAULT NULL,
  p_related_entity_id uuid DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE tx uuid; debit_total bigint; credit_total bigint; gross bigint; r record; acct public.financial_accounts; before_bal bigint;
BEGIN
  IF auth.role() IN ('anon','authenticated') THEN RAISE EXCEPTION 'service role required' USING ERRCODE='42501'; END IF;
  IF p_idempotency_key IS NULL OR length(p_idempotency_key)=0 THEN RAISE EXCEPTION 'idempotency key required'; END IF;
  SELECT id INTO tx FROM public.financial_transactions WHERE idempotency_key=p_idempotency_key;
  IF tx IS NOT NULL THEN RETURN tx; END IF;
  IF jsonb_typeof(p_entries) <> 'array' OR jsonb_array_length(p_entries) < 2 THEN RAISE EXCEPTION 'journal requires at least two entries'; END IF;
  SELECT COALESCE(sum(CASE WHEN value->>'direction'='debit' THEN (value->>'amount_minor')::bigint ELSE 0 END),0), COALESCE(sum(CASE WHEN value->>'direction'='credit' THEN (value->>'amount_minor')::bigint ELSE 0 END),0) INTO debit_total, credit_total FROM jsonb_array_elements(p_entries);
  IF debit_total <= 0 OR debit_total <> credit_total THEN RAISE EXCEPTION 'journal debits and credits must balance'; END IF;
  gross := debit_total;
  PERFORM 1 FROM public.financial_accounts fa JOIN (SELECT DISTINCT (value->>'account_id')::uuid id FROM jsonb_array_elements(p_entries)) e ON e.id=fa.id ORDER BY fa.id FOR UPDATE;
  FOR r IN SELECT value->>'account_id' account_id, value->>'direction' direction, (value->>'amount_minor')::bigint amount_minor, value->>'component' component, value->>'description' description FROM jsonb_array_elements(p_entries) LOOP
    IF r.amount_minor <= 0 THEN RAISE EXCEPTION 'journal amounts must be positive'; END IF;
    IF r.direction NOT IN ('debit','credit') THEN RAISE EXCEPTION 'journal direction must be debit or credit'; END IF;
    SELECT * INTO acct FROM public.financial_accounts WHERE id=r.account_id::uuid;
    IF acct.id IS NULL THEN RAISE EXCEPTION 'journal account not found'; END IF;
    IF acct.account_status <> 'active' THEN RAISE EXCEPTION 'journal account is not active'; END IF;
    IF acct.currency_code <> p_currency_code THEN RAISE EXCEPTION 'journal account currency mismatch'; END IF;
    IF acct.owner_type <> 'system' AND r.direction='debit' AND acct.available_balance_minor < r.amount_minor THEN RAISE EXCEPTION 'insufficient funds'; END IF;
  END LOOP;
  INSERT INTO public.financial_transactions(transaction_category,status,currency_code,gross_amount_minor,net_amount_minor,source_account_id,destination_account_id,related_entity_type,related_entity_id,description,idempotency_key,created_by_user_id,created_by_actor,completed_at,source_currency_code,destination_currency_code,source_amount_minor,destination_amount_minor,metadata)
  VALUES(p_event_type,'completed',p_currency_code,gross,gross,(SELECT (value->>'account_id')::uuid FROM jsonb_array_elements(p_entries) WHERE value->>'direction'='debit' LIMIT 1),(SELECT (value->>'account_id')::uuid FROM jsonb_array_elements(p_entries) WHERE value->>'direction'='credit' LIMIT 1),p_related_entity_type,p_related_entity_id,p_event_type::text,p_idempotency_key,auth.uid(),COALESCE(auth.uid()::text,'system'),timezone('utc',now()),p_currency_code,p_currency_code,gross,gross,p_metadata||jsonb_build_object('journal_event_id',p_event_id,'journal_entries',p_entries)) RETURNING id INTO tx;
  FOR r IN SELECT value->>'account_id' account_id, value->>'direction' direction, (value->>'amount_minor')::bigint amount_minor, value->>'component' component, value->>'description' description FROM jsonb_array_elements(p_entries) LOOP
    SELECT current_balance_minor INTO before_bal FROM public.financial_accounts WHERE id=r.account_id::uuid FOR UPDATE;
    UPDATE public.financial_accounts SET current_balance_minor = CASE WHEN r.direction='debit' THEN current_balance_minor-r.amount_minor ELSE current_balance_minor+r.amount_minor END, updated_at=timezone('utc',now()) WHERE id=r.account_id::uuid;
    INSERT INTO public.financial_ledger_entries(transaction_id,account_id,entry_direction,amount_minor,balance_before_minor,balance_after_minor,currency_code) VALUES(tx,r.account_id::uuid,r.direction::public.financial_entry_direction,r.amount_minor,before_bal,CASE WHEN r.direction='debit' THEN before_bal-r.amount_minor ELSE before_bal+r.amount_minor END,p_currency_code);
  END LOOP;
  RETURN tx;
END $$;
REVOKE EXECUTE ON FUNCTION public.post_financial_journal(public.financial_transaction_category,uuid,char(3),text,jsonb,text,uuid,jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.post_financial_journal(public.financial_transaction_category,uuid,char(3),text,jsonb,text,uuid,jsonb) TO service_role;

CREATE OR REPLACE FUNCTION public.post_provider_loan_origination(p_contract_id uuid,p_event_id uuid,p_idempotency_key text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.loan_contracts; fund uuid; recv uuid; fee_income uuid; equity uuid; disb public.bank_accounts; repay public.bank_accounts; tx uuid; fee bigint; entries jsonb;
BEGIN
  SELECT * INTO c FROM public.loan_contracts WHERE id=p_contract_id FOR UPDATE;
  IF c.id IS NULL THEN RAISE EXCEPTION 'loan contract not found'; END IF;
  IF c.origination_event_id IS NOT NULL THEN RETURN jsonb_build_object('origination_event_id',c.origination_event_id,'transaction_id',c.disbursement_transaction_id,'idempotent',true); END IF;
  SELECT * INTO disb FROM public.bank_accounts WHERE id=c.disbursement_bank_account_id FOR UPDATE; SELECT * INTO repay FROM public.bank_accounts WHERE id=c.repayment_bank_account_id FOR UPDATE;
  fund := public.get_or_create_provider_finance_account(c.provider_id,c.currency_code,'lending_funding'); recv := public.get_or_create_provider_finance_account(c.provider_id,c.currency_code,'loan_receivable'); fee_income := public.get_or_create_provider_finance_account(c.provider_id,c.currency_code,'fee_income'); equity := public.get_or_create_provider_finance_account(c.provider_id,c.currency_code,'provider_equity');
  fee := COALESCE((SELECT origination_fee_minor FROM public.loan_offers WHERE id=c.offer_id),0);
  entries := jsonb_build_array(jsonb_build_object('account_id',fund,'direction','debit','amount_minor',c.principal_minor,'component','principal_funding','description','Provider funding paid once'),jsonb_build_object('account_id',disb.linked_finance_account_id,'direction','credit','amount_minor',c.principal_minor,'component','borrower_cash','description','Borrower receives principal'),jsonb_build_object('account_id',equity,'direction','debit','amount_minor',c.principal_minor,'component','receivable_offset','description','Provider capital recognises lending asset'),jsonb_build_object('account_id',recv,'direction','credit','amount_minor',c.principal_minor,'component','loan_receivable','description','Provider loan receivable'));
  IF fee > 0 THEN entries := entries || jsonb_build_array(jsonb_build_object('account_id',repay.linked_finance_account_id,'direction','debit','amount_minor',fee,'component','origination_fee_cash','description','Borrower pays origination fee'),jsonb_build_object('account_id',fee_income,'direction','credit','amount_minor',fee,'component','origination_fee_income','description','Provider fee income')); END IF;
  tx := public.post_financial_journal('loan_disbursement',p_event_id,c.currency_code,'loan-origination-'||p_idempotency_key,entries,'loan_contract',c.id,jsonb_build_object('taxable',false,'liability',true,'origination_fee_minor',fee));
  UPDATE public.loan_contracts SET disbursement_transaction_id=tx, origination_fee_transaction_id=CASE WHEN fee>0 THEN tx ELSE NULL END, net_proceeds_minor=principal_minor, origination_event_id=p_event_id, metadata=metadata||jsonb_build_object('phase7_4_origination_journal_id',tx) WHERE id=c.id;
  RETURN jsonb_build_object('origination_event_id',p_event_id,'transaction_id',tx,'origination_fee_minor',fee);
END $$;

CREATE OR REPLACE FUNCTION public.post_provider_loan_repayment(p_contract_id uuid,p_schedule_line_id uuid,p_principal_minor bigint,p_interest_minor bigint,p_fee_minor bigint,p_payment_type text,p_idempotency_key text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.loan_contracts; repay public.bank_accounts; fund uuid; recv uuid; int_inc uuid; fee_inc uuid; equity uuid; settle uuid; tx uuid; total_due bigint; entries jsonb;
BEGIN
  SELECT * INTO c FROM public.loan_contracts WHERE id=p_contract_id FOR UPDATE; IF c.id IS NULL THEN RAISE EXCEPTION 'loan contract not found'; END IF;
  SELECT journal_event_id INTO tx FROM public.loan_payments WHERE idempotency_key=p_idempotency_key; IF tx IS NOT NULL THEN RETURN jsonb_build_object('repayment_event_id',tx,'idempotent',true); END IF;
  total_due := GREATEST(0,p_principal_minor)+GREATEST(0,p_interest_minor)+GREATEST(0,p_fee_minor); IF total_due<=0 THEN RAISE EXCEPTION 'repayment amount must be positive'; END IF;
  SELECT * INTO repay FROM public.bank_accounts WHERE id=c.repayment_bank_account_id FOR UPDATE;
  fund := public.get_or_create_provider_finance_account(c.provider_id,c.currency_code,'lending_funding'); recv := public.get_or_create_provider_finance_account(c.provider_id,c.currency_code,'loan_receivable'); int_inc := public.get_or_create_provider_finance_account(c.provider_id,c.currency_code,'interest_income'); fee_inc := public.get_or_create_provider_finance_account(c.provider_id,c.currency_code,'fee_income'); equity := public.get_or_create_provider_finance_account(c.provider_id,c.currency_code,'provider_equity'); settle := public.get_or_create_provider_finance_account(c.provider_id,c.currency_code,'settlement_clearing');
  entries := jsonb_build_array(jsonb_build_object('account_id',repay.linked_finance_account_id,'direction','debit','amount_minor',total_due,'component','borrower_cash','description','Borrower repayment cash'),jsonb_build_object('account_id',fund,'direction','credit','amount_minor',total_due,'component','provider_cash','description','Provider cash receipt'));
  IF p_principal_minor>0 THEN entries := entries || jsonb_build_array(jsonb_build_object('account_id',recv,'direction','debit','amount_minor',p_principal_minor,'component','principal_receivable_reduction','description','Reduce loan receivable'),jsonb_build_object('account_id',equity,'direction','credit','amount_minor',p_principal_minor,'component','receivable_offset_release','description','Release receivable offset')); END IF;
  IF p_interest_minor>0 THEN entries := entries || jsonb_build_array(jsonb_build_object('account_id',settle,'direction','debit','amount_minor',p_interest_minor,'component','interest_income_clearing','description','Classify interest income'),jsonb_build_object('account_id',int_inc,'direction','credit','amount_minor',p_interest_minor,'component','interest_income','description','Provider interest income')); END IF;
  IF p_fee_minor>0 THEN entries := entries || jsonb_build_array(jsonb_build_object('account_id',settle,'direction','debit','amount_minor',p_fee_minor,'component','fee_income_clearing','description','Classify fee income'),jsonb_build_object('account_id',fee_inc,'direction','credit','amount_minor',p_fee_minor,'component','fee_income','description','Provider fee income')); END IF;
  tx := public.post_financial_journal('loan_principal_repayment',gen_random_uuid(),c.currency_code,p_idempotency_key,entries,'loan_contract',c.id,jsonb_build_object('schedule_line_id',p_schedule_line_id,'payment_type',p_payment_type));
  INSERT INTO public.loan_payments(loan_contract_id,schedule_line_id,amount_minor,principal_minor,interest_minor,fee_minor,currency_code,payment_type,transaction_id,principal_transaction_id,interest_transaction_id,fee_transaction_id,journal_event_id,idempotency_key,metadata) VALUES(c.id,p_schedule_line_id,total_due,GREATEST(0,p_principal_minor),GREATEST(0,p_interest_minor),GREATEST(0,p_fee_minor),c.currency_code,p_payment_type,tx,tx,CASE WHEN p_interest_minor>0 THEN tx END,CASE WHEN p_fee_minor>0 THEN tx END,tx,p_idempotency_key,jsonb_build_object('phase','7.4')) ON CONFLICT DO NOTHING;
  RETURN jsonb_build_object('repayment_event_id',tx);
END $$;

CREATE OR REPLACE FUNCTION public.accept_loan_offer(p_offer_id uuid,p_disbursement_bank_account_id uuid,p_repayment_bank_account_id uuid,p_idempotency_key text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE offer public.loan_offers; app public.loan_applications; prod public.loan_products; disb public.bank_accounts; repay public.bank_accounts; contract_id uuid; sched record; obligation uuid; event_id uuid := gen_random_uuid(); next_amt bigint;
BEGIN
  SELECT id INTO contract_id FROM public.loan_contracts WHERE metadata->>'acceptance_idempotency_key'=p_idempotency_key; IF contract_id IS NOT NULL THEN RETURN contract_id; END IF;
  SELECT * INTO offer FROM public.loan_offers WHERE id=p_offer_id FOR UPDATE; IF offer.id IS NULL OR offer.status<>'issued' OR offer.offer_expires_at<=timezone('utc',now()) THEN RAISE EXCEPTION 'loan offer is not acceptable'; END IF;
  SELECT * INTO app FROM public.loan_applications WHERE id=offer.application_id FOR UPDATE; SELECT * INTO prod FROM public.loan_products WHERE id=app.product_id;
  PERFORM public.banking_assert_owner_access(app.applicant_type,app.applicant_id,'accept_loan',offer.principal_minor);
  SELECT * INTO disb FROM public.bank_accounts WHERE id=p_disbursement_bank_account_id FOR UPDATE; SELECT * INTO repay FROM public.bank_accounts WHERE id=p_repayment_bank_account_id FOR UPDATE;
  IF disb.owner_type<>app.applicant_type OR disb.owner_id<>app.applicant_id OR repay.owner_type<>app.applicant_type OR repay.owner_id<>app.applicant_id THEN RAISE EXCEPTION 'bank account does not belong to borrower'; END IF;
  IF disb.currency_code<>offer.currency_code OR repay.currency_code<>offer.currency_code THEN RAISE EXCEPTION 'loan accounts must match loan currency unless explicit conversion is quoted'; END IF;
  IF disb.status NOT IN ('active','restricted') OR repay.status<>'active' THEN RAISE EXCEPTION 'bank account is not eligible'; END IF;
  IF offer.origination_fee_minor>0 AND (SELECT available_balance_minor FROM public.financial_accounts WHERE id=repay.linked_finance_account_id) < offer.origination_fee_minor THEN RAISE EXCEPTION 'insufficient funds for origination fee'; END IF;
  INSERT INTO public.loan_contracts(borrower_type,borrower_id,provider_id,product_id,offer_id,repayment_bank_account_id,disbursement_bank_account_id,principal_minor,currency_code,outstanding_principal_minor,interest_rate_basis_points,rate_type,term_months,maturity_date,payment_frequency,scheduled_payment_minor,next_payment_date,total_payments,purpose,linked_entity_type,linked_entity_id,credit_score_at_origination,affordability_snapshot,status,metadata)
  VALUES(app.applicant_type,app.applicant_id,app.provider_id,app.product_id,offer.id,repay.id,disb.id,offer.principal_minor,offer.currency_code,offer.principal_minor,offer.interest_rate_basis_points,offer.rate_type,offer.term_months,offer.first_payment_date+((offer.term_months-1)||' months')::interval,offer.payment_frequency,offer.scheduled_payment_minor,offer.first_payment_date,offer.term_months,app.purpose,app.related_entity_type,app.related_entity_id,app.credit_score_snapshot,app.affordability_result,'pending_activation',jsonb_build_object('acceptance_idempotency_key',p_idempotency_key,'principal_is_income',false)) RETURNING id INTO contract_id;
  FOR sched IN SELECT * FROM public.calculate_equal_instalment_schedule(offer.principal_minor,offer.interest_rate_basis_points,offer.term_months,offer.first_payment_date) LOOP INSERT INTO public.loan_schedule_lines(loan_contract_id,instalment_number,due_date,opening_principal_minor,scheduled_principal_minor,scheduled_interest_minor,total_due_minor) VALUES(contract_id,sched.instalment_number,sched.due_date,sched.opening_principal_minor,sched.scheduled_principal_minor,sched.scheduled_interest_minor,sched.total_due_minor); END LOOP;
  SELECT total_due_minor INTO next_amt FROM public.loan_schedule_lines WHERE loan_contract_id=contract_id AND status<>'paid' ORDER BY due_date,instalment_number LIMIT 1;
  INSERT INTO public.recurring_financial_obligations(owner_type,owner_id,owner_account_id,expense_category,description,amount_minor,currency_code,frequency,next_due_date,related_entity_type,related_entity_id,auto_pay_enabled,grace_period_days,priority,metadata) VALUES(app.applicant_type,app.applicant_id,repay.linked_finance_account_id,'loan_principal_repayment','Scheduled loan repayment',COALESCE(next_amt,offer.scheduled_payment_minor),offer.currency_code,offer.payment_frequency,offer.first_payment_date,'loan_contract',contract_id,true,offer.grace_period_days,10,jsonb_build_object('allocation_order',ARRAY['late_fee','accrued_interest','scheduled_interest','principal'])) RETURNING id INTO obligation;
  UPDATE public.loan_contracts SET recurring_obligation_id=obligation WHERE id=contract_id;
  PERFORM public.post_provider_loan_origination(contract_id,event_id,p_idempotency_key);
  UPDATE public.loan_contracts SET status='active' WHERE id=contract_id;
  UPDATE public.loan_offers SET status='accepted',accepted_at=timezone('utc',now()) WHERE id=offer.id; UPDATE public.loan_applications SET status='offer_accepted' WHERE id=app.id;
  UPDATE public.banking_customer_profiles SET total_borrowing_minor=total_borrowing_minor+offer.principal_minor,available_credit_minor=GREATEST(0,available_credit_minor-offer.principal_minor),updated_at=timezone('utc',now()) WHERE owner_type=app.applicant_type AND owner_id=app.applicant_id;
  INSERT INTO public.banking_audit_events(action,entity_type,entity_id,provider_id,reason,new_value) VALUES('loan_acceptance','loan_contract',contract_id,app.provider_id,'Phase 7.4 journal-backed acceptance',jsonb_build_object('origination_event_id',event_id));
  RETURN contract_id;
END $$;

CREATE OR REPLACE FUNCTION public.process_due_loan_repayments(p_as_of date DEFAULT CURRENT_DATE) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE line record; loan public.loan_contracts; paid int:=0; fee_due bigint; principal_due bigint; interest_due bigint; total_due bigint; result jsonb; event_tx uuid; next_line record;
BEGIN
  IF auth.role() <> 'service_role' THEN RAISE EXCEPTION 'service role required' USING ERRCODE='42501'; END IF;
  FOR line IN SELECT l.* FROM public.loan_schedule_lines l JOIN public.loan_contracts c ON c.id=l.loan_contract_id WHERE c.status IN ('active','grace_period','delinquent') AND l.due_date<=p_as_of AND l.status IN ('scheduled','due','grace_period','late','seriously_late','final_warning','partial') ORDER BY l.due_date FOR UPDATE SKIP LOCKED LOOP
    SELECT * INTO loan FROM public.loan_contracts WHERE id=line.loan_contract_id FOR UPDATE; principal_due:=GREATEST(0,line.scheduled_principal_minor-line.principal_paid_minor); interest_due:=GREATEST(0,line.scheduled_interest_minor-line.interest_paid_minor); fee_due:=GREATEST(0,line.scheduled_fee_minor-line.fee_paid_minor); total_due:=principal_due+interest_due+fee_due; IF total_due<=0 THEN CONTINUE; END IF;
    BEGIN
      result := public.post_provider_loan_repayment(loan.id,line.id,principal_due,interest_due,fee_due,'scheduled','loan-payment-'||line.id||'-'||p_as_of); event_tx := (result->>'repayment_event_id')::uuid;
      UPDATE public.loan_schedule_lines SET amount_paid_minor=total_due,principal_paid_minor=scheduled_principal_minor,interest_paid_minor=scheduled_interest_minor,fee_paid_minor=scheduled_fee_minor,status='paid',payment_transaction_id=event_tx,repayment_event_id=event_tx WHERE id=line.id;
      SELECT * INTO next_line FROM public.loan_schedule_lines WHERE loan_contract_id=loan.id AND status<>'paid' ORDER BY due_date,instalment_number LIMIT 1;
      UPDATE public.loan_contracts SET outstanding_principal_minor=GREATEST(0,outstanding_principal_minor-principal_due),amount_repaid_minor=amount_repaid_minor+total_due,interest_paid_minor=interest_paid_minor+interest_due,fees_paid_minor=fees_paid_minor+fee_due,payments_made=payments_made+1,next_payment_date=next_line.due_date,scheduled_payment_minor=COALESCE(next_line.total_due_minor,scheduled_payment_minor) WHERE id=loan.id;
      UPDATE public.recurring_financial_obligations SET amount_minor=COALESCE(next_line.total_due_minor,amount_minor),next_due_date=next_line.due_date,status='active',failure_count=0,last_attempted_at=timezone('utc',now()) WHERE related_entity_type='loan_contract' AND related_entity_id=loan.id;
      PERFORM public.record_credit_score_event(loan.borrower_type,loan.borrower_id,8,'loan_repayment_on_time','A scheduled loan repayment was completed on time','loan_contract',loan.id); paid:=paid+1;
    EXCEPTION WHEN others THEN UPDATE public.recurring_financial_obligations SET failure_count=failure_count+1,last_attempted_at=timezone('utc',now()),status='failed',metadata=metadata||jsonb_build_object('last_system_failure',SQLERRM) WHERE related_entity_type='loan_contract' AND related_entity_id=loan.id; END;
  END LOOP;
  UPDATE public.loan_contracts SET status='paid_off',outstanding_principal_minor=0,completed_at=timezone('utc',now()) WHERE status IN ('active','grace_period','delinquent') AND outstanding_principal_minor=0 AND NOT EXISTS(SELECT 1 FROM public.loan_schedule_lines l WHERE l.loan_contract_id=loan_contracts.id AND l.status<>'paid'); RETURN paid;
END $$;

CREATE OR REPLACE FUNCTION public.retry_loan_payment(p_loan_contract_id uuid,p_schedule_line_id uuid,p_idempotency_key text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.loan_contracts; l public.loan_schedule_lines; res jsonb; tx uuid; next_line record; total_due bigint; principal_due bigint; interest_due bigint; fee_due bigint;
BEGIN
  SELECT * INTO c FROM public.loan_contracts WHERE id=p_loan_contract_id FOR UPDATE; IF c.id IS NULL THEN RAISE EXCEPTION 'loan not found'; END IF;
  PERFORM public.banking_assert_owner_access(c.borrower_type,c.borrower_id,'manage_borrowing',c.outstanding_principal_minor);
  SELECT * INTO l FROM public.loan_schedule_lines WHERE id=p_schedule_line_id AND loan_contract_id=c.id FOR UPDATE; IF l.id IS NULL THEN RAISE EXCEPTION 'schedule line not found'; END IF;
  IF l.status='paid' OR l.due_date>CURRENT_DATE THEN RAISE EXCEPTION 'schedule line is not repayable'; END IF;
  principal_due:=GREATEST(0,l.scheduled_principal_minor-l.principal_paid_minor); interest_due:=GREATEST(0,l.scheduled_interest_minor-l.interest_paid_minor); fee_due:=GREATEST(0,l.scheduled_fee_minor-l.fee_paid_minor); total_due:=principal_due+interest_due+fee_due;
  res:=public.post_provider_loan_repayment(c.id,l.id,principal_due,interest_due,fee_due,'manual_retry',p_idempotency_key); tx:=(res->>'repayment_event_id')::uuid;
  UPDATE public.loan_schedule_lines SET amount_paid_minor=total_due,principal_paid_minor=scheduled_principal_minor,interest_paid_minor=scheduled_interest_minor,fee_paid_minor=scheduled_fee_minor,status='paid',payment_transaction_id=tx,repayment_event_id=tx WHERE id=l.id;
  SELECT * INTO next_line FROM public.loan_schedule_lines WHERE loan_contract_id=c.id AND status<>'paid' ORDER BY due_date,instalment_number LIMIT 1;
  UPDATE public.loan_contracts SET outstanding_principal_minor=GREATEST(0,outstanding_principal_minor-principal_due),amount_repaid_minor=amount_repaid_minor+total_due,interest_paid_minor=interest_paid_minor+interest_due,fees_paid_minor=fees_paid_minor+fee_due,payments_made=payments_made+1,next_payment_date=next_line.due_date,scheduled_payment_minor=COALESCE(next_line.total_due_minor,scheduled_payment_minor) WHERE id=c.id;
  RETURN jsonb_build_object('status','paid','repaymentEventId',tx,'amountMinor',total_due);
END $$;
GRANT EXECUTE ON FUNCTION public.retry_loan_payment(uuid,uuid,text) TO authenticated;

CREATE OR REPLACE FUNCTION public.create_loan_application(p_borrower_type public.financial_owner_type,p_borrower_id uuid,p_product_id uuid,p_requested_amount_minor bigint,p_requested_term_months integer,p_purpose public.loan_purpose,p_related_entity_type text DEFAULT NULL,p_related_entity_id uuid DEFAULT NULL,p_expected_use text DEFAULT NULL,p_idempotency_key text DEFAULT NULL,p_requested_currency_code char(3) DEFAULT NULL) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE existing uuid; prod public.loan_products; app_id uuid; avg_income bigint:=0; cash bigint:=0; debt_service bigint:=0; score int:=600; requested_currency char(3); period_start timestamptz:=timezone('utc',now())-interval '12 weeks'; country text;
BEGIN
  PERFORM public.banking_assert_owner_access(p_borrower_type,p_borrower_id,'apply_for_loan',p_requested_amount_minor);
  SELECT id INTO existing FROM public.loan_applications WHERE idempotency_key=p_idempotency_key AND p_idempotency_key IS NOT NULL; IF existing IS NOT NULL THEN RETURN existing; END IF;
  SELECT * INTO prod FROM public.loan_products WHERE id=p_product_id AND status='active'; IF prod.id IS NULL THEN RAISE EXCEPTION 'loan product unavailable'; END IF;
  requested_currency:=COALESCE(p_requested_currency_code,prod.supported_currencies[1]);
  IF NOT p_borrower_type=ANY(prod.eligible_owner_types) THEN RAISE EXCEPTION 'borrower type is not eligible'; END IF; IF NOT p_purpose=ANY(prod.allowed_purposes) THEN RAISE EXCEPTION 'loan purpose is not allowed'; END IF; IF p_requested_amount_minor<prod.minimum_amount_minor OR p_requested_amount_minor>prod.maximum_amount_minor THEN RAISE EXCEPTION 'requested amount is outside product limits'; END IF; IF p_requested_term_months<prod.minimum_term_months OR p_requested_term_months>prod.maximum_term_months THEN RAISE EXCEPTION 'requested term is outside product limits'; END IF; IF NOT requested_currency=ANY(prod.supported_currencies) THEN RAISE EXCEPTION 'requested currency is not supported'; END IF;
  SELECT primary_country INTO country FROM public.banking_customer_profiles WHERE owner_type=p_borrower_type AND owner_id=p_borrower_id; IF NOT EXISTS(SELECT 1 FROM public.banking_providers bp WHERE bp.id=prod.provider_id AND bp.status='active' AND COALESCE(country,bp.home_country)=ANY(bp.supported_countries)) THEN RAISE EXCEPTION 'provider is not available in borrower country'; END IF;
  IF EXISTS(SELECT 1 FROM public.loan_applications WHERE applicant_type=p_borrower_type AND applicant_id=p_borrower_id AND product_id=p_product_id AND status IN ('submitted','under_review','approved','offer_issued')) THEN RAISE EXCEPTION 'duplicate active application'; END IF;
  SELECT COALESCE(sum(t.net_amount_minor),0) INTO avg_income FROM public.financial_transactions t JOIN public.financial_accounts fa ON fa.id=t.destination_account_id WHERE fa.owner_type=p_borrower_type AND fa.owner_id=p_borrower_id AND t.created_at>=period_start AND t.transaction_category IN ('wage_payment','gig_payment','festival_payment','merchandise_revenue','streaming_royalty','song_release_royalty','company_revenue');
  SELECT COALESCE(sum(current_balance_minor),0) INTO cash FROM public.financial_accounts WHERE owner_type=p_borrower_type AND owner_id=p_borrower_id AND account_status='active' AND currency_code=requested_currency;
  SELECT COALESCE(sum(scheduled_payment_minor),0) INTO debt_service FROM public.loan_contracts WHERE borrower_type=p_borrower_type AND borrower_id=p_borrower_id AND status IN ('active','grace_period','delinquent'); SELECT COALESCE(credit_score,600) INTO score FROM public.banking_customer_profiles WHERE owner_type=p_borrower_type AND owner_id=p_borrower_id;
  INSERT INTO public.loan_applications(applicant_type,applicant_id,provider_id,product_id,requested_amount_minor,currency_code,requested_term_months,purpose,related_entity_type,related_entity_id,declared_expected_use,income_snapshot,expense_snapshot,debt_snapshot,credit_score_snapshot,affordability_result,status,created_by_profile_id,idempotency_key,metadata) VALUES(p_borrower_type,p_borrower_id,prod.provider_id,prod.id,p_requested_amount_minor,requested_currency,p_requested_term_months,p_purpose,p_related_entity_type,p_related_entity_id,p_expected_use,jsonb_build_object('source','server_generated','version','phase7_4_v1','period_start',period_start,'recurring_earned_income_minor',avg_income,'average_period_income_minor',floor(avg_income/12),'excluded_categories',jsonb_build_array('loan_disbursement','band_contribution','transfer_in','currency_conversion','refund','tax_placeholder','equipment_sale','administrative_adjustment')),jsonb_build_object('source','server_generated','version','phase7_4_v1'),jsonb_build_object('source','server_generated','existing_debt_service_minor',debt_service,'available_unrestricted_cash_minor',cash),score,jsonb_build_object('source','server_generated','snapshot_calculated_at',timezone('utc',now()),'income_requirement_minor',prod.income_requirement_minor,'passes_income_requirement',avg_income>=prod.income_requirement_minor),'submitted',(SELECT id FROM public.profiles WHERE user_id=auth.uid() LIMIT 1),COALESCE(p_idempotency_key,gen_random_uuid()::text),jsonb_build_object('snapshot_source','server_generated','snapshot_version','phase7_4_v1')) RETURNING id INTO app_id;
  PERFORM public.evaluate_loan_application(app_id); RETURN app_id;
END $$;
GRANT EXECUTE ON FUNCTION public.create_loan_application(public.financial_owner_type,uuid,uuid,bigint,integer,public.loan_purpose,text,uuid,text,text,char(3)) TO authenticated;

CREATE OR REPLACE FUNCTION public.list_banking_providers() RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'brandName',brand_name,'homeCountry',home_country,'supportedCountries',supported_countries,'supportedCurrencies',supported_currencies) ORDER BY brand_name),'[]'::jsonb) FROM public.banking_providers WHERE status IN ('active','restricted') $$;
CREATE OR REPLACE FUNCTION public.list_eligible_loan_products(p_borrower_type public.financial_owner_type DEFAULT 'player') RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT COALESCE(jsonb_agg(jsonb_build_object('id',lp.id,'providerId',lp.provider_id,'providerName',bp.brand_name,'productCode',lp.product_code,'productName',lp.product_name,'allowedPurposes',lp.allowed_purposes,'supportedCurrencies',lp.supported_currencies,'minimumAmountMinor',lp.minimum_amount_minor,'maximumAmountMinor',lp.maximum_amount_minor,'minimumTermMonths',lp.minimum_term_months,'maximumTermMonths',lp.maximum_term_months,'interestRateBps',lp.base_interest_rate_basis_points,'originationFeeBps',lp.origination_fee_basis_points,'originationFeeFlatMinor',lp.origination_fee_flat_minor,'scheduleType','equal_principal','eligibilityNotes',lp.purpose_restrictions) ORDER BY bp.brand_name,lp.product_name),'[]'::jsonb) FROM public.loan_products lp JOIN public.banking_providers bp ON bp.id=lp.provider_id WHERE lp.status='active' AND p_borrower_type=ANY(lp.eligible_owner_types) $$;
CREATE OR REPLACE FUNCTION public.list_player_bank_accounts() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE pid uuid; BEGIN SELECT id INTO pid FROM public.profiles WHERE user_id=auth.uid() LIMIT 1; RETURN COALESCE((SELECT jsonb_agg(jsonb_build_object('id',ba.id,'providerId',ba.provider_id,'providerName',bp.brand_name,'accountType',ba.account_type,'currencyCode',ba.currency_code,'status',ba.status,'balanceMinor',fa.current_balance_minor) ORDER BY ba.created_at) FROM public.bank_accounts ba JOIN public.financial_accounts fa ON fa.id=ba.linked_finance_account_id JOIN public.banking_providers bp ON bp.id=ba.provider_id WHERE ba.owner_type='player' AND ba.owner_id=pid),'[]'::jsonb); END $$;
CREATE OR REPLACE FUNCTION public.open_player_bank_account(p_provider_id uuid,p_account_type public.bank_account_type DEFAULT 'current',p_currency_code char(3) DEFAULT 'USD',p_idempotency_key text DEFAULT NULL) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE pid uuid; fa public.financial_accounts; ba uuid; BEGIN SELECT id INTO pid FROM public.profiles WHERE user_id=auth.uid() LIMIT 1; IF pid IS NULL THEN RAISE EXCEPTION 'profile required'; END IF; SELECT id INTO ba FROM public.bank_accounts WHERE owner_type='player' AND owner_id=pid AND provider_id=p_provider_id AND account_type=p_account_type AND currency_code=p_currency_code AND metadata->>'open_idempotency_key'=p_idempotency_key; IF ba IS NOT NULL THEN RETURN ba; END IF; fa:=public.get_or_create_financial_account_for_currency('player',pid,p_currency_code,'bank_cash','Player bank account',false); INSERT INTO public.bank_accounts(owner_type,owner_id,provider_id,account_type,currency_code,linked_finance_account_id,status,metadata) VALUES('player',pid,p_provider_id,p_account_type,p_currency_code,fa.id,'active',jsonb_build_object('open_idempotency_key',p_idempotency_key)) RETURNING id INTO ba; RETURN ba; END $$;
CREATE OR REPLACE FUNCTION public.get_loan_application_result(p_application_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT jsonb_build_object('id',a.id,'status',a.status,'affordabilityResult',a.affordability_result,'incomeSnapshot',a.income_snapshot,'offer',(SELECT jsonb_build_object('id',o.id,'status',o.status,'principalMinor',o.principal_minor,'currencyCode',o.currency_code,'interestRateBps',o.interest_rate_basis_points,'originationFeeMinor',o.origination_fee_minor,'totalInterestMinor',o.total_interest_minor,'totalRepaymentMinor',o.total_repayment_minor,'firstPaymentDate',o.first_payment_date,'offerExpiresAt',o.offer_expires_at) FROM public.loan_offers o WHERE o.application_id=a.id)) FROM public.loan_applications a WHERE a.id=p_application_id $$;
CREATE OR REPLACE FUNCTION public.get_active_loan_offer(p_application_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT jsonb_build_object('id',id,'principalMinor',principal_minor,'currencyCode',currency_code,'interestRateBps',interest_rate_basis_points,'originationFeeMinor',origination_fee_minor,'totalInterestMinor',total_interest_minor,'totalRepaymentMinor',total_repayment_minor,'firstPaymentDate',first_payment_date,'offerExpiresAt',offer_expires_at) FROM public.loan_offers WHERE application_id=p_application_id AND status='issued' ORDER BY created_at DESC LIMIT 1 $$;
CREATE OR REPLACE FUNCTION public.get_loan_details(p_loan_contract_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT jsonb_build_object('id',c.id,'providerName',bp.brand_name,'status',c.status,'purpose',c.purpose,'principalMinor',c.principal_minor,'outstandingPrincipalMinor',c.outstanding_principal_minor,'currencyCode',c.currency_code,'interestRateBps',c.interest_rate_basis_points,'originationFeeMinor',COALESCE(o.origination_fee_minor,0),'nextPaymentDate',n.due_date,'nextPaymentMinor',COALESCE(n.total_due_minor-n.amount_paid_minor,0),'repaymentBankAccountId',c.repayment_bank_account_id,'disbursementBankAccountId',c.disbursement_bank_account_id) FROM public.loan_contracts c JOIN public.banking_providers bp ON bp.id=c.provider_id LEFT JOIN public.loan_offers o ON o.id=c.offer_id LEFT JOIN LATERAL (SELECT * FROM public.loan_schedule_lines l WHERE l.loan_contract_id=c.id AND l.status<>'paid' ORDER BY l.due_date,l.instalment_number LIMIT 1) n ON true WHERE c.id=p_loan_contract_id $$;
CREATE OR REPLACE FUNCTION public.get_loan_schedule(p_loan_contract_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'instalmentNumber',instalment_number,'dueDate',due_date,'openingPrincipalMinor',opening_principal_minor,'principalMinor',scheduled_principal_minor,'interestMinor',scheduled_interest_minor,'feeMinor',scheduled_fee_minor,'totalDueMinor',total_due_minor,'amountPaidMinor',amount_paid_minor,'status',status) ORDER BY instalment_number),'[]'::jsonb) FROM public.loan_schedule_lines WHERE loan_contract_id=p_loan_contract_id $$;
CREATE OR REPLACE FUNCTION public.list_loan_payment_attempts(p_loan_contract_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'scheduleLineId',schedule_line_id,'amountMinor',amount_minor,'principalMinor',principal_minor,'interestMinor',interest_minor,'feeMinor',fee_minor,'paymentType',payment_type,'createdAt',created_at,'transactionId',transaction_id) ORDER BY created_at DESC),'[]'::jsonb) FROM public.loan_payments WHERE loan_contract_id=p_loan_contract_id $$;
GRANT EXECUTE ON FUNCTION public.list_banking_providers() TO authenticated; GRANT EXECUTE ON FUNCTION public.list_eligible_loan_products(public.financial_owner_type) TO authenticated; GRANT EXECUTE ON FUNCTION public.list_player_bank_accounts() TO authenticated; GRANT EXECUTE ON FUNCTION public.open_player_bank_account(uuid,public.bank_account_type,char(3),text) TO authenticated; GRANT EXECUTE ON FUNCTION public.get_loan_application_result(uuid) TO authenticated; GRANT EXECUTE ON FUNCTION public.get_active_loan_offer(uuid) TO authenticated; GRANT EXECUTE ON FUNCTION public.get_loan_details(uuid) TO authenticated; GRANT EXECUTE ON FUNCTION public.get_loan_schedule(uuid) TO authenticated; GRANT EXECUTE ON FUNCTION public.list_loan_payment_attempts(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.reconcile_loan_contract(p_loan_contract_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
WITH c AS (SELECT * FROM public.loan_contracts WHERE id=p_loan_contract_id), ledger AS (
 SELECT COALESCE(sum(CASE WHEN b.account_role='loan_receivable' THEN CASE WHEN e.entry_direction='credit' THEN e.amount_minor ELSE -e.amount_minor END ELSE 0 END),0) receivable,
        COALESCE(sum(CASE WHEN b.account_role='interest_income' THEN CASE WHEN e.entry_direction='credit' THEN e.amount_minor ELSE -e.amount_minor END ELSE 0 END),0) interest,
        COALESCE(sum(CASE WHEN b.account_role='fee_income' THEN CASE WHEN e.entry_direction='credit' THEN e.amount_minor ELSE -e.amount_minor END ELSE 0 END),0) fees
 FROM c JOIN public.banking_provider_financial_accounts b ON b.provider_id=c.provider_id AND b.currency_code=c.currency_code LEFT JOIN public.financial_ledger_entries e ON e.account_id=b.finance_account_id LEFT JOIN public.financial_transactions t ON t.id=e.transaction_id AND t.related_entity_type='loan_contract' AND t.related_entity_id=(SELECT id FROM c)
), p AS (SELECT COALESCE(sum(principal_minor),0) principal,COALESCE(sum(interest_minor),0) interest,COALESCE(sum(fee_minor),0) fees,COALESCE(sum(amount_minor),0) repaid FROM public.loan_payments WHERE loan_contract_id=p_loan_contract_id)
SELECT jsonb_build_object('contractPrincipal',c.principal_minor,'outstandingPrincipal',c.outstanding_principal_minor,'originatedReceivable',c.principal_minor,'repaidPrincipal',p.principal,'writtenOffPrincipal',0,'interestPaid',c.interest_paid_minor,'interestJournalTotal',ledger.interest,'feesPaid',c.fees_paid_minor,'feeJournalTotal',ledger.fees,'borrowerCashReceived',c.principal_minor,'borrowerCashRepaid',p.repaid,'status',c.status,'issues',CASE WHEN ledger.receivable=c.outstanding_principal_minor AND ledger.interest=c.interest_paid_minor AND ledger.fees>=c.fees_paid_minor THEN '[]'::jsonb ELSE jsonb_build_array('ledger_component_mismatch') END,'reconciliationStatus',CASE WHEN ledger.receivable=c.outstanding_principal_minor AND ledger.interest=c.interest_paid_minor AND ledger.fees>=c.fees_paid_minor THEN 'Reconciled' ELSE 'Critical' END) FROM c,ledger,p $$;
GRANT EXECUTE ON FUNCTION public.reconcile_loan_contract(uuid) TO authenticated;

CREATE OR REPLACE VIEW public.banking_provider_reconciliation AS
WITH loans AS (SELECT c.provider_id,c.currency_code,COALESCE(sum(c.outstanding_principal_minor),0) contract_outstanding_principal_minor,COALESCE(sum(c.principal_minor),0) originated_principal_minor,COALESCE(sum(c.interest_paid_minor),0) paid_interest_minor,COALESCE(sum(c.fees_paid_minor),0) paid_fee_minor FROM public.loan_contracts c GROUP BY c.provider_id,c.currency_code), ledger AS (SELECT b.provider_id,b.currency_code,COALESCE(sum(CASE WHEN b.account_role='loan_receivable' THEN CASE WHEN e.entry_direction='credit' THEN e.amount_minor ELSE -e.amount_minor END ELSE 0 END),0) receivable_ledger_minor,COALESCE(sum(CASE WHEN b.account_role='interest_income' THEN CASE WHEN e.entry_direction='credit' THEN e.amount_minor ELSE -e.amount_minor END ELSE 0 END),0) interest_income_ledger_minor,COALESCE(sum(CASE WHEN b.account_role='fee_income' THEN CASE WHEN e.entry_direction='credit' THEN e.amount_minor ELSE -e.amount_minor END ELSE 0 END),0) fee_income_ledger_minor,COALESCE(sum(CASE WHEN b.account_role='settlement_clearing' THEN CASE WHEN e.entry_direction='credit' THEN e.amount_minor ELSE -e.amount_minor END ELSE 0 END),0) settlement_clearing_minor FROM public.banking_provider_financial_accounts b LEFT JOIN public.financial_ledger_entries e ON e.account_id=b.finance_account_id GROUP BY b.provider_id,b.currency_code)
SELECT COALESCE(l.provider_id,g.provider_id) provider_id,COALESCE(l.currency_code,g.currency_code) currency_code,COALESCE(l.contract_outstanding_principal_minor,0) contract_outstanding_principal_minor,COALESCE(l.originated_principal_minor,0) originated_principal_minor,COALESCE(l.paid_interest_minor,0) paid_interest_minor,COALESCE(l.paid_fee_minor,0) paid_fee_minor,COALESCE(g.receivable_ledger_minor,0) receivable_ledger_minor,COALESCE(g.interest_income_ledger_minor,0) interest_income_ledger_minor,COALESCE(g.fee_income_ledger_minor,0) fee_income_ledger_minor,COALESCE(g.settlement_clearing_minor,0) settlement_clearing_minor,COALESCE(g.receivable_ledger_minor,0)-COALESCE(l.contract_outstanding_principal_minor,0) receivable_difference_minor,COALESCE(g.interest_income_ledger_minor,0)-COALESCE(l.paid_interest_minor,0) interest_income_difference_minor,COALESCE(g.fee_income_ledger_minor,0)-COALESCE(l.paid_fee_minor,0) fee_income_difference_minor,CASE WHEN COALESCE(g.receivable_ledger_minor,0)=COALESCE(l.contract_outstanding_principal_minor,0) AND COALESCE(g.interest_income_ledger_minor,0)=COALESCE(l.paid_interest_minor,0) AND COALESCE(g.fee_income_ledger_minor,0)>=COALESCE(l.paid_fee_minor,0) THEN 'Reconciled' ELSE 'Critical' END status FROM loans l FULL JOIN ledger g ON g.provider_id=l.provider_id AND g.currency_code=l.currency_code;

CREATE OR REPLACE VIEW public.loan_integrity_issues AS
SELECT 'loan_principal_without_disbursement_transaction' issue_type,id::text subject_id FROM public.loan_contracts WHERE status<>'cancelled' AND disbursement_transaction_id IS NULL
UNION ALL SELECT 'loan_disbursement_classified_as_income',c.id::text FROM public.loan_contracts c JOIN public.financial_transactions t ON t.id=c.disbursement_transaction_id WHERE t.transaction_category<>'loan_disbursement' OR COALESCE((t.metadata->>'taxable')::boolean,true)
UNION ALL SELECT 'loan_without_repayment_schedule',c.id::text FROM public.loan_contracts c WHERE NOT EXISTS(SELECT 1 FROM public.loan_schedule_lines l WHERE l.loan_contract_id=c.id)
UNION ALL SELECT 'principal_below_zero',id::text FROM public.loan_contracts WHERE outstanding_principal_minor<0
UNION ALL SELECT 'paid_off_loan_with_remaining_balance',id::text FROM public.loan_contracts WHERE status='paid_off' AND outstanding_principal_minor<>0
UNION ALL SELECT 'loan_payment_without_ledger_transaction',id::text FROM public.loan_payments WHERE COALESCE(journal_event_id,transaction_id) IS NULL
UNION ALL SELECT 'late_fee_duplicated',schedule_line_id::text FROM public.loan_delinquency_records WHERE late_fee_minor>0 GROUP BY schedule_line_id HAVING count(*)>1
UNION ALL SELECT 'default_without_overdue_schedule',d.loan_contract_id::text FROM public.loan_default_records d WHERE NOT EXISTS(SELECT 1 FROM public.loan_schedule_lines l WHERE l.loan_contract_id=d.loan_contract_id AND l.status='defaulted')
UNION ALL SELECT 'credit_score_outside_allowed_range',id::text FROM public.banking_customer_profiles WHERE credit_score<0 OR credit_score>1000
UNION ALL SELECT 'bank_account_balance_mismatch',ba.id::text FROM public.bank_accounts ba JOIN public.financial_accounts fa ON fa.id=ba.linked_finance_account_id LEFT JOIN (SELECT account_id,COALESCE(sum(CASE WHEN entry_direction='credit' THEN amount_minor ELSE -amount_minor END),0) bal FROM public.financial_ledger_entries GROUP BY account_id) s ON s.account_id=fa.id WHERE fa.owner_type<>'system' AND fa.current_balance_minor<>COALESCE(s.bal,0)
UNION ALL SELECT 'savings_interest_without_funding_transaction',id::text FROM public.deposit_interest_accruals WHERE status='paid' AND COALESCE(payment_transaction_id,linked_transaction_id) IS NULL
UNION ALL SELECT 'duplicate_active_repayment_obligation',related_entity_id::text FROM public.recurring_financial_obligations WHERE related_entity_type='loan_contract' AND status='active' GROUP BY related_entity_id HAVING count(*)>1
UNION ALL SELECT 'unsupported_loan_currency',c.id::text FROM public.loan_contracts c JOIN public.banking_providers p ON p.id=c.provider_id WHERE NOT (c.currency_code=ANY(p.supported_currencies))
UNION ALL SELECT 'provider_exposure_mismatch',p.id::text FROM public.banking_providers p WHERE COALESCE((SELECT sum(outstanding_principal_minor) FROM public.loan_contracts c WHERE c.provider_id=p.id AND c.status IN ('active','grace_period','delinquent','defaulted')),0)>p.maximum_exposure_minor
UNION ALL SELECT 'financial_account_currency_default_mismatch',id::text FROM public.financial_accounts WHERE account_status='active' AND currency_code<>default_currency_code
UNION ALL SELECT 'active_contract_without_origination_event',id::text FROM public.loan_contracts WHERE status='active' AND origination_event_id IS NULL
UNION ALL SELECT 'origination_fee_expected_but_not_posted',c.id::text FROM public.loan_contracts c JOIN public.loan_offers o ON o.id=c.offer_id WHERE o.origination_fee_minor>0 AND c.origination_fee_transaction_id IS NULL
UNION ALL SELECT 'provider_receivable_mismatch',provider_id::text FROM public.banking_provider_reconciliation WHERE receivable_difference_minor<>0
UNION ALL SELECT 'provider_interest_mismatch',provider_id::text FROM public.banking_provider_reconciliation WHERE interest_income_difference_minor<>0
UNION ALL SELECT 'provider_fee_mismatch',provider_id::text FROM public.banking_provider_reconciliation WHERE fee_income_difference_minor<0
UNION ALL SELECT 'settlement_clearing_imbalance',provider_id::text FROM public.banking_provider_reconciliation WHERE settlement_clearing_minor<>0
UNION ALL SELECT 'repayment_component_mismatch',id::text FROM public.loan_payments WHERE amount_minor<>principal_minor+interest_minor+fee_minor
UNION ALL SELECT 'schedule_principal_total_mismatch',c.id::text FROM public.loan_contracts c JOIN (SELECT loan_contract_id,sum(scheduled_principal_minor) total FROM public.loan_schedule_lines GROUP BY loan_contract_id) s ON s.loan_contract_id=c.id WHERE s.total<>c.principal_minor
UNION ALL SELECT 'contract_next_payment_mismatch',c.id::text FROM public.loan_contracts c LEFT JOIN LATERAL (SELECT due_date,total_due_minor FROM public.loan_schedule_lines l WHERE l.loan_contract_id=c.id AND l.status<>'paid' ORDER BY due_date,instalment_number LIMIT 1) n ON true WHERE c.status IN ('active','grace_period','delinquent') AND (c.next_payment_date IS DISTINCT FROM n.due_date OR c.scheduled_payment_minor IS DISTINCT FROM n.total_due_minor);

CREATE OR REPLACE FUNCTION public.get_banking_dashboard() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE pid uuid; result jsonb; BEGIN SELECT id INTO pid FROM public.profiles WHERE user_id=auth.uid() LIMIT 1; IF pid IS NULL THEN RETURN jsonb_build_object('accounts','[]'::jsonb,'loans','[]'::jsonb,'creditProfile',jsonb_build_object('band','Building','positiveFactors',jsonb_build_array('Create a profile to start banking.'),'negativeFactors','[]'::jsonb),'recentActivity','[]'::jsonb); END IF; SELECT jsonb_build_object('accounts',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',ba.id,'accountType',ba.account_type,'currencyCode',ba.currency_code,'balanceMinor',fa.current_balance_minor,'providerName',bp.brand_name,'restrictionSummary',CASE WHEN ba.status='restricted' THEN 'Restricted' ELSE 'Unrestricted' END,'annualRateBps',COALESCE((ba.interest_configuration->>'annual_rate_bps')::int,0))) FROM public.bank_accounts ba JOIN public.financial_accounts fa ON fa.id=ba.linked_finance_account_id JOIN public.banking_providers bp ON bp.id=ba.provider_id WHERE ba.owner_type='player' AND ba.owner_id=pid),'[]'::jsonb),'loans',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',c.id,'providerName',bp.brand_name,'status',c.status,'principalMinor',c.principal_minor,'outstandingPrincipalMinor',c.outstanding_principal_minor,'currencyCode',c.currency_code,'interestRateBps',c.interest_rate_basis_points,'nextPaymentMinor',COALESCE(n.total_due_minor-n.amount_paid_minor,0),'nextPaymentDate',n.due_date,'overdueMinor',COALESCE(o.overdue,0))) FROM public.loan_contracts c JOIN public.banking_providers bp ON bp.id=c.provider_id LEFT JOIN LATERAL (SELECT * FROM public.loan_schedule_lines l WHERE l.loan_contract_id=c.id AND l.status<>'paid' ORDER BY l.due_date,l.instalment_number LIMIT 1) n ON true LEFT JOIN LATERAL (SELECT sum(total_due_minor-amount_paid_minor) overdue FROM public.loan_schedule_lines l WHERE l.loan_contract_id=c.id AND l.due_date<CURRENT_DATE AND l.status<>'paid') o ON true WHERE c.borrower_type='player' AND c.borrower_id=pid AND c.status NOT IN ('cancelled','paid_off')),'[]'::jsonb),'creditProfile',COALESCE((SELECT jsonb_build_object('band',credit_band,'score',credit_score,'positiveFactors',jsonb_build_array('On-time payments improve your band.'),'negativeFactors','[]'::jsonb) FROM public.banking_customer_profiles WHERE owner_type='player' AND owner_id=pid),jsonb_build_object('band','Building','positiveFactors',jsonb_build_array('Open a current account to start building a banking history.'),'negativeFactors','[]'::jsonb)),'recentActivity','[]'::jsonb) INTO result; RETURN result; END $$;
