-- Expand player creation origin/backstory choices.
-- Existing origins remain unchanged so current player identities keep their references.

INSERT INTO public.character_origins
  (key, name, tagline, description, icon, starting_cash, starting_fame, skill_bonuses, reputation_modifiers, display_order)
VALUES
  ('bedroom_songwriter', 'Bedroom Songwriter', 'A catalogue nobody has heard yet', 'You spent years writing songs behind a closed bedroom door, building a private catalogue and learning how to turn everyday moments into lyrics. You have little stage experience, but plenty to say.', 'pen-line', 100, 0, '{"songwriting": 15, "composition": 5}', '{"creativity": 15, "authenticity": 10}', 9),
  ('open_mic_regular', 'Open Mic Regular', 'Five songs, one mic, no safety net', 'You learned your craft in pubs, cafés, and tiny clubs where every audience had to be won over from scratch. You are comfortable performing without production tricks and know how to recover when a set goes wrong.', 'mic-2', 75, 5, '{"performance": 10, "vocals": 10}', '{"authenticity": 10, "reliability": 5}', 10),
  ('choir_kid', 'Choir Kid', 'Harmony came before the spotlight', 'Years of rehearsals taught you pitch, discipline, and how to blend with other voices. Now you want to discover what your own voice sounds like when nobody else is singing the same part.', 'audio-lines', 125, 0, '{"vocals": 15, "technical": 5}', '{"reliability": 10, "attitude": 5}', 11),
  ('battle_of_bands', 'Battle of the Bands Winner', 'You already know how it feels to win a room', 'A run of local competitions gave you your first taste of trophies, rivalries, and noisy crowds. You have momentum and confidence, but the professional circuit is a much bigger arena.', 'trophy', 200, 20, '{"performance": 10, "guitar": 5, "vocals": 5}', '{"attitude": -5, "creativity": 5}', 12),
  ('cover_band_pro', 'Cover Band Professional', 'A thousand songs and a thousand late nights', 'Weddings, bars, clubs, corporate stages—you have played them all. You can learn material quickly, keep a crowd moving, and finish a set professionally even when the room is difficult.', 'list-music', 300, 5, '{"performance": 10, "technical": 10}', '{"reliability": 15, "creativity": -5}', 13),
  ('studio_apprentice', 'Studio Apprentice', 'You learned music from the other side of the glass', 'You started by making tea, wrapping cables, and watching sessions from the control room. Along the way you learned arrangement, recording etiquette, and what separates a rough demo from a finished record.', 'sliders-horizontal', 250, 0, '{"technical": 10, "composition": 10, "songwriting": 5}', '{"reliability": 10, "creativity": 5}', 14),
  ('dj_producer', 'Bedroom Producer', 'Built on beats, samples, and sleepless nights', 'Your first audience lived online. You taught yourself production by rebuilding tracks, chopping samples, and uploading experiments late at night. Now you want to turn production skill into an artist career.', 'headphones', 150, 5, '{"technical": 10, "composition": 10, "creativity": 10}', '{"creativity": 15}', 15),
  ('musical_family', 'Musical Family', 'Music was always in the house', 'Rehearsals, instruments, records, and arguments about songs were part of everyday life growing up. You begin with broad musical instincts and useful advice, but still have to build a reputation of your own.', 'house', 200, 5, '{"songwriting": 5, "performance": 5, "technical": 5}', '{"reliability": 5, "authenticity": 5}', 16),
  ('punk_squat', 'DIY Scene Regular', 'No label, no budget, no permission needed', 'You came up putting on tiny shows, printing flyers, trading favours, and making things happen with almost no money. You trust scenes and communities more than gatekeepers.', 'megaphone', 40, 10, '{"performance": 10, "creativity": 5}', '{"authenticity": 20, "attitude": -5}', 17),
  ('church_musician', 'Community Musician', 'You learned to serve the song and the room', 'Weekly performances at community gatherings taught you consistency, listening, harmony, and how to support other musicians rather than compete for every moment of attention.', 'heart-handshake', 100, 0, '{"vocals": 10, "performance": 5, "technical": 5}', '{"reliability": 15, "attitude": 10}', 18),
  ('talent_show_alumni', 'Talent Show Alumni', 'You have already faced the judges', 'A televised or regional talent competition put you under bright lights early. You learned to perform under pressure and handle attention, even if some people still see you as a contestant rather than an artist.', 'star', 250, 35, '{"performance": 15, "vocals": 5}', '{"authenticity": -5, "attitude": 5}', 19),
  ('late_bloomer', 'Late Bloomer', 'The dream waited. You did not forget it.', 'Music was always the unfinished chapter. After years spent building a life outside the industry, you finally decided to give the songs, rehearsals, and stages the commitment they deserved.', 'sprout', 400, 0, '{"songwriting": 10, "performance": 5}', '{"reliability": 15, "authenticity": 10}', 20),
  ('road_crew', 'Road Crew Graduate', 'You learned the stage by building it', 'Before performing on stages, you loaded them. Touring crews taught you how venues work, what professionals expect, and how much effort happens before the first note is played.', 'wrench', 250, 0, '{"technical": 15, "performance": 5}', '{"reliability": 20}', 21),
  ('record_collector', 'Record Collector', 'Obsession became an education', 'You spent years hunting records, studying liner notes, comparing eras, and tracing the influences behind your favourite artists. Your practical experience is limited, but your musical vocabulary is unusually deep.', 'disc-3', 100, 0, '{"composition": 10, "songwriting": 10, "creativity": 5}', '{"creativity": 10, "authenticity": 10}', 22),
  ('self_taught_outsider', 'Self-Taught Outsider', 'Nobody showed you the correct way', 'You learned by ear, imitation, experimentation, and stubborn repetition. Your technique can be unconventional, but so are the ideas that come from never being told what you are supposed to do.', 'sparkles', 75, 0, '{"creativity": 15, "performance": 5, "songwriting": 5}', '{"creativity": 20, "authenticity": 10}', 23),
  ('former_child_performer', 'Former Child Performer', 'The stage stopped being new a long time ago', 'You performed when most people your age were still discovering music. Experience gave you composure and technique, but adulthood means deciding what kind of artist you actually want to become.', 'spotlight', 300, 15, '{"performance": 15, "technical": 5}', '{"reliability": 10, "authenticity": -5}', 24)
ON CONFLICT (key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  starting_cash = EXCLUDED.starting_cash,
  starting_fame = EXCLUDED.starting_fame,
  skill_bonuses = EXCLUDED.skill_bonuses,
  reputation_modifiers = EXCLUDED.reputation_modifiers,
  display_order = EXCLUDED.display_order,
  is_active = true,
  updated_at = now();
