-- Finance Phase 8B.6: obligations security/correctness repair and band expense funding foundation.


ALTER TABLE public.financial_obligations ADD COLUMN IF NOT EXISTS business_key text;
ALTER TABLE public.financial_obligations ADD COLUMN IF NOT EXISTS accounting_strategy text NOT NULL DEFAULT 'generic_transfer';
ALTER TABLE public.financial_obligation_schedule ADD COLUMN IF NOT EXISTS source_schedule_version integer NOT NULL DEFAULT 1;
ALTER TABLE public.financial_obligation_schedule ADD COLUMN IF NOT EXISTS business_key text;
ALTER TABLE public.financial_obligation_schedule ADD COLUMN IF NOT EXISTS idempotency_key text;
ALTER TABLE public.financial_obligation_schedule ADD COLUMN IF NOT EXISTS first_missed_at timestamptz;
ALTER TABLE public.financial_obligation_schedule ADD COLUMN IF NOT EXISTS next_retry_at timestamptz;
ALTER TABLE public.financial_obligation_schedule ADD COLUMN IF NOT EXISTS last_attempted_at timestamptz;
ALTER TABLE public.financial_obligation_schedule ADD COLUMN IF NOT EXISTS resolved_at timestamptz;
ALTER TABLE public.debt_records ADD COLUMN IF NOT EXISTS schedule_id uuid REFERENCES public.financial_obligation_schedule(id);
ALTER TABLE public.player_credit_scores ADD COLUMN IF NOT EXISTS calculation_version text NOT NULL DEFAULT 'phase8b6_weighted_v1';
ALTER TABLE public.player_credit_scores ADD COLUMN IF NOT EXISTS factor_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE public.player_credit_scores ADD COLUMN IF NOT EXISTS calculated_from_event_date date;
ALTER TABLE public.mortgage_contracts ADD COLUMN IF NOT EXISTS financial_obligation_id uuid REFERENCES public.financial_obligations(id);
ALTER TABLE public.band_expense_payments ADD COLUMN IF NOT EXISTS transaction_id uuid REFERENCES public.financial_transactions(id);
ALTER TABLE public.band_expense_payments ADD COLUMN IF NOT EXISTS metadata jsonb NOT NULL DEFAULT '{}'::jsonb;

UPDATE public.financial_obligations SET business_key=concat_ws(':',obligation_type,owner_type,owner_id::text,COALESCE(linked_asset_type,'none'),COALESCE(linked_asset_id::text,legacy_recurring_obligation_id::text,id::text)) WHERE business_key IS NULL;
UPDATE public.financial_obligation_schedule s SET business_key=concat_ws(':',s.obligation_id::text,COALESCE(s.source_schedule_type,'manual'),COALESCE(s.source_schedule_id::text,s.instalment_number::text),s.source_schedule_version::text) WHERE business_key IS NULL;
UPDATE public.debt_records d SET schedule_id=(d.metadata->>'schedule_id')::uuid WHERE d.schedule_id IS NULL AND d.metadata ? 'schedule_id';

CREATE UNIQUE INDEX IF NOT EXISTS financial_obligations_business_key_idx ON public.financial_obligations(business_key);
CREATE UNIQUE INDEX IF NOT EXISTS financial_obligation_schedule_business_key_idx ON public.financial_obligation_schedule(business_key);
CREATE UNIQUE INDEX IF NOT EXISTS debt_records_one_open_per_schedule_idx ON public.debt_records(obligation_id,schedule_id) WHERE status='open' AND schedule_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS player_credit_history_unique_schedule_event_idx ON public.player_credit_history(profile_id,event_type,obligation_id,((private_metadata->>'schedule_id'))) WHERE private_metadata ? 'schedule_id';

ALTER TABLE public.financial_obligation_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_obligations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_obligation_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_obligation_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_obligation_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_obligation_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.debt_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.debt_collection_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_credit_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_credit_scores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS financial_obligations_owner_select ON public.financial_obligations;
CREATE POLICY financial_obligations_owner_select ON public.financial_obligations FOR SELECT TO authenticated USING (
  (owner_type='player' AND owner_id=public.current_player_profile_id())
  OR (owner_type='band' AND public.user_has_band_finance_permission(owner_id, public.current_player_profile_id(), 'view_detailed_income_expenses'::public.band_finance_permission))
);
DROP POLICY IF EXISTS financial_obligation_policies_read ON public.financial_obligation_policies;
CREATE POLICY financial_obligation_policies_read ON public.financial_obligation_policies FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS financial_obligation_schedule_owner_select ON public.financial_obligation_schedule;
CREATE POLICY financial_obligation_schedule_owner_select ON public.financial_obligation_schedule FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.financial_obligations o WHERE o.id=obligation_id AND ((o.owner_type='player' AND o.owner_id=public.current_player_profile_id()) OR (o.owner_type='band' AND public.user_has_band_finance_permission(o.owner_id, public.current_player_profile_id(), 'view_detailed_income_expenses'::public.band_finance_permission)))));
DROP POLICY IF EXISTS financial_obligation_attempts_owner_select ON public.financial_obligation_attempts;
CREATE POLICY financial_obligation_attempts_owner_select ON public.financial_obligation_attempts FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.financial_obligations o WHERE o.id=obligation_id AND o.owner_type='player' AND o.owner_id=public.current_player_profile_id()));
DROP POLICY IF EXISTS financial_obligation_events_owner_select ON public.financial_obligation_events;
CREATE POLICY financial_obligation_events_owner_select ON public.financial_obligation_events FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.financial_obligations o WHERE o.id=obligation_id AND o.owner_type='player' AND o.owner_id=public.current_player_profile_id()));
DROP POLICY IF EXISTS financial_obligation_status_history_owner_select ON public.financial_obligation_status_history;
CREATE POLICY financial_obligation_status_history_owner_select ON public.financial_obligation_status_history FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.financial_obligations o WHERE o.id=obligation_id AND o.owner_type='player' AND o.owner_id=public.current_player_profile_id()));
DROP POLICY IF EXISTS debt_records_owner_select ON public.debt_records;
CREATE POLICY debt_records_owner_select ON public.debt_records FOR SELECT TO authenticated USING (owner_type='player' AND owner_id=public.current_player_profile_id());
DROP POLICY IF EXISTS debt_collection_events_owner_select ON public.debt_collection_events;
CREATE POLICY debt_collection_events_owner_select ON public.debt_collection_events FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.debt_records d WHERE d.id=debt_id AND d.owner_type='player' AND d.owner_id=public.current_player_profile_id()));
DROP POLICY IF EXISTS player_credit_history_owner_select ON public.player_credit_history;
CREATE POLICY player_credit_history_owner_select ON public.player_credit_history FOR SELECT TO authenticated USING (profile_id=public.current_player_profile_id());
DROP POLICY IF EXISTS player_credit_scores_owner_select ON public.player_credit_scores;
CREATE POLICY player_credit_scores_owner_select ON public.player_credit_scores FOR SELECT TO authenticated USING (profile_id=public.current_player_profile_id());

REVOKE ALL ON public.financial_obligations, public.financial_obligation_schedule, public.financial_obligation_attempts, public.financial_obligation_events, public.financial_obligation_status_history, public.debt_records, public.debt_collection_events, public.player_credit_history, public.player_credit_scores FROM anon, authenticated;
GRANT SELECT ON public.financial_obligations, public.financial_obligation_schedule, public.financial_obligation_attempts, public.financial_obligation_events, public.financial_obligation_status_history, public.debt_records, public.debt_collection_events, public.player_credit_history, public.player_credit_scores TO authenticated;
GRANT ALL ON public.financial_obligations, public.financial_obligation_schedule, public.financial_obligation_attempts, public.financial_obligation_events, public.financial_obligation_status_history, public.debt_records, public.debt_collection_events, public.player_credit_history, public.player_credit_scores TO service_role;

CREATE OR REPLACE FUNCTION public.reconcile_financial_obligation_state(p_obligation_id uuid,p_as_of_date date DEFAULT CURRENT_DATE) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE out_bal bigint; missed int; next_due date; new_status public.financial_obligation_status;
BEGIN
 SELECT COALESCE(sum(amount_minor) FILTER (WHERE status IN ('missed','failed') OR (status IN ('scheduled','due') AND due_date<=p_as_of_date)),0), count(*) FILTER (WHERE first_missed_at IS NOT NULL AND resolved_at IS NULL), min(due_date) FILTER (WHERE status IN ('scheduled','due','missed','failed')) INTO out_bal,missed,next_due FROM public.financial_obligation_schedule WHERE obligation_id=p_obligation_id;
 IF EXISTS (SELECT 1 FROM public.debt_records WHERE obligation_id=p_obligation_id AND status='open' AND collection_stage IN ('collections','legal_action','asset_recovery')) THEN new_status:='collections';
 ELSIF next_due IS NULL THEN new_status:='completed';
 ELSIF EXISTS (SELECT 1 FROM public.financial_obligation_schedule WHERE obligation_id=p_obligation_id AND next_retry_at IS NOT NULL AND next_retry_at>timezone('utc',now()) AND resolved_at IS NULL) THEN new_status:='retrying';
 ELSIF out_bal>0 THEN new_status:='failed'; ELSE new_status:='active'; END IF;
 UPDATE public.financial_obligations SET outstanding_balance_minor=out_bal, missed_payment_count=missed, next_due_date=COALESCE(next_due,next_due_date), status=CASE WHEN status IN ('paused','cancelled','written_off') THEN status ELSE new_status END, updated_at=timezone('utc',now()), completed_at=CASE WHEN new_status='completed' THEN COALESCE(completed_at,timezone('utc',now())) ELSE completed_at END WHERE id=p_obligation_id;
 RETURN jsonb_build_object('outstandingBalanceMinor',out_bal,'missedPaymentCount',missed,'nextDueDate',next_due,'status',new_status);
END $$;

CREATE OR REPLACE FUNCTION public.record_financial_obligation_event_internal(p_obligation_id uuid,p_event_type public.financial_obligation_event_type,p_payload jsonb DEFAULT '{}'::jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE eid uuid; BEGIN INSERT INTO public.financial_obligation_events(obligation_id,event_type,event_payload,created_by_profile_id) VALUES(p_obligation_id,p_event_type,p_payload,public.current_player_profile_id()) RETURNING id INTO eid; RETURN eid; END $$;
CREATE OR REPLACE FUNCTION public.record_financial_obligation_event(p_obligation_id uuid,p_event_type public.financial_obligation_event_type,p_payload jsonb DEFAULT '{}'::jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service role required' USING ERRCODE='42501'; END IF; RETURN public.record_financial_obligation_event_internal(p_obligation_id,p_event_type,p_payload); END $$;

CREATE OR REPLACE FUNCTION public.recalculate_player_credit_score_internal(p_profile_id uuid) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE total_events int; paid int; misses int; collections int; open_debt bigint; oldest_days int; recent_negative int; score int; snap jsonb;
BEGIN
 SELECT count(*), count(*) FILTER (WHERE event_type IN ('successful_payment','mortgage_completion','debt_settlement')), count(*) FILTER (WHERE event_type IN ('missed_payment','default')), count(*) FILTER (WHERE event_type='collection'), COALESCE(max(CURRENT_DATE-event_date),0), count(*) FILTER (WHERE event_type IN ('missed_payment','default','collection') AND event_date>=CURRENT_DATE-interval '180 days') INTO total_events,paid,misses,collections,oldest_days,recent_negative FROM public.player_credit_history WHERE profile_id=p_profile_id;
 SELECT COALESCE(sum(outstanding_balance_minor),0) INTO open_debt FROM public.debt_records WHERE owner_type='player' AND owner_id=p_profile_id AND status='open';
 score:=600 + LEAST(80,paid*5) + LEAST(45,oldest_days/30) - LEAST(180,misses*25 + recent_negative*20) - LEAST(160,collections*70) - LEAST(120,(open_debt/10000)::int);
 score:=LEAST(850,GREATEST(300,score));
 snap:=jsonb_build_object('version','phase8b6_weighted_v1','paidEvents',paid,'missedEvents',misses,'collections',collections,'oldestHistoryDays',oldest_days,'openDebtMinor',open_debt,'recentNegativeEvents',recent_negative);
 INSERT INTO public.player_credit_scores(profile_id,credit_score,credit_band,positive_factors,negative_factors,calculation_version,factor_snapshot,calculated_from_event_date) VALUES(p_profile_id,score,CASE WHEN score>=760 THEN 'Excellent' WHEN score>=700 THEN 'Good' WHEN score>=620 THEN 'Fair' WHEN score>=520 THEN 'Poor' ELSE 'High Risk' END,jsonb_build_array('Capped payment history and older account age can improve this private score.'),CASE WHEN misses+collections+recent_negative>0 OR open_debt>0 THEN jsonb_build_array('Recent missed payments, collections and open debt reduce this private score.') ELSE '[]'::jsonb END,'phase8b6_weighted_v1',snap,(SELECT min(event_date) FROM public.player_credit_history WHERE profile_id=p_profile_id)) ON CONFLICT(profile_id) DO UPDATE SET credit_score=EXCLUDED.credit_score,credit_band=EXCLUDED.credit_band,positive_factors=EXCLUDED.positive_factors,negative_factors=EXCLUDED.negative_factors,calculation_version=EXCLUDED.calculation_version,factor_snapshot=EXCLUDED.factor_snapshot,calculated_from_event_date=EXCLUDED.calculated_from_event_date,calculated_at=timezone('utc',now());
 RETURN score;
END $$;
CREATE OR REPLACE FUNCTION public.recalculate_player_credit_score(p_profile_id uuid) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service role required' USING ERRCODE='42501'; END IF; RETURN public.recalculate_player_credit_score_internal(p_profile_id); END $$;

CREATE OR REPLACE FUNCTION public.process_financial_obligation_payment_internal(p_schedule_id uuid,p_idempotency_key text,p_as_of_date date DEFAULT CURRENT_DATE,p_as_of_timestamp timestamptz DEFAULT timezone('utc',now())) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE s public.financial_obligation_schedule; o public.financial_obligations; payer public.financial_accounts; recip public.financial_accounts; tx uuid; attempts int; shortfall bigint; next_due date; debt uuid; res jsonb;
BEGIN
 SELECT * INTO s FROM public.financial_obligation_schedule WHERE id=p_schedule_id FOR UPDATE; IF s.id IS NULL THEN RAISE EXCEPTION 'schedule not found'; END IF;
 SELECT * INTO o FROM public.financial_obligations WHERE id=s.obligation_id FOR UPDATE; SELECT * INTO payer FROM public.financial_accounts WHERE id=o.payment_account_id FOR UPDATE; SELECT * INTO recip FROM public.financial_accounts WHERE id=o.recipient_account_id FOR UPDATE;
 IF s.status='paid' THEN RETURN jsonb_build_object('status','already_paid'); END IF;
 IF s.next_retry_at IS NOT NULL AND s.next_retry_at>p_as_of_timestamp THEN RETURN jsonb_build_object('status','retry_not_due','nextRetryAt',s.next_retry_at); END IF;
 SELECT count(*)+1 INTO attempts FROM public.financial_obligation_attempts WHERE schedule_id=s.id;
 shortfall:=GREATEST(0,s.amount_minor-COALESCE(payer.available_balance_minor,0));
 IF payer.id IS NULL OR payer.account_status<>'active' OR payer.owner_type::text<>o.owner_type OR payer.owner_id<>o.owner_id OR payer.default_currency_code<>o.currency_code OR recip.id IS NULL OR recip.account_status<>'active' OR recip.default_currency_code<>o.currency_code OR shortfall>0 THEN
  INSERT INTO public.financial_obligation_attempts(obligation_id,schedule_id,attempt_number,status,failure_reason,balance_at_attempt_minor,remaining_shortfall_minor,idempotency_key,attempted_at,metadata) VALUES(o.id,s.id,attempts,'failed',CASE WHEN payer.id IS NULL THEN 'missing_payment_account' WHEN payer.owner_type::text<>o.owner_type OR payer.owner_id<>o.owner_id THEN 'payment_account_owner_mismatch' WHEN payer.default_currency_code<>o.currency_code OR COALESCE(recip.default_currency_code,o.currency_code)<>o.currency_code THEN 'currency_mismatch' WHEN COALESCE(payer.account_status::text,'missing')<>'active' OR COALESCE(recip.account_status::text,'missing')<>'active' THEN 'inactive_account' ELSE 'insufficient_funds' END,COALESCE(payer.available_balance_minor,0),shortfall,p_idempotency_key,p_as_of_timestamp,jsonb_build_object('as_of_date',p_as_of_date)) ON CONFLICT DO NOTHING;
  UPDATE public.financial_obligation_schedule SET status=CASE WHEN p_as_of_date<=grace_expires_at THEN 'missed' ELSE 'failed' END, first_missed_at=COALESCE(first_missed_at,p_as_of_timestamp), last_attempted_at=p_as_of_timestamp, next_retry_at=p_as_of_timestamp + make_interval(days=>o.retry_interval_days) WHERE id=s.id;
  IF o.owner_type='player' THEN INSERT INTO public.player_credit_history(profile_id,event_type,obligation_id,amount_minor,currency_code,score_delta,private_metadata,event_date) VALUES(o.owner_id,'missed_payment',o.id,s.amount_minor,o.currency_code,-20,jsonb_build_object('schedule_id',s.id),p_as_of_date) ON CONFLICT DO NOTHING; PERFORM public.recalculate_player_credit_score_internal(o.owner_id); END IF;
  IF attempts>=o.max_attempts OR p_as_of_date>s.grace_expires_at THEN INSERT INTO public.debt_records(obligation_id,schedule_id,owner_type,owner_id,original_amount_minor,outstanding_balance_minor,currency_code,metadata) VALUES(o.id,s.id,o.owner_type,o.owner_id,s.amount_minor,s.amount_minor,o.currency_code,jsonb_build_object('schedule_id',s.id)) ON CONFLICT (obligation_id,schedule_id) WHERE status='open' DO UPDATE SET outstanding_balance_minor=GREATEST(public.debt_records.outstanding_balance_minor,EXCLUDED.outstanding_balance_minor),updated_at=p_as_of_timestamp RETURNING id INTO debt; PERFORM public.record_financial_obligation_event_internal(o.id,'debt_created',jsonb_build_object('debt_id',debt,'schedule_id',s.id)); IF o.owner_type='player' THEN INSERT INTO public.player_credit_history(profile_id,event_type,obligation_id,debt_id,amount_minor,currency_code,score_delta,event_date,private_metadata) VALUES(o.owner_id,'collection',o.id,debt,s.amount_minor,o.currency_code,-60,p_as_of_date,jsonb_build_object('schedule_id',s.id)) ON CONFLICT DO NOTHING; END IF; END IF;
  PERFORM public.reconcile_financial_obligation_state(o.id,p_as_of_date); RETURN jsonb_build_object('status','failed','shortfallMinor',shortfall,'attempt',attempts,'nextRetryAt',p_as_of_timestamp + make_interval(days=>o.retry_interval_days));
 END IF;
 IF s.source_schedule_type='mortgage_schedule_line' THEN res:=public.post_mortgage_schedule_payment(s.source_schedule_id,p_idempotency_key||'-mortgage-accounting'); tx:=(res->>'transactionId')::uuid; ELSE tx:=public.post_financial_journal('financial_obligation_payment',gen_random_uuid(),o.currency_code,p_idempotency_key,jsonb_build_array(jsonb_build_object('account_id',o.payment_account_id,'direction','debit','amount_minor',s.amount_minor),jsonb_build_object('account_id',o.recipient_account_id,'direction','credit','amount_minor',s.amount_minor)),'financial_obligation_schedule',s.id,jsonb_build_object('trusted_finance_workflow',true,'obligation_id',o.id,'accounting_strategy',o.accounting_strategy)); END IF;
 INSERT INTO public.financial_obligation_attempts(obligation_id,schedule_id,attempt_number,status,balance_at_attempt_minor,transaction_id,idempotency_key,attempted_at) VALUES(o.id,s.id,attempts,'succeeded',payer.available_balance_minor,tx,p_idempotency_key,p_as_of_timestamp) ON CONFLICT DO NOTHING;
 UPDATE public.financial_obligation_schedule SET status='paid',transaction_id=tx,paid_at=p_as_of_timestamp,last_attempted_at=p_as_of_timestamp,resolved_at=COALESCE(resolved_at,p_as_of_timestamp),next_retry_at=NULL WHERE id=s.id;
 UPDATE public.debt_records SET outstanding_balance_minor=0,status='settled',collection_stage='settled',updated_at=p_as_of_timestamp WHERE schedule_id=s.id AND status='open' RETURNING id INTO debt;
 IF debt IS NOT NULL THEN INSERT INTO public.debt_collection_events(debt_id,previous_stage,new_stage,notes,created_at) VALUES(debt,NULL,'settled','Debt settled by obligation payment',p_as_of_timestamp); PERFORM public.record_financial_obligation_event_internal(o.id,'debt_escalated',jsonb_build_object('debt_id',debt,'schedule_id',s.id)); END IF;
 SELECT min(due_date) INTO next_due FROM public.financial_obligation_schedule WHERE obligation_id=o.id AND status IN ('scheduled','due','missed','failed');
 UPDATE public.financial_obligations SET linked_finance_transaction_id=tx,updated_at=p_as_of_timestamp WHERE id=o.id;
 IF o.owner_type='player' THEN INSERT INTO public.player_credit_history(profile_id,event_type,obligation_id,debt_id,amount_minor,currency_code,score_delta,event_date,private_metadata) VALUES(o.owner_id,CASE WHEN s.first_missed_at IS NULL THEN 'successful_payment'::public.player_credit_event_type ELSE 'debt_settlement'::public.player_credit_event_type END,o.id,debt,s.amount_minor,o.currency_code,CASE WHEN s.first_missed_at IS NULL THEN 2 ELSE 8 END,p_as_of_date,jsonb_build_object('schedule_id',s.id)) ON CONFLICT DO NOTHING; PERFORM public.recalculate_player_credit_score_internal(o.owner_id); END IF;
 PERFORM public.reconcile_financial_obligation_state(o.id,p_as_of_date); PERFORM public.record_financial_obligation_event_internal(o.id,'payment_succeeded',jsonb_build_object('schedule_id',s.id,'transaction_id',tx));
 RETURN jsonb_build_object('status','posted','transactionId',tx,'nextDueDate',next_due);
END $$;
CREATE OR REPLACE FUNCTION public.process_financial_obligation_payment(p_schedule_id uuid,p_idempotency_key text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service role required' USING ERRCODE='42501'; END IF; RETURN public.process_financial_obligation_payment_internal(p_schedule_id,p_idempotency_key,CURRENT_DATE,timezone('utc',now())); END $$;
CREATE OR REPLACE FUNCTION public.retry_my_financial_obligation_payment(p_schedule_id uuid,p_idempotency_key text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE pid uuid:=public.current_player_profile_id(); BEGIN IF pid IS NULL THEN RAISE EXCEPTION 'profile required'; END IF; IF NOT EXISTS (SELECT 1 FROM public.financial_obligation_schedule s JOIN public.financial_obligations o ON o.id=s.obligation_id WHERE s.id=p_schedule_id AND o.owner_type='player' AND o.owner_id=pid) THEN RAISE EXCEPTION 'schedule not found or not owned by current player' USING ERRCODE='42501'; END IF; RETURN public.process_financial_obligation_payment_internal(p_schedule_id,p_idempotency_key,CURRENT_DATE,timezone('utc',now())); END $$;

CREATE OR REPLACE FUNCTION public.process_due_financial_obligations(p_as_of_date date DEFAULT CURRENT_DATE,p_limit int DEFAULT 100) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE r record; res jsonb; attempted int:=0; posted int:=0; failed int:=0; skipped int:=0; errored int:=0; details jsonb:='[]'::jsonb; BEGIN IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service role required' USING ERRCODE='42501'; END IF; FOR r IN SELECT s.id FROM public.financial_obligation_schedule s JOIN public.financial_obligations o ON o.id=s.obligation_id WHERE o.status IN ('active','grace_period','retrying','failed') AND s.status IN ('scheduled','due','missed','failed') AND s.due_date<=p_as_of_date AND (s.next_retry_at IS NULL OR s.next_retry_at<=p_as_of_date::timestamptz) ORDER BY s.due_date LIMIT p_limit FOR UPDATE SKIP LOCKED LOOP attempted:=attempted+1; BEGIN res:=public.process_financial_obligation_payment_internal(r.id,'obligation-auto-'||r.id||'-'||p_as_of_date,p_as_of_date,p_as_of_date::timestamptz); IF res->>'status'='posted' THEN posted:=posted+1; ELSIF res->>'status'='retry_not_due' THEN skipped:=skipped+1; ELSE failed:=failed+1; END IF; details:=details||jsonb_build_array(jsonb_build_object('scheduleId',r.id,'result',res)); EXCEPTION WHEN OTHERS THEN errored:=errored+1; INSERT INTO public.financial_obligation_events(event_type,event_payload) VALUES('admin_adjusted',jsonb_build_object('schedule_id',r.id,'error',SQLERRM,'as_of_date',p_as_of_date)); END; END LOOP; RETURN jsonb_build_object('attempted',attempted,'posted',posted,'failed',failed,'skipped',skipped,'errored',errored,'details',details); END $$;

CREATE OR REPLACE FUNCTION public.get_my_private_credit_profile() RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT jsonb_build_object('score',s.credit_score,'band',s.credit_band,'lastCalculatedAt',s.calculated_at,'positiveFactors',s.positive_factors,'negativeFactors',s.negative_factors,'history',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',h.id,'eventType',h.event_type,'eventDate',h.event_date,'amountMinor',h.amount_minor,'currencyCode',h.currency_code,'scoreDelta',h.score_delta) ORDER BY h.event_date DESC) FROM public.player_credit_history h WHERE h.profile_id=public.current_player_profile_id()),'[]'::jsonb)) FROM public.player_credit_scores s WHERE s.profile_id=public.current_player_profile_id() $$;
CREATE OR REPLACE FUNCTION public.get_my_financial_obligations_dashboard() RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT jsonb_build_object(
 'obligations',COALESCE((SELECT jsonb_agg(to_jsonb(o) ORDER BY o.next_due_date) FROM (SELECT id,obligation_type,owner_type,owner_id,linked_asset_type,linked_asset_id,amount_minor,currency_code,frequency,next_due_date,grace_period_days,status,missed_payment_count,outstanding_balance_minor FROM public.financial_obligations WHERE owner_type='player' AND owner_id=public.current_player_profile_id() LIMIT 50) o),'[]'::jsonb),
 'schedule',COALESCE((SELECT jsonb_agg(to_jsonb(s) ORDER BY s.due_date) FROM (SELECT s.id,s.obligation_id,s.due_date,s.amount_minor,o.currency_code,s.status,s.paid_at,s.first_missed_at,s.next_retry_at,s.resolved_at FROM public.financial_obligation_schedule s JOIN public.financial_obligations o ON o.id=s.obligation_id WHERE o.owner_type='player' AND o.owner_id=public.current_player_profile_id() AND s.status IN ('scheduled','due','missed','failed','paid') LIMIT 100) s),'[]'::jsonb),
 'debts',COALESCE((SELECT jsonb_agg(to_jsonb(d) ORDER BY d.updated_at DESC) FROM (SELECT id,obligation_id,schedule_id,original_amount_minor,outstanding_balance_minor,currency_code,collection_stage,status,updated_at FROM public.debt_records WHERE owner_type='player' AND owner_id=public.current_player_profile_id() LIMIT 25) d),'[]'::jsonb),
 'creditProfile',public.get_my_private_credit_profile()) $$;

CREATE OR REPLACE FUNCTION public.preview_band_expense_funding(p_band_id uuid,p_expense_type text,p_expense_id uuid,p_amount_minor bigint,p_currency_code char,p_requested_payment_source text,p_personal_bank_account_id uuid DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE pid uuid:=public.current_player_profile_id(); treasury uuid; band_bal bigint:=0; ba public.bank_accounts; fa public.financial_accounts; personal_bal bigint:=0; band_part bigint:=0; personal_part bigint:=0; can_use_band boolean; is_member boolean;
BEGIN
 IF pid IS NULL THEN RAISE EXCEPTION 'profile required'; END IF; IF p_amount_minor<=0 THEN RAISE EXCEPTION 'amount must be positive'; END IF; IF p_requested_payment_source NOT IN ('band_only','personal_only','band_then_personal_shortfall') THEN RAISE EXCEPTION 'unsupported payment source'; END IF;
 is_member:=EXISTS(SELECT 1 FROM public.band_members WHERE band_id=p_band_id AND profile_id=pid AND COALESCE(member_status,'active')='active'); can_use_band:=public.user_has_band_finance_permission(p_band_id,pid,'pay_band_expenses'::public.band_finance_permission);
 treasury:=public.get_or_create_band_treasury_account(p_band_id,p_currency_code); SELECT available_balance_minor INTO band_bal FROM public.financial_accounts WHERE id=treasury;
 IF p_personal_bank_account_id IS NOT NULL THEN SELECT * INTO ba FROM public.bank_accounts WHERE id=p_personal_bank_account_id; SELECT * INTO fa FROM public.financial_accounts WHERE id=ba.linked_finance_account_id; IF ba.owner_type='player' AND ba.owner_id=pid AND ba.status='active' AND fa.account_status='active' AND ba.currency_code=p_currency_code THEN personal_bal:=fa.available_balance_minor; END IF; END IF;
 IF p_requested_payment_source='band_only' THEN band_part:=LEAST(p_amount_minor,band_bal); personal_part:=0; ELSIF p_requested_payment_source='personal_only' THEN band_part:=0; personal_part:=p_amount_minor; ELSE band_part:=LEAST(p_amount_minor,band_bal); personal_part:=p_amount_minor-band_part; END IF;
 RETURN jsonb_build_object('status',CASE WHEN NOT is_member THEN 'permission_denied' WHEN band_part>0 AND NOT can_use_band THEN 'permission_denied' WHEN p_requested_payment_source='band_only' AND band_bal<p_amount_minor THEN 'insufficient_band_funds' WHEN personal_part>0 AND personal_bal<personal_part THEN 'insufficient_personal_funds' ELSE 'ready' END,'totalAmountMinor',p_amount_minor,'bandAvailableMinor',band_bal,'shortfallMinor',GREATEST(0,p_amount_minor-band_bal),'currencyCode',p_currency_code,'personalPaymentEligible',is_member AND p_personal_bank_account_id IS NOT NULL,'bandFundedAmountMinor',band_part,'personalAmountMinor',personal_part,'personalAvailableBalanceMinor',personal_bal,'resultingBandBalanceMinor',band_bal-band_part,'resultingPersonalBalanceMinor',personal_bal-personal_part,'permission',jsonb_build_object('member',is_member,'useBandFunds',can_use_band));
END $$;

CREATE OR REPLACE FUNCTION public.resolve_and_pay_band_expense(p_band_id uuid,p_expense_type text,p_expense_id uuid,p_destination_account_id uuid,p_amount_minor bigint,p_currency_code char,p_requested_payment_source text,p_personal_bank_account_id uuid,p_initiating_player_id uuid,p_idempotency_key text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE preview jsonb; treasury uuid; ba public.bank_accounts; personal uuid; band_part bigint; personal_part bigint; tx uuid; payment uuid; component uuid; cid uuid;
BEGIN
 IF p_initiating_player_id<>public.current_player_profile_id() AND auth.role()<>'service_role' THEN RAISE EXCEPTION 'initiating player mismatch'; END IF;
 SELECT id INTO payment FROM public.band_expense_payments WHERE idempotency_key=p_idempotency_key; IF payment IS NOT NULL THEN RETURN jsonb_build_object('status','already_posted','paymentId',payment); END IF;
 preview:=public.preview_band_expense_funding(p_band_id,p_expense_type,p_expense_id,p_amount_minor,p_currency_code,p_requested_payment_source,p_personal_bank_account_id); IF preview->>'status'<>'ready' THEN RETURN preview; END IF;
 band_part:=(preview->>'bandFundedAmountMinor')::bigint; personal_part:=(preview->>'personalAmountMinor')::bigint; treasury:=public.get_or_create_band_treasury_account(p_band_id,p_currency_code); SELECT * INTO ba FROM public.bank_accounts WHERE id=p_personal_bank_account_id FOR UPDATE; personal:=ba.linked_finance_account_id;
 tx:=public.post_financial_journal('band_expense',gen_random_uuid(),p_currency_code,p_idempotency_key,(CASE WHEN band_part>0 THEN jsonb_build_array(jsonb_build_object('account_id',treasury,'direction','debit','amount_minor',band_part)) ELSE '[]'::jsonb END) || (CASE WHEN personal_part>0 THEN jsonb_build_array(jsonb_build_object('account_id',personal,'direction','debit','amount_minor',personal_part)) ELSE '[]'::jsonb END) || jsonb_build_array(jsonb_build_object('account_id',p_destination_account_id,'direction','credit','amount_minor',p_amount_minor)),'band_expense',p_expense_id,jsonb_build_object('trusted_finance_workflow',true,'band_id',p_band_id,'expense_type',p_expense_type,'personal_charge_explicit',personal_part>0));
 INSERT INTO public.band_expense_payments(band_id,expense_type,expense_id,destination_account_id,total_amount_minor,currency_code,status,initiating_player_id,transaction_id,idempotency_key,metadata) VALUES(p_band_id,p_expense_type,p_expense_id,p_destination_account_id,p_amount_minor,p_currency_code,'completed',p_initiating_player_id,tx,p_idempotency_key,jsonb_build_object('requested_payment_source',p_requested_payment_source)) RETURNING id INTO payment;
 IF band_part>0 THEN INSERT INTO public.band_expense_payment_components(payment_id,component_type,source_account_id,amount_minor,transaction_id) VALUES(payment,'band_treasury',treasury,band_part,tx); END IF;
 IF personal_part>0 THEN INSERT INTO public.band_expense_payment_components(payment_id,component_type,source_account_id,contributor_player_id,amount_minor,transaction_id) VALUES(payment,'personal_player',personal,p_initiating_player_id,personal_part,tx) RETURNING id INTO component; INSERT INTO public.band_financial_contributions(band_id,contributing_player_id,source_player_account_id,destination_band_treasury_account_id,amount_minor,currency_code,transaction_id,contribution_type,related_expense_type,related_expense_id,idempotency_key,notes) VALUES(p_band_id,p_initiating_player_id,personal,treasury,personal_part,p_currency_code,tx,CASE WHEN band_part=0 THEN 'full_expense_payment' ELSE 'expense_shortfall' END,p_expense_type,p_expense_id,p_idempotency_key||'-contribution','Personal funding of band expense') RETURNING id INTO cid; END IF;
 RETURN jsonb_build_object('status','posted','paymentId',payment,'transactionId',tx,'bandAmountMinor',band_part,'personalAmountMinor',personal_part,'contributionId',cid);
END $$;
CREATE OR REPLACE FUNCTION public.confirm_band_expense_funding(p_band_id uuid,p_expense_type text,p_expense_id uuid,p_destination_account_id uuid,p_amount_minor bigint,p_currency_code char,p_requested_payment_source text,p_personal_bank_account_id uuid,p_idempotency_key text) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT public.resolve_and_pay_band_expense(p_band_id,p_expense_type,p_expense_id,p_destination_account_id,p_amount_minor,p_currency_code,p_requested_payment_source,p_personal_bank_account_id,public.current_player_profile_id(),p_idempotency_key) $$;

CREATE OR REPLACE FUNCTION public.progress_financial_debt_collections(p_as_of_date date DEFAULT CURRENT_DATE,p_limit int DEFAULT 100) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE d record; new_stage public.debt_collection_stage; progressed int:=0; BEGIN IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'service role required'; END IF; FOR d IN SELECT * FROM public.debt_records WHERE status='open' ORDER BY stage_entered_at LIMIT p_limit FOR UPDATE SKIP LOCKED LOOP new_stage:=CASE WHEN p_as_of_date>=d.created_at::date+60 THEN 'asset_recovery' WHEN p_as_of_date>=d.created_at::date+35 THEN 'legal_action' WHEN p_as_of_date>=d.created_at::date+21 THEN 'collections' WHEN p_as_of_date>=d.created_at::date+14 THEN 'final_notice' WHEN p_as_of_date>=d.created_at::date+7 THEN 'late_notice' ELSE 'friendly_reminder' END; IF new_stage<>d.collection_stage THEN UPDATE public.debt_records SET collection_stage=new_stage,stage_entered_at=p_as_of_date::timestamptz,updated_at=timezone('utc',now()) WHERE id=d.id; INSERT INTO public.debt_collection_events(debt_id,previous_stage,new_stage,notes) VALUES(d.id,d.collection_stage,new_stage,'Automated policy progression'); progressed:=progressed+1; END IF; END LOOP; RETURN jsonb_build_object('progressed',progressed); END $$;

REVOKE EXECUTE ON FUNCTION public.record_financial_obligation_event(uuid,public.financial_obligation_event_type,jsonb), public.set_financial_obligation_status(uuid,public.financial_obligation_status,text), public.recalculate_player_credit_score(uuid), public.process_financial_obligation_payment(uuid,text), public.create_financial_obligation_from_mortgage(uuid), public.process_due_financial_obligations(date,int), public.process_due_mortgage_repayments(date,int), public.reconcile_financial_obligation_state(uuid,date), public.record_financial_obligation_event_internal(uuid,public.financial_obligation_event_type,jsonb), public.recalculate_player_credit_score_internal(uuid), public.process_financial_obligation_payment_internal(uuid,text,date,timestamptz), public.progress_financial_debt_collections(date,int) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_financial_obligation_event(uuid,public.financial_obligation_event_type,jsonb), public.set_financial_obligation_status(uuid,public.financial_obligation_status,text), public.recalculate_player_credit_score(uuid), public.process_financial_obligation_payment(uuid,text), public.create_financial_obligation_from_mortgage(uuid), public.process_due_financial_obligations(date,int), public.process_due_mortgage_repayments(date,int), public.reconcile_financial_obligation_state(uuid,date), public.record_financial_obligation_event_internal(uuid,public.financial_obligation_event_type,jsonb), public.recalculate_player_credit_score_internal(uuid), public.process_financial_obligation_payment_internal(uuid,text,date,timestamptz), public.progress_financial_debt_collections(date,int) TO service_role;
GRANT EXECUTE ON FUNCTION public.retry_my_financial_obligation_payment(uuid,text), public.get_my_private_credit_profile(), public.get_my_financial_obligations_dashboard(), public.preview_band_expense_funding(uuid,text,uuid,bigint,char,text,uuid), public.confirm_band_expense_funding(uuid,text,uuid,uuid,bigint,char,text,uuid,text) TO authenticated;
