
-- Add hype_score to releases
ALTER TABLE public.releases ADD COLUMN IF NOT EXISTS hype_score integer DEFAULT 0;

-- Release party questions table
CREATE TABLE public.release_party_questions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  question_text text NOT NULL,
  party_context text[] DEFAULT '{all}',
  category text NOT NULL,
  option_a_text text NOT NULL,
  option_a_effects jsonb NOT NULL DEFAULT '{}',
  option_b_text text NOT NULL,
  option_b_effects jsonb NOT NULL DEFAULT '{}',
  option_c_text text NOT NULL,
  option_c_effects jsonb NOT NULL DEFAULT '{}',
  option_d_text text NOT NULL,
  option_d_effects jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.release_party_questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read release party questions" ON public.release_party_questions FOR SELECT USING (true);

-- Release party results table
CREATE TABLE public.release_party_results (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  release_id uuid REFERENCES public.releases(id) NOT NULL,
  user_id uuid REFERENCES auth.users(id) NOT NULL,
  band_id uuid REFERENCES public.bands(id),
  questions jsonb NOT NULL DEFAULT '[]',
  total_effects jsonb NOT NULL DEFAULT '{}',
  hype_awarded integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  UNIQUE(release_id)
);

ALTER TABLE public.release_party_results ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read own release party results" ON public.release_party_results FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own release party results" ON public.release_party_results FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Seed 100 release party questions (20 per category)

-- CATEGORY: Fan Interaction (20)
INSERT INTO public.release_party_questions (question_text, category, party_context, option_a_text, option_a_effects, option_b_text, option_b_effects, option_c_text, option_c_effects, option_d_text, option_d_effects) VALUES
('A superfan asks you to sign their tattoo of your lyrics. What do you do?', 'fan_interaction', '{all}', 'Sign it proudly and take a photo together', '{"hype_mult":1.3,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Politely decline but offer a signed poster instead', '{"hype_mult":1.0,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"professional":1}}', 'Make a big scene about it for social media', '{"hype_mult":1.4,"fan_mult":0.9,"cash_mult":1.1,"reputation":{"controversial":2}}', 'Ignore them and walk away', '{"hype_mult":0.6,"fan_mult":0.5,"cash_mult":1.0,"reputation":{"authentic":-2}}'),
('Fans are chanting for you to play a snippet of the new release. Do you?', 'fan_interaction', '{all}', 'Play the chorus acoustic right there', '{"hype_mult":1.5,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Tease it by humming a few bars', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"mysterious":1}}', 'Tell them to wait for the official release', '{"hype_mult":0.9,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"professional":1}}', 'Start a freestyle instead', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"creative":1}}'),
('A young fan tells you your music saved their life. How do you respond?', 'fan_interaction', '{all}', 'Hug them and share a heartfelt moment', '{"hype_mult":1.2,"fan_mult":1.5,"cash_mult":1.0,"reputation":{"authentic":3}}', 'Thank them professionally and move on', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Invite them backstage to chat more', '{"hype_mult":1.3,"fan_mult":1.4,"cash_mult":0.9,"reputation":{"authentic":2}}', 'Use it as a speech moment for the crowd', '{"hype_mult":1.4,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"controversial":1}}'),
('Someone in the crowd is holding up a sign asking you to dedicate a song to them.', 'fan_interaction', '{all}', 'Read the sign aloud and dedicate the next track', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Give them a thumbs up but keep going', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Invite them on stage for a moment', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creative":1}}', 'Pretend you didnt see it', '{"hype_mult":0.7,"fan_mult":0.6,"cash_mult":1.0,"reputation":{"authentic":-1}}'),
('A fan asks if they can film the entire release party for their channel.', 'fan_interaction', '{all}', 'Allow it — free publicity!', '{"hype_mult":1.4,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Allow clips only, not the full thing', '{"hype_mult":1.2,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Say no — keep it exclusive', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":1.1,"reputation":{"mysterious":2}}', 'Only if they pay a licensing fee', '{"hype_mult":0.9,"fan_mult":0.7,"cash_mult":1.3,"reputation":{"professional":1}}'),
('Fans start a mosh pit at the release party. Its getting intense!', 'fan_interaction', '{all}', 'Jump in and crowd surf', '{"hype_mult":1.5,"fan_mult":1.3,"cash_mult":0.9,"reputation":{"authentic":2}}', 'Encourage it from stage safely', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creative":1}}', 'Ask security to calm things down', '{"hype_mult":0.8,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"professional":1}}', 'Stop the music until everyone chills', '{"hype_mult":0.6,"fan_mult":0.5,"cash_mult":1.0,"reputation":{"professional":1}}'),
('A fan gifts you handmade artwork inspired by your upcoming release.', 'fan_interaction', '{all}', 'Display it at the party and thank them publicly', '{"hype_mult":1.3,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Accept it graciously backstage', '{"hype_mult":1.0,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"professional":1}}', 'Post it on social media right now', '{"hype_mult":1.4,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"accessible":1}}', 'Leave it on the table', '{"hype_mult":0.6,"fan_mult":0.5,"cash_mult":1.0,"reputation":{"authentic":-2}}'),
('Someone asks you to do a Q&A session with the crowd.', 'fan_interaction', '{all}', 'Sure, open mic for 10 minutes', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Take 3 pre-selected questions only', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":2}}', 'Do it live on social media too', '{"hype_mult":1.5,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Decline — the music speaks for itself', '{"hype_mult":0.8,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"mysterious":2}}'),
('A group of fans starts singing one of your older songs at the party.', 'fan_interaction', '{all}', 'Join in and sing along with them', '{"hype_mult":1.4,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Smile and let them have their moment', '{"hype_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"professional":1}}', 'Redirect them to the new material', '{"hype_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"professional":1}}', 'Tell them this party is about the new stuff only', '{"hype_mult":0.7,"fan_mult":0.6,"cash_mult":1.0,"reputation":{"authentic":-1}}'),
('A fan is crying tears of joy meeting you. The moment is caught on camera.', 'fan_interaction', '{all}', 'Comfort them and share the moment genuinely', '{"hype_mult":1.3,"fan_mult":1.5,"cash_mult":1.0,"reputation":{"authentic":3}}', 'Pose for a photo and move along', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Make sure the cameras get a good angle', '{"hype_mult":1.2,"fan_mult":0.8,"cash_mult":1.1,"reputation":{"controversial":1}}', 'Get uncomfortable and ask them to stop', '{"hype_mult":0.6,"fan_mult":0.5,"cash_mult":1.0,"reputation":{"authentic":-1}}'),
('A fan offers to buy you a drink to celebrate the release.', 'fan_interaction', '{all}', 'Accept and toast to the new music together', '{"hype_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Decline politely — staying focused tonight', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Accept and buy the whole crowd a round', '{"hype_mult":1.5,"fan_mult":1.4,"cash_mult":0.7,"reputation":{"accessible":3}}', 'Only drink your own brand', '{"hype_mult":0.9,"fan_mult":0.8,"cash_mult":1.2,"reputation":{"professional":1}}'),
('Fans are requesting you play the full album right now before the release date.', 'fan_interaction', '{all}', 'Play the whole thing — surprise early listen!', '{"hype_mult":1.5,"fan_mult":1.4,"cash_mult":0.8,"reputation":{"authentic":2}}', 'Play just one unreleased track as a teaser', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creative":1}}', 'Tell them patience is a virtue', '{"hype_mult":0.9,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"mysterious":2}}', 'Start a countdown to the release date', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"professional":1}}'),
('A fan challenges you to a music trivia contest about your own discography.', 'fan_interaction', '{all}', 'Accept the challenge and have fun with it', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Let your bandmate do it instead', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Turn it into a crowd game with prizes', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":0.9,"reputation":{"creative":2}}', 'Say you dont remember your own songs', '{"hype_mult":0.8,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"controversial":1}}'),
('A fan asks for your autograph on their phone case.', 'fan_interaction', '{all}', 'Sign it with a personal message', '{"hype_mult":1.1,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":1}}', 'Sign it quickly and move on', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Offer to take a selfie instead', '{"hype_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":1}}', 'Tell them you dont do autographs', '{"hype_mult":0.6,"fan_mult":0.5,"cash_mult":1.0,"reputation":{"mysterious":1}}'),
('The crowd starts a wave at your release party!', 'fan_interaction', '{all}', 'Lead the wave from the stage', '{"hype_mult":1.4,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":1}}', 'Watch and enjoy the energy', '{"hype_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"professional":1}}', 'Start a different crowd activity', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":2}}', 'Ask them to settle down', '{"hype_mult":0.6,"fan_mult":0.5,"cash_mult":1.0,"reputation":{"professional":1}}'),
('A fan brought their baby wearing a tiny band t-shirt.', 'fan_interaction', '{all}', 'Take a photo and share it online', '{"hype_mult":1.3,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Smile and wave at the baby', '{"hype_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authentic":1}}', 'Sign the babys t-shirt', '{"hype_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Suggest this isnt a baby-friendly event', '{"hype_mult":0.7,"fan_mult":0.5,"cash_mult":1.0,"reputation":{"controversial":1}}'),
('Fans made a fan-edit video of your music and want to show it at the party.', 'fan_interaction', '{all}', 'Play it on the big screen for everyone', '{"hype_mult":1.4,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Watch it privately and give feedback', '{"hype_mult":1.0,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authentic":1}}', 'Ask them to post it online instead', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Tell them to take it down — copyright issues', '{"hype_mult":0.5,"fan_mult":0.4,"cash_mult":1.0,"reputation":{"authentic":-2}}'),
('A fan proposes to their partner at your release party!', 'fan_interaction', '{all}', 'Stop everything and celebrate with them', '{"hype_mult":1.5,"fan_mult":1.5,"cash_mult":1.0,"reputation":{"authentic":3}}', 'Play a love song as backdrop', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"creative":2}}', 'Acknowledge it briefly and continue', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Feel upstaged and get annoyed', '{"hype_mult":0.5,"fan_mult":0.4,"cash_mult":1.0,"reputation":{"controversial":-1}}'),
('Someone in the crowd has a sign saying "We waited 2 years for this!"', 'fan_interaction', '{all}', 'Acknowledge it and promise it was worth the wait', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Read it aloud and laugh about it', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"accessible":1}}', 'Apologize for the long wait', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"authentic":1}}', 'Ignore it — no negative energy tonight', '{"hype_mult":0.8,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"professional":1}}'),

-- CATEGORY: Media Spotlight (20)
('A journalist asks what inspired this release. Your honest answer might be controversial.', 'media_spotlight', '{all}', 'Tell the raw, unfiltered truth', '{"hype_mult":1.4,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authentic":3,"controversial":1}}', 'Give a diplomatic, polished answer', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":2}}', 'Deflect with humor', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":1}}', 'Say no comment', '{"hype_mult":0.7,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"mysterious":2}}'),
('A music blogger wants an exclusive track premiere on their site.', 'media_spotlight', '{all}', 'Give them a full exclusive premiere', '{"hype_mult":1.5,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Offer a 30-second clip only', '{"hype_mult":1.2,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Decline — release it everywhere simultaneously', '{"hype_mult":0.9,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"professional":1}}', 'Ask for payment for the exclusive', '{"hype_mult":0.8,"fan_mult":0.7,"cash_mult":1.3,"reputation":{"professional":1}}'),
('A photographer wants candid shots backstage before the party starts.', 'media_spotlight', '{all}', 'Let them capture everything — raw and real', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Allow posed shots only', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":2}}', 'Grant access but approve all photos first', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'No backstage access for anyone', '{"hype_mult":0.7,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"mysterious":2}}'),
('A TV crew wants to film a mini-documentary about your release.', 'media_spotlight', '{all}', 'Give them full access for a week', '{"hype_mult":1.5,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"accessible":3}}', 'Allow one day of filming', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"professional":1}}', 'Only if you get final edit approval', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":2}}', 'Decline — too invasive', '{"hype_mult":0.7,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"mysterious":2}}'),
('A music critic who previously trashed your work wants an interview.', 'media_spotlight', '{all}', 'Welcome them — prove them wrong with the new music', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"professional":2}}', 'Confront them about their past review', '{"hype_mult":1.4,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"controversial":2}}', 'Politely decline the interview', '{"hype_mult":0.9,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Publicly call them out on social media', '{"hype_mult":1.5,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"controversial":3}}'),
('A podcast host asks you to rank your own albums live on air.', 'media_spotlight', '{all}', 'Rank them honestly — even if the new one isnt #1', '{"hype_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authentic":3}}', 'Say the new one is the best, obviously', '{"hype_mult":1.3,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Say you love them all equally', '{"hype_mult":0.9,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Turn it into a joke', '{"hype_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":1}}'),
('A rival artists fans are trolling your release party online. Media notices.', 'media_spotlight', '{all}', 'Rise above it and focus on your fans', '{"hype_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"professional":2}}', 'Clap back with a witty response', '{"hype_mult":1.4,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"controversial":1,"creative":1}}', 'Challenge the rival to a friendly collab', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":2}}', 'Get visibly upset about it', '{"hype_mult":0.7,"fan_mult":0.6,"cash_mult":1.0,"reputation":{"authentic":-1}}'),
('A journalist asks if the lyrics are about a specific person.', 'media_spotlight', '{all}', 'Confirm it and tell the story', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authentic":2,"controversial":1}}', 'Say its open to interpretation', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"mysterious":2}}', 'Deny it completely', '{"hype_mult":0.9,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"professional":1}}', 'Wink and say next question', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"mysterious":2}}'),
('A major music publication offers a cover story if you give them dirt on your label.', 'media_spotlight', '{all}', 'Take the cover and keep it professional', '{"hype_mult":1.3,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":2}}', 'Spill everything for the exposure', '{"hype_mult":1.5,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"controversial":3}}', 'Decline the offer entirely', '{"hype_mult":0.8,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Counter-offer with a different story angle', '{"hype_mult":1.2,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"creative":2}}'),
('Radio stations want you to call in live during their morning show.', 'media_spotlight', '{all}', 'Do multiple stations in one morning blitz', '{"hype_mult":1.5,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Pick one exclusive station', '{"hype_mult":1.2,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Send a pre-recorded message instead', '{"hype_mult":0.9,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"professional":1}}', 'Decline — you hate mornings', '{"hype_mult":0.7,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"authentic":1}}'),
('A music magazine wants to do a photo shoot with you for their release week feature.', 'media_spotlight', '{all}', 'Go all out with a creative concept shoot', '{"hype_mult":1.4,"fan_mult":1.1,"cash_mult":0.9,"reputation":{"creative":2}}', 'Keep it simple and professional', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Suggest a fan-involved shoot instead', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Send old press photos', '{"hype_mult":0.6,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"professional":-1}}'),
('A reporter asks about rumored tensions within your band.', 'media_spotlight', '{all}', 'Address it honestly and transparently', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Deny everything and change the subject', '{"hype_mult":0.9,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Make a joke to defuse the situation', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"creative":1}}', 'Walk out of the interview', '{"hype_mult":1.3,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"controversial":2}}'),
('A livestream of the party is getting thousands of viewers. Chat is going wild.', 'media_spotlight', '{all}', 'Interact with the chat live on camera', '{"hype_mult":1.5,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"accessible":3}}', 'Focus on the in-person crowd', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"authentic":1}}', 'Read out the funniest comments', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creative":1}}', 'Ask to shut down the stream', '{"hype_mult":0.5,"fan_mult":0.5,"cash_mult":1.0,"reputation":{"mysterious":1}}'),
('A famous music YouTuber is reviewing your release live at the party.', 'media_spotlight', '{all}', 'Watch their reaction and engage', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Give them an exclusive interview', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"professional":1}}', 'Let them do their thing independently', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Ask them not to post until release day', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"professional":1}}'),
('An entertainment news crew wants a quote about your biggest competitor.', 'media_spotlight', '{all}', 'Give a respectful, classy response', '{"hype_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"professional":2}}', 'Throw shade subtly', '{"hype_mult":1.4,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"controversial":2}}', 'Praise them genuinely', '{"hype_mult":1.0,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Refuse to acknowledge competitors', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"mysterious":1}}'),
('A music blog is live-tweeting their first listen of your release.', 'media_spotlight', '{all}', 'Retweet and engage with their reactions', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Let it play out organically', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Send them exclusive bonus content', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":0.9,"reputation":{"creative":1}}', 'Ask them to stop spoiling it', '{"hype_mult":0.6,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"professional":1}}'),
('A radio DJ asks you to freestyle over the phone right now.', 'media_spotlight', '{all}', 'Go for it — pure energy', '{"hype_mult":1.4,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"creative":2,"authentic":1}}', 'Do a modified version of a new song', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":1}}', 'Laugh and politely decline', '{"hype_mult":0.9,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"professional":1}}', 'Say freestyling isnt your style', '{"hype_mult":0.7,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"authentic":1}}'),
('Press asks if this release marks a new direction for your music.', 'media_spotlight', '{all}', 'Yes — explain the artistic evolution passionately', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":2}}', 'Its a natural progression, not a reinvention', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Say every release is its own journey', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"authentic":1}}', 'No comment on artistic direction', '{"hype_mult":0.7,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"mysterious":1}}'),
('A gossip site publishes a fake story about you right before the party.', 'media_spotlight', '{all}', 'Address it head-on with facts', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Ignore it completely', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Make fun of it publicly', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":1}}', 'Threaten legal action', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":0.9,"reputation":{"professional":1}}'),

-- CATEGORY: Party Vibes (20)
('The energy at the party is dying. What do you do?', 'party_vibes', '{all}', 'Jump on the DJ booth and hype the crowd', '{"hype_mult":1.5,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Start an impromptu acoustic set', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creative":2}}', 'Bring out surprise guest performers', '{"hype_mult":1.4,"fan_mult":1.1,"cash_mult":0.8,"reputation":{"creative":2}}', 'Let it wind down naturally', '{"hype_mult":0.7,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"professional":1}}'),
('Someone suggests doing shots with the whole crowd.', 'party_vibes', '{all}', 'Lead the toast and party hard', '{"hype_mult":1.4,"fan_mult":1.3,"cash_mult":0.8,"reputation":{"authentic":1}}', 'Toast with water — staying sharp', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Buy the whole venue a round', '{"hype_mult":1.5,"fan_mult":1.4,"cash_mult":0.6,"reputation":{"accessible":3}}', 'Decline — focus on the music', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"professional":2}}'),
('The venue wants to shut down early. The party is still going strong.', 'party_vibes', '{all}', 'Negotiate to keep it going another hour', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":0.8,"reputation":{"authentic":1}}', 'Move the party to a nearby spot', '{"hype_mult":1.4,"fan_mult":1.3,"cash_mult":0.7,"reputation":{"creative":2}}', 'Respect the venue rules and wrap up', '{"hype_mult":0.9,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"professional":2}}', 'Do an impromptu street performance outside', '{"hype_mult":1.5,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"authentic":2}}'),
('Confetti cannons or smoke machines — which do you choose for the big reveal?', 'party_vibes', '{all}', 'Both — go all out', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":0.7,"reputation":{"creative":2}}', 'Confetti — keep it fun and colorful', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":0.9,"reputation":{"creative":1}}', 'Smoke machines — dramatic effect', '{"hype_mult":1.3,"fan_mult":1.0,"cash_mult":0.9,"reputation":{"mysterious":1}}', 'Neither — let the music be the moment', '{"hype_mult":0.9,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"authentic":2}}'),
('The party DJ is playing your songs but the crowd wants different music.', 'party_vibes', '{all}', 'Let the DJ switch to crowd requests', '{"hype_mult":1.0,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Keep your music playing — its YOUR party', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"professional":1}}', 'Mix your tracks with popular hits', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"creative":2}}', 'Take over the DJ booth yourself', '{"hype_mult":1.4,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":1}}'),
('A food fight breaks out at the party. Cameras are rolling.', 'party_vibes', '{all}', 'Join in — legendary party moment!', '{"hype_mult":1.5,"fan_mult":1.2,"cash_mult":0.8,"reputation":{"controversial":1,"authentic":1}}', 'Dodge it and laugh it off', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":1}}', 'Shut it down immediately', '{"hype_mult":0.7,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"professional":2}}', 'Film it for social media content', '{"hype_mult":1.3,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"creative":1}}'),
('Power goes out at the venue mid-party!', 'party_vibes', '{all}', 'Lead an acoustic singalong by phone light', '{"hype_mult":1.5,"fan_mult":1.5,"cash_mult":1.0,"reputation":{"authentic":3}}', 'Wait patiently for it to come back', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"professional":1}}', 'Move the party outside', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creative":2}}', 'Cancel the rest of the event', '{"hype_mult":0.5,"fan_mult":0.4,"cash_mult":1.0,"reputation":{"professional":1}}'),
('Someone brought a piñata shaped like your album cover.', 'party_vibes', '{all}', 'Smash it open yourself — its amazing!', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Let the crowd take swings', '{"hype_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":1}}', 'Display it as art — too good to destroy', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"creative":1}}', 'Feel weird about people hitting your art', '{"hype_mult":0.7,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"authentic":1}}'),
('The afterparty is getting wilder than expected. People are taking videos.', 'party_vibes', '{all}', 'Keep the energy going — this is legendary', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":0.9,"reputation":{"authentic":1}}', 'Ask people to put phones away', '{"hype_mult":0.8,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"mysterious":2}}', 'Perform an exclusive afterparty-only song', '{"hype_mult":1.5,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"creative":2}}', 'Slip out quietly — protect your image', '{"hype_mult":0.7,"fan_mult":0.6,"cash_mult":1.0,"reputation":{"professional":1}}'),
('A karaoke machine appears at the party. Fans want you to sing someone elses song.', 'party_vibes', '{all}', 'Belt out a classic hit — full commitment', '{"hype_mult":1.4,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Sing a duet with a fan', '{"hype_mult":1.3,"fan_mult":1.5,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Only sing your own songs', '{"hype_mult":0.9,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"professional":1}}', 'Do a hilarious terrible rendition on purpose', '{"hype_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creative":1}}'),
('The party is so loud neighbors are complaining.', 'party_vibes', '{all}', 'Invite the neighbors to join the party', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Turn it down respectfully', '{"hype_mult":0.9,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"professional":2}}', 'Ignore them — its a release party!', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"controversial":1}}', 'Send them a signed album as an apology', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":0.9,"reputation":{"authentic":2}}'),
('Someone set up a photo booth with props themed around your album.', 'party_vibes', '{all}', 'Get in there and take silly photos with fans', '{"hype_mult":1.3,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Share the best ones on your social media', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":1}}', 'Think its a cool idea but stay out of it', '{"hype_mult":0.9,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"mysterious":1}}', 'Take it too seriously and pose dramatically', '{"hype_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"creative":1}}'),
('The party caterer made themed food based on your song titles.', 'party_vibes', '{all}', 'Post about it everywhere — so creative!', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":1}}', 'Thank the caterer on stage', '{"hype_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Try each dish and rate them publicly', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":1}}', 'You dont notice — too busy mingling', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"professional":1}}'),
('A spontaneous dance circle forms. Everyone is looking at you to start.', 'party_vibes', '{all}', 'Show off your best moves', '{"hype_mult":1.4,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Pull a fan in to dance with you', '{"hype_mult":1.3,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Watch and hype everyone else up', '{"hype_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"professional":1}}', 'Refuse — dancing isnt your thing', '{"hype_mult":0.7,"fan_mult":0.6,"cash_mult":1.0,"reputation":{"authentic":1}}'),
('Someone suggests a balloon drop for the midnight release moment.', 'party_vibes', '{all}', 'Absolutely — make it dramatic!', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":0.8,"reputation":{"creative":1}}', 'Add fireworks too', '{"hype_mult":1.5,"fan_mult":1.3,"cash_mult":0.6,"reputation":{"creative":2}}', 'A simple countdown is enough', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Skip the theatrics', '{"hype_mult":0.7,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"authentic":1}}'),
('The party playlist accidentally plays a rivals song.', 'party_vibes', '{all}', 'Laugh it off and sing along', '{"hype_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Quickly skip it to your music', '{"hype_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"professional":1}}', 'Leave it — good music is good music', '{"hype_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authentic":1}}', 'Get annoyed and call out the DJ', '{"hype_mult":0.7,"fan_mult":0.6,"cash_mult":1.0,"reputation":{"controversial":1}}'),
('Fans want to do a group photo with everyone at the party.', 'party_vibes', '{all}', 'Organize it and get the whole crowd together', '{"hype_mult":1.3,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Join a smaller group shot', '{"hype_mult":1.0,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"professional":1}}', 'Get a drone shot from above', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":0.9,"reputation":{"creative":2}}', 'Decline — too chaotic', '{"hype_mult":0.7,"fan_mult":0.6,"cash_mult":1.0,"reputation":{"mysterious":1}}'),
('The release party is trending on social media!', 'party_vibes', '{all}', 'Post more content to fuel the trend', '{"hype_mult":1.5,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Let it grow organically', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"professional":1}}', 'Go live and interact with online fans', '{"hype_mult":1.4,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"accessible":2}}', 'You dont care about social media', '{"hype_mult":0.7,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"authentic":1}}'),
('Someone brings sparklers for everyone at the release countdown.', 'party_vibes', '{all}', 'Light them all and create a magical moment', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":0.9,"reputation":{"creative":2}}', 'Safety first — check with the venue', '{"hype_mult":0.9,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"professional":2}}', 'Only a few for the stage performance', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Too dangerous — no fire at the party', '{"hype_mult":0.7,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"professional":1}}'),

-- CATEGORY: Industry Talk (20)
('A label exec at the party says your release could be bigger with their backing.', 'industry_talk', '{all}', 'Hear them out — always explore opportunities', '{"hype_mult":1.2,"fan_mult":1.0,"cash_mult":1.2,"reputation":{"professional":2}}', 'Politely decline — staying independent', '{"hype_mult":1.0,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Play hard to get — make them chase', '{"hype_mult":1.3,"fan_mult":1.0,"cash_mult":1.1,"reputation":{"mysterious":2}}', 'Tell them off publicly', '{"hype_mult":1.4,"fan_mult":0.8,"cash_mult":0.8,"reputation":{"controversial":2}}'),
('A music producer wants to remix one of your new tracks.', 'industry_talk', '{all}', 'Love the idea — lets do it', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.1,"reputation":{"creative":2}}', 'Only if you maintain creative control', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":2}}', 'Let fans vote on which track to remix', '{"hype_mult":1.4,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"accessible":2}}', 'No remixes — the album is perfect as-is', '{"hype_mult":0.8,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"authentic":2}}'),
('A brand wants to sponsor your release party in exchange for product placement.', 'industry_talk', '{all}', 'Take the money — funds the party', '{"hype_mult":1.1,"fan_mult":0.9,"cash_mult":1.4,"reputation":{"professional":1}}', 'Only if its a brand that fits your image', '{"hype_mult":1.2,"fan_mult":1.0,"cash_mult":1.2,"reputation":{"professional":2}}', 'Decline — keep it authentic', '{"hype_mult":1.0,"fan_mult":1.2,"cash_mult":0.8,"reputation":{"authentic":3}}', 'Negotiate for a better deal', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.3,"reputation":{"professional":1}}'),
('A streaming platform offers to make your release their "Album of the Week."', 'industry_talk', '{all}', 'Accept immediately — massive exposure', '{"hype_mult":1.5,"fan_mult":1.3,"cash_mult":1.2,"reputation":{"professional":1}}', 'Negotiate for better playlist placement too', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.3,"reputation":{"professional":2}}', 'Ask if its exclusive — you want all platforms', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":2}}', 'Decline — you dont need their validation', '{"hype_mult":0.7,"fan_mult":0.8,"cash_mult":0.9,"reputation":{"authentic":2}}'),
('Your manager suggests delaying the release for better marketing timing.', 'industry_talk', '{all}', 'Agree — trust the business strategy', '{"hype_mult":0.9,"fan_mult":0.8,"cash_mult":1.2,"reputation":{"professional":2}}', 'Compromise on a shorter delay', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.1,"reputation":{"professional":1}}', 'Refuse — the fans are ready NOW', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":0.9,"reputation":{"authentic":2}}', 'Fire the manager for suggesting it', '{"hype_mult":1.4,"fan_mult":1.0,"cash_mult":0.8,"reputation":{"controversial":2}}'),
('A sync licensing agent wants to use your lead single in a TV show.', 'industry_talk', '{all}', 'Agree — incredible exposure opportunity', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":1.3,"reputation":{"professional":1}}', 'Only if its the right show for your brand', '{"hype_mult":1.2,"fan_mult":1.0,"cash_mult":1.1,"reputation":{"professional":2}}', 'Ask for too much money and lose the deal', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":0.9,"reputation":{"professional":-1}}', 'Your music isnt for sale to TV', '{"hype_mult":0.7,"fan_mult":0.9,"cash_mult":0.8,"reputation":{"authentic":2}}'),
('Another artist at the party suggests a collaboration on a bonus track.', 'industry_talk', '{all}', 'Lets do it tonight in the studio!', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creative":3}}', 'Save it for the deluxe edition', '{"hype_mult":1.2,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":2}}', 'Politely decline — this release is solo', '{"hype_mult":0.9,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"authentic":1}}', 'Challenge them to a rap battle instead', '{"hype_mult":1.5,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":2}}'),
('Your distributor warns that physical copies might sell out on day one.', 'industry_talk', '{all}', 'Order a rush pressing immediately', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":0.8,"reputation":{"professional":2}}', 'Let scarcity drive up demand', '{"hype_mult":1.4,"fan_mult":1.0,"cash_mult":1.2,"reputation":{"mysterious":2}}', 'Announce limited edition status', '{"hype_mult":1.5,"fan_mult":1.2,"cash_mult":1.3,"reputation":{"creative":1}}', 'Push fans to digital instead', '{"hype_mult":0.9,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"professional":1}}'),
('A venue owner offers you a residency based on the release party vibes.', 'industry_talk', '{all}', 'Accept — build a local following', '{"hype_mult":1.2,"fan_mult":1.3,"cash_mult":1.2,"reputation":{"professional":1}}', 'Negotiate better terms first', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.3,"reputation":{"professional":2}}', 'Decline — youre too big for a residency', '{"hype_mult":0.8,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"controversial":1}}', 'Suggest a monthly event instead', '{"hype_mult":1.1,"fan_mult":1.1,"cash_mult":1.1,"reputation":{"creative":1}}'),
('Your accountant says the release party is over budget.', 'industry_talk', '{all}', 'Worth every penny — keep going', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":0.6,"reputation":{"authentic":1}}', 'Cut some costs discreetly', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":0.9,"reputation":{"professional":2}}', 'Ask fans to chip in via donations', '{"hype_mult":0.8,"fan_mult":0.7,"cash_mult":1.1,"reputation":{"controversial":1}}', 'End the party early to save money', '{"hype_mult":0.5,"fan_mult":0.5,"cash_mult":1.2,"reputation":{"professional":1}}'),
('A tech company wants to create an AR experience for your album art.', 'industry_talk', '{all}', 'That sounds incredible — lets do it', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creative":3}}', 'Only if it doesnt delay the release', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Make it a paid add-on for superfans', '{"hype_mult":1.0,"fan_mult":0.9,"cash_mult":1.2,"reputation":{"professional":1}}', 'Too gimmicky for your brand', '{"hype_mult":0.7,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"authentic":1}}'),
('A concert promoter offers you a headline slot on release week.', 'industry_talk', '{all}', 'Book it — perfect timing', '{"hype_mult":1.5,"fan_mult":1.3,"cash_mult":1.2,"reputation":{"professional":2}}', 'Only if the venue is the right size', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"professional":1}}', 'Ask for a support act you choose', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":1}}', 'Decline — focus on online promotion', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"professional":1}}'),
('An investor wants to fund your next three releases.', 'industry_talk', '{all}', 'Take the investment — scale up', '{"hype_mult":1.2,"fan_mult":1.0,"cash_mult":1.4,"reputation":{"professional":2}}', 'Only if creative freedom is guaranteed', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.2,"reputation":{"authentic":2}}', 'Decline — stay bootstrapped', '{"hype_mult":1.0,"fan_mult":1.1,"cash_mult":0.8,"reputation":{"authentic":3}}', 'Counter with your own terms', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.3,"reputation":{"professional":1}}'),
('A fashion brand wants you to wear their clothes at the release party.', 'industry_talk', '{all}', 'Sure — if the clothes are cool', '{"hype_mult":1.2,"fan_mult":1.0,"cash_mult":1.2,"reputation":{"professional":1}}', 'Only your own merch tonight', '{"hype_mult":1.0,"fan_mult":1.1,"cash_mult":0.9,"reputation":{"authentic":2}}', 'Negotiate a collaboration capsule collection', '{"hype_mult":1.3,"fan_mult":1.0,"cash_mult":1.3,"reputation":{"creative":2}}', 'Wear whatever you want regardless', '{"hype_mult":0.9,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"authentic":1}}'),
('A booking agent from a major festival is in the audience.', 'industry_talk', '{all}', 'Put on the best show of your life', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"professional":2}}', 'Approach them after the show', '{"hype_mult":1.2,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Have your manager make contact', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":2}}', 'Dont change anything — be natural', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"authentic":2}}'),
('Your merch vendor suggests limited vinyl variants for the release.', 'industry_talk', '{all}', 'Do 5 color variants — collectors will love it', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":1.3,"reputation":{"creative":2}}', 'One special variant only', '{"hype_mult":1.2,"fan_mult":1.0,"cash_mult":1.1,"reputation":{"professional":1}}', 'No variants — one version for everyone', '{"hype_mult":0.9,"fan_mult":1.0,"cash_mult":0.9,"reputation":{"authentic":2}}', 'Make fan-voted variants', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"accessible":2}}'),
('A music lawyer suggests copyrighting a catchphrase from your new single.', 'industry_talk', '{all}', 'Smart move — protect the brand', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.2,"reputation":{"professional":2}}', 'Let fans use it freely — builds community', '{"hype_mult":1.2,"fan_mult":1.3,"cash_mult":0.9,"reputation":{"accessible":2}}', 'Trademark it and sell merch with it', '{"hype_mult":1.0,"fan_mult":0.9,"cash_mult":1.4,"reputation":{"professional":1}}', 'Catchphrases cant be owned', '{"hype_mult":0.8,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"authentic":1}}'),
('Your publicist got you a spot on a late-night TV show for release week.', 'industry_talk', '{all}', 'Perform the lead single live', '{"hype_mult":1.5,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"professional":2}}', 'Do a deep cut to show range', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":2}}', 'Perform a mashup of new and old songs', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creative":2}}', 'Decline — TV isnt your thing', '{"hype_mult":0.6,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"authentic":1}}'),
('A charity asks if a portion of release proceeds can go to their cause.', 'industry_talk', '{all}', 'Agree immediately — great cause and PR', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":0.8,"reputation":{"authentic":3}}', 'Do a separate charity track instead', '{"hype_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":1}}', 'Only if fans vote for the charity', '{"hype_mult":1.2,"fan_mult":1.2,"cash_mult":0.9,"reputation":{"accessible":2}}', 'Decline — business is business', '{"hype_mult":0.7,"fan_mult":0.7,"cash_mult":1.1,"reputation":{"professional":1}}'),
('An NFT platform wants to mint your album art as a digital collectible.', 'industry_talk', '{all}', 'Interesting — lets try it', '{"hype_mult":1.2,"fan_mult":0.9,"cash_mult":1.3,"reputation":{"creative":1}}', 'Only if fans get actual perks with it', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.1,"reputation":{"creative":2}}', 'Hard pass — not into NFTs', '{"hype_mult":0.9,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Do a free digital collectible instead', '{"hype_mult":1.1,"fan_mult":1.2,"cash_mult":0.9,"reputation":{"accessible":1}}'),

-- CATEGORY: Surprises (20)
('Your ex shows up at the release party uninvited.', 'surprises', '{all}', 'Be cool about it — its a public event', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":2}}', 'Dedicate a breakup song to them from stage', '{"hype_mult":1.5,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"controversial":2}}', 'Have security escort them out', '{"hype_mult":0.9,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"professional":1}}', 'Ignore their existence completely', '{"hype_mult":0.8,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"professional":1}}'),
('A famous musician shows up at your party unannounced!', 'surprises', '{all}', 'Invite them on stage for a surprise collab', '{"hype_mult":1.5,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"creative":3}}', 'Hang out and take photos together', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Give them VIP treatment backstage', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":2}}', 'Try to outshine them', '{"hype_mult":0.8,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"controversial":1}}'),
('Someone leaks the full album online during the party!', 'surprises', '{all}', 'Embrace it — the music is out there now', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":0.8,"reputation":{"authentic":2}}', 'Address it calmly and focus on the party', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":0.9,"reputation":{"professional":2}}', 'Release it officially right now to combat the leak', '{"hype_mult":1.4,"fan_mult":1.3,"cash_mult":0.7,"reputation":{"creative":2}}', 'Freak out and blame your team', '{"hype_mult":0.6,"fan_mult":0.5,"cash_mult":1.0,"reputation":{"controversial":-1}}'),
('A flash mob starts performing a choreographed dance to your single.', 'surprises', '{all}', 'Join in and learn the moves', '{"hype_mult":1.5,"fan_mult":1.5,"cash_mult":1.0,"reputation":{"authentic":3}}', 'Film it from the best angle for content', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":1}}', 'Watch in awe and applaud', '{"hype_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authentic":1}}', 'Feel embarrassed by the attention', '{"hype_mult":0.7,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"authentic":1}}'),
('A food truck pulls up playing your music. They made a menu inspired by your songs!', 'surprises', '{all}', 'Post it everywhere and eat everything', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Buy food for the whole line', '{"hype_mult":1.4,"fan_mult":1.4,"cash_mult":0.7,"reputation":{"accessible":2}}', 'Thank them but focus on the party', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Demand royalties on the food names', '{"hype_mult":0.6,"fan_mult":0.5,"cash_mult":1.1,"reputation":{"controversial":1}}'),
('Your parents show up at the party to support you!', 'surprises', '{all}', 'Introduce them to everyone proudly', '{"hype_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":3}}', 'Thank them from the stage', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Keep it low-key — they can enjoy from VIP', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Wish they hadnt come — trying to look cool', '{"hype_mult":0.7,"fan_mult":0.6,"cash_mult":1.0,"reputation":{"authentic":-1}}'),
('A rival artist sends a congratulatory message live on social media.', 'surprises', '{all}', 'Reply graciously and publicly thank them', '{"hype_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"professional":2}}', 'Suspect its sarcastic and ignore it', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"controversial":1}}', 'Share it and extend an olive branch', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Respond with a backhanded compliment', '{"hype_mult":1.4,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"controversial":2}}'),
('Someone trips and spills a drink on you at the party.', 'surprises', '{all}', 'Laugh it off — its just a shirt', '{"hype_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Change into fresh merch from your own line', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.1,"reputation":{"creative":1}}', 'Make a joke about it on stage', '{"hype_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creative":1}}', 'Get angry and cause a scene', '{"hype_mult":0.6,"fan_mult":0.4,"cash_mult":1.0,"reputation":{"controversial":-1}}'),
('A drone delivery arrives with a surprise gift from your record label.', 'surprises', '{all}', 'Open it on stage in front of everyone', '{"hype_mult":1.4,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Open it backstage privately', '{"hype_mult":0.9,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"professional":1}}', 'Share the contents with fans', '{"hype_mult":1.3,"fan_mult":1.4,"cash_mult":0.9,"reputation":{"accessible":2}}', 'Be suspicious — is it a PR stunt?', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"authentic":1}}'),
('The fire alarm goes off — false alarm, but everyone panicked.', 'surprises', '{all}', 'Calm everyone down with humor', '{"hype_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Help organize an orderly evacuation just in case', '{"hype_mult":1.0,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"professional":2}}', 'Use it as a dramatic intro when you come back', '{"hype_mult":1.4,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":2}}', 'Panic alongside everyone else', '{"hype_mult":0.6,"fan_mult":0.5,"cash_mult":1.0,"reputation":{"authentic":-1}}'),
('Your first-ever fan is at the party and reveals themselves.', 'surprises', '{all}', 'Give them a VIP experience and thank them emotionally', '{"hype_mult":1.3,"fan_mult":1.5,"cash_mult":0.9,"reputation":{"authentic":3}}', 'Bring them on stage for recognition', '{"hype_mult":1.4,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Take a photo and post about their journey', '{"hype_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":1}}', 'Nice — but you need to focus on new fans', '{"hype_mult":0.7,"fan_mult":0.6,"cash_mult":1.0,"reputation":{"professional":1}}'),
('Someone starts a rumor at the party that youre retiring after this release.', 'surprises', '{all}', 'Laugh and deny it — youre just getting started', '{"hype_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Play along mysteriously', '{"hype_mult":1.4,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"mysterious":3}}', 'Get annoyed and shut it down firmly', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"professional":1}}', 'Announce your next project to prove them wrong', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":1}}'),
('A stray cat wanders into the party venue.', 'surprises', '{all}', 'Adopt it as the official release mascot', '{"hype_mult":1.4,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Pick it up and pose for photos', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Ask someone to take it somewhere safe', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"professional":1}}', 'Youre allergic — stay far away', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"authentic":1}}'),
('A helicopter lands nearby with a mystery guest for your party.', 'surprises', '{all}', 'Run out to see who it is with the crowd', '{"hype_mult":1.5,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Wait inside and let them come to you', '{"hype_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"mysterious":2}}', 'Stream the arrival live', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":1}}', 'Worried about the noise disrupting the party', '{"hype_mult":0.7,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"professional":1}}'),
('The birthday cake they ordered for the release says the wrong album name.', 'surprises', '{all}', 'Laugh about it and eat it anyway', '{"hype_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Fix it with icing yourself', '{"hype_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":1}}', 'Post the fail on social media', '{"hype_mult":1.4,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"accessible":1}}', 'Demand a new cake', '{"hype_mult":0.7,"fan_mult":0.7,"cash_mult":0.9,"reputation":{"professional":1}}'),
('Fireworks go off outside perfectly timed with your lead singles drop.', 'surprises', '{all}', 'Take credit even if it was coincidence', '{"hype_mult":1.4,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"creative":2}}', 'Acknowledge the perfect timing on stage', '{"hype_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authentic":1}}', 'Rush outside to watch them with fans', '{"hype_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"accessible":2}}', 'Get annoyed they upstaged your music', '{"hype_mult":0.6,"fan_mult":0.5,"cash_mult":1.0,"reputation":{"controversial":-1}}'),
('You find out the release just debuted at #1 during the party!', 'surprises', '{all}', 'Announce it to the crowd and celebrate massively', '{"hype_mult":1.5,"fan_mult":1.5,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Stay humble and let someone else announce it', '{"hype_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Buy the whole party a round to celebrate', '{"hype_mult":1.4,"fan_mult":1.4,"cash_mult":0.6,"reputation":{"accessible":3}}', 'Play it cool — you expected nothing less', '{"hype_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"mysterious":2}}'),
('A street artist starts painting a mural of your album art on the venue wall.', 'surprises', '{all}', 'Join them and add your own touch', '{"hype_mult":1.4,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"creative":3}}', 'Watch and commission the finished piece', '{"hype_mult":1.2,"fan_mult":1.0,"cash_mult":0.8,"reputation":{"creative":2}}', 'Film the process for content', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":1}}', 'Ask them to stop — thats vandalism', '{"hype_mult":0.5,"fan_mult":0.5,"cash_mult":1.0,"reputation":{"professional":1}}'),
('Turns out your release date coincides with a major world event stealing all headlines.', 'surprises', '{all}', 'Roll with it — your fans will still show up', '{"hype_mult":1.0,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Delay to avoid competing for attention', '{"hype_mult":0.8,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"professional":2}}', 'Tie your release into the cultural moment', '{"hype_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creative":2}}', 'Complain about the bad timing publicly', '{"hype_mult":0.6,"fan_mult":0.6,"cash_mult":1.0,"reputation":{"controversial":1}}'),
('A flash thunderstorm starts right as the outdoor party peaks.', 'surprises', '{all}', 'Keep performing in the rain — iconic moment!', '{"hype_mult":1.5,"fan_mult":1.5,"cash_mult":0.9,"reputation":{"authentic":3}}', 'Move everything indoors quickly', '{"hype_mult":0.9,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"professional":2}}', 'Dance in the rain with fans', '{"hype_mult":1.4,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"authentic":2}}', 'Cancel the rest of the event', '{"hype_mult":0.5,"fan_mult":0.4,"cash_mult":1.0,"reputation":{"professional":1}}');
