-- Add extended skill definitions for expanded music disciplines
WITH default_caps AS (
  SELECT '{"tiers":[{"tier":1,"cap":200},{"tier":2,"cap":400},{"tier":3,"cap":600},{"tier":4,"cap":800},{"tier":5,"cap":1000}]}'::jsonb AS caps
)
INSERT INTO public.skill_definitions (slug, display_name, description, tier_caps, default_unlock_level, created_by_profile_id)
SELECT
  data.slug,
  data.display_name,
  data.description,
  default_caps.caps,
  data.default_unlock_level,
  NULL
FROM (
  VALUES
    ('songwriting_and_production', 'Songwriting & Production', 'Blending songwriting craft with studio production workflows.', 0),
    ('basic_composing', 'Basic Composing', 'Fundamental composing concepts for building melodies and arrangements.', 0),
    ('basic_lyrics', 'Basic Lyrics', 'Introductory lyric writing skills for crafting simple stories.', 0),
    ('basic_record_production', 'Basic Record Production', 'Hands-on experience with the essentials of recording sessions.', 0),
    ('basic_daw_use', 'Basic DAW Use', 'Learning the basics of operating a digital audio workstation.', 0),
    ('basic_beatmaking', 'Basic Beatmaking', 'Foundational beat construction and groove development skills.', 0),
    ('basic_sampling_and_remixing', 'Basic Sampling & Remixing', 'Entry-level sampling, chopping, and remix workflow techniques.', 0),
    ('basic_sound_design_and_synthesis', 'Basic Sound Design & Synthesis', 'Starter approaches to shaping sounds with synthesizers.', 0),
    ('basic_mixing_and_mastering', 'Basic Mixing & Mastering', 'Core mixing and mastering practices for a clean demo.', 0),
    ('basic_live_looping', 'Basic Live Looping', 'Foundational skills for building live loops on stage.', 0),
    ('basic_vocal_tuning_and_processing', 'Basic Vocal Tuning & Processing', 'Beginner pitch correction and vocal effect workflows.', 0),
    ('basic_ai_music_tools', 'Basic AI Music Tools', 'Exploring beginner-friendly AI-assisted music creation tools.', 0),
    ('basic_blues', 'Basic Blues', 'Foundational blues progressions, phrasing, and feel.', 0),
    ('basic_rock', 'Basic Rock', 'Entry-level rock rhythms, riffs, and song structures.', 0),
    ('basic_jazz', 'Basic Jazz', 'Introductory jazz harmony, improvisation, and swing feel.', 0),
    ('basic_hip_hop', 'Basic Hip Hop', 'Fundamental hip hop flow, beats, and production staples.', 0),
    ('basic_pop', 'Basic Pop', 'Core pop songwriting forms and catchy hook crafting.', 0),
    ('basic_country_and_western', 'Basic Country & Western', 'Country and western basics in storytelling and twang.', 0),
    ('basic_reggae', 'Basic Reggae', 'Foundational reggae grooves, offbeats, and mood.', 0),
    ('basic_heavy_metal', 'Basic Heavy Metal', 'Intro to heavy metal riffs, tone, and aggression.', 0),
    ('basic_classical', 'Basic Classical', 'Classical theory, notation, and ensemble awareness.', 0),
    ('basic_electronica', 'Basic Electronica', 'Essential electronica textures, layers, and grooves.', 0),
    ('basic_latin_music', 'Basic Latin Music', 'Fundamental Latin rhythms, instrumentation, and feel.', 0),
    ('basic_world_music', 'Basic World Music', 'Exploring global music motifs and cultural patterns.', 0),
    ('basic_rhythm_and_blues', 'Basic Rhythm & Blues', 'R&B grooves, vocal stylings, and emotional delivery.', 0),
    ('basic_punk_rock', 'Basic Punk Rock', 'Fast-paced punk energy, chords, and attitude.', 0),
    ('basic_flamenco', 'Basic Flamenco', 'Foundational flamenco compás, rasgueado, and flair.', 0),
    ('basic_african_music', 'Basic African Music', 'Introductory African rhythms, call-and-response, and pulse.', 0),
    ('basic_modern_rock', 'Basic Modern Rock', 'Current rock sonics, dynamics, and stage presence.', 0),
    ('basic_brass_instruments', 'Basic Brass Instruments', 'Basic brass technique, embouchure, and ensemble blend.', 0),
    ('basic_electronic_instruments', 'Basic Electronic Instruments', 'Getting started with synths, controllers, and signal flow.', 0),
    ('basic_keyboard_instruments', 'Basic Keyboard Instruments', 'Keyboard fingering, chords, and accompaniment basics.', 0),
    ('basic_percussions', 'Basic Percussions', 'Foundational percussion patterns, timing, and groove.', 0),
    ('basic_rapping', 'Basic Rapping', 'Beginner flow control, rhythm, and lyrical cadence.', 0),
    ('basic_singing', 'Basic Singing', 'Vocal warm-ups, breathing, and pitch fundamentals.', 0),
    ('basic_string_instruments', 'Basic String Instruments', 'String family basics in bowing, tuning, and tone.', 0),
    ('basic_woodwind_instruments', 'Basic Woodwind Instruments', 'Woodwind embouchure, articulation, and tone production.', 0),
    ('basic_dj_controller_skills', 'Basic DJ Controller Skills', 'Introductory DJ controller navigation and beat matching.', 0),
    ('basic_midi_controller_skills', 'Basic MIDI Controller Skills', 'Fundamental MIDI controller mapping and performance.', 0),
    ('basic_sampler_drum_machine_proficiency', 'Basic Sampler/Drum Machine Proficiency', 'Hands-on sampler and drum machine basics for grooves.', 0),
    ('basic_hybrid_drums', 'Basic Hybrid Drums', 'Combining acoustic and electronic drums at a beginner level.', 0),
    ('basic_electronic_strings', 'Basic Electronic Strings (e-violin, e-cello)', 'Entry skills for expressive performance on electronic strings.', 0),
    ('basic_showmanship', 'Basic Showmanship', 'Stage presence basics for confident performances.', 0),
    ('basic_stage_tech', 'Basic Stage Tech', 'Intro to stage gear, signal paths, and troubleshooting.', 0),
    ('basic_visual_performance_integration', 'Basic Visual Performance Integration', 'Starting visual elements synced with live music.', 0),
    ('basic_social_media_performance', 'Basic Social Media Performance', 'Presenting performances effectively on social platforms.', 0),
    ('basic_streaming_concerts', 'Basic Streaming Concerts', 'Foundations for hosting live-streamed shows.', 0),
    ('basic_crowd_interaction', 'Basic Crowd Interaction', 'Building early crowd engagement and rapport.', 0),
    ('professional_composing', 'Professional Composing', 'Advanced composition techniques for complex arrangements.', 0),
    ('professional_lyrics', 'Professional Lyrics', 'Polished lyric craftsmanship for impactful storytelling.', 0),
    ('professional_record_production', 'Professional Record Production', 'Full-scale production leadership from tracking to mix.', 0),
    ('professional_daw_production', 'Professional DAW Production', 'Expert DAW mastery for high-end sessions.', 0),
    ('professional_beatmaking', 'Professional Beatmaking', 'Cutting-edge beatmaking with professional polish.', 0),
    ('professional_sampling_and_remixing', 'Professional Sampling & Remixing', 'Sophisticated sampling and remix strategies for releases.', 0),
    ('professional_sound_design_and_synthesis', 'Professional Sound Design & Synthesis', 'Advanced synthesis sculpting for signature sounds.', 0),
    ('professional_mixing_and_mastering', 'Professional Mixing & Mastering', 'Pro-level mixing and mastering for release-ready tracks.', 0),
    ('professional_live_looping', 'Professional Live Looping', 'Commanding complex live looping arrangements in real time.', 0),
    ('professional_vocal_production', 'Professional Vocal Production', 'Expert vocal tracking, tuning, and creative processing.', 0),
    ('professional_ai_music_integration', 'Professional AI Music Integration', 'Integrating AI tools strategically within professional workflows.', 0),
    ('professional_djing', 'Professional DJing', 'High-level DJ performance, transitions, and crowd reading.', 0),
    ('professional_midi_performance', 'Professional MIDI Performance', 'Expressive MIDI performance and controller artistry.', 0),
    ('professional_drum_machine_use', 'Professional Drum Machine Use', 'Advanced drum machine programming for live and studio.', 0),
    ('professional_hybrid_drumming', 'Professional Hybrid Drumming', 'Seamless integration of acoustic and electronic drumming on stage.', 0),
    ('professional_electronic_strings', 'Professional Electronic Strings', 'Professional phrasing and expression on electronic string instruments.', 0),
    ('professional_showmanship', 'Professional Showmanship', 'Elite stagecraft that captivates audiences consistently.', 0),
    ('professional_stage_tech', 'Professional Stage Tech', 'Expert oversight of stage technology and production teams.', 0),
    ('professional_visual_shows', 'Professional Visual Shows', 'Designing immersive visual experiences for headline shows.', 0),
    ('professional_social_media_musician', 'Professional Social Media Musician', 'Professional branding and storytelling across social channels.', 0),
    ('professional_streaming_shows', 'Professional Streaming Shows', 'Delivering polished, monetized live streams to global audiences.', 0),
    ('professional_crowd_engagement', 'Professional Crowd Engagement', 'Mastering audience interaction to drive lasting fandom.', 0)
) AS data(slug, display_name, description, default_unlock_level)
CROSS JOIN default_caps
ON CONFLICT (slug)
DO UPDATE
SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  tier_caps = EXCLUDED.tier_caps,
  default_unlock_level = EXCLUDED.default_unlock_level;
