
INSERT INTO public.random_events (title, description, category, is_common, is_active, option_a_text, option_a_effects, option_a_outcome_text, option_b_text, option_b_effects, option_b_outcome_text)
VALUES
  ('Food Poisoning Abroad', 'Something you ate didn''t agree with you at all. You''re violently ill.', 'travel_hazard', true, true,
   'Push through it', '{"condition": "food_poisoning", "condition_type": "sickness", "severity": 60}', 'You soldier on but the food poisoning takes its toll.',
   'See a local doctor', '{"condition": "food_poisoning", "condition_type": "sickness", "severity": 40, "cash": -100}', 'The doctor gives you medication. Still rough but manageable.'),
  ('Bus Accident', 'Your tour bus hit a nasty pothole. You twisted your ankle badly.', 'travel_hazard', true, true,
   'Walk it off', '{"condition": "sprained_ankle", "condition_type": "injury", "severity": 50}', 'You limp through but the pain is real.',
   'Get medical attention', '{"condition": "sprained_ankle", "condition_type": "injury", "severity": 30, "cash": -150}', 'The medic wraps it up. Should heal faster now.'),
  ('Tropical Illness', 'The humid climate and mosquitoes have taken their toll. You''ve contracted a tropical fever.', 'travel_hazard', false, true,
   'Rest and hope for the best', '{"condition": "tropical_fever", "condition_type": "sickness", "severity": 70}', 'The fever rages on. You need proper treatment.',
   'Rush to hospital', '{"condition": "tropical_fever", "condition_type": "sickness", "severity": 50, "cash": -300}', 'Hospital treatment brings the fever under control.'),
  ('Jet Lag Crisis', 'Crossing multiple time zones has completely destroyed your sleep cycle.', 'travel_hazard', true, true,
   'Power through', '{"condition": "severe_jetlag", "condition_type": "sickness", "severity": 40}', 'Your body clock is wrecked. Everything feels off.',
   'Take sleeping pills', '{"condition": "severe_jetlag", "condition_type": "sickness", "severity": 25, "cash": -30}', 'The pills help reset your cycle somewhat.'),
  ('Back Injury from Luggage', 'You threw out your back lifting heavy equipment cases.', 'travel_hazard', true, true,
   'Stretch and rest', '{"condition": "back_strain", "condition_type": "injury", "severity": 55}', 'The stretching helps a bit but your back is shot.',
   'See a physiotherapist', '{"condition": "back_strain", "condition_type": "injury", "severity": 35, "cash": -120}', 'Professional treatment eases the pain significantly.'),
  ('Stage Equipment Fall', 'A lighting rig nearly fell on you during soundcheck. You got clipped.', 'travel_hazard', false, true,
   'Shake it off', '{"condition": "bruised_ribs", "condition_type": "injury", "severity": 50}', 'You brush it off but breathing hurts.',
   'Go to the ER', '{"condition": "bruised_ribs", "condition_type": "injury", "severity": 30, "cash": -200}', 'X-rays show no fractures. Just badly bruised.'),
  ('Vocal Strain', 'Performing in dry, dusty venues has damaged your vocal cords.', 'travel_hazard', true, true,
   'Rest your voice', '{"condition": "vocal_strain", "condition_type": "injury", "severity": 45}', 'You go silent for a while. The strain lingers.',
   'See a specialist', '{"condition": "vocal_strain", "condition_type": "injury", "severity": 25, "cash": -180}', 'The ENT prescribes vocal rest and steroids.'),
  ('Anxiety Attack on Flight', 'Turbulence triggered a severe anxiety attack. You can''t stop shaking.', 'travel_hazard', true, true,
   'Try to calm down alone', '{"condition": "anxiety", "condition_type": "mental_health", "severity": 50}', 'You manage to control your breathing but the dread remains.',
   'Take anxiety medication', '{"condition": "anxiety", "condition_type": "mental_health", "severity": 30, "cash": -50}', 'The medication takes the edge off. You feel numb but calmer.'),
  ('Touring Burnout', 'Weeks on the road with no break. You feel empty and exhausted.', 'travel_hazard', false, true,
   'Keep pushing', '{"condition": "burnout", "condition_type": "mental_health", "severity": 65}', 'You push through but everything feels meaningless.',
   'Cancel next show and rest', '{"condition": "burnout", "condition_type": "mental_health", "severity": 40, "cash": -500}', 'The break helps. You lost money but saved your sanity.'),
  ('Homesick Depression', 'Being away from home for so long is crushing your spirit.', 'travel_hazard', true, true,
   'Call family', '{"condition": "depression", "condition_type": "mental_health", "severity": 40}', 'Hearing familiar voices helps, but the sadness remains.',
   'Write about it', '{"condition": "depression", "condition_type": "mental_health", "severity": 35}', 'You channel the pain into lyrics. Beautiful but heavy.'),
  ('Insomnia Hits', 'You haven''t been able to sleep properly for days. The exhaustion is creeping in.', 'mental_health', true, true,
   'Try to sleep naturally', '{"condition": "insomnia", "condition_type": "mental_health", "severity": 45}', 'Another sleepless night. Your body is running on fumes.',
   'Get sleeping pills', '{"condition": "insomnia", "condition_type": "mental_health", "severity": 30, "cash": -40}', 'The pills knock you out but the sleep feels artificial.'),
  ('Creative Block Depression', 'You can''t write, can''t perform, can''t feel anything. The muse has abandoned you.', 'mental_health', false, true,
   'Isolate and reflect', '{"condition": "depression", "condition_type": "mental_health", "severity": 55}', 'The isolation deepens the gloom but clarity may follow.',
   'Book therapy immediately', '{"condition": "depression", "condition_type": "mental_health", "severity": 35, "cash": -100}', 'The therapist helps you process. A long road ahead.'),
  ('Performance Anxiety', 'The thought of going on stage fills you with dread. Your hands won''t stop trembling.', 'mental_health', true, true,
   'Face the fear', '{"condition": "anxiety", "condition_type": "mental_health", "severity": 50}', 'You go on stage anyway. It was rough but you survived.',
   'Take beta blockers', '{"condition": "anxiety", "condition_type": "mental_health", "severity": 30, "cash": -60}', 'The trembling stops. You perform mechanically but competently.');
