-- Top of the Pops phase 1 foundation.
-- Server-authoritative fortnightly television event driven by immutable UK chart snapshots.

CREATE TABLE IF NOT EXISTS public.totp_episodes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  episode_date date NOT NULL UNIQUE,
  episode_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  status text NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'inviting', 'locked', 'recording', 'broadcast', 'completed', 'cancelled')),
  chart_snapshot_date date NOT NULL,
  city_id uuid NOT NULL REFERENCES public.cities(id),
  check_in_at timestamptz NOT NULL,
  broadcast_at timestamptz NOT NULL,
  max_performances integer NOT NULL DEFAULT 10 CHECK (max_performances BETWEEN 1 AND 20),
  presenter_key text NOT NULL DEFAULT 'alex_rayne',
  broadcast_profile text NOT NULL DEFAULT 'totp_classic',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.totp_candidates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  episode_id uuid NOT NULL REFERENCES public.totp_episodes(id) ON DELETE CASCADE,
  band_id uuid NOT NULL REFERENCES public.bands(id) ON DELETE CASCADE,
  song_id uuid NOT NULL REFERENCES public.songs(id) ON DELETE CASCADE,
  chart_rank integer NOT NULL CHECK (chart_rank BETWEEN 1 AND 40),
  qualifying_chart text NOT NULL CHECK (qualifying_chart IN ('streaming', 'digital_sales', 'both')),
  chart_snapshot_date date NOT NULL,
  selection_bucket text NOT NULL CHECK (selection_bucket IN ('top10', '11_20', '21_40')),
  selected boolean NOT NULL DEFAULT false,
  ineligible_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (episode_id, band_id),
  UNIQUE (episode_id, song_id)
);

CREATE TABLE IF NOT EXISTS public.totp_invitations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  episode_id uuid NOT NULL REFERENCES public.totp_episodes(id) ON DELETE CASCADE,
  candidate_id uuid NOT NULL REFERENCES public.totp_candidates(id) ON DELETE CASCADE,
  band_id uuid NOT NULL REFERENCES public.bands(id) ON DELETE CASCADE,
  song_id uuid NOT NULL REFERENCES public.songs(id) ON DELETE CASCADE,
  qualifying_rank integer NOT NULL CHECK (qualifying_rank BETWEEN 1 AND 40),
  status text NOT NULL DEFAULT 'invited' CHECK (status IN ('invited', 'accepted', 'declined', 'expired', 'checked_in', 'performed', 'missed')),
  invited_at timestamptz NOT NULL DEFAULT now(),
  response_deadline timestamptz NOT NULL,
  responded_at timestamptz,
  checked_in_at timestamptz,
  missed_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (episode_id, band_id),
  UNIQUE (episode_id, song_id)
);

CREATE TABLE IF NOT EXISTS public.totp_performances (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  episode_id uuid NOT NULL REFERENCES public.totp_episodes(id) ON DELETE CASCADE,
  invitation_id uuid NOT NULL UNIQUE REFERENCES public.totp_invitations(id) ON DELETE CASCADE,
  band_id uuid NOT NULL REFERENCES public.bands(id) ON DELETE CASCADE,
  song_id uuid NOT NULL REFERENCES public.songs(id) ON DELETE CASCADE,
  running_order integer CHECK (running_order BETWEEN 1 AND 20),
  stage_key text NOT NULL DEFAULT 'main_stage',
  camera_profile text NOT NULL DEFAULT 'totp_classic',
  presenter_intro text,
  performance_score integer CHECK (performance_score BETWEEN 0 AND 100),
  fame_awarded integer NOT NULL DEFAULT 0 CHECK (fame_awarded >= 0),
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (episode_id, running_order),
  UNIQUE (episode_id, band_id)
);

CREATE INDEX IF NOT EXISTS totp_candidates_episode_rank_idx ON public.totp_candidates (episode_id, chart_rank);
CREATE INDEX IF NOT EXISTS totp_invitations_band_idx ON public.totp_invitations (band_id, episode_id);
CREATE INDEX IF NOT EXISTS totp_performances_band_idx ON public.totp_performances (band_id, episode_id);

ALTER TABLE public.totp_episodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.totp_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.totp_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.totp_performances ENABLE ROW LEVEL SECURITY;

-- Phase 1 keeps these tables server-only. Player/admin read models will be exposed
-- deliberately through narrow RPCs in the UI phase rather than broad table policies.
REVOKE ALL ON public.totp_episodes FROM anon, authenticated;
REVOKE ALL ON public.totp_candidates FROM anon, authenticated;
REVOKE ALL ON public.totp_invitations FROM anon, authenticated;
REVOKE ALL ON public.totp_performances FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.totp_is_episode_date(p_date date)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT p_date >= DATE '2026-09-17'
    AND extract(isodow FROM p_date) = 4
    AND mod((p_date - DATE '2026-09-17'), 14) = 0;
$$;

CREATE OR REPLACE FUNCTION public.totp_prepare_episode(p_episode_date date)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_episode_id uuid;
  v_london_id uuid;
  v_snapshot_date date;
BEGIN
  IF NOT public.totp_is_episode_date(p_episode_date) THEN
    RAISE EXCEPTION 'Top of the Pops episode date must be a scheduled fortnightly Thursday';
  END IF;

  -- An existing prepared episode is immutable. Returning it prevents scheduler retries,
  -- manual reruns or chart backfills from changing the locked chart snapshot, deleting
  -- player responses or firing duplicate invitation notifications.
  SELECT id, chart_snapshot_date
  INTO v_episode_id, v_snapshot_date
  FROM public.totp_episodes
  WHERE episode_date = p_episode_date;

  IF v_episode_id IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.totp_candidates WHERE episode_id = v_episode_id
  ) THEN
    RETURN v_episode_id;
  END IF;

  SELECT id INTO v_london_id
  FROM public.cities
  WHERE lower(name) = 'london'
  ORDER BY id
  LIMIT 1;

  IF v_london_id IS NULL THEN
    RAISE EXCEPTION 'London city record not found';
  END IF;

  IF v_snapshot_date IS NULL THEN
    SELECT max(chart_date) INTO v_snapshot_date
    FROM (
      SELECT chart_date
      FROM public.chart_entries
      WHERE country = 'United Kingdom'
        AND chart_type IN ('streaming', 'digital_sales')
        AND entry_type = 'song'
        AND chart_date <= (p_episode_date - 3)
      GROUP BY chart_date
      HAVING count(DISTINCT chart_type) = 2
    ) snapshots;
  END IF;

  IF v_snapshot_date IS NULL THEN
    RAISE EXCEPTION 'No complete UK streaming + digital sales chart snapshot found for episode %', p_episode_date;
  END IF;

  IF v_episode_id IS NULL THEN
    INSERT INTO public.totp_episodes (
      episode_date,
      chart_snapshot_date,
      city_id,
      check_in_at,
      broadcast_at,
      status
    )
    VALUES (
      p_episode_date,
      v_snapshot_date,
      v_london_id,
      ((p_episode_date::timestamp + time '15:00') AT TIME ZONE 'Europe/London'),
      ((p_episode_date::timestamp + time '20:00') AT TIME ZONE 'Europe/London'),
      'inviting'
    )
    RETURNING id INTO v_episode_id;
  END IF;

  WITH source_rows AS (
    SELECT
      ce.song_id,
      ce.chart_type,
      ce.rank,
      s.band_id
    FROM public.chart_entries ce
    JOIN public.songs s ON s.id = ce.song_id
    WHERE ce.chart_date = v_snapshot_date
      AND ce.country = 'United Kingdom'
      AND ce.entry_type = 'song'
      AND ce.chart_type IN ('streaming', 'digital_sales')
      AND ce.rank BETWEEN 1 AND 40
      AND s.band_id IS NOT NULL
      AND coalesce(s.archived, false) = false
  ),
  combined_eligibility AS (
    SELECT
      song_id,
      band_id,
      min(rank) AS best_rank,
      CASE
        WHEN count(DISTINCT chart_type) = 2 THEN 'both'
        WHEN bool_or(chart_type = 'streaming') THEN 'streaming'
        ELSE 'digital_sales'
      END AS qualifying_chart
    FROM source_rows
    GROUP BY song_id, band_id
  ),
  ranked_band_songs AS (
    SELECT
      *,
      row_number() OVER (PARTITION BY band_id ORDER BY best_rank ASC, song_id) AS band_song_rank
    FROM combined_eligibility
  ),
  best_song_per_band AS (
    SELECT song_id, band_id, best_rank, qualifying_chart
    FROM ranked_band_songs
    WHERE band_song_rank = 1
  ),
  previous_episode AS (
    SELECT id
    FROM public.totp_episodes
    WHERE episode_date < p_episode_date
      AND status <> 'cancelled'
    ORDER BY episode_date DESC
    LIMIT 1
  )
  INSERT INTO public.totp_candidates (
    episode_id, band_id, song_id, chart_rank, qualifying_chart,
    chart_snapshot_date, selection_bucket, ineligible_reason
  )
  SELECT
    v_episode_id,
    b.band_id,
    b.song_id,
    b.best_rank,
    b.qualifying_chart,
    v_snapshot_date,
    CASE WHEN b.best_rank <= 10 THEN 'top10' WHEN b.best_rank <= 20 THEN '11_20' ELSE '21_40' END,
    CASE
      WHEN EXISTS (
        SELECT 1
        FROM public.totp_performances tp
        JOIN previous_episode pe ON pe.id = tp.episode_id
        WHERE tp.band_id = b.band_id
          AND tp.completed_at IS NOT NULL
      ) THEN 'previous_episode_performer'
      ELSE NULL
    END
  FROM best_song_per_band b
  ON CONFLICT DO NOTHING;

  -- Stable editorial selection: chart success determines the pool, while an episode-
  -- seeded hash prevents players from changing selection through retries or refreshes.
  -- Slots are intentionally spread across the Top 40 so the programme is not simply
  -- another Top 10 reward screen.
  WITH ranked AS (
    SELECT c.id,
           c.selection_bucket,
           row_number() OVER (
             PARTITION BY c.selection_bucket
             ORDER BY
               CASE WHEN c.chart_rank = 1 THEN 0 ELSE 1 END,
               md5(v_episode_id::text || ':' || c.band_id::text || ':' || c.song_id::text)
           ) AS bucket_order
    FROM public.totp_candidates c
    WHERE c.episode_id = v_episode_id
      AND c.ineligible_reason IS NULL
  ),
  selected AS (
    SELECT id FROM ranked
    WHERE (selection_bucket = 'top10' AND bucket_order <= 4)
       OR (selection_bucket = '11_20' AND bucket_order <= 3)
       OR (selection_bucket = '21_40' AND bucket_order <= 3)
  )
  UPDATE public.totp_candidates c
  SET selected = true
  FROM selected s
  WHERE c.id = s.id;

  INSERT INTO public.totp_invitations (
    episode_id, candidate_id, band_id, song_id, qualifying_rank, response_deadline
  )
  SELECT
    c.episode_id,
    c.id,
    c.band_id,
    c.song_id,
    c.chart_rank,
    (((p_episode_date - 1)::timestamp + time '18:00') AT TIME ZONE 'Europe/London')
  FROM public.totp_candidates c
  WHERE c.episode_id = v_episode_id
    AND c.selected = true
  ON CONFLICT DO NOTHING;

  RETURN v_episode_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.totp_prepare_next_episode()
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_next_thursday date;
BEGIN
  v_next_thursday := current_date + ((4 - extract(isodow FROM current_date)::integer + 7) % 7);
  IF v_next_thursday = current_date THEN
    v_next_thursday := v_next_thursday + 7;
  END IF;

  IF NOT public.totp_is_episode_date(v_next_thursday) THEN
    RETURN NULL;
  END IF;

  RETURN public.totp_prepare_episode(v_next_thursday);
END;
$$;

-- Internal scheduler functions are intentionally not callable through the Data API.
REVOKE ALL ON FUNCTION public.totp_prepare_episode(date) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.totp_prepare_next_episode() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.totp_prepare_episode(date) TO service_role;
GRANT EXECUTE ON FUNCTION public.totp_prepare_next_episode() TO service_role;

DO $$
DECLARE
  v_job_id bigint;
BEGIN
  SELECT jobid INTO v_job_id
  FROM cron.job
  WHERE jobname = 'prepare_top_of_the_pops';

  IF v_job_id IS NOT NULL THEN
    PERFORM cron.unschedule(v_job_id);
  END IF;

  -- Monday 09:00 UTC. The function itself enforces the fortnightly Thursday cadence.
  PERFORM cron.schedule(
    'prepare_top_of_the_pops',
    '0 9 * * 1',
    $cron$SELECT public.totp_prepare_next_episode();$cron$
  );
END;
$$;

COMMENT ON TABLE public.totp_episodes IS 'Fortnightly Thursday Top of the Pops broadcasts in London.';
COMMENT ON TABLE public.totp_candidates IS 'Immutable eligibility snapshot from the UK streaming and digital sales Top 40.';
COMMENT ON TABLE public.totp_invitations IS 'Server-authoritative invitations; qualifying song is locked to the chart snapshot.';
COMMENT ON TABLE public.totp_performances IS 'Permanent appearance history and broadcast metadata for Top of the Pops.';