
ALTER TABLE public.songs ADD COLUMN IF NOT EXISTS popularity INTEGER DEFAULT 0;
ALTER TABLE public.songs ADD COLUMN IF NOT EXISTS is_fan_favourite BOOLEAN DEFAULT false;
ALTER TABLE public.songs ADD COLUMN IF NOT EXISTS fan_favourite_at TIMESTAMPTZ;
ALTER TABLE public.songs ADD COLUMN IF NOT EXISTS gig_play_count INTEGER DEFAULT 0;
ALTER TABLE public.songs ADD COLUMN IF NOT EXISTS last_gigged_at TIMESTAMPTZ;
