-- Persist live gig outcome breakdowns generated by the server-authoritative gig outcome calculator.
-- Legacy rows are not recalculated; missing JSON fields render with safe defaults in application code.
ALTER TABLE public.gig_outcomes
  ADD COLUMN IF NOT EXISTS calculation_version text NOT NULL DEFAULT 'legacy',
  ADD COLUMN IF NOT EXISTS technical_performance_score numeric,
  ADD COLUMN IF NOT EXISTS stage_performance_score numeric,
  ADD COLUMN IF NOT EXISTS audience_response_score numeric,
  ADD COLUMN IF NOT EXISTS setlist_flow_score numeric,
  ADD COLUMN IF NOT EXISTS ensemble_performance_score numeric,
  ADD COLUMN IF NOT EXISTS member_execution_breakdown jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS song_performance_breakdown jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS readiness_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS equipment_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS crew_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS wellness_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS venue_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS applied_variance numeric,
  ADD COLUMN IF NOT EXISTS notable_events jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS fan_reputation_changes jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS xp_reward_breakdown jsonb NOT NULL DEFAULT '[]'::jsonb;

CREATE INDEX IF NOT EXISTS idx_gig_outcomes_calculation_version
  ON public.gig_outcomes(calculation_version);

COMMENT ON COLUMN public.gig_outcomes.calculation_version IS 'legacy for pre-breakdown outcomes; gig_live_outcome_v1 for server-authoritative live outcome calculator rows.';
COMMENT ON COLUMN public.gig_outcomes.member_execution_breakdown IS 'Server-authored per-member role execution details used for post-gig reports and admin diagnostics.';
COMMENT ON COLUMN public.gig_outcomes.song_performance_breakdown IS 'Server-authored per-song technical, stage, audience, momentum and event breakdowns.';
