-- Insert 30+ lifestyle random events (table already exists with correct schema)
INSERT INTO public.random_events (title, description, category, is_common, health_min, health_max, option_a_text, option_a_effects, option_a_outcome_text, option_b_text, option_b_effects, option_b_outcome_text, is_active) VALUES
-- Hotel Events (8)
('Roach Motel Nightmare', 'Your budget accommodation has some unwanted roommates - cockroaches everywhere!', 'hotel', false, NULL, NULL, 'Demand a refund and leave', '{"money": -50, "health": -5}', 'You got a partial refund but spent the night stressed', 'Tough it out for street cred', '{"health": -10, "fame": 5}', 'You survived the roach motel - fans love the authenticity', true),
('Luxury Suite Upgrade', 'The hotel manager recognized you and offered a complimentary suite upgrade!', 'hotel', false, NULL, NULL, 'Accept graciously', '{"health": 15}', 'You enjoyed a luxurious night of rest in the presidential suite', 'Decline and donate the value', '{"fame": 20, "money": -200}', 'Your generosity made local news!', true),
('Hotel Room Trashed', 'Last night''s celebration got out of hand. The hotel is demanding payment for damages.', 'hotel', false, NULL, NULL, 'Pay the damages quietly', '{"money": -1500}', 'You paid $1,500 in damages to keep it quiet', 'Deny everything', '{"fame": -15, "money": -2000}', 'Security footage went viral - you paid double', true),
('Noise Complaint', 'Hotel security knocked on your door - other guests are complaining about the noise.', 'hotel', true, NULL, NULL, 'Apologize and quiet down', '{}', 'You apologized and kept it down for the rest of the night', 'Rock star attitude', '{"money": -100, "fame": 10}', 'You told them to deal with it - the story spread online', true),
('Lost Room Key', 'You can''t find your room key anywhere. The front desk is closed.', 'hotel', true, NULL, NULL, 'Wait for morning and pay replacement', '{"money": -25}', 'You waited in the lobby and paid for a new key', 'Climb through the window', '{"health": -5, "fame": 5}', 'You climbed in like a true rock star - someone filmed it', true),
('Hotel Spa Day', 'The hotel has an amazing spa. You have some free time before soundcheck.', 'hotel', false, NULL, NULL, 'Indulge in full treatment', '{"health": 20, "money": -150}', 'The massage and treatments left you completely refreshed', 'Skip it and rehearse', '{"xp": 25}', 'You used the time to work on your craft instead', true),
('Bed Bug Discovery', 'You wake up covered in bites. This hostel has bed bugs!', 'hotel', false, NULL, NULL, 'Demand a new room', '{"health": -5}', 'They moved you to a clean room', 'Sleep in the van', '{"health": -15}', 'The van was uncomfortable but at least bug-free', true),
('Celebrity Neighbor', 'A famous musician is staying in the room next to yours!', 'hotel', false, NULL, NULL, 'Invite them for drinks', '{"fame": 15, "money": -50}', 'You had an amazing night networking with a legend', 'Respect their privacy', '{"reputation": 10}', 'Word got around that you''re respectful - industry people noticed', true),

-- Partying Events (8)
('Legendary Afterparty', 'The afterparty is absolutely epic. Everyone who''s anyone is here.', 'partying', false, NULL, NULL, 'Go all night', '{"health": -25, "fame": 30}', 'You partied until sunrise - legendary stories will be told', 'Leave at a reasonable hour', '{"fame": -5, "health": 10}', 'You left early but got proper rest', true),
('Morning Hangover', 'You wake up feeling terrible. Soundcheck is in 2 hours.', 'partying', true, NULL, NULL, 'Hair of the dog', '{"health": -10}', 'A little drink helped but you''re still rough', 'Suffer through it sober', '{"energy": -20}', 'You toughed it out without drinking more', true),
('Free Drinks Backstage', 'The venue has stocked the green room with premium drinks.', 'partying', true, NULL, NULL, 'Drink generously', '{"health": -15, "fame": 5}', 'The free drinks flowed and you got loose for the show', 'Stay hydrated instead', '{"health": 5}', 'You stuck to water and felt great for the performance', true),
('Industry Party Invitation', 'A major label is hosting an exclusive party. You got an invite!', 'partying', false, NULL, NULL, 'Attend and network', '{"fame": 15, "money": -100, "health": -10}', 'You made valuable connections at the party', 'Decline politely', '{"fame": -5}', 'You stayed in but might have missed opportunities', true),
('Band Celebration', 'The gig was amazing! The band wants to celebrate together.', 'partying', true, NULL, NULL, 'Celebrate big', '{"health": -20, "chemistry": 10}', 'Wild night with the band - you''re all closer now', 'Quiet dinner instead', '{"health": 5, "chemistry": 5}', 'A chill dinner together was nice bonding time', true),
('Sobriety Challenge', 'A friend challenges you to stay sober for 30 days. Social media is watching.', 'partying', false, NULL, NULL, 'Accept the challenge', '{"fame": 25}', 'You committed publicly - your health will improve if you stick to it', 'Decline gracefully', '{}', 'You politely declined - no judgment', true),
('VIP Club Section', 'The hottest club in town is offering you VIP treatment.', 'partying', false, NULL, NULL, 'Accept VIP treatment', '{"money": -200, "fame": 15, "health": -10}', 'Photos of you in VIP spread across social media', 'Mingle with regular fans', '{"fame": 10}', 'Fans loved that you hung out with them instead of VIP', true),
('Drinking Contest', 'Local radio hosts challenge you to a drinking contest on air.', 'partying', false, NULL, NULL, 'Accept the challenge', '{"fame": 25, "health": -15}', 'You won! Clips went viral', 'Politely decline', '{}', 'You declined professionally - no hard feelings', true),

-- Fan Encounter Events (8)
('Obsessive Fan at Hotel', 'A fan has figured out which hotel you''re staying at and is waiting in the lobby.', 'fan_encounter', false, NULL, NULL, 'Be kind and take a photo', '{"fame": 5}', 'You made their day with a quick photo', 'Have security handle it', '{"fame": -2}', 'Security escorted them out - you felt safer', true),
('Fan Gift at Stage Door', 'A fan is waiting with a handmade gift they spent weeks creating.', 'fan_encounter', true, NULL, NULL, 'Accept warmly and chat', '{"fame": 5, "reputation": 5}', 'You spent time appreciating their gift - they were thrilled', 'Take it quickly and go', '{}', 'You accepted the gift but had to rush off', true),
('Superfan Tattoo', 'A dedicated fan shows you their new tattoo of your band logo!', 'fan_encounter', false, NULL, NULL, 'Sign next to the tattoo', '{"fame": 10}', 'You signed next to it - they posted everywhere', 'Offer to pay for removal', '{"fame": 15, "money": -100}', 'Your joke offer went viral - fans loved the humor', true),
('Crowd Surge at Meet & Greet', 'The meet and greet line has gotten out of control - fans are pushing forward.', 'fan_encounter', false, NULL, NULL, 'Crowd surf to safety', '{"fame": 15, "health": -10}', 'You dove into the crowd - dangerous but iconic', 'Call for security backup', '{}', 'Security restored order and the event continued safely', true),
('Meet & Greet Gone Wrong', 'A fan at the meet and greet is being rude and demanding.', 'fan_encounter', true, NULL, NULL, 'Handle it professionally', '{"reputation": 10}', 'You stayed calm and professional - staff was impressed', 'Call them out', '{"fame": 20}', 'The video went viral and fans supported you', true),
('Fan Marriage Proposal', 'During the show, a fan holds up a sign proposing to you!', 'fan_encounter', false, NULL, NULL, 'Play along sweetly', '{"fame": 20}', 'You blew them a kiss - the crowd went wild', 'Awkwardly move on', '{"fame": -5}', 'The moment was a bit awkward but the show continued', true),
('Young Fan Inspiration', 'A young fan tells you that your music inspired them to start playing.', 'fan_encounter', true, NULL, NULL, 'Encourage their dreams', '{"reputation": 10, "fame": 5}', 'You gave them life advice - their parent posted a thank you', 'Sign autograph and move on', '{}', 'You signed their poster and they were happy', true),
('Stalker Warning', 'Security has identified someone following the tour who seems obsessive.', 'fan_encounter', false, NULL, NULL, 'Report to authorities', '{"reputation": 5}', 'Police were notified and increased security around you', 'Ignore it for now', '{}', 'You decided not to escalate - hopefully it''s nothing', true),

-- Media Events (6)
('Paparazzi Ambush', 'Photographers are waiting outside your hotel, cameras flashing!', 'media_incident', true, NULL, NULL, 'Smile and pose', '{"fame": 5}', 'Great photos of you hit the tabloids', 'Cover face and rush past', '{"fame": -3}', 'The blurry escape photos still ran, just less flattering', true),
('Interview Gone Wrong', 'During a live interview, the host asks a very controversial question.', 'media_incident', false, NULL, NULL, 'Stand by controversial take', '{"fame": 30, "reputation": -15}', 'Your bold stance resonated - you''re trending', 'Deflect diplomatically', '{"fame": 5, "reputation": 5}', 'You navigated it smoothly - no drama', true),
('Wardrobe Malfunction on TV', 'During a live TV performance, your outfit has a wardrobe malfunction!', 'media_incident', false, NULL, NULL, 'Laugh it off', '{"fame": 15}', 'You handled it with humor - fans loved your reaction', 'Storm off stage', '{"fame": -10}', 'The dramatic exit became the story, not your music', true),
('Viral Moment', 'Something you said or did is going viral online!', 'media_incident', true, NULL, NULL, 'Embrace meme status', '{"fame": 25}', 'You leaned into it and became even more famous', 'Try to suppress it', '{"money": -500, "fame": 5}', 'The lawyers couldn''t stop the internet', true),
('Tell-All Book Offer', 'A publisher offers big money for your autobiography with "all the secrets."', 'media_incident', false, NULL, NULL, 'Accept the deal', '{"money": 5000, "chemistry": -20}', 'The advance was nice but bandmates are worried about what you''ll reveal', 'Decline politely', '{"reputation": 10}', 'You valued privacy over money - the band appreciates it', true),
('Reality TV Offer', 'A major network wants you to star in a reality show about your touring life.', 'media_incident', false, NULL, NULL, 'Accept the season', '{"money": 10000, "fame": 50, "health": -20}', 'Filming was exhausting but the exposure was massive', 'Focus on the music', '{"reputation": 15}', 'You turned down easy fame to stay authentic - respect increased', true);