
-- Add interview_completed flag to pr_media_offers
ALTER TABLE public.pr_media_offers ADD COLUMN IF NOT EXISTS interview_completed boolean DEFAULT false;

-- Create interview_questions table
CREATE TABLE public.interview_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  question_text text NOT NULL,
  media_types text[] NOT NULL DEFAULT '{all}',
  category text NOT NULL,
  option_a_text text NOT NULL,
  option_a_effects jsonb NOT NULL DEFAULT '{}',
  option_b_text text NOT NULL,
  option_b_effects jsonb NOT NULL DEFAULT '{}',
  option_c_text text NOT NULL,
  option_c_effects jsonb NOT NULL DEFAULT '{}',
  option_d_text text NOT NULL,
  option_d_effects jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Create interview_results table
CREATE TABLE public.interview_results (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id),
  band_id uuid NOT NULL REFERENCES public.bands(id),
  offer_id uuid NOT NULL,
  media_type text NOT NULL,
  questions jsonb NOT NULL DEFAULT '[]',
  total_effects jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.interview_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_results ENABLE ROW LEVEL SECURITY;

-- RLS: anyone can read questions
CREATE POLICY "Anyone can read interview questions" ON public.interview_questions FOR SELECT USING (true);

-- RLS: users can read their own results
CREATE POLICY "Users can read own interview results" ON public.interview_results FOR SELECT USING (auth.uid() = user_id);

-- RLS: users can insert their own results
CREATE POLICY "Users can insert own interview results" ON public.interview_results FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Seed 100 interview questions
INSERT INTO public.interview_questions (question_text, media_types, category, option_a_text, option_a_effects, option_b_text, option_b_effects, option_c_text, option_c_effects, option_d_text, option_d_effects) VALUES
-- CAREER (20)
('What inspired you to start making music?', '{all}', 'career', 'I had a vision to change the sound of a generation.', '{"fame_mult":1.3,"fan_mult":1.2,"cash_mult":1.1,"reputation":{"authenticity":5}}', 'My family and friends always encouraged me to follow my passion.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":3}}', 'Honestly? The money and the lifestyle.', '{"fame_mult":1.0,"fan_mult":0.8,"cash_mult":1.2,"reputation":{"authenticity":-5,"attitude":3}}', '...I don''t really know.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-5}}'),

('Where do you see your career in five years?', '{all}', 'career', 'Playing stadiums worldwide and pushing boundaries.', '{"fame_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creativity":5}}', 'Growing steadily and staying true to our roots.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":4}}', 'Probably retired on a private island.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"attitude":5,"reliability":-3}}', 'I try not to think that far ahead.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-4}}'),

('What has been your proudest achievement so far?', '{all}', 'career', 'Hearing our song on the radio for the first time was magical.', '{"fame_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":6}}', 'Building a loyal fanbase that truly connects with our music.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":4}}', 'The size of my bank account, obviously.', '{"fame_mult":0.8,"fan_mult":0.7,"cash_mult":1.1,"reputation":{"authenticity":-6,"attitude":4}}', 'Nothing really stands out.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-5}}'),

('How do you handle the pressure of fame?', '{tv,podcast,magazine}', 'career', 'I channel it into creating better music.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":6}}', 'I have a great support system that keeps me grounded.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'I just party harder to forget about it.', '{"fame_mult":1.2,"fan_mult":0.8,"cash_mult":0.9,"reputation":{"attitude":6,"reliability":-5}}', '*uncomfortable silence*', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-6}}'),

('What advice would you give to aspiring musicians?', '{all}', 'career', 'Stay hungry, stay humble, and never stop creating.', '{"fame_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authenticity":7}}', 'Practice every day and don''t give up on your dreams.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Get a good lawyer before you get a good agent.', '{"fame_mult":1.0,"fan_mult":0.9,"cash_mult":1.1,"reputation":{"attitude":3,"creativity":-2}}', 'Don''t bother, the industry is broken.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"attitude":-5}}'),

('What was your biggest career setback?', '{podcast,magazine}', 'career', 'Every setback taught me something valuable that made our next album better.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":6,"creativity":2}}', 'We had some tough times but our fans kept us going.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Getting dropped by our label — but we showed them!', '{"fame_mult":1.3,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"attitude":5,"authenticity":-2}}', 'I''d rather not talk about it.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-4}}'),

('Do you have any pre-show rituals?', '{tv,radio,podcast}', 'career', 'We huddle together and remind ourselves why we do this.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'Just a quick warm-up and some deep breaths.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":3}}', 'A bottle of whiskey and a prayer.', '{"fame_mult":1.1,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":5,"reliability":-3}}', 'Not really, I just wing it.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-5}}'),

('How do you stay motivated during long tours?', '{all}', 'career', 'The energy from the crowd every night is all I need.', '{"fame_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authenticity":6}}', 'We set small goals and celebrate each milestone.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":5}}', 'The paycheck at the end keeps me going.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.2,"reputation":{"authenticity":-4}}', 'Honestly, I don''t. Tours are miserable.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-6}}'),

('What legacy do you want to leave behind?', '{magazine,newspaper,internet}', 'career', 'Music that outlives me and inspires future generations.', '{"fame_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creativity":7,"authenticity":3}}', 'Proof that hard work and talent can overcome anything.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'The biggest mansion in the music world.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.1,"reputation":{"attitude":4,"authenticity":-5}}', 'Legacy? I''m just trying to get through today.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-5}}'),

('What was the moment you knew music was your calling?', '{podcast,tv}', 'career', 'The first time I wrote a song and someone cried listening to it.', '{"fame_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authenticity":7}}', 'When I realized I couldn''t imagine doing anything else.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":3}}', 'When I saw how much money rockstars make.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.1,"reputation":{"authenticity":-5,"attitude":3}}', 'I''m still not sure it is.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-5}}'),

('How has your sound evolved over the years?', '{radio,podcast,magazine}', 'career', 'We''re constantly experimenting — every album is a new chapter.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":7}}', 'We''ve grown naturally while keeping our core identity.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'We just follow whatever trend is popular.', '{"fame_mult":1.0,"fan_mult":0.8,"cash_mult":1.1,"reputation":{"authenticity":-6,"creativity":-3}}', 'It hasn''t really changed much.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-5}}'),

('What do you think sets you apart from other bands?', '{all}', 'career', 'Our willingness to take risks and break conventions.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":6,"authenticity":3}}', 'Our chemistry and the bond we share as a band.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Nothing — we''re just better at marketing.', '{"fame_mult":1.0,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"authenticity":-6}}', 'I don''t think we''re that different honestly.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-4}}'),

('Any plans for a world tour?', '{tv,radio,internet}', 'career', 'We''re working on something massive — the fans won''t be disappointed!', '{"fame_mult":1.4,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creativity":4}}', 'We''re looking into it and want to make sure we do it right.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Only if the promoters pay enough.', '{"fame_mult":0.9,"fan_mult":0.8,"cash_mult":1.2,"reputation":{"attitude":3,"authenticity":-3}}', 'No plans at the moment.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('Tell us about your upcoming album.', '{all}', 'career', 'It''s our most ambitious work yet — a sonic journey like nothing before.', '{"fame_mult":1.3,"fan_mult":1.2,"cash_mult":1.1,"reputation":{"creativity":6}}', 'We''ve put our hearts into it and can''t wait for everyone to hear it.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'It''ll make a lot of money, that''s all I care about.', '{"fame_mult":0.8,"fan_mult":0.7,"cash_mult":1.2,"reputation":{"authenticity":-5}}', 'I can''t really say much about it.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('Have you ever considered going solo?', '{podcast,magazine,tv}', 'career', 'The band is everything to me — we''re stronger together.', '{"fame_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"reliability":7}}', 'Maybe someday, but right now I''m focused on the band.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"authenticity":3}}', 'Already working on my solo project behind the scenes.', '{"fame_mult":1.2,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"reliability":-7,"attitude":5}}', '*awkward laugh* Next question?', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-4}}'),

('What does a typical day look like for you?', '{podcast,magazine}', 'career', 'I wake up, hit the studio, create, and lose track of time.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":5,"reliability":2}}', 'Pretty structured — practice, meetings, some downtime with family.', '{"fame_mult":1.0,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Sleep till noon, party till dawn. Rinse and repeat.', '{"fame_mult":1.1,"fan_mult":0.8,"cash_mult":0.9,"reputation":{"attitude":5,"reliability":-5}}', 'I don''t really have a routine.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-4}}'),

('How do you choose your setlist for live shows?', '{radio,podcast}', 'career', 'We mix fan favorites with deep cuts to create an emotional journey.', '{"fame_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"creativity":5}}', 'We look at what the crowd wants and give them a great show.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Whatever songs are easiest to play when we''re tired.', '{"fame_mult":0.8,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"reliability":-4,"authenticity":-3}}', 'Our manager handles all that.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-4}}'),

('What was the hardest song you ever had to write?', '{podcast,magazine,internet}', 'career', 'A deeply personal track about loss — it changed me as an artist.', '{"fame_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":7,"creativity":3}}', 'Every song has its challenges, but that''s what makes the process rewarding.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":4}}', 'The ones the label forced us to write.', '{"fame_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":4,"reliability":-2}}', 'They''re all pretty easy for me.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-5}}'),

('Do you feel the music industry has changed since you started?', '{tv,newspaper,magazine}', 'career', 'Absolutely — and we''re excited to be part of shaping its future.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":5,"authenticity":3}}', 'It''s evolved a lot, but great music always finds its audience.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Yeah, it''s all about streaming numbers now. Art is dead.', '{"fame_mult":1.0,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":5,"authenticity":-3}}', 'I don''t really pay attention to industry stuff.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-4}}'),

('What drives your creative process?', '{all}', 'career', 'Raw emotion — every experience becomes a potential song.', '{"fame_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creativity":7,"authenticity":3}}', 'Discipline and collaboration with the band.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Whatever gets the most streams.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.1,"reputation":{"authenticity":-6}}', 'I just kind of go with the flow.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-4}}'),

-- CONTROVERSY (15)
('Your latest single has divided critics. How do you respond?', '{all}', 'controversy', 'Art should provoke — I''m proud that it sparks conversation.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":7,"creativity":3}}', 'We appreciate all feedback and keep growing from it.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'The critics are idiots who don''t understand real music.', '{"fame_mult":1.2,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":6,"reliability":-4}}', '*rolls eyes* Whatever.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"attitude":-5}}'),

('There are rumors about tension within the band. Care to comment?', '{tv,newspaper,magazine}', 'controversy', 'Every family argues, but we always come back stronger.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":6,"reliability":3}}', 'We have a great working relationship and mutual respect.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Yeah, our drummer is driving everyone crazy.', '{"fame_mult":1.3,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"attitude":5,"reliability":-7}}', 'No comment.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-5}}'),

('Some fans think you''ve sold out. What do you say to them?', '{podcast,radio,internet}', 'controversy', 'Evolution isn''t selling out — it''s growing as artists.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":6,"creativity":3}}', 'We love all our fans and hope they''ll give new music a chance.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":4}}', 'If making money is selling out, then yeah, guilty as charged.', '{"fame_mult":1.0,"fan_mult":0.7,"cash_mult":1.2,"reputation":{"authenticity":-6,"attitude":5}}', 'I don''t care what they think.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-5}}'),

('You were spotted at a rival band''s show. What''s the story?', '{newspaper,internet,magazine}', 'controversy', 'Great music deserves to be appreciated, no matter who makes it.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":7}}', 'We respect other musicians — there''s room for everyone.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Know your enemy, right? I was scoping out the competition.', '{"fame_mult":1.2,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":5,"authenticity":-3}}', 'I was dragged there against my will.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-5}}'),

('There''s been talk about your behavior at award shows. Thoughts?', '{tv,newspaper}', 'controversy', 'I bring energy and passion — sometimes that rubs people the wrong way.', '{"fame_mult":1.3,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"authenticity":5,"attitude":3}}', 'I''m always working on being the best version of myself.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Award shows are boring — someone has to make them interesting.', '{"fame_mult":1.4,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":8,"reliability":-5}}', 'People should mind their own business.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"attitude":-5}}'),

('A former collaborator said you''re difficult to work with. Your response?', '{podcast,tv,magazine}', 'controversy', 'I have high standards — that drives excellence in our music.', '{"fame_mult":1.2,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"creativity":5,"attitude":2}}', 'Every collaboration is a learning experience and I wish them well.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5,"authenticity":2}}', 'They''re just bitter because they couldn''t keep up.', '{"fame_mult":1.1,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":6,"reliability":-5}}', 'That''s their problem, not mine.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-5}}'),

('Your social media post last week caused quite a stir. Regrets?', '{internet,tv,newspaper}', 'controversy', 'I stand by what I said — artists should speak their truth.', '{"fame_mult":1.3,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"authenticity":7}}', 'I could have worded it better, and I''ve learned from it.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5,"authenticity":2}}', 'The internet overreacts to everything. It was hilarious.', '{"fame_mult":1.2,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":5,"reliability":-3}}', 'My manager posted that, not me.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-6}}'),

('How do you deal with negative press?', '{all}', 'controversy', 'I use it as fuel — the best revenge is legendary music.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":5,"authenticity":3}}', 'We focus on what we can control and let the music speak.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'I call out every journalist who writes garbage about us.', '{"fame_mult":1.2,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"attitude":6,"reliability":-5}}', 'I don''t read the press.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-3}}'),

('There are accusations of plagiarism in your latest track. Comment?', '{newspaper,tv,internet}', 'controversy', 'All music builds on what came before — we''ve always credited our inspirations.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":6,"creativity":3}}', 'We take these claims seriously and are looking into it professionally.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":6}}', 'They wish they could write something this good.', '{"fame_mult":1.1,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":6,"reliability":-4}}', 'Our lawyers will handle it.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('You cancelled your last tour date. Fans are upset.', '{radio,tv,internet}', 'controversy', 'Health comes first, but we''re making it up with a free show.', '{"fame_mult":1.2,"fan_mult":1.3,"cash_mult":0.9,"reputation":{"authenticity":6,"reliability":3}}', 'We''re deeply sorry and working to reschedule as soon as possible.', '{"fame_mult":1.0,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":6}}', 'It is what it is. Life happens.', '{"fame_mult":0.8,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"reliability":-5,"attitude":3}}', 'I don''t owe anyone an explanation.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-7}}'),

('Some say your music promotes a negative lifestyle. True?', '{tv,newspaper,magazine}', 'controversy', 'Our music reflects reality — we tell authentic stories.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":7}}', 'We''re artists, not role models, but we take responsibility seriously.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'If parents can''t handle it, that''s not our problem.', '{"fame_mult":1.1,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":5,"reliability":-4}}', 'We just make what sounds good. Don''t read into it.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-4}}'),

('Your ex-manager is writing a tell-all book. Worried?', '{podcast,magazine,newspaper}', 'controversy', 'The truth always comes out, and I''m proud of who I am.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":8}}', 'Everyone has their perspective. We wish them the best.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":5}}', 'That book will be full of lies and our lawyers are ready.', '{"fame_mult":1.1,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":4,"reliability":-3}}', 'I haven''t heard about that.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-5}}'),

('Fans found old controversial posts online. Any regrets?', '{internet,tv}', 'controversy', 'I was young and have grown immensely since then.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":6,"reliability":2}}', 'I take full accountability and have learned from my mistakes.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":6}}', 'Cancel culture is ridiculous — people need to move on.', '{"fame_mult":1.1,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"attitude":5,"reliability":-5}}', 'I don''t remember posting those.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-7}}'),

('Why did you skip the charity event last month?', '{tv,newspaper}', 'controversy', 'I was dealing with personal issues but donated privately instead.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":0.9,"reputation":{"authenticity":6,"reliability":3}}', 'Scheduling conflict — I''m committed to the next one.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Charity events are just PR stunts anyway.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"authenticity":-5,"attitude":4}}', 'I wasn''t aware of it.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-5}}'),

('How do you respond to being called arrogant?', '{podcast,radio}', 'controversy', 'Confidence gets mistaken for arrogance. I believe in what we create.', '{"fame_mult":1.3,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"authenticity":5,"attitude":3}}', 'I try to stay humble and let the music do the talking.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'I am the greatest, so it''s not arrogance — it''s fact.', '{"fame_mult":1.4,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"attitude":8,"reliability":-5}}', 'People can call me whatever they want.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"attitude":-4}}'),

-- PERSONAL (15)
('What do you do in your downtime?', '{podcast,magazine}', 'personal', 'I''m constantly creating — music, art, anything that moves me.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":6}}', 'Spend time with family and recharge with nature.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'What downtime? It''s all parties and VIP sections.', '{"fame_mult":1.1,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":5,"reliability":-3}}', 'I mostly just sleep.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-3}}'),

('Who is your biggest musical influence?', '{all}', 'personal', 'I draw from everyone — Bowie, Radiohead, hip-hop, classical. It all feeds the fire.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":6,"authenticity":3}}', 'My parents were musicians, so music was always in my blood.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'Myself, honestly. I don''t need influences.', '{"fame_mult":1.0,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"attitude":6,"creativity":-4}}', 'I don''t really have one.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-4}}'),

('How has fame changed your relationships?', '{podcast,tv,magazine}', 'personal', 'It''s a filter — you learn who really cares about you.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":7}}', 'I work hard to keep my relationships strong despite the chaos.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Who needs real friends when you have millions of fans?', '{"fame_mult":1.0,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":5,"authenticity":-5}}', 'I don''t want to talk about my personal life.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-4}}'),

('What''s the craziest thing a fan has ever done?', '{radio,podcast,tv}', 'personal', 'One fan tattooed our lyrics on their arm — that level of connection is humbling.', '{"fame_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'We have incredibly passionate fans and we''re grateful for every one.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Someone broke into our tour bus. Kinda scary, kinda flattering.', '{"fame_mult":1.3,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":3,"reliability":-2}}', 'I''d rather not encourage that kind of behavior.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-3}}'),

('Do you ever feel like giving up?', '{podcast,magazine}', 'personal', 'Every artist has dark moments, but creating pulls me back every time.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":7,"creativity":2}}', 'The support from fans and bandmates keeps me going.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Yeah, at least three times a week.', '{"fame_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"authenticity":3,"reliability":-3}}', 'I''d rather not answer that.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-4}}'),

('Tell us something fans don''t know about you.', '{podcast,tv,magazine}', 'personal', 'I secretly write poetry and paint when nobody''s around.', '{"fame_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"creativity":5,"authenticity":4}}', 'I''m actually really shy offstage. The stage persona is armor.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":6}}', 'I sleep with my Grammy under my pillow.', '{"fame_mult":1.2,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"attitude":4,"authenticity":-2}}', 'There''s nothing interesting to tell.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-4}}'),

('How do you handle being in the spotlight 24/7?', '{tv,magazine,newspaper}', 'personal', 'I''ve learned to protect my peace while sharing my art openly.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":6,"reliability":2}}', 'Boundaries are key — I carve out private time every day.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":5}}', 'I love every second of it — bring on the cameras!', '{"fame_mult":1.3,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":5,"authenticity":-3}}', 'I hate it, honestly.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-4}}'),

('What was your childhood like?', '{podcast,magazine}', 'personal', 'Tough but character-building — it gave me stories to tell through music.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":7}}', 'Pretty normal — supportive family, lots of backyard jam sessions.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Privileged, honestly. I was handed everything.', '{"fame_mult":0.9,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"authenticity":3,"attitude":-3}}', 'I don''t like talking about the past.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-5}}'),

('What book or film has impacted you most?', '{podcast,magazine,internet}', 'personal', 'A film about an artist''s struggle — it reminded me why raw expression matters.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":6,"authenticity":3}}', 'A biography of a legendary musician who never gave up.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'The Wolf of Wall Street — love the hustle mentality.', '{"fame_mult":1.0,"fan_mult":0.8,"cash_mult":1.1,"reputation":{"attitude":4,"authenticity":-3}}', 'I don''t really read or watch films.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-4}}'),

('Are you dating anyone right now?', '{tv,magazine,internet}', 'personal', 'My heart belongs to the music right now — it''s a jealous lover!', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":3,"authenticity":4}}', 'I keep that part of my life private, but I''m happy.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":4}}', 'I''m dating someone very famous, but I can''t say who yet!', '{"fame_mult":1.4,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"attitude":5,"authenticity":-4}}', 'That''s none of your business.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('What do you splurge on?', '{podcast,tv}', 'personal', 'Musical instruments and studio gear — you can never have too many guitars.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":5,"authenticity":3}}', 'Experiences with friends and family. Memories over things.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'Supercars and designer everything. Living the dream!', '{"fame_mult":1.2,"fan_mult":0.8,"cash_mult":0.9,"reputation":{"attitude":5,"authenticity":-3}}', 'I don''t really spend much.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-3}}'),

('How do you stay healthy while touring?', '{magazine,podcast}', 'personal', 'Strict routine — I treat my body like an instrument that needs tuning.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5,"authenticity":3}}', 'Lots of water, rest when I can, and a good crew watching out for me.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Healthy? Have you seen my rider? It''s all junk food and energy drinks!', '{"fame_mult":1.1,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":4,"reliability":-4}}', 'I don''t worry about that stuff.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-5}}'),

('What was the first album you ever bought?', '{radio,podcast}', 'personal', 'A classic that blew my mind and shaped everything I create.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creativity":4,"authenticity":4}}', 'A pop album I''m not embarrassed to admit I still love.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'Does downloading it illegally count?', '{"fame_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":3,"reliability":-3}}', 'I honestly can''t remember.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-3}}'),

('If you weren''t a musician, what would you be?', '{all}', 'personal', 'Still creating — maybe a filmmaker or a painter.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":6}}', 'Probably a teacher — I love sharing knowledge.', '{"fame_mult":1.0,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":4,"authenticity":3}}', 'A Wall Street trader, obviously.', '{"fame_mult":0.9,"fan_mult":0.8,"cash_mult":1.1,"reputation":{"attitude":3,"authenticity":-3}}', 'I can''t imagine doing anything else.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-3}}'),

('What scares you the most?', '{podcast,magazine}', 'personal', 'Becoming irrelevant — which drives me to keep pushing boundaries.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":6,"creativity":3}}', 'Letting down the people who believe in us.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":6}}', 'Nothing scares me. I''m fearless.', '{"fame_mult":1.0,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":5,"authenticity":-4}}', 'I''d rather not say.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-4}}'),

-- MUSIC (20)
('Tell us about your songwriting process.', '{all}', 'music', 'It starts with an emotion — I capture the feeling first, then build the arrangement.', '{"fame_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creativity":7,"authenticity":3}}', 'We jam together and build on whatever clicks.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'AI writes the melodies and I just add the vocals.', '{"fame_mult":0.8,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"authenticity":-7,"creativity":-5}}', 'I don''t really have a process.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-5}}'),

('What genre best describes your sound?', '{radio,podcast,tv}', 'music', 'We transcend genres — we''re creating our own sonic universe.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":7}}', 'We blend multiple influences but stay rooted in rock.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'Whatever genre is trending on Spotify this week.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.1,"reputation":{"authenticity":-6}}', 'I don''t know. Music is music.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-4}}'),

('How important are lyrics to you?', '{podcast,magazine,internet}', 'music', 'Lyrics are the soul of a song — every word carries weight.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creativity":6,"authenticity":4}}', 'They matter a lot, but the melody has to work first.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":3,"creativity":2}}', 'Not really — most people don''t listen to lyrics anyway.', '{"fame_mult":0.8,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"creativity":-5,"authenticity":-3}}', 'I don''t write the lyrics.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-5}}'),

('What instrument do you wish you could master?', '{podcast,radio}', 'music', 'The cello — I want to bring orchestral emotion into our music.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":6}}', 'Piano — it''s the foundation of all great songwriting.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":3,"creativity":3}}', 'The wallet. It''s the most important instrument in the industry.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.1,"reputation":{"attitude":4,"creativity":-3}}', 'I''m fine with what I know.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-4}}'),

('Can you give us an exclusive about your next release?', '{radio,tv,internet}', 'music', 'Let''s just say it''s unlike anything we''ve done before — prepare to be blown away.', '{"fame_mult":1.4,"fan_mult":1.3,"cash_mult":1.1,"reputation":{"creativity":5}}', 'We''re putting the finishing touches on something special.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'My label would kill me if I said anything.', '{"fame_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"authenticity":-2}}', 'We don''t have anything planned right now.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-4}}'),

('What''s your favorite song you''ve ever written?', '{all}', 'music', 'The next one — because I''m always trying to outdo myself.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":7}}', 'A track from our first album — it captures why we started.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":6}}', 'Whichever one made the most money.', '{"fame_mult":0.8,"fan_mult":0.7,"cash_mult":1.1,"reputation":{"authenticity":-5}}', 'I don''t really have one.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-4}}'),

('Do you prefer studio work or live performance?', '{radio,podcast,tv}', 'music', 'Live — there''s nothing like feeding off the crowd''s energy.', '{"fame_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'Both have their magic. The studio is where ideas are born, the stage is where they live.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":4,"reliability":2}}', 'Studio. Live shows are exhausting and people smell.', '{"fame_mult":0.8,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"attitude":3,"authenticity":-4}}', 'I haven''t really thought about it.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-3}}'),

('How do you feel about streaming vs. physical albums?', '{podcast,magazine,internet}', 'music', 'Streaming democratized music, but vinyl has a soul you can''t digitize.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":4,"authenticity":4}}', 'Whatever gets our music to the most ears works for us.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Streaming pays nothing. Buy our merch instead.', '{"fame_mult":0.9,"fan_mult":0.8,"cash_mult":1.1,"reputation":{"attitude":3,"authenticity":-2}}', 'I don''t care how people listen.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-3}}'),

('What was the most challenging recording session?', '{podcast,magazine}', 'music', 'Our concept album — we rebuilt it from scratch three times until it was perfect.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":6,"reliability":3}}', 'Any session where emotions run high — the best music comes from real moments.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'When the studio ran out of champagne. Dark times.', '{"fame_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":4,"reliability":-2}}', 'They all kind of blur together.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-4}}'),

('Would you ever collaborate with an artist from a completely different genre?', '{radio,podcast,tv}', 'music', 'Absolutely — collision of worlds creates the most exciting art.', '{"fame_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creativity":7}}', 'If the chemistry is right, genre doesn''t matter.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":4}}', 'Only if they''re more famous than us.', '{"fame_mult":1.0,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"attitude":4,"authenticity":-4}}', 'Probably not. We stick to what we know.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-5}}'),

('What makes a great producer?', '{podcast,magazine}', 'music', 'Someone who understands your vision and elevates it beyond what you imagined.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":6,"reliability":2}}', 'Patience, great ears, and the ability to bring out the best in artists.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Big credits and industry connections.', '{"fame_mult":0.9,"fan_mult":0.8,"cash_mult":1.1,"reputation":{"attitude":3,"creativity":-3}}', 'I don''t think about it much.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-3}}'),

('Is there a song you wish you hadn''t released?', '{podcast,tv,radio}', 'music', 'Every release is part of our story — even the imperfect ones shaped who we are.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":6,"creativity":2}}', 'Maybe one or two, but they were learning experiences.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Yeah, the one that tanked on the charts. Embarrassing.', '{"fame_mult":0.9,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"authenticity":-3,"attitude":2}}', 'I don''t remember our back catalog.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-4}}'),

('How do you feel about music being used in ads or films?', '{magazine,internet,podcast}', 'music', 'When it serves the story, it gives our art a new dimension.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.1,"reputation":{"creativity":5,"authenticity":2}}', 'It''s a great way to reach new audiences.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.1,"reputation":{"reliability":4}}', 'Show me the check and I''ll sign anything.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.3,"reputation":{"authenticity":-5}}', 'I don''t have a strong opinion.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-3}}'),

('What''s your dream collaboration?', '{all}', 'music', 'An icon who changed the game — I want to create something timeless together.', '{"fame_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creativity":5,"authenticity":3}}', 'Anyone who shares our passion for authentic music.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'Whoever has the biggest fanbase — maximize exposure.', '{"fame_mult":1.0,"fan_mult":0.8,"cash_mult":1.1,"reputation":{"attitude":3,"authenticity":-4}}', 'I''m fine working on our own.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-3}}'),

('How has technology changed how you make music?', '{internet,podcast,magazine}', 'music', 'It''s opened infinite doors — we can create sounds no one has heard before.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":7}}', 'It''s a great tool, but the human element will always be at the core.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'I just press buttons now. The software does all the work.', '{"fame_mult":0.8,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"creativity":-5,"authenticity":-3}}', 'I don''t use much technology.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-5}}'),

('What''s the most underrated instrument?', '{radio,podcast}', 'music', 'The bass — it''s the heartbeat that holds everything together.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":5,"authenticity":3}}', 'Vocals! People forget the voice is an instrument too.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":4}}', 'The sound of cash registers ringing.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"attitude":4,"creativity":-3}}', 'I haven''t thought about it.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-3}}'),

('Do you ever get stage fright?', '{tv,radio,podcast}', 'music', 'Every time — but that adrenaline is what makes the performance electric.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":6}}', 'I used to, but preparation and experience have helped a lot.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Never. Fear is for amateurs.', '{"fame_mult":1.0,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":5,"authenticity":-4}}', 'I don''t think about it.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-3}}'),

('What role does improvisation play in your music?', '{podcast,radio}', 'music', 'It''s where the magic happens — some of our best moments are unplanned.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":7}}', 'We balance structured songs with room to breathe and explore.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4,"creativity":2}}', 'None. Everything is calculated for maximum impact.', '{"fame_mult":0.9,"fan_mult":0.9,"cash_mult":1.1,"reputation":{"creativity":-4}}', 'I don''t know what that means.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-5}}'),

('How do you handle creative disagreements within the band?', '{podcast,magazine,tv}', 'music', 'Tension creates diamonds — we argue, then make something brilliant.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":5,"authenticity":4}}', 'We vote and respect the majority decision.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":6}}', 'What I say goes. I''m the creative force here.', '{"fame_mult":1.0,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"attitude":6,"reliability":-5}}', 'We try to avoid disagreements.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-3}}'),

('What''s the weirdest sound you''ve used in a song?', '{radio,podcast,internet}', 'music', 'We recorded a thunderstorm through a vintage amp — it became the intro.', '{"fame_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creativity":8}}', 'We experiment with found sounds and unusual textures all the time.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"creativity":5}}', 'My producer said using a cat meow would go viral. It didn''t.', '{"fame_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":3,"creativity":-1}}', 'We keep things pretty standard.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-5}}'),

-- INDUSTRY (15)
('What do you think about the current state of record labels?', '{podcast,magazine,newspaper}', 'industry', 'The power is shifting to artists — labels need to earn our trust.', '{"fame_mult":1.3,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":6,"creativity":2}}', 'There are good and bad labels. Ours supports our vision.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Labels are vampires — they suck artists dry.', '{"fame_mult":1.2,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":5,"reliability":-3}}', 'I don''t pay attention to the business side.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-4}}'),

('How do you feel about streaming royalties?', '{podcast,internet,newspaper}', 'industry', 'They need reform, and artists should lead that conversation.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":6}}', 'It''s not perfect, but streaming brought music to billions.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'They''re a joke. I make more from merch sold at one show.', '{"fame_mult":1.1,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":4,"authenticity":-2}}', 'I let my accountant worry about that.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('What advice would you give to new bands trying to get signed?', '{radio,podcast,tv}', 'industry', 'Build your own audience first — labels should come to you, not the other way around.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":5,"creativity":3}}', 'Stay true to your sound and be professional in every interaction.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Get a good lawyer. You''re going to need one.', '{"fame_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":3}}', 'Good luck. It''s nearly impossible.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-4}}'),

('Do you think awards matter in music?', '{tv,radio,magazine}', 'industry', 'They''re a nice validation, but the real award is connecting with people.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":6}}', 'They recognize excellence and push artists to be better.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":4}}', 'They''re rigged popularity contests. We should have won way more.', '{"fame_mult":1.1,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":5,"reliability":-4}}', 'Not really, no.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-3}}'),

('What do you think about AI-generated music?', '{internet,podcast,magazine}', 'industry', 'Technology should amplify human creativity, not replace it.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creativity":5,"authenticity":4}}', 'It''s a tool — like any tool, it depends on who''s using it.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Bring it on. I''ll still outplay any algorithm.', '{"fame_mult":1.1,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":5,"creativity":-2}}', 'I don''t know much about AI.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"creativity":-4}}'),

('How important is social media for your career?', '{internet,tv,radio}', 'industry', 'It''s a direct line to fans — we share the real us, not a curated version.', '{"fame_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'It''s essential for reach, but the music always comes first.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'It''s all about clout and going viral. Content is king.', '{"fame_mult":1.1,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"authenticity":-4,"attitude":3}}', 'I don''t really use social media.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('What do you think about ticket pricing for concerts?', '{tv,newspaper,radio}', 'industry', 'We fight to keep prices fair — music should be accessible to everyone.', '{"fame_mult":1.1,"fan_mult":1.3,"cash_mult":0.9,"reputation":{"authenticity":7}}', 'It''s a balance between sustainability and accessibility.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Premium experiences cost premium prices. That''s capitalism.', '{"fame_mult":1.0,"fan_mult":0.7,"cash_mult":1.2,"reputation":{"attitude":4,"authenticity":-4}}', 'That''s the promoter''s decision, not ours.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('How do you navigate the business side of music?', '{podcast,magazine}', 'industry', 'I surround myself with trusted people, but I understand every contract I sign.', '{"fame_mult":1.2,"fan_mult":1.0,"cash_mult":1.1,"reputation":{"reliability":6,"authenticity":2}}', 'I have a great team that handles the details.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":4}}', 'I just sign whatever they put in front of me.', '{"fame_mult":0.8,"fan_mult":0.9,"cash_mult":0.9,"reputation":{"reliability":-6}}', 'Business is boring. I just want to play.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-4}}'),

('What do you think about music festivals vs. solo tours?', '{radio,podcast}', 'industry', 'Festivals bring communities together — there''s magic in discovering new bands.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":5,"creativity":2}}', 'Both have their place — we enjoy both experiences.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Headlining our own tour is better. We don''t share the spotlight.', '{"fame_mult":1.1,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":5,"authenticity":-3}}', 'I don''t have a preference.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('Do you think the industry is fair to independent artists?', '{podcast,internet,newspaper}', 'industry', 'Not yet — but independent artists are changing the rules every day.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":6}}', 'There are more opportunities than ever if you''re willing to hustle.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":4}}', 'The industry crushes indie artists. Only the corporate ones survive.', '{"fame_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":4,"reliability":-2}}', 'I haven''t thought about it.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('How do you decide on merchandise and branding?', '{magazine,internet}', 'industry', 'Our merch is an extension of our art — every design tells a story.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.1,"reputation":{"creativity":5,"authenticity":3}}', 'We listen to what fans want and try to deliver quality.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Mark it up 500% and watch the money roll in.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.3,"reputation":{"authenticity":-5}}', 'Our manager handles all that.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('What''s your take on music education?', '{podcast,magazine,newspaper}', 'industry', 'Every school should have a music program — it changes lives.', '{"fame_mult":1.1,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authenticity":7,"reliability":2}}', 'Formal training and self-taught both have merit.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":4}}', 'You don''t need education. Either you have talent or you don''t.', '{"fame_mult":1.0,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":4,"reliability":-3}}', 'I skipped school, so I wouldn''t know.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-3}}'),

('How important is a manager for a band?', '{podcast,radio}', 'industry', 'A great manager is your strategic partner — they protect your vision.', '{"fame_mult":1.2,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":5,"authenticity":3}}', 'Essential for handling the business so we can focus on music.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Managers take 20% for doing nothing. We should all self-manage.', '{"fame_mult":1.0,"fan_mult":0.9,"cash_mult":1.1,"reputation":{"attitude":4,"reliability":-3}}', 'I don''t know. Ours just appeared one day.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-4}}'),

('What''s your opinion on music copyright laws?', '{internet,newspaper,magazine}', 'industry', 'Artists deserve to be paid for their work — strong copyright protects creativity.', '{"fame_mult":1.2,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"authenticity":5,"reliability":3}}', 'It''s complicated, but protecting intellectual property matters.', '{"fame_mult":1.1,"fan_mult":1.0,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Copyright is just labels making money off artists'' backs.', '{"fame_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":4,"authenticity":-2}}', 'I''ve never read a copyright document in my life.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-5}}'),

('Do you think live music will survive in the digital age?', '{tv,radio,internet}', 'industry', 'Live music is irreplaceable — no algorithm can recreate that human connection.', '{"fame_mult":1.3,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":6,"creativity":2}}', 'Absolutely — people will always crave shared live experiences.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":4}}', 'Eventually robots will replace us. It''s only a matter of time.', '{"fame_mult":0.9,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":3,"creativity":-3}}', 'I haven''t thought about it.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

-- FAN ENGAGEMENT (15)
('What do your fans mean to you?', '{all}', 'fan_engagement', 'They''re not fans — they''re family. Every song is a letter to them.', '{"fame_mult":1.2,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"authenticity":7}}', 'Without them, we''d just be making noise in a garage.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":5}}', 'They buy the tickets and the merch — they''re customers, really.', '{"fame_mult":0.8,"fan_mult":0.6,"cash_mult":1.1,"reputation":{"authenticity":-7}}', 'They''re alright, I guess.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-5}}'),

('How do you stay connected with fans between albums?', '{internet,podcast,radio}', 'fan_engagement', 'Behind-the-scenes content, listening parties, and surprise drops.', '{"fame_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"creativity":4,"authenticity":3}}', 'Social media updates and engaging with their messages directly.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":5}}', 'We don''t. They can wait like everyone else.', '{"fame_mult":0.8,"fan_mult":0.6,"cash_mult":1.0,"reputation":{"attitude":4,"reliability":-5}}', 'I''m not great at social media stuff.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('Do you read fan mail or messages?', '{podcast,tv}', 'fan_engagement', 'Every single one — some have brought me to tears.', '{"fame_mult":1.1,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"authenticity":7}}', 'As many as I can — fan stories motivate us to keep going.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":5}}', 'My assistant handles that.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"authenticity":-4}}', 'I don''t have time for that.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-5}}'),

('What''s the best fan experience you''ve witnessed?', '{radio,tv,podcast}', 'fan_engagement', 'A couple got engaged at our show — we wrote them into our next song.', '{"fame_mult":1.3,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"authenticity":6,"creativity":3}}', 'Seeing a whole crowd sing our lyrics back to us. Pure magic.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'When fans fight over our merch. Shows we''re in demand.', '{"fame_mult":1.0,"fan_mult":0.8,"cash_mult":1.0,"reputation":{"attitude":4,"authenticity":-3}}', 'Nothing comes to mind.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-4}}'),

('Have you ever changed a song based on fan feedback?', '{podcast,internet}', 'fan_engagement', 'Absolutely — our fans'' ears are as important as ours.', '{"fame_mult":1.1,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authenticity":5,"reliability":3}}', 'We listen to constructive criticism and consider all feedback.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Never. We know better than the audience.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"attitude":5,"authenticity":-4}}', 'Fans don''t really give us feedback.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('How do you handle meeting fans after shows?', '{tv,radio,magazine}', 'fan_engagement', 'I stay until the last person has been met — they waited for us, I can wait for them.', '{"fame_mult":1.2,"fan_mult":1.4,"cash_mult":0.9,"reputation":{"authenticity":8}}', 'We do organized meet-and-greets to make sure everyone gets a moment.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":5}}', 'VIP pass holders only. Time is money.', '{"fame_mult":1.0,"fan_mult":0.7,"cash_mult":1.2,"reputation":{"attitude":4,"authenticity":-5}}', 'I usually slip out the back.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-5}}'),

('What would you say to a fan who has your lyrics tattooed?', '{podcast,tv}', 'fan_engagement', 'That level of connection is the highest honor an artist can receive.', '{"fame_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authenticity":7}}', 'It''s incredibly flattering and reminds us why we do this.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":4}}', 'I hope they got a good tattoo artist — we don''t want bad ink associated with us.', '{"fame_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":4,"authenticity":-2}}', 'That''s their choice, I suppose.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-4}}'),

('Do you think fan clubs still matter?', '{internet,magazine}', 'fan_engagement', 'More than ever — dedicated spaces create deeper community bonds.', '{"fame_mult":1.1,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authenticity":5,"reliability":3}}', 'Absolutely — our fan community is the backbone of everything we do.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Only if they''re paying subscription fees.', '{"fame_mult":0.8,"fan_mult":0.7,"cash_mult":1.2,"reputation":{"authenticity":-5,"attitude":3}}', 'I didn''t know we had a fan club.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-4}}'),

('How do you decide what cities to tour in?', '{radio,podcast,tv}', 'fan_engagement', 'We follow the energy — wherever fans are passionate, we show up.', '{"fame_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authenticity":5}}', 'Data on ticket demand plus a desire to visit new places.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Wherever the guarantee is highest. Simple economics.', '{"fame_mult":1.0,"fan_mult":0.7,"cash_mult":1.2,"reputation":{"authenticity":-4}}', 'Our booking agent decides all that.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('What do you think makes your fanbase special?', '{all}', 'fan_engagement', 'They don''t just listen — they understand. They''re part of the art.', '{"fame_mult":1.2,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"authenticity":7}}', 'Their loyalty and passion through every phase of our career.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":5}}', 'They have good taste, obviously.', '{"fame_mult":1.0,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":4,"authenticity":-2}}', 'I don''t think about it much.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-4}}'),

('Any message for fans watching right now?', '{tv,radio}', 'fan_engagement', 'You are the reason we exist. Every note is for you. We love you endlessly.', '{"fame_mult":1.3,"fan_mult":1.4,"cash_mult":1.0,"reputation":{"authenticity":8}}', 'Thank you for your support — we couldn''t do this without you.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":5}}', 'Buy our new album. It drops Friday.', '{"fame_mult":1.0,"fan_mult":0.8,"cash_mult":1.1,"reputation":{"authenticity":-3,"attitude":2}}', '*waves awkwardly*', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('How do you handle fan expectations?', '{podcast,magazine}', 'fan_engagement', 'We aim to exceed them while staying true to who we are.', '{"fame_mult":1.2,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"creativity":4,"authenticity":4}}', 'We communicate openly and deliver on our promises.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":6}}', 'Their expectations are their problem, not ours.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"attitude":5,"reliability":-4}}', 'I try not to think about it.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-4}}'),

('Would you ever do a free concert for your fans?', '{tv,radio,internet}', 'fan_engagement', 'In a heartbeat — music should be for everyone, not just those who can pay.', '{"fame_mult":1.2,"fan_mult":1.4,"cash_mult":0.8,"reputation":{"authenticity":8}}', 'We''ve done charity shows before and would love to do more.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":0.9,"reputation":{"reliability":5}}', 'Free? Nothing in this world is free. Ask the promoters.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.1,"reputation":{"attitude":4,"authenticity":-5}}', 'I doubt our label would allow it.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-3}}'),

('How do you celebrate milestones with your fanbase?', '{internet,podcast}', 'fan_engagement', 'Special releases, livestreams, and surprise gifts — they deserve celebrations!', '{"fame_mult":1.2,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"creativity":4,"authenticity":4}}', 'We share the moment on social media and thank everyone involved.', '{"fame_mult":1.1,"fan_mult":1.1,"cash_mult":1.0,"reputation":{"reliability":5}}', 'We pop champagne in private. Fans don''t need to be part of everything.', '{"fame_mult":0.9,"fan_mult":0.7,"cash_mult":1.0,"reputation":{"attitude":4,"authenticity":-4}}', 'We don''t really track milestones.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"reliability":-4}}'),

('What''s one thing you want fans to know about the real you?', '{podcast,tv,magazine}', 'fan_engagement', 'I''m just as passionate offstage as on — music isn''t a job, it''s my oxygen.', '{"fame_mult":1.3,"fan_mult":1.3,"cash_mult":1.0,"reputation":{"authenticity":8}}', 'I care deeply about every fan and every note we play.', '{"fame_mult":1.1,"fan_mult":1.2,"cash_mult":1.0,"reputation":{"reliability":5,"authenticity":3}}', 'I''m way cooler in person than in interviews.', '{"fame_mult":1.1,"fan_mult":0.9,"cash_mult":1.0,"reputation":{"attitude":4,"authenticity":-2}}', 'What you see is what you get.', '{"fame_mult":0.5,"fan_mult":0.6,"cash_mult":0.8,"reputation":{"authenticity":-3}}');
