
-- =============================================
-- NIGHTCLUB QUESTS & PROGRESS TABLES
-- =============================================

CREATE TABLE public.nightclub_quests (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  club_id UUID NOT NULL REFERENCES public.city_night_clubs(id) ON DELETE CASCADE,
  npc_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  quest_type TEXT NOT NULL DEFAULT 'one_time' CHECK (quest_type IN ('one_time', 'repeatable', 'chain')),
  chain_position INTEGER,
  chain_id TEXT,
  requirements JSONB DEFAULT '{}'::jsonb,
  dialogue JSONB NOT NULL DEFAULT '[]'::jsonb,
  rewards JSONB NOT NULL DEFAULT '{}'::jsonb,
  energy_cost INTEGER NOT NULL DEFAULT 10,
  cooldown_hours INTEGER DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.player_nightclub_quest_progress (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  quest_id UUID NOT NULL REFERENCES public.nightclub_quests(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'in_progress', 'completed', 'failed')),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  dialogue_state JSONB DEFAULT '{}'::jsonb,
  rewards_claimed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(profile_id, quest_id)
);

ALTER TABLE public.nightclub_quests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_nightclub_quest_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view nightclub quests" ON public.nightclub_quests FOR SELECT USING (true);
CREATE POLICY "Admins can manage nightclub quests" ON public.nightclub_quests FOR ALL USING (
  EXISTS (SELECT 1 FROM user_roles WHERE user_id = auth.uid() AND role = 'admin')
);

CREATE POLICY "Users can view own quest progress" ON public.player_nightclub_quest_progress FOR SELECT USING (
  profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid())
);
CREATE POLICY "Users can insert own quest progress" ON public.player_nightclub_quest_progress FOR INSERT WITH CHECK (
  profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid())
);
CREATE POLICY "Users can update own quest progress" ON public.player_nightclub_quest_progress FOR UPDATE USING (
  profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid())
);

CREATE INDEX idx_nightclub_quests_club ON public.nightclub_quests(club_id);
CREATE INDEX idx_nightclub_quests_chain ON public.nightclub_quests(chain_id) WHERE chain_id IS NOT NULL;
CREATE INDEX idx_player_quest_progress_profile ON public.player_nightclub_quest_progress(profile_id);
CREATE INDEX idx_player_quest_progress_quest ON public.player_nightclub_quest_progress(quest_id);

CREATE TRIGGER update_nightclub_quests_updated_at
  BEFORE UPDATE ON public.nightclub_quests
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- =============================================
-- SEED 80+ NIGHTCLUBS ACROSS WORLD CITIES
-- =============================================

-- UK: Birmingham
INSERT INTO public.city_night_clubs (city_id, name, description, quality_level, capacity, cover_charge, guest_actions, drink_menu, npc_profiles, dj_slot_config, metadata) VALUES
('9a2e587a-94f7-49ec-8c99-21f95cac5860', 'The Vault', 'Hidden beneath a former bank in Digbeth, this underground space throbs with bass-heavy beats and graffiti-covered walls.', 1, 180, 8, '[{"label":"Dance Floor Frenzy","description":"Lose yourself in the industrial beats","energy_cost":8},{"label":"Graffiti Wall Chat","description":"Meet local artists and DJs near the murals","energy_cost":5}]', '[{"name":"Vault Reserve","price":6,"effect":"+3 energy"},{"name":"Brummie Bitter","price":4}]', '[{"id":"vault_dj_kez","name":"DJ Kez","role":"Resident DJ","personality":"Raw, uncompromising, bass obsessed","dialogueHooks":["dubstep origins","Birmingham scene","underground culture"]},{"id":"vault_owner_rico","name":"Rico Vance","role":"Club Owner","personality":"Street-smart, loyal to regulars","dialogueHooks":["venue history","Digbeth culture","local talent"]}]', '{"fameRequirement":80,"payout":180,"setLengthMinutes":45,"schedule":"11pm-3am","perks":["+3% local fan buzz"]}', '{"live_interactions":true}'),
('9a2e587a-94f7-49ec-8c99-21f95cac5860', 'Prism', 'A boutique club in the Jewellery Quarter with prismatic light installations and eclectic house music.', 3, 250, 20, '[{"label":"VIP Booth","description":"Reserve a booth with bottle service","energy_cost":12},{"label":"Light Show Experience","description":"Immerse in the prismatic light tunnel","energy_cost":6},{"label":"Rooftop Terrace","description":"Chill on the terrace with city views","energy_cost":4}]', '[{"name":"Rainbow Fizz","price":12,"effect":"+5 mood"},{"name":"Diamond Martini","price":15,"effect":"+2 charisma"},{"name":"Gold Rush","price":10}]', '[{"id":"prism_dj_nova","name":"Nova Bright","role":"Resident DJ","personality":"Eclectic, fashion-forward, genre-blending","dialogueHooks":["house music evolution","fashion","Birmingham nightlife"]},{"id":"prism_promoter_jade","name":"Jade Kim","role":"Promoter","personality":"Connected, ambitious, trend-setter","dialogueHooks":["event promotion","social media","industry connections"]}]', '{"fameRequirement":500,"payout":600,"setLengthMinutes":60,"schedule":"10pm-2am","perks":["+5% fan engagement"]}', '{"live_interactions":true}'),
('9a2e587a-94f7-49ec-8c99-21f95cac5860', 'The Colosseum', 'Birminghams premier superclub spanning three floors with world-class sound systems.', 4, 1200, 35, '[{"label":"Main Arena","description":"Experience the massive main room","energy_cost":10},{"label":"R&B Suite","description":"Smooth vibes in the second room","energy_cost":8},{"label":"Champagne Lounge","description":"Network with VIPs","energy_cost":15}]', '[{"name":"Gladiator Shot","price":8,"effect":"+4 energy"},{"name":"Emperor Cocktail","price":18,"effect":"+3 charisma"},{"name":"Arena Punch","price":14}]', '[{"id":"colo_owner_marcus","name":"Marcus Webb","role":"Club Owner","personality":"Business mogul, high standards, generous to talent","dialogueHooks":["big business","VIP culture","headliner bookings"]},{"id":"colo_bouncer_tank","name":"Tank","role":"Bouncer","personality":"Intimidating but fair, respects talent","dialogueHooks":["door policy","respect","club security"]}]', '{"fameRequirement":1500,"payout":1200,"setLengthMinutes":75,"schedule":"10pm-4am","perks":["+8% fame boost","+5% merch sales"]}', '{"live_interactions":true}');

-- UK: Edinburgh
INSERT INTO public.city_night_clubs (city_id, name, description, quality_level, capacity, cover_charge, guest_actions, drink_menu, npc_profiles, dj_slot_config, metadata) VALUES
('f082fb21-717b-4abb-af6e-8cb5556dd072', 'The Caves', 'Nestled in Edinburghs ancient underground vaults, this atmospheric venue blends history with heavy bass.', 2, 200, 12, '[{"label":"Vault Exploration","description":"Wander through ancient stone archways","energy_cost":6},{"label":"Dance in the Dark","description":"Move to beats in candlelit chambers","energy_cost":8}]', '[{"name":"Scotch Mist","price":9,"effect":"+3 mood"},{"name":"Highland Fling","price":7}]', '[{"id":"caves_dj_angus","name":"Angus McBeat","role":"Resident DJ","personality":"Soulful, deep, Edinburgh pride","dialogueHooks":["Scottish dance scene","vinyl culture","Edinburgh nightlife"]},{"id":"caves_bartender_fiona","name":"Fiona Ross","role":"Bartender","personality":"Warm, gossipy, knows everyone","dialogueHooks":["local rumors","drink recipes","regulars"]}]', '{"fameRequirement":200,"payout":300,"setLengthMinutes":50,"schedule":"11pm-3am","perks":["+4% local buzz"]}', '{"live_interactions":true}'),
('f082fb21-717b-4abb-af6e-8cb5556dd072', 'Bongo Club', 'Eclectic arts venue and club in the heart of Old Town, championing experimental sounds.', 2, 250, 10, '[{"label":"Art Gallery Browse","description":"Check out rotating exhibitions","energy_cost":4},{"label":"Open Mic Corner","description":"Watch or perform at the open mic","energy_cost":7}]', '[{"name":"Bongo Brew","price":5},{"name":"Old Town Ale","price":4}]', '[{"id":"bongo_producer_ewan","name":"Ewan Flux","role":"Underground Producer","personality":"Experimental, philosophical, anti-mainstream","dialogueHooks":["experimental music","production techniques","art and music"]}]', '{"fameRequirement":150,"payout":250,"setLengthMinutes":45,"schedule":"10pm-2am","perks":["+3% creativity boost"]}', '{"live_interactions":true}'),
('f082fb21-717b-4abb-af6e-8cb5556dd072', 'Liquid Room', 'Premium multi-room venue on Victoria Street known for hosting international headliners.', 4, 800, 30, '[{"label":"Main Room Madness","description":"Immerse in the headliner experience","energy_cost":12},{"label":"Back Room Sessions","description":"Discover emerging talent","energy_cost":8},{"label":"VIP Balcony","description":"Watch from above with champagne","energy_cost":15}]', '[{"name":"Edinburgh Elixir","price":14,"effect":"+5 energy"},{"name":"Royal Mile Martini","price":16,"effect":"+3 charisma"}]', '[{"id":"liquid_owner_grant","name":"Grant Morrison","role":"Club Owner","personality":"Visionary, well-connected, talent scout","dialogueHooks":["international bookings","festival circuit","Scottish music industry"]},{"id":"liquid_promoter_isla","name":"Isla Campbell","role":"Promoter","personality":"Energetic, social media savvy","dialogueHooks":["event marketing","influencer culture","Edinburgh festivals"]}]', '{"fameRequirement":1800,"payout":1400,"setLengthMinutes":90,"schedule":"9pm-3am","perks":["+10% fame boost","+5% fan gain"]}', '{"live_interactions":true}');

-- UK: Liverpool
INSERT INTO public.city_night_clubs (city_id, name, description, quality_level, capacity, cover_charge, guest_actions, drink_menu, npc_profiles, dj_slot_config, metadata) VALUES
('5030bf72-9301-4b8a-80f3-123e72bdb117', 'The Shipping Forecast', 'Basement club beneath a pub on Slater Street, known for cutting-edge electronic and indie nights.', 1, 150, 7, '[{"label":"Basement Groove","description":"Get lost in the intimate dancefloor","energy_cost":7},{"label":"Record Bin Dig","description":"Browse the DJs vinyl collection","energy_cost":4}]', '[{"name":"Mersey Mixer","price":5},{"name":"Dock Lager","price":4}]', '[{"id":"ship_dj_scouse","name":"DJ Scouse Logic","role":"Resident DJ","personality":"Passionate, witty, Liverpool loyalist","dialogueHooks":["Liverpool music history","Beatles legacy","underground scene"]}]', '{"fameRequirement":100,"payout":150,"setLengthMinutes":45,"schedule":"11pm-3am","perks":["+3% local fan loyalty"]}', '{"live_interactions":true}'),
('5030bf72-9301-4b8a-80f3-123e72bdb117', 'Circus', 'Liverpools flagship dance music venue in the Baltic Triangle with world-class production.', 3, 600, 22, '[{"label":"Main Room","description":"Experience massive production value","energy_cost":10},{"label":"Garden Area","description":"Outdoor vibes and street food","energy_cost":5},{"label":"Networking Hub","description":"Meet promoters and artists","energy_cost":8}]', '[{"name":"Circus Punch","price":10,"effect":"+4 energy"},{"name":"Baltic Breeze","price":12,"effect":"+3 mood"}]', '[{"id":"circus_owner_yousef","name":"Yousef","role":"Club Owner","personality":"Industry legend, generous mentor, globally connected","dialogueHooks":["Ibiza connections","global DJ circuit","club culture"]},{"id":"circus_vip_danny","name":"Danny Hughes","role":"VIP Regular","personality":"Music industry mogul, deal-maker","dialogueHooks":["record deals","industry politics","festival bookings"]}]', '{"fameRequirement":800,"payout":700,"setLengthMinutes":60,"schedule":"10pm-4am","perks":["+6% fame boost","+4% fan engagement"]}', '{"live_interactions":true}'),
('5030bf72-9301-4b8a-80f3-123e72bdb117', '24 Kitchen Street', 'Raw, industrial warehouse space hosting boundary-pushing electronic nights.', 2, 300, 12, '[{"label":"Warehouse Rave","description":"Pure underground energy","energy_cost":9},{"label":"Smoke Machine Vibes","description":"Dance through the haze","energy_cost":7}]', '[{"name":"Kitchen Sink","price":6,"effect":"+2 energy"},{"name":"Baltic Porter","price":5}]', '[{"id":"24k_dj_hannah","name":"Hannah Laing","role":"Resident DJ","personality":"High-energy, crowd-surfing, festival-ready","dialogueHooks":["festival culture","high-energy sets","crowd control"]}]', '{"fameRequirement":300,"payout":350,"setLengthMinutes":50,"schedule":"11pm-5am","perks":["+4% energy retention"]}', '{"live_interactions":true}');

-- UK: Glasgow
INSERT INTO public.city_night_clubs (city_id, name, description, quality_level, capacity, cover_charge, guest_actions, drink_menu, npc_profiles, dj_slot_config, metadata) VALUES
('9120351f-07d6-4b6a-bc64-6914d90540a1', 'Sub Club', 'Legendary Glasgow institution. One of the worlds longest-running underground clubs.', 3, 350, 15, '[{"label":"Main Floor","description":"Experience the legendary Sub Club sound system","energy_cost":10},{"label":"Sweat Box Session","description":"Intense close-quarters dancing","energy_cost":12}]', '[{"name":"Sub Zero","price":8,"effect":"+4 energy"},{"name":"Glasgow Kiss","price":10,"effect":"+3 mood"}]', '[{"id":"sub_dj_harri","name":"Harri","role":"Resident DJ","personality":"Sub Club institution, vinyl purist, house music historian","dialogueHooks":["house music history","Glasgow scene","vinyl culture"]},{"id":"sub_owner_mike","name":"Mike Grieve","role":"Club Owner","personality":"Pioneer, stubborn idealist, anti-corporate","dialogueHooks":["club culture preservation","underground values","Glasgow identity"]}]', '{"fameRequirement":600,"payout":550,"setLengthMinutes":120,"schedule":"11pm-4am","perks":["+7% credibility boost","+5% local fame"]}', '{"live_interactions":true}'),
('9120351f-07d6-4b6a-bc64-6914d90540a1', 'SWG3', 'Multi-purpose arts and music venue in Finnieston with outdoor terrace and gallery spaces.', 3, 500, 18, '[{"label":"Gallery Walk","description":"Browse contemporary art installations","energy_cost":4},{"label":"Terrace Chill","description":"Relax on the outdoor terrace","energy_cost":5},{"label":"Main Room Rave","description":"Full production dance experience","energy_cost":10}]', '[{"name":"Finnieston Fizz","price":11,"effect":"+3 charisma"},{"name":"West End Whisky","price":14}]', '[{"id":"swg3_promoter_blair","name":"Blair McPherson","role":"Promoter","personality":"Creative, community-focused, festival organizer","dialogueHooks":["Glasgow festivals","art and music","community events"]}]', '{"fameRequirement":500,"payout":500,"setLengthMinutes":60,"schedule":"10pm-3am","perks":["+5% creativity boost"]}', '{"live_interactions":true}');

-- UK: Bristol, Leeds, Brighton, Cardiff, Newcastle, Sheffield, Belfast, Nottingham
INSERT INTO public.city_night_clubs (city_id, name, description, quality_level, capacity, cover_charge, guest_actions, drink_menu, npc_profiles, dj_slot_config, metadata) VALUES
('f3606ebd-278a-4bfc-8023-d9f9ebfedbf5', 'Motion', 'Massive warehouse complex in Bristols old industrial docks.', 4, 1500, 25, '[{"label":"Warehouse Main","description":"Cavernous main room","energy_cost":10},{"label":"The Marble Factory","description":"Intimate second room","energy_cost":8},{"label":"Outdoor Yard","description":"Street food and fresh air","energy_cost":4}]', '[{"name":"Bristol Bass Drop","price":10,"effect":"+5 energy"},{"name":"Harbourside Rum","price":12}]', '[{"id":"motion_dj_krust","name":"DJ Krust","role":"Resident DJ","personality":"D&B legend, Bristol pioneer","dialogueHooks":["drum and bass history","Bristol sound","production mastery"]},{"id":"motion_owner_chris","name":"Chris Sherwood","role":"Club Owner","personality":"Visionary, community builder","dialogueHooks":["warehouse culture","festival expansion","Bristol music"]}]', '{"fameRequirement":1200,"payout":1000,"setLengthMinutes":90,"schedule":"10pm-6am","perks":["+8% fame","+5% D&B fan attraction"]}', '{"live_interactions":true}'),
('f3606ebd-278a-4bfc-8023-d9f9ebfedbf5', 'The Blue Mountain', 'Intimate Stokes Croft venue known for reggae, dub, and bass music.', 1, 200, 8, '[{"label":"Dub Session","description":"Feel the bass in your bones","energy_cost":7},{"label":"Jerk Chicken Break","description":"Refuel with Caribbean food","energy_cost":3}]', '[{"name":"Stokes Croft Stout","price":5},{"name":"Reggae Rum Punch","price":7,"effect":"+3 mood"}]', '[{"id":"blue_dj_ras","name":"Ras Kwame","role":"Resident DJ","personality":"Roots man, spiritual, bass culture guardian","dialogueHooks":["reggae roots","sound system culture","Bristol dub"]}]', '{"fameRequirement":120,"payout":180,"setLengthMinutes":60,"schedule":"10pm-4am","perks":["+4% authenticity"]}', '{"live_interactions":true}'),
('ab2f6f73-8bd4-4adb-aee4-d123ce1a2cd3', 'Wire', 'Leeds legendary basement club.', 2, 250, 10, '[{"label":"Basement Rave","description":"Descend into the chaos","energy_cost":9},{"label":"Bar Chat","description":"Talk to DJs between sets","energy_cost":5}]', '[{"name":"Wire Juice","price":6,"effect":"+3 energy"},{"name":"Leeds Lager","price":4}]', '[{"id":"wire_dj_calibre","name":"DJ Calibre","role":"Resident DJ","personality":"Technical, precise, deep house master","dialogueHooks":["deep house","technical DJing","Leeds nightlife"]}]', '{"fameRequirement":250,"payout":300,"setLengthMinutes":50,"schedule":"11pm-4am","perks":["+4% technical credibility"]}', '{"live_interactions":true}'),
('ab2f6f73-8bd4-4adb-aee4-d123ce1a2cd3', 'Canal Mills', 'Converted industrial mill with immersive production.', 3, 700, 20, '[{"label":"Mill Floor","description":"Dance under industrial beams","energy_cost":10},{"label":"Canal Side","description":"Fresh air by the waterway","energy_cost":4}]', '[{"name":"Mill House Martini","price":12,"effect":"+4 charisma"},{"name":"Canal Water","price":8}]', '[{"id":"canal_promoter_ash","name":"Ash Williams","role":"Promoter","personality":"Ambitious, connected","dialogueHooks":["event promotion","artist bookings","Leeds scene"]}]', '{"fameRequirement":700,"payout":650,"setLengthMinutes":60,"schedule":"10pm-4am","perks":["+6% fame boost"]}', '{"live_interactions":true}'),
('50a1c6e7-b9ee-44f0-95c4-8453396728ed', 'Patterns', 'Seafront venue beneath the arches.', 2, 300, 12, '[{"label":"Beach Vibes","description":"Step out to the seafront","energy_cost":3},{"label":"Arch Dance","description":"Move under Victorian arches","energy_cost":8}]', '[{"name":"Seaside Spritz","price":9,"effect":"+3 mood"},{"name":"Brighton Banger","price":7}]', '[{"id":"patterns_dj_maya","name":"Maya Blu","role":"Resident DJ","personality":"Breezy, eclectic, seaside soul","dialogueHooks":["Brighton culture","beach parties","eclectic mixing"]}]', '{"fameRequirement":300,"payout":350,"setLengthMinutes":50,"schedule":"10pm-3am","perks":["+4% mood boost"]}', '{"live_interactions":true}'),
('50a1c6e7-b9ee-44f0-95c4-8453396728ed', 'Concorde 2', 'Brighton institution on the seafront.', 3, 600, 18, '[{"label":"Main Hall","description":"Full production experience","energy_cost":10},{"label":"Backstage Pass","description":"Mingle with artists","energy_cost":12}]', '[{"name":"Concorde Cocktail","price":11,"effect":"+4 energy"},{"name":"Pier Pressure","price":13}]', '[{"id":"conc_owner_pete","name":"Pete Sheringham","role":"Club Owner","personality":"Eclectic taste, punk roots","dialogueHooks":["punk to techno","Brighton history","diverse bookings"]}]', '{"fameRequirement":600,"payout":550,"setLengthMinutes":60,"schedule":"9pm-3am","perks":["+5% fan diversity"]}', '{"live_interactions":true}'),
('d66d819a-62fa-4594-a796-7e8f5ed53284', 'Clwb Ifor Bach', 'Cardiff institution. Three floors of Welsh passion.', 2, 350, 10, '[{"label":"Welsh Floor","description":"Local bands and Welsh nights","energy_cost":7},{"label":"Top Floor Techno","description":"Electronic on the top floor","energy_cost":9}]', '[{"name":"Dragon Fire","price":7,"effect":"+3 energy"},{"name":"Cymru Cider","price":5}]', '[{"id":"clwb_dj_gareth","name":"Gareth Howells","role":"Resident DJ","personality":"Bilingual, passionate about Welsh culture","dialogueHooks":["Welsh music scene","bilingual culture","Cardiff nightlife"]}]', '{"fameRequirement":200,"payout":280,"setLengthMinutes":45,"schedule":"10pm-3am","perks":["+4% Welsh fan loyalty"]}', '{"live_interactions":true}'),
('d66d819a-62fa-4594-a796-7e8f5ed53284', 'Tramshed', 'Converted tramway depot.', 3, 800, 20, '[{"label":"Main Hall","description":"Massive converted hall","energy_cost":10},{"label":"Mezzanine Lounge","description":"Elevated VIP viewing","energy_cost":12}]', '[{"name":"Tram Line","price":10,"effect":"+4 mood"},{"name":"Capital Crush","price":12}]', '[{"id":"tram_promoter_rhys","name":"Rhys Davies","role":"Promoter","personality":"Welsh pride, nationally connected","dialogueHooks":["Wales music industry","national promotion","festival links"]}]', '{"fameRequirement":600,"payout":550,"setLengthMinutes":60,"schedule":"9pm-3am","perks":["+5% fame boost"]}', '{"live_interactions":true}'),
('efbe74b2-913c-4585-877b-d3ba64f9348f', 'Digital', 'Newcastle flagship superclub.', 3, 900, 18, '[{"label":"Main Arena","description":"Massive LED-filled main room","energy_cost":10},{"label":"VIP Section","description":"Exclusive VIP area","energy_cost":14}]', '[{"name":"Geordie Punch","price":8,"effect":"+4 energy"},{"name":"Tyne Tonic","price":10}]', '[{"id":"digital_dj_pat","name":"Patrick Topping","role":"Resident DJ","personality":"Newcastle hero, tech-house king","dialogueHooks":["tech house","Newcastle pride","Ibiza connections"]}]', '{"fameRequirement":700,"payout":600,"setLengthMinutes":60,"schedule":"10pm-4am","perks":["+6% tech-house fan attraction"]}', '{"live_interactions":true}'),
('efbe74b2-913c-4585-877b-d3ba64f9348f', 'World HQ', 'Underground institution beneath railway arches.', 2, 250, 10, '[{"label":"Arch Sessions","description":"Raw underground vibes","energy_cost":8},{"label":"Record Shopping","description":"Browse the record store","energy_cost":4}]', '[{"name":"Arch Angel","price":7},{"name":"Northern Soul","price":6,"effect":"+3 mood"}]', '[{"id":"whq_dj_mr_thing","name":"Mr Thing","role":"Resident DJ","personality":"Hip-hop head, vinyl obsessive","dialogueHooks":["turntablism","hip-hop culture","vinyl collecting"]}]', '{"fameRequirement":200,"payout":250,"setLengthMinutes":50,"schedule":"10pm-3am","perks":["+4% turntablism XP"]}', '{"live_interactions":true}'),
('83822ef1-93c9-46f0-85d0-de8f3d2433f4', 'Hope Works', 'Sheffield legendary warehouse space.', 2, 400, 12, '[{"label":"Warehouse Floor","description":"Industrial Sheffield","energy_cost":9},{"label":"Courtyard Chill","description":"Outdoor area","energy_cost":4}]', '[{"name":"Steel City Stout","price":5},{"name":"Warp Wobble","price":8,"effect":"+3 energy"}]', '[{"id":"hope_dj_alex","name":"Alex Sherwood","role":"Resident DJ","personality":"Sheffield techno loyalist","dialogueHooks":["Sheffield electronic history","Warp Records","industrial techno"]}]', '{"fameRequirement":300,"payout":350,"setLengthMinutes":60,"schedule":"11pm-5am","perks":["+5% electronic credibility"]}', '{"live_interactions":true}'),
('83822ef1-93c9-46f0-85d0-de8f3d2433f4', 'Tank', 'Multi-level Sheffield club.', 3, 500, 16, '[{"label":"Main Tank","description":"Full immersion","energy_cost":10},{"label":"VIP Lounge","description":"Elevated experience","energy_cost":12}]', '[{"name":"Tank Shell","price":10,"effect":"+4 energy"},{"name":"Steel Reserve","price":12}]', '[{"id":"tank_promoter_sam","name":"Sam Fletcher","role":"Promoter","personality":"Diverse taste, community champion","dialogueHooks":["diverse programming","community events","Sheffield revival"]}]', '{"fameRequirement":500,"payout":500,"setLengthMinutes":60,"schedule":"10pm-3am","perks":["+5% fan diversity"]}', '{"live_interactions":true}'),
('96e8e64a-11af-4f9c-a018-9ff9e4c6fd13', 'Limelight', 'Converted Victorian church turned Belfast premier nightclub.', 3, 700, 15, '[{"label":"Main Chapel","description":"Dance in a converted church","energy_cost":10},{"label":"Confession Box","description":"Intimate side room","energy_cost":7}]', '[{"name":"Holy Water","price":8,"effect":"+4 energy"},{"name":"Belfast Bomb","price":6}]', '[{"id":"lime_dj_bicep","name":"DJ Bicep Tribute","role":"Resident DJ","personality":"Belfast electronic pride","dialogueHooks":["Belfast electronic scene","Bicep influence","Irish dance music"]}]', '{"fameRequirement":500,"payout":500,"setLengthMinutes":60,"schedule":"10pm-3am","perks":["+5% melodic house fan attraction"]}', '{"live_interactions":true}'),
('96e8e64a-11af-4f9c-a018-9ff9e4c6fd13', 'Thompsons Garage', 'Raw underground venue.', 1, 200, 8, '[{"label":"Garage Rave","description":"Pure underground energy","energy_cost":8},{"label":"Back Alley Smoke","description":"Cool off in the courtyard","energy_cost":3}]', '[{"name":"Garage Grease","price":5},{"name":"Troubles Tipple","price":7,"effect":"+3 mood"}]', '[{"id":"thomp_owner_sean","name":"Sean Maguire","role":"Club Owner","personality":"Stubborn idealist, community protector","dialogueHooks":["Belfast culture","underground values","community"]}]', '{"fameRequirement":100,"payout":160,"setLengthMinutes":45,"schedule":"11pm-4am","perks":["+3% authenticity"]}', '{"live_interactions":true}'),
('71bf8418-38af-443d-9e3f-80458b2d04a9', 'Stealth', 'Nottingham leading underground club.', 2, 400, 12, '[{"label":"Dark Room","description":"Lose yourself in darkness","energy_cost":9},{"label":"Sound System Worship","description":"Feel the Funktion-One","energy_cost":7}]', '[{"name":"Stealth Mode","price":7,"effect":"+3 energy"},{"name":"Robin Hood Rum","price":8}]', '[{"id":"stealth_dj_greg","name":"Greg Sherwood","role":"Resident DJ","personality":"Dark techno specialist","dialogueHooks":["sound system culture","dark techno","Nottingham scene"]}]', '{"fameRequirement":300,"payout":350,"setLengthMinutes":60,"schedule":"11pm-5am","perks":["+5% techno credibility"]}', '{"live_interactions":true}'),
('71bf8418-38af-443d-9e3f-80458b2d04a9', 'Rock City', 'Iconic Nottingham venue spanning four rooms.', 3, 1000, 15, '[{"label":"Main Hall","description":"Iconic live music venue","energy_cost":10},{"label":"Basement","description":"Underground electronic room","energy_cost":8},{"label":"Rig Bar","description":"Alternative vibes","energy_cost":6}]', '[{"name":"Rock Fuel","price":6,"effect":"+4 energy"},{"name":"City Slicker","price":9}]', '[{"id":"rock_promoter_nina","name":"Nina Brooks","role":"Promoter","personality":"Rock roots, electronic convert","dialogueHooks":["crossover music","venue history","Nottingham culture"]}]', '{"fameRequirement":500,"payout":500,"setLengthMinutes":60,"schedule":"10pm-3am","perks":["+5% crossover appeal"]}', '{"live_interactions":true}');

-- USA: New York
INSERT INTO public.city_night_clubs (city_id, name, description, quality_level, capacity, cover_charge, guest_actions, drink_menu, npc_profiles, dj_slot_config, metadata) VALUES
('a6d76b84-df38-4efb-9fc1-4bd882e31d1a', 'Nowadays', 'Ridgewood outdoor/indoor club. Brooklyn warehouse culture.', 2, 400, 15, '[{"label":"Outdoor Grove","description":"Dance under the trees","energy_cost":7},{"label":"Indoor Room","description":"Dark room deep cuts","energy_cost":9}]', '[{"name":"Brooklyn Bitter","price":8},{"name":"Ridgewood Remedy","price":10,"effect":"+3 mood"}]', '[{"id":"now_dj_justin","name":"Justin Carter","role":"Resident DJ","personality":"Brooklyn underground champion","dialogueHooks":["Brooklyn scene","outdoor parties","underground culture"]},{"id":"now_bartender_mia","name":"Mia Torres","role":"Bartender","personality":"Cool, observant","dialogueHooks":["regular gossip","drink specials","who to know"]}]', '{"fameRequirement":400,"payout":450,"setLengthMinutes":60,"schedule":"10pm-4am","perks":["+5% underground credibility"]}', '{"live_interactions":true}'),
('a6d76b84-df38-4efb-9fc1-4bd882e31d1a', 'Marquee New York', 'Chelsea mega-club. Celebrity playground.', 5, 1200, 60, '[{"label":"Main Floor VIP","description":"Celebrity-studded main room","energy_cost":15},{"label":"Library Lounge","description":"Exclusive quiet room","energy_cost":10},{"label":"Boom Box Room","description":"Hip-hop side room","energy_cost":8}]', '[{"name":"Marquee Magnum","price":30,"effect":"+5 charisma"},{"name":"Chelsea Champagne","price":40,"effect":"+8 fame boost"},{"name":"NYC Negroni","price":22}]', '[{"id":"marq_owner_noah","name":"Noah Tepperberg","role":"Club Owner","personality":"Mega-mogul, celebrity magnet","dialogueHooks":["celebrity culture","VIP nightlife","mega-deals"]},{"id":"marq_vip_kendall","name":"Kendall Stone","role":"VIP Regular","personality":"Fashion mogul, sponsor connections","dialogueHooks":["fashion partnerships","sponsorship deals","celebrity networking"]}]', '{"fameRequirement":5000,"payout":3000,"setLengthMinutes":120,"schedule":"10pm-4am","perks":["+15% fame boost","+10% celebrity encounter"]}', '{"live_interactions":true}'),
('a6d76b84-df38-4efb-9fc1-4bd882e31d1a', 'Output', 'Williamsburg warehouse club with Funktion-One sound.', 3, 500, 25, '[{"label":"Main Room","description":"World-class sound system","energy_cost":10},{"label":"Rooftop Sets","description":"Manhattan skyline views","energy_cost":8},{"label":"Networking","description":"Meet industry pros","energy_cost":6}]', '[{"name":"Output Signal","price":14,"effect":"+4 energy"},{"name":"Williamsburg Whiskey","price":16}]', '[{"id":"output_promoter_dave","name":"Dave Mancuso Jr","role":"Promoter","personality":"Loft party lineage","dialogueHooks":["loft party history","community events","Brooklyn culture"]},{"id":"output_producer_zara","name":"Zara Katz","role":"Underground Producer","personality":"Avant-garde, experimental","dialogueHooks":["experimental production","sound design","avant-garde music"]}]', '{"fameRequirement":1000,"payout":900,"setLengthMinutes":90,"schedule":"10pm-6am","perks":["+7% credibility","+5% producer connections"]}', '{"live_interactions":true}');

-- USA: LA, Miami, Chicago, Las Vegas
INSERT INTO public.city_night_clubs (city_id, name, description, quality_level, capacity, cover_charge, guest_actions, drink_menu, npc_profiles, dj_slot_config, metadata) VALUES
('cb7bdfa8-5558-4ffd-9d0f-235920ac269a', 'Sound Nightclub', 'Hollywood temple of techno and house.', 3, 500, 30, '[{"label":"Temple Floor","description":"Worship at the altar of sound","energy_cost":10},{"label":"Patio Vibes","description":"LA outdoor lounge","energy_cost":5}]', '[{"name":"Hollywood Haze","price":15,"effect":"+4 mood"},{"name":"Sunset Strip Sour","price":13}]', '[{"id":"sound_dj_doc","name":"Doc Martin","role":"Resident DJ","personality":"LA house legend","dialogueHooks":["LA house history","West Coast scene","longevity"]},{"id":"sound_bouncer_big_mike","name":"Big Mike","role":"Bouncer","personality":"Gentle giant, gatekeeper","dialogueHooks":["door policy","respect","celebrity encounters"]}]', '{"fameRequirement":800,"payout":700,"setLengthMinutes":60,"schedule":"10pm-3am","perks":["+6% West Coast credibility"]}', '{"live_interactions":true}'),
('cb7bdfa8-5558-4ffd-9d0f-235920ac269a', 'Avalon Hollywood', 'Legendary Vine Street art deco venue.', 4, 1500, 40, '[{"label":"Main Theater","description":"Art deco palace","energy_cost":12},{"label":"VIP Mezzanine","description":"Elevated VIP","energy_cost":15}]', '[{"name":"Avalon Elixir","price":20,"effect":"+5 energy"},{"name":"Vine Street Vintage","price":18,"effect":"+3 charisma"}]', '[{"id":"avalon_owner_john","name":"John Lyons","role":"Club Owner","personality":"Hollywood institution","dialogueHooks":["Hollywood history","venue legacy","superstar bookings"]},{"id":"avalon_promoter_tiffany","name":"Tiffany Rhodes","role":"Promoter","personality":"LA socialite","dialogueHooks":["influencer culture","LA social scene","brand partnerships"]}]', '{"fameRequirement":2000,"payout":1500,"setLengthMinutes":90,"schedule":"10pm-3am","perks":["+10% fame","+6% celebrity encounter"]}', '{"live_interactions":true}'),
('96c964de-4dbd-4bbe-80b7-6c9f68d4ba32', 'Club Space', 'Miami institution. Marathon sets, sunrise sessions.', 4, 1000, 30, '[{"label":"Terrace Sunrise","description":"Dance into Miami sunrise","energy_cost":12},{"label":"Main Room","description":"Peak-time energy","energy_cost":10}]', '[{"name":"Space Cadet","price":16,"effect":"+5 energy"},{"name":"Miami Vice","price":14,"effect":"+3 mood"}]', '[{"id":"space_dj_oscar","name":"Oscar G","role":"Resident DJ","personality":"Miami house royalty","dialogueHooks":["Miami house","marathon sets","sunrise culture"]},{"id":"space_owner_louis","name":"Louis Puig","role":"Club Owner","personality":"Nightlife visionary","dialogueHooks":["Miami nightlife history","Cuban culture","club legacy"]}]', '{"fameRequirement":1500,"payout":1200,"setLengthMinutes":180,"schedule":"11pm-11am","perks":["+10% Miami fame","+6% endurance"]}', '{"live_interactions":true}'),
('96c964de-4dbd-4bbe-80b7-6c9f68d4ba32', 'LIV', 'Fontainebleau mega-club. Hip-hop meets high fashion.', 5, 1200, 60, '[{"label":"Celebrity Table","description":"Bottle service with celebrities","energy_cost":15},{"label":"Dance Floor","description":"Hip-hop and EDM","energy_cost":10}]', '[{"name":"LIV Large","price":30,"effect":"+8 fame"},{"name":"South Beach Sunset","price":20}]', '[{"id":"liv_vip_rick","name":"Rick Ross Jr","role":"VIP Regular","personality":"Hip-hop mogul","dialogueHooks":["hip-hop business","luxury lifestyle","Miami connections"]},{"id":"liv_promoter_gia","name":"Gia Santini","role":"Promoter","personality":"Miami socialite","dialogueHooks":["celebrity appearances","VIP culture","brand deals"]}]', '{"fameRequirement":8000,"payout":5000,"setLengthMinutes":120,"schedule":"11pm-5am","perks":["+15% fame","+10% celebrity connections"]}', '{"live_interactions":true}'),
('29809134-e947-408b-9786-6d7b51181548', 'Smart Bar', 'Chicago institution. The heart of house music since 1982.', 3, 350, 15, '[{"label":"Dance Floor","description":"Where house music lives","energy_cost":9},{"label":"Bar Chat","description":"Talk with house royalty","energy_cost":5}]', '[{"name":"Chi-Town Classic","price":9,"effect":"+4 energy"},{"name":"Jack Your Body","price":8}]', '[{"id":"smart_dj_derrick","name":"Derrick Carter","role":"Resident DJ","personality":"Chicago house legend","dialogueHooks":["Chicago house history","soulful house","DJing as art"]},{"id":"smart_bartender_denise","name":"Denise Williams","role":"Bartender","personality":"Scene historian","dialogueHooks":["house music stories","Chicago legends","nightlife history"]}]', '{"fameRequirement":600,"payout":550,"setLengthMinutes":120,"schedule":"10pm-4am","perks":["+8% house credibility","+5% Chicago fame"]}', '{"live_interactions":true}'),
('29809134-e947-408b-9786-6d7b51181548', 'Radius', 'Massive Chicago superclub.', 4, 2000, 35, '[{"label":"Main Arena","description":"Epic scale production","energy_cost":12},{"label":"VIP Skybox","description":"Watch from above","energy_cost":15}]', '[{"name":"Windy City Whirl","price":14,"effect":"+5 energy"},{"name":"Lake Michigan Blue","price":16,"effect":"+4 mood"}]', '[{"id":"radius_owner_pete","name":"Peter Schivarelli","role":"Club Owner","personality":"Chicago nightlife mogul","dialogueHooks":["mega-events","Chicago entertainment","superclub culture"]}]', '{"fameRequirement":2000,"payout":1500,"setLengthMinutes":90,"schedule":"9pm-4am","perks":["+10% fame","+7% fan attraction"]}', '{"live_interactions":true}'),
('4efac643-c3bf-40b6-adcb-c3d5242c7b23', 'XS Nightclub', 'Encore at Wynn. Vegas most iconic club.', 5, 2000, 75, '[{"label":"Pool Party","description":"Daylife pool","energy_cost":12},{"label":"Nightclub Main","description":"Vegas mega production","energy_cost":15}]', '[{"name":"Vegas Jackpot","price":25,"effect":"+8 fame"},{"name":"High Roller","price":35,"effect":"+10 fame"}]', '[{"id":"xs_owner_steve","name":"Steve Wynn Jr","role":"Club Owner","personality":"Casino magnate","dialogueHooks":["Vegas nightlife","casino culture","mega-deals"]},{"id":"xs_vip_paris","name":"Paris DeLuxe","role":"VIP Regular","personality":"Socialite, influencer","dialogueHooks":["luxury lifestyle","brand partnerships","Vegas connections"]}]', '{"fameRequirement":10000,"payout":8000,"setLengthMinutes":120,"schedule":"10pm-4am","perks":["+20% fame","+15% earnings"]}', '{"live_interactions":true}');

-- Europe: Berlin, Amsterdam, Barcelona, Paris, Ibiza
INSERT INTO public.city_night_clubs (city_id, name, description, quality_level, capacity, cover_charge, guest_actions, drink_menu, npc_profiles, dj_slot_config, metadata) VALUES
('cc1fd801-c4b3-448f-ad55-f307e10e14a0', 'Berghain', 'The cathedral of techno. No photos. No VIP. Pure music.', 5, 1500, 20, '[{"label":"Main Floor","description":"Panorama Bar upstairs, Berghain down","energy_cost":15},{"label":"Panorama Bar","description":"House music with a view","energy_cost":10}]', '[{"name":"Club Mate","price":4},{"name":"Jägermeister","price":5,"effect":"+3 energy"}]', '[{"id":"berg_dj_ben","name":"Ben Klock","role":"Resident DJ","personality":"Berghain guardian, minimal, monolithic","dialogueHooks":["Berghain culture","minimal techno","Berlin nightlife"]},{"id":"berg_bouncer_sven","name":"Sven Marquardt","role":"Bouncer","personality":"Legendary doorman, photographer","dialogueHooks":["door philosophy","Berlin culture","art and nightlife"]}]', '{"fameRequirement":3000,"payout":2000,"setLengthMinutes":360,"schedule":"midnight-Monday","perks":["+15% global techno credibility","+10% underground fame"]}', '{"live_interactions":true}'),
('cc1fd801-c4b3-448f-ad55-f307e10e14a0', 'Tresor', 'Legendary Berlin techno institution in a former power plant.', 3, 600, 15, '[{"label":"Vault Floor","description":"Original Tresor vault","energy_cost":10},{"label":"Globus Upstairs","description":"House and techno upstairs","energy_cost":8}]', '[{"name":"Tresor Tonic","price":6,"effect":"+3 energy"},{"name":"Power Plant Pils","price":4}]', '[{"id":"tresor_dj_surgeon","name":"Surgeon","role":"Resident DJ","personality":"Industrial techno maestro","dialogueHooks":["industrial techno","Berlin-Birmingham connection","techno purity"]}]', '{"fameRequirement":800,"payout":600,"setLengthMinutes":120,"schedule":"midnight-noon","perks":["+8% techno credibility"]}', '{"live_interactions":true}'),
('de4787a9-f69a-44d8-8747-1cb02cae0c1c', 'De School', 'Former school turned underground club.', 3, 400, 18, '[{"label":"Gymnasium Floor","description":"Dance in the old gym","energy_cost":10},{"label":"Night Garden","description":"Outdoor sessions","energy_cost":6}]', '[{"name":"School Days","price":8,"effect":"+3 mood"},{"name":"Amsterdam Ale","price":6}]', '[{"id":"school_dj_san","name":"San Proper","role":"Resident DJ","personality":"Eccentric, unpredictable","dialogueHooks":["Amsterdam underground","eccentric style","improv DJing"]},{"id":"school_owner_luc","name":"Luc Vermeer","role":"Club Owner","personality":"Cultural visionary","dialogueHooks":["club culture innovation","Amsterdam nightlife","food and music"]}]', '{"fameRequirement":700,"payout":600,"setLengthMinutes":90,"schedule":"midnight-7am","perks":["+6% underground credibility"]}', '{"live_interactions":true}'),
('de4787a9-f69a-44d8-8747-1cb02cae0c1c', 'Paradiso', 'Legendary converted church.', 4, 1500, 25, '[{"label":"Main Hall","description":"Dance in a former church","energy_cost":12},{"label":"Balcony View","description":"Watch from the balcony","energy_cost":6}]', '[{"name":"Paradise Lost","price":12,"effect":"+5 charisma"},{"name":"Church Bell Cocktail","price":14,"effect":"+4 fame"}]', '[{"id":"para_promoter_jan","name":"Jan de Vries","role":"Promoter","personality":"Dutch institution","dialogueHooks":["Amsterdam music history","cross-genre programming","Dutch scene"]}]', '{"fameRequirement":1500,"payout":1200,"setLengthMinutes":90,"schedule":"10pm-4am","perks":["+8% fame","+5% Dutch fan loyalty"]}', '{"live_interactions":true}'),
('6c2386aa-a874-4c36-b153-8e10376f4a6e', 'Razzmatazz', 'Barcelona mega-club with five rooms.', 4, 2000, 20, '[{"label":"The Loft","description":"Electronic music haven","energy_cost":10},{"label":"Razz Club","description":"Main room indie and rock","energy_cost":8}]', '[{"name":"Barcelona Bomb","price":10,"effect":"+4 energy"},{"name":"Sangria Supreme","price":8,"effect":"+3 mood"}]', '[{"id":"razz_owner_lluis","name":"Lluís Ventura","role":"Club Owner","personality":"Catalan pride, genre-spanning vision","dialogueHooks":["Barcelona nightlife","Catalan culture","multi-genre"]},{"id":"razz_dj_marc","name":"Marc Piñol","role":"Resident DJ","personality":"Versatile, eclectic","dialogueHooks":["eclectic DJing","Barcelona underground","Catalan electronic"]}]', '{"fameRequirement":1000,"payout":900,"setLengthMinutes":90,"schedule":"1am-6am","perks":["+8% Mediterranean fame"]}', '{"live_interactions":true}'),
('13d450a9-eab3-430c-b5d1-377e5d3f2539', 'Rex Club', 'Paris techno institution near the Louvre.', 3, 400, 18, '[{"label":"Basement Dance","description":"Deep in Parisian techno","energy_cost":10},{"label":"DJ Booth Watch","description":"See the master at work","energy_cost":6}]', '[{"name":"Parisian Pulse","price":10,"effect":"+4 energy"},{"name":"Absinthe Hour","price":12,"effect":"+3 creativity"}]', '[{"id":"rex_dj_laurent","name":"Laurent Garnier","role":"Resident DJ","personality":"French techno godfather","dialogueHooks":["French techno history","eclectic programming","Paris nightlife"]},{"id":"rex_bartender_amelie","name":"Amélie Dubois","role":"Bartender","personality":"Parisian charm, witty","dialogueHooks":["Paris gossip","French culture","nightlife stories"]}]', '{"fameRequirement":700,"payout":600,"setLengthMinutes":120,"schedule":"midnight-7am","perks":["+7% European credibility"]}', '{"live_interactions":true}'),
('82ad6e5d-96a9-40a1-9cfc-b3cc256d1b4a', 'Amnesia', 'Ibiza superclub. Spiritual home of dance music tourism.', 5, 5000, 50, '[{"label":"Main Room","description":"Iconic foam party room","energy_cost":15},{"label":"Terrace","description":"Open-air sunrise sessions","energy_cost":10}]', '[{"name":"Amnesia Sunrise","price":18,"effect":"+8 energy"},{"name":"Ibiza Elixir","price":20,"effect":"+5 fame"}]', '[{"id":"amnesia_dj_marco","name":"Marco Carola","role":"Resident DJ","personality":"Italian techno king","dialogueHooks":["Ibiza seasons","Italian techno","Music On"]},{"id":"amnesia_owner_mar","name":"Mar Cardona","role":"Club Owner","personality":"Ibiza dynasty","dialogueHooks":["Ibiza history","island culture","superclub management"]}]', '{"fameRequirement":5000,"payout":4000,"setLengthMinutes":180,"schedule":"midnight-8am","perks":["+15% global fame","+10% Ibiza credibility"]}', '{"live_interactions":true}'),
('82ad6e5d-96a9-40a1-9cfc-b3cc256d1b4a', 'Ushuaïa', 'Worlds most famous open-air club.', 5, 3000, 60, '[{"label":"Pool Party","description":"Ultimate pool party","energy_cost":12},{"label":"Main Stage Front","description":"Front row main stage","energy_cost":10}]', '[{"name":"Ushuaïa Sunset","price":22,"effect":"+6 fame"},{"name":"Balearic Breeze","price":18,"effect":"+4 charisma"}]', '[{"id":"ushuaia_promoter_yann","name":"Yann Pissenem","role":"Club Owner","personality":"Nightlife empire builder","dialogueHooks":["super-club management","Ibiza empire","nightlife business"]}]', '{"fameRequirement":8000,"payout":6000,"setLengthMinutes":120,"schedule":"3pm-midnight","perks":["+18% global fame","+12% earnings boost"]}', '{"live_interactions":true}');

-- Europe: Prague, Dublin, Lisbon, Stockholm, Copenhagen, Vienna
INSERT INTO public.city_night_clubs (city_id, name, description, quality_level, capacity, cover_charge, guest_actions, drink_menu, npc_profiles, dj_slot_config, metadata) VALUES
('e798f1af-0b63-46a5-aa31-1a634b1c475f', 'Ankali', 'Prague underground institution.', 2, 300, 8, '[{"label":"Dark Dance","description":"Pure darkness and bass","energy_cost":9}]', '[{"name":"Prague Pilsner","price":3},{"name":"Ankali Acid","price":5,"effect":"+3 energy"}]', '[{"id":"ankali_dj_tomas","name":"Tomáš Nutil","role":"Resident DJ","personality":"Czech techno pioneer","dialogueHooks":["Czech techno","Eastern European scene","dark music"]}]', '{"fameRequirement":200,"payout":250,"setLengthMinutes":90,"schedule":"midnight-7am","perks":["+4% Eastern European credibility"]}', '{"live_interactions":true}'),
('31f54d08-a832-417a-8db1-3f0900e11b6a', 'Index', 'Dublin premier underground club.', 2, 200, 12, '[{"label":"Basement Boogie","description":"Intimate Dublin underground","energy_cost":8}]', '[{"name":"Dublin Drop","price":7,"effect":"+3 energy"},{"name":"Temple Bar Tipple","price":9}]', '[{"id":"index_dj_sunil","name":"Sunil Sharpe","role":"Resident DJ","personality":"Irish techno godfather","dialogueHooks":["Irish techno","Dublin underground","DIY culture"]}]', '{"fameRequirement":300,"payout":350,"setLengthMinutes":60,"schedule":"11pm-3am","perks":["+5% Irish credibility"]}', '{"live_interactions":true}'),
('cb90acc2-068d-4cb8-9371-5a2e1843e3e6', 'Lux Frágil', 'Lisbon iconic riverside club.', 4, 500, 20, '[{"label":"River Terrace","description":"Dance with Tagus views","energy_cost":8},{"label":"Main Floor","description":"Full production","energy_cost":10}]', '[{"name":"Tagus Tonic","price":10,"effect":"+4 mood"},{"name":"Lisbon Liqueur","price":12,"effect":"+3 charisma"}]', '[{"id":"lux_owner_manuel","name":"Manuel Reis","role":"Club Owner","personality":"Cultural visionary","dialogueHooks":["Lisbon culture","art and nightlife","Portuguese identity"]},{"id":"lux_dj_violet","name":"Violet","role":"Resident DJ","personality":"Minimal, refined","dialogueHooks":["minimal house","European circuit","Lisbon electronic"]}]', '{"fameRequirement":1000,"payout":800,"setLengthMinutes":90,"schedule":"midnight-6am","perks":["+8% European credibility"]}', '{"live_interactions":true}'),
('2e670249-4f15-4089-b3cf-a1c2545bb5fa', 'Trädgården', 'Summer open-air club under a bridge.', 3, 800, 20, '[{"label":"Open Air Dance","description":"Dance under the Swedish sky","energy_cost":10}]', '[{"name":"Midsommar Mule","price":14,"effect":"+4 energy"},{"name":"Stockholm Sour","price":12}]', '[{"id":"trad_promoter_erik","name":"Erik Gustafsson","role":"Promoter","personality":"Summer vibes curator","dialogueHooks":["Swedish summer","open-air culture","festival circuit"]}]', '{"fameRequirement":600,"payout":550,"setLengthMinutes":90,"schedule":"6pm-1am","perks":["+6% Scandinavian fame"]}', '{"live_interactions":true}'),
('9a2cbfe1-cd41-4f68-a385-2e792714afe5', 'Culture Box', 'Copenhagen techno institution.', 3, 400, 15, '[{"label":"Main Box","description":"Techno main room","energy_cost":10},{"label":"Red Box","description":"House and disco room","energy_cost":8}]', '[{"name":"Copenhagen Craft","price":10,"effect":"+3 energy"},{"name":"Nordic Nectar","price":12,"effect":"+4 mood"}]', '[{"id":"cbox_dj_trentemoller","name":"Trentemøller","role":"Resident DJ","personality":"Danish electronic icon","dialogueHooks":["Danish electronic","cinematic music","atmospheric production"]}]', '{"fameRequirement":600,"payout":550,"setLengthMinutes":90,"schedule":"midnight-6am","perks":["+6% Nordic credibility"]}', '{"live_interactions":true}'),
('3a32d826-cead-4d80-a829-87abda80d991', 'Grelle Forelle', 'Vienna flagship club on the Danube Canal.', 3, 500, 15, '[{"label":"Canal Dance","description":"Dance with Danube views","energy_cost":9}]', '[{"name":"Viennese Whirl","price":10,"effect":"+3 charisma"},{"name":"Danube Drop","price":8}]', '[{"id":"grelle_dj_cid","name":"Cid Rim","role":"Resident DJ","personality":"Viennese experimental","dialogueHooks":["Viennese experimental","LuckyMe label","Austrian electronic"]}]', '{"fameRequirement":500,"payout":500,"setLengthMinutes":60,"schedule":"11pm-6am","perks":["+5% Austrian credibility"]}', '{"live_interactions":true}');

-- Rest of World: Tokyo, Seoul, Bangkok, Rio, Buenos Aires, Sydney, Cape Town
INSERT INTO public.city_night_clubs (city_id, name, description, quality_level, capacity, cover_charge, guest_actions, drink_menu, npc_profiles, dj_slot_config, metadata) VALUES
('89b8b930-4fce-4776-a470-8943364ea120', 'WOMB', 'Shibuya mega-club. Four floors of Japanese electronic excellence.', 4, 1000, 30, '[{"label":"Main Floor","description":"World-class Funktion-One","energy_cost":12},{"label":"VIP Floor","description":"Japanese hospitality","energy_cost":14}]', '[{"name":"Tokyo Twilight","price":15,"effect":"+5 energy"},{"name":"Shibuya Sake","price":12,"effect":"+3 charisma"}]', '[{"id":"womb_dj_ken","name":"Ken Ishii","role":"Resident DJ","personality":"Japanese techno pioneer","dialogueHooks":["Japanese techno","futurism","Tokyo nightlife"]},{"id":"womb_owner_takeshi","name":"Takeshi Yamamoto","role":"Club Owner","personality":"Perfectionist","dialogueHooks":["Japanese club culture","omotenashi","sound system obsession"]}]', '{"fameRequirement":1500,"payout":1200,"setLengthMinutes":90,"schedule":"11pm-5am","perks":["+10% Asian fame","+6% technical credibility"]}', '{"live_interactions":true}'),
('89b8b930-4fce-4776-a470-8943364ea120', 'ageHa', 'Tokyo bay mega-club. One of Asias largest.', 5, 4000, 40, '[{"label":"Arena Main","description":"Massive arena","energy_cost":15},{"label":"Beach Stage","description":"Tokyo Bay beach","energy_cost":10}]', '[{"name":"Tokyo Bay Breeze","price":18,"effect":"+6 energy"},{"name":"Mega City Mix","price":20,"effect":"+5 fame"}]', '[{"id":"ageha_promoter_yuki","name":"Yuki Tanaka","role":"Promoter","personality":"Mega-event specialist","dialogueHooks":["mega-events","Asian circuit","Tokyo entertainment"]}]', '{"fameRequirement":3000,"payout":2500,"setLengthMinutes":120,"schedule":"11pm-10am","perks":["+12% Asian fame"]}', '{"live_interactions":true}'),
('65b3346d-0fc9-4319-b711-84a3d553d22b', 'Cakeshop', 'Seoul underground institution in Itaewon.', 2, 200, 10, '[{"label":"Underground Dance","description":"Itaewon vibes","energy_cost":8}]', '[{"name":"Soju Bomb","price":5,"effect":"+3 energy"},{"name":"K-Pop Fizz","price":8,"effect":"+3 mood"}]', '[{"id":"cake_dj_park","name":"Park Hye Jin","role":"Resident DJ","personality":"Korean electronic star","dialogueHooks":["Korean electronic","K-house","Seoul underground"]}]', '{"fameRequirement":300,"payout":350,"setLengthMinutes":60,"schedule":"10pm-5am","perks":["+5% Korean credibility"]}', '{"live_interactions":true}'),
('65b3346d-0fc9-4319-b711-84a3d553d22b', 'Octagon', 'Gangnam mega-club. K-pop meets EDM.', 5, 2000, 40, '[{"label":"LED Main Stage","description":"Immersive LED tunnel","energy_cost":12},{"label":"K-Pop Room","description":"K-pop and hip-hop","energy_cost":8}]', '[{"name":"Gangnam Style","price":18,"effect":"+5 fame"},{"name":"Seoul Sunset","price":15,"effect":"+4 charisma"}]', '[{"id":"oct_vip_jimin","name":"Ji-Min Choi","role":"VIP Regular","personality":"K-pop industry insider","dialogueHooks":["K-pop industry","Korean entertainment","Asian trends"]}]', '{"fameRequirement":5000,"payout":3000,"setLengthMinutes":90,"schedule":"10pm-5am","perks":["+15% K-pop crossover","+10% Asian fame"]}', '{"live_interactions":true}'),
('bbfcf4ba-3d9f-44ab-8413-dd04236174be', 'Beam', 'Bangkok premier underground club.', 3, 400, 15, '[{"label":"Main Room","description":"Dark, deep, immersive","energy_cost":10},{"label":"Garden Bar","description":"Tropical outdoor","energy_cost":5}]', '[{"name":"Thai Basil Smash","price":8,"effect":"+4 energy"},{"name":"Thonglor Tonic","price":10,"effect":"+3 mood"}]', '[{"id":"beam_dj_sunju","name":"Sunju Hargun","role":"Resident DJ","personality":"Bangkok deep house champion","dialogueHooks":["Bangkok scene","Southeast Asian music","vinyl culture"]},{"id":"beam_owner_pong","name":"Pong Suwannakit","role":"Club Owner","personality":"Bangkok innovator","dialogueHooks":["Thai nightlife","Japanese influence","Asian club culture"]}]', '{"fameRequirement":500,"payout":450,"setLengthMinutes":60,"schedule":"10pm-3am","perks":["+5% Southeast Asian credibility"]}', '{"live_interactions":true}'),
('0c9c8a7e-c6b4-4927-932a-8491c2b40a06', 'Fosfobox', 'Tiny Copacabana basement club.', 1, 150, 8, '[{"label":"Basement Samba","description":"Electronic meets Brazilian rhythm","energy_cost":8}]', '[{"name":"Caipirinha Classic","price":6,"effect":"+4 mood"},{"name":"Samba Sour","price":7}]', '[{"id":"fosfo_dj_renato","name":"Renato Ratier","role":"Resident DJ","personality":"Brazilian electronic pioneer","dialogueHooks":["Brazilian electronic","Rio culture","tropical bass"]}]', '{"fameRequirement":150,"payout":200,"setLengthMinutes":60,"schedule":"midnight-6am","perks":["+4% Brazilian credibility"]}', '{"live_interactions":true}'),
('03074fa3-94d0-450d-9520-092f3461daab', 'Crobar', 'Buenos Aires legendary after-hours club.', 3, 600, 15, '[{"label":"Main Room","description":"Argentine passion meets electronic","energy_cost":10},{"label":"After Hours Lounge","description":"Dawn sessions","energy_cost":8}]', '[{"name":"Malbec Mixer","price":8,"effect":"+3 mood"},{"name":"Buenos Aires Bitter","price":6}]', '[{"id":"crobar_dj_hernan","name":"Hernán Cattáneo","role":"Resident DJ","personality":"Argentine progressive house legend","dialogueHooks":["progressive house","Argentine scene","South American touring"]}]', '{"fameRequirement":600,"payout":500,"setLengthMinutes":120,"schedule":"2am-noon","perks":["+7% South American credibility"]}', '{"live_interactions":true}'),
('06a16e6b-5888-4046-90d8-dfca01eda238', 'Chinese Laundry', 'Sydney underground institution.', 2, 300, 15, '[{"label":"Basement Dance","description":"Sydney underground","energy_cost":9}]', '[{"name":"Sydney Sling","price":12,"effect":"+3 mood"},{"name":"Harbour Haze","price":10}]', '[{"id":"laundry_dj_touch","name":"Touch Sensitive","role":"Resident DJ","personality":"Australian nu-disco legend","dialogueHooks":["Australian electronic","nu-disco","Sydney scene"]}]', '{"fameRequirement":400,"payout":400,"setLengthMinutes":60,"schedule":"10pm-4am","perks":["+5% Australian credibility"]}', '{"live_interactions":true}'),
('2d9e6eca-87f9-45c4-8d19-b431032ea46b', 'Fiction', 'Cape Town premier DJ bar. South African bass culture.', 2, 250, 10, '[{"label":"DJ Bar Vibes","description":"Intimate South African beats","energy_cost":8}]', '[{"name":"Cape Crush","price":7,"effect":"+3 energy"},{"name":"Table Mountain Tonic","price":9,"effect":"+3 mood"}]', '[{"id":"fiction_dj_black","name":"Black Coffee","role":"Resident DJ","personality":"South African house icon","dialogueHooks":["Afro house","South African identity","global success"]},{"id":"fiction_bartender_thandi","name":"Thandi Nkosi","role":"Bartender","personality":"Warm, storyteller","dialogueHooks":["Cape Town culture","South African stories","local legends"]}]', '{"fameRequirement":400,"payout":400,"setLengthMinutes":60,"schedule":"10pm-4am","perks":["+6% African credibility"]}', '{"live_interactions":true}');

-- USA remaining: Nashville, Austin, SF, Atlanta, Detroit, Boston, Philly
INSERT INTO public.city_night_clubs (city_id, name, description, quality_level, capacity, cover_charge, guest_actions, drink_menu, npc_profiles, dj_slot_config, metadata) VALUES
('2a518758-067c-4d34-8ff6-666a31169fe7', 'Cannery Ballroom', 'Historic Nashville venue turned electronic hub.', 3, 800, 18, '[{"label":"Ballroom Dance","description":"Grand ballroom experience","energy_cost":10}]', '[{"name":"Cannery Cocktail","price":12,"effect":"+4 energy"},{"name":"Tennessee Twist","price":10}]', '[{"id":"cannery_promoter_lisa","name":"Lisa Sterling","role":"Promoter","personality":"Nashville nightlife champion","dialogueHooks":["Nashville evolution","live music meets DJ","Southern hospitality"]}]', '{"fameRequirement":600,"payout":550,"setLengthMinutes":60,"schedule":"9pm-3am","perks":["+5% Southern fame"]}', '{"live_interactions":true}'),
('8215d23e-5714-478e-9ac8-b7b82994fdc6', 'The Concourse Project', 'Austin mega-venue. Multi-room warehouse.', 4, 2000, 30, '[{"label":"Main Warehouse","description":"Massive warehouse rave","energy_cost":12}]', '[{"name":"Texas Thunder","price":14,"effect":"+5 energy"},{"name":"Austin Powers","price":16,"effect":"+4 fame"}]', '[{"id":"concourse_owner_mike","name":"Mike Finn","role":"Club Owner","personality":"Austin entertainment mogul","dialogueHooks":["Austin entertainment","SXSW","Texas nightlife"]}]', '{"fameRequirement":1500,"payout":1200,"setLengthMinutes":90,"schedule":"9pm-4am","perks":["+8% Austin fame"]}', '{"live_interactions":true}'),
('73fae343-9a12-4ecb-867f-ad6ec3699364', 'The Midway', 'SF massive warehouse venue in Dogpatch.', 3, 1000, 20, '[{"label":"Warehouse Floor","description":"Art-meets-music warehouse","energy_cost":10}]', '[{"name":"Dogpatch Draft","price":9,"effect":"+3 energy"},{"name":"Golden Gate Gimlet","price":13}]', '[{"id":"midway_promoter_derek","name":"Derek Vincent Smith","role":"Promoter","personality":"SF arts-music bridge builder","dialogueHooks":["SF arts scene","warehouse culture","Bay Area promotion"]}]', '{"fameRequirement":600,"payout":550,"setLengthMinutes":60,"schedule":"10pm-4am","perks":["+5% SF fame"]}', '{"live_interactions":true}'),
('872150e0-6fa6-4150-b622-b0f8e60ea6fb', 'Ravine', 'Atlanta mega-club. Trap capital meets electronic.', 4, 1500, 30, '[{"label":"Main Room","description":"ATL mega-club","energy_cost":12},{"label":"Trap Room","description":"Pure trap and hip-hop","energy_cost":10}]', '[{"name":"Atlanta Anthem","price":15,"effect":"+5 fame"},{"name":"Trap Tonic","price":12,"effect":"+4 energy"}]', '[{"id":"ravine_vip_ty","name":"Ty Robinson","role":"VIP Regular","personality":"Atlanta hip-hop mogul","dialogueHooks":["Atlanta hip-hop","trap culture","music business"]}]', '{"fameRequirement":2000,"payout":1500,"setLengthMinutes":90,"schedule":"10pm-4am","perks":["+10% ATL fame"]}', '{"live_interactions":true}'),
('0f6c3eea-29c4-443b-b505-171a6d97c3f5', 'TV Lounge', 'Detroit techno temple.', 2, 200, 10, '[{"label":"Techno Temple","description":"Detroit techno at its purest","energy_cost":9}]', '[{"name":"Motor City Mule","price":7,"effect":"+3 energy"},{"name":"Detroit Diesel","price":6}]', '[{"id":"tv_dj_kyle","name":"Kyle Hall","role":"Resident DJ","personality":"Young Detroit prodigy","dialogueHooks":["Detroit techno heritage","hardware production","Motor City pride"]}]', '{"fameRequirement":300,"payout":350,"setLengthMinutes":60,"schedule":"10pm-4am","perks":["+6% Detroit techno credibility"]}', '{"live_interactions":true}'),
('37e3030a-2f21-4d37-985c-4660360665ca', 'Royale', 'Boston premier nightclub. Converted church.', 3, 1200, 25, '[{"label":"Church Dance","description":"Dance in a converted church","energy_cost":10}]', '[{"name":"Royale Flush","price":14,"effect":"+4 charisma"},{"name":"Beacon Hill Brew","price":10}]', '[{"id":"royale_owner_ed","name":"Ed Kane","role":"Club Owner","personality":"Boston nightlife institution","dialogueHooks":["Boston nightlife","church conversion","community events"]}]', '{"fameRequirement":800,"payout":700,"setLengthMinutes":60,"schedule":"10pm-2am","perks":["+6% Boston fame"]}', '{"live_interactions":true}'),
('5c8b81fd-519b-4f7b-99e5-0a7d0f7b482f', 'NOTO', 'Philadelphia massive nightclub.', 3, 1500, 25, '[{"label":"Main Floor","description":"Philly mega-club","energy_cost":10}]', '[{"name":"Philly Special","price":12,"effect":"+4 energy"},{"name":"Liberty Bell","price":10}]', '[{"id":"noto_dj_king","name":"King Britt","role":"Resident DJ","personality":"Philadelphia electronic legend","dialogueHooks":["Philly house","Afrofuturism","Philadelphia scene"]}]', '{"fameRequirement":600,"payout":550,"setLengthMinutes":60,"schedule":"10pm-3am","perks":["+5% Philly fame"]}', '{"live_interactions":true}');

-- =============================================
-- SEED QUESTS FOR LONDON CLUBS
-- =============================================

INSERT INTO public.nightclub_quests (club_id, npc_id, title, description, quest_type, chain_position, chain_id, requirements, dialogue, rewards, energy_cost, cooldown_hours) VALUES
('63eb90b9-ee29-40bd-9aab-da76aac90d1b', 'rebel_dj', 'Prove Your Chops', 'DJ Rebel wants to see if you can handle the decks.', 'chain', 1, 'electric_basement_rebel', '{"min_fame":50}', '[{"speaker":"npc","text":"Oi, you. Yeah, you with the headphones. Think you can spin?"},{"speaker":"player_choice","options":[{"label":"I''ve been spinning since I was 15","next":2,"affinity_change":5},{"label":"I''m here to learn from the best","next":3,"affinity_change":3},{"label":"Just here for the vibes","next":4,"affinity_change":-2}]},{"speaker":"npc","text":"Ha! Big talk. I like that. Get on the decks for three tracks. Impress me."},{"speaker":"npc","text":"Humble. I respect that. Let me see what you can do. Three tracks."},{"speaker":"npc","text":"Fair enough, but fancy having a go? Three tracks, just for fun."},{"speaker":"npc","text":"Not bad at all. You''ve got potential. Come back for the real challenge.","quest_complete":true}]', '{"cash":100,"xp":50,"skill_boost":{"skill":"turntablism","amount":1},"npc_relationship":{"affinity":10,"trust":5}}', 10, 0),
('63eb90b9-ee29-40bd-9aab-da76aac90d1b', 'rebel_dj', 'Underground Connections', 'Help DJ Rebel track down a rare vinyl pressing.', 'chain', 2, 'electric_basement_rebel', '{"min_fame":150}', '[{"speaker":"npc","text":"You proved yourself. Now I need a favour. There''s a rare pressing of Strings of Life — original Detroit pressing."},{"speaker":"player_choice","options":[{"label":"I''ll find it. What''s it worth?","next":2,"affinity_change":3},{"label":"Strings of Life? Holy grail!","next":3,"affinity_change":8}]},{"speaker":"npc","text":"Straight to business. Find it and I''ll give you something money can''t buy."},{"speaker":"npc","text":"You KNOW your records! Bring it back and I''ll hook you up proper."},{"speaker":"npc","text":"You absolute legend! Here — I recorded something special for you.","quest_complete":true}]', '{"cash":250,"fame":50,"xp":75,"gifted_song":true,"npc_relationship":{"affinity":15,"trust":10,"respect":10}}', 15, 0),
('5b62aa41-f92f-4a16-b095-5ec80f91d54a', 'synthia_vega', 'Synthia''s Challenge', 'Resident DJ Synthia Vega wants you to remix her latest track.', 'chain', 1, 'neon_dreams_synthia', '{"min_fame":200}', '[{"speaker":"npc","text":"Hey! You''re that new DJ everyone''s talking about. I''ve got a proposition."},{"speaker":"player_choice","options":[{"label":"What kind of proposition?","next":2,"affinity_change":3},{"label":"What''s in it for me?","next":3,"affinity_change":1}]},{"speaker":"npc","text":"I''ve got this track that needs a fresh perspective. A remix. Think you can handle it?"},{"speaker":"npc","text":"Direct. Here''s the deal — remix my latest track. If it''s good, people hear YOUR version."},{"speaker":"npc","text":"This is incredible. You''ve completely transformed it. I''m playing this tonight.","quest_complete":true}]', '{"cash":300,"fame":75,"xp":75,"gifted_song":true,"skill_boost":{"skill":"production","amount":1},"npc_relationship":{"affinity":12,"respect":8}}', 12, 0),
('5b62aa41-f92f-4a16-b095-5ec80f91d54a', 'marcus_steel', 'Steel''s Proposition', 'Promoter Marcus Steel has a deal: promote Neon Dreams on social media.', 'one_time', null, null, '{"min_fame":100}', '[{"speaker":"npc","text":"Yo! Marcus Steel, promoter extraordinaire. Got a business opportunity."},{"speaker":"player_choice","options":[{"label":"I''m listening...","next":2,"affinity_change":3},{"label":"Not my thing","next":3,"affinity_change":-3}]},{"speaker":"npc","text":"Post about Neon Dreams on socials. Tag us. I''ll pay £500 and boost your followers."},{"speaker":"npc","text":"Your loss. Find me if you change your mind.","quest_complete":true},{"speaker":"npc","text":"Legend! Posts are getting traction. Here''s your cut.","quest_complete":true}]', '{"cash":500,"fans":50,"fame":30,"npc_relationship":{"affinity":8,"trust":5}}', 8, 0),
('5318c032-b3f7-4a46-86a1-7a8a82c877e8', 'vincent_noir', 'Vincent''s Test', 'Club owner Vincent Noir wants you to entertain his VIP guests.', 'chain', 1, 'velvet_room_vincent', '{"min_fame":1000}', '[{"speaker":"npc","text":"You must be the one everyone''s whispering about. I''m Vincent Noir. Welcome to The Velvet Room."},{"speaker":"player_choice","options":[{"label":"It''s an honour","next":2,"affinity_change":5},{"label":"Nice place. Could use better music","next":3,"affinity_change":8}]},{"speaker":"npc","text":"Charming. But charm won''t cut it here. I have important guests tonight. Can you deliver?"},{"speaker":"npc","text":"Ha! Audacious. Most people grovel. You might be what this place needs."},{"speaker":"npc","text":"My guests are raving about you. You''ve earned this.","quest_complete":true}]', '{"cash":2000,"fame":100,"xp":100,"npc_relationship":{"affinity":15,"trust":10,"respect":15}}', 20, 0),
('5318c032-b3f7-4a46-86a1-7a8a82c877e8', 'vincent_noir', 'Industry Insider', 'Network with 3 VIPs at The Velvet Room.', 'chain', 2, 'velvet_room_vincent', '{"min_fame":1500}', '[{"speaker":"npc","text":"You''ve proven you can perform. Now let''s see if you can network. Three people to meet tonight."},{"speaker":"player_choice","options":[{"label":"Who are they?","next":2,"affinity_change":3},{"label":"I work better alone","next":3,"affinity_change":-2}]},{"speaker":"npc","text":"A label exec, a festival booker, and a journalist. Impress all three."},{"speaker":"npc","text":"Nobody works alone in this business. Trust me."},{"speaker":"npc","text":"All three are singing your praises. Welcome to the inside.","quest_complete":true}]', '{"cash":1000,"fame":150,"fans":100,"xp":100,"npc_relationship":{"affinity":10,"trust":15,"respect":10}}', 18, 0),
('5318c032-b3f7-4a46-86a1-7a8a82c877e8', 'vincent_noir', 'The Velvet Residency', 'Secure a recurring DJ residency at The Velvet Room.', 'chain', 3, 'velvet_room_vincent', '{"min_fame":2500}', '[{"speaker":"npc","text":"You''ve entertained my guests. You''ve networked with the elite. Now... one final proposition."},{"speaker":"player_choice","options":[{"label":"A residency?","next":2,"affinity_change":5},{"label":"Name your price","next":3,"affinity_change":3}]},{"speaker":"npc","text":"A weekly residency at The Velvet Room. Guaranteed slot, pay, and prestige."},{"speaker":"npc","text":"It''s not about price. It''s about prestige. Are you in?"},{"speaker":"npc","text":"Welcome to the family. Your residency starts next week.","quest_complete":true}]', '{"cash":5000,"fame":300,"fans":200,"xp":200,"skill_boost":{"skill":"performance","amount":2},"equipment_reward":true,"npc_relationship":{"affinity":20,"trust":20,"respect":20}}', 25, 0),
('9528ad61-7c28-4042-9f04-1c31d5d6c2aa', 'hacc_dj', 'Madchester Memories', 'Recreate the spirit of the original Madchester movement at The Haccienda.', 'one_time', null, null, '{"min_fame":3000}', '[{"speaker":"npc","text":"This building has history, mate. The Smiths, Joy Division, Happy Mondays — they all came through here."},{"speaker":"player_choice","options":[{"label":"I''m here to make new history","next":2,"affinity_change":10},{"label":"Tell me about the old days","next":3,"affinity_change":5}]},{"speaker":"npc","text":"That''s what I want to hear! Play a set that honours the past but pushes forward."},{"speaker":"npc","text":"Where do I begin? It was magic. But prove the magic isn''t dead."},{"speaker":"npc","text":"That was something special. The Haccienda lives on through people like you.","quest_complete":true}]', '{"cash":3000,"fame":200,"xp":150,"fans":150,"skill_boost":{"skill":"performance","amount":2},"npc_relationship":{"affinity":20,"trust":15,"respect":20}}', 20, 0),
('63eb90b9-ee29-40bd-9aab-da76aac90d1b', 'rebel_dj', 'Open Deck Night', 'DJ Rebel is hosting an open deck night. Step up for one track.', 'repeatable', null, null, '{"min_fame":0}', '[{"speaker":"npc","text":"Open deck night! Step up, play one track, show us what you''ve got."},{"speaker":"player_choice","options":[{"label":"Let me on those decks!","next":2,"affinity_change":2},{"label":"Maybe next time","next":3,"affinity_change":0}]},{"speaker":"npc","text":"Get up there! One track, make it count."},{"speaker":"npc","text":"No worries, next time."},{"speaker":"npc","text":"Solid track choice. Getting better every time.","quest_complete":true}]', '{"cash":50,"xp":25,"fame":10,"npc_relationship":{"affinity":3}}', 5, 24);
