-- Canonical festival audience simulation and performance outcome layer.
-- Additive migration after 20291209090000_festival_performance_sessions.sql.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$ BEGIN CREATE TYPE public.festival_outcome_status AS ENUM ('pending','calculating','calculated','finalised','invalidated','superseded','application_pending','applied'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.festival_audience_cohort_type AS ENUM ('local_casual_fans','local_genre_fans','travelling_genre_fans','hardcore_band_fans','festival_loyalists','social_attendees','families','tourists','vip_guests','industry_media','sponsor_guests','staff_performers'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.festival_crowd_state AS ENUM ('arriving','curious','attentive','engaged','singing','dancing','excited','ecstatic','restless','bored','leaving','fatigued','concerned','unsafe'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.festival_audience_simulation_configs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version text NOT NULL UNIQUE,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  demand_weights jsonb NOT NULL DEFAULT '{"expected_attendance":0.55,"lineup_depth":0.15,"headliner":0.12,"genre_fit":0.08,"ticket_price":-0.05,"facility":0.05}'::jsonb,
  cohort_weights jsonb NOT NULL DEFAULT '{"local_casual_fans":0.2,"local_genre_fans":0.18,"travelling_genre_fans":0.12,"hardcore_band_fans":0.12,"festival_loyalists":0.12,"social_attendees":0.1,"families":0.04,"tourists":0.04,"vip_guests":0.02,"industry_media":0.02,"sponsor_guests":0.02,"staff_performers":0.02}'::jsonb,
  genre_fit_weights jsonb NOT NULL DEFAULT '{}',
  fame_weights jsonb NOT NULL DEFAULT '{}',
  elasticity jsonb NOT NULL DEFAULT '{"ticket_price":0.08,"travel_distance":0.04,"weather":0.05,"timetable_clash":0.1,"stage_capacity":0.2}'::jsonb,
  satisfaction_thresholds jsonb NOT NULL DEFAULT '{"bored":35,"attentive":50,"engaged":65,"excited":78,"ecstatic":90}'::jsonb,
  fan_conversion_thresholds jsonb NOT NULL DEFAULT '{"casual":60,"engaged":75,"dedicated":88}'::jsonb,
  randomness jsonb NOT NULL DEFAULT '{"audience_variation_pct":4,"performance_variation_points":3}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  activated_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS festival_audience_one_active_config_idx ON public.festival_audience_simulation_configs(is_active) WHERE is_active;

INSERT INTO public.festival_audience_simulation_configs(version,name,is_active,activated_at)
VALUES ('festival_audience_outcome_v1','Festival audience and outcome model v1',true,now())
ON CONFLICT (version) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.festival_audience_generations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), edition_id uuid NOT NULL REFERENCES public.festival_editions(id) ON DELETE CASCADE,
  config_id uuid NOT NULL REFERENCES public.festival_audience_simulation_configs(id), config_version text NOT NULL,
  idempotency_key text NOT NULL, input_hash text NOT NULL, deterministic_seed text NOT NULL,
  estimated_demand integer NOT NULL CHECK (estimated_demand >= 0), ticket_holders integer NOT NULL CHECK (ticket_holders >= 0), actual_arrivals integer NOT NULL CHECK (actual_arrivals >= 0), no_shows integer NOT NULL CHECK (no_shows >= 0),
  source_facts jsonb NOT NULL DEFAULT '{}', metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(edition_id), UNIQUE(edition_id,idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.festival_audience_cohorts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), generation_id uuid NOT NULL REFERENCES public.festival_audience_generations(id) ON DELETE CASCADE, edition_id uuid NOT NULL REFERENCES public.festival_editions(id) ON DELETE CASCADE,
  cohort_type public.festival_audience_cohort_type NOT NULL, estimated_demand integer NOT NULL CHECK (estimated_demand >= 0), ticket_holders integer NOT NULL CHECK (ticket_holders >= 0), actual_arrivals integer NOT NULL CHECK (actual_arrivals >= 0),
  average_budget_cents bigint NOT NULL DEFAULT 0, patience numeric NOT NULL DEFAULT 60, genre_preferences jsonb NOT NULL DEFAULT '[]', band_affinities jsonb NOT NULL DEFAULT '{}', comfort_expectations jsonb NOT NULL DEFAULT '{}', spending_tendencies jsonb NOT NULL DEFAULT '{}', arrival_window jsonb NOT NULL DEFAULT '{}', departure_behaviour jsonb NOT NULL DEFAULT '{}', mobility numeric NOT NULL DEFAULT 0.5,
  config_version text NOT NULL, source_facts jsonb NOT NULL DEFAULT '{}', metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(edition_id,cohort_type)
);

CREATE TABLE IF NOT EXISTS public.festival_stage_crowd_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), edition_id uuid NOT NULL REFERENCES public.festival_editions(id) ON DELETE CASCADE, stage_id uuid, session_id uuid REFERENCES public.festival_performance_sessions(id) ON DELETE SET NULL, snapshot_at timestamptz NOT NULL,
  idempotency_key text NOT NULL, input_hash text NOT NULL, config_version text NOT NULL,
  audience_total integer NOT NULL CHECK (audience_total >= 0), cohort_distribution jsonb NOT NULL DEFAULT '{}', capacity integer, density numeric NOT NULL DEFAULT 0, entry_flow integer NOT NULL DEFAULT 0, exit_flow integer NOT NULL DEFAULT 0, queue_estimate integer NOT NULL DEFAULT 0,
  satisfaction numeric NOT NULL DEFAULT 60, excitement numeric NOT NULL DEFAULT 50, fatigue numeric NOT NULL DEFAULT 0, safety_pressure numeric NOT NULL DEFAULT 0, crowd_state public.festival_crowd_state NOT NULL DEFAULT 'attentive', current_attraction numeric NOT NULL DEFAULT 50, next_act_attraction numeric NOT NULL DEFAULT 50, weather_impact numeric NOT NULL DEFAULT 0, incident_impact numeric NOT NULL DEFAULT 0, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(edition_id,stage_id,snapshot_at), UNIQUE(edition_id,idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.festival_performance_audience_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_id uuid NOT NULL UNIQUE REFERENCES public.festival_performance_sessions(id) ON DELETE CASCADE, edition_id uuid NOT NULL REFERENCES public.festival_editions(id), stage_id uuid, source_crowd_snapshot_id uuid REFERENCES public.festival_stage_crowd_snapshots(id), config_version text NOT NULL,
  audience_at_start integer NOT NULL CHECK (audience_at_start >= 0), audience_cohorts jsonb NOT NULL DEFAULT '{}', capacity_percentage numeric NOT NULL DEFAULT 0, expected_audience integer NOT NULL DEFAULT 0, crowd_fit numeric NOT NULL DEFAULT 50, initial_excitement numeric NOT NULL DEFAULT 50, initial_patience numeric NOT NULL DEFAULT 60, fan_ratio numeric NOT NULL DEFAULT 0.5, media_presence integer NOT NULL DEFAULT 0, industry_presence integer NOT NULL DEFAULT 0, sponsor_presence integer NOT NULL DEFAULT 0, input_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.festival_performance_outcomes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_id uuid NOT NULL REFERENCES public.festival_performance_sessions(id) ON DELETE CASCADE, edition_id uuid NOT NULL, festival_id uuid NOT NULL, band_id uuid NOT NULL,
  status public.festival_outcome_status NOT NULL DEFAULT 'calculated', model_version text NOT NULL, config_version text NOT NULL, audience_model_version text NOT NULL, source_session_version integer NOT NULL, calculation_seed text NOT NULL, idempotency_key text NOT NULL, input_hash text NOT NULL,
  overall_score numeric NOT NULL, technical_score numeric NOT NULL, musicianship_score numeric NOT NULL, setlist_score numeric NOT NULL, stagecraft_score numeric NOT NULL, crowd_connection_score numeric NOT NULL, professionalism_score numeric NOT NULL, readiness_score numeric NOT NULL, reliability_score numeric NOT NULL, audience_growth_score numeric NOT NULL, media_score numeric NOT NULL, festival_fit_score numeric NOT NULL, highlight_score numeric NOT NULL, incident_penalty numeric NOT NULL DEFAULT 0, lateness_penalty numeric NOT NULL DEFAULT 0, curtailment_penalty numeric NOT NULL DEFAULT 0, completion_modifier numeric NOT NULL DEFAULT 1,
  invalidated_at timestamptz, invalidated_by uuid REFERENCES public.profiles(id), invalidation_reason text, superseded_by_outcome_id uuid, calculated_at timestamptz NOT NULL DEFAULT now(), finalised_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}',
  UNIQUE(session_id,model_version), UNIQUE(session_id,idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.festival_song_performance_outcomes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), outcome_id uuid NOT NULL REFERENCES public.festival_performance_outcomes(id) ON DELETE CASCADE, session_id uuid NOT NULL REFERENCES public.festival_performance_sessions(id) ON DELETE CASCADE, setlist_position integer NOT NULL, song_id uuid, status text NOT NULL,
  actual_duration_seconds integer, performance_quality numeric NOT NULL, technical_execution numeric NOT NULL, familiarity_contribution numeric NOT NULL, musicianship_contribution numeric NOT NULL, crowd_fit numeric NOT NULL, crowd_response numeric NOT NULL, singalong_response numeric NOT NULL, dancing_response numeric NOT NULL, energy_change numeric NOT NULL, audience_retained integer NOT NULL DEFAULT 0, audience_gained integer NOT NULL DEFAULT 0, audience_lost integer NOT NULL DEFAULT 0, media_reaction numeric NOT NULL DEFAULT 0, incident_effects jsonb NOT NULL DEFAULT '[]', guest_contribution jsonb NOT NULL DEFAULT '{}', highlight_status text NOT NULL DEFAULT 'none', evidence_snapshot jsonb NOT NULL DEFAULT '{}', model_version text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(outcome_id,setlist_position)
);

CREATE TABLE IF NOT EXISTS public.festival_fan_conversion_outcomes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), outcome_id uuid NOT NULL UNIQUE REFERENCES public.festival_performance_outcomes(id) ON DELETE CASCADE, session_id uuid NOT NULL, band_id uuid NOT NULL, new_casual_fans integer NOT NULL DEFAULT 0, new_engaged_fans integer NOT NULL DEFAULT 0, new_dedicated_fans integer NOT NULL DEFAULT 0, lost_fans integer NOT NULL DEFAULT 0, local_fan_gains integer NOT NULL DEFAULT 0, travelling_fan_gains integer NOT NULL DEFAULT 0, genre_community_gains integer NOT NULL DEFAULT 0, cohort_breakdown jsonb NOT NULL DEFAULT '{}', conversion_explanation text NOT NULL, model_version text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.festival_performance_effects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), outcome_id uuid NOT NULL REFERENCES public.festival_performance_outcomes(id) ON DELETE CASCADE, entity_type text NOT NULL, entity_id uuid, effect_type text NOT NULL, proposed_value numeric NOT NULL, effect_payload jsonb NOT NULL DEFAULT '{}', explanation text NOT NULL, model_version text NOT NULL, application_status public.festival_outcome_status NOT NULL DEFAULT 'application_pending', applied_at timestamptz, application_idempotency_key text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(outcome_id,entity_type,entity_id,effect_type));
CREATE TABLE IF NOT EXISTS public.festival_media_outcomes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), outcome_id uuid NOT NULL REFERENCES public.festival_performance_outcomes(id) ON DELETE CASCADE, media_type text NOT NULL, tone text NOT NULL, sentiment_score numeric NOT NULL, public_summary text NOT NULL, structured_facts jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.festival_sponsor_outcomes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), outcome_id uuid NOT NULL REFERENCES public.festival_performance_outcomes(id) ON DELETE CASCADE, sponsor_entity_id uuid, sentiment_score numeric NOT NULL, visibility_score numeric NOT NULL, professionalism_score numeric NOT NULL, renewal_interest numeric NOT NULL, explanation text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.festival_performance_highlights (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), outcome_id uuid REFERENCES public.festival_performance_outcomes(id) ON DELETE CASCADE, session_id uuid NOT NULL REFERENCES public.festival_performance_sessions(id) ON DELETE CASCADE, song_outcome_id uuid REFERENCES public.festival_song_performance_outcomes(id) ON DELETE SET NULL, setlist_position integer, occurred_at timestamptz, highlight_type text NOT NULL, is_positive boolean NOT NULL, intensity numeric NOT NULL, public_description text NOT NULL, internal_evidence jsonb NOT NULL DEFAULT '{}', viewer_presentation_metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.festival_outcome_publications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), outcome_id uuid NOT NULL REFERENCES public.festival_performance_outcomes(id) ON DELETE CASCADE, publication_type text NOT NULL, public_payload jsonb NOT NULL, dedupe_key text NOT NULL UNIQUE, published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());

CREATE OR REPLACE FUNCTION public.festival_outcome_hash(p_value jsonb) RETURNS text LANGUAGE sql IMMUTABLE SET search_path=public AS $$ SELECT encode(digest(COALESCE(p_value,'null'::jsonb)::text,'sha256'),'hex') $$;
CREATE OR REPLACE FUNCTION public.festival_score_clamp(p_value numeric) RETURNS numeric LANGUAGE sql IMMUTABLE SET search_path=public AS $$ SELECT LEAST(100, GREATEST(0, COALESCE(p_value,0))) $$;
CREATE OR REPLACE FUNCTION public.festival_seeded_variation(p_seed text, p_scope text, p_range numeric) RETURNS numeric LANGUAGE sql IMMUTABLE SET search_path=public AS $$ SELECT (((('x'||substr(md5(coalesce(p_seed,'')||':'||coalesce(p_scope,'')),1,8))::bit(32)::bigint % 10000) / 10000.0) * 2 - 1) * p_range $$;

CREATE OR REPLACE FUNCTION public.generate_festival_edition_audience(p_edition_id uuid, p_idempotency_key text)
RETURNS public.festival_audience_generations LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE e public.festival_editions%ROWTYPE; cfg public.festival_audience_simulation_configs%ROWTYPE; existing public.festival_audience_generations%ROWTYPE; facts jsonb; h text; seed text; cap integer; expected integer; demand integer; holders integer; arrivals integer; k text; w numeric; allocated integer:=0; ctype public.festival_audience_cohort_type; amount integer; last_type text:='staff_performers';
BEGIN
 IF nullif(btrim(p_idempotency_key),'') IS NULL THEN RAISE EXCEPTION 'idempotency key required'; END IF;
 SELECT * INTO e FROM public.festival_editions WHERE id=p_edition_id FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'Festival edition not found'; END IF;
 SELECT * INTO cfg FROM public.festival_audience_simulation_configs WHERE is_active ORDER BY activated_at DESC NULLS LAST LIMIT 1;
 facts:=jsonb_build_object('edition_id',e.id,'festival_id',e.festival_id,'status',e.status,'expected_attendance',e.expected_attendance,'capacity',e.capacity,'min_ticket_price_cents',e.minimum_ticket_price_cents,'max_ticket_price_cents',e.maximum_ticket_price_cents,'active_contracts',(SELECT count(*) FROM public.festival_contracts c WHERE c.edition_id=e.id AND c.status='active'));
 h:=public.festival_outcome_hash(facts); SELECT * INTO existing FROM public.festival_audience_generations WHERE edition_id=e.id AND idempotency_key=p_idempotency_key; IF FOUND THEN IF existing.input_hash<>h THEN RAISE EXCEPTION 'Idempotency key reused with changed audience inputs'; END IF; RETURN existing; END IF;
 SELECT * INTO existing FROM public.festival_audience_generations WHERE edition_id=e.id; IF FOUND THEN RETURN existing; END IF;
 cap:=GREATEST(0,COALESCE(e.capacity,e.expected_attendance,1000)); expected:=GREATEST(0,COALESCE(e.expected_attendance,cap)); seed:=public.festival_outcome_hash(jsonb_build_object('edition_id',e.id,'key',p_idempotency_key,'hash',h));
 demand:=GREATEST(0,ROUND(expected * (1 + public.festival_seeded_variation(seed,'demand',0.04)))::integer); holders:=LEAST(cap,demand); arrivals:=LEAST(holders,GREATEST(0,ROUND(holders * (0.90 + public.festival_seeded_variation(seed,'arrivals',0.03)))::integer));
 INSERT INTO public.festival_audience_generations(edition_id,config_id,config_version,idempotency_key,input_hash,deterministic_seed,estimated_demand,ticket_holders,actual_arrivals,no_shows,source_facts) VALUES(e.id,cfg.id,cfg.version,p_idempotency_key,h,seed,demand,holders,arrivals,GREATEST(0,holders-arrivals),facts) RETURNING * INTO existing;
 FOR k,w IN SELECT key,(value)::text::numeric FROM jsonb_each(cfg.cohort_weights) LOOP
   ctype:=k::public.festival_audience_cohort_type; amount:=CASE WHEN k=last_type THEN arrivals-allocated ELSE floor(arrivals*w)::integer END; allocated:=allocated+amount;
   INSERT INTO public.festival_audience_cohorts(generation_id,edition_id,cohort_type,estimated_demand,ticket_holders,actual_arrivals,average_budget_cents,patience,mobility,config_version,source_facts)
   VALUES(existing.id,e.id,ctype,floor(demand*w)::integer,floor(holders*w)::integer,GREATEST(0,amount),COALESCE(e.minimum_ticket_price_cents,0)*2,CASE WHEN k IN ('families','vip_guests') THEN 75 ELSE 60 END,CASE WHEN k IN ('travelling_genre_fans','hardcore_band_fans') THEN 0.7 ELSE 0.5 END,cfg.version,facts);
 END LOOP;
 RETURN existing;
END $$;

CREATE OR REPLACE FUNCTION public.simulate_festival_crowd_movement(p_edition_id uuid, p_at timestamptz, p_idempotency_key text)
RETURNS SETOF public.festival_stage_crowd_snapshots LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE gen public.festival_audience_generations%ROWTYPE; cfgver text; h text; existing_count integer; total_cap integer; sess record; share numeric; audience integer; used integer:=0; stagecap integer; snap public.festival_stage_crowd_snapshots%ROWTYPE; bucket timestamptz:=date_trunc('minute',p_at);
BEGIN
 IF nullif(btrim(p_idempotency_key),'') IS NULL THEN RAISE EXCEPTION 'idempotency key required'; END IF;
 SELECT * INTO gen FROM public.festival_audience_generations WHERE edition_id=p_edition_id; IF NOT FOUND THEN gen:=public.generate_festival_edition_audience(p_edition_id,p_idempotency_key||':audience'); END IF; cfgver:=gen.config_version;
 h:=public.festival_outcome_hash(jsonb_build_object('edition_id',p_edition_id,'at',bucket,'arrivals',gen.actual_arrivals,'sessions',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'stage_id',stage_id,'band_id',band_id,'status',status,'start',scheduled_start_at,'end',scheduled_end_at) ORDER BY scheduled_start_at),'[]'::jsonb) FROM public.festival_performance_sessions WHERE edition_id=p_edition_id AND scheduled_start_at <= bucket + interval '45 minutes' AND scheduled_end_at >= bucket - interval '15 minutes')));
 SELECT count(*) INTO existing_count FROM public.festival_stage_crowd_snapshots WHERE edition_id=p_edition_id AND idempotency_key=p_idempotency_key; IF existing_count>0 THEN IF EXISTS(SELECT 1 FROM public.festival_stage_crowd_snapshots WHERE edition_id=p_edition_id AND idempotency_key=p_idempotency_key AND input_hash<>h) THEN RAISE EXCEPTION 'Idempotency key reused with changed crowd inputs'; END IF; RETURN QUERY SELECT * FROM public.festival_stage_crowd_snapshots WHERE edition_id=p_edition_id AND idempotency_key=p_idempotency_key ORDER BY audience_total DESC; RETURN; END IF;
 SELECT GREATEST(1,COALESCE(sum(COALESCE(st.capacity, fe.capacity, gen.actual_arrivals)),gen.actual_arrivals,1)) INTO total_cap FROM public.festival_performance_sessions s LEFT JOIN public.festival_stages st ON st.id=s.stage_id JOIN public.festival_editions fe ON fe.id=s.edition_id WHERE s.edition_id=p_edition_id AND s.scheduled_start_at <= bucket + interval '45 minutes' AND s.scheduled_end_at >= bucket - interval '15 minutes';
 FOR sess IN SELECT s.*,COALESCE(st.capacity, fe.capacity, gen.actual_arrivals) AS capacity FROM public.festival_performance_sessions s JOIN public.festival_editions fe ON fe.id=s.edition_id LEFT JOIN public.festival_stages st ON st.id=s.stage_id WHERE s.edition_id=p_edition_id AND s.scheduled_start_at <= bucket + interval '45 minutes' AND s.scheduled_end_at >= bucket - interval '15 minutes' ORDER BY s.scheduled_start_at LOOP
   stagecap:=GREATEST(0,COALESCE(sess.capacity,gen.actual_arrivals)); share:=stagecap::numeric/GREATEST(1,total_cap); audience:=LEAST(stagecap, GREATEST(0, ROUND(gen.actual_arrivals*share)::integer)); IF used+audience>gen.actual_arrivals THEN audience:=GREATEST(0,gen.actual_arrivals-used); END IF; used:=used+audience;
   INSERT INTO public.festival_stage_crowd_snapshots(edition_id,stage_id,session_id,snapshot_at,idempotency_key,input_hash,config_version,audience_total,cohort_distribution,capacity,density,satisfaction,excitement,fatigue,safety_pressure,crowd_state,current_attraction,metadata)
   VALUES(p_edition_id,sess.stage_id,sess.id,bucket,p_idempotency_key,h,cfgver,audience,(SELECT COALESCE(jsonb_object_agg(cohort_type,actual_arrivals),'{}') FROM public.festival_audience_cohorts WHERE edition_id=p_edition_id),stagecap,CASE WHEN stagecap>0 THEN audience::numeric/stagecap ELSE 0 END,60,55 + public.festival_seeded_variation(gen.deterministic_seed,sess.id::text,5),10,CASE WHEN stagecap>0 THEN GREATEST(0,(audience::numeric/stagecap)-0.9)*100 ELSE 0 END,CASE WHEN stagecap>0 AND audience::numeric/stagecap>0.95 THEN 'concerned'::public.festival_crowd_state WHEN audience>0 THEN 'engaged'::public.festival_crowd_state ELSE 'curious'::public.festival_crowd_state END,55,jsonb_build_object('reconciles_to_generation_id',gen.id)) RETURNING * INTO snap;
   RETURN NEXT snap;
 END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.calculate_festival_performance_outcome(p_session_id uuid, p_idempotency_key text)
RETURNS public.festival_performance_outcomes LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE s public.festival_performance_sessions%ROWTYPE; cfg public.festival_audience_simulation_configs%ROWTYPE; existing public.festival_performance_outcomes%ROWTYPE; aud public.festival_performance_audience_snapshots%ROWTYPE; crowd public.festival_stage_crowd_snapshots%ROWTYPE; h text; seed text; total int; completed int; skipped int; incidents int; readiness numeric; crowdfit numeric; base numeric; overall numeric; outcome public.festival_performance_outcomes%ROWTYPE; item jsonb; pos int; songstatus text; songscore numeric; retained int; gained int; lost int; soid uuid;
BEGIN
 IF nullif(btrim(p_idempotency_key),'') IS NULL THEN RAISE EXCEPTION 'idempotency key required'; END IF;
 SELECT * INTO s FROM public.festival_performance_sessions WHERE id=p_session_id FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'Session not found'; END IF;
 IF s.status NOT IN ('completed','partially_completed','abandoned','cancelled','no_show') THEN RAISE EXCEPTION 'Session is not in an outcome-eligible terminal state'; END IF;
 SELECT * INTO cfg FROM public.festival_audience_simulation_configs WHERE is_active ORDER BY activated_at DESC NULLS LAST LIMIT 1;
 h:=public.festival_outcome_hash(jsonb_build_object('session',to_jsonb(s),'incidents',(SELECT COALESCE(jsonb_agg(to_jsonb(i) ORDER BY opened_at),'[]') FROM public.festival_performance_incidents i WHERE i.session_id=s.id),'audience',(SELECT to_jsonb(a) FROM public.festival_performance_audience_snapshots a WHERE a.session_id=s.id)));
 SELECT * INTO existing FROM public.festival_performance_outcomes WHERE session_id=s.id AND idempotency_key=p_idempotency_key; IF FOUND THEN IF existing.input_hash<>h THEN RAISE EXCEPTION 'Idempotency key reused with changed outcome inputs'; END IF; RETURN existing; END IF;
 SELECT * INTO existing FROM public.festival_performance_outcomes WHERE session_id=s.id AND model_version='festival_performance_outcome_v1' AND status IN ('calculated','finalised'); IF FOUND THEN RETURN existing; END IF;
 SELECT * INTO aud FROM public.festival_performance_audience_snapshots WHERE session_id=s.id;
 IF NOT FOUND THEN SELECT * INTO crowd FROM public.festival_stage_crowd_snapshots WHERE session_id=s.id ORDER BY snapshot_at DESC LIMIT 1; INSERT INTO public.festival_performance_audience_snapshots(session_id,edition_id,stage_id,source_crowd_snapshot_id,config_version,audience_at_start,audience_cohorts,capacity_percentage,expected_audience,crowd_fit,initial_excitement,initial_patience,fan_ratio,media_presence,industry_presence,sponsor_presence,input_hash) VALUES(s.id,s.edition_id,s.stage_id,crowd.id,cfg.version,COALESCE(crowd.audience_total,0),COALESCE(crowd.cohort_distribution,'{}'),COALESCE(crowd.density,0)*100,COALESCE(crowd.audience_total,0),60,COALESCE(crowd.excitement,50),60,0.5,CEIL(COALESCE(crowd.audience_total,0)*0.01),CEIL(COALESCE(crowd.audience_total,0)*0.005),CEIL(COALESCE(crowd.audience_total,0)*0.005),h) RETURNING * INTO aud; END IF;
 total:=COALESCE(jsonb_array_length(s.setlist_snapshot->'items'),0); completed:=s.current_setlist_position; skipped:=COALESCE((SELECT count(*) FROM jsonb_array_elements(COALESCE(s.performance_evidence->'progression','[]'::jsonb)) e WHERE e->>'action' IN ('skip_song','curtail_remaining_set')),0); incidents:=COALESCE((SELECT count(*) FROM public.festival_performance_incidents WHERE session_id=s.id AND severity IN ('critical','blocking','warning')),0);
 readiness:=CASE COALESCE(s.readiness_snapshot#>>'{overall,status}','ready') WHEN 'excellent' THEN 95 WHEN 'ready' THEN 82 WHEN 'strained' THEN 65 WHEN 'compromised' THEN 48 WHEN 'blocked' THEN 25 ELSE 72 END; crowdfit:=COALESCE(aud.crowd_fit,55); seed:=public.festival_outcome_hash(jsonb_build_object('session_id',s.id,'version',s.session_version,'input_hash',h));
 base:=public.festival_score_clamp(readiness*0.28 + crowdfit*0.18 + (CASE WHEN total=0 THEN 45 ELSE completed::numeric/GREATEST(1,total)*100 END)*0.22 + 70*0.2 + COALESCE(aud.initial_excitement,50)*0.12 + public.festival_seeded_variation(seed,'overall',3)); overall:=public.festival_score_clamp(base - incidents*6 - skipped*5 - CASE WHEN s.status IN ('cancelled','no_show') THEN 55 WHEN s.status='abandoned' THEN 25 ELSE 0 END);
 INSERT INTO public.festival_performance_outcomes(session_id,edition_id,festival_id,band_id,status,model_version,config_version,audience_model_version,source_session_version,calculation_seed,idempotency_key,input_hash,overall_score,technical_score,musicianship_score,setlist_score,stagecraft_score,crowd_connection_score,professionalism_score,readiness_score,reliability_score,audience_growth_score,media_score,festival_fit_score,highlight_score,incident_penalty,lateness_penalty,curtailment_penalty,completion_modifier,metadata)
 VALUES(s.id,s.edition_id,s.festival_id,s.band_id,'calculated','festival_performance_outcome_v1',cfg.version,cfg.version,s.session_version,seed,p_idempotency_key,h,overall,public.festival_score_clamp(readiness-incidents*4),public.festival_score_clamp(70+public.festival_seeded_variation(seed,'musicianship',3)),CASE WHEN total=0 THEN 40 ELSE public.festival_score_clamp(completed::numeric/GREATEST(1,total)*100-skipped*5) END,public.festival_score_clamp(65+COALESCE(aud.initial_excitement,50)*0.2),public.festival_score_clamp(crowdfit+COALESCE(aud.initial_excitement,50)*0.25-incidents*5),CASE WHEN s.status='no_show' THEN 0 ELSE public.festival_score_clamp(80-incidents*8) END,readiness,CASE WHEN s.status IN ('cancelled','no_show') THEN 10 ELSE 80 END,public.festival_score_clamp(overall-45),public.festival_score_clamp(overall+COALESCE(aud.media_presence,0)*0.2),public.festival_score_clamp(crowdfit),public.festival_score_clamp(GREATEST(0,overall-75)),incidents*6,0,skipped*5,CASE WHEN total=0 THEN 0.5 ELSE completed::numeric/GREATEST(1,total) END,jsonb_build_object('settlement_deferred',true,'no_money_or_fame_applied',true)) RETURNING * INTO outcome;
 pos:=0; FOR item IN SELECT * FROM jsonb_array_elements(COALESCE(s.setlist_snapshot->'items','[]'::jsonb)) LOOP pos:=pos+1; songstatus:=CASE WHEN s.status IN ('cancelled','no_show') THEN 'not_performed' WHEN pos<=completed AND skipped=0 THEN 'performed' WHEN pos<=completed THEN 'performed_or_skipped' ELSE 'skipped' END; songscore:=public.festival_score_clamp(overall + public.festival_seeded_variation(seed,'song:'||pos,4) - CASE WHEN songstatus LIKE 'skipped%' OR songstatus='not_performed' THEN 25 ELSE 0 END); retained:=GREATEST(0,ROUND(COALESCE(aud.audience_at_start,0)*(songscore/100.0))::int); gained:=GREATEST(0,ROUND(COALESCE(aud.audience_at_start,0)*GREATEST(0,songscore-70)/1000.0)::int); lost:=GREATEST(0,ROUND(COALESCE(aud.audience_at_start,0)*GREATEST(0,55-songscore)/1000.0)::int);
 INSERT INTO public.festival_song_performance_outcomes(outcome_id,session_id,setlist_position,song_id,status,actual_duration_seconds,performance_quality,technical_execution,familiarity_contribution,musicianship_contribution,crowd_fit,crowd_response,singalong_response,dancing_response,energy_change,audience_retained,audience_gained,audience_lost,media_reaction,incident_effects,highlight_status,evidence_snapshot,model_version) VALUES(outcome.id,s.id,pos,NULLIF(item->>'song_id','')::uuid,songstatus,(item->>'planned_duration_seconds')::int,songscore,public.festival_score_clamp(readiness-incidents*3),50,70,crowdfit,songscore,public.festival_score_clamp(songscore-5),public.festival_score_clamp(songscore-8),songscore-50,retained,gained,lost,songscore-50,COALESCE(s.incident_snapshot,'[]'),CASE WHEN songscore>=90 THEN 'major_positive' WHEN songscore<40 THEN 'negative' ELSE 'none' END,jsonb_build_object('setlist_item',item,'progression',s.performance_evidence->'progression'),'festival_performance_outcome_v1') RETURNING id INTO soid;
 IF songscore>=90 OR songscore<40 THEN INSERT INTO public.festival_performance_highlights(outcome_id,session_id,song_outcome_id,setlist_position,occurred_at,highlight_type,is_positive,intensity,public_description,internal_evidence,viewer_presentation_metadata) VALUES(outcome.id,s.id,soid,pos,s.actual_start_at + make_interval(mins => pos*4),CASE WHEN songscore>=90 THEN 'huge_singalong' ELSE 'technical_failure' END,songscore>=90,ABS(songscore-50),CASE WHEN songscore>=90 THEN 'The crowd locked into a standout festival moment.' ELSE 'A visible performance issue affected the crowd response.' END,jsonb_build_object('song_score',songscore),jsonb_build_object('crowd_state',CASE WHEN songscore>=90 THEN 'ecstatic' ELSE 'concerned' END)); END IF;
 END LOOP;
 INSERT INTO public.festival_fan_conversion_outcomes(outcome_id,session_id,band_id,new_casual_fans,new_engaged_fans,new_dedicated_fans,lost_fans,local_fan_gains,travelling_fan_gains,genre_community_gains,cohort_breakdown,conversion_explanation,model_version) VALUES(outcome.id,s.id,s.band_id,GREATEST(0,ROUND(COALESCE(aud.audience_at_start,0)*GREATEST(0,overall-55)/1000.0)::int),GREATEST(0,ROUND(COALESCE(aud.audience_at_start,0)*GREATEST(0,overall-70)/1500.0)::int),GREATEST(0,ROUND(COALESCE(aud.audience_at_start,0)*GREATEST(0,overall-88)/2500.0)::int),GREATEST(0,ROUND(COALESCE(aud.audience_at_start,0)*GREATEST(0,45-overall)/1000.0)::int),0,0,0,aud.audience_cohorts,'Pending fan conversion proposal derived from audience fit, score and retention.','festival_performance_outcome_v1');
 INSERT INTO public.festival_performance_effects(outcome_id,entity_type,entity_id,effect_type,proposed_value,effect_payload,explanation,model_version) VALUES(outcome.id,'band',s.band_id,'band_fame',ROUND((overall-50)/10,2),'{"pending_settlement":true}','Proposed fame effect only; not applied in this PR.','festival_performance_outcome_v1'),(outcome.id,'band',s.band_id,'streaming_uplift',GREATEST(0,ROUND((overall-60)/5,2)),jsonb_build_object('duration_days',14,'decay_curve','linear'),'Proposed streaming uplift only; not applied in this PR.','festival_performance_outcome_v1'),(outcome.id,'festival',s.festival_id,'festival_reputation',ROUND((overall-55)/12,2),'{"pending_settlement":true}','Proposed festival reputation effect only; not applied in this PR.','festival_performance_outcome_v1');
 INSERT INTO public.festival_media_outcomes(outcome_id,media_type,tone,sentiment_score,public_summary,structured_facts) VALUES(outcome.id,CASE WHEN overall>=85 THEN 'breakthrough_performance' WHEN overall<40 THEN 'technical_disaster' ELSE 'review' END,CASE WHEN overall>=70 THEN 'positive' WHEN overall>=45 THEN 'mixed' ELSE 'negative' END,overall,'Festival performance outcome recorded from canonical session evidence.',jsonb_build_object('audience',aud.audience_at_start,'score',overall));
 INSERT INTO public.festival_sponsor_outcomes(outcome_id,sentiment_score,visibility_score,professionalism_score,renewal_interest,explanation) VALUES(outcome.id,public.festival_score_clamp(overall-incidents*5),public.festival_score_clamp(COALESCE(aud.capacity_percentage,0)),CASE WHEN s.status='no_show' THEN 0 ELSE public.festival_score_clamp(80-incidents*8) END,public.festival_score_clamp(overall-10),'Pending sponsor sentiment only; no sponsor payment applied.');
 INSERT INTO public.festival_outcome_publications(outcome_id,publication_type,public_payload,dedupe_key) VALUES(outcome.id,'world_pulse',jsonb_build_object('type',CASE WHEN overall>=85 THEN 'breakthrough_act' ELSE 'performance_completed' END,'session_id',s.id,'band_id',s.band_id,'audience',aud.audience_at_start,'score',overall),'world_pulse:'||outcome.id::text), (outcome.id,'twaater',jsonb_build_object('type','festival_performance_completed','session_id',s.id,'band_id',s.band_id,'tone',CASE WHEN overall>=70 THEN 'positive' ELSE 'mixed' END),'twaater:'||outcome.id::text);
 UPDATE public.festival_performance_sessions SET outcome_status='outcome_calculated', updated_at=now(), session_version=session_version+1 WHERE id=s.id;
 RETURN outcome;
END $$;

CREATE OR REPLACE FUNCTION public.festival_performance_narrative(p_session_id uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT jsonb_build_object('opening_summary','The performance narrative is derived from stored audience, song and highlight outcomes.','key_moments',COALESCE((SELECT jsonb_agg(jsonb_build_object('type',highlight_type,'description',public_description,'positive',is_positive,'intensity',intensity) ORDER BY created_at) FROM public.festival_performance_highlights WHERE session_id=p_session_id),'[]'::jsonb),'crowd_development',(SELECT jsonb_build_object('audience_at_start',audience_at_start,'initial_excitement',initial_excitement,'crowd_fit',crowd_fit) FROM public.festival_performance_audience_snapshots WHERE session_id=p_session_id),'incident_summary',(SELECT COALESCE(jsonb_agg(jsonb_build_object('category',category,'severity',severity,'resolved',resolved_at IS NOT NULL)),'[]'::jsonb) FROM public.festival_performance_incidents WHERE session_id=p_session_id),'standout_songs',(SELECT COALESCE(jsonb_agg(setlist_position ORDER BY performance_quality DESC),'[]'::jsonb) FROM (SELECT setlist_position,performance_quality FROM public.festival_song_performance_outcomes WHERE session_id=p_session_id ORDER BY performance_quality DESC LIMIT 3) x),'weakest_moment',(SELECT setlist_position FROM public.festival_song_performance_outcomes WHERE session_id=p_session_id ORDER BY performance_quality ASC LIMIT 1),'ending','Financial settlement and career effect application remain pending.','overall_assessment',(SELECT overall_score FROM public.festival_performance_outcomes WHERE session_id=p_session_id AND status IN ('calculated','finalised') ORDER BY calculated_at DESC LIMIT 1));
$$;

CREATE OR REPLACE FUNCTION public.public_festival_performance_outcomes(p_session_id uuid DEFAULT NULL, p_edition_id uuid DEFAULT NULL)
RETURNS TABLE(session_id uuid, edition_id uuid, band_id uuid, audience_size integer, capacity_percentage numeric, crowd_state text, current_song_position integer, safe_highlights jsonb, public_incident_state text, public_status text, performance_score numeric, completion_summary jsonb)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT s.id,s.edition_id,s.band_id,COALESCE(a.audience_at_start,0),COALESCE(a.capacity_percentage,0),COALESCE((SELECT sc.crowd_state::text FROM public.festival_stage_crowd_snapshots sc WHERE sc.session_id=s.id ORDER BY sc.snapshot_at DESC LIMIT 1),'attentive'),s.active_song_position,COALESCE((SELECT jsonb_agg(jsonb_build_object('type',h.highlight_type,'positive',h.is_positive,'description',h.public_description,'intensity',h.intensity) ORDER BY h.created_at) FROM public.festival_performance_highlights h WHERE h.session_id=s.id),'[]'::jsonb),CASE WHEN EXISTS(SELECT 1 FROM public.festival_performance_incidents i WHERE i.session_id=s.id AND i.severity IN ('critical','blocking') AND i.resolved_at IS NULL) THEN 'major_issue' ELSE 'normal' END,s.status::text,CASE WHEN s.status IN ('completed','partially_completed','abandoned','cancelled','no_show') THEN o.overall_score ELSE NULL END,jsonb_build_object('actual_start_at',s.actual_start_at,'actual_end_at',s.actual_end_at,'completed_song_count',s.current_setlist_position,'total_planned_song_count',COALESCE(jsonb_array_length(s.setlist_snapshot->'items'),0),'settlement_pending',true)
 FROM public.festival_performance_sessions s LEFT JOIN public.festival_performance_audience_snapshots a ON a.session_id=s.id LEFT JOIN public.festival_performance_outcomes o ON o.session_id=s.id AND o.status IN ('calculated','finalised') WHERE (p_session_id IS NULL OR s.id=p_session_id) AND (p_edition_id IS NULL OR s.edition_id=p_edition_id);
$$;

CREATE OR REPLACE FUNCTION public.invalidate_festival_performance_outcome(p_outcome_id uuid, p_reason text, p_replacement_model_version text DEFAULT NULL)
RETURNS public.festival_performance_outcomes LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE o public.festival_performance_outcomes%ROWTYPE; BEGIN IF NOT COALESCE(public.has_role(auth.uid(),'admin'::public.app_role),false) THEN RAISE EXCEPTION 'Only admins may invalidate festival outcomes'; END IF; IF nullif(btrim(p_reason),'') IS NULL THEN RAISE EXCEPTION 'Invalidation reason required'; END IF; UPDATE public.festival_performance_outcomes SET status='invalidated', invalidated_at=now(), invalidated_by=public.current_profile_id_safe(), invalidation_reason=p_reason, metadata=metadata||jsonb_build_object('replacement_model_version',p_replacement_model_version) WHERE id=p_outcome_id AND status<>'finalised' RETURNING * INTO o; IF NOT FOUND THEN RAISE EXCEPTION 'Outcome not found or finalised immutable'; END IF; RETURN o; END $$;

CREATE OR REPLACE FUNCTION public.prevent_final_festival_outcome_update() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status IN ('finalised','invalidated') THEN RAISE EXCEPTION 'Finalised or invalidated festival outcomes are immutable'; END IF; RETURN NEW; END $$;
DROP TRIGGER IF EXISTS tg_festival_outcome_immutable ON public.festival_performance_outcomes;
CREATE TRIGGER tg_festival_outcome_immutable BEFORE UPDATE ON public.festival_performance_outcomes FOR EACH ROW WHEN (OLD.status IN ('finalised','invalidated')) EXECUTE FUNCTION public.prevent_final_festival_outcome_update();

ALTER TABLE public.festival_audience_simulation_configs ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_audience_generations ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_audience_cohorts ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_stage_crowd_snapshots ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_performance_audience_snapshots ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_performance_outcomes ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_song_performance_outcomes ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_fan_conversion_outcomes ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_performance_effects ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_media_outcomes ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_sponsor_outcomes ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_performance_highlights ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_outcome_publications ENABLE ROW LEVEL SECURITY;

CREATE POLICY festival_outcome_config_read ON public.festival_audience_simulation_configs FOR SELECT TO authenticated USING (true);
CREATE POLICY festival_audience_read ON public.festival_audience_generations FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.festival_editions e WHERE e.id=edition_id AND (public.can_manage_festival_brand(e.festival_id) OR public.is_public_festival_edition_status(e.status))));
CREATE POLICY festival_cohort_read ON public.festival_audience_cohorts FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.festival_editions e WHERE e.id=edition_id AND (public.can_manage_festival_brand(e.festival_id) OR public.is_public_festival_edition_status(e.status))));
CREATE POLICY festival_crowd_read ON public.festival_stage_crowd_snapshots FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.festival_editions e WHERE e.id=edition_id AND (public.can_manage_festival_brand(e.festival_id) OR public.is_public_festival_edition_status(e.status))));
CREATE POLICY festival_performance_audience_read ON public.festival_performance_audience_snapshots FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.festival_performance_sessions s WHERE s.id=session_id AND (public.is_active_band_member(s.band_id) OR public.can_manage_festival_brand(s.festival_id))));
CREATE POLICY festival_outcome_read ON public.festival_performance_outcomes FOR SELECT TO authenticated USING (public.is_active_band_member(band_id) OR public.can_manage_festival_brand(festival_id));
CREATE POLICY festival_song_outcome_read ON public.festival_song_performance_outcomes FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.festival_performance_sessions s WHERE s.id=session_id AND (public.is_active_band_member(s.band_id) OR public.can_manage_festival_brand(s.festival_id))));
CREATE POLICY festival_effect_read ON public.festival_performance_effects FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.festival_performance_outcomes o WHERE o.id=outcome_id AND (public.is_active_band_member(o.band_id) OR public.can_manage_festival_brand(o.festival_id))));
CREATE POLICY festival_fan_media_sponsor_highlight_read ON public.festival_fan_conversion_outcomes FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.festival_performance_outcomes o WHERE o.id=outcome_id AND (public.is_active_band_member(o.band_id) OR public.can_manage_festival_brand(o.festival_id))));
CREATE POLICY festival_media_read ON public.festival_media_outcomes FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.festival_performance_outcomes o WHERE o.id=outcome_id AND (public.is_active_band_member(o.band_id) OR public.can_manage_festival_brand(o.festival_id))));
CREATE POLICY festival_sponsor_read ON public.festival_sponsor_outcomes FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.festival_performance_outcomes o WHERE o.id=outcome_id AND (public.is_active_band_member(o.band_id) OR public.can_manage_festival_brand(o.festival_id))));
CREATE POLICY festival_highlight_read ON public.festival_performance_highlights FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.festival_performance_sessions s WHERE s.id=session_id AND (public.is_active_band_member(s.band_id) OR public.can_manage_festival_brand(s.festival_id) OR EXISTS (SELECT 1 FROM public.festival_editions e WHERE e.id=s.edition_id AND public.is_public_festival_edition_status(e.status)))));
CREATE POLICY festival_publication_read ON public.festival_outcome_publications FOR SELECT TO authenticated USING (true);

GRANT SELECT ON public.festival_audience_simulation_configs, public.festival_audience_generations, public.festival_audience_cohorts, public.festival_stage_crowd_snapshots, public.festival_performance_audience_snapshots, public.festival_performance_outcomes, public.festival_song_performance_outcomes, public.festival_fan_conversion_outcomes, public.festival_performance_effects, public.festival_media_outcomes, public.festival_sponsor_outcomes, public.festival_performance_highlights, public.festival_outcome_publications TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_festival_edition_audience(uuid,text), public.simulate_festival_crowd_movement(uuid,timestamptz,text), public.calculate_festival_performance_outcome(uuid,text), public.festival_performance_narrative(uuid), public.public_festival_performance_outcomes(uuid,uuid), public.invalidate_festival_performance_outcome(uuid,text,text) TO authenticated;
