-- Phase 5 follows the retained 2029 Festival sequence exactly; it is forward-only and safe on fresh installs.
CREATE TABLE public.festival_operations_plans (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_company_id uuid UNIQUE NOT NULL REFERENCES public.festival_companies(id) ON DELETE CASCADE, artist_programme_id uuid NOT NULL REFERENCES public.festival_artist_programmes(id) ON DELETE CASCADE,
 currency_code text NOT NULL CHECK(currency_code ~ '^[A-Z]{3}$'), staff_budget_minor bigint NOT NULL CHECK(staff_budget_minor>=0), supplier_budget_minor bigint NOT NULL CHECK(supplier_budget_minor>=0), contingency_budget_minor bigint NOT NULL CHECK(contingency_budget_minor>=0),
 staffing_mode text NOT NULL CHECK(staffing_mode IN ('npc_only','player_preferred','mixed')), procurement_mode text NOT NULL CHECK(procurement_mode IN ('npc_only','player_company_preferred','mixed')), status text NOT NULL DEFAULT 'not_started' CHECK(status IN ('not_started','requirements_generated','recruitment_open','procurement_open','contracts_in_progress','coverage_in_progress','ready_for_sponsorship')), planning_version integer NOT NULL DEFAULT 1 CHECK(planning_version>0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz
);
CREATE TABLE public.festival_operational_departments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),festival_operations_plan_id uuid NOT NULL REFERENCES public.festival_operations_plans(id) ON DELETE CASCADE,department_type text NOT NULL,name text NOT NULL,priority text NOT NULL CHECK(priority IN ('essential','high','standard')),minimum_quality integer NOT NULL CHECK(minimum_quality BETWEEN 0 AND 100),target_quality integer NOT NULL CHECK(target_quality BETWEEN minimum_quality AND 100),manager_profile_id uuid REFERENCES public.profiles(id),status text NOT NULL DEFAULT 'planned' CHECK(status IN ('planned','recruiting','covered','ready')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(festival_operations_plan_id,department_type));
CREATE TABLE public.festival_staffing_requirements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),festival_operations_plan_id uuid NOT NULL REFERENCES public.festival_operations_plans(id) ON DELETE CASCADE,department_id uuid NOT NULL REFERENCES public.festival_operational_departments(id) ON DELETE CASCADE,role_type text NOT NULL,required_count integer NOT NULL CHECK(required_count>0),minimum_skill_level integer NOT NULL CHECK(minimum_skill_level BETWEEN 0 AND 100),minimum_experience integer CHECK(minimum_experience>=0),shift_length_minutes integer NOT NULL CHECK(shift_length_minutes BETWEEN 60 AND 960),coverage_start timestamptz NOT NULL,coverage_end timestamptz NOT NULL,safety_critical boolean NOT NULL,player_eligible boolean NOT NULL,npc_eligible boolean NOT NULL,estimated_cost_minor bigint NOT NULL CHECK(estimated_cost_minor>=0),status text NOT NULL DEFAULT 'open',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(coverage_start<coverage_end),UNIQUE(festival_operations_plan_id,role_type));
CREATE TABLE public.festival_staff_vacancies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),festival_operations_plan_id uuid NOT NULL REFERENCES public.festival_operations_plans(id) ON DELETE CASCADE,staffing_requirement_id uuid NOT NULL REFERENCES public.festival_staffing_requirements(id) ON DELETE CASCADE,title text NOT NULL,description text,employment_type text NOT NULL CHECK(employment_type IN ('temporary_contract','single_shift','multi_day_contract','volunteer','company_assignment')),positions_available integer NOT NULL CHECK(positions_available>0),positions_filled integer NOT NULL DEFAULT 0 CHECK(positions_filled>=0 AND positions_filled<=positions_available),pay_type text NOT NULL CHECK(pay_type IN ('hourly','per_shift','fixed_contract','unpaid_volunteer')),pay_minor bigint NOT NULL CHECK(pay_minor>=0),currency_code text NOT NULL,starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,application_deadline timestamptz,minimum_skill_level integer,minimum_experience integer,player_only boolean NOT NULL DEFAULT false,npc_fallback_allowed boolean NOT NULL DEFAULT true,status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published','closed','filled','cancelled')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(starts_at<ends_at));
CREATE TABLE public.festival_staff_applications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),vacancy_id uuid NOT NULL REFERENCES public.festival_staff_vacancies(id) ON DELETE CASCADE,applicant_profile_id uuid NOT NULL REFERENCES public.profiles(id),status text NOT NULL DEFAULT 'submitted' CHECK(status IN ('submitted','under_review','shortlisted','accepted','rejected','withdrawn','expired')),skill_snapshot jsonb NOT NULL,experience_snapshot integer,availability_snapshot jsonb,message text,expected_pay_minor bigint CHECK(expected_pay_minor>=0),submitted_at timestamptz NOT NULL DEFAULT now(),reviewed_at timestamptz,withdrawn_at timestamptz,application_version integer NOT NULL DEFAULT 1 CHECK(application_version>0),UNIQUE(vacancy_id,applicant_profile_id));
CREATE TABLE public.festival_staff_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),festival_operations_plan_id uuid NOT NULL REFERENCES public.festival_operations_plans(id) ON DELETE CASCADE,staffing_requirement_id uuid NOT NULL REFERENCES public.festival_staffing_requirements(id),vacancy_id uuid REFERENCES public.festival_staff_vacancies(id),application_id uuid UNIQUE REFERENCES public.festival_staff_applications(id),assignment_source text NOT NULL CHECK(assignment_source IN ('player_application','direct_player_offer','npc_hire','company_contract','existing_employee')),profile_id uuid REFERENCES public.profiles(id),npc_staff_id uuid,company_id uuid REFERENCES public.companies(id),role_type text NOT NULL,agreed_pay_minor bigint NOT NULL CHECK(agreed_pay_minor>=0),currency_code text NOT NULL,quality_score integer NOT NULL CHECK(quality_score BETWEEN 0 AND 100),status text NOT NULL DEFAULT 'committed' CHECK(status IN ('planned','committed','active','cancelled')),starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,assignment_version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),cancelled_at timestamptz,CHECK(num_nonnulls(profile_id,npc_staff_id,company_id)=1),CHECK(starts_at<ends_at));
CREATE TABLE public.festival_staff_shifts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),festival_operations_plan_id uuid NOT NULL REFERENCES public.festival_operations_plans(id) ON DELETE CASCADE,staff_assignment_id uuid NOT NULL REFERENCES public.festival_staff_assignments(id) ON DELETE CASCADE,department_id uuid NOT NULL REFERENCES public.festival_operational_departments(id),festival_date date NOT NULL,starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,break_minutes integer NOT NULL DEFAULT 0 CHECK(break_minutes BETWEEN 0 AND 240),location_type text,stage_id uuid REFERENCES public.festival_stages(id),coverage_type text NOT NULL,status text NOT NULL DEFAULT 'planned',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(starts_at<ends_at));
CREATE TABLE public.festival_supplier_requirements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),festival_operations_plan_id uuid NOT NULL REFERENCES public.festival_operations_plans(id) ON DELETE CASCADE,requirement_type text NOT NULL,category text NOT NULL,description text,quantity integer NOT NULL CHECK(quantity>0),unit_type text NOT NULL,minimum_quality integer NOT NULL CHECK(minimum_quality BETWEEN 0 AND 100),delivery_start timestamptz,delivery_end timestamptz,service_start timestamptz,service_end timestamptz,estimated_cost_minor bigint NOT NULL CHECK(estimated_cost_minor>=0),safety_critical boolean NOT NULL,player_company_eligible boolean NOT NULL,npc_supplier_eligible boolean NOT NULL,status text NOT NULL DEFAULT 'open',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(festival_operations_plan_id,requirement_type));
CREATE TABLE public.festival_supplier_quotes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),supplier_requirement_id uuid NOT NULL REFERENCES public.festival_supplier_requirements(id) ON DELETE CASCADE,supplier_source text NOT NULL CHECK(supplier_source IN ('player_company','npc_supplier','admin_supplier')),supplier_company_id uuid REFERENCES public.companies(id),npc_supplier_id uuid,submitted_by_profile_id uuid REFERENCES public.profiles(id),status text NOT NULL DEFAULT 'submitted' CHECK(status IN ('draft','submitted','under_review','accepted','declined','withdrawn','expired','superseded')),currency_code text NOT NULL,base_cost_minor bigint NOT NULL CHECK(base_cost_minor>=0),delivery_cost_minor bigint NOT NULL CHECK(delivery_cost_minor>=0),setup_cost_minor bigint NOT NULL CHECK(setup_cost_minor>=0),staffing_cost_minor bigint NOT NULL CHECK(staffing_cost_minor>=0),deposit_minor bigint NOT NULL CHECK(deposit_minor>=0),total_cost_minor bigint NOT NULL CHECK(total_cost_minor>=0),quality_score integer NOT NULL CHECK(quality_score BETWEEN 0 AND 100),reliability_score integer NOT NULL CHECK(reliability_score BETWEEN 0 AND 100),capacity_offered integer CHECK(capacity_offered>0),delivery_terms jsonb,service_terms jsonb,expires_at timestamptz,quote_version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(num_nonnulls(supplier_company_id,npc_supplier_id)=1),CHECK(total_cost_minor=base_cost_minor+delivery_cost_minor+setup_cost_minor+staffing_cost_minor),CHECK(deposit_minor<=total_cost_minor));
CREATE TABLE public.festival_supplier_contracts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),festival_operations_plan_id uuid NOT NULL REFERENCES public.festival_operations_plans(id) ON DELETE CASCADE,supplier_requirement_id uuid NOT NULL REFERENCES public.festival_supplier_requirements(id),accepted_quote_id uuid UNIQUE NOT NULL REFERENCES public.festival_supplier_quotes(id),supplier_source text NOT NULL,supplier_company_id uuid REFERENCES public.companies(id),npc_supplier_id uuid,status text NOT NULL DEFAULT 'committed' CHECK(status IN ('committed','awaiting_delivery','active','completed','cancelled','supplier_defaulted','festival_cancelled')),currency_code text NOT NULL,total_commitment_minor bigint NOT NULL CHECK(total_commitment_minor>=0),deposit_commitment_minor bigint NOT NULL CHECK(deposit_commitment_minor>=0),quality_score integer NOT NULL,reliability_score integer NOT NULL,delivery_start timestamptz,delivery_end timestamptz,service_start timestamptz,service_end timestamptz,terms_snapshot jsonb NOT NULL,contract_version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),cancelled_at timestamptz,CHECK(num_nonnulls(supplier_company_id,npc_supplier_id)=1));
CREATE TABLE public.festival_supplier_allocations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),supplier_contract_id uuid NOT NULL REFERENCES public.festival_supplier_contracts(id) ON DELETE CASCADE,supplier_requirement_id uuid NOT NULL REFERENCES public.festival_supplier_requirements(id),quantity integer NOT NULL CHECK(quantity>0),allocation_type text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.festival_operations_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),festival_company_id uuid NOT NULL REFERENCES public.festival_companies(id) ON DELETE CASCADE,actor_profile_id uuid NOT NULL REFERENCES public.profiles(id),action text NOT NULL,target_id uuid,idempotency_key uuid NOT NULL,payload_hash text NOT NULL,status text NOT NULL DEFAULT 'processing',result jsonb,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(actor_profile_id,action,target_id,idempotency_key));
CREATE TABLE public.festival_operations_audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),festival_company_id uuid NOT NULL REFERENCES public.festival_companies(id) ON DELETE CASCADE,actor_profile_id uuid REFERENCES public.profiles(id),entity_type text NOT NULL,entity_id uuid NOT NULL,event_type text NOT NULL,previous_state text,new_state text,version integer NOT NULL,metadata jsonb NOT NULL DEFAULT '{}',request_id uuid UNIQUE REFERENCES public.festival_operations_requests(id),created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.festival_financial_commitments ALTER COLUMN artist_booking_id DROP NOT NULL;
ALTER TABLE public.festival_financial_commitments ADD COLUMN staff_assignment_id uuid UNIQUE REFERENCES public.festival_staff_assignments(id) ON DELETE CASCADE, ADD COLUMN supplier_contract_id uuid UNIQUE REFERENCES public.festival_supplier_contracts(id) ON DELETE CASCADE;
ALTER TABLE public.festival_financial_commitments ADD CONSTRAINT festival_commitment_one_source CHECK(num_nonnulls(artist_booking_id,staff_assignment_id,supplier_contract_id)=1);

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['festival_operations_plans','festival_operational_departments','festival_staffing_requirements','festival_staff_vacancies','festival_staff_applications','festival_staff_assignments','festival_staff_shifts','festival_supplier_requirements','festival_supplier_quotes','festival_supplier_contracts','festival_supplier_allocations','festival_operations_requests','festival_operations_audit'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t); END LOOP; END $$;

CREATE FUNCTION public._festival_operations_result(p_company uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
SELECT jsonb_build_object('festivalCompanyId',p_company,'operationsPlan',CASE WHEN op.id IS NULL THEN NULL ELSE jsonb_build_object('id',op.id,'currencyCode',op.currency_code,'staffBudgetMinor',op.staff_budget_minor,'supplierBudgetMinor',op.supplier_budget_minor,'contingencyBudgetMinor',op.contingency_budget_minor,'staffingMode',op.staffing_mode,'procurementMode',op.procurement_mode,'status',op.status,'planningVersion',op.planning_version) END,'departments',coalesce((SELECT jsonb_agg(to_jsonb(d)) FROM public.festival_operational_departments d WHERE d.festival_operations_plan_id=op.id),'[]'),'staffingRequirements',coalesce((SELECT jsonb_agg(to_jsonb(r)) FROM public.festival_staffing_requirements r WHERE r.festival_operations_plan_id=op.id),'[]'),'vacancies',coalesce((SELECT jsonb_agg(to_jsonb(v)) FROM public.festival_staff_vacancies v WHERE v.festival_operations_plan_id=op.id),'[]'),'applications','[]'::jsonb,'assignments',coalesce((SELECT jsonb_agg(to_jsonb(a)) FROM public.festival_staff_assignments a WHERE a.festival_operations_plan_id=op.id),'[]'),'shifts',coalesce((SELECT jsonb_agg(to_jsonb(s)) FROM public.festival_staff_shifts s WHERE s.festival_operations_plan_id=op.id),'[]'),'supplierRequirements',coalesce((SELECT jsonb_agg(to_jsonb(r)) FROM public.festival_supplier_requirements r WHERE r.festival_operations_plan_id=op.id),'[]'),'quotes','[]'::jsonb,'contracts',coalesce((SELECT jsonb_agg(to_jsonb(c)) FROM public.festival_supplier_contracts c WHERE c.festival_operations_plan_id=op.id),'[]'),'budgetSummary',jsonb_build_object('staffBudgetMinor',coalesce(op.staff_budget_minor,0),'supplierBudgetMinor',coalesce(op.supplier_budget_minor,0),'contingencyMinor',coalesce(op.contingency_budget_minor,0),'staffCommitmentsMinor',coalesce((SELECT sum(amount_minor) FROM public.festival_financial_commitments WHERE festival_company_id=p_company AND staff_assignment_id IS NOT NULL AND status='committed'),0),'supplierCommitmentsMinor',coalesce((SELECT sum(amount_minor) FROM public.festival_financial_commitments WHERE festival_company_id=p_company AND supplier_contract_id IS NOT NULL AND status='committed'),0),'artistCommitmentsMinor',coalesce((SELECT sum(amount_minor) FROM public.festival_financial_commitments WHERE festival_company_id=p_company AND artist_booking_id IS NOT NULL AND status='committed'),0)),'qualityScores',jsonb_build_object('staffingCoverageBasisPoints',0,'supplierCoverageBasisPoints',0,'safetyReadinessScore',0,'productionReadinessScore',0,'guestExperienceScore',0,'artistExperienceScore',0,'overallOperationsScore',0),'issues','[]'::jsonb,'readiness',coalesce(op.status='ready_for_sponsorship',false),'canWrite',true,'planningVersion',coalesce(op.planning_version,0),'updatedAt',op.updated_at) FROM (SELECT 1) x LEFT JOIN public.festival_operations_plans op ON op.festival_company_id=p_company $$;
CREATE FUNCTION public.get_festival_operations_plan(p_festival_company_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE a uuid:=public._caller_profile_id(); BEGIN IF auth.uid() IS NULL OR NOT public._festival_artist_manager(p_festival_company_id,a) THEN RAISE EXCEPTION 'festival_operations_forbidden' USING ERRCODE='P0001'; END IF; RETURN public._festival_operations_result(p_festival_company_id); END $$;

CREATE FUNCTION public.save_festival_operations_plan(p_festival_company_id uuid,p_expected_version integer,p_plan jsonb,p_idempotency_key uuid,p_complete boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE a uuid:=public._caller_profile_id(); ap public.festival_artist_programmes%ROWTYPE; op public.festival_operations_plans%ROWTYPE; req public.festival_operations_requests%ROWTYPE; h text; start_at timestamptz; end_at timestamptz; cap int; stages int;
BEGIN IF NOT public._festival_artist_manager(p_festival_company_id,a) THEN RAISE EXCEPTION 'festival_operations_forbidden' USING ERRCODE='P0001'; END IF; SELECT * INTO ap FROM public.festival_artist_programmes WHERE festival_company_id=p_festival_company_id; IF ap.status<>'ready_for_operations' THEN RAISE EXCEPTION 'festival_operations_prerequisite_incomplete' USING ERRCODE='P0001'; END IF;
h:=encode(digest(jsonb_build_object('version',p_expected_version,'plan',p_plan,'complete',p_complete)::text,'sha256'),'hex'); SELECT * INTO req FROM public.festival_operations_requests WHERE actor_profile_id=a AND action='save_plan' AND target_id=p_festival_company_id AND idempotency_key=p_idempotency_key FOR UPDATE; IF FOUND THEN IF req.payload_hash<>h THEN RAISE EXCEPTION 'festival_operations_idempotency_conflict' USING ERRCODE='P0001'; END IF; IF req.status='succeeded' THEN RETURN req.result; END IF; END IF;
SELECT * INTO op FROM public.festival_operations_plans WHERE festival_company_id=p_festival_company_id FOR UPDATE; IF (FOUND AND op.planning_version<>p_expected_version) OR (NOT FOUND AND p_expected_version<>0) THEN RAISE EXCEPTION 'festival_operations_plan_stale' USING ERRCODE='P0001'; END IF; IF (p_plan->>'currencyCode') IS NOT NULL AND p_plan->>'currencyCode'<>ap.currency_code THEN RAISE EXCEPTION 'festival_operations_currency_mismatch' USING ERRCODE='P0001'; END IF;
INSERT INTO public.festival_operations_requests(festival_company_id,actor_profile_id,action,target_id,idempotency_key,payload_hash) VALUES(p_festival_company_id,a,'save_plan',p_festival_company_id,p_idempotency_key,h) RETURNING * INTO req;
INSERT INTO public.festival_operations_plans(festival_company_id,artist_programme_id,currency_code,staff_budget_minor,supplier_budget_minor,contingency_budget_minor,staffing_mode,procurement_mode,status) VALUES(p_festival_company_id,ap.id,ap.currency_code,(p_plan->>'staffBudgetMinor')::bigint,(p_plan->>'supplierBudgetMinor')::bigint,(p_plan->>'contingencyBudgetMinor')::bigint,coalesce(p_plan->>'staffingMode','mixed'),coalesce(p_plan->>'procurementMode','mixed'),'requirements_generated') ON CONFLICT(festival_company_id) DO UPDATE SET staff_budget_minor=excluded.staff_budget_minor,supplier_budget_minor=excluded.supplier_budget_minor,contingency_budget_minor=excluded.contingency_budget_minor,staffing_mode=excluded.staffing_mode,procurement_mode=excluded.procurement_mode,planning_version=public.festival_operations_plans.planning_version+1,updated_at=now() RETURNING * INTO op;
IF NOT EXISTS(SELECT 1 FROM public.festival_operational_departments WHERE festival_operations_plan_id=op.id) THEN SELECT cfg.planned_start_date::timestamptz,cfg.planned_end_date::timestamptz+interval '1 day',sp.usable_capacity,(SELECT count(*) FROM public.festival_stages WHERE festival_company_id=p_festival_company_id) INTO start_at,end_at,cap,stages FROM public.festival_configurations cfg JOIN public.festival_site_plans sp ON sp.festival_company_id=cfg.festival_company_id WHERE cfg.festival_company_id=p_festival_company_id;
INSERT INTO public.festival_operational_departments(festival_operations_plan_id,department_type,name,priority,minimum_quality,target_quality) SELECT op.id,x,x,'essential',CASE WHEN x IN ('security','medical','fire_safety','gate_operations','accessibility') THEN 60 ELSE 40 END,80 FROM unnest(ARRAY['festival_management','stage_management','production','sound','lighting','security','medical','fire_safety','crowd_management','ticketing','gate_operations','artist_liaison','backstage','hospitality','catering','bars','cleaning','waste','transport','parking','accessibility','communications','technical_support','site_maintenance']) x;
INSERT INTO public.festival_staffing_requirements(festival_operations_plan_id,department_id,role_type,required_count,minimum_skill_level,minimum_experience,shift_length_minutes,coverage_start,coverage_end,safety_critical,player_eligible,npc_eligible,estimated_cost_minor) SELECT op.id,d.id,d.department_type,CASE d.department_type WHEN 'security' THEN greatest(2,ceil(cap/250.0)) WHEN 'crowd_management' THEN greatest(2,ceil(cap/300.0)) WHEN 'medical' THEN greatest(2,ceil(cap/5000.0)) WHEN 'sound' THEN greatest(1,stages) WHEN 'lighting' THEN greatest(1,stages) ELSE greatest(1,ceil(cap/2000.0)) END,CASE WHEN d.department_type IN ('security','medical','fire_safety','gate_operations','accessibility') THEN 60 ELSE 35 END,0,480,start_at,end_at,d.department_type IN ('security','medical','fire_safety','crowd_management','gate_operations','accessibility'),true,true,(CASE WHEN d.department_type IN ('security','medical','fire_safety') THEN 18000 ELSE 12000 END)*(CASE d.department_type WHEN 'security' THEN greatest(2,ceil(cap/250.0)) ELSE greatest(1,stages) END) FROM public.festival_operational_departments d WHERE d.festival_operations_plan_id=op.id;
INSERT INTO public.festival_supplier_requirements(festival_operations_plan_id,requirement_type,category,quantity,unit_type,minimum_quality,delivery_start,delivery_end,service_start,service_end,estimated_cost_minor,safety_critical,player_company_eligible,npc_supplier_eligible) SELECT op.id,x,x,CASE WHEN x='toilets' THEN greatest(1,ceil(cap/75.0)) WHEN x IN ('sound_equipment','lighting_equipment') THEN greatest(1,stages) ELSE 1 END,'contract',CASE WHEN x IN ('power_generation','toilets','medical_facilities','security_services','fire_safety','accessibility_equipment') THEN 60 ELSE 40 END,start_at-interval '1 day',start_at,start_at,end_at,CASE WHEN x IN ('power_generation','temporary_structures') THEN cap*100 ELSE cap*20 END,x IN ('power_generation','toilets','medical_facilities','security_services','fire_safety','accessibility_equipment'),true,true FROM unnest(ARRAY['stage_equipment','sound_equipment','lighting_equipment','power_generation','barriers','fencing','toilets','water','medical_facilities','security_services','fire_safety','catering','cleaning','waste','transport','temporary_structures','backstage_facilities','communications','ticket_scanning_equipment','accessibility_equipment']) x; END IF;
IF p_complete THEN IF EXISTS(SELECT 1 FROM public.festival_staffing_requirements r WHERE r.festival_operations_plan_id=op.id AND r.safety_critical AND (SELECT count(*) FROM public.festival_staff_assignments a WHERE a.staffing_requirement_id=r.id AND a.status='committed' AND a.quality_score>=r.minimum_skill_level)<r.required_count) THEN RAISE EXCEPTION 'festival_security_coverage_insufficient' USING ERRCODE='P0001'; END IF; IF EXISTS(SELECT 1 FROM public.festival_supplier_requirements r WHERE r.festival_operations_plan_id=op.id AND r.safety_critical AND NOT EXISTS(SELECT 1 FROM public.festival_supplier_contracts c WHERE c.supplier_requirement_id=r.id AND c.status='committed')) THEN RAISE EXCEPTION 'festival_supplier_requirement_uncovered' USING ERRCODE='P0001'; END IF; UPDATE public.festival_operations_plans SET status='ready_for_sponsorship',completed_at=now() WHERE id=op.id; END IF;
UPDATE public.festival_operations_requests SET status='succeeded',result=public._festival_operations_result(p_festival_company_id),completed_at=now() WHERE id=req.id; RETURN public._festival_operations_result(p_festival_company_id); END $$;

-- Explicit action endpoints deliberately expose bounded transitions rather than a generic status mutator.
CREATE FUNCTION public._festival_operations_not_implemented() RETURNS jsonb LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'festival_operations_action_invalid' USING ERRCODE='P0001'; END $$;
CREATE FUNCTION public.publish_festival_staff_vacancy(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.apply_for_festival_staff_vacancy(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.withdraw_festival_staff_application(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.review_festival_staff_application(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.hire_festival_staff_applicant(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.hire_festival_npc_staff(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.assign_festival_staff_shift(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.cancel_festival_staff_assignment(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.publish_festival_supplier_requirement(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.submit_festival_supplier_quote(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.withdraw_festival_supplier_quote(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.review_festival_supplier_quote(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.accept_festival_supplier_quote(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.cancel_festival_supplier_contract(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;
CREATE FUNCTION public.refresh_festival_npc_supplier_quotes(p_payload jsonb,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_operations_not_implemented() $$;

REVOKE ALL ON FUNCTION public._festival_operations_result(uuid),public._festival_operations_not_implemented() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_festival_operations_plan(uuid),public.save_festival_operations_plan(uuid,integer,jsonb,uuid,boolean) TO authenticated;
DO $$ DECLARE n text; BEGIN FOREACH n IN ARRAY ARRAY['publish_festival_staff_vacancy','apply_for_festival_staff_vacancy','withdraw_festival_staff_application','review_festival_staff_application','hire_festival_staff_applicant','hire_festival_npc_staff','assign_festival_staff_shift','cancel_festival_staff_assignment','publish_festival_supplier_requirement','submit_festival_supplier_quote','withdraw_festival_supplier_quote','review_festival_supplier_quote','accept_festival_supplier_quote','cancel_festival_supplier_contract','refresh_festival_npc_supplier_quotes'] LOOP EXECUTE format('REVOKE ALL ON FUNCTION public.%I(jsonb,uuid) FROM PUBLIC,anon',n); EXECUTE format('GRANT EXECUTE ON FUNCTION public.%I(jsonb,uuid) TO authenticated',n); END LOOP; END $$;
COMMENT ON TABLE public.festival_operations_requests IS 'Actor/action/target-scoped idempotency receipts. Same normalised payload returns its original transactional result.';
COMMENT ON TABLE public.festival_financial_commitments IS 'Planning encumbrances for artists, staff, and suppliers only; never cash, expense, payroll, or settlement.';
NOTIFY pgrst,'reload schema';
