-- Phase 3 is the single documented continuation after Phase 2's retained 2029 migration.
-- These are planning records only: this migration issues no tickets, opens no sale and posts no finance transaction.
CREATE TABLE public.festival_ticket_plans (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_company_id uuid UNIQUE NOT NULL REFERENCES public.festival_companies(id) ON DELETE CASCADE, festival_site_plan_id uuid UNIQUE NOT NULL REFERENCES public.festival_site_plans(id) ON DELETE CASCADE,
 currency_code text NOT NULL CHECK(currency_code ~ '^[A-Z]{3}$'), sales_tax_rate_basis_points integer NOT NULL CHECK(sales_tax_rate_basis_points BETWEEN 0 AND 10000), booking_fee_mode text NOT NULL CHECK(booking_fee_mode IN ('fixed','percentage','combined','none')), booking_fee_minor bigint NOT NULL DEFAULT 0 CHECK(booking_fee_minor>=0), booking_fee_basis_points integer NOT NULL DEFAULT 0 CHECK(booking_fee_basis_points BETWEEN 0 AND 10000), booking_fee_payer text NOT NULL CHECK(booking_fee_payer IN ('customer','festival_company','split')), refund_policy text, transfer_policy text, minimum_purchase_quantity integer NOT NULL DEFAULT 1 CHECK(minimum_purchase_quantity>0), maximum_purchase_quantity integer NOT NULL CHECK(maximum_purchase_quantity>=minimum_purchase_quantity), expected_sell_through_basis_points integer NOT NULL DEFAULT 8000 CHECK(expected_sell_through_basis_points BETWEEN 0 AND 10000), expected_refund_basis_points integer NOT NULL DEFAULT 300 CHECK(expected_refund_basis_points BETWEEN 0 AND 10000), expected_complimentary_use_basis_points integer NOT NULL DEFAULT 8000 CHECK(expected_complimentary_use_basis_points BETWEEN 0 AND 10000), expected_no_show_basis_points integer NOT NULL DEFAULT 500 CHECK(expected_no_show_basis_points BETWEEN 0 AND 10000), validation_issues jsonb NOT NULL DEFAULT '[]', forecast jsonb NOT NULL DEFAULT '{}', status text NOT NULL DEFAULT 'in_progress' CHECK(status IN ('not_started','in_progress','products_configured','capacity_allocated','forecast_reviewed','ready_for_artist_planning')), planning_version integer NOT NULL DEFAULT 1 CHECK(planning_version>0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz
);
CREATE TABLE public.festival_ticket_products (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_ticket_plan_id uuid NOT NULL REFERENCES public.festival_ticket_plans(id) ON DELETE CASCADE, festival_company_id uuid NOT NULL REFERENCES public.festival_companies(id) ON DELETE CASCADE, name text NOT NULL CHECK(char_length(btrim(name)) BETWEEN 1 AND 120), slug text NOT NULL, ticket_type text NOT NULL CHECK(ticket_type IN ('general_admission','day_ticket','weekend','full_festival','vip','accessible','child','resident','early_entry','camping','parking')), product_class text NOT NULL CHECK(product_class IN ('admission','upgrade','add_on')), access_scope text NOT NULL CHECK(access_scope IN ('single_day','date_range','full_festival','non_admission')), valid_from_date date NOT NULL, valid_to_date date NOT NULL CHECK(valid_to_date>=valid_from_date), price_minor bigint NOT NULL CHECK(price_minor>=0), face_value_minor bigint NOT NULL CHECK(face_value_minor>=0), capacity_limit integer NOT NULL CHECK(capacity_limit>=0), minimum_age integer CHECK(minimum_age BETWEEN 0 AND 99), includes_camping boolean NOT NULL DEFAULT false, includes_parking boolean NOT NULL DEFAULT false, includes_vip_area boolean NOT NULL DEFAULT false, includes_backstage boolean NOT NULL DEFAULT false, transferable boolean NOT NULL DEFAULT true, refundable boolean NOT NULL DEFAULT false, sale_priority integer NOT NULL CHECK(sale_priority>=0), active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(festival_ticket_plan_id,slug), UNIQUE(festival_ticket_plan_id,sale_priority), CHECK((product_class='add_on')=(access_scope='non_admission'))
);
CREATE TABLE public.festival_ticket_release_phases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_ticket_plan_id uuid NOT NULL REFERENCES public.festival_ticket_plans(id) ON DELETE CASCADE, festival_ticket_product_id uuid NOT NULL REFERENCES public.festival_ticket_products(id) ON DELETE CASCADE, name text NOT NULL CHECK(char_length(btrim(name))>0), release_type text NOT NULL CHECK(release_type IN ('presale','early_bird','general_sale','final_release','door','invitation','sponsor','community')), sort_order integer NOT NULL CHECK(sort_order>=0), starts_at timestamptz, ends_at timestamptz, allocation_limit integer NOT NULL CHECK(allocation_limit>=0), price_override_minor bigint CHECK(price_override_minor>=0), discount_basis_points integer NOT NULL DEFAULT 0 CHECK(discount_basis_points BETWEEN 0 AND 9000), eligibility_rule text, status text NOT NULL DEFAULT 'planned' CHECK(status IN ('planned','disabled')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(festival_ticket_plan_id,festival_ticket_product_id,name), UNIQUE(festival_ticket_plan_id,festival_ticket_product_id,sort_order), CHECK(starts_at IS NULL OR ends_at IS NULL OR starts_at<ends_at));
CREATE TABLE public.festival_ticket_capacity_allocations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_ticket_plan_id uuid NOT NULL REFERENCES public.festival_ticket_plans(id) ON DELETE CASCADE, festival_ticket_product_id uuid NOT NULL REFERENCES public.festival_ticket_products(id) ON DELETE CASCADE, festival_date date NOT NULL, capacity_allocated integer NOT NULL CHECK(capacity_allocated>=0), capacity_reserved integer NOT NULL DEFAULT 0 CHECK(capacity_reserved>=0), capacity_complimentary integer NOT NULL DEFAULT 0 CHECK(capacity_complimentary>=0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(festival_ticket_plan_id,festival_ticket_product_id,festival_date));
CREATE TABLE public.festival_ticket_plan_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_company_id uuid NOT NULL REFERENCES public.festival_companies(id) ON DELETE CASCADE, caller_profile_id uuid NOT NULL REFERENCES public.profiles(id), idempotency_key uuid NOT NULL, payload_hash text NOT NULL, result jsonb, status text NOT NULL DEFAULT 'processing' CHECK(status IN ('processing','succeeded')), created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, UNIQUE(festival_company_id,caller_profile_id,idempotency_key));
CREATE TABLE public.festival_ticket_plan_audit (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_company_id uuid NOT NULL REFERENCES public.festival_companies(id) ON DELETE CASCADE, ticket_plan_id uuid NOT NULL REFERENCES public.festival_ticket_plans(id) ON DELETE CASCADE, actor_profile_id uuid REFERENCES public.profiles(id), event_type text NOT NULL, previous_version integer NOT NULL, new_version integer NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.festival_ticket_plans ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_ticket_products ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_ticket_release_phases ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_ticket_capacity_allocations ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_ticket_plan_requests ENABLE ROW LEVEL SECURITY; ALTER TABLE public.festival_ticket_plan_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.festival_ticket_plans,public.festival_ticket_products,public.festival_ticket_release_phases,public.festival_ticket_capacity_allocations,public.festival_ticket_plan_requests,public.festival_ticket_plan_audit FROM PUBLIC,anon,authenticated;

CREATE FUNCTION public._festival_ticket_plan_result(p_company uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT jsonb_build_object('festivalCompanyId',fc.id,'festivalName',cfg.public_name,'festivalDates',(SELECT jsonb_agg(d::date ORDER BY d) FROM generate_series(cfg.planned_start_date,cfg.planned_end_date,'1 day') d),'usableSiteCapacity',sp.usable_capacity,'sitePlanStatus',sp.status,
 'ticketPlan',CASE WHEN tp.id IS NULL THEN NULL ELSE jsonb_build_object('id',tp.id,'currencyCode',tp.currency_code,'salesTaxRateBasisPoints',tp.sales_tax_rate_basis_points,'bookingFeeMode',tp.booking_fee_mode,'bookingFeeMinor',tp.booking_fee_minor,'bookingFeeBasisPoints',tp.booking_fee_basis_points,'bookingFeePayer',tp.booking_fee_payer,'refundPolicy',coalesce(tp.refund_policy,''),'transferPolicy',coalesce(tp.transfer_policy,''),'minimumPurchaseQuantity',tp.minimum_purchase_quantity,'maximumPurchaseQuantity',tp.maximum_purchase_quantity,'expectedSellThroughBasisPoints',tp.expected_sell_through_basis_points,'expectedRefundBasisPoints',tp.expected_refund_basis_points,'expectedComplimentaryUseBasisPoints',tp.expected_complimentary_use_basis_points,'expectedNoShowBasisPoints',tp.expected_no_show_basis_points,'status',tp.status) END,
 'products',coalesce((SELECT jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'slug',p.slug,'ticketType',p.ticket_type,'productClass',p.product_class,'accessScope',p.access_scope,'validFromDate',p.valid_from_date,'validToDate',p.valid_to_date,'priceMinor',p.price_minor,'faceValueMinor',p.face_value_minor,'capacityLimit',p.capacity_limit,'minimumAge',p.minimum_age,'includesCamping',p.includes_camping,'includesParking',p.includes_parking,'includesVipArea',p.includes_vip_area,'includesBackstage',p.includes_backstage,'transferable',p.transferable,'refundable',p.refundable,'salePriority',p.sale_priority,'active',p.active) ORDER BY p.sale_priority) FROM public.festival_ticket_products p WHERE p.festival_ticket_plan_id=tp.id),'[]'),
 'releasePhases',coalesce((SELECT jsonb_agg(jsonb_build_object('id',r.id,'productId',r.festival_ticket_product_id,'name',r.name,'releaseType',r.release_type,'sortOrder',r.sort_order,'startsAt',r.starts_at,'endsAt',r.ends_at,'allocationLimit',r.allocation_limit,'priceOverrideMinor',r.price_override_minor,'discountBasisPoints',r.discount_basis_points,'eligibilityRule',coalesce(r.eligibility_rule,''),'status',r.status) ORDER BY r.sort_order) FROM public.festival_ticket_release_phases r WHERE r.festival_ticket_plan_id=tp.id),'[]'),
 'capacityAllocations',coalesce((SELECT jsonb_agg(jsonb_build_object('id',a.id,'productId',a.festival_ticket_product_id,'productSlug',p.slug,'festivalDate',a.festival_date,'capacityAllocated',a.capacity_allocated,'capacityReserved',a.capacity_reserved,'capacityComplimentary',a.capacity_complimentary) ORDER BY a.festival_date,p.sale_priority) FROM public.festival_ticket_capacity_allocations a JOIN public.festival_ticket_products p ON p.id=a.festival_ticket_product_id WHERE a.festival_ticket_plan_id=tp.id),'[]'),'forecast',coalesce(tp.forecast,'{}'),'issues',coalesce(tp.validation_issues,'[]'),'warnings','[]'::jsonb,'ready',coalesce(tp.status='ready_for_artist_planning',false),'canWrite',true,'planningVersion',coalesce(tp.planning_version,0),'updatedAt',tp.updated_at)
 FROM public.festival_companies fc JOIN public.festival_configurations cfg ON cfg.festival_company_id=fc.id JOIN public.festival_site_plans sp ON sp.festival_company_id=fc.id LEFT JOIN public.festival_ticket_plans tp ON tp.festival_company_id=fc.id WHERE fc.id=p_company $$;
CREATE FUNCTION public.get_festival_ticket_plan(p_festival_company_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE profile uuid:=public._caller_profile_id(); BEGIN IF auth.uid() IS NULL OR NOT EXISTS(SELECT 1 FROM public.festival_companies f WHERE f.id=p_festival_company_id AND (f.owner_profile_id=profile OR coalesce(public.has_role(auth.uid(),'admin'::public.app_role),false))) THEN RAISE EXCEPTION 'festival_ticket_plan_forbidden' USING ERRCODE='P0001'; END IF; RETURN public._festival_ticket_plan_result(p_festival_company_id); END $$;
CREATE FUNCTION public.save_festival_ticket_plan(p_festival_company_id uuid,p_expected_version integer,p_ticket_plan jsonb,p_products jsonb,p_release_phases jsonb,p_capacity_allocations jsonb,p_idempotency_key uuid,p_complete boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE profile uuid:=public._caller_profile_id(); sp public.festival_site_plans%ROWTYPE; cfg public.festival_configurations%ROWTYPE; plan public.festival_ticket_plans%ROWTYPE; req public.festival_ticket_plan_requests%ROWTYPE; item jsonb; h text; result jsonb; currency text; issues jsonb:='[]'; total bigint; maximum_revenue bigint:=0; expected_gross bigint:=0; expected_sold bigint:=0; fee bigint:=0; tax bigint:=0; refunds bigint:=0; company_fee bigint:=0; forecast jsonb; old_version int:=0; product_id uuid; allocation_sum bigint;
BEGIN
 IF auth.uid() IS NULL OR NOT EXISTS(SELECT 1 FROM public.festival_companies f WHERE f.id=p_festival_company_id AND (f.owner_profile_id=profile OR coalesce(public.has_role(auth.uid(),'admin'::public.app_role),false))) THEN RAISE EXCEPTION 'festival_ticket_plan_forbidden' USING ERRCODE='P0001'; END IF;
 SELECT * INTO sp FROM public.festival_site_plans WHERE festival_company_id=p_festival_company_id; IF NOT FOUND OR sp.status<>'ready_for_ticketing' THEN RAISE EXCEPTION 'festival_site_plan_incomplete' USING ERRCODE='P0001'; END IF; SELECT * INTO cfg FROM public.festival_configurations WHERE festival_company_id=p_festival_company_id;
 currency:=CASE WHEN lower((SELECT country FROM public.cities WHERE id=cfg.home_city_id)) IN ('united kingdom','uk','england','scotland','wales','northern ireland') THEN 'GBP' WHEN lower((SELECT country FROM public.cities WHERE id=cfg.home_city_id)) IN ('united states','usa') THEN 'USD' ELSE 'EUR' END;
 PERFORM pg_advisory_xact_lock(hashtextextended(p_festival_company_id::text||p_idempotency_key::text,0)); h:=encode(digest(jsonb_build_object('version',p_expected_version,'plan',p_ticket_plan-'currencyCode','products',(SELECT coalesce(jsonb_agg(x ORDER BY x->>'slug'),'[]') FROM jsonb_array_elements(p_products) x),'phases',(SELECT coalesce(jsonb_agg(x ORDER BY x->>'productId',x->>'sortOrder'),'[]') FROM jsonb_array_elements(p_release_phases) x),'allocations',(SELECT coalesce(jsonb_agg(x ORDER BY x->>'productSlug',x->>'festivalDate'),'[]') FROM jsonb_array_elements(p_capacity_allocations) x),'complete',p_complete)::text,'sha256'),'hex');
 SELECT * INTO req FROM public.festival_ticket_plan_requests WHERE festival_company_id=p_festival_company_id AND caller_profile_id=profile AND idempotency_key=p_idempotency_key; IF FOUND THEN IF req.payload_hash<>h THEN RAISE EXCEPTION 'festival_ticket_plan_idempotency_conflict' USING ERRCODE='P0001'; END IF; IF req.status='succeeded' THEN RETURN req.result; END IF; ELSE INSERT INTO public.festival_ticket_plan_requests(festival_company_id,caller_profile_id,idempotency_key,payload_hash) VALUES(p_festival_company_id,profile,p_idempotency_key,h) RETURNING * INTO req; END IF;
 IF jsonb_typeof(p_products)<>'array' OR jsonb_array_length(p_products)=0 THEN RAISE EXCEPTION 'festival_ticket_product_required' USING ERRCODE='P0001'; END IF;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_products) x WHERE btrim(coalesce(x->>'name',''))='' OR coalesce(x->>'productClass','') NOT IN ('admission','upgrade','add_on') OR coalesce(x->>'accessScope','') NOT IN ('single_day','date_range','full_festival','non_admission') OR (x->>'priceMinor') !~ '^\d+$' OR (x->>'capacityLimit') !~ '^\d+$' OR (x->>'validFromDate')::date<cfg.planned_start_date OR (x->>'validToDate')::date>cfg.planned_end_date OR ((x->>'productClass')='add_on')<>((x->>'accessScope')='non_admission')) THEN RAISE EXCEPTION 'festival_ticket_product_invalid' USING ERRCODE='P0001'; END IF;
 IF EXISTS(SELECT lower(x->>'slug') FROM jsonb_array_elements(p_products)x GROUP BY lower(x->>'slug') HAVING count(*)>1) THEN RAISE EXCEPTION 'festival_ticket_product_invalid: duplicate slug' USING ERRCODE='P0001'; END IF;
 SELECT coalesce(planning_version,0) INTO old_version FROM public.festival_ticket_plans WHERE festival_company_id=p_festival_company_id FOR UPDATE; IF old_version<>p_expected_version THEN RAISE EXCEPTION 'festival_ticket_plan_stale' USING ERRCODE='P0001'; END IF;
 INSERT INTO public.festival_ticket_plans(festival_company_id,festival_site_plan_id,currency_code,sales_tax_rate_basis_points,booking_fee_mode,booking_fee_minor,booking_fee_basis_points,booking_fee_payer,refund_policy,transfer_policy,minimum_purchase_quantity,maximum_purchase_quantity,expected_sell_through_basis_points,expected_refund_basis_points,expected_complimentary_use_basis_points,expected_no_show_basis_points,status,planning_version)
 VALUES(p_festival_company_id,sp.id,currency,coalesce((p_ticket_plan->>'salesTaxRateBasisPoints')::int,2000),coalesce(p_ticket_plan->>'bookingFeeMode','none'),coalesce((p_ticket_plan->>'bookingFeeMinor')::bigint,0),coalesce((p_ticket_plan->>'bookingFeeBasisPoints')::int,0),coalesce(p_ticket_plan->>'bookingFeePayer','customer'),p_ticket_plan->>'refundPolicy',p_ticket_plan->>'transferPolicy',coalesce((p_ticket_plan->>'minimumPurchaseQuantity')::int,1),coalesce((p_ticket_plan->>'maximumPurchaseQuantity')::int,8),coalesce((p_ticket_plan->>'expectedSellThroughBasisPoints')::int,8000),coalesce((p_ticket_plan->>'expectedRefundBasisPoints')::int,300),coalesce((p_ticket_plan->>'expectedComplimentaryUseBasisPoints')::int,8000),coalesce((p_ticket_plan->>'expectedNoShowBasisPoints')::int,500),'in_progress',1)
 ON CONFLICT(festival_company_id) DO UPDATE SET sales_tax_rate_basis_points=excluded.sales_tax_rate_basis_points,booking_fee_mode=excluded.booking_fee_mode,booking_fee_minor=excluded.booking_fee_minor,booking_fee_basis_points=excluded.booking_fee_basis_points,booking_fee_payer=excluded.booking_fee_payer,refund_policy=excluded.refund_policy,transfer_policy=excluded.transfer_policy,minimum_purchase_quantity=excluded.minimum_purchase_quantity,maximum_purchase_quantity=excluded.maximum_purchase_quantity,expected_sell_through_basis_points=excluded.expected_sell_through_basis_points,expected_refund_basis_points=excluded.expected_refund_basis_points,expected_complimentary_use_basis_points=excluded.expected_complimentary_use_basis_points,expected_no_show_basis_points=excluded.expected_no_show_basis_points,planning_version=public.festival_ticket_plans.planning_version+1,updated_at=now() RETURNING * INTO plan;
 DELETE FROM public.festival_ticket_products WHERE festival_ticket_plan_id=plan.id;
 FOR item IN SELECT * FROM jsonb_array_elements(p_products) LOOP INSERT INTO public.festival_ticket_products(festival_ticket_plan_id,festival_company_id,name,slug,ticket_type,product_class,access_scope,valid_from_date,valid_to_date,price_minor,face_value_minor,capacity_limit,minimum_age,includes_camping,includes_parking,includes_vip_area,includes_backstage,transferable,refundable,sale_priority,active) VALUES(plan.id,p_festival_company_id,btrim(item->>'name'),lower(item->>'slug'),item->>'ticketType',item->>'productClass',item->>'accessScope',(item->>'validFromDate')::date,(item->>'validToDate')::date,(item->>'priceMinor')::bigint,(item->>'faceValueMinor')::bigint,(item->>'capacityLimit')::int,(item->>'minimumAge')::int,coalesce((item->>'includesCamping')::boolean,false),coalesce((item->>'includesParking')::boolean,false),coalesce((item->>'includesVipArea')::boolean,false),coalesce((item->>'includesBackstage')::boolean,false),coalesce((item->>'transferable')::boolean,true),coalesce((item->>'refundable')::boolean,false),(item->>'salePriority')::int,coalesce((item->>'active')::boolean,true)); END LOOP;
 FOR item IN SELECT * FROM jsonb_array_elements(p_capacity_allocations) LOOP SELECT id INTO product_id FROM public.festival_ticket_products WHERE festival_ticket_plan_id=plan.id AND slug=item->>'productSlug'; IF product_id IS NULL OR (item->>'festivalDate')::date NOT BETWEEN cfg.planned_start_date AND cfg.planned_end_date OR (item->>'capacityAllocated') !~ '^\d+$' THEN RAISE EXCEPTION 'festival_ticket_capacity_invalid' USING ERRCODE='P0001'; END IF; IF EXISTS(SELECT 1 FROM public.festival_ticket_products WHERE id=product_id AND product_class<>'admission' AND (item->>'capacityAllocated')::int>0) THEN RAISE EXCEPTION 'festival_ticket_capacity_invalid: add-on consumes admission capacity' USING ERRCODE='P0001'; END IF; INSERT INTO public.festival_ticket_capacity_allocations(festival_ticket_plan_id,festival_ticket_product_id,festival_date,capacity_allocated,capacity_reserved,capacity_complimentary) VALUES(plan.id,product_id,(item->>'festivalDate')::date,(item->>'capacityAllocated')::int,coalesce((item->>'capacityReserved')::int,0),coalesce((item->>'capacityComplimentary')::int,0)); END LOOP;
 IF EXISTS(SELECT festival_date FROM public.festival_ticket_capacity_allocations WHERE festival_ticket_plan_id=plan.id GROUP BY festival_date HAVING sum(capacity_allocated+capacity_reserved+capacity_complimentary)>sp.usable_capacity) THEN RAISE EXCEPTION 'festival_ticket_daily_capacity_exceeded' USING ERRCODE='P0001'; END IF;
 FOR item IN SELECT * FROM jsonb_array_elements(p_release_phases) LOOP SELECT id INTO product_id FROM public.festival_ticket_products WHERE festival_ticket_plan_id=plan.id AND (id::text=item->>'productId' OR slug=item->>'productSlug'); IF product_id IS NULL THEN RAISE EXCEPTION 'festival_ticket_release_invalid' USING ERRCODE='P0001'; END IF; INSERT INTO public.festival_ticket_release_phases(festival_ticket_plan_id,festival_ticket_product_id,name,release_type,sort_order,starts_at,ends_at,allocation_limit,price_override_minor,discount_basis_points,eligibility_rule,status) VALUES(plan.id,product_id,btrim(item->>'name'),item->>'releaseType',(item->>'sortOrder')::int,(item->>'startsAt')::timestamptz,(item->>'endsAt')::timestamptz,(item->>'allocationLimit')::int,(item->>'priceOverrideMinor')::bigint,coalesce((item->>'discountBasisPoints')::int,0),item->>'eligibilityRule',coalesce(item->>'status','planned')); END LOOP;
 IF EXISTS(SELECT r.festival_ticket_product_id FROM public.festival_ticket_release_phases r JOIN public.festival_ticket_products p ON p.id=r.festival_ticket_product_id WHERE r.festival_ticket_plan_id=plan.id GROUP BY r.festival_ticket_product_id,p.capacity_limit HAVING sum(r.allocation_limit)>p.capacity_limit) THEN RAISE EXCEPTION 'festival_ticket_release_allocation_exceeded' USING ERRCODE='P0001'; END IF;
 SELECT coalesce(sum(face_value_minor*capacity_limit),0),coalesce(sum((face_value_minor*capacity_limit*plan.expected_sell_through_basis_points)/10000),0),coalesce(sum((capacity_limit*plan.expected_sell_through_basis_points)/10000),0) INTO maximum_revenue,expected_gross,expected_sold FROM public.festival_ticket_products WHERE festival_ticket_plan_id=plan.id AND product_class='admission' AND active;
 fee:=CASE plan.booking_fee_mode WHEN 'none' THEN 0 ELSE ((plan.booking_fee_minor*expected_sold)+(expected_gross*plan.booking_fee_basis_points)/10000) END; tax:=(expected_gross*plan.sales_tax_rate_basis_points)/10000; refunds:=(expected_gross*plan.expected_refund_basis_points)/10000; company_fee:=CASE plan.booking_fee_payer WHEN 'customer' THEN 0 WHEN 'split' THEN fee/2 ELSE fee END;
 forecast:=jsonb_build_object('maximumAdmissionRevenueMinor',maximum_revenue,'expectedTicketsSold',expected_sold,'expectedGrossTicketReceiptsMinor',expected_gross,'expectedBookingFeesMinor',fee,'estimatedFestivalPaidFeesMinor',company_fee,'estimatedTaxMinor',tax,'expectedRefundsMinor',refunds,'expectedNetTicketReceiptsMinor',greatest(0,expected_gross-tax-refunds-company_fee),'averageRevenuePerAttendeeMinor',CASE WHEN expected_sold=0 THEN 0 ELSE expected_gross/expected_sold END,'daily',(SELECT coalesce(jsonb_agg(jsonb_build_object('festivalDate',d,'attendance',(used*plan.expected_sell_through_basis_points)/10000,'capacity',sp.usable_capacity,'utilisationBasisPoints',((used*plan.expected_sell_through_basis_points)/10000)*10000/sp.usable_capacity,'remainingCapacity',sp.usable_capacity-used) ORDER BY d),'[]') FROM (SELECT d::date d,coalesce(sum(a.capacity_allocated+a.capacity_reserved+a.capacity_complimentary),0)::bigint used FROM generate_series(cfg.planned_start_date,cfg.planned_end_date,'1 day') d LEFT JOIN public.festival_ticket_capacity_allocations a ON a.festival_ticket_plan_id=plan.id AND a.festival_date=d::date GROUP BY d) q));
 IF p_complete AND (NOT EXISTS(SELECT 1 FROM public.festival_ticket_products WHERE festival_ticket_plan_id=plan.id AND product_class='admission' AND active) OR EXISTS(SELECT 1 FROM generate_series(cfg.planned_start_date,cfg.planned_end_date,'1 day') d WHERE NOT EXISTS(SELECT 1 FROM public.festival_ticket_capacity_allocations a WHERE a.festival_ticket_plan_id=plan.id AND a.festival_date=d::date AND a.capacity_allocated>0))) THEN RAISE EXCEPTION 'festival_ticket_plan_incomplete' USING ERRCODE='P0001'; END IF;
 UPDATE public.festival_ticket_plans SET forecast=forecast,validation_issues=issues,status=CASE WHEN p_complete THEN 'ready_for_artist_planning' ELSE 'forecast_reviewed' END,completed_at=CASE WHEN p_complete THEN now() ELSE NULL END WHERE id=plan.id;
 INSERT INTO public.festival_ticket_plan_audit(festival_company_id,ticket_plan_id,actor_profile_id,event_type,previous_version,new_version,metadata) VALUES(p_festival_company_id,plan.id,profile,CASE WHEN p_complete THEN 'ticket_plan_completed' ELSE 'ticket_plan_saved' END,old_version,plan.planning_version,jsonb_build_object('forecastOnly',true,'currency',currency)); result:=public._festival_ticket_plan_result(p_festival_company_id); UPDATE public.festival_ticket_plan_requests SET result=result,status='succeeded',completed_at=now() WHERE id=req.id; RETURN result;
END $$;
REVOKE ALL ON FUNCTION public._festival_ticket_plan_result(uuid) FROM PUBLIC,anon,authenticated; REVOKE ALL ON FUNCTION public.get_festival_ticket_plan(uuid),public.save_festival_ticket_plan(uuid,integer,jsonb,jsonb,jsonb,jsonb,uuid,boolean) FROM PUBLIC,anon; GRANT EXECUTE ON FUNCTION public.get_festival_ticket_plan(uuid),public.save_festival_ticket_plan(uuid,integer,jsonb,jsonb,jsonb,jsonb,uuid,boolean) TO authenticated;
COMMENT ON TABLE public.festival_ticket_plans IS 'Planning assumptions and forecasts only; never evidence of a sale or earned revenue.';
