-- Authoritative post-runtime settlement for annual Festival editions.  The older
-- festival_financial_settlements authority remains a read-only legacy system: this
-- aggregate is bound exclusively to the canonical edition runtime completion digest.
CREATE TYPE public.festival_edition_settlement_state AS ENUM ('pending','preparing','review','approved','posting','completed','failed','recovery_required','reopened','voided');
CREATE TYPE public.festival_edition_reconciliation_status AS ENUM ('balanced','balanced_with_approved_rounding','warning','blocked');

CREATE TABLE public.festival_edition_settlements (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), festival_company_id uuid NOT NULL REFERENCES public.festival_companies(id), edition_id uuid NOT NULL REFERENCES public.festival_editions_v2(id),
 runtime_id uuid NOT NULL REFERENCES public.festival_edition_runtimes(id), runtime_completion_digest_id uuid NOT NULL REFERENCES public.festival_runtime_completion_digests(id), schedule_revision_id uuid NOT NULL REFERENCES public.festival_schedule_revisions(id), upgrade_snapshot_id uuid NOT NULL REFERENCES public.festival_edition_upgrade_snapshots(id),
 licence_snapshot jsonb NOT NULL, state public.festival_edition_settlement_state NOT NULL DEFAULT 'pending', settlement_version integer NOT NULL DEFAULT 1 CHECK(settlement_version>0), rules_version text NOT NULL DEFAULT 'festival-edition-settlement-v1', currency_code char(3) NOT NULL,
 gross_revenue_minor bigint NOT NULL DEFAULT 0 CHECK(gross_revenue_minor>=0), operating_revenue_minor bigint NOT NULL DEFAULT 0 CHECK(operating_revenue_minor>=0), total_costs_minor bigint NOT NULL DEFAULT 0 CHECK(total_costs_minor>=0), tax_minor bigint NOT NULL DEFAULT 0 CHECK(tax_minor>=0), refunds_minor bigint NOT NULL DEFAULT 0 CHECK(refunds_minor>=0), net_profit_loss_minor bigint NOT NULL DEFAULT 0,
 cash_posted_minor bigint NOT NULL DEFAULT 0, unpaid_receivables_minor bigint NOT NULL DEFAULT 0 CHECK(unpaid_receivables_minor>=0), unpaid_payables_minor bigint NOT NULL DEFAULT 0 CHECK(unpaid_payables_minor>=0), amount_posted_to_company_minor bigint NOT NULL DEFAULT 0,
 reconciliation_status public.festival_edition_reconciliation_status NOT NULL DEFAULT 'blocked', reconciliation jsonb NOT NULL DEFAULT '{}', input_snapshot jsonb NOT NULL, input_digest text NOT NULL, settlement_digest text,
 prepared_at timestamptz, approved_at timestamptz, posted_at timestamptz, completed_at timestamptz, reopened_at timestamptz, audit_metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(edition_id,settlement_version), UNIQUE(runtime_completion_digest_id), CHECK(currency_code~'^[A-Z]{3}$')
);
CREATE UNIQUE INDEX festival_edition_one_active_settlement ON public.festival_edition_settlements(edition_id) WHERE state<>'voided';

CREATE TABLE public.festival_edition_settlement_lines (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), settlement_id uuid NOT NULL REFERENCES public.festival_edition_settlements(id), line_kind text NOT NULL CHECK(line_kind IN('revenue','cost')), category text NOT NULL,
 source_type text NOT NULL, source_id text NOT NULL, gross_amount_minor bigint NOT NULL CHECK(gross_amount_minor>=0), tax_treatment text NOT NULL, tax_amount_minor bigint NOT NULL DEFAULT 0 CHECK(tax_amount_minor>=0), net_amount_minor bigint NOT NULL CHECK(net_amount_minor>=0), currency_code char(3) NOT NULL,
 evidence_reference jsonb NOT NULL, calculation_rule text NOT NULL, rules_version text NOT NULL, contract_id uuid, recipient_type text, recipient_id uuid, cash_state text NOT NULL DEFAULT 'unposted' CHECK(cash_state IN('unposted','posted','receivable','payable','not_applicable')), audit_timestamp timestamptz NOT NULL DEFAULT now(),
 UNIQUE(settlement_id,line_kind,category,source_type,source_id), CHECK(currency_code~'^[A-Z]{3}$')
);
CREATE TABLE public.festival_edition_settlement_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_id uuid REFERENCES public.festival_edition_settlements(id),edition_id uuid NOT NULL REFERENCES public.festival_editions_v2(id),actor_profile_id uuid NOT NULL REFERENCES public.profiles(id),action text NOT NULL,idempotency_key uuid NOT NULL,request_digest text NOT NULL,response jsonb,status text NOT NULL DEFAULT 'processing',created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(actor_profile_id,action,idempotency_key));
CREATE TABLE public.festival_edition_posting_batches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_id uuid NOT NULL UNIQUE REFERENCES public.festival_edition_settlements(id),state text NOT NULL CHECK(state IN('pending','posting','recovery_required','completed')),expected_items integer NOT NULL DEFAULT 0,completed_items integer NOT NULL DEFAULT 0,failure jsonb,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz);
CREATE TABLE public.festival_edition_posting_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),batch_id uuid NOT NULL REFERENCES public.festival_edition_posting_batches(id),settlement_line_id uuid NOT NULL UNIQUE REFERENCES public.festival_edition_settlement_lines(id),posting_reference text NOT NULL UNIQUE,state text NOT NULL CHECK(state IN('pending','posted','failed')),financial_transaction_id uuid UNIQUE REFERENCES public.financial_transactions(id),attempts integer NOT NULL DEFAULT 0,last_error text,posted_at timestamptz);
CREATE TABLE public.festival_edition_settlement_outcomes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_id uuid NOT NULL REFERENCES public.festival_edition_settlements(id),outcome_type text NOT NULL,subject_type text NOT NULL,subject_id text NOT NULL,final_score numeric CHECK(final_score BETWEEN 0 AND 100),components jsonb NOT NULL,effects jsonb NOT NULL DEFAULT '{}',rules_version text NOT NULL,evidence_references jsonb NOT NULL,applied_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(settlement_id,outcome_type,subject_type,subject_id));
CREATE TABLE public.festival_edition_licence_evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_id uuid NOT NULL UNIQUE REFERENCES public.festival_edition_settlements(id),edition_id uuid NOT NULL REFERENCES public.festival_editions_v2(id),evidence jsonb NOT NULL,rules_version text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.festival_edition_achievement_evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_id uuid NOT NULL REFERENCES public.festival_edition_settlements(id),achievement_key text NOT NULL,evidence jsonb NOT NULL,awarded_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(settlement_id,achievement_key));
CREATE TABLE public.festival_edition_history_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_id uuid NOT NULL,settlement_version integer NOT NULL,edition_id uuid NOT NULL REFERENCES public.festival_editions_v2(id),festival_company_id uuid NOT NULL REFERENCES public.festival_companies(id),public_projection jsonb NOT NULL,private_snapshot jsonb NOT NULL,content_digest text NOT NULL,runtime_digest text NOT NULL,settlement_digest text NOT NULL,migration_provenance jsonb,created_at timestamptz NOT NULL DEFAULT now(),superseded_at timestamptz,UNIQUE(settlement_id,settlement_version));

CREATE FUNCTION public._festival_edition_settlement_error(p_code text,p_details jsonb DEFAULT '{}') RETURNS void LANGUAGE plpgsql SET search_path='' AS $$ BEGIN RAISE EXCEPTION USING ERRCODE='P0001',MESSAGE=p_code,DETAIL=p_details::text; END $$;
CREATE FUNCTION public._festival_edition_settlement_authorised(p_company uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_edition_runtime_authorised(p_company) $$;
CREATE FUNCTION public._festival_settlement_request(p_edition uuid,p_settlement uuid,p_action text,p_key uuid,p_request jsonb,p_actor uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE x public.festival_edition_settlement_requests%ROWTYPE; d text:=encode(digest(p_request::text,'sha256'),'hex'); BEGIN
 SELECT * INTO x FROM public.festival_edition_settlement_requests WHERE actor_profile_id=p_actor AND action=p_action AND idempotency_key=p_key FOR UPDATE;
 IF FOUND AND x.request_digest<>d THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_IDEMPOTENCY_CONFLICT'); END IF;
 IF FOUND AND x.status='completed' THEN RETURN x.response; END IF;
 IF NOT FOUND THEN INSERT INTO public.festival_edition_settlement_requests(settlement_id,edition_id,actor_profile_id,action,idempotency_key,request_digest) VALUES(p_settlement,p_edition,p_actor,p_action,p_key,d); END IF;
 RETURN NULL; END $$;

-- All preparation inputs are copied from the frozen runtime configuration/evidence.
-- No mutable Festival-company configuration participates in this function.
CREATE FUNCTION public.prepare_festival_edition_settlement(p_edition_id uuid,p_expected_runtime_digest text,p_idempotency_key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE r public.festival_edition_runtimes%ROWTYPE; cd public.festival_runtime_completion_digests%ROWTYPE; s public.festival_edition_settlements%ROWTYPE; cfg jsonb; inp jsonb; actor uuid:=public._festival_edition_runtime_actor(); replay jsonb; cur text; taxcfg jsonb; ticket jsonb; gross bigint:=0; costs bigint:=0; tax bigint:=0; refunds bigint:=0; e jsonb; amount bigint; cat text;
BEGIN
 SELECT * INTO r FROM public.festival_edition_runtimes WHERE edition_id=p_edition_id ORDER BY created_at DESC LIMIT 1 FOR UPDATE;
 IF NOT FOUND OR r.state<>'completed' THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_RUNTIME_INCOMPLETE'); END IF;
 IF actor IS NULL OR NOT public._festival_edition_settlement_authorised(r.festival_company_id) THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_ACCESS_DENIED'); END IF;
 SELECT * INTO cd FROM public.festival_runtime_completion_digests WHERE runtime_id=r.id;
 IF NOT FOUND OR cd.runtime_digest<>p_expected_runtime_digest THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_EVIDENCE_MISSING',jsonb_build_object('component','completion_digest')); END IF;
 replay:=public._festival_settlement_request(p_edition_id,NULL,'prepare',p_idempotency_key,jsonb_build_object('edition',p_edition_id,'runtimeDigest',p_expected_runtime_digest),actor); IF replay IS NOT NULL THEN RETURN replay; END IF;
 IF EXISTS(SELECT 1 FROM public.festival_edition_settlements WHERE edition_id=p_edition_id AND state<>'voided') THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_ALREADY_EXISTS'); END IF;
 SELECT configuration INTO cfg FROM public.festival_runtime_configuration_versions WHERE runtime_id=r.id AND version=r.configuration_version;
 cur:=coalesce(cfg->>'currencyCode','GBP'); taxcfg:=cfg->'taxConfiguration'; ticket:=cfg->'ticketSalesSnapshot';
 IF cfg IS NULL OR ticket IS NULL THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_EVIDENCE_MISSING',jsonb_build_object('component','ticketSalesSnapshot')); END IF;
 IF taxcfg IS NULL OR taxcfg->>'rule' IS NULL THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_TAX_CONFIGURATION_MISSING'); END IF;
 IF cur!~'^[A-Z]{3}$' THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_CURRENCY_MISMATCH'); END IF;
 inp:=jsonb_build_object('runtimeCompletionDigest',to_jsonb(cd),'runtimeConfiguration',cfg,'runtimeEvidence',(SELECT coalesce(jsonb_agg(to_jsonb(x) ORDER BY x.id),'[]') FROM public.festival_runtime_evidence x WHERE x.runtime_id=r.id),'incidents',(SELECT coalesce(jsonb_agg(to_jsonb(x) ORDER BY x.id),'[]') FROM public.festival_edition_runtime_incidents x WHERE x.runtime_id=r.id),'frozenAt',now());
 INSERT INTO public.festival_edition_settlements(festival_company_id,edition_id,runtime_id,runtime_completion_digest_id,schedule_revision_id,upgrade_snapshot_id,licence_snapshot,state,currency_code,input_snapshot,input_digest,prepared_at,audit_metadata)
 VALUES(r.festival_company_id,r.edition_id,r.id,cd.id,r.schedule_revision_id,r.upgrade_snapshot_id,r.licence_snapshot,'preparing',cur,inp,encode(digest(inp::text,'sha256'),'hex'),now(),jsonb_build_object('preparedBy',actor)) RETURNING * INTO s;
 -- Frozen generic financial evidence uses category/amountMinor/sourceId. Unknown or
 -- unapproved categories fail closed rather than becoming an unexplained total.
 FOR e IN SELECT value FROM jsonb_array_elements(coalesce(ticket->'lines','[]')) LOOP
  amount:=(e->>'amountMinor')::bigint; cat:=coalesce(e->>'category','ticket_other');
  IF amount<0 OR cat NOT IN('ticket_general_admission','ticket_vip','ticket_camping','ticket_multi_day','ticket_other') THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_EVIDENCE_MISSING',jsonb_build_object('category',cat)); END IF;
  INSERT INTO public.festival_edition_settlement_lines(settlement_id,line_kind,category,source_type,source_id,gross_amount_minor,tax_treatment,tax_amount_minor,net_amount_minor,currency_code,evidence_reference,calculation_rule,rules_version,cash_state) VALUES(s.id,'revenue',cat,'ticket_sales_snapshot',e->>'sourceId',amount,coalesce(e->>'taxTreatment','inclusive'),coalesce((e->>'taxMinor')::bigint,0),amount-coalesce((e->>'taxMinor')::bigint,0),cur,e,'frozen-ticket-line','festival-edition-settlement-v1','unposted'); gross:=gross+amount; END LOOP;
 FOR e IN SELECT value FROM jsonb_array_elements(coalesce(cfg->'approvedFinancialEvidence','[]')) LOOP
  amount:=(e->>'amountMinor')::bigint; cat:=e->>'category'; IF amount<0 OR e->>'kind' NOT IN('revenue','cost') THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_EVIDENCE_MISSING'); END IF;
  INSERT INTO public.festival_edition_settlement_lines(settlement_id,line_kind,category,source_type,source_id,gross_amount_minor,tax_treatment,tax_amount_minor,net_amount_minor,currency_code,evidence_reference,calculation_rule,rules_version,contract_id,recipient_type,recipient_id,cash_state) VALUES(s.id,e->>'kind',cat,e->>'sourceType',e->>'sourceId',amount,coalesce(e->>'taxTreatment','exclusive'),coalesce((e->>'taxMinor')::bigint,0),amount,cur,e,coalesce(e->>'calculationRule','frozen-approved-evidence'),'festival-edition-settlement-v1',nullif(e->>'contractId','')::uuid,e->>'recipientType',nullif(e->>'recipientId','')::uuid,CASE WHEN e->>'cashState' IN('receivable','payable') THEN e->>'cashState' ELSE 'unposted' END);
  IF e->>'kind'='revenue' THEN gross:=gross+amount; ELSE costs:=costs+amount; END IF; END LOOP;
 refunds:=coalesce((ticket->>'refundedMinor')::bigint,0); tax:=((greatest(gross-refunds,0)*(taxcfg->>'rateBasisPoints')::bigint)+5000)/10000;
 IF refunds>0 THEN INSERT INTO public.festival_edition_settlement_lines(settlement_id,line_kind,category,source_type,source_id,gross_amount_minor,tax_treatment,net_amount_minor,currency_code,evidence_reference,calculation_rule,rules_version) VALUES(s.id,'cost','refunds','ticket_sales_snapshot','refunds',refunds,'not_taxable',refunds,cur,ticket,'authoritative-refund-records','festival-edition-settlement-v1'); END IF;
 IF tax>0 THEN INSERT INTO public.festival_edition_settlement_lines(settlement_id,line_kind,category,source_type,source_id,gross_amount_minor,tax_treatment,net_amount_minor,currency_code,evidence_reference,calculation_rule,rules_version,cash_state) VALUES(s.id,'cost','tax','tax_configuration',taxcfg->>'rule',tax,'tax',tax,cur,taxcfg,'jurisdiction-basis-points','festival-edition-settlement-v1','payable'); END IF;
 UPDATE public.festival_edition_settlements SET state='review',gross_revenue_minor=gross,operating_revenue_minor=gross,total_costs_minor=costs+tax+refunds,tax_minor=tax,refunds_minor=refunds,net_profit_loss_minor=gross-costs-tax-refunds,reconciliation_status='balanced',reconciliation=jsonb_build_object('status','balanced','runtimeDigest',cd.runtime_digest,'lineRevenueMinor',gross,'lineCostMinor',costs+tax+refunds),settlement_version=2,updated_at=now() WHERE id=s.id RETURNING * INTO s;
 replay:=jsonb_build_object('settlementId',s.id,'state',s.state,'version',s.settlement_version,'reconciliationStatus',s.reconciliation_status,'idempotent',false); UPDATE public.festival_edition_settlement_requests SET settlement_id=s.id,status='completed',response=replay,completed_at=now() WHERE actor_profile_id=actor AND action='prepare' AND idempotency_key=p_idempotency_key; RETURN replay;
END $$;

CREATE FUNCTION public.approve_festival_edition_settlement(p_settlement_id uuid,p_expected_version integer,p_idempotency_key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE s public.festival_edition_settlements%ROWTYPE; actor uuid:=public._festival_edition_runtime_actor(); replay jsonb; result jsonb; BEGIN SELECT * INTO s FROM public.festival_edition_settlements WHERE id=p_settlement_id FOR UPDATE; IF NOT FOUND THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_NOT_FOUND'); END IF; IF actor IS NULL OR NOT public._festival_edition_settlement_authorised(s.festival_company_id) THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_ACCESS_DENIED'); END IF; replay:=public._festival_settlement_request(s.edition_id,s.id,'approve',p_idempotency_key,jsonb_build_object('settlement',s.id,'version',p_expected_version),actor); IF replay IS NOT NULL THEN RETURN replay; END IF; IF s.settlement_version<>p_expected_version THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_VERSION_CONFLICT'); END IF; IF s.state<>'review' THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_INVALID_TRANSITION'); END IF; IF s.reconciliation_status='blocked' THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_RECONCILIATION_FAILED'); END IF; UPDATE public.festival_edition_settlements SET state='approved',settlement_version=settlement_version+1,approved_at=now(),updated_at=now() WHERE id=s.id RETURNING * INTO s; result:=jsonb_build_object('settlementId',s.id,'state',s.state,'version',s.settlement_version); UPDATE public.festival_edition_settlement_requests SET status='completed',response=result,completed_at=now() WHERE actor_profile_id=actor AND action='approve' AND idempotency_key=p_idempotency_key; RETURN result; END $$;

-- Posting delegates every movement to the shared canonical finance ledger.  Stable
-- line references and finance idempotency constraints make recovery safe.
CREATE FUNCTION public.post_festival_edition_settlement(p_settlement_id uuid,p_expected_version integer,p_idempotency_key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE s public.festival_edition_settlements%ROWTYPE; l public.festival_edition_settlement_lines%ROWTYPE; b public.festival_edition_posting_batches%ROWTYPE; item public.festival_edition_posting_items%ROWTYPE; actor uuid:=public._festival_edition_runtime_actor(); replay jsonb; tx uuid; result jsonb; desttype public.financial_owner_type; net bigint:=0;
BEGIN SELECT * INTO s FROM public.festival_edition_settlements WHERE id=p_settlement_id FOR UPDATE; IF NOT FOUND THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_NOT_FOUND'); END IF; IF actor IS NULL OR NOT public._festival_edition_settlement_authorised(s.festival_company_id) THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_ACCESS_DENIED'); END IF;
 replay:=public._festival_settlement_request(s.edition_id,s.id,'post',p_idempotency_key,jsonb_build_object('settlement',s.id,'version',p_expected_version),actor); IF replay IS NOT NULL THEN RETURN replay; END IF;
 IF s.state='completed' THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_ALREADY_POSTED'); END IF; IF s.settlement_version<>p_expected_version THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_VERSION_CONFLICT'); END IF; IF s.state NOT IN('approved','recovery_required') THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_INVALID_TRANSITION'); END IF; IF s.reconciliation_status='blocked' THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_RECONCILIATION_FAILED'); END IF;
 INSERT INTO public.festival_edition_posting_batches(settlement_id,state,expected_items) VALUES(s.id,'posting',(SELECT count(*) FROM public.festival_edition_settlement_lines WHERE settlement_id=s.id AND net_amount_minor>0)) ON CONFLICT(settlement_id) DO UPDATE SET state='posting',failure=NULL RETURNING * INTO b; UPDATE public.festival_edition_settlements SET state='posting',updated_at=now() WHERE id=s.id;
 FOR l IN SELECT * FROM public.festival_edition_settlement_lines WHERE settlement_id=s.id AND net_amount_minor>0 ORDER BY line_kind,id FOR UPDATE LOOP
  INSERT INTO public.festival_edition_posting_items(batch_id,settlement_line_id,posting_reference,state) VALUES(b.id,l.id,'festival-edition-settlement:'||s.id||':line:'||l.id,'pending') ON CONFLICT(settlement_line_id) DO NOTHING; SELECT * INTO item FROM public.festival_edition_posting_items WHERE settlement_line_id=l.id FOR UPDATE; IF item.state='posted' THEN CONTINUE; END IF;
  BEGIN
   IF l.line_kind='revenue' THEN tx:=public.finance_credit_owner('company',s.festival_company_id,l.net_amount_minor,'festival_payment','Festival edition income',item.posting_reference,actor,jsonb_build_object('settlementId',s.id,'editionId',s.edition_id,'lineId',l.id)); net:=net+l.net_amount_minor;
   ELSIF l.recipient_id IS NOT NULL AND l.recipient_type IN('player','band','company') THEN desttype:=l.recipient_type::public.financial_owner_type; tx:=public.finance_transfer('company',s.festival_company_id,desttype,l.recipient_id,l.net_amount_minor,CASE WHEN l.category IN('staff_wages','staff_overtime') THEN 'wage_payment'::public.financial_transaction_category ELSE 'festival_payment'::public.financial_transaction_category END,'Festival edition payable',item.posting_reference,'festival_edition_settlement',s.id,actor,jsonb_build_object('lineId',l.id)); net:=net-l.net_amount_minor;
   ELSE tx:=public.finance_debit_owner('company',s.festival_company_id,l.net_amount_minor,CASE WHEN l.category='refunds' THEN 'refund'::public.financial_transaction_category WHEN l.category='tax' THEN 'tax_placeholder'::public.financial_transaction_category ELSE 'company_operating_expense'::public.financial_transaction_category END,'Festival edition cost',item.posting_reference,actor,jsonb_build_object('settlementId',s.id,'lineId',l.id)); net:=net-l.net_amount_minor; END IF;
   UPDATE public.festival_edition_posting_items SET state='posted',financial_transaction_id=tx,attempts=attempts+1,posted_at=now() WHERE id=item.id; UPDATE public.festival_edition_settlement_lines SET cash_state='posted' WHERE id=l.id;
  EXCEPTION WHEN OTHERS THEN UPDATE public.festival_edition_posting_items SET state='failed',attempts=attempts+1,last_error=SQLSTATE WHERE id=item.id; UPDATE public.festival_edition_posting_batches SET state='recovery_required',failure=jsonb_build_object('code','FESTIVAL_SETTLEMENT_POSTING_FAILED','lineId',l.id) WHERE id=b.id; UPDATE public.festival_edition_settlements SET state='recovery_required',updated_at=now() WHERE id=s.id; PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_RECOVERY_REQUIRED',jsonb_build_object('lineId',l.id)); END;
 END LOOP;
 UPDATE public.festival_edition_posting_batches SET state='completed',completed_items=expected_items,completed_at=now() WHERE id=b.id; UPDATE public.festival_edition_settlements SET state='completed',settlement_version=settlement_version+1,cash_posted_minor=net,amount_posted_to_company_minor=net,posted_at=now(),completed_at=now(),settlement_digest=encode(digest(input_digest||':'||gross_revenue_minor||':'||total_costs_minor||':'||net_profit_loss_minor,'sha256'),'hex'),updated_at=now() WHERE id=s.id RETURNING * INTO s;
 -- Evidence-derived outcomes, eligibility and stable achievements are applied once.
 INSERT INTO public.festival_edition_settlement_outcomes(settlement_id,outcome_type,subject_type,subject_id,final_score,components,rules_version,evidence_references) SELECT s.id,'audience_satisfaction','edition',s.edition_id::text,coalesce(avg((e.evidence->>'score')::numeric),50),jsonb_build_object('samples',count(*)),'festival-outcome-v1',jsonb_agg(e.id) FROM public.festival_runtime_evidence e WHERE e.runtime_id=s.runtime_id AND e.evidence_type='audience_satisfaction' ON CONFLICT DO NOTHING;
 INSERT INTO public.festival_edition_licence_evidence(settlement_id,edition_id,evidence,rules_version) VALUES(s.id,s.edition_id,jsonb_build_object('completedEdition',true,'attendance',(SELECT admitted_attendance FROM public.festival_edition_runtimes WHERE id=s.runtime_id),'taxPaid',s.tax_minor,'solvent',s.net_profit_loss_minor>=0),'festival-licence-evidence-v1') ON CONFLICT DO NOTHING;
 INSERT INTO public.festival_edition_achievement_evidence(settlement_id,achievement_key,evidence) VALUES(s.id,'festival.run_first',jsonb_build_object('editionId',s.edition_id)),(s.id,CASE WHEN s.net_profit_loss_minor>0 THEN 'festival.profitable' ELSE 'festival.completed' END,jsonb_build_object('netProfitLossMinor',s.net_profit_loss_minor)) ON CONFLICT DO NOTHING;
 INSERT INTO public.festival_edition_history_snapshots(settlement_id,settlement_version,edition_id,festival_company_id,public_projection,private_snapshot,content_digest,runtime_digest,settlement_digest) SELECT s.id,s.settlement_version,s.edition_id,s.festival_company_id,jsonb_build_object('editionId',s.edition_id,'dates',jsonb_build_object('startsOn',e.starts_on,'endsOn',e.ends_on),'attendance',r.admitted_attendance,'audienceRating',(SELECT final_score FROM public.festival_edition_settlement_outcomes WHERE settlement_id=s.id AND outcome_type='audience_satisfaction'),'sellOut',r.admitted_attendance=r.site_capacity,'profitabilityBand',CASE WHEN s.net_profit_loss_minor>0 THEN 'profitable' WHEN s.net_profit_loss_minor<0 THEN 'loss' ELSE 'break_even' END,'completedAt',s.completed_at),jsonb_build_object('settlement',to_jsonb(s),'inputs',s.input_snapshot,'lines',(SELECT jsonb_agg(to_jsonb(x) ORDER BY x.id) FROM public.festival_edition_settlement_lines x WHERE x.settlement_id=s.id),'outcomes',(SELECT jsonb_agg(to_jsonb(x) ORDER BY x.id) FROM public.festival_edition_settlement_outcomes x WHERE x.settlement_id=s.id)),encode(digest(s.input_digest||s.settlement_digest,'sha256'),'hex'),cd.runtime_digest,s.settlement_digest FROM public.festival_editions_v2 e JOIN public.festival_edition_runtimes r ON r.id=s.runtime_id JOIN public.festival_runtime_completion_digests cd ON cd.id=s.runtime_completion_digest_id WHERE e.id=s.edition_id;
 result:=jsonb_build_object('settlementId',s.id,'state',s.state,'version',s.settlement_version,'postingBatchId',b.id,'settlementDigest',s.settlement_digest); UPDATE public.festival_edition_settlement_requests SET status='completed',response=result,completed_at=now() WHERE actor_profile_id=actor AND action='post' AND idempotency_key=p_idempotency_key; RETURN result; END $$;

CREATE FUNCTION public.get_festival_edition_settlement(p_festival_company_id uuid,p_edition_id uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$ DECLARE s public.festival_edition_settlements%ROWTYPE; BEGIN IF NOT public._festival_edition_settlement_authorised(p_festival_company_id) THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_ACCESS_DENIED'); END IF; SELECT * INTO s FROM public.festival_edition_settlements WHERE festival_company_id=p_festival_company_id AND edition_id=p_edition_id AND state<>'voided'; IF NOT FOUND THEN RETURN NULL; END IF; RETURN jsonb_build_object('settlement',to_jsonb(s),'lines',(SELECT coalesce(jsonb_agg(to_jsonb(l) ORDER BY l.line_kind,l.category,l.id),'[]') FROM public.festival_edition_settlement_lines l WHERE l.settlement_id=s.id),'outcomes',(SELECT coalesce(jsonb_agg(to_jsonb(o) ORDER BY o.outcome_type,o.subject_id),'[]') FROM public.festival_edition_settlement_outcomes o WHERE o.settlement_id=s.id),'batch',(SELECT to_jsonb(b) FROM public.festival_edition_posting_batches b WHERE b.settlement_id=s.id),'audit',(SELECT coalesce(jsonb_agg(to_jsonb(q) ORDER BY q.created_at),'[]') FROM public.festival_edition_settlement_requests q WHERE q.settlement_id=s.id)); END $$;
CREATE FUNCTION public.get_public_festival_edition_history(p_edition_id uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT public_projection FROM public.festival_edition_history_snapshots WHERE edition_id=p_edition_id AND superseded_at IS NULL ORDER BY settlement_version DESC LIMIT 1 $$;

CREATE FUNCTION public._festival_history_immutable() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_HISTORY_ALREADY_FROZEN'); RETURN NULL; END $$;
CREATE TRIGGER festival_history_immutable BEFORE UPDATE OR DELETE ON public.festival_edition_history_snapshots FOR EACH ROW EXECUTE FUNCTION public._festival_history_immutable();
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['festival_edition_settlements','festival_edition_settlement_lines','festival_edition_settlement_requests','festival_edition_posting_batches','festival_edition_posting_items','festival_edition_settlement_outcomes','festival_edition_licence_evidence','festival_edition_achievement_evidence','festival_edition_history_snapshots'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t); END LOOP; END $$;
REVOKE ALL ON FUNCTION public._festival_edition_settlement_error(text,jsonb),public._festival_edition_settlement_authorised(uuid),public._festival_settlement_request(uuid,uuid,text,uuid,jsonb,uuid),public.prepare_festival_edition_settlement(uuid,text,uuid),public.approve_festival_edition_settlement(uuid,integer,uuid),public.post_festival_edition_settlement(uuid,integer,uuid),public.get_festival_edition_settlement(uuid,uuid),public.get_public_festival_edition_history(uuid),public._festival_history_immutable() FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.prepare_festival_edition_settlement(uuid,text,uuid),public.approve_festival_edition_settlement(uuid,integer,uuid),public.post_festival_edition_settlement(uuid,integer,uuid),public.get_festival_edition_settlement(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_festival_edition_history(uuid) TO anon,authenticated;
COMMENT ON TABLE public.festival_edition_settlements IS 'Single active authoritative aggregate bound to immutable canonical runtime completion evidence; legacy settlement tables are not writers for annual editions.';
COMMENT ON TABLE public.festival_edition_history_snapshots IS 'Immutable private evidence and deliberately redacted public projection. Never rebuilt from mutable company state.';
