-- Edition-bound hidden Festival foundations.
-- The owner continues to choose only high-level annual plan, ticket and line-up inputs.
-- Site engineering, stages, release allocation and forecast detail are generated by the server.

ALTER TABLE public.festival_site_plans
  DROP CONSTRAINT IF EXISTS festival_site_plans_festival_company_id_key;
ALTER TABLE public.festival_ticket_plans
  DROP CONSTRAINT IF EXISTS festival_ticket_plans_festival_company_id_key;
ALTER TABLE public.festival_artist_programmes
  DROP CONSTRAINT IF EXISTS festival_artist_programmes_festival_company_id_key;

ALTER TABLE public.festival_site_plans
  ADD COLUMN IF NOT EXISTS projection_source text NOT NULL DEFAULT 'manual'
    CHECK (projection_source IN ('manual', 'annual_plan'));
ALTER TABLE public.festival_site_plan_stages
  ADD COLUMN IF NOT EXISTS projection_source text NOT NULL DEFAULT 'manual'
    CHECK (projection_source IN ('manual', 'annual_plan'));
ALTER TABLE public.festival_ticket_plans
  ADD COLUMN IF NOT EXISTS projection_source text NOT NULL DEFAULT 'manual'
    CHECK (projection_source IN ('manual', 'annual_plan'));

CREATE INDEX IF NOT EXISTS festival_site_plans_company_edition_idx
  ON public.festival_site_plans(festival_company_id, festival_edition_id);
CREATE INDEX IF NOT EXISTS festival_ticket_plans_company_edition_idx
  ON public.festival_ticket_plans(festival_company_id, festival_edition_id);
CREATE INDEX IF NOT EXISTS festival_artist_programmes_company_edition_idx
  ON public.festival_artist_programmes(festival_company_id, festival_edition_id);

CREATE OR REPLACE FUNCTION public._festival_projection_currency(p_city_id uuid)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE
    WHEN lower(country) IN (
      'united kingdom', 'uk', 'england', 'scotland', 'wales',
      'northern ireland'
    ) THEN 'GBP'
    WHEN lower(country) IN ('united states', 'usa', 'us') THEN 'USD'
    ELSE 'EUR'
  END
  FROM public.cities
  WHERE id = p_city_id
$$;

CREATE OR REPLACE FUNCTION public._festival_projection_authorized(
  p_festival_company_id uuid,
  p_festival_edition_id uuid,
  p_actor uuid
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.festival_companies company
    JOIN public.festival_editions_v2 edition
      ON edition.festival_company_id = company.id
     AND edition.id = p_festival_edition_id
    WHERE company.id = p_festival_company_id
      AND (
        company.owner_profile_id = p_actor
        OR coalesce(public.has_role(auth.uid(), 'admin'::public.app_role), false)
      )
  )
$$;

CREATE OR REPLACE FUNCTION public._festival_projection_forecast(
  p_start date,
  p_end date,
  p_capacity integer,
  p_price_minor bigint,
  p_sell_through_basis_points integer,
  p_tax_basis_points integer DEFAULT 2000,
  p_refund_basis_points integer DEFAULT 300
)
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH values AS (
    SELECT
      greatest(0, round(p_capacity::numeric * p_sell_through_basis_points / 10000))::bigint AS sold,
      greatest(0, p_capacity) AS capacity
  ), totals AS (
    SELECT
      sold,
      capacity,
      sold * greatest(0, p_price_minor) AS gross
    FROM values
  )
  SELECT jsonb_build_object(
    'maximumAdmissionRevenueMinor', capacity::bigint * greatest(0, p_price_minor),
    'expectedTicketsSold', sold,
    'expectedGrossTicketReceiptsMinor', gross,
    'expectedBookingFeesMinor', 0,
    'estimatedFestivalPaidFeesMinor', 0,
    'estimatedTaxMinor', round(gross::numeric * p_tax_basis_points / 10000)::bigint,
    'expectedRefundsMinor', round(gross::numeric * p_refund_basis_points / 10000)::bigint,
    'expectedNetTicketReceiptsMinor', greatest(
      0,
      gross
        - round(gross::numeric * p_tax_basis_points / 10000)::bigint
        - round(gross::numeric * p_refund_basis_points / 10000)::bigint
    ),
    'averageRevenuePerAttendeeMinor', CASE WHEN sold = 0 THEN 0 ELSE greatest(0, p_price_minor) END,
    'daily', (
      SELECT coalesce(jsonb_agg(jsonb_build_object(
        'festivalDate', day::date,
        'attendance', sold,
        'capacity', capacity,
        'utilisationBasisPoints', p_sell_through_basis_points,
        'remainingCapacity', greatest(0, capacity - sold)
      ) ORDER BY day), '[]'::jsonb)
      FROM generate_series(p_start, p_end, interval '1 day') day
    )
  )
  FROM totals
$$;

CREATE OR REPLACE FUNCTION public.materialize_festival_edition_foundations(
  p_festival_company_id uuid,
  p_festival_edition_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  edition public.festival_editions_v2%ROWTYPE;
  configuration public.festival_configurations%ROWTYPE;
  scale public.festival_scale_catalogue%ROWTYPE;
  city public.cities%ROWTYPE;
  site public.festival_site_plans%ROWTYPE;
  ticket public.festival_ticket_plans%ROWTYPE;
  product_id uuid;
  stage_count integer;
  stage_index integer;
  stage_capacity integer;
  main_capacity integer;
  remaining_capacity integer;
  reserve_capacity integer;
  ticket_price_minor bigint;
  expected_sell_through integer;
  expected_sold bigint;
  currency text;
  demand_basis_points integer;
  facilities jsonb;
  projection_forecast jsonb;
BEGIN
  SELECT * INTO edition
  FROM public.festival_editions_v2
  WHERE id = p_festival_edition_id
    AND festival_company_id = p_festival_company_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'festival_edition_not_found' USING ERRCODE = 'P0001';
  END IF;

  IF edition.starts_on IS NULL
     OR edition.ends_on IS NULL
     OR edition.city_id IS NULL
     OR edition.site_type IS NULL
     OR edition.festival_scale IS NULL
     OR coalesce(edition.expected_capacity, 0) <= 0 THEN
    RETURN jsonb_build_object(
      'materialized', false,
      'reason', 'annual_plan_incomplete',
      'festivalEditionId', edition.id
    );
  END IF;

  SELECT * INTO configuration
  FROM public.festival_configurations
  WHERE festival_company_id = p_festival_company_id
  ORDER BY (festival_edition_id = p_festival_edition_id) DESC, created_at
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'festival_configuration_incomplete' USING ERRCODE = 'P0001';
  END IF;

  SELECT * INTO scale
  FROM public.festival_scale_catalogue
  WHERE key = edition.festival_scale;
  SELECT * INTO city
  FROM public.cities
  WHERE id = edition.city_id;

  IF scale.key IS NULL OR city.id IS NULL THEN
    RAISE EXCEPTION 'festival_annual_plan_invalid' USING ERRCODE = 'P0001';
  END IF;

  reserve_capacity := greatest(1, round(edition.expected_capacity * 0.03)::integer);
  facilities := jsonb_build_object(
    'toiletsRequired', ceil(edition.expected_capacity / 75.0)::integer,
    'medicalPointsRequired', greatest(1, ceil(edition.expected_capacity / 5000.0)::integer),
    'securityPositionsRequired', greatest(2, ceil(edition.expected_capacity / 250.0)::integer),
    'barsRecommended', greatest(1, ceil(edition.expected_capacity / 1000.0)::integer),
    'foodVendorSpacesRecommended', greatest(1, ceil(edition.expected_capacity / 750.0)::integer),
    'waterPointsRequired', greatest(1, ceil(edition.expected_capacity / 1000.0)::integer),
    'accessibleViewingRequired', greatest(1, ceil(edition.expected_capacity / 100.0)::integer),
    'backstageZonesRequired', greatest(1, scale.minimum_stages),
    'parkingRequirement', CASE WHEN edition.site_type = 'indoor' THEN 0 ELSE ceil(edition.expected_capacity / 5.0)::integer END,
    'transportRequirement', greatest(1, ceil(edition.expected_capacity / 2500.0)::integer)
  );

  INSERT INTO public.festival_site_plans(
    festival_company_id,
    festival_edition_id,
    configuration_id,
    site_source,
    existing_venue_id,
    site_name,
    site_type,
    site_description,
    city_id,
    timezone,
    total_capacity,
    usable_capacity,
    reserved_capacity,
    minimum_age,
    curfew_time,
    gates_open_time,
    daily_open_time,
    daily_close_time,
    accessibility_notes,
    transport_notes,
    weather_exposure,
    ground_condition,
    facility_recommendations,
    validation_issues,
    status,
    planning_version,
    completed_at,
    projection_source
  ) VALUES (
    edition.festival_company_id,
    edition.id,
    configuration.id,
    CASE edition.site_type
      WHEN 'outdoor' THEN 'open_land'
      WHEN 'mixed' THEN 'mixed_site'
      ELSE 'temporary_site'
    END,
    NULL,
    left(edition.name || ' generated site', 120),
    edition.site_type,
    'Generated from the annual Festival plan, licence and permanent company upgrades.',
    edition.city_id,
    city.timezone,
    edition.expected_capacity + reserve_capacity,
    edition.expected_capacity,
    reserve_capacity,
    NULL,
    time '23:00',
    time '10:00',
    time '10:00',
    time '23:00',
    'Accessibility capacity and routes are generated from company upgrades.',
    'Transport demand is generated from capacity and city choice.',
    CASE edition.site_type WHEN 'indoor' THEN 'protected' ELSE 'exposed' END,
    CASE edition.site_type WHEN 'indoor' THEN 'fixed' ELSE 'temporary' END,
    facilities,
    '[]'::jsonb,
    'ready_for_ticketing',
    1,
    now(),
    'annual_plan'
  )
  ON CONFLICT (festival_edition_id) WHERE festival_edition_id IS NOT NULL
  DO UPDATE SET
    configuration_id = EXCLUDED.configuration_id,
    site_source = EXCLUDED.site_source,
    site_name = EXCLUDED.site_name,
    site_type = EXCLUDED.site_type,
    site_description = EXCLUDED.site_description,
    city_id = EXCLUDED.city_id,
    timezone = EXCLUDED.timezone,
    total_capacity = EXCLUDED.total_capacity,
    usable_capacity = EXCLUDED.usable_capacity,
    reserved_capacity = EXCLUDED.reserved_capacity,
    curfew_time = EXCLUDED.curfew_time,
    gates_open_time = EXCLUDED.gates_open_time,
    daily_open_time = EXCLUDED.daily_open_time,
    daily_close_time = EXCLUDED.daily_close_time,
    facility_recommendations = EXCLUDED.facility_recommendations,
    validation_issues = '[]'::jsonb,
    status = 'ready_for_ticketing',
    planning_version = public.festival_site_plans.planning_version + 1,
    updated_at = now(),
    completed_at = now()
  WHERE public.festival_site_plans.projection_source = 'annual_plan'
  RETURNING * INTO site;

  IF site.id IS NULL THEN
    SELECT * INTO site
    FROM public.festival_site_plans
    WHERE festival_edition_id = edition.id;
  END IF;

  IF site.projection_source = 'annual_plan' THEN
    DELETE FROM public.festival_site_plan_stages
    WHERE festival_site_plan_id = site.id
      AND projection_source = 'annual_plan';

    stage_count := least(scale.maximum_stages, greatest(1, scale.minimum_stages));
    main_capacity := CASE
      WHEN stage_count = 1 THEN edition.expected_capacity
      ELSE least(
        scale.maximum_main_stage_capacity,
        greatest(1, round(edition.expected_capacity * 0.65)::integer)
      )
    END;
    remaining_capacity := greatest(0, edition.expected_capacity - main_capacity);

    FOR stage_index IN 1..stage_count LOOP
      stage_capacity := CASE
        WHEN stage_index = 1 THEN main_capacity
        ELSE greatest(1, floor(remaining_capacity::numeric / (stage_count - 1))::integer)
      END;

      INSERT INTO public.festival_site_plan_stages(
        festival_site_plan_id,
        festival_company_id,
        name,
        slug,
        stage_type,
        sort_order,
        capacity,
        minimum_artist_fame,
        performance_area_quality,
        sound_quality,
        lighting_quality,
        production_complexity,
        indoor,
        covered,
        accessible_viewing_capacity,
        opens_at,
        closes_at,
        changeover_minutes,
        headline_slot_minutes,
        standard_slot_minutes,
        status,
        projection_source
      ) VALUES (
        site.id,
        edition.festival_company_id,
        CASE stage_index
          WHEN 1 THEN 'Main Stage'
          WHEN 2 THEN 'Discovery Stage'
          WHEN 3 THEN 'Emerging Stage'
          ELSE 'Stage ' || stage_index::text
        END,
        CASE stage_index
          WHEN 1 THEN 'main-stage'
          WHEN 2 THEN 'discovery-stage'
          WHEN 3 THEN 'emerging-stage'
          ELSE 'stage-' || stage_index::text
        END,
        CASE stage_index
          WHEN 1 THEN 'main'
          WHEN 2 THEN 'secondary'
          WHEN 3 THEN 'emerging'
          ELSE 'specialist'
        END,
        stage_index - 1,
        stage_capacity,
        CASE WHEN stage_index = 1 THEN 100 ELSE NULL END,
        50,
        50,
        50,
        CASE WHEN stage_index = 1 THEN 'headline' ELSE 'standard' END,
        edition.site_type = 'indoor',
        edition.site_type <> 'outdoor',
        least(stage_capacity, greatest(1, round(stage_capacity * 0.02)::integer)),
        time '12:00',
        time '23:00',
        CASE WHEN stage_index = 1 THEN 30 ELSE 20 END,
        CASE WHEN stage_index = 1 THEN 90 ELSE 60 END,
        CASE WHEN stage_index = 1 THEN 60 ELSE 45 END,
        'ready',
        'annual_plan'
      );
    END LOOP;
  END IF;

  currency := coalesce(public._festival_projection_currency(edition.city_id), 'GBP');
  demand_basis_points := coalesce(
    nullif(edition.planning_effects->>'marketingDemandBasisPoints', '')::integer,
    10000
  );
  expected_sell_through := least(
    9500,
    greatest(5000, 8000 + ((demand_basis_points - 10000) / 2))
  );
  ticket_price_minor := greatest(
    1000,
    round(
      greatest(1, edition.estimated_operating_cost_minor)::numeric
      / greatest(1, edition.expected_capacity)
      * 1.25
    )::bigint
  );

  INSERT INTO public.festival_ticket_plans(
    festival_company_id,
    festival_edition_id,
    festival_site_plan_id,
    currency_code,
    sales_tax_rate_basis_points,
    booking_fee_mode,
    booking_fee_minor,
    booking_fee_basis_points,
    booking_fee_payer,
    refund_policy,
    transfer_policy,
    minimum_purchase_quantity,
    maximum_purchase_quantity,
    expected_sell_through_basis_points,
    expected_refund_basis_points,
    expected_complimentary_use_basis_points,
    expected_no_show_basis_points,
    validation_issues,
    forecast,
    status,
    planning_version,
    completed_at,
    projection_source
  ) VALUES (
    edition.festival_company_id,
    edition.id,
    site.id,
    currency,
    2000,
    'none',
    0,
    0,
    'customer',
    'Standard Festival refund policy',
    'Tickets may be transferred before the Festival starts.',
    1,
    8,
    expected_sell_through,
    300,
    0,
    500,
    '[]'::jsonb,
    '{}'::jsonb,
    'ready_for_artist_planning',
    1,
    now(),
    'annual_plan'
  )
  ON CONFLICT (festival_edition_id) WHERE festival_edition_id IS NOT NULL
  DO UPDATE SET
    festival_site_plan_id = EXCLUDED.festival_site_plan_id,
    currency_code = EXCLUDED.currency_code,
    expected_sell_through_basis_points = EXCLUDED.expected_sell_through_basis_points,
    validation_issues = '[]'::jsonb,
    status = 'ready_for_artist_planning',
    planning_version = public.festival_ticket_plans.planning_version + 1,
    updated_at = now(),
    completed_at = now()
  WHERE public.festival_ticket_plans.projection_source = 'annual_plan'
  RETURNING * INTO ticket;

  IF ticket.id IS NULL THEN
    SELECT * INTO ticket
    FROM public.festival_ticket_plans
    WHERE festival_edition_id = edition.id;
  END IF;

  IF ticket.projection_source = 'annual_plan' THEN
    INSERT INTO public.festival_ticket_products(
      festival_ticket_plan_id,
      festival_company_id,
      name,
      slug,
      ticket_type,
      product_class,
      access_scope,
      valid_from_date,
      valid_to_date,
      price_minor,
      face_value_minor,
      capacity_limit,
      minimum_age,
      includes_camping,
      includes_parking,
      includes_vip_area,
      includes_backstage,
      transferable,
      refundable,
      sale_priority,
      active
    ) VALUES (
      ticket.id,
      edition.festival_company_id,
      'Standard Festival Ticket',
      'standard-festival-ticket',
      'full_festival',
      'admission',
      'full_festival',
      edition.starts_on,
      edition.ends_on,
      ticket_price_minor,
      ticket_price_minor,
      edition.expected_capacity,
      NULL,
      false,
      false,
      false,
      false,
      true,
      false,
      0,
      true
    )
    ON CONFLICT (festival_ticket_plan_id, slug)
    DO UPDATE SET
      valid_from_date = EXCLUDED.valid_from_date,
      valid_to_date = EXCLUDED.valid_to_date,
      capacity_limit = least(
        public.festival_ticket_products.capacity_limit,
        edition.expected_capacity
      ),
      updated_at = now()
    RETURNING id, price_minor INTO product_id, ticket_price_minor;

    INSERT INTO public.festival_ticket_release_phases(
      festival_ticket_plan_id,
      festival_ticket_product_id,
      name,
      release_type,
      sort_order,
      starts_at,
      ends_at,
      allocation_limit,
      price_override_minor,
      discount_basis_points,
      eligibility_rule,
      status
    ) VALUES (
      ticket.id,
      product_id,
      'General sale',
      'general_sale',
      0,
      NULL,
      NULL,
      edition.expected_capacity,
      NULL,
      0,
      NULL,
      'planned'
    )
    ON CONFLICT (festival_ticket_plan_id, festival_ticket_product_id, name)
    DO UPDATE SET
      allocation_limit = EXCLUDED.allocation_limit,
      updated_at = now();

    INSERT INTO public.festival_ticket_capacity_allocations(
      festival_ticket_plan_id,
      festival_ticket_product_id,
      festival_date,
      capacity_allocated,
      capacity_reserved,
      capacity_complimentary
    )
    SELECT
      ticket.id,
      product_id,
      day::date,
      edition.expected_capacity,
      0,
      0
    FROM generate_series(edition.starts_on, edition.ends_on, interval '1 day') day
    ON CONFLICT (festival_ticket_plan_id, festival_ticket_product_id, festival_date)
    DO UPDATE SET
      capacity_allocated = EXCLUDED.capacity_allocated,
      capacity_reserved = EXCLUDED.capacity_reserved,
      capacity_complimentary = EXCLUDED.capacity_complimentary,
      updated_at = now();

    projection_forecast := public._festival_projection_forecast(
      edition.starts_on,
      edition.ends_on,
      edition.expected_capacity,
      ticket_price_minor,
      ticket.expected_sell_through_basis_points,
      ticket.sales_tax_rate_basis_points,
      ticket.expected_refund_basis_points
    );
    UPDATE public.festival_ticket_plans
    SET forecast = projection_forecast,
        updated_at = now()
    WHERE id = ticket.id
    RETURNING * INTO ticket;
  END IF;

  RETURN jsonb_build_object(
    'materialized', true,
    'festivalEditionId', edition.id,
    'sitePlanId', site.id,
    'ticketPlanId', ticket.id,
    'siteProjectionSource', site.projection_source,
    'ticketProjectionSource', ticket.projection_source
  );
END;
$$;

CREATE OR REPLACE FUNCTION public._festival_edition_foundation_trigger()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.status NOT IN ('cancelled', 'completed')
     AND NEW.locked_at IS NULL
     AND NEW.starts_on IS NOT NULL
     AND NEW.ends_on IS NOT NULL
     AND NEW.city_id IS NOT NULL
     AND NEW.site_type IS NOT NULL
     AND NEW.festival_scale IS NOT NULL
     AND coalesce(NEW.expected_capacity, 0) > 0 THEN
    PERFORM public.materialize_festival_edition_foundations(
      NEW.festival_company_id,
      NEW.id
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS festival_edition_foundation_projection
  ON public.festival_editions_v2;
CREATE TRIGGER festival_edition_foundation_projection
AFTER INSERT OR UPDATE OF
  starts_on,
  ends_on,
  city_id,
  site_type,
  festival_scale,
  expected_capacity,
  estimated_operating_cost_minor,
  planning_effects,
  status,
  locked_at
ON public.festival_editions_v2
FOR EACH ROW
EXECUTE FUNCTION public._festival_edition_foundation_trigger();

CREATE OR REPLACE FUNCTION public._festival_edition_site_plan_result(
  p_festival_company_id uuid,
  p_festival_edition_id uuid
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'festivalCompanyId', company.id,
    'festivalName', edition.name,
    'configurationStatus', 'ready_for_planning',
    'sitePlan', CASE WHEN site.id IS NULL THEN NULL ELSE jsonb_build_object(
      'id', site.id,
      'siteSource', site.site_source,
      'existingVenueId', site.existing_venue_id,
      'siteName', site.site_name,
      'siteType', site.site_type,
      'siteDescription', coalesce(site.site_description, ''),
      'cityId', site.city_id,
      'timezone', site.timezone,
      'totalCapacity', site.total_capacity,
      'usableCapacity', site.usable_capacity,
      'reservedCapacity', site.reserved_capacity,
      'minimumAge', site.minimum_age,
      'curfewTime', site.curfew_time,
      'gatesOpenTime', site.gates_open_time,
      'dailyOpenTime', site.daily_open_time,
      'dailyCloseTime', site.daily_close_time,
      'accessibilityNotes', coalesce(site.accessibility_notes, ''),
      'transportNotes', coalesce(site.transport_notes, ''),
      'weatherExposure', coalesce(site.weather_exposure, ''),
      'groundCondition', coalesce(site.ground_condition, ''),
      'status', site.status
    ) END,
    'venueOptions', '[]'::jsonb,
    'scaleLimits', jsonb_build_object(
      'minimumSiteCapacity', scale.minimum_site_capacity,
      'maximumSiteCapacity', scale.maximum_site_capacity,
      'minimumStages', scale.minimum_stages,
      'maximumStages', scale.maximum_stages,
      'maximumMainStageCapacity', scale.maximum_main_stage_capacity,
      'maximumTotalStageCapacity', scale.maximum_total_stage_capacity,
      'requiresSecondaryStage', scale.requires_secondary_stage,
      'requiresAccessibilityPlan', scale.requires_accessibility_plan
    ),
    'stages', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', stage.id,
        'name', stage.name,
        'slug', stage.slug,
        'stageType', stage.stage_type,
        'sortOrder', stage.sort_order,
        'capacity', stage.capacity,
        'minimumArtistFame', stage.minimum_artist_fame,
        'performanceAreaQuality', stage.performance_area_quality,
        'soundQuality', stage.sound_quality,
        'lightingQuality', stage.lighting_quality,
        'productionComplexity', stage.production_complexity,
        'indoor', stage.indoor,
        'covered', stage.covered,
        'accessibleViewingCapacity', stage.accessible_viewing_capacity,
        'opensAt', stage.opens_at,
        'closesAt', stage.closes_at,
        'changeoverMinutes', stage.changeover_minutes,
        'headlineSlotMinutes', stage.headline_slot_minutes,
        'standardSlotMinutes', stage.standard_slot_minutes,
        'status', stage.status
      ) ORDER BY stage.sort_order)
      FROM public.festival_site_plan_stages stage
      WHERE stage.festival_site_plan_id = site.id
    ), '[]'::jsonb),
    'facilities', coalesce(site.facility_recommendations, '{}'::jsonb),
    'issues', coalesce(site.validation_issues, '[]'::jsonb),
    'ready', coalesce(site.status = 'ready_for_ticketing', false),
    'canWrite', edition.status NOT IN ('completed', 'cancelled') AND edition.locked_at IS NULL,
    'planningVersion', coalesce(site.planning_version, 0),
    'updatedAt', site.updated_at,
    'capacityMetrics', jsonb_build_object(
      'largestStageCapacity', coalesce((SELECT max(capacity) FROM public.festival_site_plan_stages WHERE festival_site_plan_id = site.id), 0),
      'totalStageCapacity', coalesce((SELECT sum(capacity) FROM public.festival_site_plan_stages WHERE festival_site_plan_id = site.id), 0),
      'mainStageShare', coalesce((SELECT round(100.0 * capacity / nullif(site.usable_capacity, 0)) FROM public.festival_site_plan_stages WHERE festival_site_plan_id = site.id AND stage_type = 'main'), 0),
      'accessibleViewingTotal', coalesce((SELECT sum(accessible_viewing_capacity) FROM public.festival_site_plan_stages WHERE festival_site_plan_id = site.id), 0),
      'peakCrowdConcentration', coalesce((SELECT round(100.0 * max(capacity) / nullif(site.usable_capacity, 0)) FROM public.festival_site_plan_stages WHERE festival_site_plan_id = site.id), 0)
    )
  )
  FROM public.festival_companies company
  JOIN public.festival_editions_v2 edition
    ON edition.festival_company_id = company.id
   AND edition.id = p_festival_edition_id
  JOIN public.festival_scale_catalogue scale
    ON scale.key = edition.festival_scale
  LEFT JOIN public.festival_site_plans site
    ON site.festival_edition_id = edition.id
  WHERE company.id = p_festival_company_id
$$;

CREATE OR REPLACE FUNCTION public.get_festival_edition_site_plan(
  p_festival_company_id uuid,
  p_festival_edition_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid := public._caller_profile_id();
BEGIN
  IF auth.uid() IS NULL
     OR actor IS NULL
     OR NOT public._festival_projection_authorized(
       p_festival_company_id,
       p_festival_edition_id,
       actor
     ) THEN
    RAISE EXCEPTION 'festival_site_plan_forbidden' USING ERRCODE = 'P0001';
  END IF;
  RETURN public._festival_edition_site_plan_result(
    p_festival_company_id,
    p_festival_edition_id
  );
END;
$$;

CREATE OR REPLACE FUNCTION public._festival_edition_ticket_plan_result(
  p_festival_company_id uuid,
  p_festival_edition_id uuid
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'festivalCompanyId', company.id,
    'festivalName', edition.name,
    'festivalDates', (
      SELECT coalesce(jsonb_agg(day::date ORDER BY day), '[]'::jsonb)
      FROM generate_series(edition.starts_on, edition.ends_on, interval '1 day') day
    ),
    'usableSiteCapacity', site.usable_capacity,
    'sitePlanStatus', site.status,
    'ticketPlan', CASE WHEN ticket.id IS NULL THEN NULL ELSE jsonb_build_object(
      'id', ticket.id,
      'currencyCode', ticket.currency_code,
      'salesTaxRateBasisPoints', ticket.sales_tax_rate_basis_points,
      'bookingFeeMode', ticket.booking_fee_mode,
      'bookingFeeMinor', ticket.booking_fee_minor,
      'bookingFeeBasisPoints', ticket.booking_fee_basis_points,
      'bookingFeePayer', ticket.booking_fee_payer,
      'refundPolicy', coalesce(ticket.refund_policy, ''),
      'transferPolicy', coalesce(ticket.transfer_policy, ''),
      'minimumPurchaseQuantity', ticket.minimum_purchase_quantity,
      'maximumPurchaseQuantity', ticket.maximum_purchase_quantity,
      'expectedSellThroughBasisPoints', ticket.expected_sell_through_basis_points,
      'expectedRefundBasisPoints', ticket.expected_refund_basis_points,
      'expectedComplimentaryUseBasisPoints', ticket.expected_complimentary_use_basis_points,
      'expectedNoShowBasisPoints', ticket.expected_no_show_basis_points,
      'status', ticket.status
    ) END,
    'products', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', product.id,
        'name', product.name,
        'slug', product.slug,
        'ticketType', product.ticket_type,
        'productClass', product.product_class,
        'accessScope', product.access_scope,
        'validFromDate', product.valid_from_date,
        'validToDate', product.valid_to_date,
        'priceMinor', product.price_minor,
        'faceValueMinor', product.face_value_minor,
        'capacityLimit', product.capacity_limit,
        'minimumAge', product.minimum_age,
        'includesCamping', product.includes_camping,
        'includesParking', product.includes_parking,
        'includesVipArea', product.includes_vip_area,
        'includesBackstage', product.includes_backstage,
        'transferable', product.transferable,
        'refundable', product.refundable,
        'salePriority', product.sale_priority,
        'active', product.active
      ) ORDER BY product.sale_priority)
      FROM public.festival_ticket_products product
      WHERE product.festival_ticket_plan_id = ticket.id
    ), '[]'::jsonb),
    'releasePhases', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', phase.id,
        'productId', phase.festival_ticket_product_id,
        'name', phase.name,
        'releaseType', phase.release_type,
        'sortOrder', phase.sort_order,
        'startsAt', phase.starts_at,
        'endsAt', phase.ends_at,
        'allocationLimit', phase.allocation_limit,
        'priceOverrideMinor', phase.price_override_minor,
        'discountBasisPoints', phase.discount_basis_points,
        'eligibilityRule', coalesce(phase.eligibility_rule, ''),
        'status', phase.status
      ) ORDER BY phase.sort_order)
      FROM public.festival_ticket_release_phases phase
      WHERE phase.festival_ticket_plan_id = ticket.id
    ), '[]'::jsonb),
    'capacityAllocations', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', allocation.id,
        'productId', allocation.festival_ticket_product_id,
        'productSlug', product.slug,
        'festivalDate', allocation.festival_date,
        'capacityAllocated', allocation.capacity_allocated,
        'capacityReserved', allocation.capacity_reserved,
        'capacityComplimentary', allocation.capacity_complimentary
      ) ORDER BY allocation.festival_date, product.sale_priority)
      FROM public.festival_ticket_capacity_allocations allocation
      JOIN public.festival_ticket_products product
        ON product.id = allocation.festival_ticket_product_id
      WHERE allocation.festival_ticket_plan_id = ticket.id
    ), '[]'::jsonb),
    'forecast', coalesce(ticket.forecast, '{}'::jsonb),
    'issues', coalesce(ticket.validation_issues, '[]'::jsonb),
    'warnings', '[]'::jsonb,
    'ready', coalesce(ticket.status = 'ready_for_artist_planning', false),
    'canWrite', edition.status NOT IN ('completed', 'cancelled') AND edition.locked_at IS NULL,
    'planningVersion', coalesce(ticket.planning_version, 0),
    'updatedAt', ticket.updated_at
  )
  FROM public.festival_companies company
  JOIN public.festival_editions_v2 edition
    ON edition.festival_company_id = company.id
   AND edition.id = p_festival_edition_id
  JOIN public.festival_site_plans site
    ON site.festival_edition_id = edition.id
  LEFT JOIN public.festival_ticket_plans ticket
    ON ticket.festival_edition_id = edition.id
  WHERE company.id = p_festival_company_id
$$;

CREATE OR REPLACE FUNCTION public.get_festival_edition_ticket_plan(
  p_festival_company_id uuid,
  p_festival_edition_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid := public._caller_profile_id();
BEGIN
  IF auth.uid() IS NULL
     OR actor IS NULL
     OR NOT public._festival_projection_authorized(
       p_festival_company_id,
       p_festival_edition_id,
       actor
     ) THEN
    RAISE EXCEPTION 'festival_ticket_plan_forbidden' USING ERRCODE = 'P0001';
  END IF;
  RETURN public._festival_edition_ticket_plan_result(
    p_festival_company_id,
    p_festival_edition_id
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.save_festival_edition_ticket_plan(
  p_festival_company_id uuid,
  p_festival_edition_id uuid,
  p_expected_version integer,
  p_ticket_plan jsonb,
  p_products jsonb,
  p_release_phases jsonb,
  p_capacity_allocations jsonb,
  p_idempotency_key uuid,
  p_complete boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid := public._caller_profile_id();
  edition public.festival_editions_v2%ROWTYPE;
  site public.festival_site_plans%ROWTYPE;
  ticket public.festival_ticket_plans%ROWTYPE;
  request public.festival_ticket_plan_requests%ROWTYPE;
  admission jsonb;
  product_id uuid;
  payload_hash text;
  response jsonb;
  price_minor bigint;
  capacity integer;
  sell_through integer;
  projection_forecast jsonb;
BEGIN
  IF auth.uid() IS NULL
     OR actor IS NULL
     OR NOT public._festival_projection_authorized(
       p_festival_company_id,
       p_festival_edition_id,
       actor
     ) THEN
    RAISE EXCEPTION 'festival_ticket_plan_forbidden' USING ERRCODE = 'P0001';
  END IF;

  SELECT * INTO edition
  FROM public.festival_editions_v2
  WHERE id = p_festival_edition_id
    AND festival_company_id = p_festival_company_id
  FOR UPDATE;
  IF edition.status IN ('completed', 'cancelled') OR edition.locked_at IS NOT NULL THEN
    RAISE EXCEPTION 'festival_ticket_plan_locked' USING ERRCODE = 'P0001';
  END IF;

  PERFORM public.materialize_festival_edition_foundations(
    p_festival_company_id,
    p_festival_edition_id
  );

  SELECT * INTO site
  FROM public.festival_site_plans
  WHERE festival_edition_id = edition.id;
  SELECT * INTO ticket
  FROM public.festival_ticket_plans
  WHERE festival_edition_id = edition.id
  FOR UPDATE;

  IF site.id IS NULL OR ticket.id IS NULL OR site.status <> 'ready_for_ticketing' THEN
    RAISE EXCEPTION 'festival_site_plan_incomplete' USING ERRCODE = 'P0001';
  END IF;

  SELECT value INTO admission
  FROM jsonb_array_elements(coalesce(p_products, '[]'::jsonb)) value
  WHERE value->>'productClass' = 'admission'
    AND coalesce((value->>'active')::boolean, true)
  ORDER BY coalesce((value->>'salePriority')::integer, 0)
  LIMIT 1;

  IF admission IS NULL THEN
    RAISE EXCEPTION 'festival_ticket_product_required' USING ERRCODE = 'P0001';
  END IF;

  price_minor := nullif(admission->>'priceMinor', '')::bigint;
  capacity := nullif(admission->>'capacityLimit', '')::integer;
  sell_through := nullif(p_ticket_plan->>'expectedSellThroughBasisPoints', '')::integer;

  IF price_minor IS NULL OR price_minor < 0
     OR capacity IS NULL OR capacity <= 0 OR capacity > site.usable_capacity
     OR sell_through IS NULL OR sell_through NOT BETWEEN 0 AND 10000 THEN
    RAISE EXCEPTION 'festival_ticket_plan_invalid' USING ERRCODE = 'P0001';
  END IF;

  payload_hash := encode(digest(jsonb_build_object(
    'festivalEditionId', edition.id,
    'expectedVersion', p_expected_version,
    'priceMinor', price_minor,
    'capacity', capacity,
    'sellThrough', sell_through,
    'complete', p_complete
  )::text, 'sha256'), 'hex');

  PERFORM pg_advisory_xact_lock(
    hashtextextended(edition.id::text || p_idempotency_key::text, 0)
  );
  SELECT * INTO request
  FROM public.festival_ticket_plan_requests
  WHERE festival_company_id = p_festival_company_id
    AND caller_profile_id = actor
    AND idempotency_key = p_idempotency_key
  FOR UPDATE;

  IF FOUND THEN
    IF request.payload_hash <> payload_hash THEN
      RAISE EXCEPTION 'festival_ticket_plan_idempotency_conflict' USING ERRCODE = 'P0001';
    END IF;
    IF request.status = 'succeeded' THEN
      RETURN request.result;
    END IF;
  ELSE
    INSERT INTO public.festival_ticket_plan_requests(
      festival_company_id,
      caller_profile_id,
      idempotency_key,
      payload_hash
    ) VALUES (
      p_festival_company_id,
      actor,
      p_idempotency_key,
      payload_hash
    ) RETURNING * INTO request;
  END IF;

  IF ticket.planning_version <> p_expected_version THEN
  RAISE EXCEPTION 'festival_ticket_plan_stale' USING ERRCODE = 'P0001';
END IF;

  UPDATE public.festival_ticket_plans
  SET expected_sell_through_basis_points = sell_through,
      status = 'ready_for_artist_planning',
      validation_issues = '[]'::jsonb,
      planning_version = planning_version + 1,
      completed_at = CASE WHEN p_complete THEN now() ELSE completed_at END,
      updated_at = now()
  WHERE id = ticket.id
  RETURNING * INTO ticket;

  INSERT INTO public.festival_ticket_products(
    festival_ticket_plan_id,
    festival_company_id,
    name,
    slug,
    ticket_type,
    product_class,
    access_scope,
    valid_from_date,
    valid_to_date,
    price_minor,
    face_value_minor,
    capacity_limit,
    minimum_age,
    includes_camping,
    includes_parking,
    includes_vip_area,
    includes_backstage,
    transferable,
    refundable,
    sale_priority,
    active
  ) VALUES (
    ticket.id,
    edition.festival_company_id,
    'Standard Festival Ticket',
    'standard-festival-ticket',
    'full_festival',
    'admission',
    'full_festival',
    edition.starts_on,
    edition.ends_on,
    price_minor,
    price_minor,
    capacity,
    NULL,
    false,
    false,
    false,
    false,
    true,
    false,
    0,
    true
  )
  ON CONFLICT (festival_ticket_plan_id, slug)
  DO UPDATE SET
    valid_from_date = EXCLUDED.valid_from_date,
    valid_to_date = EXCLUDED.valid_to_date,
    price_minor = EXCLUDED.price_minor,
    face_value_minor = EXCLUDED.face_value_minor,
    capacity_limit = EXCLUDED.capacity_limit,
    active = true,
    updated_at = now()
  RETURNING id INTO product_id;

  DELETE FROM public.festival_ticket_capacity_allocations
  WHERE festival_ticket_plan_id = ticket.id
    AND festival_ticket_product_id = product_id;
  INSERT INTO public.festival_ticket_capacity_allocations(
    festival_ticket_plan_id,
    festival_ticket_product_id,
    festival_date,
    capacity_allocated,
    capacity_reserved,
    capacity_complimentary
  )
  SELECT ticket.id, product_id, day::date, capacity, 0, 0
  FROM generate_series(edition.starts_on, edition.ends_on, interval '1 day') day;

  projection_forecast := public._festival_projection_forecast(
    edition.starts_on,
    edition.ends_on,
    capacity,
    price_minor,
    sell_through,
    ticket.sales_tax_rate_basis_points,
    ticket.expected_refund_basis_points
  );
  UPDATE public.festival_ticket_plans
  SET forecast = projection_forecast,
      updated_at = now()
  WHERE id = ticket.id;

  response := public._festival_edition_ticket_plan_result(
    p_festival_company_id,
    p_festival_edition_id
  );
  UPDATE public.festival_ticket_plan_requests
  SET status = 'succeeded', result = response, completed_at = now()
  WHERE id = request.id;
  RETURN response;
END;
$$;

CREATE OR REPLACE FUNCTION public._festival_edition_artist_programme_result(
  p_festival_company_id uuid,
  p_festival_edition_id uuid
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'festivalCompanyId', company.id,
    'festivalName', edition.name,
    'festivalDates', (
      SELECT coalesce(jsonb_agg(day::date ORDER BY day), '[]'::jsonb)
      FROM generate_series(edition.starts_on, edition.ends_on, interval '1 day') day
    ),
    'stages', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', stage.id,
        'name', stage.name,
        'stageType', stage.stage_type,
        'capacity', stage.capacity,
        'active', stage.status = 'ready'
      ) ORDER BY stage.sort_order)
      FROM public.festival_site_plan_stages stage
      WHERE stage.festival_site_plan_id = site.id
    ), '[]'::jsonb),
    'programme', CASE WHEN programme.id IS NULL THEN NULL ELSE jsonb_build_object(
      'id', programme.id,
      'currencyCode', programme.currency_code,
      'applicationMode', programme.application_mode,
      'applicationsOpenAt', programme.applications_open_at,
      'applicationsCloseAt', programme.applications_close_at,
      'minimumArtistFame', programme.minimum_artist_fame,
      'maximumArtistFame', programme.maximum_artist_fame,
      'preferredGenres', programme.preferred_genres,
      'excludedGenres', programme.excluded_genres,
      'artistBudgetMinor', programme.artist_budget_minor,
      'contingencyBudgetMinor', programme.contingency_budget_minor,
      'minimumPlayerArtistShareBasisPoints', programme.minimum_player_artist_share_basis_points,
      'status', programme.status
    ) END,
    'applicationWindows', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', application_window.id,
        'name', application_window.name,
        'opensAt', application_window.opens_at,
        'closesAt', application_window.closes_at,
        'eligibleArtistType', application_window.eligible_artist_type,
        'minimumFame', application_window.minimum_fame,
        'maximumFame', application_window.maximum_fame,
        'preferredGenres', application_window.preferred_genres,
        'minimumBandMembers', application_window.minimum_band_members,
        'maximumBandMembers', application_window.maximum_band_members,
        'targetStageTypes', application_window.target_stage_types,
        'maximumSetMinutes', application_window.maximum_set_minutes,
        'active', application_window.active
      ) ORDER BY application_window.opens_at)
      FROM public.festival_artist_application_windows application_window
      WHERE application_window.festival_artist_programme_id = programme.id
    ), '[]'::jsonb),
    'applications', '[]'::jsonb,
    'invitations', '[]'::jsonb,
    'offers', '[]'::jsonb,
    'bookings', '[]'::jsonb,
    'budget', jsonb_build_object(
      'artistBudgetMinor', coalesce(programme.artist_budget_minor, 0),
      'contingencyBudgetMinor', coalesce(programme.contingency_budget_minor, 0),
      'draftOfferCommitmentsMinor', 0,
      'sentOfferCommitmentsMinor', 0,
      'acceptedCommitmentsMinor', 0,
      'remainingMinor', coalesce(programme.artist_budget_minor + programme.contingency_budget_minor, 0),
      'potentialApplicationRequestsMinor', 0,
      'headlineBudgetShareBasisPoints', 0,
      'playerArtistBudgetShareBasisPoints', 0,
      'npcArtistBudgetShareBasisPoints', 0
    ),
    'issues', '[]'::jsonb,
    'playerArtistCount', 0,
    'npcArtistCount', 0,
    'playerArtistShareBasisPoints', 0,
    'ready', coalesce(programme.status = 'ready_for_operations', false),
    'canWrite', edition.status NOT IN ('completed', 'cancelled') AND edition.locked_at IS NULL,
    'planningVersion', coalesce(programme.planning_version, 0),
    'updatedAt', programme.updated_at
  )
  FROM public.festival_companies company
  JOIN public.festival_editions_v2 edition
    ON edition.festival_company_id = company.id
   AND edition.id = p_festival_edition_id
  JOIN public.festival_site_plans site
    ON site.festival_edition_id = edition.id
  JOIN public.festival_ticket_plans ticket
    ON ticket.festival_edition_id = edition.id
  LEFT JOIN public.festival_artist_programmes programme
    ON programme.festival_edition_id = edition.id
  WHERE company.id = p_festival_company_id
$$;

CREATE OR REPLACE FUNCTION public.get_festival_edition_artist_programme(
  p_festival_company_id uuid,
  p_festival_edition_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid := public._caller_profile_id();
BEGIN
  IF auth.uid() IS NULL
     OR actor IS NULL
     OR NOT public._festival_projection_authorized(
       p_festival_company_id,
       p_festival_edition_id,
       actor
     ) THEN
    RAISE EXCEPTION 'festival_artist_programme_forbidden' USING ERRCODE = 'P0001';
  END IF;
  RETURN public._festival_edition_artist_programme_result(
    p_festival_company_id,
    p_festival_edition_id
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.save_festival_edition_artist_programme(
  p_festival_company_id uuid,
  p_festival_edition_id uuid,
  p_expected_version integer,
  p_programme jsonb,
  p_application_windows jsonb,
  p_idempotency_key uuid,
  p_complete boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid := public._caller_profile_id();
  edition public.festival_editions_v2%ROWTYPE;
  ticket public.festival_ticket_plans%ROWTYPE;
  programme public.festival_artist_programmes%ROWTYPE;
  request public.festival_artist_plan_requests%ROWTYPE;
  payload_hash text;
  application_mode text;
  artist_budget bigint;
  contingency_budget bigint;
  minimum_fame integer;
  maximum_fame integer;
  preferred_genres text[];
  excluded_genres text[];
  application_window_payload jsonb;
  response jsonb;
  old_version integer;
BEGIN
  IF auth.uid() IS NULL
     OR actor IS NULL
     OR NOT public._festival_projection_authorized(
       p_festival_company_id,
       p_festival_edition_id,
       actor
     ) THEN
    RAISE EXCEPTION 'festival_artist_programme_forbidden' USING ERRCODE = 'P0001';
  END IF;

  SELECT * INTO edition
  FROM public.festival_editions_v2
  WHERE id = p_festival_edition_id
    AND festival_company_id = p_festival_company_id
  FOR UPDATE;
  IF edition.status IN ('completed', 'cancelled') OR edition.locked_at IS NOT NULL THEN
    RAISE EXCEPTION 'festival_artist_programme_locked' USING ERRCODE = 'P0001';
  END IF;

  SELECT * INTO ticket
  FROM public.festival_ticket_plans
  WHERE festival_edition_id = edition.id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'festival_ticket_plan_incomplete' USING ERRCODE = 'P0001';
  END IF;

  application_mode := p_programme->>'applicationMode';
  artist_budget := coalesce(nullif(p_programme->>'artistBudgetMinor', '')::bigint, 0);
  contingency_budget := coalesce(nullif(p_programme->>'contingencyBudgetMinor', '')::bigint, 0);
  minimum_fame := nullif(p_programme->>'minimumArtistFame', '')::integer;
  maximum_fame := nullif(p_programme->>'maximumArtistFame', '')::integer;
  SELECT coalesce(array_agg(value), '{}'::text[]) INTO preferred_genres
  FROM jsonb_array_elements_text(coalesce(p_programme->'preferredGenres', '[]'::jsonb)) value;
  SELECT coalesce(array_agg(value), '{}'::text[]) INTO excluded_genres
  FROM jsonb_array_elements_text(coalesce(p_programme->'excludedGenres', '[]'::jsonb)) value;

  IF application_mode NOT IN ('closed', 'invite_only', 'applications_only', 'hybrid')
     OR artist_budget < 0
     OR contingency_budget < 0
     OR (maximum_fame IS NOT NULL AND minimum_fame IS NOT NULL AND maximum_fame < minimum_fame) THEN
    RAISE EXCEPTION 'festival_artist_programme_invalid' USING ERRCODE = 'P0001';
  END IF;

  payload_hash := encode(digest(jsonb_build_object(
    'festivalEditionId', edition.id,
    'expectedVersion', p_expected_version,
    'programme', p_programme,
    'applicationWindows', p_application_windows,
    'complete', p_complete
  )::text, 'sha256'), 'hex');
  PERFORM pg_advisory_xact_lock(
    hashtextextended(edition.id::text || p_idempotency_key::text, 0)
  );

  SELECT * INTO request
  FROM public.festival_artist_plan_requests
  WHERE caller_profile_id = actor
    AND target_entity_id = edition.id
    AND action = 'save_edition_programme'
    AND idempotency_key = p_idempotency_key
  FOR UPDATE;
  IF FOUND THEN
    IF request.payload_hash <> payload_hash THEN
      RAISE EXCEPTION 'festival_artist_idempotency_conflict' USING ERRCODE = 'P0001';
    END IF;
    IF request.status = 'succeeded' THEN
      RETURN request.result;
    END IF;
  ELSE
    INSERT INTO public.festival_artist_plan_requests(
      festival_company_id,
      caller_profile_id,
      target_entity_id,
      action,
      idempotency_key,
      payload_hash
    ) VALUES (
      edition.festival_company_id,
      actor,
      edition.id,
      'save_edition_programme',
      p_idempotency_key,
      payload_hash
    ) RETURNING * INTO request;
  END IF;

  SELECT coalesce(max(planning_version), 0) INTO old_version
FROM public.festival_artist_programmes
WHERE festival_edition_id = edition.id;
IF old_version <> p_expected_version THEN
  RAISE EXCEPTION 'festival_artist_programme_stale' USING ERRCODE = 'P0001';
END IF;

  INSERT INTO public.festival_artist_programmes(
    festival_company_id,
    festival_edition_id,
    festival_ticket_plan_id,
    currency_code,
    application_mode,
    applications_open_at,
    applications_close_at,
    minimum_artist_fame,
    maximum_artist_fame,
    preferred_genres,
    excluded_genres,
    artist_budget_minor,
    contingency_budget_minor,
    minimum_player_artist_share_basis_points,
    status,
    planning_version,
    completed_at
  ) VALUES (
    edition.festival_company_id,
    edition.id,
    ticket.id,
    ticket.currency_code,
    application_mode,
    nullif(p_programme->>'applicationsOpenAt', '')::timestamptz,
    nullif(p_programme->>'applicationsCloseAt', '')::timestamptz,
    minimum_fame,
    maximum_fame,
    preferred_genres,
    excluded_genres,
    artist_budget,
    contingency_budget,
    coalesce(nullif(p_programme->>'minimumPlayerArtistShareBasisPoints', '')::integer, 0),
    CASE WHEN p_complete THEN 'ready_for_operations' ELSE 'applications_configured' END,
    1,
    CASE WHEN p_complete THEN now() ELSE NULL END
  )
  ON CONFLICT (festival_edition_id) WHERE festival_edition_id IS NOT NULL
  DO UPDATE SET
    festival_ticket_plan_id = EXCLUDED.festival_ticket_plan_id,
    currency_code = EXCLUDED.currency_code,
    application_mode = EXCLUDED.application_mode,
    applications_open_at = EXCLUDED.applications_open_at,
    applications_close_at = EXCLUDED.applications_close_at,
    minimum_artist_fame = EXCLUDED.minimum_artist_fame,
    maximum_artist_fame = EXCLUDED.maximum_artist_fame,
    preferred_genres = EXCLUDED.preferred_genres,
    excluded_genres = EXCLUDED.excluded_genres,
    artist_budget_minor = EXCLUDED.artist_budget_minor,
    contingency_budget_minor = EXCLUDED.contingency_budget_minor,
    minimum_player_artist_share_basis_points = EXCLUDED.minimum_player_artist_share_basis_points,
    status = EXCLUDED.status,
    planning_version = public.festival_artist_programmes.planning_version + 1,
    updated_at = now(),
    completed_at = EXCLUDED.completed_at
  RETURNING * INTO programme;

  IF application_mode IN ('applications_only', 'hybrid')
     AND jsonb_array_length(coalesce(p_application_windows, '[]'::jsonb)) > 0 THEN
    application_window_payload := p_application_windows->0;
    INSERT INTO public.festival_artist_application_windows(
      festival_artist_programme_id,
      name,
      opens_at,
      closes_at,
      eligible_artist_type,
      minimum_fame,
      maximum_fame,
      preferred_genres,
      minimum_band_members,
      maximum_band_members,
      target_stage_types,
      maximum_set_minutes,
      active
    ) VALUES (
      programme.id,
      coalesce(nullif(btrim(application_window_payload->>'name'), ''), 'General Festival applications'),
      (application_window_payload->>'opensAt')::timestamptz,
      (application_window_payload->>'closesAt')::timestamptz,
      coalesce(application_window_payload->>'eligibleArtistType', 'player_only'),
      nullif(application_window_payload->>'minimumFame', '')::integer,
      nullif(application_window_payload->>'maximumFame', '')::integer,
      ARRAY(SELECT jsonb_array_elements_text(coalesce(application_window_payload->'preferredGenres', '[]'::jsonb))),
      nullif(application_window_payload->>'minimumBandMembers', '')::integer,
      nullif(application_window_payload->>'maximumBandMembers', '')::integer,
      ARRAY(SELECT jsonb_array_elements_text(coalesce(application_window_payload->'targetStageTypes', '[]'::jsonb))),
      coalesce(nullif(application_window_payload->>'maximumSetMinutes', '')::integer, 60),
      true
    )
    ON CONFLICT (festival_artist_programme_id, name)
    DO UPDATE SET
      opens_at = EXCLUDED.opens_at,
      closes_at = EXCLUDED.closes_at,
      eligible_artist_type = EXCLUDED.eligible_artist_type,
      minimum_fame = EXCLUDED.minimum_fame,
      maximum_fame = EXCLUDED.maximum_fame,
      preferred_genres = EXCLUDED.preferred_genres,
      minimum_band_members = EXCLUDED.minimum_band_members,
      maximum_band_members = EXCLUDED.maximum_band_members,
      target_stage_types = EXCLUDED.target_stage_types,
      maximum_set_minutes = EXCLUDED.maximum_set_minutes,
      active = true,
      version = public.festival_artist_application_windows.version + 1,
      updated_at = now();
  ELSE
    UPDATE public.festival_artist_application_windows
    SET active = false,
        updated_at = now()
    WHERE festival_artist_programme_id = programme.id;
  END IF;

  response := public._festival_edition_artist_programme_result(
    p_festival_company_id,
    p_festival_edition_id
  );
  UPDATE public.festival_artist_plan_requests
  SET status = 'succeeded', result = response, completed_at = now()
  WHERE id = request.id;
  RETURN response;
END;
$$;

-- Backfill every complete, editable annual Festival. Existing manual rows are retained.
DO $$
DECLARE
  edition record;
BEGIN
  FOR edition IN
    SELECT id, festival_company_id
    FROM public.festival_editions_v2
    WHERE status NOT IN ('cancelled', 'completed')
      AND locked_at IS NULL
      AND starts_on IS NOT NULL
      AND ends_on IS NOT NULL
      AND city_id IS NOT NULL
      AND site_type IS NOT NULL
      AND festival_scale IS NOT NULL
      AND coalesce(expected_capacity, 0) > 0
  LOOP
    PERFORM public.materialize_festival_edition_foundations(
      edition.festival_company_id,
      edition.id
    );
  END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION public._festival_projection_currency(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._festival_projection_authorized(uuid, uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._festival_projection_forecast(date, date, integer, bigint, integer, integer, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.materialize_festival_edition_foundations(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._festival_edition_foundation_trigger() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._festival_edition_site_plan_result(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._festival_edition_ticket_plan_result(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._festival_edition_artist_programme_result(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_festival_edition_site_plan(uuid, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_festival_edition_ticket_plan(uuid, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.save_festival_edition_ticket_plan(uuid, uuid, integer, jsonb, jsonb, jsonb, jsonb, uuid, boolean) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_festival_edition_artist_programme(uuid, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.save_festival_edition_artist_programme(uuid, uuid, integer, jsonb, jsonb, uuid, boolean) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.get_festival_edition_site_plan(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_festival_edition_ticket_plan(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_festival_edition_ticket_plan(uuid, uuid, integer, jsonb, jsonb, jsonb, jsonb, uuid, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_festival_edition_artist_programme(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_festival_edition_artist_programme(uuid, uuid, integer, jsonb, jsonb, uuid, boolean) TO authenticated;

COMMENT ON FUNCTION public.materialize_festival_edition_foundations(uuid, uuid) IS
  'Creates or refreshes hidden, exact-edition site, stage and ticket foundations from the simplified annual plan without overwriting manually-owned plans.';
COMMENT ON FUNCTION public.save_festival_edition_ticket_plan(uuid, uuid, integer, jsonb, jsonb, jsonb, jsonb, uuid, boolean) IS
  'Exact-edition simple ticket choice save. Detailed products, releases, allocations and forecasts remain server generated.';
COMMENT ON FUNCTION public.save_festival_edition_artist_programme(uuid, uuid, integer, jsonb, jsonb, uuid, boolean) IS
  'Exact-edition simple line-up strategy and budget save.';

NOTIFY pgrst, 'reload schema';
