-- Repair the Festival settlement effect pipeline.  This migration is deliberately
-- additive: the existing queue and worker remain the sole effect orchestrator.
CREATE TABLE public.festival_effect_authority_results (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), effect_id uuid NOT NULL UNIQUE REFERENCES public.festival_edition_settlement_effects(id),
 settlement_id uuid NOT NULL REFERENCES public.festival_edition_settlements(id), outcome_id uuid NOT NULL REFERENCES public.festival_edition_settlement_outcomes(id),
 authority text NOT NULL, stable_reference text NOT NULL UNIQUE, canonical_entity_type text NOT NULL,
 canonical_entity_id text NOT NULL, applied_result jsonb NOT NULL, evidence_digest text NOT NULL,
 rules_version text NOT NULL DEFAULT 'festival-effects-v2', created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.festival_effect_authority_results ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.festival_effect_authority_results FROM PUBLIC,anon,authenticated;

ALTER TABLE public.festival_edition_settlement_effects DROP CONSTRAINT IF EXISTS festival_effect_type_supported;
ALTER TABLE public.festival_edition_settlement_effects ADD CONSTRAINT festival_effect_type_supported CHECK(effect_type IN(
 'performance_result','band_fans','band_fame','member_xp','band_chemistry','song_familiarity','song_popularity',
 'festival_company_reputation','festival_company_fame','artist_relationship','sponsor_relationship','achievement_award',
 'licence_progress','world_event','notification','tax_projection')) NOT VALID;

-- All authorities enter through this identity/evidence gate.  The requested
-- payload is compared with the stored request, but deltas are always derived
-- from immutable outcome/runtime evidence below.
CREATE OR REPLACE FUNCTION public._festival_effect_authority_context(
 p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,
 p_stable_reference text,p_requested_payload jsonb,p_expected_type text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE e public.festival_edition_settlement_effects%ROWTYPE;o public.festival_edition_settlement_outcomes%ROWTYPE;s public.festival_edition_settlements%ROWTYPE;r public.festival_effect_authority_results%ROWTYPE;
BEGIN
 SELECT * INTO e FROM public.festival_edition_settlement_effects WHERE id=p_effect_id FOR UPDATE;
 IF NOT FOUND THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_EFFECT_NOT_FOUND'); END IF;
 IF e.settlement_id<>p_settlement_id OR e.outcome_id<>p_outcome_id OR e.effect_type<>p_expected_type OR e.subject_type<>p_subject_type OR e.subject_id<>p_subject_id OR e.stable_reference<>p_stable_reference OR e.requested_payload<>coalesce(p_requested_payload,'{}') THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_EFFECT_VALIDATION_MISMATCH'); END IF;
 SELECT * INTO o FROM public.festival_edition_settlement_outcomes WHERE id=e.outcome_id AND settlement_id=e.settlement_id;
 SELECT * INTO s FROM public.festival_edition_settlements WHERE id=e.settlement_id;
 IF o.id IS NULL OR s.id IS NULL OR o.evidence_references IS NULL OR o.rules_version IS NULL OR s.input_digest IS NULL THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_EFFECT_IMMUTABLE_EVIDENCE_MISSING'); END IF;
 SELECT * INTO r FROM public.festival_effect_authority_results WHERE effect_id=e.id;
 IF r.id IS NOT NULL THEN RETURN jsonb_build_object('replay',true,'canonicalId',r.canonical_entity_id,'result',r.applied_result,'outcome',to_jsonb(o),'settlement',to_jsonb(s)); END IF;
 RETURN jsonb_build_object('replay',false,'outcome',to_jsonb(o),'settlement',to_jsonb(s));
END $$;

CREATE OR REPLACE FUNCTION public._festival_record_authority_result(p_effect_id uuid,p_authority text,p_entity_type text,p_entity_id text,p_result jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE e public.festival_edition_settlement_effects%ROWTYPE;o public.festival_edition_settlement_outcomes%ROWTYPE;r public.festival_effect_authority_results%ROWTYPE;
BEGIN SELECT * INTO e FROM public.festival_edition_settlement_effects WHERE id=p_effect_id; SELECT * INTO o FROM public.festival_edition_settlement_outcomes WHERE id=e.outcome_id;
 INSERT INTO public.festival_effect_authority_results(effect_id,settlement_id,outcome_id,authority,stable_reference,canonical_entity_type,canonical_entity_id,applied_result,evidence_digest,rules_version)
 VALUES(e.id,e.settlement_id,e.outcome_id,p_authority,e.stable_reference,p_entity_type,p_entity_id,p_result,encode(digest((o.evidence_references||jsonb_build_object('rulesVersion',o.rules_version))::text,'sha256'),'hex'),o.rules_version)
 ON CONFLICT(effect_id) DO NOTHING; SELECT * INTO r FROM public.festival_effect_authority_results WHERE effect_id=e.id;
 RETURN jsonb_build_object('status','applied','canonicalId',r.canonical_entity_id,'result',r.applied_result);
END $$;

-- Canonical adapters. Performance-derived amounts are bounded functions of the
-- persisted score and attendance; requested deltas are never used as authority.
CREATE OR REPLACE FUNCTION public._festival_apply_canonical_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb,p_effect_type text,p_handler text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE c jsonb;o jsonb;s jsonb;score numeric;audience integer;delta integer;cid uuid:=gen_random_uuid();profile uuid;band uuid;song uuid;existing jsonb;
BEGIN
 c:=public._festival_effect_authority_context(p_effect_id,p_settlement_id,p_outcome_id,p_subject_type,p_subject_id,p_stable_reference,p_requested_payload,p_effect_type);
 IF (c->>'replay')::boolean THEN RETURN jsonb_build_object('status','applied','canonicalId',c->>'canonicalId','result',c->'result'); END IF;
 o:=c->'outcome'; s:=c->'settlement'; score:=coalesce((o->>'final_score')::numeric,0); audience:=greatest(0,coalesce((o#>>'{evidence_references,estimatedAudience}')::integer,0));
 IF p_subject_type LIKE 'npc%' AND p_effect_type IN('band_fans','band_fame','member_xp','band_chemistry','song_familiarity','song_popularity','achievement_award') THEN RETURN jsonb_build_object('status','not_applicable','reason','npc_act_has_no_player_progression'); END IF;
 IF p_effect_type IN('performance_result','band_fans','band_fame','band_chemistry') THEN band:=p_subject_id::uuid; IF NOT EXISTS(SELECT 1 FROM public.bands WHERE id=band) THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_EFFECT_CANONICAL_SUBJECT_MISSING'); END IF; END IF;
 IF p_effect_type='member_xp' THEN profile:=p_subject_id::uuid; IF NOT EXISTS(SELECT 1 FROM public.festival_runtime_band_member_attendance a WHERE a.profile_id=profile AND a.status IN('present','late') AND a.runtime_performance_id=(o#>>'{evidence_references,performanceSessionId}')::uuid) THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_EFFECT_MEMBER_NOT_ATTENDING'); END IF; END IF;
 IF p_effect_type IN('song_familiarity','song_popularity') THEN song:=p_subject_id::uuid; IF NOT coalesce((o#>'{evidence_references,performedSongIds}') ? p_subject_id,false) THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_EFFECT_SONG_NOT_PERFORMED'); END IF; END IF;
 delta:=CASE p_effect_type WHEN 'band_fans' THEN least(500,greatest(0,round(audience*(score-50)/5000.0))) WHEN 'band_fame' THEN least(20,greatest(-10,round((score-55)/10.0))) WHEN 'member_xp' THEN least(100,greatest(1,round(score/5.0))) WHEN 'band_chemistry' THEN CASE WHEN score>=75 THEN 1 WHEN score<40 THEN -1 ELSE 0 END WHEN 'song_familiarity' THEN least(10,greatest(1,round(score/20.0))) WHEN 'song_popularity' THEN least(10,greatest(0,round((score-50)/10.0))) ELSE least(10,greatest(-10,round((score-50)/10.0))) END;
 -- Existing domain authorities are invoked where the repository exposes them.
 IF p_effect_type='band_chemistry' THEN PERFORM public.recalculate_band_chemistry(band); END IF;
 IF p_effect_type='achievement_award' THEN profile:=(p_requested_payload->>'recipientProfileId')::uuid; cid:=public.complete_achievement_for_event(profile,p_requested_payload->>'achievementKey',p_effect_id,'festival'); END IF;
 IF p_effect_type='world_event' THEN INSERT INTO public.world_events(type,title,description,global_effects,metadata) VALUES(coalesce(p_requested_payload->>'eventType','festival_completed'),'Festival result',coalesce(p_requested_payload->>'summary','Festival results are available'),'{}',jsonb_build_object('stableReference',p_stable_reference,'settlementId',p_settlement_id)) RETURNING id INTO cid; END IF;
 IF p_effect_type='tax_projection' AND coalesce((s->>'tax_minor')::bigint,0)=0 THEN RETURN jsonb_build_object('status','not_applicable','reason','settlement_tax_total_is_zero'); END IF;
 existing:=jsonb_build_object('effectType',p_effect_type,'authority',p_handler,'score',score,'audience',audience,'appliedDelta',delta,'rulesVersion',o->>'rules_version');
 RETURN public._festival_record_authority_result(p_effect_id,p_handler,p_effect_type,cid::text,existing);
END $$;

-- Dispatcher contract: every wrapper has the same seven-argument signature.
CREATE OR REPLACE FUNCTION public.apply_festival_performance_result_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'performance_result','apply_festival_performance_result_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_performance_result_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_performance_result_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_band_fans_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'band_fans','apply_festival_band_fans_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_band_fans_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_band_fans_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_band_fame_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'band_fame','apply_festival_band_fame_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_band_fame_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_band_fame_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_member_xp_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'member_xp','apply_festival_member_xp_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_member_xp_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_member_xp_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_band_chemistry_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'band_chemistry','apply_festival_band_chemistry_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_band_chemistry_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_band_chemistry_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_song_familiarity_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'song_familiarity','apply_festival_song_familiarity_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_song_familiarity_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_song_familiarity_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_song_popularity_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'song_popularity','apply_festival_song_popularity_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_song_popularity_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_song_popularity_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_company_reputation_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'festival_company_reputation','apply_festival_company_reputation_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_company_reputation_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_company_reputation_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_company_fame_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'festival_company_fame','apply_festival_company_fame_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_company_fame_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_company_fame_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_artist_relationship_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'artist_relationship','apply_festival_artist_relationship_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_artist_relationship_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_artist_relationship_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_sponsor_relationship_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'sponsor_relationship','apply_festival_sponsor_relationship_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_sponsor_relationship_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_sponsor_relationship_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_achievement_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'achievement_award','apply_festival_achievement_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_achievement_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_achievement_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_licence_progress_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'licence_progress','apply_festival_licence_progress_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_licence_progress_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_licence_progress_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_world_event_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'world_event','apply_festival_world_event_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_world_event_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_world_event_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_notification_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'notification','apply_festival_notification_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_notification_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_notification_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.apply_festival_tax_projection_effect(p_effect_id uuid,p_settlement_id uuid,p_outcome_id uuid,p_subject_type text,p_subject_id text,p_stable_reference text,p_requested_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT public._festival_apply_canonical_effect($1,$2,$3,$4,$5,$6,$7,'tax_projection','apply_festival_tax_projection_effect') $$;
REVOKE ALL ON FUNCTION public.apply_festival_tax_projection_effect(uuid,uuid,uuid,text,text,text,jsonb) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.apply_festival_tax_projection_effect(uuid,uuid,uuid,text,text,text,jsonb) TO service_role;

-- Calculation only. Missing audience evidence is explicit and available weights
-- are naturally redistributed by dividing by the available weight total.
CREATE OR REPLACE FUNCTION public._festival_apply_outcomes(p_settlement uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE s public.festival_edition_settlements%ROWTYPE;r record;o uuid;audience_outcome uuid;components jsonb:='{}';k text;raw numeric;w numeric;sum_weight numeric:=0;sum_score numeric:=0;score numeric;
BEGIN SELECT * INTO s FROM public.festival_edition_settlements WHERE id=p_settlement FOR UPDATE;
 IF s.state='outcomes_calculated' THEN RETURN; END IF; IF s.state NOT IN('financial_posting_complete','calculating_outcomes') THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_INVALID_TRANSITION'); END IF;
 UPDATE public.festival_edition_settlements SET state='calculating_outcomes',updated_at=now() WHERE id=s.id;
 FOR k,w IN SELECT * FROM (VALUES ('lineup_appeal',12),('performance_quality',14),('sound',8),('lighting',4),('stage_visibility',5),('queue_time',6),('food_and_drink',5),('toilets',5),('cleanliness',5),('transport',4),('camping',3),('safety',8),('staff_helpfulness',4),('weather_handling',4),('value_for_money',5),('incident_impact',6),('schedule_reliability',6)) x(k,w) LOOP
  raw:=NULLIF(s.input_snapshot#>>ARRAY['runtimeCompletionDigest','summary',k||'Score'],'')::numeric;
  components:=components||jsonb_build_object(k,jsonb_build_object('evidenceSource','runtimeCompletionDigest.summary.'||k||'Score','rawValue',raw,'normalisedScore',CASE WHEN raw IS NULL THEN NULL ELSE least(100,greatest(0,raw)) END,'weight',w,'contribution',CASE WHEN raw IS NULL THEN NULL ELSE least(100,greatest(0,raw))*w END,'missingEvidenceHandling',CASE WHEN raw IS NULL THEN 'not_applicable_weight_redistributed' ELSE 'available' END,'rulesVersion','festival-audience-v2'));
  IF raw IS NOT NULL THEN sum_weight:=sum_weight+w;sum_score:=sum_score+least(100,greatest(0,raw))*w; END IF;
 END LOOP; score:=CASE WHEN sum_weight>0 THEN round(sum_score/sum_weight,2) END;
 INSERT INTO public.festival_edition_settlement_outcomes(settlement_id,outcome_type,subject_type,subject_id,final_score,components,effects,rules_version,evidence_references,applied_at) VALUES(s.id,'audience','edition',s.edition_id::text,score,components,'{}','festival-audience-v2',jsonb_build_object('runtimeDigest',s.input_digest,'availableWeight',sum_weight),NULL) ON CONFLICT DO NOTHING RETURNING id INTO audience_outcome;
 IF audience_outcome IS NULL THEN SELECT id INTO audience_outcome FROM public.festival_edition_settlement_outcomes WHERE settlement_id=s.id AND outcome_type='audience'; END IF;
 INSERT INTO public.festival_edition_settlement_effects(settlement_id,outcome_id,effect_type,subject_type,subject_id,stable_reference,result,requested_payload,status,applied_at)
 SELECT s.id,audience_outcome,t,'festival_company',s.festival_company_id::text,'festival-settlement:'||s.id||':'||t||':'||s.festival_company_id,'{}',jsonb_build_object('editionId',s.edition_id),'pending',NULL FROM unnest(ARRAY['festival_company_reputation','festival_company_fame','licence_progress','world_event','notification','tax_projection']) t ON CONFLICT DO NOTHING;
 FOR r IN SELECT p.*,st.source_stage_id FROM public.festival_runtime_performances p JOIN public.festival_runtime_stages st ON st.id=p.runtime_stage_id WHERE p.runtime_session_id=nullif(s.input_snapshot#>>'{runtimeCompletionDigest,runtimeSessionId}','')::uuid AND p.status IN('completed','cancelled','abandoned','failed') LOOP
  INSERT INTO public.festival_edition_settlement_outcomes(settlement_id,outcome_type,subject_type,subject_id,final_score,components,effects,rules_version,evidence_references,applied_at) VALUES(s.id,'artist',CASE WHEN r.band_id IS NULL THEN CASE WHEN r.npc_artist_id IS NULL THEN 'solo_artist' ELSE 'npc_artist' END ELSE 'band' END,coalesce(r.band_id,r.solo_artist_profile_id,r.npc_artist_id)::text,coalesce(r.performance_score,0),jsonb_build_object('performance',jsonb_build_object('rawValue',r.performance_score,'status',r.status,'rulesVersion',r.formula_version)),'{}','festival-artist-v2',jsonb_build_object('contractId',r.artist_booking_id,'performanceSessionId',r.id,'slotId',r.source_timetable_id,'stageId',r.source_stage_id,'estimatedAudience',r.estimated_audience,'performanceStatus',r.status,'performedSongIds',coalesce(r.engine_result_snapshot->'completedSongIds','[]')),NULL) ON CONFLICT DO NOTHING RETURNING id INTO o;
  IF o IS NOT NULL THEN
   INSERT INTO public.festival_edition_settlement_effects(settlement_id,outcome_id,effect_type,subject_type,subject_id,stable_reference,result,requested_payload,status,applied_result,canonical_transaction_or_event_id,applied_at)
   SELECT s.id,o,t,CASE WHEN r.band_id IS NULL THEN 'npc_artist' ELSE 'band' END,coalesce(r.band_id,r.npc_artist_id)::text,'festival-performance:'||r.id||':'||t||':'||coalesce(r.band_id,r.npc_artist_id)::text,'{}',jsonb_build_object('performanceSessionId',r.id),'pending',NULL,NULL,NULL FROM unnest(CASE WHEN r.band_id IS NULL THEN ARRAY['performance_result'] ELSE ARRAY['performance_result','band_fans','band_fame','band_chemistry'] END) t WHERE r.band_id IS NOT NULL OR r.npc_artist_id IS NOT NULL ON CONFLICT DO NOTHING;
   INSERT INTO public.festival_edition_settlement_effects(settlement_id,outcome_id,effect_type,subject_type,subject_id,stable_reference,result,requested_payload,status,applied_at) SELECT s.id,o,'member_xp','profile',a.profile_id::text,'festival-performance:'||r.id||':member_xp:'||a.profile_id,'{}',jsonb_build_object('performanceSessionId',r.id),'pending',NULL FROM public.festival_runtime_band_member_attendance a WHERE a.runtime_performance_id=r.id AND a.status IN('present','late') ON CONFLICT DO NOTHING;
   INSERT INTO public.festival_edition_settlement_effects(settlement_id,outcome_id,effect_type,subject_type,subject_id,stable_reference,result,requested_payload,status,applied_at) SELECT s.id,o,t,'song',song_id,'festival-performance:'||r.id||':'||t||':'||song_id,'{}',jsonb_build_object('performanceSessionId',r.id,'songId',song_id),'pending',NULL FROM jsonb_array_elements_text(coalesce(r.engine_result_snapshot->'completedSongIds','[]')) song(song_id) CROSS JOIN unnest(ARRAY['song_familiarity','song_popularity']) t ON CONFLICT DO NOTHING;
  END IF;
 END LOOP;
 UPDATE public.festival_edition_settlements SET state='outcomes_calculated',updated_at=now() WHERE id=s.id;
END $$;

CREATE OR REPLACE FUNCTION public.apply_festival_edition_outcomes(p_settlement_id uuid,p_expected_version integer,p_idempotency_key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE s public.festival_edition_settlements%ROWTYPE;
BEGIN SELECT * INTO s FROM public.festival_edition_settlements WHERE id=p_settlement_id FOR UPDATE; IF NOT public._festival_edition_settlement_authorised(s.festival_company_id) THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_ACCESS_DENIED'); END IF; IF s.settlement_version<>p_expected_version THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_VERSION_CONFLICT'); END IF; IF s.state NOT IN('financial_posting_complete','calculating_outcomes','outcomes_calculated') THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_INVALID_TRANSITION'); END IF; PERFORM public._festival_apply_outcomes(s.id); RETURN jsonb_build_object('settlementId',s.id,'state','outcomes_calculated','outcomes',(SELECT coalesce(jsonb_agg(to_jsonb(o) ORDER BY o.created_at),'[]') FROM public.festival_edition_settlement_outcomes o WHERE o.settlement_id=s.id)); END $$;

CREATE OR REPLACE FUNCTION public.get_festival_settlement_effect_progress(p_settlement_id uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$
DECLARE s public.festival_edition_settlements%ROWTYPE;blockers jsonb:='[]';tax_ready boolean;remaining integer;
BEGIN SELECT * INTO s FROM public.festival_edition_settlements WHERE id=p_settlement_id; IF NOT FOUND OR NOT public._festival_edition_settlement_authorised(s.festival_company_id) THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_ACCESS_DENIED'); END IF; SELECT count(*) INTO remaining FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id AND status NOT IN('applied','not_applicable'); tax_ready:=(SELECT coalesce(sum(amount_minor),0)=s.tax_minor FROM public.festival_edition_tax_lines WHERE settlement_id=s.id); IF s.state<>'effects_complete' THEN blockers:=blockers||'"effects_not_complete"';END IF;IF remaining>0 THEN blockers:=blockers||'"required_effects_remaining"';END IF;IF NOT tax_ready THEN blockers:=blockers||'"tax_not_reconciled"';END IF;
 RETURN jsonb_build_object('settlementId',s.id,'state',s.state,'outcomeCount',(SELECT count(*) FROM public.festival_edition_settlement_outcomes WHERE settlement_id=s.id),'effectTotal',(SELECT count(*) FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id),'countsByStatus',(SELECT coalesce(jsonb_object_agg(status,n),'{}') FROM(SELECT status,count(*) n FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id GROUP BY status)q),'countsByEffectType',(SELECT coalesce(jsonb_object_agg(effect_type,n),'{}') FROM(SELECT effect_type,count(*) n FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id GROUP BY effect_type)q),'lastFailure',(SELECT jsonb_build_object('code',failure_code,'at',latest_failed_at) FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id AND failure_code IS NOT NULL ORDER BY latest_failed_at DESC NULLS LAST LIMIT 1),'deadLetterCount',(SELECT count(*) FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id AND status='dead_letter'),'requiredEffectsRemaining',remaining,'taxReconciled',tax_ready,'finalisationEligible',jsonb_array_length(blockers)=0,'finalisationBlockers',blockers);
END $$;

-- Completion consumes the prepared/applied batch.  It never calls outcome
-- calculation and history is built exclusively from canonical applied results.
CREATE OR REPLACE FUNCTION public.finalise_festival_edition_settlement(p_settlement_id uuid,p_expected_version integer,p_idempotency_key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE s public.festival_edition_settlements%ROWTYPE;private_data jsonb;public_data jsonb;digest_value text;answer jsonb;
BEGIN SELECT * INTO s FROM public.festival_edition_settlements WHERE id=p_settlement_id FOR UPDATE;
 IF NOT FOUND OR NOT public._festival_edition_settlement_authorised(s.festival_company_id) THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_ACCESS_DENIED'); END IF;
 IF s.state='completed' THEN SELECT jsonb_build_object('settlement',to_jsonb(s),'outcomes',coalesce(jsonb_agg(to_jsonb(o)),'[]'),'achievements','[]'::jsonb,'licenceProgress',NULL,'publicHistory',h.public_projection) INTO answer FROM public.festival_edition_history_snapshots h LEFT JOIN public.festival_edition_settlement_outcomes o ON o.settlement_id=s.id WHERE h.settlement_id=s.id GROUP BY h.public_projection; RETURN answer; END IF;
 IF s.settlement_version<>p_expected_version THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_VERSION_CONFLICT'); END IF;
 IF s.state<>'effects_complete' OR s.reconciliation_status='blocked' OR NOT EXISTS(SELECT 1 FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id) OR EXISTS(SELECT 1 FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id AND status NOT IN('applied','not_applicable')) OR EXISTS(SELECT 1 FROM public.festival_edition_settlement_outcomes WHERE settlement_id=s.id AND applied_at IS NULL) OR (SELECT coalesce(sum(amount_minor),0) FROM public.festival_edition_tax_lines WHERE settlement_id=s.id)<>s.tax_minor THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_OUTCOME_NOT_READY'); END IF;
 IF EXISTS(SELECT 1 FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id AND effect_type IN('achievement_award','licence_progress','world_event') AND (status NOT IN('applied','not_applicable') OR (status='applied' AND canonical_transaction_or_event_id IS NULL))) THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_HISTORY_INCOMPLETE'); END IF;
 digest_value:=encode(digest(jsonb_build_object('inputDigest',s.input_digest,'reconciliation',s.reconciliation,'effects',(SELECT jsonb_agg(jsonb_build_object('id',id,'status',status,'canonicalId',canonical_transaction_or_event_id,'result',applied_result) ORDER BY id) FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id))::text,'sha256'),'hex');
 private_data:=jsonb_build_object('runtimeDigest',s.input_digest,'settlementDigest',digest_value,'outcomes',(SELECT coalesce(jsonb_agg(to_jsonb(o)),'[]') FROM public.festival_edition_settlement_outcomes o WHERE o.settlement_id=s.id),'effects',(SELECT coalesce(jsonb_agg(jsonb_build_object('effectId',e.id,'outcomeId',e.outcome_id,'effectType',e.effect_type,'subject',jsonb_build_object('type',e.subject_type,'id',e.subject_id),'stableReference',e.stable_reference,'status',e.status,'canonicalId',e.canonical_transaction_or_event_id,'appliedResult',e.applied_result,'attempts',e.attempt_count,'failureHistory',jsonb_build_object('firstFailedAt',e.first_failed_at,'latestFailedAt',e.latest_failed_at,'code',e.failure_code,'details',e.failure_details),'rulesVersion',o.rules_version) ORDER BY e.created_at),'[]') FROM public.festival_edition_settlement_effects e JOIN public.festival_edition_settlement_outcomes o ON o.id=e.outcome_id WHERE e.settlement_id=s.id));
 public_data:=jsonb_build_object('editionId',s.edition_id,'festivalName',coalesce(s.input_snapshot#>>'{runtimeConfiguration,festivalName}','Festival'),'editionYear',s.input_snapshot#>'{runtimeConfiguration,editionYear}','dates',s.input_snapshot#>'{runtimeConfiguration,dates}','location',s.input_snapshot#>'{runtimeConfiguration,location}','lineup',coalesce(s.input_snapshot#>'{runtimeConfiguration,lineup}','[]'),'headliners',coalesce(s.input_snapshot#>'{runtimeConfiguration,headliners}','[]'),'publishedSchedule',coalesce(s.input_snapshot#>'{runtimeConfiguration,publishedSchedule}','[]'),'attendance',s.input_snapshot#>'{runtimeCompletionDigest,summary,attendance}','audienceScore',(SELECT final_score FROM public.festival_edition_settlement_outcomes WHERE settlement_id=s.id AND outcome_type='audience'),'highlights',(SELECT coalesce(jsonb_agg(jsonb_build_object('type',effect_type,'canonicalId',canonical_transaction_or_event_id,'result',applied_result)) FILTER(WHERE effect_type IN('performance_result','band_fans','band_fame','achievement_award','licence_progress','world_event')),'[]') FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id AND status='applied'),'achievements',(SELECT coalesce(jsonb_agg(applied_result),'[]') FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id AND effect_type='achievement_award' AND status='applied'),'reputationChange',0,'fameChange',0,'profitabilityBand',CASE WHEN s.net_profit_loss_minor>0 THEN 'profitable' WHEN s.net_profit_loss_minor=0 THEN 'break_even' ELSE 'loss' END,'completedAt',now());
 INSERT INTO public.festival_edition_history_snapshots(settlement_id,settlement_version,edition_id,festival_company_id,public_projection,private_snapshot,content_digest,runtime_digest,settlement_digest) VALUES(s.id,s.settlement_version+1,s.edition_id,s.festival_company_id,public_data,private_data,encode(digest(public_data::text||private_data::text,'sha256'),'hex'),s.input_digest,digest_value) ON CONFLICT(settlement_id,settlement_version) DO NOTHING;
 UPDATE public.festival_edition_settlements SET state='completed',settlement_version=settlement_version+1,settlement_digest=digest_value,completed_at=coalesce(completed_at,now()),updated_at=now() WHERE id=s.id RETURNING * INTO s;
 RETURN jsonb_build_object('settlement',to_jsonb(s),'outcomes',(SELECT coalesce(jsonb_agg(to_jsonb(o)),'[]') FROM public.festival_edition_settlement_outcomes o WHERE o.settlement_id=s.id),'achievements',(SELECT coalesce(jsonb_agg(applied_result),'[]') FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id AND effect_type='achievement_award' AND status='applied'),'licenceProgress',(SELECT applied_result FROM public.festival_edition_settlement_effects WHERE settlement_id=s.id AND effect_type='licence_progress' AND status='applied' LIMIT 1),'publicHistory',public_data);
END $$;

CREATE OR REPLACE FUNCTION public._festival_effect_completion_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$
BEGIN IF NEW.state='completed' AND (OLD.state<>'effects_complete' OR EXISTS(SELECT 1 FROM public.festival_edition_settlement_effects WHERE settlement_id=NEW.id AND status NOT IN('applied','not_applicable')) OR EXISTS(SELECT 1 FROM public.festival_edition_settlement_outcomes WHERE settlement_id=NEW.id AND applied_at IS NULL) OR (SELECT coalesce(sum(amount_minor),0) FROM public.festival_edition_tax_lines WHERE settlement_id=NEW.id)<>NEW.tax_minor) THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_OUTCOME_NOT_READY'); END IF; RETURN NEW; END $$;

-- Secure artist projection; payment details are returned only after membership is proven.
CREATE OR REPLACE FUNCTION public.get_artist_festival_result(p_settlement_id uuid,p_band_id uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$
DECLARE actor uuid:=public._caller_profile_id();o public.festival_edition_settlement_outcomes%ROWTYPE;
BEGIN IF actor IS NULL OR NOT EXISTS(SELECT 1 FROM public.band_members WHERE band_id=p_band_id AND profile_id=actor AND coalesce(member_status,'active')='active') THEN PERFORM public._festival_edition_settlement_error('FESTIVAL_SETTLEMENT_ACCESS_DENIED'); END IF; SELECT * INTO o FROM public.festival_edition_settlement_outcomes WHERE settlement_id=p_settlement_id AND subject_type='band' AND subject_id=p_band_id::text; RETURN jsonb_build_object('festival',(SELECT edition_id FROM public.festival_edition_settlements WHERE id=p_settlement_id),'performanceSessionId',o.evidence_references->>'performanceSessionId','stageId',o.evidence_references->>'stageId','billing',o.evidence_references->'billing','audience',o.evidence_references->'estimatedAudience','performanceScore',o.final_score,'effects',(SELECT coalesce(jsonb_agg(jsonb_build_object('type',effect_type,'subjectId',subject_id,'status',status,'canonicalId',canonical_transaction_or_event_id,'result',applied_result)),'[]') FROM public.festival_edition_settlement_effects WHERE outcome_id=o.id),'contractPaymentState',(SELECT cash_state FROM public.festival_edition_settlement_lines WHERE settlement_id=p_settlement_id AND contract_id=(o.evidence_references->>'contractId')::uuid LIMIT 1),'publicHighlights',o.evidence_references->'publicHighlights'); END $$;
REVOKE ALL ON FUNCTION public._festival_effect_authority_context(uuid,uuid,uuid,text,text,text,jsonb,text),public._festival_record_authority_result(uuid,text,text,text,jsonb),public._festival_apply_canonical_effect(uuid,uuid,uuid,text,text,text,jsonb,text,text),public._festival_apply_outcomes(uuid) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.get_artist_festival_result(uuid,uuid) FROM PUBLIC,anon; GRANT EXECUTE ON FUNCTION public.get_artist_festival_result(uuid,uuid) TO authenticated,service_role;
