-- Confirmed acts must occupy the running order before autogenerated filler.
-- Preserve the existing runtime implementation and authority checks.
DO $patch$
DECLARE
  definition text;
  old_filler constant text := E'      0 grp,\n      f.n ord,';
  new_filler constant text := E'      1 grp,\n      f.n ord,';
  old_booked constant text := E'    SELECT\n      1,\n      b.bill_rank * 100000 + b.rn,';
  new_booked constant text := E'    SELECT\n      0,\n      b.bill_rank * 100000 + b.rn,';
BEGIN
  SELECT pg_get_functiondef('public.run_simplified_festival_edition(uuid,uuid,integer,uuid)'::regprocedure)
    INTO definition;
  IF definition IS NULL THEN RAISE EXCEPTION 'festival_simplified_runtime_missing'; END IF;
  IF position(new_filler IN definition)>0 AND position(new_booked IN definition)>0 THEN RETURN; END IF;
  IF position(old_filler IN definition)=0 OR position(old_booked IN definition)=0 THEN
    RAISE EXCEPTION 'festival_running_order_shape_changed';
  END IF;
  definition:=replace(definition,old_filler,new_filler);
  definition:=replace(definition,old_booked,new_booked);
  EXECUTE definition;
END;
$patch$;
-- Does not rewrite an already frozen runtime. Shock must use an audited rerun
-- after the original company posting is compensated.
NOTIFY pgrst,'reload schema';
