-- Phase 9A: Festival financial settlement and participant payments.
-- Forward-only and additive. This migration creates no aggregate and moves no money.
CREATE TABLE public.festival_financial_settlements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),runtime_session_id uuid NOT NULL UNIQUE REFERENCES public.festival_runtime_sessions(id),festival_launch_id uuid NOT NULL UNIQUE REFERENCES public.festival_launches(id),festival_company_id uuid NOT NULL REFERENCES public.festival_companies(id),status text NOT NULL DEFAULT 'settlement_review' CHECK(status IN('not_ready','ready_for_settlement','settlement_review','settling','partially_settled','settled','settlement_failed','disputed')),currency_code text NOT NULL CHECK(currency_code~'^[A-Z]{3}$'),version integer NOT NULL DEFAULT 1 CHECK(version>0),formula_version text NOT NULL DEFAULT 'festival-settlement-v1',runtime_version integer NOT NULL,runtime_outcome_digest text NOT NULL,review_snapshot_id uuid,final_snapshot_id uuid,total_revenue_minor bigint NOT NULL DEFAULT 0,total_cost_minor bigint NOT NULL DEFAULT 0,net_profit_loss_minor bigint NOT NULL DEFAULT 0,cash_received_minor bigint NOT NULL DEFAULT 0,cash_paid_minor bigint NOT NULL DEFAULT 0,outstanding_receivables_minor bigint NOT NULL DEFAULT 0,outstanding_payables_minor bigint NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),settled_at timestamptz);
CREATE TABLE public.festival_settlement_snapshots(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_id uuid NOT NULL REFERENCES public.festival_financial_settlements(id),snapshot_type text NOT NULL CHECK(snapshot_type IN('review','final')),runtime_outcome_snapshot_id uuid NOT NULL REFERENCES public.festival_runtime_outcome_snapshots(id),snapshot jsonb NOT NULL,content_digest text NOT NULL,formula_versions jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(settlement_id,snapshot_type));
ALTER TABLE public.festival_financial_settlements ADD CONSTRAINT festival_settlement_review_snapshot_fk FOREIGN KEY(review_snapshot_id) REFERENCES public.festival_settlement_snapshots(id),ADD CONSTRAINT festival_settlement_final_snapshot_fk FOREIGN KEY(final_snapshot_id) REFERENCES public.festival_settlement_snapshots(id);
CREATE TABLE public.festival_settlement_lines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_id uuid NOT NULL REFERENCES public.festival_financial_settlements(id),line_type text NOT NULL CHECK(line_type IN('ticket_revenue','vendor_revenue','festival_merch_revenue','artist_merch_revenue','sponsor_receivable','artist_fee','staff_wage','supplier_invoice','tax_liability','refund','platform_fee','inventory_cost','other_income','other_expense')),source_type text NOT NULL,source_id uuid NOT NULL,recipient_type text,recipient_id uuid,payer_type text,payer_id uuid,gross_amount_minor bigint NOT NULL CHECK(gross_amount_minor>=0),tax_amount_minor bigint NOT NULL DEFAULT 0 CHECK(tax_amount_minor>=0),fee_amount_minor bigint NOT NULL DEFAULT 0 CHECK(fee_amount_minor>=0),net_amount_minor bigint NOT NULL CHECK(net_amount_minor>=0),currency_code text NOT NULL CHECK(currency_code~'^[A-Z]{3}$'),status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','processing','paid','failed','outstanding','waived')),priority integer NOT NULL,formula_version text NOT NULL DEFAULT 'festival-settlement-v1',calculation_metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(source_type,source_id,line_type));
CREATE INDEX festival_settlement_lines_work_idx ON public.festival_settlement_lines(settlement_id,priority,id) WHERE status IN('pending','failed','outstanding');
CREATE TABLE public.festival_settlement_payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_line_id uuid NOT NULL REFERENCES public.festival_settlement_lines(id),attempt integer NOT NULL,amount_minor bigint NOT NULL,currency_code text NOT NULL,status text NOT NULL CHECK(status IN('processing','paid','failed')),financial_transaction_id uuid REFERENCES public.financial_transactions(id),idempotency_key text NOT NULL UNIQUE,started_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(settlement_line_id,attempt));
CREATE TABLE public.festival_settlement_receipts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_line_id uuid NOT NULL UNIQUE REFERENCES public.festival_settlement_lines(id),payment_id uuid UNIQUE REFERENCES public.festival_settlement_payments(id),canonical_transaction_id uuid UNIQUE REFERENCES public.financial_transactions(id),receipt jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.festival_settlement_failures(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_id uuid NOT NULL REFERENCES public.festival_financial_settlements(id),settlement_line_id uuid NOT NULL REFERENCES public.festival_settlement_lines(id),payment_id uuid REFERENCES public.festival_settlement_payments(id),error_code text NOT NULL,retryable boolean NOT NULL,attempt integer NOT NULL,private_detail text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.festival_settlement_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_id uuid REFERENCES public.festival_financial_settlements(id),runtime_session_id uuid REFERENCES public.festival_runtime_sessions(id),actor_profile_id uuid NOT NULL REFERENCES public.profiles(id),action text NOT NULL,idempotency_key uuid NOT NULL,payload_hash text NOT NULL,status text NOT NULL DEFAULT 'processing',result jsonb,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(actor_profile_id,action,idempotency_key));
CREATE TABLE public.festival_settlement_audit(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_id uuid NOT NULL REFERENCES public.festival_financial_settlements(id),actor_profile_id uuid REFERENCES public.profiles(id),event_type text NOT NULL,previous_status text,new_status text,version integer NOT NULL,metadata jsonb NOT NULL DEFAULT '{}',dedupe_key text NOT NULL UNIQUE,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.festival_settlement_disputes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_id uuid NOT NULL REFERENCES public.festival_financial_settlements(id),raised_by_profile_id uuid NOT NULL REFERENCES public.profiles(id),reason text NOT NULL,status text NOT NULL DEFAULT 'open' CHECK(status IN('open','resolved','rejected')),resolution text,created_at timestamptz NOT NULL DEFAULT now(),resolved_at timestamptz);

CREATE FUNCTION public._festival_settlement_owner(s uuid,a uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$SELECT EXISTS(SELECT 1 FROM public.festival_financial_settlements x JOIN public.festival_companies f ON f.id=x.festival_company_id WHERE x.id=s AND f.owner_profile_id=a) OR coalesce(public.has_role(auth.uid(),'admin'::public.app_role),false)$$;
CREATE FUNCTION public._festival_settlement_json(s public.festival_financial_settlements) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$SELECT jsonb_build_object('id',s.id,'runtimeSessionId',s.runtime_session_id,'festivalCompanyId',s.festival_company_id,'status',s.status,'currencyCode',s.currency_code,'version',s.version,'formulaVersion',s.formula_version,'reviewSnapshotId',s.review_snapshot_id,'finalSnapshotId',s.final_snapshot_id,'permissions',jsonb_build_object('canPrepare',public._festival_settlement_owner(s.id,public._caller_profile_id()),'canExecute',public._festival_settlement_owner(s.id,public._caller_profile_id()),'canRetry',public._festival_settlement_owner(s.id,public._caller_profile_id()),'canDispute',s.status='settled','canReadFullSummary',public._festival_settlement_owner(s.id,public._caller_profile_id())))$$;

CREATE FUNCTION public.prepare_festival_settlement(p_runtime_session_id uuid,p_expected_runtime_version integer,p_idempotency_key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE a uuid:=public._caller_profile_id();r public.festival_runtime_sessions%ROWTYPE;l public.festival_launches%ROWTYPE;fc public.festival_companies%ROWTYPE;o public.festival_runtime_outcome_snapshots%ROWTYPE;s public.festival_financial_settlements%ROWTYPE;req public.festival_settlement_requests%ROWTYPE;snap jsonb;sid uuid;currency text;scheduled bigint;actual bigint;
BEGIN
 SELECT * INTO r FROM public.festival_runtime_sessions WHERE id=p_runtime_session_id FOR UPDATE;
 IF r.id IS NULL OR NOT r.ready_for_settlement OR r.status<>'runtime_complete' THEN RAISE EXCEPTION 'festival_settlement_not_ready';END IF;
 IF NOT public._festival_runtime_owner(r.id,a) THEN RAISE EXCEPTION 'festival_settlement_forbidden';END IF;
 IF r.version<>p_expected_runtime_version THEN RAISE EXCEPTION 'festival_settlement_stale';END IF;
 SELECT * INTO o FROM public.festival_runtime_outcome_snapshots WHERE runtime_session_id=r.id; IF o.id IS NULL THEN RAISE EXCEPTION 'festival_settlement_not_ready';END IF;
 IF EXISTS(SELECT 1 FROM public.festival_runtime_performances WHERE runtime_session_id=r.id AND status NOT IN('completed','cancelled','abandoned','failed')) OR EXISTS(SELECT 1 FROM public.festival_runtime_vendor_sales WHERE runtime_session_id=r.id AND status<>'closed') OR EXISTS(SELECT 1 FROM public.festival_runtime_incidents WHERE runtime_session_id=r.id AND status NOT IN('resolved','handed_over')) OR EXISTS(SELECT 1 FROM public.festival_runtime_vendor_sales v WHERE v.runtime_session_id=r.id AND NOT EXISTS(SELECT 1 FROM public.festival_runtime_revenue_postings p WHERE p.vendor_sales_id=v.id)) THEN RAISE EXCEPTION 'festival_settlement_not_ready';END IF;
 SELECT * INTO l FROM public.festival_launches WHERE id=r.festival_launch_id;IF l.launch_status<>'sales_closed' OR l.ticket_sales_closed_at IS NULL THEN RAISE EXCEPTION 'festival_settlement_not_ready';END IF;SELECT * INTO fc FROM public.festival_companies WHERE id=l.festival_company_id;
 SELECT coalesce((SELECT currency FROM public.festival_public_ticket_products WHERE festival_launch_id=l.id LIMIT 1),(SELECT currency_code FROM public.festival_runtime_vendor_sales WHERE runtime_session_id=r.id LIMIT 1),'GBP') INTO currency;
 SELECT * INTO s FROM public.festival_financial_settlements WHERE runtime_session_id=r.id;IF s.id IS NOT NULL THEN RETURN public._festival_settlement_json(s);END IF;
 INSERT INTO public.festival_settlement_requests(runtime_session_id,actor_profile_id,action,idempotency_key,payload_hash)VALUES(r.id,a,'prepare',p_idempotency_key,encode(digest(r.id::text||p_expected_runtime_version,'sha256'),'hex'))RETURNING * INTO req;
 INSERT INTO public.festival_financial_settlements(runtime_session_id,festival_launch_id,festival_company_id,currency_code,runtime_version,runtime_outcome_digest)VALUES(r.id,l.id,fc.id,currency,r.version,o.content_digest)RETURNING * INTO s;
 -- Ticket receipts already moved at purchase. Keep retained booking fees distinct and accrue tax.
 INSERT INTO public.festival_settlement_lines(settlement_id,line_type,source_type,source_id,recipient_type,recipient_id,payer_type,payer_id,gross_amount_minor,tax_amount_minor,fee_amount_minor,net_amount_minor,currency_code,status,priority,calculation_metadata)
 SELECT s.id,'ticket_revenue','festival_ticket_sale',x.id,'company',fc.company_id,'player',x.buyer_profile_id,x.subtotal_minor,x.tax_minor,x.fee_minor,x.subtotal_minor+x.fee_minor,x.currency,'paid',90,jsonb_build_object('actual',true,'bookingFeeRetainedMinor',x.fee_minor) FROM public.festival_ticket_sales x WHERE x.festival_launch_id=l.id AND x.status IN('completed','partially_refunded');
 INSERT INTO public.festival_settlement_lines(settlement_id,line_type,source_type,source_id,recipient_type,recipient_id,payer_type,payer_id,gross_amount_minor,tax_amount_minor,fee_amount_minor,net_amount_minor,currency_code,status,priority,calculation_metadata)
 SELECT s.id,CASE v.category WHEN 'festival_merch' THEN 'festival_merch_revenue' WHEN 'artist_merch' THEN 'artist_merch_revenue' ELSE 'vendor_revenue' END,'festival_runtime_vendor_sales',v.id,'company',fc.company_id,'system',NULL,v.gross_revenue_minor,v.tax_liability_minor,0,v.gross_revenue_minor-v.tax_liability_minor,v.currency_code,'paid',90,jsonb_build_object('actual',true,'category',v.category,'costBasisMinor',v.cost_basis_minor,'wasteUnits',v.waste_units,'postingId',p.id) FROM public.festival_runtime_vendor_sales v JOIN public.festival_runtime_revenue_postings p ON p.vendor_sales_id=v.id WHERE v.runtime_session_id=r.id;
 -- Artist contract actuals: cancellation/no-show/partial terms are read only from accepted snapshots.
 INSERT INTO public.festival_settlement_lines(settlement_id,line_type,source_type,source_id,recipient_type,recipient_id,payer_type,payer_id,gross_amount_minor,net_amount_minor,currency_code,status,priority,calculation_metadata)
 SELECT s.id,'artist_fee','festival_artist_booking',b.id,CASE b.artist_type WHEN 'solo' THEN 'player' WHEN 'band' THEN 'band' ELSE 'system' END,coalesce(b.artist_profile_id,b.band_id,b.npc_artist_id),'company',fc.company_id,b.total_commitment_minor,GREATEST(0,round(b.total_commitment_minor*coalesce((SELECT avg(CASE p.status WHEN 'completed' THEN coalesce((p.engine_result_snapshot->>'completionRatio')::numeric,1) WHEN 'cancelled' THEN coalesce((b.contract_terms->>'cancellationPayRatio')::numeric,0) ELSE coalesce((b.contract_terms->>'noShowPayRatio')::numeric,0) END) FROM public.festival_runtime_performances p WHERE p.runtime_session_id=r.id AND p.artist_booking_id=b.id),1))::bigint),b.currency_code,'pending',50,jsonb_build_object('contractTerms',b.contract_terms,'billingPosition',b.billing_position,'acceptedTermsUnchanged',true) FROM public.festival_artist_bookings b JOIN public.festival_artist_programmes ap ON ap.id=b.festival_artist_programme_id WHERE ap.festival_company_id=fc.id AND b.status NOT IN('cancelled','festival_cancelled');
 -- Actual check-in/out controls paid shift proportion; overtime only applies when accepted assignment time is exceeded.
 INSERT INTO public.festival_settlement_lines(settlement_id,line_type,source_type,source_id,recipient_type,recipient_id,payer_type,payer_id,gross_amount_minor,net_amount_minor,currency_code,status,priority,calculation_metadata)
 SELECT s.id,'staff_wage','festival_runtime_staff_checkin',c.id,CASE WHEN a.profile_id IS NOT NULL THEN 'player' WHEN a.company_id IS NOT NULL THEN 'company' ELSE 'system' END,coalesce(a.profile_id,a.company_id,a.npc_staff_id),'company',fc.company_id,a.agreed_pay_minor,CASE WHEN c.checked_in_at IS NULL THEN 0 ELSE LEAST(a.agreed_pay_minor,round(a.agreed_pay_minor*GREATEST(0,extract(epoch from(coalesce(c.checked_out_at,c.expected_end)-GREATEST(c.checked_in_at,c.expected_start)))/NULLIF(extract(epoch from(c.expected_end-c.expected_start)),0)))::bigint) END,a.currency_code,'pending',CASE WHEN a.profile_id IS NOT NULL THEN 30 ELSE 60 END,jsonb_build_object('checkedInAt',c.checked_in_at,'checkedOutAt',c.checked_out_at,'expectedStart',c.expected_start,'expectedEnd',c.expected_end,'latenessMinutes',coalesce(o2.lateness_minutes,0),'overtimeTermsApplied',false) FROM public.festival_runtime_staff_checkins c JOIN public.festival_staff_shifts sh ON sh.id=c.staff_shift_id JOIN public.festival_staff_assignments a ON a.id=sh.staff_assignment_id LEFT JOIN public.festival_runtime_staff_outcomes o2 ON o2.staff_checkin_id=c.id WHERE c.runtime_session_id=r.id AND a.status IN('committed','active');
 INSERT INTO public.festival_settlement_lines(settlement_id,line_type,source_type,source_id,recipient_type,recipient_id,payer_type,payer_id,gross_amount_minor,net_amount_minor,currency_code,status,priority,calculation_metadata)
 SELECT s.id,'supplier_invoice','festival_supplier_contract',c.id,CASE WHEN c.supplier_company_id IS NOT NULL THEN 'company' ELSE 'system' END,coalesce(c.supplier_company_id,c.npc_supplier_id),'company',fc.company_id,c.total_commitment_minor,round(c.total_commitment_minor*coalesce(o2.contract_compliance,0)/100.0)::bigint,c.currency_code,'pending',CASE WHEN c.supplier_company_id IS NOT NULL THEN 40 ELSE 60 END,jsonb_build_object('acceptedTerms',c.terms_snapshot,'deliveryCompleteness',o2.delivery_completeness,'quality',o2.product_quality,'latenessMinutes',o2.lateness_minutes) FROM public.festival_supplier_contracts c JOIN public.festival_operations_plans op ON op.id=c.festival_operations_plan_id JOIN public.festival_runtime_supplier_checkins ck ON ck.supplier_contract_id=c.id AND ck.runtime_session_id=r.id JOIN public.festival_runtime_supplier_outcomes o2 ON o2.supplier_checkin_id=ck.id WHERE op.festival_company_id=fc.id AND c.status<>'cancelled';
 -- Only cash receivables become payable lines. In-kind value remains summary metadata.
 INSERT INTO public.festival_settlement_lines(settlement_id,line_type,source_type,source_id,recipient_type,recipient_id,payer_type,payer_id,gross_amount_minor,net_amount_minor,currency_code,status,priority,calculation_metadata)
 SELECT s.id,'sponsor_receivable','festival_financial_receivable',fr.id,'company',fc.company_id,CASE WHEN sc.company_id IS NULL THEN 'system' ELSE 'company' END,sc.company_id,fr.amount_minor,CASE WHEN EXISTS(SELECT 1 FROM public.festival_runtime_sponsor_activations a2 WHERE a2.runtime_session_id=r.id AND a2.status='partially_completed') THEN fr.amount_minor/2 WHEN EXISTS(SELECT 1 FROM public.festival_runtime_sponsor_activations a2 WHERE a2.runtime_session_id=r.id AND a2.status IN('failed','cancelled')) THEN 0 ELSE fr.amount_minor END,fr.currency_code,'pending',20,jsonb_build_object('cash',true,'inKindContributionMinor',sc.in_kind_contribution_minor) FROM public.festival_financial_receivables fr JOIN public.festival_sponsor_contracts sc ON sc.id=fr.sponsor_contract_id JOIN public.festival_sponsorship_plans sp ON sp.id=sc.festival_sponsorship_plan_id WHERE sp.festival_company_id=fc.id AND fr.source_type='sponsor_contract_cash' AND fr.status='planned';
 INSERT INTO public.festival_settlement_lines(settlement_id,line_type,source_type,source_id,recipient_type,recipient_id,payer_type,payer_id,gross_amount_minor,net_amount_minor,currency_code,status,priority,calculation_metadata)
 SELECT s.id,'refund','festival_ticket_refund_obligation',ro.id,'player',ro.buyer_profile_id,'company',fc.company_id,ro.amount_minor,ro.amount_minor,ro.currency,'pending',10,jsonb_build_object('reasonCode',ro.reason_code) FROM public.festival_ticket_refund_obligations ro JOIN public.festival_ticket_sales ts ON ts.id=ro.festival_ticket_sale_id WHERE ts.festival_launch_id=l.id AND ro.status IN('pending','failed');
 -- Tax remains an accrued canonical liability, never fabricated as an immediate payment.
 INSERT INTO public.festival_settlement_lines(settlement_id,line_type,source_type,source_id,recipient_type,payer_type,payer_id,gross_amount_minor,net_amount_minor,currency_code,status,priority,calculation_metadata)
 SELECT s.id,'tax_liability',z.source_type,z.source_id,'tax_authority','company',fc.company_id,z.amount,z.amount,z.currency,'outstanding',15,jsonb_build_object('accrued',true,'canonicalTaxCycle',true) FROM (SELECT 'festival_ticket_sale' source_type,id source_id,tax_minor amount,currency FROM public.festival_ticket_sales WHERE festival_launch_id=l.id AND status IN('completed','partially_refunded') UNION ALL SELECT 'festival_runtime_vendor_sales',id,tax_liability_minor,currency_code FROM public.festival_runtime_vendor_sales WHERE runtime_session_id=r.id)z WHERE z.amount>0;
 SELECT coalesce(sum(extract(epoch from(expected_end-expected_start))),0)::bigint,coalesce(sum(extract(epoch from(coalesce(checked_out_at,expected_end)-coalesce(checked_in_at,expected_start))),0)::bigint) INTO scheduled,actual FROM public.festival_runtime_staff_checkins WHERE runtime_session_id=r.id;
 snap:=jsonb_build_object('runtimeOutcomeDigest',o.content_digest,'runtimeVersion',r.version,'runtimeSnapshot',o.snapshot,'lineIds',(SELECT jsonb_agg(id ORDER BY priority,id) FROM public.festival_settlement_lines WHERE settlement_id=s.id),'actualShiftSeconds',actual,'scheduledShiftSeconds',scheduled,'forecastsIncluded',false,'formulaVersion','festival-settlement-v1');
 INSERT INTO public.festival_settlement_snapshots(settlement_id,snapshot_type,runtime_outcome_snapshot_id,snapshot,content_digest,formula_versions)VALUES(s.id,'review',o.id,snap,encode(digest(snap::text,'sha256'),'hex'),jsonb_build_object('settlement','festival-settlement-v1'))RETURNING id INTO sid;UPDATE public.festival_financial_settlements SET review_snapshot_id=sid WHERE id=s.id RETURNING * INTO s;
 INSERT INTO public.festival_settlement_audit(settlement_id,actor_profile_id,event_type,previous_status,new_status,version,dedupe_key)VALUES(s.id,a,'settlement_review_ready','ready_for_settlement','settlement_review',s.version,'prepare:'||p_idempotency_key);
 UPDATE public.festival_settlement_requests SET settlement_id=s.id,status='completed',result=public._festival_settlement_json(s),completed_at=now() WHERE id=req.id;RETURN public._festival_settlement_json(s);
END$$;
CREATE FUNCTION public._process_festival_settlement_line(p_line_id uuid,p_actor uuid) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$DECLARE l public.festival_settlement_lines%ROWTYPE;s public.festival_financial_settlements%ROWTYPE;pay public.festival_settlement_payments%ROWTYPE;tx uuid;attempt integer;BEGIN SELECT * INTO l FROM public.festival_settlement_lines WHERE id=p_line_id FOR UPDATE;SELECT * INTO s FROM public.festival_financial_settlements WHERE id=l.settlement_id;IF l.status IN('paid','waived') OR EXISTS(SELECT 1 FROM public.festival_settlement_receipts WHERE settlement_line_id=l.id) THEN RETURN true;END IF;IF l.line_type='tax_liability' THEN RETURN true;END IF;attempt:=coalesce((SELECT max(x.attempt) FROM public.festival_settlement_payments x WHERE x.settlement_line_id=l.id),0)+1;IF l.net_amount_minor=0 THEN UPDATE public.festival_settlement_lines SET status='waived',completed_at=now() WHERE id=l.id;INSERT INTO public.festival_settlement_receipts(settlement_line_id,receipt)VALUES(l.id,jsonb_build_object('status','waived','amountMinor',0));RETURN true;END IF;INSERT INTO public.festival_settlement_payments(settlement_line_id,attempt,amount_minor,currency_code,status,idempotency_key)VALUES(l.id,attempt,l.net_amount_minor,l.currency_code,'processing','festival-settlement-line:'||l.id||':attempt:'||attempt)RETURNING * INTO pay;UPDATE public.festival_settlement_lines SET status='processing' WHERE id=l.id;
 BEGIN
  tx:=public.finance_transfer(l.payer_type::public.financial_owner_type,l.payer_id,l.recipient_type::public.financial_owner_type,l.recipient_id,l.net_amount_minor,'festival_payment','Festival settlement: '||replace(l.line_type,'_',' '),'festival-settlement-line:'||l.id,'festival_settlement_line',l.id,p_actor,jsonb_build_object('settlementId',s.id,'currencyCode',l.currency_code,'formulaVersion',l.formula_version));
  UPDATE public.festival_settlement_payments SET status='paid',financial_transaction_id=tx,completed_at=now() WHERE id=pay.id;UPDATE public.festival_settlement_lines SET status='paid',completed_at=now() WHERE id=l.id;INSERT INTO public.festival_settlement_receipts(settlement_line_id,payment_id,canonical_transaction_id,receipt)VALUES(l.id,pay.id,tx,jsonb_build_object('status','paid','amountMinor',l.net_amount_minor,'currencyCode',l.currency_code));
  IF l.line_type='refund' THEN UPDATE public.festival_ticket_refund_obligations SET status='completed',processed_at=now() WHERE id=l.source_id AND EXISTS(SELECT 1 FROM public.financial_transactions WHERE id=tx AND status='completed');UPDATE public.festival_ticket_sales SET status='refunded',refunded_at=now() WHERE id=(SELECT festival_ticket_sale_id FROM public.festival_ticket_refund_obligations WHERE id=l.source_id);END IF;
  IF l.line_type='sponsor_receivable' THEN UPDATE public.festival_financial_receivables SET status='settled' WHERE id=l.source_id;END IF;
  IF l.line_type='artist_fee' THEN UPDATE public.festival_financial_commitments SET status='settled' WHERE artist_booking_id=l.source_id;END IF;
  INSERT INTO public.festival_launch_events(festival_launch_id,event_type,recipient_profile_id,channel,dedupe_key,payload)VALUES(s.festival_launch_id,l.line_type||'_payment_completed',CASE WHEN l.recipient_type='player' THEN l.recipient_id END,'notification','festival-settlement-payment:'||l.id,jsonb_build_object('route','/festivals/settlement/'||s.id,'status','paid','amountMinor',l.net_amount_minor,'currencyCode',l.currency_code)) ON CONFLICT(dedupe_key) DO NOTHING;RETURN true;
 EXCEPTION WHEN OTHERS THEN UPDATE public.festival_settlement_payments SET status='failed',completed_at=now() WHERE id=pay.id;UPDATE public.festival_settlement_lines SET status=CASE WHEN SQLERRM ILIKE '%insufficient%' THEN 'outstanding' ELSE 'failed' END WHERE id=l.id;INSERT INTO public.festival_settlement_failures(settlement_id,settlement_line_id,payment_id,error_code,retryable,attempt,private_detail)VALUES(s.id,l.id,pay.id,CASE WHEN SQLERRM ILIKE '%insufficient%' THEN 'insufficient_funds' ELSE 'finance_service_failure' END,true,attempt,left(SQLERRM,500));RETURN false;END;
END$$;

CREATE FUNCTION public.execute_festival_settlement(p_settlement_id uuid,p_expected_version integer,p_idempotency_key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$DECLARE a uuid:=public._caller_profile_id();s public.festival_financial_settlements%ROWTYPE;o public.festival_runtime_outcome_snapshots%ROWTYPE;x record;req public.festival_settlement_requests%ROWTYPE;failed integer;snap jsonb;sid uuid;BEGIN SELECT * INTO s FROM public.festival_financial_settlements WHERE id=p_settlement_id FOR UPDATE;IF NOT public._festival_settlement_owner(s.id,a) THEN RAISE EXCEPTION 'festival_settlement_forbidden';END IF;IF s.version<>p_expected_version THEN RAISE EXCEPTION 'festival_settlement_stale';END IF;IF s.status NOT IN('settlement_review','partially_settled','settlement_failed') THEN RAISE EXCEPTION 'festival_settlement_invalid_transition';END IF;SELECT * INTO o FROM public.festival_runtime_outcome_snapshots WHERE runtime_session_id=s.runtime_session_id;IF o.content_digest<>s.runtime_outcome_digest OR NOT EXISTS(SELECT 1 FROM public.festival_settlement_snapshots WHERE id=s.review_snapshot_id AND content_digest=encode(digest(snapshot::text,'sha256'),'hex')) THEN RAISE EXCEPTION 'festival_settlement_snapshot_changed';END IF;INSERT INTO public.festival_settlement_requests(settlement_id,runtime_session_id,actor_profile_id,action,idempotency_key,payload_hash)VALUES(s.id,s.runtime_session_id,a,'execute',p_idempotency_key,encode(digest(s.id::text||p_expected_version,'sha256'),'hex')) ON CONFLICT(actor_profile_id,action,idempotency_key) DO UPDATE SET idempotency_key=excluded.idempotency_key RETURNING * INTO req;IF req.status='completed' THEN RETURN req.result;END IF;UPDATE public.festival_financial_settlements SET status='settling',version=version+1,updated_at=now() WHERE id=s.id RETURNING * INTO s;INSERT INTO public.festival_settlement_audit(settlement_id,actor_profile_id,event_type,previous_status,new_status,version,dedupe_key)VALUES(s.id,a,'settlement_started','settlement_review','settling',s.version,'execute:'||p_idempotency_key) ON CONFLICT DO NOTHING;
 FOR x IN SELECT id FROM public.festival_settlement_lines WHERE settlement_id=s.id AND status IN('pending','failed','outstanding') AND line_type<>'tax_liability' ORDER BY priority,id LOOP PERFORM public._process_festival_settlement_line(x.id,a);END LOOP;
 SELECT count(*) INTO failed FROM public.festival_settlement_lines WHERE settlement_id=s.id AND status IN('pending','processing','failed','outstanding') AND line_type<>'tax_liability';
 UPDATE public.festival_financial_settlements SET status=CASE WHEN failed=0 THEN 'settled' ELSE 'partially_settled' END,version=version+1,total_revenue_minor=coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type IN('ticket_revenue','vendor_revenue','festival_merch_revenue','artist_merch_revenue','sponsor_receivable','other_income')),0),total_cost_minor=coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type IN('artist_fee','staff_wage','supplier_invoice','refund','platform_fee','inventory_cost','other_expense')),0),cash_received_minor=coalesce((SELECT sum(l.net_amount_minor) FROM public.festival_settlement_lines l WHERE l.settlement_id=s.id AND l.status='paid' AND l.line_type IN('ticket_revenue','vendor_revenue','festival_merch_revenue','artist_merch_revenue','sponsor_receivable','other_income')),0),cash_paid_minor=coalesce((SELECT sum(l.net_amount_minor) FROM public.festival_settlement_lines l WHERE l.settlement_id=s.id AND l.status='paid' AND l.line_type IN('artist_fee','staff_wage','supplier_invoice','refund','platform_fee','inventory_cost','other_expense')),0),outstanding_receivables_minor=coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type IN('sponsor_receivable','other_income') AND status IN('pending','failed','outstanding')),0),outstanding_payables_minor=coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type NOT IN('ticket_revenue','vendor_revenue','festival_merch_revenue','artist_merch_revenue','sponsor_receivable','other_income') AND status IN('pending','failed','outstanding')),0),settled_at=CASE WHEN failed=0 THEN now() ELSE NULL END,updated_at=now() WHERE id=s.id RETURNING * INTO s;UPDATE public.festival_financial_settlements SET net_profit_loss_minor=total_revenue_minor-total_cost_minor WHERE id=s.id RETURNING * INTO s;
 IF s.status='settled' THEN snap:=jsonb_build_object('settlement',to_jsonb(s),'lines',(SELECT jsonb_agg(to_jsonb(l) ORDER BY priority,id) FROM public.festival_settlement_lines l WHERE settlement_id=s.id),'receipts',(SELECT jsonb_agg(to_jsonb(r2)) FROM public.festival_settlement_receipts r2 JOIN public.festival_settlement_lines l2 ON l2.id=r2.settlement_line_id WHERE l2.settlement_id=s.id),'taxLiabilitiesRemainAccrued',true);INSERT INTO public.festival_settlement_snapshots(settlement_id,snapshot_type,runtime_outcome_snapshot_id,snapshot,content_digest,formula_versions)VALUES(s.id,'final',o.id,snap,encode(digest(snap::text,'sha256'),'hex'),jsonb_build_object('settlement',s.formula_version)) ON CONFLICT(settlement_id,snapshot_type) DO NOTHING RETURNING id INTO sid;IF sid IS NULL THEN SELECT id INTO sid FROM public.festival_settlement_snapshots WHERE settlement_id=s.id AND snapshot_type='final';END IF;UPDATE public.festival_financial_settlements SET final_snapshot_id=sid WHERE id=s.id RETURNING * INTO s;END IF;
 INSERT INTO public.festival_settlement_audit(settlement_id,actor_profile_id,event_type,previous_status,new_status,version,dedupe_key)VALUES(s.id,a,CASE WHEN s.status='settled' THEN 'settlement_completed' ELSE 'settlement_partially_completed' END,'settling',s.status,s.version,'execute-result:'||p_idempotency_key);INSERT INTO public.festival_launch_events(festival_launch_id,event_type,recipient_profile_id,channel,dedupe_key,payload)VALUES(s.festival_launch_id,CASE WHEN s.status='settled' THEN 'settlement_completed' ELSE 'settlement_partially_completed' END,a,'notification','festival-settlement-result:'||p_idempotency_key,jsonb_build_object('route','/festivals/settlement/'||s.id,'status',s.status,'outstandingPayablesMinor',s.outstanding_payables_minor,'currencyCode',s.currency_code)) ON CONFLICT DO NOTHING;UPDATE public.festival_settlement_requests SET status='completed',result=public._festival_settlement_json(s),completed_at=now() WHERE id=req.id;RETURN public._festival_settlement_json(s);END$$;

CREATE FUNCTION public.retry_festival_settlement(p_settlement_id uuid,p_expected_version integer,p_idempotency_key uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$SELECT public.execute_festival_settlement(p_settlement_id,p_expected_version,p_idempotency_key)$$;
CREATE FUNCTION public.retry_festival_settlement_line(p_settlement_line_id uuid,p_expected_version integer,p_idempotency_key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$DECLARE l public.festival_settlement_lines%ROWTYPE;s public.festival_financial_settlements%ROWTYPE;a uuid:=public._caller_profile_id();BEGIN SELECT * INTO l FROM public.festival_settlement_lines WHERE id=p_settlement_line_id;SELECT * INTO s FROM public.festival_financial_settlements WHERE id=l.settlement_id FOR UPDATE;IF NOT public._festival_settlement_owner(s.id,a) THEN RAISE EXCEPTION 'festival_settlement_forbidden';END IF;IF s.version<>p_expected_version THEN RAISE EXCEPTION 'festival_settlement_stale';END IF;IF l.status NOT IN('failed','outstanding') THEN RAISE EXCEPTION 'festival_settlement_line_not_retryable';END IF;PERFORM public._process_festival_settlement_line(l.id,a);UPDATE public.festival_financial_settlements SET version=version+1,updated_at=now() WHERE id=s.id RETURNING * INTO s;RETURN public._festival_settlement_json(s);END$$;
CREATE FUNCTION public.get_festival_settlement(p_runtime_session_id uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$DECLARE s public.festival_financial_settlements%ROWTYPE;BEGIN SELECT * INTO s FROM public.festival_financial_settlements WHERE runtime_session_id=p_runtime_session_id;IF s.id IS NULL THEN RAISE EXCEPTION 'festival_settlement_not_ready';END IF;IF NOT public._festival_settlement_owner(s.id,public._caller_profile_id()) THEN RAISE EXCEPTION 'festival_settlement_forbidden';END IF;RETURN public._festival_settlement_json(s);END$$;
CREATE FUNCTION public.get_festival_settlement_lines(p_settlement_id uuid,p_status text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$BEGIN IF NOT public._festival_settlement_owner(p_settlement_id,public._caller_profile_id()) THEN RAISE EXCEPTION 'festival_settlement_forbidden';END IF;RETURN coalesce((SELECT jsonb_agg(jsonb_build_object('id',l.id,'settlementId',l.settlement_id,'lineType',l.line_type,'sourceType',l.source_type,'sourceId',l.source_id,'recipientType',l.recipient_type,'recipientId',l.recipient_id,'payerType',l.payer_type,'payerId',l.payer_id,'grossAmountMinor',l.gross_amount_minor,'taxAmountMinor',l.tax_amount_minor,'feeAmountMinor',l.fee_amount_minor,'netAmountMinor',l.net_amount_minor,'currencyCode',l.currency_code,'status',l.status,'priority',l.priority,'formulaVersion',l.formula_version,'calculationMetadata',l.calculation_metadata) ORDER BY l.priority,l.id) FROM public.festival_settlement_lines l WHERE l.settlement_id=p_settlement_id AND (p_status IS NULL OR l.status=p_status)),'[]');END$$;
CREATE FUNCTION public.get_festival_settlement_summary(p_settlement_id uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$DECLARE s public.festival_financial_settlements%ROWTYPE;BEGIN SELECT * INTO s FROM public.festival_financial_settlements WHERE id=p_settlement_id;IF NOT public._festival_settlement_owner(s.id,public._caller_profile_id()) THEN RAISE EXCEPTION 'festival_settlement_forbidden';END IF;RETURN jsonb_build_object('ticketRevenueMinor',coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type='ticket_revenue'),0),'vendorRevenueMinor',coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type='vendor_revenue'),0),'festivalMerchRevenueMinor',coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type='festival_merch_revenue'),0),'artistMerchGrossMinor',coalesce((SELECT sum(gross_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type='artist_merch_revenue'),0),'sponsorshipIncomeMinor',coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type='sponsor_receivable'),0),'totalRevenueMinor',s.total_revenue_minor,'artistCostsMinor',coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type='artist_fee'),0),'staffCostsMinor',coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type='staff_wage'),0),'supplierCostsMinor',coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type='supplier_invoice'),0),'refundsMinor',coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type='refund'),0),'taxLiabilitiesMinor',coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type='tax_liability'),0),'platformFeesMinor',coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type='platform_fee'),0),'otherCostsMinor',coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type IN('inventory_cost','other_expense')),0),'netProfitLossMinor',s.net_profit_loss_minor,'cashReceivedMinor',s.cash_received_minor,'cashPaidMinor',s.cash_paid_minor,'outstandingReceivablesMinor',s.outstanding_receivables_minor,'outstandingPayablesMinor',s.outstanding_payables_minor,'nonCashContributionsMinor',coalesce((SELECT sum((calculation_metadata->>'inKindContributionMinor')::bigint) FROM public.festival_settlement_lines WHERE settlement_id=s.id AND line_type='sponsor_receivable'),0),'currencyCode',s.currency_code);END$$;

CREATE FUNCTION public._festival_participant_statement(p_settlement_id uuid,p_kind text,p_actor uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$DECLARE pid uuid;BEGIN
 IF p_kind='artist' THEN SELECT coalesce(b.artist_profile_id,b.band_id) INTO pid FROM public.festival_artist_bookings b JOIN public.festival_settlement_lines l ON l.source_id=b.id AND l.source_type='festival_artist_booking' WHERE l.settlement_id=p_settlement_id AND ((b.artist_profile_id=p_actor) OR (b.band_id IS NOT NULL AND EXISTS(SELECT 1 FROM public.band_members bm WHERE bm.band_id=b.band_id AND bm.profile_id=p_actor))) LIMIT 1;
 ELSIF p_kind='staff' THEN SELECT a.profile_id INTO pid FROM public.festival_settlement_lines l JOIN public.festival_runtime_staff_checkins c ON c.id=l.source_id JOIN public.festival_staff_shifts sh ON sh.id=c.staff_shift_id JOIN public.festival_staff_assignments a ON a.id=sh.staff_assignment_id WHERE l.settlement_id=p_settlement_id AND a.profile_id=p_actor LIMIT 1;
 ELSIF p_kind='supplier' THEN SELECT c.supplier_company_id INTO pid FROM public.festival_settlement_lines l JOIN public.festival_supplier_contracts c ON c.id=l.source_id JOIN public.companies co ON co.id=c.supplier_company_id WHERE l.settlement_id=p_settlement_id AND co.owner_id=auth.uid() LIMIT 1;
 ELSIF p_kind='sponsor' THEN SELECT c.company_id INTO pid FROM public.festival_settlement_lines l JOIN public.festival_financial_receivables fr ON fr.id=l.source_id JOIN public.festival_sponsor_contracts c ON c.id=fr.sponsor_contract_id JOIN public.companies co ON co.id=c.company_id WHERE l.settlement_id=p_settlement_id AND co.owner_id=auth.uid() LIMIT 1;END IF;
 IF pid IS NULL THEN RAISE EXCEPTION 'festival_settlement_forbidden';END IF;
 RETURN jsonb_build_object('participantType',p_kind,'participantId',pid,'currencyCode',(SELECT currency_code FROM public.festival_financial_settlements WHERE id=p_settlement_id),'items',coalesce((SELECT jsonb_agg(jsonb_build_object('label',replace(line_type,'_',' '),'amountMinor',net_amount_minor,'metadata',calculation_metadata) ORDER BY priority,id) FROM public.festival_settlement_lines WHERE settlement_id=p_settlement_id AND recipient_id=pid OR (p_kind='sponsor' AND settlement_id=p_settlement_id AND payer_id=pid)),'[]'),'totalPaidMinor',coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=p_settlement_id AND status='paid' AND (recipient_id=pid OR (p_kind='sponsor' AND payer_id=pid))),0),'outstandingAmountMinor',coalesce((SELECT sum(net_amount_minor) FROM public.festival_settlement_lines WHERE settlement_id=p_settlement_id AND status IN('pending','failed','outstanding') AND (recipient_id=pid OR (p_kind='sponsor' AND payer_id=pid))),0));END$$;
CREATE FUNCTION public.get_my_festival_artist_statement(p_settlement_id uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$SELECT public._festival_participant_statement(p_settlement_id,'artist',public._caller_profile_id())$$;
CREATE FUNCTION public.get_my_festival_staff_statement(p_settlement_id uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$SELECT public._festival_participant_statement(p_settlement_id,'staff',public._caller_profile_id())$$;
CREATE FUNCTION public.get_my_festival_supplier_statement(p_settlement_id uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$SELECT public._festival_participant_statement(p_settlement_id,'supplier',public._caller_profile_id())$$;
CREATE FUNCTION public.get_my_festival_sponsor_statement(p_settlement_id uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$SELECT public._festival_participant_statement(p_settlement_id,'sponsor',public._caller_profile_id())$$;
CREATE FUNCTION public.resolve_festival_settlement_dispute(p_settlement_id uuid,p_expected_version integer,p_resolution text,p_idempotency_key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$DECLARE s public.festival_financial_settlements%ROWTYPE;a uuid:=public._caller_profile_id();BEGIN SELECT * INTO s FROM public.festival_financial_settlements WHERE id=p_settlement_id FOR UPDATE;IF NOT coalesce(public.has_role(auth.uid(),'admin'::public.app_role),false) THEN RAISE EXCEPTION 'festival_settlement_forbidden';END IF;IF s.version<>p_expected_version OR s.status<>'disputed' THEN RAISE EXCEPTION 'festival_settlement_stale';END IF;IF char_length(btrim(p_resolution))<10 THEN RAISE EXCEPTION 'festival_settlement_resolution_required';END IF;UPDATE public.festival_settlement_disputes SET status='resolved',resolution=p_resolution,resolved_at=now() WHERE settlement_id=s.id AND status='open';UPDATE public.festival_financial_settlements SET status='settled',version=version+1,updated_at=now() WHERE id=s.id RETURNING * INTO s;INSERT INTO public.festival_settlement_audit(settlement_id,actor_profile_id,event_type,previous_status,new_status,version,metadata,dedupe_key)VALUES(s.id,a,'dispute_resolved','disputed','settled',s.version,jsonb_build_object('resolution',p_resolution),'dispute:'||p_idempotency_key);RETURN public._festival_settlement_json(s);END$$;

DO $$DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['festival_financial_settlements','festival_settlement_snapshots','festival_settlement_lines','festival_settlement_payments','festival_settlement_receipts','festival_settlement_failures','festival_settlement_requests','festival_settlement_audit','festival_settlement_disputes'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC,anon,authenticated',t);END LOOP;END$$;
REVOKE ALL ON FUNCTION public._process_festival_settlement_line(uuid,uuid),public._festival_participant_statement(uuid,text,uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_festival_settlement(uuid),public.get_festival_settlement_summary(uuid),public.get_festival_settlement_lines(uuid,text),public.get_my_festival_artist_statement(uuid),public.get_my_festival_staff_statement(uuid),public.get_my_festival_supplier_statement(uuid),public.get_my_festival_sponsor_statement(uuid),public.prepare_festival_settlement(uuid,integer,uuid),public.execute_festival_settlement(uuid,integer,uuid),public.retry_festival_settlement(uuid,integer,uuid),public.retry_festival_settlement_line(uuid,integer,uuid),public.resolve_festival_settlement_dispute(uuid,integer,text,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public._process_festival_settlement_line(uuid,uuid) TO service_role;
COMMENT ON TABLE public.festival_settlement_snapshots IS 'Immutable Phase 9A review/final statements. UPDATE and DELETE are revoked.';
COMMENT ON COLUMN public.festival_financial_settlements.net_profit_loss_minor IS 'Festival-company result; never distributed automatically to the owner.';
