// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/lib/supabase-types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const REFERRAL_STORAGE_KEY = "rockmundo_referral_code";
const REFERRAL_CODE_PATTERN = /^RM[A-Z0-9]{6,18}$/;
const REFERRAL_BAND_STORAGE_KEY = "rockmundo_referral_band";
const REFERRAL_SOURCE_STORAGE_KEY = "rockmundo_referral_source";
const REFERRAL_SOURCE_PATTERN = /^[a-z0-9_]{2,40}$/;
const REFERRAL_CAMPAIGN_STORAGE_KEY = "rockmundo_referral_campaign";
const REFERRAL_CAMPAIGN_PATTERN = /^[a-z0-9][a-z0-9_-]{1,39}$/;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing Supabase environment configuration. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

const getPendingReferralCode = () => {
  if (typeof window === "undefined") return null;
  const code = localStorage.getItem(REFERRAL_STORAGE_KEY)?.trim().toUpperCase();
  return code && REFERRAL_CODE_PATTERN.test(code) ? code : null;
};

// Referral links use /auth?ref=CODE. Persist the code before email verification redirects.
// When a signup follows, also attach it to user metadata so the database trigger captures
// attribution immediately even if email confirmation happens on another browser or device.
if (typeof window !== "undefined") {
  const referralParam = new URLSearchParams(window.location.search).get("ref")?.trim().toUpperCase();
  if (referralParam && REFERRAL_CODE_PATTERN.test(referralParam)) {
    localStorage.setItem(REFERRAL_STORAGE_KEY, referralParam);
    const sourceParam = new URLSearchParams(window.location.search).get("source")?.trim().toLowerCase();
    if (sourceParam && REFERRAL_SOURCE_PATTERN.test(sourceParam)) {
      localStorage.setItem(REFERRAL_SOURCE_STORAGE_KEY, sourceParam);
    }
    const campaignParam = new URLSearchParams(window.location.search).get("campaign")?.trim().toLowerCase();
    if (campaignParam && REFERRAL_CAMPAIGN_PATTERN.test(campaignParam)) {
      localStorage.setItem(REFERRAL_CAMPAIGN_STORAGE_KEY, campaignParam);
    }
    const bandParam = new URLSearchParams(window.location.search).get("band")?.trim();
    if (bandParam && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(bandParam)) {
      localStorage.setItem(REFERRAL_BAND_STORAGE_KEY, bandParam);
    }
  }

  // Keep this wrapper deliberately untyped: Supabase's signUp overload is highly generic and
  // expanding it here makes the project typecheck pathologically slow. Runtime credentials keep
  // the same shape; we only merge referral_code into options.data when one is pending.
  const auth = supabase.auth as any;
  const originalSignUp = auth.signUp.bind(auth);
  auth.signUp = (credentials: any) => {
    const pendingCode = getPendingReferralCode();
    if (!pendingCode) return originalSignUp(credentials);

    return originalSignUp({
      ...credentials,
      options: {
        ...credentials.options,
        data: {
          ...credentials.options?.data,
          referral_code: pendingCode,
          referral_band_id: localStorage.getItem(REFERRAL_BAND_STORAGE_KEY) || undefined,
          referral_source: localStorage.getItem(REFERRAL_SOURCE_STORAGE_KEY) || undefined,
          referral_campaign: localStorage.getItem(REFERRAL_CAMPAIGN_STORAGE_KEY) || undefined,
        },
      },
    });
  };

  let bindingReferral = false;
  supabase.auth.onAuthStateChange((_event, session) => {
    const pendingCode = getPendingReferralCode();
    if (!session?.user || !pendingCode || bindingReferral) return;

    bindingReferral = true;
    // Avoid awaiting Supabase work directly inside the auth callback.
    setTimeout(async () => {
      try {
        const pendingSource = localStorage.getItem(REFERRAL_SOURCE_STORAGE_KEY)?.trim().toLowerCase();
        const { error } = await (supabase as any).rpc("bind_referral_code", {
          p_code: pendingCode,
          p_source: pendingSource && REFERRAL_SOURCE_PATTERN.test(pendingSource) ? pendingSource : undefined,
        });
        if (!error || /already_bound/i.test(error?.message ?? "")) {
          const pendingCampaign = localStorage.getItem(REFERRAL_CAMPAIGN_STORAGE_KEY)?.trim().toLowerCase();
          if (pendingCampaign && REFERRAL_CAMPAIGN_PATTERN.test(pendingCampaign)) {
            const { error: campaignError } = await (supabase as any).rpc("attach_my_referral_campaign", { p_campaign: pendingCampaign });
            if (!campaignError || /already.*attached/i.test(campaignError?.message ?? "")) {
              localStorage.removeItem(REFERRAL_CAMPAIGN_STORAGE_KEY);
            } else {
              console.warn("[REFERRAL] Unable to attach pending referral campaign", campaignError.message);
            }
          }
          const pendingBand = localStorage.getItem(REFERRAL_BAND_STORAGE_KEY)?.trim();
          if (pendingBand && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(pendingBand)) {
            const { error: bandError } = await (supabase as any).rpc("attach_my_referral_band", { p_band_id: pendingBand });
            if (!bandError) {
              localStorage.removeItem(REFERRAL_BAND_STORAGE_KEY);
            } else {
              console.warn("[REFERRAL] Unable to attach pending referral band", bandError.message);
            }
          }
          localStorage.removeItem(REFERRAL_STORAGE_KEY);
          localStorage.removeItem(REFERRAL_SOURCE_STORAGE_KEY);
        } else {
          console.warn("[REFERRAL] Unable to bind pending referral code", error.message);
        }
      } catch (error) {
        console.warn("[REFERRAL] Unable to bind pending referral code", error);
      } finally {
        bindingReferral = false;
      }
    }, 0);
  });
}
