// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/lib/supabase-types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const REFERRAL_STORAGE_KEY = "rockmundo_referral_code";
const REFERRAL_CODE_PATTERN = /^RM[A-Z0-9]{6,18}$/;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing Supabase environment configuration. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

export const getPendingReferralCode = () => {
  if (typeof window === "undefined") return null;
  const code = localStorage.getItem(REFERRAL_STORAGE_KEY)?.trim().toUpperCase();
  return code && REFERRAL_CODE_PATTERN.test(code) ? code : null;
};

// Referral links use /auth?ref=CODE. Persist the code before email verification redirects.
if (typeof window !== "undefined") {
  const referralParam = new URLSearchParams(window.location.search).get("ref")?.trim().toUpperCase();
  if (referralParam && REFERRAL_CODE_PATTERN.test(referralParam)) {
    localStorage.setItem(REFERRAL_STORAGE_KEY, referralParam);
  }

  let bindingReferral = false;
  supabase.auth.onAuthStateChange((_event, session) => {
    const pendingCode = getPendingReferralCode();
    if (!session?.user || !pendingCode || bindingReferral) return;

    bindingReferral = true;
    // Avoid awaiting Supabase work directly inside the auth callback.
    setTimeout(async () => {
      try {
        const { error } = await (supabase as any).rpc("bind_referral_code", { p_code: pendingCode });
        if (!error) {
          localStorage.removeItem(REFERRAL_STORAGE_KEY);
        } else if (/already_bound/i.test(error.message ?? "")) {
          localStorage.removeItem(REFERRAL_STORAGE_KEY);
        } else {
          console.warn("[REFERRAL] Unable to bind pending referral code", error.message);
        }
      } catch (error) {
        console.warn("[REFERRAL] Unable to bind pending referral code", error);
      } finally {
        bindingReferral = false;
      }
    }, 0);
  });
}
