import {z} from "zod";
import {supabase} from "@/integrations/supabase/client";
import {FESTIVAL_UPGRADE_KEYS,FESTIVAL_UPGRADE_MESSAGES,type FestivalCompanyUpgradeState,type FestivalUpgradePreview,type FestivalUpgradeKey} from "./types";
const rpc=supabase.rpc.bind(supabase) as unknown as (name:string,args?:Record<string,unknown>)=>Promise<{data:unknown;error:{message?:string}|null}>;
const error=(e:{message?:string})=>{const code=Object.keys(FESTIVAL_UPGRADE_MESSAGES).find(x=>e.message?.includes(x))??"FESTIVAL_UPGRADE_UNAVAILABLE";return Object.assign(new Error(FESTIVAL_UPGRADE_MESSAGES[code]??"Festival upgrades are temporarily unavailable."),{code});};
const effect=z.record(z.string(),z.union([z.number(),z.boolean()]));
const windowSchema=z.object({limit:z.number().int().positive(),used:z.number().int().nonnegative(),remaining:z.number().int().nonnegative(),windowDays:z.number().int().positive(),serverNow:z.string().datetime({offset:true}),nextAvailableAt:z.string().datetime({offset:true}).nullable()});
const category=z.object({key:z.enum(FESTIVAL_UPGRADE_KEYS),displayName:z.string(),description:z.string(),ownedLevel:z.number().int().nonnegative(),activeLevel:z.number().int().nonnegative(),effectiveLevel:z.number().int().nonnegative(),maximumLevel:z.number().int().positive(),bandKey:z.string(),bandName:z.string(),bandStartLevel:z.number().int().positive(),bandEndLevel:z.number().int().positive(),nextMilestoneLevel:z.number().int().positive().nullable(),nextMilestoneName:z.string().nullable(),levelsUntilMilestone:z.number().int().nonnegative().nullable(),status:z.enum(["not_installed","purchased","building","active","cancelled","failed"]),currentUpkeepMinor:z.number().nonnegative(),nextLevel:z.number().int().positive().nullable(),nextCostMinor:z.number().nonnegative().nullable(),nextUpkeepMinor:z.number().nonnegative().nullable(),buildDurationHours:z.number().nonnegative().nullable(),effects:effect,nextEffects:effect.nullable(),effectDelta:effect,missingRequirements:z.array(z.object({code:z.string(),message:z.string()})),affordable:z.boolean(),construction:z.record(z.string(),z.unknown()),delinquent:z.boolean()}).superRefine((c,ctx)=>{if(c.ownedLevel>c.maximumLevel||c.activeLevel>c.ownedLevel||c.effectiveLevel>c.activeLevel||c.bandEndLevel>c.maximumLevel||(c.ownedLevel===c.maximumLevel&&c.nextLevel!==null))ctx.addIssue({code:"custom",message:"invalid authoritative levels"})});
const licence=z.object({current:z.object({key:z.string(),name:z.string(),status:z.string()}).nullable(),highestEligible:z.object({key:z.string(),name:z.string()}).nullable(),next:z.object({key:z.string(),name:z.string(),feeMinor:z.number()}).nullable(),requirements:z.array(z.object({code:z.string(),description:z.string(),complete:z.boolean()}))});
const stateSchema=z.object({festivalCompanyId:z.string().uuid(),catalogueVersion:z.number().int().positive(),companyVersion:z.number().int().nonnegative(),currencyCode:z.string(),availableBalanceMinor:z.number(),purchaseWindow:windowSchema,categories:z.array(category).length(11),licence}).superRefine((v,ctx)=>{if(!FESTIVAL_UPGRADE_KEYS.every(k=>v.categories.some(c=>c.key===k)))ctx.addIssue({code:"custom",message:"missing category"})});
const previewSchema=z.object({category,catalogueVersion:z.number().int().positive(),companyVersion:z.number().int().nonnegative(),purchaseWindow:windowSchema,balanceMinor:z.number(),remainingBalanceMinor:z.number(),eligible:z.boolean(),reasonCodes:z.array(z.string()),licenceImplications:z.array(z.string())});
function invalid():never{throw Object.assign(new Error(FESTIVAL_UPGRADE_MESSAGES.FESTIVAL_UPGRADE_RESPONSE_INVALID),{code:"FESTIVAL_UPGRADE_RESPONSE_INVALID"});}
function state(value:unknown):FestivalCompanyUpgradeState{const parsed=stateSchema.safeParse(value);if(!parsed.success)invalid();return parsed.data as FestivalCompanyUpgradeState}
export async function getFestivalCompanyUpgrades(id:string){const {data,error:e}=await rpc("get_festival_company_upgrades",{p_festival_company_id:id});if(e)throw error(e);return state(data)}
export async function previewFestivalUpgrade(input:{festivalCompanyId:string;categoryKey:FestivalUpgradeKey}){const {data,error:e}=await rpc("get_festival_upgrade_purchase_preview",{p_festival_company_id:input.festivalCompanyId,p_category_key:input.categoryKey});if(e)throw error(e);const parsed=previewSchema.safeParse(data);if(!parsed.success)invalid();return parsed.data as FestivalUpgradePreview}
export async function purchaseFestivalUpgrade(input:{festivalCompanyId:string;categoryKey:FestivalUpgradeKey;nextLevel:number;catalogueVersion:number;companyVersion:number;idempotencyKey:string}){const {data,error:e}=await rpc("purchase_festival_company_upgrade",{p_festival_company_id:input.festivalCompanyId,p_category_key:input.categoryKey,p_requested_level:input.nextLevel,p_expected_catalogue_version:input.catalogueVersion,p_expected_company_version:input.companyVersion,p_idempotency_key:input.idempotencyKey});if(e)throw error(e);return state(data)}
