import { useMemo, useState } from "react";
import { AdminRoute } from "@/components/AdminRoute";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { GigViewerShell } from "@/features/gig-experience/viewer/GigViewerShell";
import { buildGigViewerReplay } from "@/features/gig-experience/events/generator";
import type { GigExperienceDTO } from "@/features/gig-experience/types";
import { supabase } from "@/integrations/supabase/client";

const presets = ["Empty club","Half-full small venue","Sold-out club","Average theatre show","Poor arena booking","Sold-out arena","Solo acoustic-style act","Standard four-piece band","Large ensemble","Rising momentum","Major recovery","No encore","Excellent encore","Mixed audio availability","No song audio"];

function fixtureExperience(preset: string): GigExperienceDTO {
  const soldOut = /Sold-out/.test(preset), empty = /Empty/.test(preset), poor = /Poor/.test(preset), solo = /Solo/.test(preset), large = /Large/.test(preset), noAudio = /No song audio/.test(preset);
  const capacity = /arena/i.test(preset) ? 18000 : /theatre/i.test(preset) ? 1500 : 250; const attendance = empty ? 0 : soldOut ? capacity : Math.round(capacity * (/Half/.test(preset) ? .5 : .7));
  const songs = Array.from({ length: /Large|arena/i.test(preset) ? 5 : 3 }, (_, i) => ({ id:`perf-${i}`, songId:`fixture-song-${i}`, position:i+1, title:["Neon Doors","Crowd Voltage","Last Encore","Static Hearts","Afterglow"][i], audio: noAudio || i % 2 === 1 && /Mixed/.test(preset) ? { available:false, sourceType:"none" as const, url:null, durationSeconds:null, generationStatus:null, permissionState:"admin_demo" as const, reasonUnavailable:"fixture_disabled" } : { available:true, sourceType:"fixture" as const, url:"/music/christmas-mothercluckers-v2.mp3", durationSeconds:180, generationStatus:"completed", permissionState:"admin_demo" as const }, performanceScore:{ status:"available" as const, value: poor ? 8+i : 16+i*2, source:"derived" as const }, crowdResponse:{ status:"available" as const, value: poor ? "quiet" : "engaged", source:"derived" as const }, contributions:{ songQuality:{status:"available" as const,value:4}, rehearsal:{status:"available" as const,value:3}, chemistry:{status:"available" as const,value:3}, equipment:{status:"available" as const,value:3}, crew:{status:"available" as const,value:2}, memberSkill:{status:"available" as const,value:3} } }));
  return { schemaVersion:1, gig:{ id:"fixture-gig", bandId:null, status:"completed", scheduledDate:"2026-07-11", startedAt:null, completedAt:"2026-07-11T00:00:00Z", ticketPrice:{status:"available",value:20}, venue:{id:"fixture-venue",name:preset,location:"Demo",capacity}}, headline:{ overallRating:{status:"available",value:poor?7:soldOut?23:16}, performanceGrade:{status:"available",value:poor?"D":soldOut?"S":"B"}, verdict:"Demo data — no game records will be changed.", attendance:{status:"available",value:attendance}, capacity:{status:"available",value:capacity}, netProfit:{status:"available",value:attendance*12}, fameGained:{status:"available",value:poor?1:8}, fansGained:{status:"available",value:Math.round(attendance*.1)}, bestSongTitle:{status:"available",value:songs.at(-1)?.title || "None"}}, songs, performers:Array.from({length: solo?1:large?8:4},(_,i)=>({id:`p${i}`,profileId:`p${i}`,displayName:["Alex","Sam","Jo","River","Kai","Dee","Ash","Ren"][i]||`Member ${i+1}`,roleOrInstrument:["Vocals","Guitar","Bass","Drums"][i%4],lineupStatus:"active"})), finances:{ticketRevenue:{status:"available",value:attendance*20},merchRevenue:{status:"available",value:attendance*4},totalRevenue:{status:"available",value:attendance*24},crewCosts:{status:"available",value:400},equipmentWearCost:{status:"available",value:150},venueCost:{status:"available",value:capacity},totalCosts:{status:"available",value:capacity+550},netProfit:{status:"available",value:attendance*24-capacity-550},merchItemsSold:{status:"available",value:Math.round(attendance*.2)}}, progression:{fameGained:{status:"available",value:5},chemistryChange:{status:"available",value:1},totalXpAwarded:{status:"available",value:50},fansGained:{status:"available",value:10},fanConversions:{status:"available",value:5}}, analysis:{equipmentQuality:{status:"available",value:14},crewSkill:{status:"available",value:12},bandChemistry:{status:"available",value:13},memberSkills:{status:"available",value:15},crowdEnergyPeak:{status:"available",value:soldOut?92:55},stageBehaviorUsed:{status:"not_applicable",reason:"fixture"},gearEffects:null,warnings:["Demo data — no game records will be changed."]}, lessons:{worked:["Fixture replay rendered locally."],heldBack:["No database mutations are performed."],recommendations:["Use Real Replay Inspector for stored canonical replay checks."]}, viewer:{ready:true,outcomeId:"fixture-outcome",resultReadyAt:"2026-07-11T00:00:00Z",replayAvailable:true,replay:{viewerVersion:1,durationMs:180000,generationStatus:"ready"}} };
}

export default function GigViewerDemo() {
 const [preset,setPreset]=useState("Sold-out club"); const [open,setOpen]=useState(true); const [search,setSearch]=useState(""); const [rows,setRows]=useState<any[]>([]); const experience=useMemo(()=>fixtureExperience(preset),[preset]);
 const replayPromise=useMemo(()=>buildGigViewerReplay({ replayId:"fixture-replay", outcomeId:"fixture-outcome", generatedAt:"2026-07-11T00:00:00Z", gig:{id:"fixture-gig",completedAt:"2026-07-11T00:00:00Z",actualAttendance:experience.headline.attendance.value,venueCapacity:experience.gig.venue.capacity,overallRating:experience.headline.overallRating.value,netProfit:experience.finances.netProfit.value}, songs:experience.songs.map(s=>({songId:s.songId!,title:s.title,position:s.position-1,performanceScore:s.performanceScore.value})), performers:experience.performers.map(p=>({profileId:p.profileId,displayName:p.displayName,roleOrInstrument:p.roleOrInstrument})) }),[experience]);
 (window as any).__fixtureReplayPromise = replayPromise;
 async function searchReplays(){ const {data}= await supabase.from("gig_viewer_replays").select("id,gig_id,viewer_version,event_schema_version,duration_ms,generation_status,generated_at").eq("generation_status","ready").ilike("gig_id",`%${search}%`).limit(10); setRows(data||[]); }
 return <AdminRoute><main className="container mx-auto space-y-4 p-4"><h1 className="text-3xl font-bold">Admin Gig Viewer Demo</h1><p className="text-muted-foreground">Demo data — no game records will be changed.</p><Card><CardHeader><CardTitle>Fixture presets</CardTitle><CardDescription>Local deterministic presentation-only data; no gig, reward, replay, or song mutations.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2">{presets.map(p=><Button key={p} variant={p===preset?"default":"outline"} onClick={()=>{setPreset(p);setOpen(false);setTimeout(()=>setOpen(true),0)}}>{p}</Button>)}</CardContent></Card><PromiseViewer promise={replayPromise} experience={experience} open={open}/><Card><CardHeader><CardTitle>Audio Diagnostics</CardTitle></CardHeader><CardContent className="space-y-2">{experience.songs.map(s=><div key={s.id} className="flex flex-wrap gap-2 rounded border p-2"><b>{s.title}</b><Badge>{s.audio?.available?"playable":"unplayable"}</Badge><span>{s.audio?.sourceType}</span><span>{s.audio?.durationSeconds ?? "—"}s</span><span>{s.audio?.reasonUnavailable ?? "signed URL not displayed"}</span></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Real Replay Inspector</CardTitle><CardDescription>Read-only search of completed stored replay rows.</CardDescription></CardHeader><CardContent className="space-y-2"><div className="flex gap-2"><Input aria-label="Search gig ID" value={search} onChange={e=>setSearch(e.target.value)} placeholder="gig id"/><Button onClick={searchReplays}>Search completed gigs</Button></div>{rows.length?rows.map(r=><pre key={r.id} className="rounded bg-muted p-2 text-xs">{JSON.stringify({...r,payload:"hidden",validation:"metadata loaded read-only"},null,2)}</pre>):<p className="text-sm text-muted-foreground">No search results.</p>}</CardContent></Card></main></AdminRoute>;
}
function PromiseViewer({promise,experience,open}:{promise:Promise<any>;experience:GigExperienceDTO;open:boolean}){ const [replay,setReplay]=useState<any>(null); useMemo(()=>{promise.then(setReplay)},[promise]); if(!replay) return <Card><CardContent className="p-4">Building deterministic fixture replay…</CardContent></Card>; return <GigViewerShell gigId={replay.gigId} experience={experience} open={open} replayOverride={replay} onViewResult={()=>{}} onClose={()=>{}}/> }
