import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AlertTriangle, CheckCircle2, Clock, Music, Radio, Users } from "lucide-react";
import { useFestivalPerformerCheckIn, useFestivalPerformanceSession, useFestivalSessionArrival, useFestivalSessionReadiness, useFestivalSessionRealtime } from "@/features/festivals/performance/hooks";
import { calculateLateMinutes } from "@/features/festivals/performance/model";

export function ReadinessPanel({ readiness }: { readiness: Record<string, any> | undefined }) {
  const entries = Object.entries(readiness ?? {}).filter(([key]) => key !== "overall");
  return <div className="grid gap-3 md:grid-cols-2">{entries.map(([key, value]) => <Card key={key}><CardHeader className="pb-2"><CardTitle className="capitalize text-base flex items-center justify-between">{key}<Badge variant={(value?.status ?? value?.arrival_readiness) === "blocked" ? "destructive" : "secondary"}>{value?.status ?? value?.arrival_readiness ?? "ready"}</Badge></CardTitle></CardHeader><CardContent className="text-sm space-y-2"><p className="text-muted-foreground">Facts: {JSON.stringify(value?.facts ?? value?.supporting_facts ?? [])}</p>{(value?.blockers?.length ?? 0) > 0 && <p className="text-destructive">Blockers: {value.blockers.join(", ")}</p>}{(value?.warnings?.length ?? 0) > 0 && <p className="text-amber-600">Warnings: {value.warnings.join(", ")}</p>}</CardContent></Card>)}</div>;
}

export function FestivalSessionWorkspace({ sessionId, organiser = false }: { sessionId: string; organiser?: boolean }) {
  useFestivalSessionRealtime(sessionId);
  const session = useFestivalPerformanceSession(sessionId);
  const readiness = useFestivalSessionReadiness(sessionId);
  const arrival = useFestivalSessionArrival(sessionId);
  const checkIn = useFestivalPerformerCheckIn(sessionId);
  const s = session.data;
  const late = s?.arrival_deadline_at ? calculateLateMinutes(new Date().toISOString(), s.arrival_deadline_at) : 0;
  return <div className="space-y-4"><Card><CardHeader><CardTitle className="flex items-center justify-between"><span className="flex items-center gap-2"><Radio className="h-5 w-5" /> Festival performance session</span><Badge>{s?.status ?? "loading"}</Badge></CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-4"><div><p className="text-xs text-muted-foreground">Scheduled</p><p>{s?.scheduled_start_at ? new Date(s.scheduled_start_at).toLocaleString() : "—"}</p></div><div><p className="text-xs text-muted-foreground">Arrival deadline</p><p>{s?.arrival_deadline_at ? new Date(s.arrival_deadline_at).toLocaleTimeString() : "—"}</p></div><div><p className="text-xs text-muted-foreground">Stage call</p><p>{s?.stage_call_at ? new Date(s.stage_call_at).toLocaleTimeString() : "—"}</p></div><div><p className="text-xs text-muted-foreground">Lateness</p><p>{late} minutes</p></div></CardContent></Card>
  <Tabs defaultValue="prep"><TabsList className="grid grid-cols-4"><TabsTrigger value="prep">Preparation</TabsTrigger><TabsTrigger value="soundcheck">Soundcheck</TabsTrigger><TabsTrigger value="live">Live</TabsTrigger><TabsTrigger value="mobile">Mobile</TabsTrigger></TabsList><TabsContent value="prep" className="space-y-4"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Users className="h-4 w-4" /> Arrival</CardTitle></CardHeader><CardContent><pre className="whitespace-pre-wrap text-xs bg-muted p-3 rounded">{JSON.stringify(arrival.data ?? {}, null, 2)}</pre><Button className="mt-3" onClick={() => checkIn.mutate()} disabled={checkIn.isPending}>Check In</Button></CardContent></Card><ReadinessPanel readiness={readiness.data as any} /></TabsContent><TabsContent value="soundcheck"><Card><CardHeader><CardTitle>Soundcheck workflow</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p>Begin Soundcheck, capture issues, apply substitutions, record technical notes, then Complete Soundcheck. Critical unresolved issues must be resolved or explicitly accepted server-side.</p><Button variant="outline">Begin Soundcheck</Button><Button variant="outline" className="ml-2">Complete Soundcheck</Button></CardContent></Card></TabsContent><TabsContent value="live"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Music className="h-4 w-4" /> Performance control</CardTitle></CardHeader><CardContent className="space-y-2"><p>Current position: {s?.current_setlist_position ?? 0}; active song: {s?.active_song_position ?? "none"}.</p>{organiser ? <div className="flex flex-wrap gap-2"><Button>Call to Stage</Button><Button>Start Performance</Button><Button variant="outline">Start Song</Button><Button variant="outline">Complete Song</Button><Button variant="destructive">Cancel / No Show</Button></div> : <p className="text-muted-foreground">Performer view shows current song, next song, timing, encore and safe incident status only.</p>}</CardContent></Card></TabsContent><TabsContent value="mobile"><Card className="border-primary"><CardHeader><CardTitle className="flex items-center gap-2"><Clock className="h-4 w-4" /> Mobile session</CardTitle></CardHeader><CardContent className="space-y-3"><div className="text-2xl font-semibold">{s?.status ?? "scheduled"}</div><Button className="w-full" onClick={() => checkIn.mutate()}><CheckCircle2 className="h-4 w-4 mr-2" /> Check In</Button><p className="text-sm flex gap-2"><AlertTriangle className="h-4 w-4" /> Missing readiness items and incident alerts appear here.</p></CardContent></Card></TabsContent></Tabs></div>;
}
