export type PropertyOwnerType = "player" | "band" | "company" | "world";
export type PropertyStatus = "available" | "occupied" | "reserved" | "under_maintenance";
export type ListingStatus = "for_sale" | "for_rent" | "off_market";
export type PropertyCategory = "residential" | "commercial";
export type PropertyPermissionRole = "owner" | "occupant" | "partner" | "bandmate" | "guest" | "member" | "manager" | "visitor" | "employee" | "contractor";
export type PropertyUse = "player_residence" | "band_hq" | "company_office" | "studio" | "venue_office";

export type Money = { amountMinor: number; currencyCode: string };
export type PropertyTemplate = { id: string; city: string; district: string; category: PropertyCategory; type: string; quality: number; sizeSqm: number; rooms: number; bedrooms: number; capacity: number; monthlyCosts: Record<string, Money>; purchaseValue: Money; rentalValue: Money; maintenanceLevel: number; prestige: number; upgradePotential: number; storageCapacity: number; generationWeight?: number };
export type OwnershipRecord = { ownerType: PropertyOwnerType; ownerId: string; purchaseDate: string; purchasePrice: Money; endDate?: string };
export type Lease = { tenantType: Exclude<PropertyOwnerType, "world">; tenantId: string; monthlyRent: Money; deposit: Money; leaseStart: string; leaseEnd?: string; noticePeriodDays: number; furnished: boolean; utilitiesIncluded: boolean; status: "active" | "expired" | "notice_given" };
export type ValuationPoint = { date: string; marketValue: Money; reason: string };
export type Property = { id: string; templateId: string; city: string; district: string; category: PropertyCategory; type: string; quality: number; sizeSqm: number; rooms: number; bedrooms: number; capacity: number; status: PropertyStatus; listingStatus: ListingStatus; ownerType: PropertyOwnerType; ownerId: string; purchaseDate?: string; purchasePrice?: Money; occupantType?: PropertyOwnerType; occupantId?: string; officialUse?: PropertyUse; ownershipHistory: OwnershipRecord[]; lease?: Lease; condition: number; estimatedMarketValue: Money; valuationHistory: ValuationPoint[]; appreciationHistory: ValuationPoint[]; permissions: Record<PropertyPermissionRole, string[]>; storage: { used: number; capacity: number; reservedFor: string[] }; prestige: number; monthlyCosts: Record<string, Money>; upgrades: string[]; futureFinance?: { mortgageId?: string; insurancePolicyId?: string; securedLoanIds?: string[]; sharedOwnership?: unknown; auctionId?: string; repossessionCaseId?: string } };
export type FinanceJournal = { idempotencyKey: string; category: string; description: string; lines: Array<{ accountRole: string; direction: "debit" | "credit"; amountMinor: number; currencyCode: string }> };

const cloneMoney = (m: Money): Money => ({ ...m });
const addMoney = (items: Money[]) => items.reduce((a, m) => (a.currencyCode === m.currencyCode ? { ...a, amountMinor: a.amountMinor + m.amountMinor } : a), { amountMinor: 0, currencyCode: items[0]?.currencyCode ?? "USD" });
export const isPropertyJournalBalanced = (journal: FinanceJournal) => journal.lines.filter(l => l.direction === "debit").reduce((s,l)=>s+l.amountMinor,0) === journal.lines.filter(l => l.direction === "credit").reduce((s,l)=>s+l.amountMinor,0);

export function generateCityProperties(templates: PropertyTemplate[], countByTemplate: Record<string, number>, seed = "phase8a"): Property[] {
  let n = 0;
  return templates.flatMap((t) => Array.from({ length: countByTemplate[t.id] ?? 0 }, () => ({ id: `${t.city.toLowerCase()}-${t.district.toLowerCase().replace(/\W+/g, "-")}-${t.id}-${++n}`, templateId: t.id, city: t.city, district: t.district, category: t.category, type: t.type, quality: t.quality, sizeSqm: t.sizeSqm, rooms: t.rooms, bedrooms: t.bedrooms, capacity: t.capacity, status: "available" as const, listingStatus: t.category === "residential" ? "for_rent" as const : "for_sale" as const, ownerType: "world" as const, ownerId: seed, ownershipHistory: [], condition: 100, estimatedMarketValue: cloneMoney(t.purchaseValue), valuationHistory: [{ date: "2026-07-19", marketValue: cloneMoney(t.purchaseValue), reason: "initial_generation" }], appreciationHistory: [], permissions: { owner: [], occupant: [], partner: [], bandmate: [], guest: [], member: [], manager: [], visitor: [], employee: [], contractor: [] }, storage: { used: 0, capacity: t.storageCapacity, reservedFor: [] }, prestige: t.prestige, monthlyCosts: t.monthlyCosts, upgrades: [], futureFinance: {} })));
}

export function buyProperty(property: Property, buyer: { type: Exclude<PropertyOwnerType, "world">; id: string }, date: string, price = property.estimatedMarketValue): { property: Property; journal: FinanceJournal } {
  const record = { ownerType: buyer.type, ownerId: buyer.id, purchaseDate: date, purchasePrice: price };
  return { property: { ...property, ownerType: buyer.type, ownerId: buyer.id, purchaseDate: date, purchasePrice: price, status: "occupied", listingStatus: "off_market", ownershipHistory: [...property.ownershipHistory, record], permissions: { ...property.permissions, owner: [buyer.id] } }, journal: { idempotencyKey: `property-purchase:${property.id}:${buyer.id}:${date}`, category: "property_purchase", description: `Purchase of ${property.type} in ${property.city}`, lines: [{ accountRole: "buyer_cash", direction: "credit", amountMinor: price.amountMinor, currencyCode: price.currencyCode }, { accountRole: "seller_asset_disposal", direction: "debit", amountMinor: price.amountMinor, currencyCode: price.currencyCode }] } };
}

export function rentProperty(property: Property, tenant: { type: "player" | "band" | "company"; id: string }, lease: Omit<Lease, "tenantType" | "tenantId" | "status">): Property {
  return { ...property, status: "occupied", listingStatus: "off_market", occupantType: tenant.type, occupantId: tenant.id, lease: { ...lease, tenantType: tenant.type, tenantId: tenant.id, status: "active" }, permissions: { ...property.permissions, occupant: [tenant.id] } };
}

export function collectMonthlyRent(property: Property, period: string): FinanceJournal | undefined {
  if (!property.lease || property.lease.status !== "active") return undefined;
  const r = property.lease.monthlyRent;
  return { idempotencyKey: `property-rent:${property.id}:${period}`, category: "property_rent", description: `Monthly rent for ${property.type} (${period})`, lines: [{ accountRole: "tenant_cash", direction: "credit", amountMinor: r.amountMinor, currencyCode: r.currencyCode }, { accountRole: "landlord_rental_income", direction: "debit", amountMinor: r.amountMinor, currencyCode: r.currencyCode }] };
}

export function processRunningCosts(property: Property, period: string): FinanceJournal {
  const total = addMoney(Object.values(property.monthlyCosts));
  return { idempotencyKey: `property-running-costs:${property.id}:${period}`, category: "property_running_costs", description: `Maintenance, utilities, taxes and services for ${property.type}`, lines: [{ accountRole: "property_owner_cash", direction: "credit", amountMinor: total.amountMinor, currencyCode: total.currencyCode }, { accountRole: "property_service_expense", direction: "debit", amountMinor: total.amountMinor, currencyCode: total.currencyCode }] };
}

export function deteriorateProperty(property: Property, months = 1): Property { const condition = Math.max(0, property.condition - Math.ceil(property.monthlyCosts.maintenance.amountMinor / 10000) * months); return { ...property, condition, prestige: Math.max(0, property.prestige - (condition < 60 ? 1 : 0)) }; }
export function renovateProperty(property: Property, upgrade: { name: string; cost: Money; valueIncreaseBps: number; prestigeIncrease: number; conditionIncrease: number }): { property: Property; journal: FinanceJournal } { const marketValue = { ...property.estimatedMarketValue, amountMinor: Math.round(property.estimatedMarketValue.amountMinor * (1 + upgrade.valueIncreaseBps / 10000)) }; return { property: { ...property, condition: Math.min(100, property.condition + upgrade.conditionIncrease), prestige: property.prestige + upgrade.prestigeIncrease, estimatedMarketValue: marketValue, upgrades: [...property.upgrades, upgrade.name], valuationHistory: [...property.valuationHistory, { date: "2026-07-19", marketValue, reason: `renovation:${upgrade.name}` }] }, journal: { idempotencyKey: `property-renovation:${property.id}:${upgrade.name}`, category: "property_renovation", description: upgrade.name, lines: [{ accountRole: "owner_cash", direction: "credit", amountMinor: upgrade.cost.amountMinor, currencyCode: upgrade.cost.currencyCode }, { accountRole: "capital_improvement_asset", direction: "debit", amountMinor: upgrade.cost.amountMinor, currencyCode: upgrade.cost.currencyCode }] } }; }
export function moveResidence(from: Property | undefined, to: Property, playerId: string, cost: Money): { from?: Property; to: Property; journal: FinanceJournal } { return { from: from ? { ...from, occupantId: undefined, occupantType: undefined, officialUse: undefined, status: from.ownerType === "world" ? "available" : from.status } : undefined, to: { ...to, occupantType: "player", occupantId: playerId, officialUse: "player_residence", permissions: { ...to.permissions, occupant: [playerId] } }, journal: { idempotencyKey: `property-move:${playerId}:${to.id}`, category: "property_moving_cost", description: "Moving house costs", lines: [{ accountRole: "player_cash", direction: "credit", amountMinor: cost.amountMinor, currencyCode: cost.currencyCode }, { accountRole: "moving_supplier_income", direction: "debit", amountMinor: cost.amountMinor, currencyCode: cost.currencyCode }] } }; }
export function canAccessProperty(property: Property, actorId: string, role: PropertyPermissionRole) { return property.permissions[role]?.includes(actorId) || property.permissions.owner.includes(actorId); }
export function filterMarketplace(properties: Property[], f: Partial<{ city: string; district: string; type: string; availability: ListingStatus; maxPriceMinor: number; maxRentMinor: number; minSize: number; minPrestige: number }>) { return properties.filter(p => (!f.city || p.city === f.city) && (!f.district || p.district === f.district) && (!f.type || p.type === f.type) && (!f.availability || p.listingStatus === f.availability) && (!f.maxPriceMinor || p.estimatedMarketValue.amountMinor <= f.maxPriceMinor) && (!f.maxRentMinor || (p.lease?.monthlyRent.amountMinor ?? p.monthlyCosts.rent?.amountMinor ?? Infinity) <= f.maxRentMinor) && (!f.minPrestige || p.prestige >= f.minPrestige)); }
export function expireLeases(properties: Property[], onDate: string) { return properties.map(p => p.lease?.leaseEnd && p.lease.leaseEnd < onDate ? { ...p, lease: { ...p.lease, status: "expired" as const }, status: "available" as const, occupantId: undefined, occupantType: undefined } : p); }
